### ISSUE TITLE
materials 本地启动打开JS面板报错

### ISSUE THREAD

**Issue by sundi78634** [alibaba/lowcode-engine#100]
## **Describe the bug (required)** / **详细描述 bug（必填）**

lowcode-materials 库本地`npm run lowcode:dev`启动，点击左侧JS面板报错。

![image](https://user-images.githubusercontent.com/13900729/157415915-8048d6cd-a292-4117-994d-a9ed8cec618a.png)

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1. `npm run lowcode:dev`启动 lowcode-materials
2. 点击左侧**JS面板**

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
如[demo](https://alifd.alicdn.com/npm/@alilc/lowcode-demo@1.0.0/build/index.html) 中所示，打开源码面板，可进行编辑

---

## **Screenshots (optional)** / **bug 截图（可选）**
![image](https://user-images.githubusercontent.com/13900729/157417582-a0c364ba-3653-4503-afe9-89d7fcc11aee.png)
![image](https://user-images.githubusercontent.com/13900729/157417652-46144db8-867e-431f-aa5d-8803ab3d629a.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: 1.0.2-beta.1
 - AliLowCodeEngineExt version: 1.0.2-beta.1
 - Chrome version: 98.0.4758.109
 - material version: 1.0.2-beta.1

**Comment by alvarto** [comment]
`this.props.editor.get` 应该是旧版的源码编辑引用的 API，看看是不是工具链引用的版本不对？

**Comment by eternalsky** [comment]
> `this.props.editor.get` 应该是旧版的源码编辑引用的 API，看看是不是工具链引用的版本不对？

material 相关的需要 @mark-ck 来看一下。

**Comment by mark-ck** [comment]
JS 面板确实用的还是内部版，我处理下

**Comment by sundi78634** [comment]
> JS 面板确实用的还是内部版，我处理下

JS 面板下边的数据源有相似的问题。

**Comment by wssgchungang** [comment]
@mark-ck  请问下这个问题修复了吗 脚手架@alilc/element的js面板 也有一样的问题，数据源面板也有

**Comment by mark-ck** [comment]
fixed in @alifd/build-plugin-lowcode@0.2.0-beta.6
