### ISSUE TITLE
求教，查看教程，新建一个组件的时候有报错

### ISSUE THREAD

**Issue by cc8476** [alibaba/lowcode-engine#1000]
npm init @alilc/element your-material-demo
npm i
npm run lowcode:dev
上述命令正常

build-scripts start --config ./build.lowcode.js   执行后报错，如下截图
![image](https://user-images.githubusercontent.com/23565901/187871773-43006229-b4bd-45a5-ac60-c3e051ef1233.png)

本地信息：
window 10
npm 8.18.0
node 16.17.0
webpack  4.46.0

**Comment by eternalsky** [comment]
https://lowcode-engine.cn/docV2/funcv8#SIGYf

**Comment by liujuping** [comment]
注意：引擎提供的 cli 并未对 windows 系统做适配，windows 环境必须使用 [WSL](https://docs.microsoft.com/zh-cn/windows/wsl/install)，其他终端不保证能正常运行
