### ISSUE TITLE
如何设置画布节点选中状态？

### ISSUE THREAD

**Issue by flingyu** [alibaba/lowcode-engine#1001]
![image](https://user-images.githubusercontent.com/30229467/187879445-78a23332-173a-49de-a8cd-129422f2e29d.png)
期望：document加载完成之后默认选中根节点容器
通过project?.select('node_ocl6fsxjla1')去设置选中状态吗？

**Comment by yz1311** [comment]
```
project.getCurrentDocument()?.selection?.select(nodeId)
```

**Comment by flingyu** [comment]
project.onChangeDocument((node) => {
          project.onSimulatorRendererReady(() => {
                     node.selection.select(nodeId)
          })
})

**Comment by flingyu** [comment]
`
project.onChangeDocument((node) => {
       project.onSimulatorRendererReady(() => {
             node.selection.select(nodeId)
       })
})
`

**Comment by 1270791812** [comment]
请问下节点ID如何获取呢？

**Comment by 1270791812** [comment]
选中默认节点后，设置器面板未打开啊，可以自动打开吗？

**Comment by 1270791812** [comment]
> `project.onChangeDocument((node) => { project.onSimulatorRendererReady(() => { node.selection.select(nodeId) }) })`

选中默认节点后，设置器面板未打开啊，可以自动打开吗？
