### ISSUE TITLE
咨询：请问在渲染模式中的组件如何获取device信息

### ISSUE THREAD

**Issue by Forever8** [alibaba/lowcode-engine#1007]
在设计模式下可以通过simulatorHost获取device，但是单纯使用@alilc/lowcode-react-renderer渲染页面时，组件怎样获取device？

代码：
`
import ReactRenderer from '@alilc/lowcode-react-renderer';
<ReactRenderer
  className="lowcode-plugin-sample-preview-content"
  device="phone"
  schema={schema}
  components={components}
  appHelper={{
    requestHandlersMap: {
      fetch: createFetchHandler()
    }
  }}
/>
`

**Comment by liujuping** [comment]
这个是业务自己决定的，例如：
1.地址 A 是用于移动端的，device="phone"
2.地址 B 是 PC 端的，device=“pc”
3.地址pc/h5的，device根据屏幕宽度判断一下

**Comment by Forever8** [comment]
> 这个是业务自己决定的

@liujuping  感谢你的支持！

我在写一套支持响应式的物料，想在渲染器入口这里<ReactRenderer />根据设备类型传入不同的device，然后在组件内部读取这个device，来渲染正确的视图。

不知现在是否有接口能够支持到这个实现？

**Comment by liujuping** [comment]
这个值是放到 ConfigProvider 类似于这样的代码
```javascript
import ConfigProvider from '@alifd/next/lib/config-provider';
<ConfigProvider device={device}></ConfigProvider>
```
组件内部也是可以取到的，如何获取你可以根据这个代码研究一下先。

**Comment by oneQiu** [comment]
> > 这个是业务自己决定的
> 
> @liujuping 感谢你的支持！
> 
> 我在写一套支持响应式的物料，想在渲染器入口这里根据设备类型传入不同的device，然后在组件内部读取这个device，来渲染正确的视图。
> 
> 不知现在是否有接口能够支持到这个实现？

我是自己通过尺寸去写hooks判断的，如果用这种传递进来的方式判断的话，在页面发布以后的响应式不还是要自己内部逻辑吗？PS：我是使用者哈

我目前的方案，暂时用尺寸来判断
![image](https://user-images.githubusercontent.com/50658231/188421944-e79c98f7-f6fc-43c7-b131-22370d79eced.png)
![image](https://user-images.githubusercontent.com/50658231/188422146-7cf3ed88-2ad3-4210-8f19-9db5cdfd377b.png)
