### ISSUE TITLE
官方线上 demo 的场景 antd + formily 场景有问题，导致拉取到项目中出现相同问题

### ISSUE THREAD

**Issue by kevinbolton729** [alibaba/lowcode-engine#1008]
## **Describe the bug (required)** / **详细描述 bug（必填）**

拖动【组件库】中的【高级组件】的表格类组件，出现 h.Form.useInstance not function 的 Bug

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
1. 直接访问官方地址：https://lowcode-engine.cn/demo/antd-pro-with-formily.html
2. 左侧菜单中，选择【组件库】/【高级组件】，拖动【表格类】至模拟器则出现此 Bug

---

English version example：
3. Click on '....'
4. Scroll down to '....'
5. See error

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
希望正确渲染出【组件库 】/【高级组件】/【表格类】的各组件

---

## **Screenshots (optional)** / **bug 截图（可选）**
![image](https://user-images.githubusercontent.com/28046159/188371784-d3408d9a-b376-4494-a505-1edde6b7b6b7.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本 v1.0.11
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本  v1.0.3
 - Browser [e.g. chrome, safari] / 浏览器版本 Edge 版本 105.0.1343.27 (正式版本) (arm64)
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本 Nodejs v14.20.0

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by liujuping** [comment]
可以看一下 antd 场景是否可以复现，如果不能复现，是跟 formily 有关，可以去这边提问哈，https://github.com/seada-low-code/lowcode-ecology/tree/main/packages/formily-materials

**Comment by kevinbolton729** [comment]
> 可以看一下 antd 场景是否可以复现，如果不能复现，是跟 formily 有关，可以去这边提问哈，https://github.com/seada-low-code/lowcode-ecology/tree/main/packages/formily-materials

antd 场景刚才试了一下，是正常的并没有复现此问题。

**Comment by twinkle77** [comment]
我看下

**Comment by kevinbolton729** [comment]
> 我看下

我刚刚修改了 scenarios 目录下 antd+formily 场景的 asset.json 中的 @seada/formily-materials 和 @seada/antd-materials 的版本为 1.0.0-rc.12   则恢复正常，应该就是最近这2天最新的发布的 Bug
