### ISSUE TITLE
debug预览态提示“注入成功”，控制台“component is not found in components list”

### ISSUE THREAD

**Issue by dingyanhe** [alibaba/lowcode-engine#1009]
## 复现截图
![Hf8ShXUJ0A](https://user-images.githubusercontent.com/26290798/188383248-c5c15097-944a-4e51-9197-2142d4b1c99a.jpg)
![6PztPi9emt](https://user-images.githubusercontent.com/26290798/188383260-7602d0d3-8e68-445e-aa02-b89de510f583.jpg)
<img width="1085" alt="image" src="https://user-images.githubusercontent.com/26290798/188384289-d1fe5cd2-e7c0-40ca-9ea9-2a14189e0e42.png">
<img width="1083" alt="image" src="https://user-images.githubusercontent.com/26290798/188384349-7a04675a-e90a-459d-acfd-6779366c60f4.png">

## 复现流程与链接
- 初始化物料仓库
```
npm init @alilc/element your-plugin-name
```
![image](https://user-images.githubusercontent.com/26290798/188383433-9b15a6f7-1e6a-4c60-8cd0-ee0182a41a8e.png)

- 开启调试（见文档）
- https://lowcode-engine.cn/demo/basic-antd.html?debug
- 拖动`colorful-button`样例物料，保存，预览

## 期望结果
预览时本地物料注入也能有效。

## 环境信息

- 引擎版本 1.0.11
- ext 版本 1.0.3
- 物料
  - moment﹫2.24.0
  - lodash
  - iconfont-icons
  - ﹫ant-design/icons﹫4.7.0
  - antd﹫4.19.5
  - ﹫alifd/next﹫1.23.0
  - ﹫alilc/antd-lowcode-materials﹫1.0.6
  - your-plugin-name﹫0.1.0

**Comment by LeoYuan** [comment]
@eternalsky 帮忙看看这个~

**Comment by eternalsky** [comment]
文中所述的 demo 地址已经失效了，等价的新地址测试没有问题，建议将本地依赖都升级一下之后再看下。
