### ISSUE TITLE
inject插件的debug模式没有对hash路由模式兼容

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#1012]
场景：我的项目是用的hash路由，所以我在路由后面直接加?debug，没有生效，但是用引擎的demo是成功的

分析：在demo上是可以的，所以我觉得是路由模式不同导致的，可能是直接拿的location.search。查看了[源码](https://github.com/alibaba/lowcode-tools/blob/main/packages/lowcode-plugin-inject/src/utils.tsx#L34)以后发现确实如此，我需要把路由改成browser或者把?debug参数放在#前面

期望：希望也能支持一下hash后面这种情况（对这个iss没问题的话 我也可以自己提mr）

这是我自己项目用的时候会处理一下
![image](https://user-images.githubusercontent.com/50658231/188534564-9b287b65-0b7d-4b66-babd-5e96695f0b20.png)

![image](https://user-images.githubusercontent.com/50658231/188534089-4d26965e-14bc-4bb2-98a7-c90052e63ca6.png)

![image](https://user-images.githubusercontent.com/50658231/188534062-51ce4610-8d46-4794-afaa-e01dad5b6e25.png)

![image](https://user-images.githubusercontent.com/50658231/188534119-8aa002a9-470b-4953-a305-14994df45a62.png)

**Comment by liujuping** [comment]
这样试一下

http://localhost:3333/?debug#/xxx
