### ISSUE TITLE
出码包（alibaba/lowcode-engine(子目录：modules/code-generator)）npm run build报错

### ISSUE THREAD

**Issue by yinxuejiang** [alibaba/lowcode-engine#1016]
## **出码包（alibaba/lowcode-engine(子目录：modules/code-generator)）npm run build报错**

把出码源码（modules/code-generator），下载下来单独 npm run build报错

---

## **拷贝源码(modules/code-generator),安装依赖，npm run build, npm publish报错**

1. 拷贝源码(modules/code-generator)
2. 安装依赖，
3. npm run build 报错
4. 修改包名
5. npm publish报错
---

## **想了解低码引擎中使用，自定义源码的流程**

code-generator源码已经修改，怎么在低码引擎中使用

##**预期行为**
1. 可以正常编译
2. 可以正常发布

---

##  **bug 截图（可选）**
![image](https://user-images.githubusercontent.com/18732567/188603071-271d92b0-c66e-45bb-99f0-3c04b8c6ba31.png)

![image](https://user-images.githubusercontent.com/18732567/188603124-c6b1af1d-9a35-49ab-aeb5-4233ee96d697.png)

---

## ****请提供如下信息（必填）**

![image](https://user-images.githubusercontent.com/18732567/188604008-814fb40c-c0a8-4048-9d99-4533976d06d9.png)

## **更多额外信息（可选）**
把出码源码编译并发布，想低代码引擎中使用

**Comment by LeoYuan** [comment]
![image](https://user-images.githubusercontent.com/1195765/188816697-afb3c7ac-2835-4859-aca7-142d6bf1eddc.png)

依赖引擎顶层的 tsconfig.json 配置~

**Comment by yinxuejiang** [comment]
![image](https://user-images.githubusercontent.com/18732567/188843259-5f2f298b-13d7-48dd-a2fc-d6156327b49c.png)
修复上个问题，还是报错

**Comment by LeoYuan** [comment]
看报错自己解决一下，看报错信息都很明显~

既然都 fork 代码了，代码的工程化配置、代码逻辑还是得熟悉熟悉的~
