### ISSUE TITLE
自定义设置器，会引起node的nodeId变更

### ISSUE THREAD

**Issue by Sarali2022** [alibaba/lowcode-engine#1022]
## **Describe the bug (required)** / **详细描述 bug（必填）**
我们定义了一个设置器（VarSetter），用户可以定义变量，然后定义了一套配置用户可以在物料属性的上定义http请求，参数从（VarSetter中获取），选取变量是下拉框，lable是VarSetter设置的值，value为物料的nodeId。目前发现每次在设置中输入值的时候，物料的nodeId会变化。初步定位设置器在变更时会刷新nodeId的变更。
## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
设置器的代码
`import * as React from 'react';
import { Input } from '@alifd/next';
import { handleMaterial, createuuidAndmaterialFlag } from "../../_utils/utils"
import './index.less';

/**
 * 暂时不需要注入到schema,因为改标记可以通过变量shchema中的form表单获取
 * 所以，只需要保证唯一就行，这样表单通过setState设置时，key唯一。
 * 这里需要注意：复制模块的时候该表单的uuid可能相同，所以后期需要处理
 * @param field 
 */
export default class BlStringSetter extends React.PureComponent<any, any> {
  static displayName = 'StringSetter';

  changeInput = (val: any) => {
    const { onChange } = this.props;
    const newValue = createuuidAndmaterialFlag(val)
    onChange(newValue)
  }

  render() {
    const { placeholder, value } = this.props;
    const str = value || ''
    const newValue = handleMaterial(str)
    return (
      <Input
        size="small"
        value={newValue}
        placeholder={placeholder || '请输入标识'}
        onChange={(val: any) => this.changeInput(val)}
        style={{ width: '100%' }}
      />
    );
  }
}`

Steps to reproduce the behavior: / 详细复现步骤：
1、引擎
<img width="835" alt="image" src="https://user-images.githubusercontent.com/104294827/189027393-0eada11f-b5c8-4337-9af4-e7f70df20cad.png">
2、使用的原始物料fashion-ui上修改
3、在form表单的input上绑定BlStringSetter；
4、拖input到布局，检查下nodeId值，修改BlStringSetter绑定属性，再检查下nodeId值，发现两次值不一样。
---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by LeoYuan** [comment]
看你的自定义 Setter，应该没有问题~

猜测 fusion-ui 中的 Form 对拖入的表单项节点会重新构造，结合钉钉群里有同学回复：
```
主要的原理呢。给拖拽的组件，多嵌套了一层或者多层的父组件，在节点复制的过程，
先销毁后复制，id就不会重新生成了
先复制后销毁，id重复，就重新生成，旧id节点对应也就删除掉了
```

可以照着这个思路去看看 fusion-ui/Form 组件~

**Comment by Sarali2022** [comment]
是指用了 动态生成物料引起的吗？
<img width="692" alt="image" src="https://user-images.githubusercontent.com/104294827/190094505-6fe908ab-d0d6-438c-960d-6e055980d039.png">
