### ISSUE TITLE
可以单独修改某个物料的设计器辅助层吗？

### ISSUE THREAD

**Issue by liulangsven** [alibaba/lowcode-engine#1025]
## **Describe the bug (required)** / **详细描述 bug（必填）**
![1662621349708](https://user-images.githubusercontent.com/33243742/189059026-d324bef5-1f24-4fe7-b11e-8f4103c2df86.png)
如题 ： 比如这个表单容器的锁定按钮和复制按钮我不要 怎么单独配置 ？ 文档里的removeBuiltinComponentAction方法会影响所有的物料。

**Comment by oneQiu** [comment]
![image](https://user-images.githubusercontent.com/50658231/189256445-2aa1373c-664f-4ec0-81da-81cdc25f7f30.png)
这是不要复制的配置
