### ISSUE TITLE
绑定了 渲染条件 的组件很难搭建，这种情况怎么解

### ISSUE THREAD

**Issue by twinkle77** [alibaba/lowcode-engine#1026]
## **Describe the bug (required)** / **详细描述（必填）**

像 dialog 的渲染条件绑定了 this.state.visible，搭建时就只能手动加 this.state.visible 改成 true，是否有必要提供一个开关，在搭建时，有机会让用户将组件的 `渲染条件` 置为 `true`

<img width="309" alt="image" src="https://user-images.githubusercontent.com/17792166/189060145-4e05dfa2-d75c-4339-924b-0dd3009c2057.png">

<img width="372" alt="image" src="https://user-images.githubusercontent.com/17792166/189059302-7b9139b7-c7da-413c-ad85-91e936430f50.png">

**Comment by liujuping** [comment]
1.默认可以在页面设计的时候，过滤掉 visible 为 false 的情况，让所有情况下都是展示的，预览的时候才能看到 visible 的效果。

2.设计一个按钮，点击按钮可以切换是否让 visible 为 false 生效。

可以利用 addPropsTransducer 之类的实现。

**Comment by twinkle77** [comment]
> 1.默认可以在页面设计的时候，过滤掉 visible 为 false 的情况，让所有情况下都是展示的，预览的时候才能看到 visible 的效果。
> 
> 2.设计一个按钮，点击按钮可以切换是否让 visible 为 false 生效。
> 
> 可以利用 addPropsTransducer 之类的实现。

懂了 谢谢
