### ISSUE TITLE
引擎无法构建启动

### ISSUE THREAD

**Issue by hakuna-tata** [alibaba/lowcode-engine#103]
##  MAC 和  Windows 在根目录下 install 后， npm run build 都会报错

![image](https://user-images.githubusercontent.com/58654825/157480547-815f63b4-6139-4d7c-861d-d3b6adf91751.png)

难道 npm 源用的还都是阿里内部的么？？？

**Comment by LeoYuan** [comment]
看报错信息是在 types 在 build，单独到 types 下执行 npm run build 看看更详细的报错信息~

另外，你是按照 npm i && npm run setup && npm start 来启动的么？

**Comment by hakuna-tata** [comment]
解决了。tks  关掉哈

**Comment by LeoYuan** [comment]
> 解决了。tks  关掉哈

是没按照指引来启动吧？😃
