### ISSUE TITLE
物料组件内配置多个slot

### ISSUE THREAD

**Issue by Ronchan0805** [alibaba/lowcode-engine#1033]
## **Describe the bug (required)** / **详细描述 bug（必填）**
自定义物料组件时，想实现一个布局容器，该容器允许通过属性（例如NumberSetter设置器）动态设置插槽个数。目前只能通过在物料描述文件meta.ts中配置isContainer:true 设置一个插槽。

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
1. 按照搭建组件协议结构，配置组件的isContainer属性为true
![image](https://user-images.githubusercontent.com/74052977/189798533-0fa20918-d71b-47f3-9bd6-be3f05029cfd.png)
2. 此时在组件内的props中已能拿到一个children数组,内部包含的是一个slot DOM元素 （配置了isContainer为true后自动出现的，经测试，配置isContainer为false则在组件内props中拿到的children就会变成null）
![image](https://user-images.githubusercontent.com/74052977/189795621-61a0d226-778b-4224-93f0-4844b6ba5866.png)
3. 通过在自定义物料组件内解析渲染该children，就能生成一个布局组件
![image](https://user-images.githubusercontent.com/74052977/189796296-367f2dbf-2010-4f54-bbff-bb23274558f7.png)

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
 希望布局组件内能包含多个slot，最好能够直接通过属性进行配置

---

## **Screenshots (optional)** / **bug 截图（可选）**
 期望最终的结果是这样的
![image](https://user-images.githubusercontent.com/74052977/189797034-de1ed1b8-dbc4-4688-ade2-6f5682c43331.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
 npm init @alilc/element your-material-name, 使用官方提供的脚手架项目进行新组件的开发和调试

**Comment by Ronchan0805** [comment]
目前的一个想法是通过实现一个复合组件，里面用包含slot的行容器组件拼凑而成，最终在复合组件（布局组件）的属性中配置行容器个数？
但考虑到props的children是一个数组，是不是意味着可以直接配置slot DOM的个数呢？（目前只能生成一个）

**Comment by LeoYuan** [comment]
`isContainer: true` 其实算是插槽的一种特殊形态，即有一个在 children 位置的插槽，更广泛的插槽场景是自定义插槽数量和位置~

比如在组件 JSON 结构为 
```
{
  componentName: 'Xxx',
  props: {
    slotA: {
      type: 'JSSlot'
    },
    slotB: {
      type: 'JSSlot'
    }
  }
}
```

这时就会引擎会给 Xxx 组件传入两个插槽渲染函数，使用 slotA / slotB 是由 Xxx 组件自行决定的，比如：

```
// Xxx.render()
render() {
   <div>
      <div class="left">我在左边：{this.props.slotA()}</div>
      <div class="right">我在右边：{this.props.slotB()}</div>
  </div>
}
```

**Comment by Ronchan0805** [comment]
我自定义了一个设置器，在设置器的组件UI交互的回调方法里 根据官方文档提供的模型API 动态往组件里新增删除children节点。最终也实现了这一效果
