### ISSUE TITLE
希望defaultValue不影响生成的schema

### ISSUE THREAD

**Issue by mmmmmmmgo** [alibaba/lowcode-engine#1034]
如果A组件的a属性默认是false(源码里有false)，我开发meta.js时也会描述这个组件a属性默认是false。
但是生成的schema.json 是 { a:false }, 实际期望不要有a:false

**Comment by liujuping** [comment]
得去掉 meta.js 的属性描述

**Comment by mmmmmmmgo** [comment]
如果是Button按钮的size呢, 默认是middle

**Comment by liujuping** [comment]
这个设置了默认值 schema 就会生成，除非你自己过滤一下，参考 project.addPropsTransducer 这个 API。

**Comment by mmmmmmmgo** [comment]
> 这个设置了默认值 schema 就会生成，除非你自己过滤一下，参考 project.addPropsTransducer 这个 API。

稍微有点麻烦, 这样每个默认值不是false/undefined的地方都需要用这个api去设置默认值

**Comment by liujuping** [comment]
这个是你业务逻辑，只能自己适配了。

**Comment by mmmmmmmgo** [comment]
我可以自己设计一个defaultValue2, 然后在这个api里,统一地处理?

**Comment by liujuping** [comment]
可以尝试一下

**Comment by LeoYuan** [comment]
设计优雅一点的话，可以：
1. 在 [advanced.filters](https://github.com/alibaba/lowcode-engine/blob/3d176cb5345f9c712457f2d2545e03541ffcb585/packages/types/src/metadata.ts#L155) 上挂载当前组件的哪些属性可以被过滤掉；
2. 配合 addPropsReducer 来定制导出的 schema。addPropsReducer 中可以读取 advanced.filters，以及可以决定是在 'render'(编辑渲染态) 还是在 'save'(导出以供存储) 时钩子函数生效；

**Comment by eightHundreds** [comment]
抛开这个issue.
翻源码时, 发现一个地方,可能有问题
<img width="777" alt="图片" src="https://user-images.githubusercontent.com/18695431/191209538-9a3a91af-106d-4edf-8ccc-439759ae8ad0.png">

```
props: this.document.designer.transformProps(props, this, stage),
      ...this.document.designer.transformProps(_extras_, this, stage),
```
transformProps方法最后会调用addPropsTransducer.

这个地方调用了两次addPropsTransducer, 我猜测第二次是处理内部props时调用的, 但是addPropsTransducer的使用方无法区分当前处理的是组件本身的props还是低代码引擎内部的props

**Comment by eightHundreds** [comment]
> 这个设置了默认值 schema 就会生成，除非你自己过滤一下，参考 project.addPropsTransducer 这个 API。
我最终的做法

``` ts
 ctx.project.addPropsTransducer((props, node, ctx) => {
        const propsWithDefaultValue = getPropsWithDefaultValue(node.componentMeta);
        Object.keys(props).forEach((key) => {
          if (key in propsWithDefaultValue && propsWithDefaultValue[key] === props[key]) {
            delete props[key];
          }
        });
        return props;
      }, TransformStage.Save);
```
