### ISSUE TITLE
多页面出码插件（alibaba/lowcode-code-generator-demo）使用

### ISSUE THREAD

**Issue by yinxuejiang** [alibaba/lowcode-engine#1035]
### 问题1 出码插件 options参数如何拿的到
引擎内
 await plugins.register(CodeGenPlugin, { disableCodeGenActionBtn: true });

插件内
![image](https://user-images.githubusercontent.com/18732567/189902866-11c46635-a85f-40bb-a150-f2f48fffbece.png)

 options参数没有拿到

### 问题2 出码插件 对外暴露的方法如何在插件调用处拿到

怎么拿到 generateCode
![image](https://user-images.githubusercontent.com/18732567/189903248-ae30e2c3-800f-4630-a37d-5c7f5d22a050.png)

**Comment by liujuping** [comment]
辛苦分为三个 issue 提问，一个 issue 问多个问题不好跟踪和回答，这个就先关掉了。
