### ISSUE TITLE
通过antd标签进行切换页面，重新返回低代码引擎编辑器时，低代码引擎编辑器的内容未正常渲染，

### ISSUE THREAD

**Issue by Chuchudongren** [alibaba/lowcode-engine#1036]
我将编辑器引入项目，并通过标签页切换不同的低代码编辑器，当页面首次渲染的时候，编辑器正常渲染。
当我切换不同的标签页时，编辑器就不能正常的展示页面。并且，重新对插件进行注册并未生效。

于是我尽可能再页面加载的时候进行重新加载编辑器，但是编辑器的画面始终不能展示，只有首次刷新网页可以。使用开发者工具检查，发现首次刷新时，编辑器内部画面是通过iframe进行内嵌，并绑定到id为app的标签中渲染。可是当我切换不同的标签页，并未对网页进行刷新，iframe中的id为app的div标签并未加载出来，这也是造成画面不出现的原因。
这是第一次刷新的iframe标签，
![image](https://user-images.githubusercontent.com/85165276/190123634-698d4f1c-e848-43b6-8e08-3d4f95a8cc31.png)
这是再次刷新的iframe标签
![image](https://user-images.githubusercontent.com/85165276/190123421-652e97f6-c87f-48fa-a7d3-5930eb2889d8.png)

我分析原因是觉得我再次对编辑器进注册和初始化的时候并没有生效，导致编辑器不能正常加载。
我看demo中的编辑器，切换不同的场景是直接切换路由刷新页面。
是否可以，再同一个页面内，进行编辑器的销毁，并且重新加载编辑器展示不同的内容。

**Comment by liujuping** [comment]
目前还不支持单页切换，可以参考这个 issue https://github.com/alibaba/lowcode-engine/issues/178

**Comment by LeoYuan** [comment]
![image](https://user-images.githubusercontent.com/1195765/190622727-ab938b85-ec01-4216-9f59-9f9c9a8b90a0.png)

用 umi 3 + antd Tabs 没有复现你说的问题，我来回切 Tab 了~

所以说为什么要精确的复现步骤。。。

**Comment by sy296565890** [comment]
> ![image](https://user-images.githubusercontent.com/1195765/190622727-ab938b85-ec01-4216-9f59-9f9c9a8b90a0.png)
> 
> 用 umi 3 + antd Tabs 没有复现你说的问题，我来回切 Tab 了~
> 
> 所以说为什么要精确的复现步骤。。。

来回切换路由，即菜单项，即可复现

**Comment by LeoYuan** [comment]
写了个 DEMO 可以尝试下~

步骤：
1. 拉引擎分支 `feat/spa`，启动后，[配置代理](https://www.yuque.com/lce/doc/glz0fx)；
2. 下载 [lce-spa-umi-demo](https://github.com/LeoYuan/lce-spa-umi-demo)，安装依赖，启动后切换路由；

**Comment by a153884673** [comment]
> 写了个 DEMO 可以尝试下~
> 
> 步骤：
> 
> 1. 拉引擎分支 `feat/spa`，启动后，[配置代理](https://www.yuque.com/lce/doc/glz0fx)；
> 2. 下载 [lce-spa-umi-demo](https://github.com/LeoYuan/lce-spa-umi-demo)，安装依赖，启动后切换路由；

请问下怎么集成到已有的umi3+antd pro中呢
