### ISSUE TITLE
调试物料 提示注入成功，画布上不能展示该组件，显示Component Not Found。

### ISSUE THREAD

**Issue by ChiZng** [alibaba/lowcode-engine#1037]
## **详细描述 bug**
调试物料 提示注入成功，画布上不能展示该组件，显示Component Not Found。控制台提示 base.js:500 ColorfulInput component is not found in components list。

---

##  **如何复现 bug？**

Steps to reproduce the behavior: / 详细复现步骤：
1. 初始化物料仓库，选择react-组件库
 npm init @alilc/element your-material-name
2. 根据文档修改build.lowcode.js
 ```typescript
const { library } = require('./build.json');

module.exports = {
  alias: {
    '@': './src',
  },
  plugins: [
    '@alifd/build-plugin-lowcode',
    [
      '@alilc/build-plugin-alt',
      {
        type: 'component',
        inject: true,
        library,
        // 配置要打开的页面，在注入调试模式下，不配置此项的话不会打开浏览器
        // 支持直接使用官方 demo 项目：https://lowcode-engine.cn/demo/index.html
        openUrl: 'https://lowcode-engine.cn/demo/basic-antd.html?debug',
      },
    ],
  ],
};
```
3. 启动调试  npm run lowcode:dev
4. 官方demo的画布中显示组件注册成功。但是把colorful-button组件或者colorful-input组件拖到画布上不能渲染。显示Component Not Found。控制台提示 base.js:500 ColorfulInput component is not found in components list。

## **预期行为（必填，非常重要）**
本地物料注册成功后就应该能正常使用。

---

## **bug 截图（可选）**
截图：
![1](https://user-images.githubusercontent.com/27946984/190159173-d3153c94-b21e-4a70-b24e-8554bc014933.png)

![2](https://user-images.githubusercontent.com/27946984/190159199-b45a1afa-c4c8-4baa-8d57-7ee2234e0fe6.png)

![3](https://user-images.githubusercontent.com/27946984/190159350-4d876d11-db9b-4139-a6b2-f096a302170d.png)
![4](https://user-images.githubusercontent.com/27946984/190159351-4f09acdf-11fb-404d-911e-a671ecd656c0.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
使用的官方demo。
物料库在lowcode:dev时 报了一个 Error: Cannot find module 'moment'。 安装了一个"moment": "2.24.0"。
其余没有任何修改

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

**Comment by LeoYuan** [comment]
控制台还有一个报错，是组件代码运行出错么？

**Comment by eternalsky** [comment]
```js
[
      '@alifd/build-plugin-lowcode',
      {
        library,
        engineScope: "@alilc"
      },
    ]
```

build-plugin-lowcode 需要这样配置

**Comment by LeoYuan** [comment]
@eternalsky 现在模板是不是默认加上 engineScope alilc 呀？

**Comment by ChiZng** [comment]
@eternalsky 按照新的文档配置可以了。感谢
