### ISSUE TITLE
怎么让物料在左侧物料面板中不显示

### ISSUE THREAD

**Issue by lavyun** [alibaba/lowcode-engine#1044]
我有一个默认的根布局组件，我不希望他在物料面板中展示出来，类似于官方demo中的 NextPage 组件，请问下有没有办法解决？
![image](https://user-images.githubusercontent.com/22797898/190403188-2eda3e5d-3ba2-4bd1-b998-781336a51546.png)

**Comment by Dogtiti** [comment]
`meta.js` 中配置`hidden:true`

**Comment by lavyun** [comment]
谢谢，可以了，希望能完善到物料协议文档中

**Comment by 12mubai** [comment]
@lavyun 具体是在哪里配置呀？遇到了同样的问题
