### ISSUE TITLE
物料的 props 里 condition 设为 false 会影响 schema、组件内的值，希望仅在右侧设置面板不展示

### ISSUE THREAD

**Issue by ImSwordTooth** [alibaba/lowcode-engine#1045]
## **Describe the bug (required)** / **详细描述 bug（必填）**
props `condition` 设为 false 时，schema 里直接没有这个 props 了，组件内拿到的也是 undefined。   
我理解 `condition` 应该只是隐藏某个不想让用户看到的配置项，比如 id 等。
或者有没有其他配置可以做到。

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

**meta.ts**
两个 props 都设置了初始值，拖拽组件到画布中时会自动获取节点的 id。
id 设置了 condition 为 false，为了对比，component_id_2 没有设置。

第三个 props 是我做的一些尝试，在官方的 StringSetter 基础上自己重构了一下，加了个 disabled 参数。
```javascript
{
  "props": [
    {
      "title": "component_id_1,
      "name": "component_id_1",
      "setter": "StringSetter",
      "condition": () => false,
      "defaultValue": (node) => {
         return node.getNode().id
      }
    },
    {
      "title": "component_id_2",
      "name": "component_id_2",
      "setter": "StringSetter",
      "defaultValue": (node) => {
         return node.getNode().id
      }
    },
    {
      "title": "disabledInputValue",
      "name": "disabledInputValue",
      "setter": {
        "componentName": "StringSetter",
        "props": {
          "disabled": true
        }
      },
      "defaultValue": (node) => {
         return node.getNode().id
      }
    }
  ]
}
```

**schema**
![image](https://user-images.githubusercontent.com/43266605/190539174-c84f7707-88a2-45a8-82e8-d67c370b5ad3.png)
![image](https://user-images.githubusercontent.com/43266605/190539492-f4ee5f37-41a0-4001-8c63-b3419ef06802.png)

**组件内**
![image](https://user-images.githubusercontent.com/43266605/190539296-f10e402d-4412-4b97-b06a-a1a2cfb9d75f.png)

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
预期 condition 只影响属性的展示，不要影响值本身。
另外第三个 disabledInput 的 props 只有第一次有值，再拖一个，也拿不到 id 值，刷新页面后重置第一次可用的状态。

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: 1.0.14
 - AliLowCodeEngineExt version: ^1.0.3
 - Browser: chrome

**Comment by tsheng** [comment]
遇到相同的问题了，condition的本意应该只是影藏属性配置，不应该让schema中的对应字段丢失了。

**Comment by LeoYuan** [comment]
嗯嗯，正在看这个问题了~

可以尝试在 snippets 里把属性默认值加上，可以暂时绕开这个问题~

**Comment by ImSwordTooth** [comment]
> 嗯嗯，正在看这个问题了~
> 
> 可以尝试在 snippets 里把属性默认值加上，可以暂时绕开这个问题~

好像还是没有修复？
`condition: () => false` 的 props，即使指定了默认值（defaultValue），也没有在 schema 里显示

**Comment by LeoYuan** [comment]
![image](https://user-images.githubusercontent.com/1195765/196361533-09250b20-9d1f-46b0-956a-7627d519d79a.png)

我这么测试是 OK 的~

**Comment by ImSwordTooth** [comment]
> ![image](https://user-images.githubusercontent.com/1195765/196361533-09250b20-9d1f-46b0-956a-7627d519d79a.png)
> 
> 我这么测试是 OK 的~

一样的代码，schema 里的结果是这样的：
![image](https://user-images.githubusercontent.com/43266605/196362775-7e219f65-9751-4b91-bbc3-d762d6f4a5b7.png)

**Comment by LeoYuan** [comment]
![image](https://user-images.githubusercontent.com/1195765/196365534-8a8b9018-6041-405a-b86e-ebda87e602c5.png)

你自己再检查检查吧，比如引擎版本号，组件重新拖入了吗？等等~

**Comment by ImSwordTooth** [comment]
试了很多次，发现是`defaultValue: () => '123'`的结果和你那边一致，setter.initialValue的行为和我截图里的一致。

终归是解决了，感谢支持🌹

**Comment by LeoYuan** [comment]
```
// 目前存在 defaultValue/initialValue 配置的地方
{
  name: xxx,
  title: xxx,
  defaultValue: <prop 的 默认值>,
  setter: {
    componentName: xxxx,
    initialValue: <SetterConfig 里定义的 defaultValue ？>
    props: {
      xxx: xxx,
      defaultValue: <Setter 对应 React 组件接收的 defaultValue>
    }
  }
}
```

```
defaultValue = setterProps.defaultValue || prop.defaultValue;

initialValue = setter.initialValue || defaultValue;
```

可以对照一下字段以及优先级~

**Comment by ImSwordTooth** [comment]
好的，这个很有用，谢谢~
