### ISSUE TITLE
Question: 请问画布上拖拽节点的时候，可以拖动元素本身，而不是使用DragGhost吗？

### ISSUE THREAD

**Issue by ICMI** [alibaba/lowcode-engine#1046]
咨询问题：如题

图片演示：
![image](https://user-images.githubusercontent.com/7451866/190541614-26208353-ab6e-4e00-b941-ef4611fa3788.png)

**Comment by LeoYuan** [comment]
理论上可以通过 drag-ghost 定制成任何样子，不过好像还没开放 drag-ghost 的 API😃

**Comment by ICMI** [comment]
但我不想拖动的时候拖动 drag-host，就是拖动的组件本身，组件也能随着拖动更新位置。

然后就有另一个问题，我们的这个组件是可以重叠放的吗，还是只能放容器里，或和组件一起在同一层排布。

有啥思路
