### ISSUE TITLE
拖拽两个简单组件，不接入数据。只是单纯组件，生码后的代码 无法运行

### ISSUE THREAD

**Issue by Zhzxiansheng** [alibaba/lowcode-engine#1051]
## 拖拽两个简单组件，不接入数据。只是单纯组件，生码后的代码 无法运行
![image](https://user-images.githubusercontent.com/22702616/190600628-0af23e11-b19b-43c5-ac1d-faddf0cb0849.png)

---

## 从Demo中拖拽两个组件，如图所示，然后出码并运行
![image](https://user-images.githubusercontent.com/22702616/190600852-6b789671-b5f3-4010-b364-d28102864fdd.png)
npm install
npm run start
![image](https://user-images.githubusercontent.com/22702616/190600628-0af23e11-b19b-43c5-ac1d-faddf0cb0849.png)

## version
node 16.17.0
npm 8.15.0

**Comment by wdxia** [comment]
俺的也跑不起来

**Comment by huangapple** [comment]
跑不起来+1

**Comment by JackLian** [comment]
node换14.17试试

**Comment by huangapple** [comment]
@JackLian 
node v14.17.6
npm 6.14.15 
还是不行， 报错也是一样的。

**Comment by huangapple** [comment]
把  react-sortablejs 限定在版本 6.0.3 是没问题， 最新的 6.1.4会报错。

但npm start没报错了， 但有一些警告。
![image](https://user-images.githubusercontent.com/10572028/195523262-73157fd1-43bf-4445-b971-e3ce57e7bfc1.png)


然后 项目在浏览器里是白屏的。
打开控制台有报错
![image](https://user-images.githubusercontent.com/10572028/195523185-a30b22c9-2e19-4b67-8d89-24789b116aef.png)

**Comment by eternalsky** [comment]
这个是要升级 alifd/next 的版本

**Comment by huangapple** [comment]
@eternalsky 大兄弟， 能否帮忙在demo修复一下， 这个问题所有使用现版本的demo都会遇到的。

**Comment by eternalsky** [comment]
@Zhzxiansheng 的问题只要本地更新一个 next 的版本即可解决，不需要其他修复，其他问题，请另起 issue 讨论，就不混在一起了。
