### ISSUE TITLE
物料开发中，在meta文件使用了advanced属性后，该组件使用设置器或者拖入组件，都无法触发实时重新刷新渲染。

### ISSUE THREAD

**Issue by 1377023219** [alibaba/lowcode-engine#1058]
## **Describe the bug (required)** / **详细描述 bug（必填）**
物料开发中，在meta文件使用了advanced属性后，该组件使用设置器或者拖入组件，都无法触发实时重新刷新渲染。

我们最开始以为是我们写错了什么代码，但是我们重新拉取了官网推荐的这个项目https://github.com/Dogtiti/next-pro-lowcode-materials.git，仅在原来meta的基础上添加了一行：advanced: {}，也出现了这个问题。

我们这个物料从6月份就开始开发，上周五出现了这个问题，期间我们没有更新或者添加过其他相关的依赖库
---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
![image](https://user-images.githubusercontent.com/36667646/190945223-8dd90c65-0e72-46d3-88c8-9efe9f586b85.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.6] / 低代码引擎版本 【--------------------这里，我尝试修改依赖的引擎版本，0.11，0.14，都有这个问题】
 - AliLowCodeEngineExt version: [e.g. 1.0.4] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by 1377023219** [comment]
之前advanced属性一直没问题，也没有再改动，后来出现了问题，现在目前排除是用了advanced属性。

而在官方推荐的这个项目github.com/Dogtiti/next-pro-lowcode-materials.git，仅在原来meta的基础上添加了一行：advanced: {}，也出现了这个问题。

结论：应该不是我改错了什么东西，而且之前没问题，是不是最近官方更新了什么代码导致的

**Comment by liujuping** [comment]
物料是在 DEMO 中运行的嘛？

**Comment by liujuping** [comment]
物料是在 DEMO 中运行的嘛？

**Comment by 1377023219** [comment]
> 物料是在 DEMO 中运行的嘛？

@liujuping  不是，直接使用npm run lowcode:dev

记得星期五简单试了一下，build放demo里，好像就没有问题。

**Comment by liujuping** [comment]
那可以先用 demo 来进行调试，本地调试的环境好像有点问题，之前有一个 issue 反馈了，我们先看看问题原因，
demo 调试：https://www.yuque.com/lce/doc/ulvlkz

**Comment by liujuping** [comment]
更新一下 @alifd/build-plugin-lowcode@latest 的版本

**Comment by 1377023219** [comment]
@liujuping 
![image](https://user-images.githubusercontent.com/36667646/191155776-994f2b2b-42ee-4fe7-bbca-c6d80e845711.png)
![image](https://user-images.githubusercontent.com/36667646/191155819-017a8a99-d004-4320-a020-2d0be6d7c8d2.png)
已经更新，但是问题依旧

**Comment by Ronchan0805** [comment]
我也遇到了同样的问题，去掉advanced就可以了，，，

**Comment by liujuping** [comment]
@alifd/build-plugin-lowcode@0.3.6 fixed

**Comment by 1377023219** [comment]
@liujuping 已更新，问题已经解决，感谢
