### ISSUE TITLE
官网打开报错。如下。

### ISSUE THREAD

**Issue by kbb522** [alibaba/lowcode-engine#1066]
## **bug 描述**
打开 https://lowcode-engine.cn/demo/index.html 官网报错。网页无法正常显示。

---

## **如何复现 bug？**
1. 打开 https://lowcode-engine.cn/demo/index.html

---

## **bug 截图**
![1663654814493](https://user-images.githubusercontent.com/16772592/191182082-a7829dc1-98fa-498b-bb00-128bcb24c96a.png)

![1663739899730](https://user-images.githubusercontent.com/16772592/191425707-dfc6953c-f3ba-4e9f-86d3-276c5b7f1241.png)

**Comment by liujuping** [comment]
可以看看其他人有没有访问报错，目前我们访问都是正常的，所以没法复现问题。

**Comment by LeoYuan** [comment]
检查一下 DevTools 的 Network，大概率你有资源访问 404 了~
