### ISSUE TITLE
使用 react 的方式初始化的时候， o.skeleton.buildFromConfig 报错

### ISSUE THREAD

**Issue by leoner** [alibaba/lowcode-engine#107]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

https://lowcode-engine.cn/doc?url=start-with-lce

使用 用 skeletonCabin.Workbench 方式初始化 

```
import React, { useState, useEffect } from 'react'
import { plugins, common, skeleton , project } from '@alilc/lowcode-engine'

// 此 schema 参考 demo 中的默认 schema 书写
import userSchema from './schema.json'

export default function EditorView() {
  /** 插件是否已初始化成功，因为必须要等插件初始化后才能渲染 Workbench */
  const [hasPluginInited, setHasPluginInited] = useState(false)

  useEffect(() => {
    plugins.init().then(() => {
      setHasPluginInited(true)
    }).catch(err => console.error(err))
  }, [])
  
  useEffect(() => {
    project.importSchema(userSchema)
  }, [userSchema])

  return hasPluginInited && (
      <common.skeletonCabin.Workbench
        skeleton={skeleton}
      />
    )}
  )
}
```

## **Screenshots (optional)** / **bug 截图（可选）**

![image](https://user-images.githubusercontent.com/546535/157577749-7800ad49-e219-428c-bbd5-455f7c07be16.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**

 AliLowCodeEngine  v1.0.1-beta.0 
AliLowCodeExt  v1.0.2-beta.2

**Comment by leoner** [comment]
![image](https://user-images.githubusercontent.com/546535/157577998-da29470c-2e77-4af4-ba56-84d1b57e904a.png)

```
  useEffect(() => {
    project.importSchema(userSchema)
  }, [userSchema])
```
如果加上这个， 还会有 open 这个错误

**Comment by leoner** [comment]
希望也能顺便给一个完整的 react 的例子， 毕竟现在项目大部分都是基于 react 呀。 

或者能把这个初始化方式再给包装下， 可以包装一个完整的 react 组件呀。

**Comment by alvarto** [comment]
> 希望也能顺便给一个完整的 react 的例子， 毕竟现在项目大部分都是基于 react 呀。

事实上 Demo 项目就是一个完整的 React 的例子，相对来说是一个更简单的使用方式。https://github.com/alibaba/lowcode-demo/blob/main/src/index.ts

但是你走的是自己项目自定义渲染的链路，因此是更高阶的功能，只有在需要插件和 redux 联动之类的情况更适用。

> 或者能把这个初始化方式再给包装下， 可以包装一个完整的 react 组件呀。

完整的 react 组件就是 `common.skeletonCabin.Workbench`，但是资产包和 schema 定义都是没有必要再封装的，各个业务方的获取方式都不太一样。

**Comment by leoner** [comment]
https://github.com/alibaba/lowcode-engine/blob/main/packages/shell/src/skeleton.ts

https://github.com/alibaba/lowcode-engine/blob/main/packages/editor-skeleton/src/skeleton.ts

还不清楚这两个区别， 但是报错的地方引用到的 skeleton 的对象是 shell 这个模块的， 理论上应该是 editor-skeleton 的

**Comment by LeoYuan** [comment]
已经差不多搞定了，待会儿给你个 beta 版本？或者直接给你分支？

**Comment by leoner** [comment]
辛苦了， 那帮忙发一个 beta 版本吧。 我好引用? 

import { plugins, common, skeleton, project} from '@alilc/lowcode-engine'

就是 只需要应用 @alilc/lowcode-engine 这个就好了是吧。

**Comment by LeoYuan** [comment]
@alilc/lowcode-engine@1.0.3-beta.0

**Comment by leoner** [comment]
@LeoYuan 就是第二个错误好像还没有修复。 

![image](https://user-images.githubusercontent.com/546535/157808321-a21602cf-1e16-47fc-a3c4-7ac7993fbbb4.png)

**Comment by LeoYuan** [comment]
参考一下这个文件的写法：https://github.com/alibaba/lowcode-demo/pull/5/files#diff-7af53eed249f4d7a8da743f852217941dda24e8fdb7a28c31d0ccac70efe3af6

open 为空我看了下逻辑应该是 componentsTree 为空数组，应该是 userSchema 的数据结构不对~ 参考：https://github.com/alibaba/lowcode-engine/blob/4f4ac5115d18357a7399632860808f6cffc33fad/packages/designer/src/project/project.ts#L85

**Comment by leoner** [comment]
![image](https://user-images.githubusercontent.com/546535/157815075-dd18ee91-341f-4bef-8a82-2b5467753b22.png)

是这个? 

我这个 schema 就是拿的 scema.json，可能请求的方式不一样， 我也通过 request 的方式获取下。

**Comment by leoner** [comment]
https://github.com/alibaba/lowcode-demo/blob/main/public/schema.json

我应该就是直接用的这个 json, 应该还是不行。

就是直接用这个 json 可以？

**Comment by leoner** [comment]
额， 应该是例子误导了，
``` {
      componentsTree: [schema],
      componentsMap: material.componentsMap,
      version: '1.0.0',
      i18n: {},
    }
```

嗯， 那需要手动 componentsTree 加上这个数组，就不报错了

**Comment by leoner** [comment]
![image](https://user-images.githubusercontent.com/546535/157816662-eedea546-2f3b-44c2-ae84-0357d54f25f4.png)

出来了， 但是没有东西， 感觉可能初始化还是少东西呀， 那看来用这个方式初始化的时候， 是不是还需要做好多事情呀， 不是简单的只是加载下 schema 就好了吧。 
```
<common.skeletonCabin.Workbench
      skeleton={skeleton}
    />

````

**Comment by LeoYuan** [comment]
对的，init 内部逻辑包括（但不限于）：
1. 传递 options 并设置 config 对象；
2. 传递 preference 并设置 plugins 入参；
3. 初始化 Workbench；

init 逻辑：https://github.com/alibaba/lowcode-engine/blob/d5c3ca1068ce2c2140980bd059d0da333574dc34/packages/engine/src/engine-core.ts#L182-L215

拆解后的逻辑：https://github.com/alibaba/lowcode-demo/blob/72b8ff7cd416d1331e6f24bf4009c39466f190a7/src/index-custom.tsx#L20-L54

拆解后的好处是将 ReactClass 暴露出来，便于自己去封装数据流逻辑，缺点是麻烦，目前集团内只听说过一例这样拆解用的~

**Comment by leoner** [comment]
就是发现这个模块 node_modules/@alilc/lowcode-plugin-simulator-select/lib/index.js

![image](https://user-images.githubusercontent.com/546535/157834736-156d571f-99d0-43db-ae79-78be3f5adb6b.png)

![image](https://user-images.githubusercontent.com/546535/157834803-07073f8b-eaa6-40f6-8f6a-e48c5f0b3f27.png)


@LeoYuan 帮忙看看 lowcode-plugin-simulator-select/ 是不是这个插件的引用有问题哈。

**Comment by leoner** [comment]
感觉用  umi 把这个模块配置到一个页面中还挺复杂， 看来还是走单独运行的方式好了。

**Comment by LeoYuan** [comment]
从根上得改插件本身的代码 @金禅
短期内可以通过把这个externals配成跟alifc的一样，参考下demo仓库的build.json

发自我的iPhone
