### ISSUE TITLE
@alilc/lowcode-utils的buildComponents第三个参数 - 函数 有实现吗

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#1073]
![image](https://user-images.githubusercontent.com/50658231/191437226-597f29e2-3938-4281-ab76-214e264fb3c1.png)
![image](https://user-images.githubusercontent.com/50658231/191437381-13f30386-970f-4bae-96d0-003476bc241c.png)

好像被没有触发这个事件

**Comment by liujuping** [comment]
可以看下这里的源码，不是所有资产包都会走到这个逻辑的。

![image](https://user-images.githubusercontent.com/11935995/191918590-104e4e00-5b8a-4fac-8143-81f52341a0bb.png)
