### ISSUE TITLE
如何把组件树(componentsTree)中的某children组件设置为根组件，从而渲染在大纲树顶端和画布最外部容器。。。

### ISSUE THREAD

**Issue by supersoulsoul** [alibaba/lowcode-engine#1077]
![image](https://user-images.githubusercontent.com/38419476/191692609-fdaee4da-a431-4dbd-9463-51ea5fe97e26.png)

![image](https://user-images.githubusercontent.com/38419476/191692575-cf64c899-e11c-423e-91c5-c9bd3bc891cf.png)
步骤：
1、打开宜搭表单设计器，随便拖入表单元素
2、打开隐藏的schema面板查看schema 数据结构
3、发现用户设计的真实数据是包裹在 Page -> RootContent -> FormContainer -> children中
4、得出结论：大纲树中的顶端组件和画布最外层容器都是 FormContainer 组件 ，而低代码引擎demo中渲染的根节点是Page组件
期望：
1、基于低代码引擎和demo，实现如宜搭的表单设计器结构。即：可以将children中的组件渲染在大纲树顶端，成为画布最外层容器

**Comment by JackLian** [comment]
这个自行定制大纲树插件即可

**Comment by LeoYuan** [comment]
有个 focusNodeSelector，我在其他 issue 回答过，可以搜下

**Comment by supersoulsoul** [comment]
> 

![image](https://user-images.githubusercontent.com/38419476/191888787-79035a31-46f1-4c68-960b-fa928f052254.png)
在引擎源码中用this.designer.editor.set()设置，是可以实现的。但是在外部用config.set()无法实现。

**Comment by supersoulsoul** [comment]
> 有个 focusNodeSelector，我在其他 issue 回答过，可以搜下

![image](https://user-images.githubusercontent.com/38419476/191889062-01cd1af9-e1fc-4493-a053-5ca0154e6d1e.png)
在引擎源码中用this.designer.editor.set()设置，是可以实现的。但是在外部用config.set()无法实现。

**Comment by liujuping** [comment]
升级引擎到 1.0.15
