### ISSUE TITLE
组件的事件没有组册到事件绑定面板之中

### ISSUE THREAD

**Issue by posuihushui** [alibaba/lowcode-engine#108]
demo项目不支持内置事件，组件的事件没有组册到事件绑定面板之中，这样无法弹框
下图为demo项目的事件面板
![image](https://user-images.githubusercontent.com/24692874/157578512-ef94ab25-ec6b-4c9e-92b6-3e2200e41b8c.png)

下图为宜搭项目的事件面板
![image](https://user-images.githubusercontent.com/24692874/157578633-a36cb141-d3b5-4a8e-94db-654b714a4da8.png)

**Comment by alvarto** [comment]
> demo项目不支持内置事件，组件的事件

**Comment by posuihushui** [comment]
@alvarto 是弹框哈

**Comment by LeoYuan** [comment]
假如问的是为啥两个事件绑定弹框不一样，本来引擎的设计就是「以协议为根本，上层灵活实现」的理念，宜搭或者其他平台完全可以自定义实现，demo 中的更多是示意性的参考实现~

假如问的是绑定不了事件，建议还是给出重现步骤~

**Comment by posuihushui** [comment]
@LeoYuan  绑定不了内置事件

**Comment by hzd822** [comment]
这一个版本时间绑定暂时不支持内置事件，弹框请选择"对话框"组件
