### ISSUE TITLE
数据源面板新建提示Cannot read properties of null (reading 'createVoidField')

### ISSUE THREAD

**Issue by zoomwang** [alibaba/lowcode-engine#1084]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
1.打开数据源面板
2.点击新建，提示：Cannot read properties of null (reading 'createVoidField')

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by zoomwang** [comment]
@alilc/lowcode-plugin-datasource-pane版本是1.0.6

**Comment by liujuping** [comment]
@twinkle77 辛苦帮忙看看这个问题。

**Comment by zoomwang** [comment]
![image](https://user-images.githubusercontent.com/8100241/192241743-560e2cbb-b64f-4d48-aee8-42e226dc237a.png)

**Comment by zoomwang** [comment]
![image](https://user-images.githubusercontent.com/8100241/192246324-078aec9a-17b0-4a10-8ea4-18be4e6d8468.png)

**Comment by iPortNe** [comment]
遇到相同问题，新建和编辑数据源都会出现这个问题。

**Comment by twinkle77** [comment]
> 遇到相同问题，新建和编辑数据源都会出现这个问题。 使用的是lowcode-demo 1.0.27的默认依赖

我看下

**Comment by twinkle77** [comment]
@iPortNe @zoomwang  
重新 clone 了最新 lowcode-demo ，没有复现这个问题

从图片看是 formily 的报错

想确认下，你们项目是不是也依赖  formily，尝试更新下 formily 的版本 ？

**Comment by alex921131958** [comment]
遇到了相同的问题
<img width="814" alt="image" src="https://user-images.githubusercontent.com/33477787/204538107-657734ec-1429-48af-ae44-ff5b62945fe1.png">
依赖版本
"@alifd/next": "^1.19.4",
    "@alifd/theme-design-pro": "0.x",
    "@alilc/lowcode-datasource-fetch-handler": "^1.0.1",
    "@alilc/lowcode-engine": "1.0.12",
    "@alilc/lowcode-plugin-code-editor": "^1.0.3",
    "@alilc/lowcode-plugin-components-pane": "^1.0.3",
    "@alilc/lowcode-plugin-datasource-pane": "^1.0.5",
    "@alilc/lowcode-plugin-inject": "^1.1.1",
    "@alilc/lowcode-plugin-manual": "^1.0.3",
    "@alilc/lowcode-plugin-schema": "^1.0.1",
    "@alilc/lowcode-plugin-simulator-select": "^1.0.0",
    "@alilc/lowcode-plugin-undo-redo": "^1.0.0",
    "@alilc/lowcode-setter-behavior": "^1.0.0",
    "@alilc/lowcode-setter-title": "^1.0.2",
    "@alilc/lowcode-types": "^1.0.1",

**Comment by alex921131958** [comment]
> 尝试统一formily依赖至同一版本 可以修复报错
```
/@alilc/lowcode-plugin-datasource-pane/1.0.7_b15c2cefb020943db03bbf068b4dc95e:
    resolution: {integrity: sha1-bFg7a1ukgCy6I9FW3YN6UXe9hwY=, tarball: '@alilc/lowcode-plugin-datasource-pane/download/@alilc/lowcode-plugin-datasource-pane-1.0.7.tgz'}
    peerDependencies:
      moment: ^2.29.1
    dependencies:
      '@alifd/next': 1.26.6_react-dom@16.14.0+react@16.14.0
      '@alilc/lowcode-plugin-base-monaco-editor': 1.1.1
      '@alilc/lowcode-types': 1.0.15
      '@babel/core': 7.20.2
      '@babel/parser': 7.20.3
      '@babel/preset-env': 7.20.2_@babel+core@7.20.2
      '@babel/preset-react': 7.18.6_@babel+core@7.20.2
      '@babel/standalone': 7.20.0
      '@babel/traverse': 7.20.1
      '@babel/types': 7.20.2
      '@formily/core': 2.2.10
      '@formily/next': 2.2.10_63e5b4141339bf80661c3dedf337c516
      '@formily/react': 2.2.10_0dd69d1fbad40aac04c3d3fcdfc6b78a
      '@types/lodash': 4.14.188
      '@xstate/react': 1.6.3_26ecd258e1f22bb8181e862323d32a4e
      ajv: 6.12.6
      babel-plugin-transform-remove-strict-mode: 0.0.2
      classnames: 2.3.2
      js-beautify: 1.14.7
      lodash: 4.17.21
      react: 16.14.0
      react-copy-to-clipboard: 5.1.0_react@16.14.0
      react-dnd: 14.0.5_33c0b7af9ae2c143024d18648574fcd9
      react-dnd-html5-backend: 14.1.0
      react-dom: 16.14.0_react@16.14.0
      react-error-boundary: 3.1.4_react@16.14.0
      svgo: 2.8.0
      traverse: 0.6.7
      xstate: 4.34.0
```

**Comment by Shijf** [comment]
同样遇到这个问题，懵懵懵

**Comment by liujuping** [comment]
解决方案：

1.lowcode-demo 中除了 formily 场景，其他场景不应该依赖 @formily/xxx

2.formily 场景需要通过 "resolutions" 来固定 @formily/xxx 的版本，防止不同的插件之间 @formily/xxx 版本不一致。
