### ISSUE TITLE
「设计讨论」如何解决因 props 内部对象过于复杂，导致初始化/更新等耗时过长从而页面卡顿

### ISSUE THREAD

**Issue by LeoYuan** [alibaba/lowcode-engine#1086]
### 背景

目前引擎内部的 Props / Prop 模块，在处理 json 对象时，会一直递归生成 Prop 实例（唯一的例外是在处理 JSSlot / JSExpression 时），当初这样设计，是为了让 Prop#value 的响应式可以更灵活，比如如下 json 对象：

```js
{
  componentName: 'MyComponent',
  // 其他节点字段
  props: {
    x: {
      y: {
        z: 1
      }
    }
  }
}
```

这样生成嵌套结构的 Prop 实例，每层都是响应式，则在视图层通过 `props.setPropValue('x.y.z', 2)` 可以完成视图自动更新~

### 问题

如今有这样一种情况，当 props 结构特别复杂时，比如对象深度超过 10 层，将对整个引擎的性能产生非常大损耗，尤其当用户根本不关心深层级的响应式时~
```js
{
  props: {
    x: {
      y: {
        z: {
          // giant json object
        }
      }
    }
  }
}
```

感受一下这个函数调用栈~
![image](https://user-images.githubusercontent.com/1195765/192450895-2f57198a-5177-4939-b310-e08f7b531bb4.png)

### 解法

目前 Prop 中有几种特殊类型，比如 JSSlot 和 JSExpression，对于 JSSlot，将会新建 Slot 节点和初始化 Slot 对应的 Props，继而嵌套的 Prop 实例，对于 JSExpression，将会按照原始结构保存，并在其他使用到的地方做 evaluate 计算，现在想增加一种「原子型对象」类型，表明该对象「**不可再分，无须递归解析**」，且 **无法通过 getPropValue(内部路径)** 获取到内部的 Prop 对象，对于引擎来讲，该对象即为最底层对象了，即最多 getPropValue('x.y.z')，没法 getPropValue('x.y.z.innerPath')~

原特殊类型 Prop 值结构：
```js
// JSExpression
{
  type: 'JSExpression',
  value: xxx,
  mock: 'mock value'
}

// JSSlot
{
  type: 'JSSlot',
  value: xxx
}
```

新增数据结构：
```js
{
  type: 'AtomObject',
  value: giant json object
}
```

新的结构几个特点：
1. 无递归生成 Prop 逻辑；
2. 无法通过 innerPath 去获取值，即无 getPropValue('x.y.z.innerPath')；
3. innerPath 内部的响应式不再生效，需要整体设值来触发响应式，比如通过 setPropValue('x.y.z', { ...originalValue, newValue });

**Comment by Cossey11111** [comment]
hi~目前这个问题有解决方按了吗？我是看到代码没有被合并呀

**Comment by LeoYuan** [comment]
没有，后面用其他方案解决了，是渲染次数过多导致了卡顿，代码应该合入了~
