### ISSUE TITLE
AssetLoader资源加载无法保证按序加载

### ISSUE THREAD

**Issue by mmmmmmmgo** [alibaba/lowcode-engine#1087]
在预览页中。

antd物料有概率会报错, 原因是这个物料依赖了antd external.
而AssetLoader的加载逻辑无法保证物料的加载顺序

**Comment by mmmmmmmgo** [comment]
https://github.com/alibaba/lowcode-engine/blob/7a0bab11aca6fa5856af894736222c6d14897467/packages/utils/src/asset.ts#L235-L238

**Comment by mmmmmmmgo** [comment]
![image](https://user-images.githubusercontent.com/112670419/192491089-c6bad4d9-5c0c-4bea-a150-eeee0aa3fdb9.png)


![image](https://user-images.githubusercontent.com/112670419/192491244-9e1a8a66-a167-47b6-9e55-62e4f51e5121.png)

**Comment by mmmmmmmgo** [comment]
官网无法复现,hhh

**Comment by mmmmmmmgo** [comment]
原来是lowcode demo里依赖的 @alilc/lowcode-utils 是旧版的. 小丑竟是我自己🤡

**Comment by mmmmmmmgo** [comment]
但是@alilc/lowcode-engine-ext@1.0.4 把@alilc/lowcode-utils的版本写死成1.0.0, 而我正好换了pnpm, 升不上去, 只能强制依赖.

**Comment by liujuping** [comment]
@alilc/lowcode-engine-ext 的依赖问题我们处理一下，感谢反馈和定位问题。
