### ISSUE TITLE
建立个阿里lowcode钉钉交流群吧,二开问题太多了.

### ISSUE THREAD

**Issue by duoduoObama** [alibaba/lowcode-engine#109]
建立交流群的缘由:

1.目前物料开发这块,按文档走很多走不通.
2.太多关于开发环境的注意问题(linux?windows?mac?).
3.关于npm和tnpm非标准的开发环境带来的问题.

**Comment by mark-ck** [comment]
![image](https://user-images.githubusercontent.com/44559440/157593229-a170acf6-64f1-4ba1-862c-3a8e22784577.png)

官网有群二维码 https://lowcode-engine.cn/
