### ISSUE TITLE
编辑态和渲染态的区别？

### ISSUE THREAD

**Issue by heyicheng** [alibaba/lowcode-engine#1090]
编辑态的Button组件的点击事件是能生效的，但是select组件点击不能弹出下拉框，
想咨询一下渲染态下点击select怎样才能弹出

**Comment by LeoYuan** [comment]
绑定onClick事件，通过设置变量决定模态框的显隐。

设计器里，默认屏蔽了一些组件的事件，因为编辑态无法做到完全的所见即所得，比如点击到底是选中节点进行属性编辑还是响应节点本身的事件，这有二义性。
