### ISSUE TITLE
【提问】如何在低代码中做到父子组件之间共享数据

### ISSUE THREAD

**Issue by tsheng** [alibaba/lowcode-engine#1094]
现在我们有一些全局的数据希望在父组件（或者根Page组件）上进行配置，然后在页面的正文部分的各个子组件之间能够方便的访问到，做到全局数据共享，有没有比较推荐的做法？

目前能想到的就做法就是把数据配置到Page组件上，组件运行时把这些全局数据挂载到window上，子组件通过window来访问到这些数据，想看看有没有更推荐的做法，谢谢。

**Comment by LeoYuan** [comment]
来自热心群众：可以阅读  FusionUI 中关于 [Form](https://github.com/alibaba/lowcode-materials/blob/9aee237cec829151e9cfdf1607d151edf4247874/packages/fusion-ui/src/components/pro-form/index.tsx) & [FormItem](https://github.com/alibaba/lowcode-materials/blob/9aee237cec829151e9cfdf1607d151edf4247874/packages/fusion-ui/src/components/pro-form/components/form-item/index.tsx) 的代码~

**Comment by LeoYuan** [comment]
或者把 Page 组件做成包含 ConfigProvider 的形式？Page 上配置的属性，（孙）子节点通过 context 获取~

**Comment by tsheng** [comment]
> 或者把 Page 组件做成包含 ConfigProvider 的形式？Page 上配置的属性，（孙）子节点通过 context 获取~

试了下，子组件在运行时拿不到Provider的数据，搭建模式下是可以拿到的。

react-dom.development.js:539 Warning: React does not recognize the `shareConfig` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `shareconfig` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by InstPage)
    in InstPage (created by InstPage)
    in InstPage (created by base-renderer)
    in base-renderer (created by ReactRenderer)
    in ConfigProvider (created by ReactRenderer)
    in ReactRenderer (created by SamplePreview)
    in div (created by SamplePreview)
    in SamplePreview

**Comment by LeoYuan** [comment]
调试下，理论上这个跟引擎关系不大了

**Comment by tsheng** [comment]
> 调试下，理论上这个跟引擎关系不大了

已经验证OK了，是我写法的问题，用Provider的方式可行。Many thanks.
