### ISSUE TITLE
importSchema时弹窗组件不会立即渲染

### ISSUE THREAD

**Issue by eightHundreds** [alibaba/lowcode-engine#1095]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

1. 打开 [demo](https://lowcode-engine.cn/demo/basic-antd.html)；
2. 导入Schema
```
{
  "componentName": "Page",
  "id": "node_ocl8ldgt8w1",
  "props": {},
  "fileName": "sample",
  "hidden": false,
  "title": "",
  "isLocked": false,
  "condition": true,
  "conditionGroup": "",
  "children": [
    {
      "componentName": "Modal",
      "id": "node_ocl8ldgt8w2",
      "props": {
        "title": "Basic Modal",
        "okText": "确认",
        "cancelText": "取消",
        "visible": true,
        "destroyOnClose": true,
        "centered": false,
        "closable": true,
        "confirmLoading": false,
        "forceRender": false,
        "keyboard": true,
        "mask": true,
        "maskClosable": true,
        "bodyStyle": {},
        "maskStyle": {}
      },
      "hidden": false,
      "title": "",
      "isLocked": false,
      "condition": true,
      "conditionGroup": ""
    }
  ]
}
```
3. 保存
4. **弹窗不会出现**

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
画布中展示出弹窗

---

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**

全是最新

 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by eightHundreds** [comment]
根据我的调试, 弹窗组件导入后都不会出现, 因为他们都没渲染.

**Comment by LeoYuan** [comment]
by design~

需要显示的话，调用相应 API 去做~

**Comment by eightHundreds** [comment]
> by design~
> 
> 需要显示的话，调用相应 API 去做~

关键是, 我从弹窗打开的情况下到导出, 刷新再导入. 发现弹窗没打开

感觉像bug

**Comment by LeoYuan** [comment]
目前设计器默认就会将所有模态节点隐藏，理解一下设计模块，渲染模块以及组件自身的实现，你也可以定制你想要的行为。

```
const outerVisible = true; // 引擎层面控制的显隐，决定组件是否可以被渲染
const innerVisible = true; // 组件接收的 props，自己依然可以决定是否渲染出实际节点

// 引擎实现
if (!outerVisible) {
  return null;
}

return <Dialog {...props} />

// Dialog 实现
function Dialog(props) {
  if (!props.innerVisible) return null;
  return <div />;
}
```
总结：引擎控制的是外层，设置区控制的是传入的 props，也就是里层，两层的控制都得是 true，才能渲染出模态框~

**Comment by eightHundreds** [comment]
![2022-09-29 10 29 49](https://user-images.githubusercontent.com/18695431/192925491-ebe742fd-fb5c-4451-990b-e3b61332f7be.gif)

**Comment by eightHundreds** [comment]
如果这样是认为没问题的, 那就是没问题了

**Comment by liujuping** [comment]
弹窗的弹出控制是设计态的行为，在刚刚拖入进去的时候会默认展示，正常导入 schema/刷新都不会展示，因为不会存储弹窗是否默认展示的字段（这样会导致预览的时候弹窗展示不符合预期，预览和设计弹窗展示的逻辑是不一样的）。
