### ISSUE TITLE
README.md中git clone提示没有访问权限

### ISSUE THREAD

**Issue by shabbyaaa** [alibaba/lowcode-engine#11]
git clone git@github.com:alibaba/lowcode-engine.git
改为用http下载可以成功，建议README.md中改一下别使用git@形式下载
![image](https://user-images.githubusercontent.com/48679300/154466557-da401ab6-30ff-439e-8eaa-16b98f79e380.png)

**Comment by alvarto** [comment]
https://github.com/settings/ssh/new

git 方式 clone 需要创建 ssh key 并正确挂钩。
