### ISSUE TITLE
【咨询】请问有画布开发的相关文档吗？

### ISSUE THREAD

**Issue by ZhelinCheng** [alibaba/lowcode-engine#1100]
因为业务需求更偏向于C端，样式布局可能更自由一点，找了一圈没看到相关文档。

**Comment by liujuping** [comment]
目前没有文档，参考这两个画布的实现：
1.https://github.com/alibaba/lowcode-engine/tree/main/packages/rax-simulator-renderer
2.https://github.com/alibaba/lowcode-engine/tree/main/packages/react-simulator-renderer
