### ISSUE TITLE
ant高级组件里的表格，查询区域时间类型组件不能点击“此刻”按钮，点了就报错

### ISSUE THREAD

**Issue by dong-gy** [alibaba/lowcode-engine#1104]
![lQLPJxa79MGFqi3NA6HNB4CwQYCHsMMCamADNQN3koDsAA_1920_929](https://user-images.githubusercontent.com/48462501/193234780-bfa03503-8e4a-4e85-83b9-1f72b2481e6e.png)
![lQLPJxa79MGFqoTNA6HNB4CwNjNjurmoXUEDNQN3mgCRAA_1920_929](https://user-images.githubusercontent.com/48462501/193234812-cc026ef8-e804-46b9-b64c-65848f1d7f24.png)

**Comment by twinkle77** [comment]
这个修复了 我提个到 lowcode-demo
  
  @dong-gy  使用最新版本的组件 https://github.com/seada-low-code/lowcode-ecology
