### ISSUE TITLE
【Feature】操作辅助区扩展可以支持函数

### ISSUE THREAD

**Issue by jiangtao** [alibaba/lowcode-engine#1107]
### 背景

在一些业务扩展场景下，title 和 content 等希望可以根据节点来动态处理，动态变化。如一个节点有 id，状态为编辑，否则为保存等操作。

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **截图**

红色区域对应的每个属性希望都可以根据node 扩展

<img width="1042" alt="image" src="https://user-images.githubusercontent.com/2155745/194705321-59d3e3da-84d6-4f22-9510-a098736bdb78.png">

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - materials
> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
暂无

**Comment by LeoYuan** [comment]
是扩展红框内容还是红框右边的复制、删除的内容？

**Comment by jiangtao** [comment]
> 是扩展红框内容还是红框右边的复制、删除的内容？

https://github.com/alibaba/lowcode-engine/blob/main/packages/designer/src/component-meta.ts#L397 这个文件。
期望 name、content下的字段可以支持函数， 返回值保持现在的返回值类型。

```javascript
{
    // 希望可以扩展成函数, 这样可以自由定制
    name (node: Node) {
        if (node.isContainer()) {
            return 'Container'
        } else {
            return `${node.id}`
        }
    },
    content: {
      icon: IconHidden,
      // 希望可以扩展成函数, 这样可以自由定制
      title(node: Node) {
        if (node.isContainer()) {
            return 'Container'
        } else {
            return `${node.id}`
        }
     },
    }
}
```

**Comment by LeoYuan** [comment]
> 一个功能按钮进行不同节点下显示不同的状态、名称、图标等，现在需要有多少个状态写多少遍，太冗余了，只能根据 condition 来做区分

其实我觉得没问题，多少中状态 / 名称 / 图标，你管理一个正交的状态集，一个 for 循环就都创建了~

除此之外，假如真要做，几个问题：
- name 对外并无实际意义，只是内部管理用到的，比如 removeBuiltinComponentAction，支持函数后，怎么移除某个指定 action？
- title 国际化

**Comment by jiangtao** [comment]
> > 一个功能按钮进行不同节点下显示不同的状态、名称、图标等，现在需要有多少个状态写多少遍，太冗余了，只能根据 condition 来做区分
> 
> 其实我觉得没问题，多少中状态 / 名称 / 图标，你管理一个正交的状态集，一个 for 循环就都创建了~
> 
> 除此之外，假如真要做，几个问题：
> 
> * name 对外并无实际意义，只是内部管理用到的，比如 removeBuiltinComponentAction，支持函数后，怎么移除某个指定 action？
> * title 国际化

好。我这边看看怎么在业务侧设定的其他人更友好的引入吧。
