### ISSUE TITLE
父子组件都是container的时候，再拖入一个组件的时候， 组件放置的临界点判断的问题

### ISSUE THREAD

**Issue by ljmCoder** [alibaba/lowcode-engine#1108]
官网demo的antd场景下即可复现：

举个例子： space组件拖进一个card组件， 这个时候想拖入第二个card组件进入space， 这个时候发现很难拖进去， 不是和space平行就是会被拖进第一个card里面，但实际上是想拖进space和第一个card平行。 这种父子都是container的情况下，再拖入时的临界点有什么好的处理方法？ 

![image](https://user-images.githubusercontent.com/41459781/194735073-8cacbe71-a913-4089-ba21-d07e21f07917.png)

**Comment by LeoYuan** [comment]
假如子组件把父组件都占满了，再想拖入一个子组件 2 是比较难，此时用大纲树拖拽或者点击复制原子组件吧~

**Comment by LeoYuan** [comment]
目前没想到更好的交互~

之前想过拖拽悬停的时候，目标放置的容器做一定的样式变化，比如 margin 变化，这样能区分「紧贴的两层容器」，不过会引发整个页面布局变化，甚至错乱，不太优雅，后面想到更好的处理方式再打开此 issue 哈~
