### ISSUE TITLE
设置器高级功能bug

### ISSUE THREAD

**Issue by posuihushui** [alibaba/lowcode-engine#112]
高级变量绑定时候容易自动绑定空数据循环，无法正常显示，需要手动在schema里删除loop相关字段

---

## *如何复现 bug？*

1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 访问localhost:3333；
3. 点击组件库，拖入按钮、文字组件；
4. 给文字组件绑定高级->变量->isShowDialog, 给按钮绑定onclick事件为onclick,

## *预期行为*
预览时按钮组件不消失；

AliLowCodeEngine version: 1.0.2

**Comment by alvarto** [comment]
https://github.com/alibaba/lowcode-engine/issues/31

应该是这个的复现方式，@hzd822 看看？

**Comment by LeoYuan** [comment]
![image](https://user-images.githubusercontent.com/1195765/158139441-4e106f08-cdd3-4e98-ac0e-6434bfc35062.png)

正常的？

绑定的是 文本 组件的变量，为什么预期 按钮 组件消失？

**Comment by ChongYnag** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
