### ISSUE TITLE
请问 该引擎 适合制作  微信小程序吗？  有相关的demo吗？ 能否导出项目供前端二次开发？

### ISSUE THREAD

**Issue by huangapple** [alibaba/lowcode-engine#1126]
如题

**Comment by JackLian** [comment]
1. 可以做， 2. 目前没demo， 3. 能出码供前端二次开发，但二次开发就无法转回低代码，需要产品层面做好权衡

**Comment by hskww** [comment]
> 1. 可以做， 2. 目前没demo， 3. 能出码供前端二次开发，但二次开发就无法转回低代码，需要产品层面做好权衡

大部分场景是低代码转到wx小程序，不需要小程序再回转到低代码， 但不需要进行二次开发，而一次性就转好，需要自己创建微信小程序的code-generator
