### ISSUE TITLE
报CORS错误

### ISSUE THREAD

**Issue by 84896150** [alibaba/lowcode-engine#1129]
## 复现截图
has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.

![image](https://user-images.githubusercontent.com/3245204/195602375-5a92c8a9-15d7-45c6-ba0e-6494a7b25765.png)
![image](https://user-images.githubusercontent.com/3245204/195602509-d392f1a5-59f0-4c3d-a3d2-ebefa670cdd2.png)
## 环境信息

- 引擎版本 1.0.3-beta.0
- ext 版本 1.0.3
- 物料
  - moment﹫2.24.0
  - lodash
  - ﹫alifd/next﹫1.24.18
  - NextTable﹫1.0.1
  - ﹫alilc/lowcode-materials﹫1.0.2
  - ﹫alifd/pro-layout﹫1.0.1-beta.6
  - ﹫alifd/fusion-ui﹫1.0.5

**Comment by LeoYuan** [comment]
CORS 的问题主要看看 API 提供方的相关跨域设置~

**Comment by LiCain** [comment]
想问下解决？在哪里，没找到呢

**Comment by LeoYuan** [comment]
意思是：CORS 是接口调用方（通常是浏览器）和接口提供方针对跨域资源的处理策略，请去 MDN 再仔细学习一下 [CORS](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS)~

报错可能是提供方 API 不允许跨域，也可能是对调用方有一些要求~
@LiCain

**Comment by huchuansai** [comment]
补充一下规范的CORS配置，经验证过后可用于lowcode-engine的fetch请求中
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/50079978/211145308-3900f588-100b-417c-bc9a-c9f4a36ad79e.png">

**Comment by avocadowang** [comment]
接口提供方配了允许跨域, 但还是报cors, 没有人遇到同样的问题吗?

**Comment by hinhinlaw** [comment]
> 接口提供方配了允许跨域, 但还是报cors, 没有人遇到同样的问题吗?

我是用express搭的服务端，用了cors中间件也是报cors

**Comment by nljshoxbb** [comment]
nestjs 这样配置可以
```
app.enableCors({
    origin: true,
    allowedHeaders:
      'Cookie, Authorization, DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type',
    methods: 'GET,POST,PUT,DELETE,OPTIONS',
    credentials: true,
  });
```

nginx
```
 add_header 'Access-Control-Allow-Origin' $http_origin always;
    add_header 'Access-Control-Allow-Headers' 'Cookie, Authorization, DNT,X-CustomHeader,Keep-Alive,User-Agent,X-Requested-With,If-Modified-Since,Cache-Control,Content-Type';
    add_header 'Access-Control-Allow-Credentials' true;
    add_header 'Access-Control-Allow-Methods' 'GET,POST,PUT,DELETE,OPTIONS';

    if ($request_method = 'OPTIONS'){
        return 204; # 预检测
    }
```

**Comment by kangshuolei** [comment]
<img width="1033" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/50732481/55d618d6-b932-4fa0-b4e3-fcbdf049dce9">
为什么我的还是跨域呢

**Comment by kangshuolei** [comment]
<img width="1033" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/50732481/4549a028-7ba0-4259-878f-34e6315da69c">
为什么我的还是跨域呢
