### ISSUE TITLE
出码功能的在线预览异常

### ISSUE THREAD

**Issue by shifengdiy** [alibaba/lowcode-engine#113]
官方提供的demo，出码功能的在线预览一直显示加载中
demo地址：https://alifd.alicdn.com/npm/@alilc/lowcode-demo@1.0.0/build/index.html

**Comment by LeoYuan** [comment]
![image](https://user-images.githubusercontent.com/1195765/158136435-339edc3c-896c-446e-ba64-01df7ce46dd7.png)

btw：下次最好使用 https://lowcode-engine.cn/demo， 我们会定期将其指向最新版本的 demo~
