### ISSUE TITLE
大纲树加载不出来

### ISSUE THREAD

**Issue by zzq1314zll** [alibaba/lowcode-engine#1133]
<img width="1778" alt="image" src="https://user-images.githubusercontent.com/33930711/195989023-706779eb-a36b-4606-9287-46f13e0e44d4.png">

**Comment by LeoYuan** [comment]
你大概率是没有使用 UMD + webpack externals 的形式，而是 npm 直接打包了吧，参考 lowcode-demo 的用法去使用吧~
