### ISSUE TITLE
能否通过LowCode的API直接创建schema

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#1138]
场景就是我们产品需要在某个页面（非低代码拖拽页面，还没init）进行excel导入创建页面，解析出excel，我需要对内容生成出对应的shcema，但是因为不是在拖拽页面所以我不能直接调用lowcode-engine的方法。

所以想问下有没有某个API能够支持我传入packages和组件信息以后，可以直接创建schema出来

**Comment by JackLian** [comment]
要参考协议自行构造一下了，没有api
