### ISSUE TITLE
多页面出码如何实现

### ISSUE THREAD

**Issue by imscorpioer** [alibaba/lowcode-engine#1142]
## **Describe the bug (required)** / **详细描述 bug（必填）**

想知道完整项目多个页面的出码实现，是否可以实现出码之后，用菜单切换不用的路由，官方能否提供一个相关的demo实现

**Comment by iqinning** [comment]
首先你要能配置多页面协议这个有直播视频看怎么做，出码那块现在官方提供的默认ICE解决方案是支持多页页面切换的，有路由相关的插槽。

**Comment by imscorpioer** [comment]
> 首先你要能配置多页面协议这个有直播视频看怎么做，出码那块现在官方提供的默认ICE解决方案是支持多页页面切换的，有路由相关的插槽。

thanks ， 我去看看

**Comment by shmilyCai** [comment]
你好，请问下在哪里看“能配置多页面协议这个有直播视频”的直播视频，麻烦分享下视频链接嘛？
