### ISSUE TITLE
rax-单组件执行lowcode:dev浏览器报错

### ISSUE THREAD

**Issue by youngerbyte** [alibaba/lowcode-engine#1147]
@alilc/element创建“rax-单组件“lowcode:dev浏览器报错
一、详细描述 bug
通过命令 $npm init @alilc/element your-element-name --registry=https://registry.npmmirror.com 创建的“rax-单组件”报下面的错
<img width="703" alt="截屏2022-10-19 11 01 17" src="https://user-images.githubusercontent.com/12269663/196587346-1dbd82b1-3d42-4fd9-b3eb-85473138d2e5.png">

二、如何复现 bug + 详细复现步骤
1. $npm init @alilc/element your-element-name --registry=https://registry.npmmirror.com
2. 选择 "rax-单组件"
3. 创建成功后 $yarn&&yarn lowcode:dev
三、问题大概定位
生成的文件中 .tmp/index.jsx，可能和editor.set('renderEnv', 'rax');有关系，苦于没有源码无法定位
`if (baseLibrary && baseLibrary === 'rax') {
        editor.set('renderEnv', 'rax');
        project.onRendererReady(() => {
          editor.get('designer').currentDocument.simulator._iframe.onload = () => {
            editor.get('designer').currentDocument.simulator.set('device', 'phone');
          }
        });
      }`
三、环境信息
低代码引擎版本: 1.0.1
低代码引擎扩展包版本: 1.0.1
浏览器版本: chrome 版本 105.0.5195.125（正式版本） (x86_64)

**Comment by mark-ck** [comment]
fixed

**Comment by youngerbyte** [comment]
> 
还是报错呢？
<img width="519" alt="截屏2022-10-27 19 12 44" src="https://user-images.githubusercontent.com/12269663/198269681-f2b57b41-e297-4162-879b-0e6693510a23.png">
