### ISSUE TITLE
关系图编排

### ISSUE THREAD

**Issue by linzer** [alibaba/lowcode-engine#115]
“通过注册不同的模拟器画布，你可以基于 G6或者 mxgraph 来做关系图编排。你可以定制一个流式布局的画布，也可以定制一个自由布局的画布”
1，官方有计划做关系图编排设计器插件没
2，如果没有计划能否给个简单的插件雏形再由社区完善，designer、host、simulator-renderer间的通信交互看似挺复杂的

需求场景：
1，er图(编辑)
2，业务编排

**Comment by JackLian** [comment]
阿里内部有类似的实现，目前还没到开源的阶段，还需要打磨下~
