### ISSUE TITLE
通过api获取物料meta信息

### ISSUE THREAD

**Issue by hi-heshuai** [alibaba/lowcode-engine#1157]
官方文档提供获取物料meta信息api如下：
import { material } from '@alilc/lowcode-engine';

material.getComponentMeta('Input');

当我使用上面api后得到的对象通过symbol包裹了一层，我无法拿到这个symbol变量，所以也拿不到物料的meta信息

**Comment by liujuping** [comment]
![image](https://user-images.githubusercontent.com/11935995/197670379-8839f683-b4c2-4482-b503-dd32d2933e63.png)

这个就是物料的 meta 信息，不用拿 symbol 变量。有缺少的信息可以重新提个 issue。
