### ISSUE TITLE
精选组件里的组件没有找到meta 文件

### ISSUE THREAD

**Issue by leehomeok** [alibaba/lowcode-engine#116]
精选组件里的protable, filter 这些组件，在lowcode-materials 没有发现对应的meta文件，请问在哪里可以修改？

**Comment by mark-ck** [comment]
> lowcode-materials 安装依赖时报错 ![image](https://user-images.githubusercontent.com/13464485/157788171-911b12bf-eab1-4354-9ae9-4bb5b4e58d4f.png)

问题已解决，你再重新安装下依赖试试呢
