### ISSUE TITLE
预览页面内点击按钮实现路由跳转

### ISSUE THREAD

**Issue by gaojian531048553** [alibaba/lowcode-engine#1170]
## **Describe the bug (required)**  多页面应用开发中,在预览页面和设计页面里如何实现点击按钮可以使用路由跳转到另外一个页面吗?或者有其他的解决方式吗?
![image](https://user-images.githubusercontent.com/20181669/197980241-2d79b5a9-9ef0-4dd7-b8b7-2cbc94d2080f.png)

**Comment by liujuping** [comment]
目前引擎还没提供应用级别的渲染能力，可以结合已有的渲染 + react-router 等路由，在跳转之后通过路径判断来使用对应页面的 schema 来渲染。

**Comment by JackLian** [comment]
可以通过appHelper把 router注入到utils下，然后类似这样的调用 this.utils.router.goToPage(xxx,xx,xx)

**Comment by 15163789836** [comment]
> 

你好请问有没有 具体的方法。实现步骤 教程
