### ISSUE TITLE
slot 编辑器和渲染器展示效果差异

### ISSUE THREAD

**Issue by lucy091** [alibaba/lowcode-engine#1173]
## **Describe the bug (required)** / **详细描述 bug（必填）**
bug 1023 中确实去掉了lc-container的包裹，不过编辑器和渲染器出来的效果某些情况下还是有差异
<img width="648" alt="image" src="https://user-images.githubusercontent.com/33422728/198186561-f01e9461-635f-4208-a6e8-9808ff461d4c.png">

版本信息
AliLowCodeEngine  v1.0.15 
AliLowCodeExt  v1.0.5 

对应有传递dom的渲染函数，如pro-component中table组件的search.optionRender, 会传递两个button组件 dom为参数
<img width="1226" alt="image" src="https://user-images.githubusercontent.com/33422728/198187044-982ed0fc-d80e-4c0f-82de-ae4e9da860a9.png">
物料下面两种处理方式
<img width="778" alt="image" src="https://user-images.githubusercontent.com/33422728/198187592-4121b9f5-1000-427d-80b2-710bdefcdcfa.png">
<img width="716" alt="image" src="https://user-images.githubusercontent.com/33422728/198187802-f2a22d1f-c397-4f5e-9f37-d9ff17b13415.png">

会出现下面的差异
<img width="1717" alt="image" src="https://user-images.githubusercontent.com/33422728/198186047-9451a730-94c9-4d11-9d11-f09edc10e168.png">

<img width="1529" alt="image" src="https://user-images.githubusercontent.com/33422728/198186128-d8b8c762-b6f8-4372-9247-dee9d97b0dd4.png">

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

**Comment by liujuping** [comment]
这个差异的原因是编辑态需要 Slot 组件包裹，用于辅助页面设计，而预览态是不需要的。相当于：

编辑态下：
- Slot
- - Button
- - Button

预览下：
- Button
- Button

这里编辑态的 Slot 是没有办法去掉的，这里的效果如果需要一致需要在产品上自行处理（设计态组件去掉 Slot 或者预览态包裹一层 Slot），引擎目前在设计态和预览态是不保证完全一致的，以后可能会添加 live 的设计模式和预览态保持一致。
