### ISSUE TITLE
【咨询】请问你们这边是如何开发画布的？

### ISSUE THREAD

**Issue by ZhelinCheng** [alibaba/lowcode-engine#1175]
因为我有这个需求，可不可以描述一个简要的开发流程。

**Comment by JackLian** [comment]
https://lowcode-engine.cn/docV2/af3dxw#UEG1P
参考这这个文档中对原理的介绍，代码上建议参考 react-simulator-renderer 和 react-renderer

**Comment by ghwghw4** [comment]
> https://lowcode-engine.cn/docV2/af3dxw#UEG1P 参考这这个文档中对原理的介绍，代码上建议参考 react-simulator-renderer 和 react-renderer

@JackLian 文档地址已经失效了，能否更新下最新的文档地址

**Comment by JackLian** [comment]
https://lowcode-engine.cn/site/docs/guide/design/renderer
