### ISSUE TITLE
 现有【modules/code-generator/】出码模块， 如何出多页面的程序？

### ISSUE THREAD

**Issue by huangapple** [alibaba/lowcode-engine#1178]
![image](https://user-images.githubusercontent.com/10572028/198262839-a69ca85d-9dc9-405d-854d-9ae68f813d12.png)

这样只能出一个页面， 如果我编辑了多个页面， 我要如何出码？文档翻了好多遍， 没看到相关的说明
官方能否给一个demo， 或指导一下？

**Comment by LeoYuan** [comment]
你的目标是怎样的？比如一个 componentsTree 含有两/多个页面？需要有跳转能力？

**Comment by huangapple** [comment]
因为demo只是一个单页面的编辑器。但项目基本都是多页面的。要改要配套的改

目前我这边自己魔改的是， 一个componentsTree是包含多个页面的。跳转能力就是根据路由跳的。

目前出码的模块， 其实 对多页面已经有一部分的支持了。但有一些还不是很完善

1. src/layouts/BasicLayout/menuConfig这个文件里的菜单没有跟 src/routes里面的配套起来， 前者是写死的, 目前我是粗暴的等出码后再进行替换。
2. 出码的模板有点旧(ice1.x)， 而且还是js的。
3. 出码的package.json里面有个undefined:* ， 这应该是个小BUG， 但好像没影响什么。


菜单感觉 ProjectSchema 协议， 好像不太支持菜单相关的设置， 所以比较尴尬
我这边是自己弄了个菜单管理， 菜单上有分是页面还是文件夹（就是下级是菜单）
![image](https://user-images.githubusercontent.com/10572028/204189437-9eb4ebc4-6162-4de3-b2ca-6f2ab1cbe6df.png)

**Comment by shiert** [comment]
> 因为demo只是一个单页面的编辑器。但项目基本都是多页面的。要改要配套的改
> 
> 目前我这边自己魔改的是， 一个componentsTree是包含多个页面的。跳转能力就是根据路由跳的。
> 
> 目前出码的模块， 其实 对多页面已经有一部分的支持了。但有一些还不是很完善
> 
> 1. src/layouts/BasicLayout/menuConfig这个文件里的菜单没有跟 src/routes里面的配套起来， 前者是写死的, 目前我是粗暴的等出码后再进行替换。
> 2. 出码的模板有点旧(ice1.x)， 而且还是js的。
> 3. 出码的package.json里面有个undefined:* ， 这应该是个小BUG， 但好像没影响什么。
> 
> 菜单感觉 ProjectSchema 协议， 好像不太支持菜单相关的设置， 所以比较尴尬 我这边是自己弄了个菜单管理， 菜单上有分是页面还是文件夹（就是下级是菜单） ![image](https://user-images.githubusercontent.com/10572028/204189437-9eb4ebc4-6162-4de3-b2ca-6f2ab1cbe6df.png)

你这边有遇到出码后本地运行会样式丢失的问题么？

**Comment by huangapple** [comment]
有啊， 一般构建时就会报错了 ， 要相应修改掉

**Comment by shiert** [comment]
> 

改哪个部分可以告知一下么？

**Comment by huangapple** [comment]
你报错贴一下

**Comment by shiert** [comment]
> 有啊， 一般构建时就会报错了 ， 要相应修改掉
我这边构建目前没报错  但页面就是丢失样式 组件的话样式不会丢失 主要是页头之类的

**Comment by huangapple** [comment]
那不懂了， 我是有报错， 一般就是把依赖更新一下， 就好了

**Comment by shiert** [comment]
#

> 
行吧谢谢 我目前就是遇到的样式丢失主要是 其他昨天的时候有依赖报错 更新了一下就没问题

**Comment by shiert** [comment]
![bug](https://user-images.githubusercontent.com/80880099/204424895-d1085a18-77ab-45e3-a0e2-eef514606bf4.PNG)

**Comment by LeoYuan** [comment]
导航的数据结构的问题，目前开源版本确实考虑还不周全，内部我们是有张扩展表来保存的~

这块我建议你可以自己先定义一个结构，并且出码实现，后面看看能不能提个 PR 来增强搭建协议~

**Comment by huangapple** [comment]
收到
