### ISSUE TITLE
[模拟器] 期望可以通过API同步获取模拟器内Page/Component节点的state数据

### ISSUE THREAD

**Issue by charmtiger** [alibaba/lowcode-engine#1181]
问题描述 

无

---
期望

期望可以通过API同步获取模拟器内 Page / Component 节点的 state 数据，目的是方便开发过程中时刻了解当前的数据值

---

 - AliLowCodeEngine version: [e.g. 1.0.15] 
 - AliLowCodeEngineExt version: [e.g. v1.0.5]
 - Browser [edge 最新版]

**Comment by JackLian** [comment]
提供下更具体的场景吧，还没看到这方面的必要性，设计器是一个设计态，并非运行时，也就不涉及state，所以没太明白你的诉求场景

**Comment by charmtiger** [comment]
虽然是设计态，但是在设计的时候，生命周期，数据源和js函数都可以在模拟器中运行。所以我认为，既然可以在开发的过程中进行简单的调试，那么就可以优化一下，做一个面板查看实时的数据，方便对接数据

**Comment by JackLian** [comment]
并没有执行的，你说的执行应该是预览状态吧，那个其实不算是设计器内了

**Comment by charmtiger** [comment]
现状是编辑器的页面打开后，数据源和生命周期都会执行，并且接口数据也可以用于渲染，最后编辑时的点击事件可以触发函数改变state的。这种才是正常的吧😂

**Comment by JackLian** [comment]
并没有，编辑器内不触发数据源和js逻辑，不会执行的，产品上也不建议这么做

**Comment by charmtiger** [comment]
不对吧，比如antd的列表组件。如果没有数据源的数据，那么就要在编辑态额外准备mock数据，那体验太差了

**Comment by JackLian** [comment]
体验并不差，目前这个体系就是这么设计的，这个能力目前不会提供

**Comment by charmtiger** [comment]
好的，这一块保持现状就好，谢啦
