### ISSUE TITLE
this.i18n获取为空？

### ISSUE THREAD

**Issue by vjzning** [alibaba/lowcode-engine#1189]
官方的demo 测试效果
用@alilc/lowcode-react-renderer 渲染的时候  schema中传递的是componentsTree[0]， 那 i18n json对象怎么传递进去呢？
![image](https://user-images.githubusercontent.com/5629031/198513517-72198533-936d-452e-8a11-e376aeebd451.png)

**Comment by liujuping** [comment]
看一下这个文档

https://www.yuque.com/lce/doc/ikdcvk#TxrqE

**Comment by vjzning** [comment]
> 看一下这个文档
> 
> https://www.yuque.com/lce/doc/ikdcvk#TxrqE

看到这个文档后，渲染模式下传入messages: i18n 正常了， 但是在编辑器中用的是 common.skeletonCabin.Workbench这种初始化，怎么传message？ 我试了 这2种方式 都不行。
    config.set('messages', projectSchema.i18n);
    project.simulatorHost.set('messages', projectSchema.i18n);

**Comment by vjzning** [comment]
通过看源码 用这种方式设置
project.simulatorHost.renderer._appContext.utils.i18n.messages = schema.i18n  可以显示出来。 
没有暴露设置的函数吗。

**Comment by JackLian** [comment]
utils下的都是通过appHelper自行注入的，所以renderer._appContext.utils.i18n 这个i18n 是你可以自己定义的

**Comment by JackLian** [comment]
最新的综合场景demo中提供了相关实现，可以拉源码看看
https://github.com/alibaba/lowcode-demo/tree/main/demo-general
