### ISSUE TITLE
请问怎么覆写物料的setter 配置

### ISSUE THREAD

**Issue by leehomeok** [alibaba/lowcode-engine#119]
![image](https://user-images.githubusercontent.com/13464485/157796464-7e050583-30e6-4fd5-a7d7-4ea89e98d21d.png)

如图这个 setter override 的完整配置应该放在项目的什么位置？

**Comment by LeoYuan** [comment]
https://github.com/alibaba/lowcode-demo/blob/a28f8fb0cee22302c5fd60d132cfd5812d5d2e79/src/universal/plugin.tsx#L62

其实就是保证传入到 setAssets 的 json 结构为物料描述结构就好，目前 demo 中用了远程格式，属于更高阶的用法~

假如是想修改 fusion 的物料元数据，可以通过写一个插件，插件内调用 [registerMetadataTransducer](https://www.yuque.com/lce/doc/mu7lml#LRXhp) 来完成修改~
