### ISSUE TITLE
[设置器]如何修改同级属性的 Setter 的 props

### ISSUE THREAD

**Issue by DiligentNezha** [alibaba/lowcode-engine#1195]
## **Describe the bug (required)** / **详细描述 bug（必填）**

比如小数位数设置为 2，则步长、最大值、最小值对应的NumberSetter 的 precision 也需要同步改成2，我试了下 setExtraPropValue 没有成功
<img width="620" alt="image" src="https://user-images.githubusercontent.com/20829924/199222080-6b5f08bd-6b97-450f-aaf7-59b9cf83850c.png">
<img width="620" alt="image" src="https://user-images.githubusercontent.com/20829924/199222086-c427be8b-b3d2-47c0-9a9b-6e2b4c412ee2.png">

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

---

English version example：

中文版示例：

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
可以有API 支持修改同级属性的 Setter 的 props ，修改后对应的 Setter 渲染以修改后的属性进行同步渲染

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.15] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.5] / 低代码引擎扩展包版本
 - Browser [e.g. edge] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by hzd822** [comment]
目前还不支持联动修改setter的props属性

**Comment by DiligentNezha** [comment]
> 
我翻了下 ArraySetter 和 ObjectSetter 的源码，以及 editor-skeleton，了解到 ArraySetter 和 ObjectSetter 只能改变单个属性局部的渲染，然后顺着找到了 setting-primary-pane，我通过 SettingPropEntry 把 #props 里的 items 给改变了，但是没有找到合适的方法让 setting-primary-pane 重新渲染让 items 生效，大佬指导
<img width="1036" alt="image" src="https://user-images.githubusercontent.com/20829924/199381647-f212b7e7-6f28-4407-9c65-0ce51547c881.png">

**Comment by hzd822** [comment]
不建议这么改吧，这个相当于重新生成了一份field，然后把原先的替换掉，后面看下能否直接在field里面开一些api让外部能修改setter的props @LeoYuan

**Comment by DiligentNezha** [comment]
> 不建议这么改吧，这个相当于重新生成了一份field，然后把原先的替换掉，后面看下能否直接在field里面开一些api让外部能修改setter的props @LeoYuan

通过这种方式也可以达到修改 Setter 的 props 的效果
