### ISSUE TITLE
lowcode-engine npm run build 构建失败

### ISSUE THREAD

**Issue by Tstrive** [alibaba/lowcode-engine#1196]
![image](https://user-images.githubusercontent.com/30211588/199388761-307e8bce-8cb3-4a7f-98ae-bf08c600ee4f.png)
![image](https://user-images.githubusercontent.com/30211588/199388811-9e40b319-0964-4d28-a549-e8f2443619de.png)

node 版本
![image](https://user-images.githubusercontent.com/30211588/199388997-3c1c7f09-b615-407f-8b80-ac2d04a81d00.png)
npm  run build 报错信息   wsl 和 linux 都报该错   有没有大佬遇到过这个问题   npm run start 没问题

**Comment by JackLian** [comment]
run build 是要自己打npm包？

**Comment by JackLian** [comment]
这个项目目前只提供umd方式使用，参考这个文档
https://lowcode-engine.cn/docV2/start-with-lce

**Comment by Tstrive** [comment]
> run build 是要自己打npm包？

是的

**Comment by Tstrive** [comment]
> 这个项目目前只提供umd方式使用，参考这个文档 https://lowcode-engine.cn/docV2/start-with-lce

好的
