### ISSUE TITLE
自定义组件在meta.ts中设置defaultValue无效

### ISSUE THREAD

**Issue by PLUTO06210331** [alibaba/lowcode-engine#1202]
我通过自定义组件的方式新建一个Process组件，配置完成后执行 npm run lowcode:dev和npm run lowcode:build后在生成的meta.ts的configure.props中设置 defaultValue: 30 页面没有默认展示

![image](https://user-images.githubusercontent.com/33271366/199672858-117460eb-c84f-4046-91cf-498ce4e30c37.png)
![image](https://user-images.githubusercontent.com/33271366/199672904-176f4252-d875-4c27-95ad-cdd4b32b986c.png)

**Comment by otakuXv** [comment]
@PLUTO06210331 建议写在 snippets 中

**Comment by liujuping** [comment]
setter.initialValue 优先级大于 defaultValue 的配置。可以删掉 initialValue 再看看，或者配置到  initialValue 上面
