### ISSUE TITLE
Rax 自定义组件无法在面板中设置样式

### ISSUE THREAD

**Issue by youngerbyte** [alibaba/lowcode-engine#1203]
## **Describe the bug (required)** / **详细描述 bug（必填）**
提供的Demo中，Rax自定义组件不能设置style
Demo地址：https://github.com/youngerbyte/lowcode-engine-rax-demo

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
1.git clone https://github.com/youngerbyte/lowcode-engine-rax-demo
2.yarn && yarn start
3.自动打开浏览器后，拖动组件
4.选中右侧面板的“样式面板”，设置样式相关属性，但是不生效

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
期望demo中的Rax组件能够设置样式
## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
<img width="337" alt="截屏2022-11-03 21 02 25" src="https://user-images.githubusercontent.com/12269663/199727766-fff4719f-b145-4837-8ed3-59140fbe4e30.png">
chrome 版本 107.0.5304.87（正式版本） (x86_64)
materials / plugins / tools / 其他物料 / 插件 / 工具链版本: 参见demo

**Comment by liujuping** [comment]
设置方式1：自定义组件接受 style 对象

设置方式2：自定义组件接受 className 值，再将 style 对象和 className 结合一起处理，放到 schema 的 css 中。这个需要自己通过插件实现。

![image](https://user-images.githubusercontent.com/11935995/200528361-78066b12-fa78-43b8-949f-52f09c294614.png)

可以参考现有的 react 自定义组件，现在的逻辑符合预期。

**Comment by youngerbyte** [comment]
> 设置方式1：自定义组件接受 style 对象
> 
> 设置方式2：自定义组件接受 className 值，再将 style 对象和 className 结合一起处理，放到 schema 的 css 中。这个需要自己通过插件实现。
> 
> ![image](https://user-images.githubusercontent.com/11935995/200528361-78066b12-fa78-43b8-949f-52f09c294614.png)
> 
> 可以参考现有的 react 自定义组件，现在的逻辑符合预期。

【设置方式1：自定义组件接受 style 对象 】这个自己的确可以实现；
【设置方式2：自定义组件接受 className 值... ...】拿Avatar举例，Avatar props有className，无style属性，我跟踪createElement在创建React自定义组件Avatar时候没有传className只传了style(见下图)，但是样式却生效了呢；
avatar组件代码地址：https://github.com/alibaba-fusion/next/blob/master/src/avatar/index.jsx

**Comment by liujuping** [comment]
设置方式1 和 方式2 是只需要用一种的，这里的 Avatar 组件有 style 属性了样式也就生效了。

至于设置方式 2 目前对外没有 demo，得自己按照样式生效的原理研究一下。
