### ISSUE TITLE
使用demo项目通过`build-plugin-alt`调试本地物料时无法使用预览功能

### ISSUE THREAD

**Issue by Dogtiti** [alibaba/lowcode-engine#1205]
### 本地启动物料开发时通过`build-plugin-alt`插件进行调试时，只能在编辑界面进行调试，预览时会报找不到component
![image](https://user-images.githubusercontent.com/38354472/199878288-7c818db8-0a88-4d03-9518-4dc11efc091e.png)

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

### 本地启动物料库和demo项目，物料配置调试模式
```js
 module.exports = {
    //...
  plugins: [
    // ...
    [
      '@alilc/build-plugin-alt',
      {
        type: 'component',
        library,
        inject: true,
        openUrl: 'http://localhost:5556?debug',
      },
    ],
   
  ],
};

```

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为
### 能正确预览到本地注入的物料
---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: @latest / 低代码引擎版本
 - AliLowCodeEngineExt version: @latest / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] /  @latest
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本  @latest

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by LeoYuan** [comment]
@eternalsky 大佬看看预览态是不是要加什么配置项~

**Comment by eternalsky** [comment]
查看一下预览的url 上有没有查询参数 debug

**Comment by Dogtiti** [comment]
@eternalsky 
<img width="1416" alt="image" src="https://user-images.githubusercontent.com/38354472/199880742-aefad48e-7e59-4c2c-9b65-ba56083f6fdc.png">
加了好像也不行

**Comment by eternalsky** [comment]
看起来注入已经完成了，但是不知道因为什么原因没有解析处理。能提供一些源代码方便本地调试吗，否则的话可能只能你自己看下 inject 的源代码来调试一下了。

**Comment by Dogtiti** [comment]
@eternalsky 好的 稍等我去创建一个repo

**Comment by Dogtiti** [comment]
@eternalsky  https://github.com/Dogtiti/test-alt-materials 两个项目直接启动就好了 可以直接复现
<img width="515" alt="image" src="https://user-images.githubusercontent.com/38354472/199886313-7d8b1372-8407-47e8-b6cc-68cdd8e83121.png">
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/38354472/199886351-f15ac116-c8d5-4063-8f04-a51e3ba213e4.png">
<img width="1426" alt="image" src="https://user-images.githubusercontent.com/38354472/199886415-14e381eb-6837-4591-bba3-daf403599344.png">

**Comment by eternalsky** [comment]
@Dogtiti 我们对多组件的预览支持出了一点问题，已经发了beta 版修复。demo 里升级到这个版本可以修复，@alilc/lowcode-plugin-inject@1.2.0-beta.1

**Comment by lsycxyj** [comment]
你们是不是忘了发包

**Comment by eternalsky** [comment]
@lsycxyj @alilc/lowcode-plugin-inject@1.2.0 已发
