### ISSUE TITLE
[Error] react.development.js:1407 Uncaught TypeError: Object prototype may only be an Object or null: undefined

### ISSUE THREAD

**Issue by SilenceSunshine** [alibaba/lowcode-engine#1208]
此问题比较急，跪求各位大神帮忙看看
### 一、版本
  "@alifd/next": "^1.26.6",
    "@alilc/lowcode-plugin-inject": "^1.1.3",
    "@alilc/lowcode-react-renderer": "^1.0.15",
    "@alilc/lowcode-utils": "^1.0.15",
    "antd": "^4.23.6",
     "react": "^18.2.0",
    "react-dom": "^18.2.0",
    "react-router": "^6.4.2",
    "react-router-dom": "^6.4.2",

### 二、代码
import React from 'react';
import ReactRenderer from '@alilc/lowcode-react-renderer';
import { buildComponents, assetBundle, AssetLevel, AssetLoader } from '@alilc/lowcode-utils';
import { injectComponents } from '@alilc/lowcode-plugin-inject';

const getLSName = (scenarioName: string, ns = 'projectSchema') => `${scenarioName}:${ns}`;

const getScenarioName = function () {
    if (location.search) {
        return new URLSearchParams(location.search.slice(1)).get('scenarioName') || 'index';
    }
    return 'index';
};

const getPackagesFromLocalStorage = (scenarioName: string) => {
    if (!scenarioName) {
        console.error('scenarioName is required!');
        return;
    }
    return JSON.parse(window.localStorage.getItem(getLSName(scenarioName, 'packages')) || '{}');
};

const getProjectSchemaFromLocalStorage = (scenarioName: string) => {
    if (!scenarioName) {
        console.error('scenarioName is required!');
        return;
    }
    return JSON.parse(window.localStorage.getItem(getLSName(scenarioName)) || '{}');
};

export const Test = () => {
    const [data, setData] = React.useState({});

    async function init() {
        const scenarioName = getScenarioName();
        const packages = getPackagesFromLocalStorage(scenarioName);
        const projectSchema = getProjectSchemaFromLocalStorage(scenarioName);
        const { componentsMap: componentsMapArray, componentsTree } = projectSchema;
        const componentsMap: any = {};
        componentsMapArray.forEach((component: any) => {
            componentsMap[component.componentName] = component;
        });
        const schema = componentsTree[0];

        const libraryMap = {};
        const libraryAsset: any[] = [];
        packages.forEach(({ package: _package, library, urls, renderUrls }) => {
            libraryMap[_package] = library;
            if (renderUrls) {
                libraryAsset.push(renderUrls);
            } else if (urls) {
                libraryAsset.push(urls);
            }
        });

        const vendors = [assetBundle(libraryAsset, AssetLevel.Library)];

        // TODO asset may cause pollution
        const assetLoader = new AssetLoader();
        await assetLoader.load(libraryAsset);
        const components = await injectComponents(buildComponents(libraryMap, componentsMap));
        setData({
            schema,
            components,
        });
    }
    const { schema, components } = data;

    if (!schema || !components) {
        init();
        return <div>loading</div>;
    }

    return (
        <div>
            <ReactRenderer schema={schema} components={components as any} />
        </div>
    );
};

### 三、错误提示
![image](https://user-images.githubusercontent.com/19547310/200213377-ce09fb5e-015b-49ab-b6f0-24cc6bdb0862.png)

**Comment by hooper-hc** [comment]
为啥关了，我也遇到了类似问题

**Comment by leesren** [comment]
我用 vite 也遇到同样这个问题。
`[plugin:vite:resolve] Module "events" has been externalized for browser compatibility, imported by xxx`
我猜测应该是 vite 没有使用 events 这个包，所以安装这个包就可以了。
`npm i events`
@hooper-hc
