### ISSUE TITLE
低代码引擎页面无法显示

### ISSUE THREAD

**Issue by xiongyechang** [alibaba/lowcode-engine#1210]
# 低代码引擎页面无法显示

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
先切换到图像编辑器页面，低代码引擎页面可以显示出来，然后切换到其他的页面，再切换到图形编辑器页面，低代码引擎页面无法显示，并且没有报错

页面如下：
![466E7C6B-8906-41C4-99CC-45A7012C362F](https://user-images.githubusercontent.com/28780680/200253964-72e9cbec-609c-477f-a899-169dd56f6539.png)

代码如下：
![20221107154824](https://user-images.githubusercontent.com/28780680/200255132-adb87dcb-08d8-4c52-8ef6-e6c0dc0de652.jpg)

![20221107154810](https://user-images.githubusercontent.com/28780680/200255166-f9808d95-7c56-4582-9de4-8b80000bb0fa.jpg)

![AA5B7973-A926-475F-BAA5-DF74D4375975](https://user-images.githubusercontent.com/28780680/200255262-a44045b4-a7b0-4be1-8bf6-237892ab7db7.png)

**Comment by JackLian** [comment]
麻烦提供下可复现的demo源码
