### ISSUE TITLE
物料数据源自定义请求，如何支持嵌套参数（从其他项目中获取的参数）和避免跨域问题

### ISSUE THREAD

**Issue by SilenceSunshine** [alibaba/lowcode-engine#1216]
在使用物料面板的时候，遇到了以下问题，路过的各位大神救救孩子吧
<img width="726" alt="image" src="https://user-images.githubusercontent.com/19547310/200567250-bf47629a-c71d-4f17-bbcd-e2b10333a16f.png">

**Comment by JackLian** [comment]
1. 跨域不是这个能解决的，建议多了解下什么是跨域问题，网上有很多资料 https://zhuanlan.zhihu.com/p/414130685
2. 可以从url上把参数带进来
