### ISSUE TITLE
通过 project api 修改国际化，设计区域（渲染画布）不渲染当前语言文字

### ISSUE THREAD

**Issue by Winna-wnn** [alibaba/lowcode-engine#1217]
## **Describe the bug (required)** / **详细描述 bug（必填）**

增加一个plugin , 实现切换 **渲染画布国际化**

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
1. 增加一个plugin ,主要功能是实现 **渲染画布** 语言切换；
2. project scheme中 i18n已有国际化数据；  
```
"i18n": {
    "zh-CN": {
      "i18n-jwg27yo4": "你好",
      "i18n-jwg27yo3": "${name}博士"
    },
    "en-US": {
      "i18n-jwg27yo4": "Hello",
      "i18n-jwg27yo3": "Doctor ${name}"
    }
  }
```
3. 初始化引擎；

```
import { init } from '@alilc/lowcode-engine';

init(elem, {
  locale: 'zh-CN',
});
```

4. 该plugin简要方法修改方法如下：  
```
import { project } from '@alilc/lowcode-engine';

project.simulatorHost.set('locale', 'en-US');
project.simulator.rerender()
```
5. 渲染画布中绑定了国际化数据的字段并未显示当前语言的文本；

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.14] / 低代码引擎版本

**Comment by vjzning** [comment]
切换语言可以重新 加载 schema 就可以
project.importSchema(project.exportSchema())

**Comment by Winna-wnn** [comment]
> 切换语言可以重新 加载 schema 就可以 project.importSchema(project.exportSchema())

加上这个实现了
