### ISSUE TITLE
官网 demo 出码以后的项目运行报错

### ISSUE THREAD

**Issue by WooodHead** [alibaba/lowcode-engine#122]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
官网 demo 出码以后的项目运行报错

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1、下载 demo 项目并运行
2、点击“出码”按钮下载 zip
3、运行 ali-lowcode-generated-sources 项目
4、报错，无法运行
![image](https://user-images.githubusercontent.com/5668806/158106815-55a52aa8-8053-4219-9c3c-ba3757b957d8.png)
![image](https://user-images.githubusercontent.com/5668806/158106820-d0872e75-7dff-45ed-8fd4-eca101efeb82.png)

```json
{
  "name": "@alilc/lowcode-demo",
  "version": "1.0.2",
  "description": "Low-Code Engine 低代码搭建引擎 Demo 项目",
  "repository": "git@github.com:alibaba/lowcode-demo.git",
  "license": "MIT",
  "main": "index.js",
  "scripts": {
    "start": "build-scripts start --disable-reload --port 5556",
    "build": "build-scripts build",
    "pub": "node ./scripts/watchdog.js && npm pub"
  },
  "files": [
    "build"
  ],
  "config": {},
  "dependencies": {
    "@alilc/lowcode-plugin-code-editor": "^1.0.1",
    "@alilc/lowcode-plugin-code-generator": "^1.0.2",
    "@alilc/lowcode-plugin-components-pane": "^1.0.2",
    "@alilc/lowcode-plugin-datasource-pane": "^1.0.0",
    "@alilc/lowcode-plugin-inject": "^1.0.0",
    "@alilc/lowcode-plugin-manual": "^1.0.0",
    "@alilc/lowcode-plugin-schema": "^1.0.0",
    "@alilc/lowcode-plugin-simulator-select": "^1.0.0",
    "@alilc/lowcode-plugin-undo-redo": "^1.0.0",
    "@alilc/lowcode-plugin-zh-en": "^1.0.0",
    "@alilc/lowcode-react-renderer": "^1.0.0",
    "@alilc/lowcode-setter-behavior": "^1.0.0",
    "@alilc/lowcode-setter-title": "^1.0.2"
  },
  "devDependencies": {
    "@alilc/lowcode-engine": "^1.0.0",
    "@alilc/lowcode-engine-ext": "^1.0.0",
    "@alilc/lowcode-types": "^1.0.0",
    "@alib/build-scripts": "^0.1.18",
    "@types/events": "^3.0.0",
    "@types/react": "^16.8.3",
    "@types/react-dom": "^16.8.2",
    "@types/streamsaver": "^2.0.0",
    "build-plugin-fusion": "^0.1.0",
    "build-plugin-moment-locales": "^0.1.0",
    "build-plugin-react-app": "^1.1.2",
    "tsconfig-paths-webpack-plugin": "^3.2.0"
  }
}

```
Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by LeoYuan** [comment]
this.state.info.info 可以先写成 this.state.info?.info，这里我们在如何定义「初始化渲染时」理解有些歧义，正在厘清中~

![image](https://user-images.githubusercontent.com/1195765/158132648-70f23cc0-af6d-4b2c-8dae-efea0e757d32.png)
