### ISSUE TITLE
引擎 DEMO 缺少国际化相关的能力，待补充

### ISSUE THREAD

**Issue by liujuping** [alibaba/lowcode-engine#1222]
## **Describe the bug (required)** / **详细描述 bug（必填）**

引擎 DEMO 缺少国际化相关的能力

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---
1.https://github.com/alibaba/lowcode-demo
2.需要根据 https://www.yuque.com/lce/doc/ikdcvk 文档进行改造才能使用国际化的能力

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

期望 demo 可以提供开箱即用的国际化能力

**Comment by xugx29** [comment]
关于datepicker等组件中英文混杂的情况，经过我的测试，得到的结论是:
1、所有的html模版中的moment.js要保持与node_modules中的版本一致;
2、注意，src/service/assets.json中，momentjs除了要引用本身以外，还要引入zh-cn的中文包，如下图所示;

<img width="1071" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/13448173/5d2d350b-42d7-4a2d-8f9e-6c696a30b154">

上述操作结束后，如果中英文混杂的情况没解决，需要在页面的tsx文件中，执行moment.locale('zh-cn')
