### ISSUE TITLE
官网的  'https://lowcode-engine.cn/api/get_usage'  这个接口报跨域

### ISSUE THREAD

**Issue by huangapple** [alibaba/lowcode-engine#1228]
需求是我们在demo的基础上做开发， 搬过来时发现点问号帮助那个功能， 有个官方的接口报了跨域， 官方能否解决一下
![image](https://user-images.githubusercontent.com/10572028/201560028-0f54385e-6e06-4c39-b1bc-28591955f4f1.png)

官网的  'https://lowcode-engine.cn/api/get_usage'  这个接口报跨域

**Comment by alvarto** [comment]
跨域受限于阿里内安全规则的限制，没有办法放宽。因此这个插件可以不注册：

```
// plugin.tsx
// 注释掉这里：
// await plugins.register(ManualPlugin);
```

**Comment by huangapple** [comment]
有点可惜啊， 感觉这里面的帮助内容挺有用的。我看下是不是只有这个接口， 是的话服务端做个转发， 或直接写死在里面好 。

**Comment by alvarto** [comment]
嗯据我了解应该是只有这个接口，你控制了后端可以直接转发并追加 CORS 头

**Comment by huangapple** [comment]
我改成这个API接口外部传入吧。不传默认用你们的这个
https://lowcode-engine.cn/api/get_usage
我们本地化部署就传我们自己的后端代理地址
