### ISSUE TITLE
母子表格切换数据源， 组件自动消失

### ISSUE THREAD

**Issue by leoner** [alibaba/lowcode-engine#123]
https://alifd.alicdn.com/npm/@alilc/lowcode-demo@1.0.2/build/index.html

![image](https://user-images.githubusercontent.com/546535/158117944-b2e8dedd-1f2d-411b-8785-e24d60cdc930.png)

就是选择后， 母子表格这个组件就自动删除了。

**Comment by leoner** [comment]
![image](https://user-images.githubusercontent.com/546535/158552873-8c9b9ae0-5ab2-4841-9a78-21a69bd0bdf0.png)

![image](https://user-images.githubusercontent.com/546535/158552907-219ddf12-eeb5-4ca7-865b-e92387ca93e4.png)

就是选择表格组件后， 这里的是否循环只要切换下， 表格组件也是消失了， 不知道是不是和上面同样的问题。

**Comment by alvarto** [comment]
跟这个 issue 应该相关：https://github.com/alibaba/lowcode-engine/issues/31
