### ISSUE TITLE
低代码引擎如何通过乾坤嵌入主项目，官方有实践不？

### ISSUE THREAD

**Issue by ajl512** [alibaba/lowcode-engine#1232]
低代码引擎通过qiankun嵌入主项目，
![image](https://user-images.githubusercontent.com/47838397/201846296-b8d0120a-1d5f-4797-87cd-45d463643633.png)
出现两个问题
1. 两个资源404； 查找后，是`https://alifd.alicdn.com/npm/@alilc/lowcode-engine@1.0.14/dist/js/engine-core.js`中需要加载这两个资源，资源域名使用的是getPublicPatch => document.currentScript的方式，而qiankun是通过`import-html-entry 框架注释掉 script 标签后，会先用 fetch 请求到内容，然后使用 eval 执行内容`, script标签已经被去除，那么document.currentScript获取的就是null了，所以加载拼接请求路径前缀地址时就成了空，所以请求404；
2. window上一些全局变量为空报错；
3. 子项目上加ignore后，物料库设置不上；
4. 主项目也把低代码的各个CDN地址通过script引入，解决了全局变量报错的问题；
5. 但是依旧解决不了物料库的问题；与子项目的`https://alifd.alicdn.com/npm/@alilc/lowcode-engine@1.0.14/dist/js/engine-core.js`相关，但是放开，页面也只是会一直loading而已，物料库依旧设置不上

**Comment by Shijf** [comment]
这个貌似在 乾坤 issue 里有说明，https://github.com/umijs/qiankun/issues/718 可以看看这个？

**Comment by WHSnhcZDYRZC** [comment]
可以去看下这个库的解决方案哦
https://github.com/WHSnhcZDYRZC/umi4-lowcode-engine-solutions

**Comment by dannykbsoul** [comment]
> 可以去看下这个库的解决方案哦 https://github.com/WHSnhcZDYRZC/umi4-lowcode-engine-solutions

你好 我看你是在主应用加载子应用资源方式实现的，这样不会污染到主应用的环境么 😂能直接让资源加载放在子应用中么，麻烦大佬解惑🙏

**Comment by homestylew** [comment]
> > > 可以去看下这个库的解决方案哦https://github.com/WHSnhcZDYRZC/umi4-lowcode-engine-solutions
> > 
> > 
> > 你好我看你是在主应用加载子应用资源的方式实现的，这样不会污染到主应用的环境么😂可以直接让资源加载放在子应用中么，麻烦大佬解惑🙏@WHSnhcZDYRZC
> 
> 不好意思很久才看到通知。会影响主应用环境，并且 qiankun 的两种 css 解决方案都会有一些问题，你可以自己实现一个 类似于 vue 的 scoped ，或者写 className 的时候注意每次手动加上 一个前缀 比如子应用名称，使得唯一。后续有问题你可以往哪那个仓库中 提 iss，我能及时看到，并处理。

js也会污染啊，有正确的办法吗

**Comment by chestnut647** [comment]
window上一些全局变量为空报错问题， 可以通过配置松散模式解决： sandbox: {loose:true}：https://github.com/umijs/qiankun/issues/1575
