### ISSUE TITLE
开发环境，

### ISSUE THREAD

**Issue by ye-jeck** [alibaba/lowcode-engine#1233]
## 接口报跨域问题，但是我在其他项目里面能正常请求，在这里请求就有问题

详细复现步骤：
![lQLPJxbgKnYDVr3NAxDNAxSwsvJgMZ37j_0DcFbzucDOAA_788_784](https://user-images.githubusercontent.com/66102780/201902636-7972d1d0-52f2-43f7-83cc-c50918bd17fe.png)

**Comment by JackLian** [comment]
建议了解下跨域问题的相关知识，这里并不是选了支持跨域就可以变成能跨域的意思
