### ISSUE TITLE
如何引用第三方 JS 资源？

### ISSUE THREAD

**Issue by guojb824** [alibaba/lowcode-engine#1234]
事件回调函数中需要用到第三方库，如何在线引入第三方库？

附：
宜搭的方案：
https://www.yuque.com/yida/support/ocmxyv#dVs2N

**Comment by JackLian** [comment]
首先，这是个引擎，提供的是底层技术层面的方案啊，考虑的是标准实现路径，参考这个文档：https://lowcode-engine.cn/docV2/cse4oy
另外宜搭是产品层面的方案，考虑的如何给用户提供使用形式，这方面怎么定义都行，你可以定义自己的实现
