### ISSUE TITLE
1.0.16版本，无法设置parentWhitelist: ["Page"]

### ISSUE THREAD

**Issue by yz1311** [alibaba/lowcode-engine#1235]
## **如何复现 bug？（必填，非常重要）**

我有一个自定义组件，设置只能是Page的子节点
```
 "component": {
      isContainer: true,
      // isModal: true,
      nestingRule: {
        parentWhitelist: ["Page"]
      },
    }
```
 这个设置在1.0.15中是有用的，但是在1.0.16中，这个组件无法拖动到Page节点下面了

## **预期行为（必填，非常重要）**
配置生效

**Comment by liujuping** [comment]
Page 组件设置了 childWhitelist 所以无法拓展进去，只在子元素设置 parentWhitelist 而忽略了 父元素的 childWhitelist 是有问题的，所以在 1.0.16 版本进行了修复。

https://github.com/alibaba/lowcode-materials/pull/31

**Comment by yz1311** [comment]
> 

请问，如果我需要设置Dialog组件只能拖动到Page节点下面，应该如何操作?

**Comment by liujuping** [comment]
参考：https://www.yuque.com/lce/doc/sw3ae62xd85n6oa4
