### ISSUE TITLE
出码模块， 想要加新的东西，  目前好像只能改源码？有办法在不改源码的情况下做一些扩展或调整吗？

### ISSUE THREAD

**Issue by huangapple** [alibaba/lowcode-engine#1242]
目前看暴露的接口， 比如 只能生成项目， 没有别的配置项
export interface IProjectBuilder {
    generateProject: (schema: ProjectSchema | string) => Promise<ResultDir>;
}

CodeGenerator.solutions
也只有
![image](https://user-images.githubusercontent.com/10572028/202410144-a33b5278-21f6-4b1e-b575-68e82a75247a.png)
没有提供 外部 添加一个生成方案的方式

const projectBuilder = CodeGenerator.solutions.icejs({inStrictMode: true});
这个参数也比较少
![image](https://user-images.githubusercontent.com/10572028/202410368-f5098580-a6fa-47f8-85d3-355f0fb3ce58.png)

想请问一下， 比如我想把 生成文件从js改成ts， 应该如何做？ 想把ice1.x升级到3.x， 应该如何做？
一定要编译源码重新发布npm吗？还是可以在外部直接调整参数， 或者 添加一个生成模板的方式去实现？？
@Clarence-pan  希望能得到指导

BTW: 编译源码, win下老是失败， 用了wsl还是失败。

**Comment by iqinning** [comment]
可以参考源码在外面自定义一个解决方案的

**Comment by huangapple** [comment]
嗯， 目前采用的方法是在他生成的代码基础上， 再做一些加加减减。比较低端， 但成本也比较低。

**Comment by LeoYuan** [comment]
我理解是不是通过：

1. 生成一个自己的 solution；

```
npx @alilc/lowcode-code-generator init-solution
```

2. 利用项目导出的公共的 plugins 去组织你的定制 solution；
3. 使用新的 solution 去出码；

更好一点？

**Comment by huangapple** [comment]
是， 谢谢指导！
