### ISSUE TITLE
alt脚手架初始化时未包含inject配置

### ISSUE THREAD

**Issue by JackLian** [alibaba/lowcode-engine#1245]
目前用户通过脚手架创建组件和插件时调试流程不顺，原因是始化时未包含inject配置，而文档中信息无法帮助用户跨域这个障碍，建议以下方案二选一：
1. 组件和plugin的脚手架默认配置中增加inject配置
2. https://www.yuque.com/lce/doc/ulvlkz 优化该文档

**Comment by eternalsky** [comment]
@JackLian 目前提供两套开发模式，本地开发模式和 inject 模式。两种模式在对应的配置下都是可以正常使用的，非 inject 下open 本地连接，inject 模式下默认打开 lowcode-engine demo。目前插件、setter 的脚手架默认走 inject 模式，组件因为脚手架在金禅那边暂时未调整。

**Comment by eternalsky** [comment]
已优化文档，去除误解描述。现在默认都走本地模式，插件有对应的指导描述如何开启。
