### ISSUE TITLE
物料是不是没法直接使用自己开发的组件库？

### ISSUE THREAD

**Issue by Go7hic** [alibaba/lowcode-engine#125]
看了一下文档 https://www.yuque.com/lce/doc/funcv8
我们内部开发的组件库是不是没法直接接入到这个物料里来使用？按照定制物料的方法来弄好像也不太行

**Comment by LeoYuan** [comment]
需要定义一套物料描述，如 demo 中的 [assets.json](https://github.com/alibaba/lowcode-demo/blob/6a26531007e79ed83ec074ec515f38db2a676756/public/assets.json) 文件

**Comment by Go7hic** [comment]
> 需要定义一套物料描述，如 demo 中的 [assets.json](https://github.com/alibaba/lowcode-demo/blob/6a26531007e79ed83ec074ec515f38db2a676756/public/assets.json) 文件

只需要修改这个文件就可以了？组件不是按照你们那个阿里前后端协议实现的也可以么，比如我想接入 bnt-design，这个文件里应该怎么修改呢

**Comment by liujuping** [comment]
参考 https://lowcode-engine.cn/doc?url=funcv8 的 配置低代码开发环境 部分。

配置低代码相关的配置。
