### ISSUE TITLE
重写和不重写requestHandler，网络请求返回的数据格式不一致

### ISSUE THREAD

**Issue by jcljcljcl** [alibaba/lowcode-engine#1251]
## **Describe the bug (required)** / **详细描述 bug（必填）**

我们在编辑态的reactrender中重写了requestHandler函数，网络请求返回的数据看起来被额外包装了一层data；在渲染态没有重写requestHandler函数，网络请求返回的数据看起来没有额外包装data。
看了源码发现重不重写走的流程差别很大，想问一下，当时这么设计的理念是什么样子？后续这块推荐怎么做？后续升级会走什么方向？

---

![image](https://user-images.githubusercontent.com/55192369/203263450-ce35c939-29a0-428d-bb1c-6878f389cdaa.png)

**Comment by jcljcljcl** [comment]
还有一个问题，现在不使用requestHandler是不能使用willFetch、shouldFetch等函数的，这个我也不理解，为什么没有自定义requestHandler还不能使用willFetch这类函数，反而自定义了requestHandler却可以使用willFetch这类函数

**Comment by JackLian** [comment]
> 还有一个问题，现在不使用requestHandler是不能使用willFetch、shouldFetch等函数的，这个我也不理解，为什么没有自定义requestHandler还不能使用willFetch这类函数，反而自定义了requestHandler却可以使用willFetch这类函数

因为没实现好完整...欢迎pr
