### ISSUE TITLE
ProjectSchema的constants 不生效， 是不支持吗？还是我对文档的理解有误？

### ISSUE THREAD

**Issue by huangapple** [alibaba/lowcode-engine#1253]
![image](https://user-images.githubusercontent.com/10572028/203270473-c0427a40-f12f-4b67-8aa7-193d8ccecee2.png)
![image](https://user-images.githubusercontent.com/10572028/203271155-f9e9ea0f-bcf0-4de7-ac5d-1c980e889550.png)
![image](https://user-images.githubusercontent.com/10572028/203271940-075cbb75-f7c0-449f-8469-b99e9c129073.png)
![image](https://user-images.githubusercontent.com/10572028/203271979-0ab89269-9371-4d1f-9ebc-ca62fba28a2c.png)
是不支持吗？还是我对文档的理解有误？

只能在init时 ， 写死吗
```
    appHelper: {
      constants: {
        host: "123456"
      }
    }
```

**Comment by JackLian** [comment]
对，目前就是初始化时一次注入计划

**Comment by JackLian** [comment]
这个有动态修改的诉求场景吗，跟出码不出码的关系不大，出码是从schema到code的过程，现在相当于是不支持动态改，只能在初始化时候注入

**Comment by JackLian** [comment]
> 我的需求是这样的 #498
> 
> 而且 我认为 ProjectSchema 是协议， 应该要根据协议走。
> 
> 动态修改的场景是有的， 每个项目的变量肯定会有不一样， 不可能写死。

如果只是这个需求最简单方案就改成相对地址就好了，用constants也行，但也就是每个设计器初始化时候把constants内容从服务端取过来就好，并不需要写死

**Comment by huangapple** [comment]
目前的做法就是初始化时把constants内容从服务端取过来
```
  appHelper: {
    //注入常量
    constants: projectData?.globalConstants
  }
```
而且我在初始化schema已经处理过一次了
```
    let projectData = ProjectData.getProjectData()
    //这个处理是无效的。
    schema.constants = projectData.globalConstants
    project.importSchema(schema);
```

constants好注入，  utils是函数， 就需要处理一下。
schema定义的 是
```
    /**
     * 应用范围内的全局自定义函数或第三方工具类扩展
     */
    utils?: UtilsMap;
    /**
     * 应用范围内的全局常量
     */
    constants?: JSONObject;


export declare type InternalUtils = {
    name: string;
    type: 'function';
    content: JSFunction | JSExpression;
};
export declare type ExternalUtils = {
    name: string;
    type: 'npm' | 'tnpm';
    content: NpmInfo;
};
export declare type UtilItem = InternalUtils | ExternalUtils;
export declare type UtilsMap = UtilItem[];
```

跟appHelper定义的不太一样， 还要再转一下
```
    /**
     * 与 react-renderer 的 appHelper 一致，  https://lowcode-engine.cn/docV2/nhilce#appHelper
     */
    appHelper?: {
        /** 全局公共函数 */
        utils?: Record<string, any>;
        /** 全局常量 */
        constants?: Record<string, any>;
    };
```

我认为引擎应该统一下， 保留 ProjectSchema 协议约定的做法就好。
