### ISSUE TITLE
在数据源面板以及源码面板， 如何使用在appHelper注入的  util跟constants?

### ISSUE THREAD

**Issue by huangapple** [alibaba/lowcode-engine#1254]
直接  constants 是错的， this.constants 也是错的

**Comment by huangapple** [comment]
在组件的变量绑定上， 是可以通过　this.constants 访问到的。

**Comment by JackLian** [comment]
<img width="798" alt="Screen Shot 2022-11-23 at 12 41 03" src="https://user-images.githubusercontent.com/2149847/203470572-fa8dce52-85a1-458b-b1dd-ee3b860ac292.png">

<img width="624" alt="Screen Shot 2022-11-23 at 12 38 00" src="https://user-images.githubusercontent.com/2149847/203470670-ee6dc2d7-7bdd-4ff8-8fcd-e14ffad3ef37.png">

<img width="1831" alt="Screen Shot 2022-11-23 at 12 41 26" src="https://user-images.githubusercontent.com/2149847/203470686-b40d8231-94ad-49c0-9452-c9c2ff5e14bd.png">

**Comment by huangapple** [comment]
我的问题， 预览时我没有注入。
谢谢指导！

**Comment by huangapple** [comment]
目前在编辑器   以及 预览，  通过 appHelper 注入， 都没问题了。

但导出时还是有问题
导出的结果是这样的
```
export interface IProjectBuilder {
    generateProject: (schema: ProjectSchema | string) => Promise<ResultDir>;
}
```
我通过 schema.constants 注入的,
生成的代码里 constants.ts 有相关的内容。
但是 在具体使用到的文件里却没有引入 constants.ts文件
![image](https://user-images.githubusercontent.com/10572028/203487122-f05ae7c3-5623-4ad6-bdbc-e1edf8f522db.png)

**Comment by JackLian** [comment]
导出是指出码吗，可以单独提个issue

**Comment by huangapple** [comment]
好的， 谢谢
