### ISSUE TITLE
Vue项目可以接入嘛

### ISSUE THREAD

**Issue by L-Angel** [alibaba/lowcode-engine#1258]
Vue项目可以接入嘛

**Comment by JackLian** [comment]
https://lowcode-engine.cn/docV2/blo2wd

**Comment by brizer** [comment]
> https://lowcode-engine.cn/docV2/blo2wd

404

**Comment by ZTrainWilliams** [comment]
https://lowcode-engine.cn/site/docs/faq/faq017
