### ISSUE TITLE
项目出码， 如何使用 constants？通过 ProjectSchema.constants注入， 生成的 constants.ts 有相应内容， 但使用的地方却没有导入该文件

### ISSUE THREAD

**Issue by huangapple** [alibaba/lowcode-engine#1259]
目前在编辑器 以及 预览， 通过 appHelper 注入 constants， 可以正常使用。

但出码时还是有问题

出码的接口是这样的

export interface IProjectBuilder {
    generateProject: (schema: ProjectSchema | string) => Promise<ResultDir>;
}
我通过 schema.constants 注入的,
生成的代码里 constants.ts 有相关的内容。
但是 在具体使用到的文件里却没有引入 constants.ts文件
![image](https://user-images.githubusercontent.com/10572028/203487122-f05ae7c3-5623-4ad6-bdbc-e1edf8f522db.png)

代码执行到该位置会报 _this.constants 为空指针

我导出用的是 ice模板， 我搜索源码， 好像只搜索到rax有引入
![image](https://user-images.githubusercontent.com/10572028/203487619-dd4acada-8232-4ce4-8250-6a5606d26d9e.png)
ice模板用的好像是
![image](https://user-images.githubusercontent.com/10572028/203487692-b1549625-8261-4b49-9383-f06be1dbb171.png)

没看到 引入

请问下这是出码的BUG， 还是我使用姿势的问题？

**Comment by LeoYuan** [comment]
@huangapple 应该是个 bug，没有引入 constants~

急的话，可以先用 state，应该能达成一样的效果~

**Comment by huangapple** [comment]
我先简单的替换了
![image](https://user-images.githubusercontent.com/10572028/203682630-b9475875-ff02-4c0e-9928-cf987c56425c.png)

**Comment by LeoYuan** [comment]
emmm...

不能说不是很粗暴 😄

**Comment by LeoYuan** [comment]
+ @alilc/lowcode-code-generator@1.0.7-beta.2

@huangapple 试一下这个版本哈~

**Comment by huangapple** [comment]
可以用， 很棒！！

**Comment by zxtyjx** [comment]
同楼主的问题，出码是不是同样不支持appHelper中的utils，我订制了utils但是出码后看不到相关的方法
