### ISSUE TITLE
出码过程npm i的时候@alifd/fusion-ui@0.1.3-beta.3找不到

### ISSUE THREAD

**Issue by lijiaxu1996** [alibaba/lowcode-engine#126]
## **新增组件问题详细描述**

1. 搭建好基础页面
![image](https://user-images.githubusercontent.com/59685169/158142946-c1f60c5f-3fcd-4048-9c30-2793c995a35f.png)
2. 点击出码并下载源码包,导入vscode 使用npm i 安装依赖
![image](https://user-images.githubusercontent.com/59685169/158143219-130a0fa7-0e02-4391-86fb-cbd180632944.png)
3.终端报错找不到
![image](https://user-images.githubusercontent.com/59685169/158143318-cc25f2e3-5a57-47f9-b302-3e3a5e2d2630.png)

## **环境**
 - 1.0.1 / 低代码引擎版本
 - 98.0.4758.109（正式版本） (x86_64)
 -  node v14.18.1
 - npm源
 
![image](https://user-images.githubusercontent.com/59685169/158143681-3bd77bc6-a89b-42f2-970b-e7a3a6355eef.png)

**Comment by lijiaxu1996** [comment]
希望这部分依赖能够更新一下~~~

**Comment by mark-ck** [comment]
fixed in @alifd/fusion-ui@1.0.5
