### ISSUE TITLE
Cannot read property 'icejs' of undefined

### ISSUE THREAD

**Issue by yangyangdg** [alibaba/lowcode-engine#1260]
![image](https://user-images.githubusercontent.com/49295228/203491569-f54dddc0-bace-4ebc-a83b-d5c314531065.png)
Cannot read property 'icejs' of undefined

**Comment by huangapple** [comment]
服务端出码我按说明的使用， 没遇到类似问题。

**Comment by yangyangdg** [comment]
> 服务端出码我按说明的使用， 没遇到类似问题。

难道是node版本吗

**Comment by huangapple** [comment]
```
import CodeGenerator from '@alilc/lowcode-code-generator';
```
我是这样导入的
你看下你不是这样？

**Comment by huangapple** [comment]
那不知道， 你试下把版本升级到1.0.6， 我看你写的是 ^1.0.4, 不知道下载的是不是1.0.6， 我的是1.0.6

**Comment by yangyangdg** [comment]
> 
1.0.6也是这样，也不知道问题出在哪里

**Comment by huangapple** [comment]
我在项目外单独的 js文件里
```

const CodeGenerator = require("@alilc/lowcode-code-generator")

let t = CodeGenerator.solutions.icejs()
console.log(t)
```
跟你一样的错。


但我放在项目里  就没问题， 项目是ts的， 可能是因为有经过编译成js？

**Comment by yangyangdg** [comment]
> 

这样可以，非常感谢！！

**Comment by LeoYuan** [comment]
初步判断：
esbuild 通过 bundle: true 把 es 目录打成了 bundle，此时的 export default 被转成了 module.exports.default，导致无法直接拿到，后面我看看怎么调整下，因为是 breaking，可能需要慎重点~

ref:
https://github.com/alibaba/lowcode-engine/blob/4f4ac5115d18357a7399632860808f6cffc33fad/modules/code-generator/scripts/build.js#L48

![image](https://user-images.githubusercontent.com/1195765/203894064-dbe052c2-cda9-451a-aa6b-6f40acc3aff1.png)

**Comment by LeoYuan** [comment]
先关闭 issue~

后面假如做 2.x 再考虑调整 export
