### ISSUE TITLE
出码时候，标签正则兼容问题

### ISSUE THREAD

**Issue by kjts20** [alibaba/lowcode-engine#1263]
#### 错误提示：
<img width="819" alt="image" src="https://user-images.githubusercontent.com/108455342/203528757-3c29ebcb-51ff-4c9a-a393-700715a439d4.png">

#### 源代码是这么写的
<img width="1087" alt="image" src="https://user-images.githubusercontent.com/108455342/203529344-5b1d9f43-d51f-47d3-91a8-2c04f5301a5d.png">

**Comment by LeoYuan** [comment]
![image](https://user-images.githubusercontent.com/1195765/204211578-e9af34fb-3eca-4ab1-af53-e4d414878fa0.png)

在本地测试是 OK 的，在 demo 在线出码确实有问题，你是在 demo 上测试的吧？@kjts20

**Comment by kjts20** [comment]
有标签名带“.” ，出码的时候就会报错。线上demo、把demo拉下来代码都会报错。在node_modules把那段正则修改下就可以。

**Comment by LeoYuan** [comment]
+ @alilc/lowcode-code-generator@1.0.7-beta.3

**Comment by lilithyang2018** [comment]
上面的fix在下面这次更新中被回退
![icejs3_update](https://github.com/alibaba/lowcode-engine/assets/39897706/4cd4485a-9fe5-495c-a5ed-e485afcbbc33)
所以在这之后一直到现在的1.1.9-beta.5版本中 这个bug仍然存在

**Comment by lilithyang2018** [comment]
发现有两种Tab组件
![different_tabs](https://github.com/alibaba/lowcode-engine/assets/39897706/4fef8927-11c1-4af2-91fa-633e894ceb1b)
其中信息输入类的普通型选项卡会导致出码错误
