### ISSUE TITLE
数据源添加请求参数报错或者无效

### ISSUE THREAD

**Issue by leoner** [alibaba/lowcode-engine#127]
https://alifd.alicdn.com/npm/@alilc/lowcode-demo@1.0.2/build/index.html

![image](https://user-images.githubusercontent.com/546535/158144929-fcdbfb68-0c9e-45a5-9901-b0e68f208a9a.png)
添加始终失败。

然后尝试直接在 url 后面添加参数， 就直接报错了。

![image](https://user-images.githubusercontent.com/546535/158145104-13b88bf7-c046-4e00-a0fb-018427d82d30.png)

**Comment by leoner** [comment]
![image](https://user-images.githubusercontent.com/546535/158145541-92577060-0cb2-4c9e-9fcf-f46fa317901b.png)

还有一个就是这个参数的联动效果， 就是前面输入 key, 后面输入内容的时候， 会自动把  key 给同步。

**Comment by liujuping** [comment]
"然后尝试直接在 url 后面添加参数， 就直接报错了。"

您好，这个我这边没有复现，麻烦再详细描述一下复现步骤。

**Comment by leoner** [comment]
> "然后尝试直接在 url 后面添加参数， 就直接报错了。"
> 
> 您好，这个我这边没有复现，麻烦再详细描述一下复现步骤。

额， 这个好像是可以了， 昨天一直不可以。 其他的1个问题还是在， 就是参数添加不上， 和联动的问题

**Comment by leoner** [comment]
本地重新 更新了 lowcode-demo, 然后现在在 url 上直接添加参数是不报错了

![image](https://user-images.githubusercontent.com/546535/158293206-8dbec3c4-fd09-4450-902b-a4d7f01bcdcd.png)

但是这个参数内容的联动更新， 和添加还是继续无效

**Comment by leoner** [comment]
https://dev.g.alicdn.com/ali-lowcode/ali-lowcode-materials/1.1.0/schema.json

然后现在本地还会请求这个 dev 的地址， 也会报错。 没有找到哪里配置的， 感觉不应该请求 dev

![image](https://user-images.githubusercontent.com/546535/158293537-6f14dacb-1931-4ae8-a607-8102bb6710c3.png)

**Comment by leoner** [comment]
![image](https://user-images.githubusercontent.com/546535/158298940-ddf37b6e-c219-4bda-a303-0940008c7aba.png)

![image](https://user-images.githubusercontent.com/546535/158298969-51519e6f-84b1-4883-9ed0-b122dc0cd6a4.png)

还有一个问题， 就是添加请求头的时候， content-type 只能追加？ 就是如何覆盖默认的那个 form?

**Comment by lijiaxu1996** [comment]
> https://dev.g.alicdn.com/ali-lowcode/ali-lowcode-materials/1.1.0/schema.json
> 
> 然后现在本地还会请求这个 dev 的地址， 也会报错。 没有找到哪里配置的， 感觉不应该请求 dev
> 
> ![image](https://user-images.githubusercontent.com/546535/158293537-6f14dacb-1931-4ae8-a607-8102bb6710c3.png)

https://github.com/alibaba/lowcode-engine/issues/94 你可以看看这个，dev开头的不能访问
