### ISSUE TITLE
 npm start throw error @ali/lowcode-engine not found

### ISSUE THREAD

**Issue by proclml** [alibaba/lowcode-engine#1272]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
---
![image](https://user-images.githubusercontent.com/38473196/203897594-b7588f75-eb06-42bd-b373-7f37148f2526.png)

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---
- download demo zip from github
- run `npm install`, success
- run `npm start` got error like image above

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---
run `npm start` success
## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - lowcode-demo version: 1.0.30

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by liujuping** [comment]
@alilc/lowcode-plugin-simulator-select 看看是什么版本，是不是 1.0.2

**Comment by qiliping-mgl** [comment]
@liujuping 我也遇到这个问题，看了下 @alilc/lowcode-plugin-simulator-select 是1.0.2 版本

**Comment by romanticu** [comment]
> @alilc/lowcode-plugin-simulator-select 看看是什么版本，是不是 1.0.2

我也是一样的问题，运行 demo 报这个错 但是 @alilc/lowcode-plugin-simulator-select 1.0.0

改成 1.0.2 就好了

**Comment by romanticu** [comment]
> @liujuping 我也遇到这个问题，看了下 @alilc/lowcode-plugin-simulator-select 是1.0.2 版本

然后叫我
`To install it, you can run: npm install --save @ali/lowcode-engine`

但是运行是会报错

```
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@ali%2flowcode-engine - Not found
npm ERR! 404 
npm ERR! 404  '@ali/lowcode-engine@*' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Comment by liujuping** [comment]
npm i @alilc/lowcode-plugin-simulator-select@1.0.2 试一下

**Comment by qiliping-mgl** [comment]
嗯 我这边已经好了

**Comment by proclml** [comment]
可以了
