### ISSUE TITLE
下拉选项配置不是这么配吗

### ISSUE THREAD

**Issue by lulg** [alibaba/lowcode-engine#128]
![image](https://user-images.githubusercontent.com/28698352/158286186-427a842a-3e5d-4420-8bf6-4529825486e0.png)
线上demo，我在查询表单里有个下拉。下拉选项的值不能这样配吗，配上下拉不出来呢。

**Comment by liujuping** [comment]
预览看一下是否有下拉框

**Comment by lulg** [comment]
预览是空白什么都没有
![Uploading image.png…]()

**Comment by liujuping** [comment]
可能不小心带上了循环配置，可以先清空一下循环配置项

**Comment by lulg** [comment]
我看了，所有元素的循环配置都是[],应该都是空的了

**Comment by lulg** [comment]
![image](https://user-images.githubusercontent.com/28698352/158291735-8c89c8e4-50a3-4386-8b37-f92cfebb9dd8.png)

![image](https://user-images.githubusercontent.com/28698352/158291646-3708a5a6-b2c5-4cc3-9d70-966c5ffb72f0.png)
预览效果：
![image](https://user-images.githubusercontent.com/28698352/158291676-211b8341-53e5-4ac9-9020-9ee616785bb7.png)

**Comment by lulg** [comment]
已经好了，序号清理缓存才能调到最新的。谢谢。
