### ISSUE TITLE
更新后 demo里 Antd pro & Formily , 里拖入高级组件的 Curd表格等， 会导致页面卡死

### ISSUE THREAD

**Issue by Shilver-afka** [alibaba/lowcode-engine#1284]
复现地址 https://lowcode-engine.cn/demo/demo-antd-pro-with-formily/index.html

复现步骤 
 1、点击右侧组件库
 2、点击高级组件
 3、拖入Curd表格 或者 查询表格

现象
    页面卡死、浏览器卡顿

**Comment by huangapple** [comment]
+1

**Comment by JackLian** [comment]
官网demo已更新
