### ISSUE TITLE
内网部署

### ISSUE THREAD

**Issue by HappyYang233** [alibaba/lowcode-engine#1285]
demo中含有大量的外网链接，部署内网需要下载的文件过多，请问有没有通用的迁移方案啊

**Comment by JackLian** [comment]
官方并没有这样的方案

**Comment by HappyYang233** [comment]
> 官方并没有这样的方案
官方的demo内有很多内置的插件，这些插件内部存在官方的cdn链接，导致无法进行内网迁移困难重重呀；
希望能有个统一的解决方案，或者说官方能不能给个思路，我这边看能不能提个pr，我这边也有团队做支持

**Comment by JackLian** [comment]
所谓内网部署康为理解是一种很彻底的资源私有化，这个不是demo的定位范畴内，要你们自己来想办法把资源替换成内网可访问的

**Comment by HappyYang233** [comment]
确实不在demo的定位范围之类，但我建议lowcodeengine能有这方面的设计，说简单点低代码平台就是个内部开发工具，未来内网部署的需求肯定会很多，我之前也接触过一些像amis这样的低代码平台，他的引用就比较清晰，内网部署很快；
我现在遇到的问题如下图
<img width="1081" alt="image" src="https://user-images.githubusercontent.com/31692772/204432193-c89c0c87-2b5d-4146-9027-cdaaf51aa035.png">
_@alilc_lowcode-plugin-simulator-select@1.0.2@@alilc这个包里代码内写死的路径我没找到好的办法去处理，可能只能走代理了 但不是一个好的解决方案

**Comment by JackLian** [comment]
嗯嗯，我们跟amis确实不一样，你如果需要的是一个低代码平台，建议谨慎考虑下是不是需要的是这个项目

**Comment by mixtan** [comment]
> 嗯嗯，我们跟amis确实不一样，你如果需要的是一个低代码平台，建议谨慎考虑下是不是需要的是这个项目

我的项目也是做低代码平台，正在调研中，但看到你们这么说，结论是lowcode-engine不适合开发低代码平台吗？还是说不能完全私有化部署？

**Comment by JackLian** [comment]
> > 嗯嗯，我们跟amis确实不一样，你如果需要的是一个低代码平台，建议谨慎考虑下是不是需要的是这个项目
> 
> 我的项目也是做低代码平台，正在调研中，但看到你们这么说，结论是lowcode-engine不适合开发低代码平台吗？还是说不能完全私有化部署？

看具体能力，引擎顾名思义是个内核，并不是现成的产品，能不能私有化部署是产品层面的事情，取决于你们的研发能力，研发能力足够就怎么都能做

**Comment by hengyanqwe** [comment]
> > > 嗯嗯，我们跟amis确实不一样，你如果需要的是一个低代码平台，建议谨慎考虑下是不是需要的是这个项目
> > 
> > 
> > 我的项目也是做低代码平台，正在调研中，但看到你们这么说，结论是lowcode-engine不适合开发低代码平台吗？还是说不能完全私有化部署？
> 
> 看具体能力，引擎顾名思义是个内核，并不是现成的产品，能不能私有化部署是产品层面的事情，取决于你们的研发能力，研发能力足够就怎么都能做

可问题在于很多alibaba下面的插件比如lowcode-plugin-simulator-select都是写死远程cdn的，那个仓库还不能提issue
