### ISSUE TITLE
面板的内容组件中如何知道当前面板被打开还是关闭了。

### ISSUE THREAD

**Issue by lavyun** [alibaba/lowcode-engine#1286]
![image](https://user-images.githubusercontent.com/22797898/204282624-59cd023f-53f5-467e-8e68-9c6d67c0b669.png)

想在每次面板被打开时做一些初始化的动作，现在没找到相关API

**Comment by liujuping** [comment]
可以看看这几个 API

https://lowcode-engine.cn/site/docs/api/skeleton#onshowpanel
