### ISSUE TITLE
初始化组件库之后，colorful-button报错

### ISSUE THREAD

**Issue by proclml** [alibaba/lowcode-engine#1289]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---
初始化自定义组件库之后，colorful-button报错，为什么style的属性是一个字符串的'object'？是需要自己做判断吗

![image](https://user-images.githubusercontent.com/38473196/204418159-450a45f1-2eee-40e0-a89d-15ee933ba346.png)

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

1. npm init @alilc/element test-material
2. cd test-material
3. npm run lowcode:dev
4. 打开页面，将colorful-button拖到中部，点击“样式”，提示错误“组件渲染异常，请查看控制台日志”

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---
不报错

**Comment by JackLian** [comment]
1. npm init @alilc/element test-material 这步后边的选择是什么，是单组件还是组件库
2. cd 完了直接就run ？没install下？

**Comment by JackLian** [comment]
https://lowcode-engine.cn/site/docs/guide/expand/editor/cli#%E8%84%9A%E6%89%8B%E6%9E%B6%E5%88%9D%E5%A7%8B%E5%8C%96
