### ISSUE TITLE
造物组件开发平台 目前是什么情况？弃用了吗？

### ISSUE THREAD

**Issue by huangapple** [alibaba/lowcode-engine#1293]
造物组件开发平台 目前是什么情况？弃用了吗？
我体验了下， 加了antd， 解析出来最新的是5.0.2

但最新版本一直显示 4.20.5, 而且 自动解析出来的， 基本不能用， 比如antd自动解析出来的， 只有一个按钮， 还是啥功能都没有的按钮

是我使用姿势的问题， 还是造物这个平台还不完善？
https://parts.lowcode-engine.cn/

**Comment by JackLian** [comment]
你有没有弃用得你自己判断下了，平台官方还在持续建设，有问题可以针对问题直接提issue或答疑群中提
