### ISSUE TITLE
fusion demo 物料包异常

### ISSUE THREAD

**Issue by javaxiu** [alibaba/lowcode-engine#1298]
# 复现步骤
1. 访问 https://lowcode-engine.cn/demo/demo-basic-fusion/index.html
2. 拖入一个分栏组件

# 异常截图
<img width="1080" alt="image" src="https://user-images.githubusercontent.com/4281225/204485966-596f426a-0441-49a4-bd08-1f49a67ea71a.png">

**Comment by JackLian** [comment]
线上已修复，有几个组件如分栏依赖 prolayout，如需使用，可使用综合场景demo
