### ISSUE TITLE
功能文档能写的清晰一点吗？

### ISSUE THREAD

**Issue by m-yangyu** [alibaba/lowcode-engine#13]
![image](https://user-images.githubusercontent.com/26132427/154485749-914681fe-3f76-40fd-b28d-e6be29fb9591.png)

这个文档写的太不清晰了吧。。

![image](https://user-images.githubusercontent.com/26132427/154485956-77d752b2-6c81-4c2e-be11-ac3ebf63a28c.png)

默认打开的画布位置为什么是跟着左边的侧边栏一样高的。。高度怎么调整也没有写。。这真的是准备开源给人用的吗？

**Comment by LeoYuan** [comment]
1. 在我们公司设计规范上确实要求是等高的
2. 文档优化的问题是永无止境的，我们会持续优化，也欢迎提有效建议
3. 哪里官宣开源了？这不还在路上么？

**Comment by m-yangyu** [comment]
> 1. 在我们公司设计规范上确实要求是等高的
> 2. 文档优化的问题是永无止境的，我们会持续优化，也欢迎提有效建议
> 3. 哪里官宣开源了？这不还在路上么？

等个demo，我对这个还是很期待的

**Comment by dylanli09** [comment]
demo 有放出来的时间点吗？？

**Comment by LeoYuan** [comment]
> demo 有放出来的时间点吗？？

最快本周吧，要看测试的结果。
争取以好一点的状态放出来，打磨费时😃

**Comment by linonetwo** [comment]
已 watch release，期待正式版 release

**Comment by Kun8018** [comment]
> 3\. 路上
支持，持续关注，后续也想参与， 哈哈

**Comment by alvarto** [comment]
Demo 已放出：http://lowcode-engine.cn/demo

整体文档还在开源的前期准备中，有些还未完全 ready 哈，请各位谅解

**Comment by chensce** [comment]
demo在Safari浏览器上白屏，选择一个组件，放到画布，然后就白屏。Safari版本是15.2

**Comment by LeoYuan** [comment]
> demo在Safari浏览器上白屏，选择一个组件，放到画布，然后就白屏。Safari版本是15.2

麻烦另外开一个 issue 哈~
