### ISSUE TITLE
请求参数表达式无法正常填写

### ISSUE THREAD

**Issue by zero-npm** [alibaba/lowcode-engine#130]
## 复现截图
![image](https://user-images.githubusercontent.com/61113848/158332426-b3e95e4c-9064-44f2-8cc6-76547950ef78.png)
![image](https://user-images.githubusercontent.com/61113848/158332480-de64cde7-edb7-4b36-9dd6-707fd0d0eec7.png)

## 复现流程与链接
点击数据源的请求参数表达式
## 期望结果
可以正常写请求参数表达式
## 环境信息

- 引擎版本 1.0.1-beta.1
- ext 版本 1.0.2
- 物料
  - moment﹫2.24.0
  - lodash
  - ﹫alifd/next﹫1.24.18
  - NextTable﹫1.0.1
  - ﹫alilc/lowcode-materials﹫1.0.1
  - ﹫alifd/pro-layout﹫1.0.1-beta.5
  - ﹫alifd/fusion-ui﹫1.0.5-beta.1

**Comment by zhengby** [comment]
同遇到

**Comment by liujuping** [comment]
Duplicate of https://github.com/alibaba/lowcode-engine/issues/127
