### ISSUE TITLE
demo中,设置device:'mobile',图标显示不正确

### ISSUE THREAD

**Issue by gaojian531048553** [alibaba/lowcode-engine#1301]
## **Describe the bug (required)
demo中,设置device:'mobile',图标显示不正确
![image](https://user-images.githubusercontent.com/20181669/204702406-c168931b-749b-44d5-9a8f-28d8bee5965b.png)
![image](https://user-images.githubusercontent.com/20181669/204702432-56c9f6d4-c2dd-4a97-8108-d9533ed39e9e.png)
这是我设置的问题,还是一个小bug

**Comment by JackLian** [comment]
应该是插件实现的不完善
