### ISSUE TITLE
antd 基础物料， 组件类别及划分过细问题请教

### ISSUE THREAD

**Issue by huangapple** [alibaba/lowcode-engine#1303]
目前看 antd的基础物料， 通用时放了6个按钮， 只是type不一样。
![image](https://user-images.githubusercontent.com/10572028/204947856-6c7e04c8-08f9-4595-a62d-969f7f3fccd6.png)

Typography放了9个， 但其实只有4种类型。
![image](https://user-images.githubusercontent.com/10572028/204947816-71d5957a-5c55-42fc-ae68-a2bbb6dd955b.png)

是不是按antd的官网这样分类会更合理？
![image](https://user-images.githubusercontent.com/10572028/204947912-e5a6b218-de65-4781-86b3-bc4b010c8768.png)

把button合成一个， Typography分成4个， 统一放通用

**Comment by JackLian** [comment]
你可以在自己的产品里这样调整，demo只是示例

**Comment by huangapple** [comment]
意思是demo对合并也是能接受的吗？我能提PR合并起来吗？

**Comment by JackLian** [comment]
demo这个部分不打算改，但你可以自己的项目里去优化

**Comment by JackLian** [comment]
组件面板也是开源的，接受PR

**Comment by huangapple** [comment]
好




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年12月2日(星期五) 下午3:16
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [alibaba/lowcode-engine] antd 基础物料， 组件类别及划分过细问题请教 (Issue #1303)





 
demo这个部分不打算改，但你可以自己的项目里去优化
