### ISSUE TITLE
@alilc/lowcode-types 最新的是1.0.17， 今天更新的， 但怎么感觉跟现有的类型对不上？旧版本的@alilc/lowcode-types也是对不上的

### ISSUE THREAD

**Issue by huangapple** [alibaba/lowcode-engine#1306]
antd的物料包仓库在这， https://github.com/alibaba/lowcode-materials/tree/main/packages/antd-lowcode-materials

随便挑一个， 里面的meta, 比如
https://github.com/alibaba/lowcode-materials/blob/main/packages/antd-lowcode-materials/lowcode/button/meta.ts

比如第246行的
```
{
  name: 'danger',
  title: { label: '危险按钮', tip: 'danger | 设置危险按钮' },
  propType: 'bool',
  setter: 'BoolSetter',
  defaultValue: false
}
```
整个结构按协议来看是个PropConfig类型， 
但跟  @alilc/lowcode-types里面的对不上啊
```
/**
 * 组件属性信息
 */
export interface PropConfig {
    /**
     * 属性名称
     */
    name: string;
    /**
     * 属性类型
     */
    propType: PropType;
    /**
     * 属性描述
     */
    description?: string;
    /**
     * 属性默认值
     */
    defaultValue?: any;
    /**
     * @deprecated 已被弃用
     */
    setter?: any;
}
```
很多字段是对不上的， 比如title， 协议是没有的， 但title这个字段却是实实在在起作用的

整个的应该是个  ComponentMetadata 类型， 也没有完全对应上。

这是协议旧了吗？还是我弄错协议了？正确的在哪？

**Comment by huangapple** [comment]
```
{
  name: 'danger',
  title: { label: '危险按钮', tip: 'danger | 设置危险按钮' },
  propType: 'bool',
  setter: 'BoolSetter',
  defaultValue: false
}
```
这个上整个应该是个 FieldConfig 类型
```

/**
 * 属性面板配置
 */
export interface FieldConfig extends FieldExtraProps {
    /**
     * 面板配置隶属于单个 field 还是分组
     */
    type?: 'field' | 'group';
    /**
     * the name of this setting field, which used in quickEditor
     */
    name: string | number;
    /**
     * the field title
     * @default sameas .name
     */
    title?: TitleContent;
    /**
     * 单个属性的 setter 配置
     *
     * the field body contains when .type = 'field'
     */
    setter?: SetterType | DynamicSetter;
    /**
     * the setting items which group body contains when .type = 'group'
     */
    items?: FieldConfig[];
    /**
     * extra props for field
     * 其他配置属性（不做流通要求）
     */
    extraProps?: FieldExtraProps;
    /**
     * @deprecated
     */
    description?: TitleContent;
    /**
     * @deprecated
     */
    isExtends?: boolean;
}
```
对上了 但整个结构跟 Configure 又对不上
```
/**
 * 编辑体验配置
 */
export interface Configure {
    /**
     * 属性面板配置
     */
    props?: FieldConfig[];
    /**
     * 组件能力配置
     */
    component?: ComponentConfigure;
    /**
     * 通用扩展面板支持性配置
     */
    supports?: ConfigureSupport;
    /**
     * 高级特性配置
     */
    advanced?: Advanced;
}
```
---
---

https://github.com/alibaba/lowcode-materials/blob/main/packages/antd-lowcode-materials/lowcode/button/meta.ts
这整个是  ComponentMetadata | Configure 类型？

**Comment by huangapple** [comment]
[menuMeta第18行](https://github.com/alibaba/lowcode-materials/blob/main/packages/antd-lowcode-materials/lowcode/menu/meta.ts#L18)
这里的itemSetter在@alilc/lowcode-types找不到
![image](https://user-images.githubusercontent.com/10572028/205012500-a455b0d1-1c42-4454-b8ad-642a05126fb5.png)

**Comment by JackLian** [comment]
@alilc/lowcode-types 并不是跟协议对应的，是跟引擎实现对应的，并且是只有需要跨包复用或者对外公开API涉及的才会放到这个包里

**Comment by huangapple** [comment]
那有没有存在一个类型， 能对应上的？
设置了类型， 配合IDE， 开发物料会快一些， 有写错， IDE也会报错

**Comment by huangapple** [comment]
这个能否提供一个？
目前协议里面的好像也不全， https://lowcode-engine.cn/site/docs/specs/material-spec

偶尔还是能官方的一些示例物料中， 看到一两个协议没有的用法。

**Comment by JackLian** [comment]
嗯嗯，最终会提供的，也会跟协议对齐的，如果有发现没对齐的点也帮忙提个单独的issue吧，我们可以补充上
