### ISSUE TITLE
npm run build 构建失败无法解析模块

### ISSUE THREAD

**Issue by ibreathebsb** [alibaba/lowcode-engine#1309]
## **Describe the bug (required)** / **详细描述 bug（必填）**

构建失败 Can't resolve '@alilc/lowcode-rax-renderer

@alilc/lowcode-rax-simulator-renderer: info WEBPACK Hash: a5f81b7c78a4b0cf119c
@alilc/lowcode-rax-simulator-renderer: info WEBPACK Version: webpack 4.46.0
@alilc/lowcode-rax-simulator-renderer: info WEBPACK Child web:
@alilc/lowcode-rax-simulator-renderer: info WEBPACK     Hash: a5f81b7c78a4b0cf119c
@alilc/lowcode-rax-simulator-renderer: info WEBPACK     Time: 3737ms
@alilc/lowcode-rax-simulator-renderer: info WEBPACK     Built at: 2022/12/01 17:53:17
@alilc/lowcode-rax-simulator-renderer: info WEBPACK                                Asset      Size  Chunks         Chunk Names
@alilc/lowcode-rax-simulator-renderer: info WEBPACK       css/rax-simulator-renderer.css  2.52 KiB       0         rax-simulator-renderer
@alilc/lowcode-rax-simulator-renderer: info WEBPACK         js/rax-simulator-renderer.js   193 KiB       0         rax-simulator-renderer
@alilc/lowcode-rax-simulator-renderer: info WEBPACK     js/rax-simulator-renderer.js.map   665 KiB       0  [dev]  rax-simulator-renderer
@alilc/lowcode-rax-simulator-renderer: ERR! (web) ./src/renderer.ts
@alilc/lowcode-rax-simulator-renderer: ERR! Module not found: Can't resolve '@alilc/lowcode-rax-renderer' in '/Users/isaac/Work/lowcode-engine/packages/rax-simulator-renderer/src'
@alilc/lowcode-rax-simulator-renderer: ERR! 
@alilc/lowcode-rax-simulator-renderer: ERR! (web) ./src/renderer-view.tsx
@alilc/lowcode-rax-simulator-renderer: ERR! Module not found: Can't resolve '@alilc/lowcode-rax-renderer' in '/Users/isaac/Work/lowcode-engine/packages/rax-simulator-renderer/src'
@alilc/lowcode-rax-simulator-renderer: ERR! webpack compile error 
@alilc/lowcode-rax-simulator-renderer: Error: webpack compile error
@alilc/lowcode-rax-simulator-renderer:     at /Users/isaac/Work/lowcode-engine/node_modules/@alib/build-scripts/lib/commands/build.js:91:28
@alilc/lowcode-rax-simulator-renderer:     at finalCallback (/Users/isaac/Work/lowcode-engine/node_modules/webpack/lib/MultiCompiler.js:254:12)
@alilc/lowcode-rax-simulator-renderer:     at /Users/isaac/Work/lowcode-engine/node_modules/webpack/lib/MultiCompiler.js:277:6
@alilc/lowcode-rax-simulator-renderer:     at done (/Users/isaac/Work/lowcode-engine/node_modules/neo-async/async.js:2931:13)
@alilc/lowcode-rax-simulator-renderer:     at runCompilers (/Users/isaac/Work/lowcode-engine/node_modules/webpack/lib/MultiCompiler.js:181:48)
@alilc/lowcode-rax-simulator-renderer:     at /Users/isaac/Work/lowcode-engine/node_modules/webpack/lib/MultiCompiler.js:188:7
@alilc/lowcode-rax-simulator-renderer:     at /Users/isaac/Work/lowcode-engine/node_modules/webpack/lib/MultiCompiler.js:270:7
@alilc/lowcode-rax-simulator-renderer:     at finalCallback (/Users/isaac/Work/lowcode-engine/node_modules/webpack/lib/Compiler.js:257:39)
@alilc/lowcode-rax-simulator-renderer:     at /Users/isaac/Work/lowcode-engine/node_modules/webpack/lib/Compiler.js:273:13
@alilc/lowcode-rax-simulator-renderer:     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/isaac/Work/lowcode-engine/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:33:1)
@alilc/lowcode-rax-simulator-renderer:     at AsyncSeriesHook.lazyCompileHook (/Users/isaac/Work/lowcode-engine/node_modules/tapable/lib/Hook.js:154:20)
@alilc/lowcode-rax-simulator-renderer:     at onCompiled (/Users/isaac/Work/lowcode-engine/node_modules/webpack/lib/Compiler.js:271:21)
@alilc/lowcode-rax-simulator-renderer:     at /Users/isaac/Work/lowcode-engine/node_modules/webpack/lib/Compiler.js:681:15
@alilc/lowcode-rax-simulator-renderer:     at AsyncSeriesHook.eval [as callAsync] (eval at create (/Users/isaac/Work/lowcode-engine/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
@alilc/lowcode-rax-simulator-renderer:     at AsyncSeriesHook.lazyCompileHook (/Users/isaac/Work/lowcode-engine/node_modules/tapable/lib/Hook.js:154:20)
@alilc/lowcode-rax-simulator-renderer:     at /Users/isaac/Work/lowcode-engine/node_modules/webpack/lib/Compiler.js:678:31
@alilc/lowcode-rax-simulator-renderer: error Command failed with exit code 1.
@alilc/lowcode-rax-simulator-renderer: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build:umd exited 1 in '@alilc/lowcode-rax-simulator-renderer'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
cp: directory ./packages/engine/dist/js does not exist
cp: directory ./packages/engine/dist/css does not exist
cp: directory ./packages/engine/dist/js does not exist
cp: directory ./packages/engine/dist/css does not exist
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ build: `./scripts/build.sh`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/isaac/.npm/_logs/2022-12-01T09_53_18_034Z-debug.log

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

```shell
git clone
npm i 
npm run setup 
npm run build
```

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - node v14.21.1

**Comment by liujuping** [comment]
拉取最新的 main 分支，删除 nodemodules，重新安装一下依赖试一下。

**Comment by liujuping** [comment]
不过为什么需要 build 呢，官方引擎只支持 umd 使用。

**Comment by ibreathebsb** [comment]
> 不过为什么需要 build 呢，官方引擎只支持 umd 使用。

引擎从内部版本升级到开源版本，我们之前在内部版本fork出来一份并进行了了定制，需要将原有功能迁移到新的开源版本，所以需要build

**Comment by ibreathebsb** [comment]
> 拉取最新的 main 分支，删除 nodemodules，重新安装一下依赖试一下。

还是同样的错误

tnpm@9.5.9 (/Users/isaac/.nvm/versions/node/v14.21.1/bin/tnpm)
npm@8.19.3 (/Users/isaac/.nvm/versions/node/v14.21.1/lib/node_modules/tnpm/node_modules/npm/index.js)
node@14.21.1 (/Users/isaac/.nvm/versions/node/v14.21.1/bin/node)
npminstall@6.6.2 (/Users/isaac/.nvm/versions/node/v14.21.1/lib/node_modules/tnpm/node_modules/npminstall/lib/index.js)
prefix=/Users/isaac/.nvm/versions/node/v14.21.1 (load prefix from: $ npm config get prefix)
darwin x64 22.1.0

**Comment by liujuping** [comment]
这种定制版本可以自己研究一下，引擎的 build 主要是官方发包使用。

**Comment by ibreathebsb** [comment]
> 这种定制版本可以自己研究一下，引擎的 build 主要是官方发包使用。

目前还没有定制代码 只是按照官方文档 尝试build产物就跑不通 这种问题不需要解决吗

**Comment by liujuping** [comment]
嗯嗯，需要解决。由于目前 build 主要是提供给官方团队使用，系统相关的兼容性处理优先级由官方处理会比较低，欢迎 PR。
