### ISSUE TITLE
请问如何在物料开发的目录中新增自定义setter?

### ISSUE THREAD

**Issue by proclml** [alibaba/lowcode-engine#1316]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---
跑完`npm init @alilc/element test-material`之后，发现setter不够用需要自定义，但没找到可以将新定义的setter注册进去的地方，难道只能在使用该物料的时候才能注册自定义setter吗

**Comment by oneQiu** [comment]
两种方式使用自定义setter
- 在物料开发的npm项目里面写，可以查看官方的资产包里面写法
  1. 创建Setter
  2. 直接引用
![image](https://user-images.githubusercontent.com/50658231/205541954-666d1336-e6c0-4191-ab88-6ea96c15bf8b.png)
- 在消费资产包的项目使用
  1. 开发Setter  
![image](https://user-images.githubusercontent.com/50658231/205542112-3e9cb826-050b-4f0c-9408-3829dd114a82.png)
  2. 使用`setters.registerSetter`注册插件 
![image](https://user-images.githubusercontent.com/50658231/205542222-c0b3eade-ed7b-47ab-afdd-d5b27a5bb49e.png)
  3. 在对应需要用到的地方修改`componentName`
![image](https://user-images.githubusercontent.com/50658231/205542324-488a28b8-5d33-4697-9740-2b532c1af671.png)

**Comment by oneQiu** [comment]
额外的点注意一下，如果Setter用了hooks的语法，需要把isDynamic给关闭

**Comment by proclml** [comment]
@oneQiu 多谢

**Comment by sy296565890** [comment]
自定义设置器 如何在物料加载的时候自动加载  而不是写入plugin
