### ISSUE TITLE
页面之间如何互动呢

### ISSUE THREAD

**Issue by lulg** [alibaba/lowcode-engine#132]
请问页面之间如何互动和传参呢？

比如列表页操作跳转到编辑表单如何传参？
表单编辑完了如何刷新列表？

**Comment by Go7hic** [comment]
原子组件有超链接可以跳转，还有点击事件应该可以通过函数来实现。

**Comment by JackLian** [comment]
可以使用lab体验相关能力，https://lab.lowcode-engine.cn/#/
