### ISSUE TITLE
Is there anyway that I can find complete demo version of low code engine

### ISSUE THREAD

**Issue by dostongulmatov** [alibaba/lowcode-engine#1329]
I want to make Website Builder in english using Alibaba low code engine but it is completely in chinese and it is hard to translate it into english. Is there any easy ways that I can translate the whole low code engine into english?

**Comment by JackLian** [comment]
sorry for the inconvenience, for now you can use chrome`s translation, right click on the webpage and you can see ’translate to english‘，which works for both demo and document site.
