### ISSUE TITLE
想拓展现有物料setter,getConvertedExtraKey方法找不到怎么解决啊？

### ISSUE THREAD

**Issue by BLUE-FAT** [alibaba/lowcode-engine#133]
![image](https://user-images.githubusercontent.com/45302169/158499325-90bcb5f4-b768-46bb-93bb-cc6900d6de63.png)

**Comment by LeoYuan** [comment]
忘记加了。。。下个版本补上~

急着用可以临时写 ___condition___（前后各3个下划线）

**Comment by BLUE-FAT** [comment]
好的~

**Comment by xiaochena** [comment]
getConvertedExtraKey 还没加 😭

**Comment by liujuping** [comment]
AliLowCodeEngine.common.utils.getConvertedExtraKey 已经有了，文档待补充
