### ISSUE TITLE
lowcode-rax-renderer可以渲染成weex吗

### ISSUE THREAD

**Issue by wenlai** [alibaba/lowcode-engine#1331]
低代码引擎渲染端可以通过 @alilc/lowcode-rax-renderer， 渲染成weex文件页面吗？
目前在做低代码和weex结合，官方没有明确可行性，如果可行，我会继续研究。本来就不行，那就得想其他办法了。

**Comment by JackLian** [comment]
标准做法是建议直接做个weex renderer

**Comment by wenlai** [comment]
那就是和@alilc/lowcode-rax-renderer没关系了，自己用排版出来的schema和components，直接写一个rax-weex renderer了，对吗？谢谢

**Comment by wenlai** [comment]
好的，谢谢。
