### ISSUE TITLE
自定义setter中如何获取自定义组件

### ISSUE THREAD

**Issue by mengyuhang4879** [alibaba/lowcode-engine#1335]
![image](https://user-images.githubusercontent.com/39154179/206116240-67876e0f-0393-4a2e-9ff0-9ffebc6539b2.png)
1.编辑区的每种题型都是发到npm的自定义组件
2.点击全局设置中的是否展示题号，怎么通知各个组件更新

**Comment by hzd822** [comment]
可以通过全局拿当前的schema信息做额外的处理

**Comment by hinhinlaw** [comment]
你好，请问设置器面板中这些样式是怎么自定义的呢？
<img width="246" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/61171216/929a4196-38a2-4739-8546-b82f3f1bf090">

**Comment by mengyuhang4879** [comment]
可以参考一下自定义setter
https://lowcode-engine.cn/site/docs/api/setters#%E5%BC%80%E5%8F%91%E8%87%AA%E5%AE%9A%E4%B9%89-setter
