### ISSUE TITLE
低代码生态脚手架 创建plugin的调试问题

### ISSUE THREAD

**Issue by dengBox** [alibaba/lowcode-engine#1339]
## **Describe the bug (required)** / **详细描述 bug（必填）**

根据[官方文档](https://lowcode-engine.cn/site/docs/guide/expand/editor/cli)后创建`plugin | setter`模板后进行开发，本地运行之后无任何反应。
根据官方文档描述，配置`openUrl`即可进行调试，实际任何反应都没有

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1. `npm init @alilc/element your-element-name`
2. select plugin template
3. npm i
4. npm start
5. output WARN CONFIG No webpack config found.

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
1. 可以正常开发面板插件
2. 可以如文档所说，利用官方在线demo进行调试，而无需本地模拟编辑器进行调试。

---

## **Screenshots (optional)** / **bug 截图（可选）**
<img width="495" alt="image" src="https://user-images.githubusercontent.com/29906246/206412804-0f6d2178-c1ba-405d-b281-f51a565abae7.png">

<img width="748" alt="image" src="https://user-images.githubusercontent.com/29906246/206414581-ec2fef06-c2ca-42a2-b232-47d79ec9beed.png">

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
-@alilc/create-element@1.1.4
-node: 12.13.0
-npm: 6.12.0

**Comment by LeoYuan** [comment]
麻烦重新执行一下初始化的过程~

**Comment by dengBox** [comment]
升级后的脚手架 ，启动是没问题了，但是`build.js`中`openUrl`的具体作用是什么，感觉描述的不是很清楚。
配置之后 浏览器是可以打开官方的demo页面，但是当前开发的plugin并没有显示。是需要其他配置吗？

**Comment by LeoYuan** [comment]
inject: true 打开了么？页面 url 加了 debug=true 么？

**Comment by dengBox** [comment]
> inject: true 打开了么？页面 url 加了 debug=true 么？

是的 打开了，严格按照官网文档写的，
<img width="1002" alt="image" src="https://user-images.githubusercontent.com/29906246/206616117-98e46934-560f-4fdc-9629-88d7e763a63a.png">

**Comment by LeoYuan** [comment]
![image](https://user-images.githubusercontent.com/1195765/206618755-5c01630c-99e1-45bf-a143-38feab102b90.png)

加个 debug 可以的~

我猜测你遇到的问题可能是跳转到 `https://lowcode-engine.cn/demo/index.html?debug` 后，302 到了 `https://lowcode-engine.cn/demo/demo-general/index.html`，导致 debug 标识丢掉了~ @JackLian @liujuping 可以关注下~

**Comment by dengBox** [comment]
谢谢 可以了，手动加debug就好了

**Comment by dengBox** [comment]
今天又不行了，同样的代码启动之后报错了，
<img width="1045" alt="image" src="https://user-images.githubusercontent.com/29906246/207420559-18f897b1-e1df-4ba4-9aa4-ed9b668a59e0.png">
