### ISSUE TITLE
lowcode-materials  windows环境下build报错

### ISSUE THREAD

**Issue by leehomeok** [alibaba/lowcode-engine#134]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
lowcode-materials  windows环境下 执行npm run lowcode:build报错

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
1.git clone  https://github.com/alibaba/lowcode-materials.git
2.npm install
3.npm run lowcode:build

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
![image](https://user-images.githubusercontent.com/13464485/158534220-7f5253fb-349e-48e9-bd8c-c44057d42558.png)
---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - @alilc/lowcode-materials  1.0.2-beta.1

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题
![image](https://user-images.githubusercontent.com/13464485/158534588-338f5561-e9a1-44b2-ab7f-fac21d949bb1.png)
导入的绝对路径在windows系统 看来是有问题  
import * as CollapseData from 'D:\lowcode\lowcode-materials\lowcode\collapse\view'
绝对路径都变成反斜杠了

**Comment by lijiaxu1996** [comment]
两种办法，mac开发或者放到服务器上使用vscode配置ssh远程开发调试
