### ISSUE TITLE
inject 注入后, 由于主项目设置了publicPath 无法调试

### ISSUE THREAD

**Issue by hjgeek** [alibaba/lowcode-engine#1343]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

我在通过 inject  方式调试官方插件
由于微服务开发和部署要求, 在demo项目中设置了publicPath, 
打开demo页面后, console面板出现 inject提示信息, 但页面没有 inject 成功消息提示, 并且插件仍然是原来的插件.

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---
1. demo项目 build.plugin.js 中增加配置  config.output.publicPath('/lowcodeDesigner/')
![image](https://user-images.githubusercontent.com/45581788/206566179-ab6ff5d7-6fe6-45f5-8533-da4f01dd6fb1.png)

2. demo项目中启动  npm start

3. 进入插件项目 packages\plugin-code-editor, 
build.js 配置 inject 为 true
![image](https://user-images.githubusercontent.com/45581788/206567244-7c367a22-35b2-43e2-8f07-6958abb7ff28.png)
修改按钮文字为 保存111
![image](https://user-images.githubusercontent.com/45581788/206567704-94e9eeb6-4e9d-4e7e-bcf4-27d341f88fbc.png)

6. 启动插件项目  npm start

7. 访问 demo项目, console面板出现 inject提示信息, 但页面没有 inject 成功消息提示, 并且插件仍然是原来的插件.
![image](https://user-images.githubusercontent.com/45581788/206567890-146b5e90-5fd4-422d-b4b6-03958c1d5c11.png)
![image](https://user-images.githubusercontent.com/45581788/206568238-2e6e175e-3dfa-44bf-bec0-673f4d3f3372.png)

8. 再进入官方demo项目正常, 猜测是 publicPath 的问题, 求解决办法
![image](https://user-images.githubusercontent.com/45581788/206569104-b485c805-e7aa-4efc-b89e-e49fd2ae7dd8.png)
![image](https://user-images.githubusercontent.com/45581788/206569166-25e0008c-dd52-4170-b224-3bd1af47d2a4.png)

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

期望在有前缀url的主项目中进行调试
---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本
@alilc/build-plugin-alt版本: 1.2.2
@alilc/lowcode-plugin-inject版本: 1.0.0

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by eternalsky** [comment]
inject 应该是要在第一个注册的，在 inject 插件注册之前的插件都无法调试。官方 demo 后面会调整回来。

**Comment by hjgeek** [comment]
感谢大佬~~
目前除了 initSchema在第一个, inject第二个, 其他的都在后面, 不影响调试就好~~
此问题可以关闭了, 还是我太菜了哈哈哈
