### ISSUE TITLE
为什么@alilc/element开发的组件和组件库物料无法使用@alilc/build-plugin-alt插件

### ISSUE THREAD

**Issue by JUNHAN12138** [alibaba/lowcode-engine#1347]
node环境14.17.0和16.18.0下，电脑为mac
npm i @alilc/build-plugin-alt
安装好插件之后，选择物料——>react组件和react组件库，将官网代码
`[
  '@alilc/build-plugin-alt',
  {
    type: 'component',
    inject: true,
    library,
    // 配置要打开的页面，在注入调试模式下，不配置此项的话不会打开浏览器
    // 支持直接使用官方 demo 项目：https://lowcode-engine.cn/demo/index.html
    openUrl: 'https://lowcode-engine.cn/demo/index.html?debug',
  },
],`添加至如下图所示
![image](https://user-images.githubusercontent.com/65531323/206895956-16af0395-a1da-4dd7-96d2-a2acc0126f57.png)
，
运行时报错，
![image](https://user-images.githubusercontent.com/65531323/206896035-8d949f1f-2b00-4e80-aa49-784d221d6ab2.png)

但是在选择初始化插件时确是好用的，

**Comment by eternalsky** [comment]
问一下，最后一句 ”但是在选择初始化插件时确是好用的“ 是指的什么~

**Comment by JUNHAN12138** [comment]
> 偶尔也会遇到，怀疑是某些间接依赖需要 moment，但是没有写到 deps 里声明，在某些情况下，比如 build-plugin-locales 间接引入了 moment（/不确信）会掩盖问题，但是用更纯净的 build-plugin 插件就会暴露问题~
> 
> @JUNHAN12138 紧急使用的话，先手动 npm i moment 一下~

好的，感谢

**Comment by JUNHAN12138** [comment]
> 偶尔也会遇到，怀疑是某些间接依赖需要 moment，但是没有写到 deps 里声明，在某些情况下，比如 build-plugin-locales 间接引入了 moment（/不确信）会掩盖问题，但是用更纯净的 build-plugin 插件就会暴露问题~
> 
> @JUNHAN12138 紧急使用的话，先手动 npm i moment 一下~

已解决，感谢

**Comment by eternalsky** [comment]
这个问题，其实是webpack 的moment 插件的问题，这个插件 peer 依赖了 moment，在我们的官方插件里都有使用。如果遇到不安装 peer 依赖的 npm 版本，就会出现这个问题。

**Comment by eternalsky** [comment]
https://unpkg.com/browse/moment-locales-webpack-plugin@1.2.0/index.js

**Comment by LeoYuan** [comment]
要看判断下引擎支持的 npm manager 的版本，

假如要求必须支持 peerDeps，那这个就是 by design，
假如不强制要求，那就是 bug，需要在插件 / setter / 组件脚手架中 devDeps 或者 alt 中加上 moment~

**Comment by eternalsky** [comment]
> 

考虑到插件本身自己 peer 的原因，就是必须要跟项目共享 moment。所以自己不直接指定到 deps 里。所以放到 alt 里是不合适的，脚手架里目前在考虑加。

**Comment by eternalsky** [comment]
@JUNHAN12138 你现在安装依赖使用的是什么 npm 的什么版本~ 我看官方的 7 & 8 的话会安装 peer，本地也试了一下，目前脚手架里的话，moment 也放到了 peer 里。

**Comment by JUNHAN12138** [comment]
> 

我现在是14.17.0版本

**Comment by eternalsky** [comment]
> 

这个是 node 版本，我的意思是使用什么 npm 安装，以及版本，比如是 npm 还是 cnpm 或者 pnpm。

**Comment by JUNHAN12138** [comment]
> > 
> 
> 这个是 node 版本，我的意思是使用什么 npm 安装，以及版本，比如是 npm 还是 cnpm 或者 pnpm。

用的是tnpm，本地版本为7.6.0

**Comment by eternalsky** [comment]
> 

tnpm 我本地测试确实是有这个问题，即使是本地 package.json 里写的 peer 也不安装，可以采用 tnpm 的 npm 来回避一下。
tnpm i --by=npm

**Comment by JUNHAN12138** [comment]
> 

好的好的
