### ISSUE TITLE
源码组件能否使用第三方组件呀，还是必须使用@alifd/next？不用cdn怎么解决~~

### ISSUE THREAD

**Issue by lijiaxu1996** [alibaba/lowcode-engine#135]
在写自定义组件的时候，源码组件部分能不能使用npm下载的组件比如antd等，能直接渲染么，UI组件必须使用'@alifd/next'吗?
![image](https://user-images.githubusercontent.com/59685169/158538781-fd4db72e-5752-4082-9a64-3274857a6439.png)
![image](https://user-images.githubusercontent.com/59685169/158538877-b3dfce05-8cc6-4426-9dde-63cb58c27e48.png)
![image](https://user-images.githubusercontent.com/59685169/158547028-5a8ad045-700f-42ce-b358-4e2ef4e7b10e.png)
还是必须使用@alifd/next呢
![image](https://user-images.githubusercontent.com/59685169/158546643-964fe98f-cd24-4d55-975e-34c45519f737.png)
@LeoYuan 老哥帮忙看看哈

**Comment by lijiaxu1996** [comment]
> 看下这个 #125

我这个npm run lowcode:build之后是这个，需要把demo里面的assets.json拷贝过来么，还是怎么弄呀，老哥
![image](https://user-images.githubusercontent.com/59685169/158559267-95aea85a-8725-41b9-a4b2-1f554a2345da.png)

**Comment by lijiaxu1996** [comment]
![image](https://user-images.githubusercontent.com/59685169/158559903-d85dd26d-21d3-4a3f-bc77-eb0c8bd6065f.png)
这是我npm run lowcode:build之后的生成的，需要把demo里面的assets.json配置拷贝到这个json里面吗？

**Comment by LeoYuan** [comment]
应该要把这些merge到assets.json里，但是里边的./view.js等相对路径得改成cdn地址

**Comment by lijiaxu1996** [comment]
我看了一下，我使用npm init @alilc/element新增物料最终运行的结果和官方demo相比缺了好多的webpack配置，那么能不能直接在官方demo里面写源码组件呢，如果能的话是在哪里写呢？

**Comment by eternalsky** [comment]
> 

https://www.yuque.com/lce/doc/ulvlkz#Ioc87 看下这里

**Comment by lijiaxu1996** [comment]
> 另外，是不是自己写的复杂业务组件如果想使用，是不是必须发布到阿里的公域(npm)才能使用呢？



> 
好的，
另外，是不是自己写的复杂业务组件如果想使用，是不是必须发布到阿里的公域(npm)才能使用呢？

**Comment by lijiaxu1996** [comment]
![image](https://user-images.githubusercontent.com/59685169/158763420-864f8304-73e3-4bb8-9455-68f5520bb3fd.png)
我想自己在官方demo里面新增一个react源码组件，但是看了组件都是用cdn资产包的形式引入的，不知道从哪里写我自己的物料

**Comment by LeoYuan** [comment]
参考一下 https://github.com/alibaba/lowcode-demo/tree/feat/scenario 中 basic-fusion 部分，可能更方便你理解~

**Comment by lijiaxu1996** [comment]
> 参考一下 https://github.com/alibaba/lowcode-demo/tree/feat/scenario 中 basic-fusion 部分，可能更方便你理解~

![image](https://user-images.githubusercontent.com/59685169/158764771-b83b9670-fcce-476a-837c-626b2cb2f087.png)

访问不了，是要切分支么

**Comment by LeoYuan** [comment]
直接看代码吧，url也看不出啥。。。

**Comment by lijiaxu1996** [comment]
> 
好~~

**Comment by LeoYuan** [comment]
准备的讲，源码组件变不成低代码组件，源码组件 + 组件（物料）元数据配置 的组合可以让组件在设计器中被配置，配置形成的页面描述结构中每个节点的属性就完善了起来，最终用渲染器去解释执行页面描述结构 或者 出码打包运行~

**Comment by lijiaxu1996** [comment]
是不是我自己写的源码组件必须复合你们这套配置规则才行呢，我看你们[官方文档](https://www.yuque.com/lce/doc/funcv8)文档上面说的可以转变的~~~

**Comment by lijiaxu1996** [comment]
@mark-ck @LeoYuan 希望大佬帮忙看看如何按照物料规则自定义，因为我们的业务组件是得用第三方的源码组件的，但是不知道怎么转化为低代码组件~

**Comment by LeoYuan** [comment]
https://www.yuque.com/lce/doc/funcv8 按照这个文档哪里走不通么？

**Comment by lijiaxu1996** [comment]
> https://www.yuque.com/lce/doc/funcv8 按照这个文档哪里走不通么？
要是用antd等第三方很普通的组件，最后就会报这个issue开始的错误~~
<img width="803" alt="image" src="https://user-images.githubusercontent.com/59685169/158914782-f2feb9aa-0eaa-4b9f-bd80-94dd5ef6be09.png">
请看这个问题最开始的几张图片

**Comment by mark-ck** [comment]
> 

这个是 warning 不影响，需要更多的报错信息

**Comment by mark-ck** [comment]
引擎没有限制 fusion 的组件，只要是 react 的组件 + 低代码描述都能够在引擎中使用

**Comment by lijiaxu1996** [comment]
> 引擎没有限制 fusion 的组件，只要是 react 的组件 + 低代码描述都能够在引擎中使用
这个描述就是那个meta.ts么？能不能这里具体讲讲哈，谢谢啦

**Comment by mark-ck** [comment]
> > 引擎没有限制 fusion 的组件，只要是 react 的组件 + 低代码描述都能够在引擎中使用
> > 这个描述就是那个meta.ts么？能不能这里具体讲讲哈，谢谢啦

你创建一个组件，npm run lowcode:dev 会自动生成一份 meta.ts，你可以打开页面调试看看；
具体的定义看这个文档： https://lowcode-engine.cn/material (2.2.2 组件描述协议章节)
常用配置可以参考这个文档： https://www.yuque.com/lce/doc/funcv8#MRwDl

**Comment by lijiaxu1996** [comment]
> > > 引擎没有限制 fusion 的组件，只要是 react 的组件 + 低代码描述都能够在引擎中使用
> > > 这个描述就是那个meta.ts么？能不能这里具体讲讲哈，谢谢啦
> 
> 你创建一个组件，npm run lowcode:dev 会自动生成一份 meta.ts，你可以打开页面调试看看； 具体的定义看这个文档： https://lowcode-engine.cn/material (2.2.2 组件描述协议章节) 常用配置可以参考这个文档： https://www.yuque.com/lce/doc/funcv8#MRwDl
好的，这个是需要手动配置么，还是需要在webpack里面进行配置呢

**Comment by mark-ck** [comment]
> > > > 引擎没有限制 fusion 的组件，只要是 react 的组件 + 低代码描述都能够在引擎中使用
> > > > 这个描述就是那个meta.ts么？能不能这里具体讲讲哈，谢谢啦
> > 
> > 
> > 你创建一个组件，npm run lowcode:dev 会自动生成一份 meta.ts，你可以打开页面调试看看； 具体的定义看这个文档： https://lowcode-engine.cn/material (2.2.2 组件描述协议章节) 常用配置可以参考这个文档： https://www.yuque.com/lce/doc/funcv8#MRwDl
> > 好的，这个是需要手动配置么，还是需要在webpack里面进行配置呢

什么需要手动配置？meta.ts 吗？
lowcode/<component name>/meta.ts 是组件的低代码描述，是需要进行开发的，最终要打包为构建产物发布到 npm 的；它不是 webpack 这类工程化构建配置

**Comment by lijiaxu1996** [comment]
> > > > > 引擎没有限制 fusion 的组件，只要是 react 的组件 + 低代码描述都能够在引擎中使用
> > > > > 这个描述就是那个meta.ts么？能不能这里具体讲讲哈，谢谢啦
> > > 
> > > 
> > > 你创建一个组件，npm run lowcode:dev 会自动生成一份 meta.ts，你可以打开页面调试看看； 具体的定义看这个文档： https://lowcode-engine.cn/material (2.2.2 组件描述协议章节) 常用配置可以参考这个文档： https://www.yuque.com/lce/doc/funcv8#MRwDl
> > > 好的，这个是需要手动配置么，还是需要在webpack里面进行配置呢
> 
> 什么需要手动配置？meta.ts 吗？ lowcode//meta.ts 是组件的低代码描述，是需要进行开发的，最终要打包为构建产物发布到 npm 的；它不是 webpack 这类工程化构建配置

![image](https://user-images.githubusercontent.com/59685169/158931433-9908d592-dc1c-4d04-964f-8ea8ae43d607.png)
嗯，类似这种自带的按钮，是不是这种属性啥的必须按照这种规范开发才行呢？

**Comment by mark-ck** [comment]
> > > > > > 引擎没有限制 fusion 的组件，只要是 react 的组件 + 低代码描述都能够在引擎中使用
> > > > > > 这个描述就是那个meta.ts么？能不能这里具体讲讲哈，谢谢啦
> > > > 
> > > > 
> > > > 你创建一个组件，npm run lowcode:dev 会自动生成一份 meta.ts，你可以打开页面调试看看； 具体的定义看这个文档： https://lowcode-engine.cn/material (2.2.2 组件描述协议章节) 常用配置可以参考这个文档： https://www.yuque.com/lce/doc/funcv8#MRwDl
> > > > 好的，这个是需要手动配置么，还是需要在webpack里面进行配置呢
> > 
> > 
> > 什么需要手动配置？meta.ts 吗？ lowcode//meta.ts 是组件的低代码描述，是需要进行开发的，最终要打包为构建产物发布到 npm 的；它不是 webpack 这类工程化构建配置
> 
> ![image](https://user-images.githubusercontent.com/59685169/158931433-9908d592-dc1c-4d04-964f-8ea8ae43d607.png) 嗯，类似这种自带的按钮，是不是这种属性啥的必须按照这种规范开发才行呢？

源码部分没有限制写法，你就按照你们自己的规范来开发就行，只是如果按照比较标准的 ts 写法，我们自动生成的 meta.ts 的准确率会更高

**Comment by lijiaxu1996** [comment]
大概懂了，生成的meta.ts需要还要再按照你们的规则去改，能尽量变成我们的业务需求就好了

**Comment by mark-ck** [comment]
> 大概懂了，生成的meta.ts还要再按照你们的规则去改，能尽量满足我们的业务需求就好了

嗯，再有具体问题可以提新 issue ~
