### ISSUE TITLE
写物料setter的事件模板template 并没有把模板加载到数据源面板上

### ISSUE THREAD

**Issue by luotongxin1998** [alibaba/lowcode-engine#1351]
## **物料setter的事件模板template 并没有把模板加载到数据源面板**
调试了一下源码并进行了params 属性的打印，打印的结果是templete,但是
![354f458d5a27aa4c577596ecc20cedf](https://user-images.githubusercontent.com/59943386/206974069-92721936-8e1f-455f-8cf3-a1a83833ff81.png)
![326025231bf8587b705454c60fa64d9](https://user-images.githubusercontent.com/59943386/206974390-97df7f03-2e2d-4f3d-8526-2e49e77d0842.png)
![1670826056236](https://user-images.githubusercontent.com/59943386/206975480-c6e13cf3-2156-40cd-a7de-30c9bfa4729e.png)

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **/ **如何复现 bug？（必填，非常重要）**

1.选择一个meta.js 带有事件模板template的物料
2.进行事件绑定，就会发现事件模板没有加载到源码面板上

## ** / **预期行为（必填，非常重要）**
希望修复这个bug,或者是我这边的问题请告知失误原因

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by alvarto** [comment]
templete 属于拼写错误，应为 template。

**Comment by alvarto** [comment]
@hzd822 请在 setter 处进行修改哈

**Comment by luotongxin1998** [comment]
@hzd822 @alvarto  麻烦你们了，如果修复好，请告知我一下，万分感谢

**Comment by alvarto** [comment]
> @luotongxin1998 

可能你去 lowcode-engine-ext fork 一个分支然后提 pr 合适一些

**Comment by luotongxin1998** [comment]
这个是版本太久，用的1.0.3版本出现的问题，官方早就修复了，把依赖@alilc/lowcode-engine-ext的版本号换成最新的
