### ISSUE TITLE
插件等调试默认跳转的url重定向后缺失debug参数

### ISSUE THREAD

**Issue by LeoYuan** [alibaba/lowcode-engine#1353]
我猜测你遇到的问题可能是跳转到 `https://lowcode-engine.cn/demo/index.html?debug` 后，302 到了 `https://lowcode-engine.cn/demo/demo-general/index.html`，导致 debug 标识丢掉了~ @JackLian @liujuping 可以关注下~

__Originally posted by @LeoYuan in https://github.com/alibaba/lowcode-engine/issues/1339#issuecomment-1343805637__

**Comment by JackLian** [comment]
如果是302跳转导致的问题，就不做兼容了，不过除非是手打的url，或者保存了 https://lowcode-engine.cn/demo/index.html?debug， 要不然不太会有这样的情况

**Comment by LeoYuan** [comment]
那就把插件脚手架要改一下，写死了上面的url

**Comment by JackLian** [comment]
https://github.com/alibaba/lowcode-tools/pull/22
done
