### ISSUE TITLE
Demo 中源码面板的「保存 Schema」功能失效

### ISSUE THREAD

**Issue by LeoYuan** [alibaba/lowcode-engine#1369]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点开源码面板，点击「保存 Schema」；
3. 页面无反应，没有保存 Schema；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

使用当前源码面板中的 Schema
---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
![image](https://user-images.githubusercontent.com/1195765/207559015-bb9da162-f991-4995-b556-ada6ac3e5999.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by oneQiu** [comment]
大佬 想问下这里保存的提示信息可以配中文吗

**Comment by LeoYuan** [comment]
肯定可以的，需要调用引擎的locale接口以及变更事件来做，可以来个pr哈

**Comment by liujuping** [comment]
无法复现，可能最新版本的 demo 已经修复了。
