### ISSUE TITLE
VERSION_PLACEHOLDER is not defined

### ISSUE THREAD

**Issue by Go7hic** [alibaba/lowcode-engine#137]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
<img width="548" alt="image" src="https://user-images.githubusercontent.com/3821390/158563405-db363537-bb9d-4d65-8afa-1db37a97e1cb.png">

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

https://github.com/alibaba/lowcode-demo/blob/main/src/preview.tsx 我就是用CRA 搭建项目跑了一个这个 preview页面，安装的依赖
<img width="530" alt="image" src="https://user-images.githubusercontent.com/3821390/158564014-43ff56d5-fbe3-4c47-9c3a-99c36d70dde4.png">

 启动 然后报错了

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by Darcrandex** [comment]
我也遇到了同样的问题，目前我的解决方案是在 preview.html 中先定义
`var VERSION_PLACEHOLDER = "1.0"`

**Comment by Go7hic** [comment]
> 好奇：
> 
> 1. 检查一下你的engine-core的版本号？
> 2. 渲染态为什么用到了编排模块？
> 
> 假如你也好奇，可以给个复现的仓库

看下这个地址能不能查看 https://codesandbox.io/s/clever-sid-diqs65?file=/src/index.tsx

**Comment by LeoYuan** [comment]
我明白了，根因是 #alilc/lowcode-engine 的 npm 包 lib /es 目录下没有进行 VERSION_PLACEHODER 的替换，只在 dist 目录下有~

你在项目的 externals 配置里加[一行配置](https://github.com/alibaba/lowcode-demo/blob/f8afad0df3190565caccc0a1dfd750dbf84c680f/build.json#L16)吧~

**Comment by fxhfwf** [comment]
@LeoYuan 我这边不是用的demo的仓库，也是报错这个， 想知道能怎样解决吗？
![image](https://user-images.githubusercontent.com/40874982/165896291-b32c4ad4-7092-450e-944c-28e205eb506b.png)

**Comment by LeoYuan** [comment]
不管你用什么打包工具，总有类似 webpack 的 externals 功能吧？做相应配置就好了~

**Comment by fxhfwf** [comment]
可以啦
