### ISSUE TITLE
事件绑定没有返回值

### ISSUE THREAD

**Issue by yz1311** [alibaba/lowcode-engine#1373]
## **详细描述 bug（必填）**

在组件绑定的事件 return 数据，但是在自定义组件中调用的位置返回值为undefined

## **预期行为（必填，非常重要）**
组件暴露的事件可以获取到返回值

## **bug 截图（可选）**
![image](https://user-images.githubusercontent.com/9854019/208025045-ea041ddd-c021-402c-82f9-7e47a2470275.png)
![image](https://user-images.githubusercontent.com/9854019/208025075-ba7d418d-d0a8-4da4-b0c4-478c7770cb25.png)

**Comment by liujuping** [comment]
你的问题可能和这个相关，这个问题我先关掉了，有需要在这个 issue 上进行关注，https://github.com/alibaba/lowcode-engine/issues/1420。
