### ISSUE TITLE
runtime is invalid, module 'findDOMNode' does not exist

### ISSUE THREAD

**Issue by zandko** [alibaba/lowcode-engine#1375]
## **Describe the bug (required)** / **详细描述 bug（必填）**

报错后渲染不出页面

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

内嵌页面

Steps to reproduce the behavior: / 详细复现步骤：

---

中文版示例：
1. 生成预览页面后；
2. 通过页面嵌入的方式，比如iframe和其他方式会偶发性出现这个错误；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**

<img width="1159" alt="IMG-2022-12-17-00 54 05@2x" src="https://user-images.githubusercontent.com/37948383/208149091-846f756b-12a2-44e4-9bc5-61a5fa02dc89.png">
<img width="655" alt="IMG-2022-12-17-00 54 25@2x" src="https://user-images.githubusercontent.com/37948383/208149129-ae1cb801-faed-4ce3-b82b-e89f06684310.png">

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本 latest
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本 latest
 - Browser [e.g. chrome, safari] / 浏览器版本 chrome
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本 渲染

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by zandko** [comment]
<img width="928" alt="IMG-2022-12-17-00 59 11@2x" src="https://user-images.githubusercontent.com/37948383/208150102-6124eb34-10f5-4331-a6d6-683ed2fd79b9.png">
还有这个报错

**Comment by zandko** [comment]
<img width="328" alt="IMG-2022-12-17-01 02 37@2x" src="https://user-images.githubusercontent.com/37948383/208150597-b30657f7-7dfa-4c84-a2bc-098b0779132d.png">

**Comment by JackLian** [comment]
咋复现，这些错误信息目前没啥帮助

**Comment by liujuping** [comment]
> <img alt="IMG-2022-12-17-01 02 37@2x" width="328" src="https://user-images.githubusercontent.com/37948383/208150597-b30657f7-7dfa-4c84-a2bc-098b0779132d.png">

这个错误可能是缺少 https://g.alicdn.com/code/lib/prop-types/15.7.2/prop-types.js 依赖。

这个问题由于相关信息不足先关掉了，有需要可以重新打开或者新提 issue。
