### ISSUE TITLE
Question : How to open a previously saved project properly

### ISSUE THREAD

**Issue by aderici** [alibaba/lowcode-engine#1377]
I'm trying to create a multi-page app builder. I have a project with multiple documents underneath. I save my whole project schema to a file. I want to re-open my project. I initialize my editor like this : 

```  const Workbench = withAuthenticationRequired(common.skeletonCabin.Workbench);
  return  (hasPluginInited) ?  <Workbench /> : null; ```
  
What is the right way to open an existing project? There is project.import but i believe it changes the id's of documents every time i import.

**Comment by JackLian** [comment]
there is a easy way,  save each page as a single file, which becomes the same with demo project, and it`s actually better, because eventually when page count is getting bigger, that file will be toooo big

**Comment by aderici** [comment]
Thanks @JackLian for the quick response. It would really help me if i could wrap my head around these : 

what is the purpose of multi-document nature of project api then? 

Also, when you have an app with multiple pages, how would you navigate from one page to the other from within the page? By setting window.location ?

Should there be a way for multiple pages to share the same state?

I thought these would be possible if all pages were contained within the same project

**Comment by JackLian** [comment]
what is the purpose of multi-document nature of project api then?
> engine is designed to support all kind of lowcode cases,  some will need this multi page ability

Also, when you have an app with multiple pages, how would you navigate from one page to the other from within the page? By setting window.location ?
> you can use use a shell component to organize pages, each page can be renderered with renderer, or you can use framework such as qiankun or icestark to do similar stuff 

> and design-time , render time can be seperated, for example, you can edit single pages, and when runtime, preprocess these page schemas and make them into one big schema

**Comment by aderici** [comment]
Thank you for the clarifications, i am implementing it as you suggested. One page per project at a time.
