### ISSUE TITLE
如何定义meta props嵌套，比如{a: { b: '' } }

### ISSUE THREAD

**Issue by Noodles006** [alibaba/lowcode-engine#1378]
![image](https://user-images.githubusercontent.com/8025633/208429317-8222d343-884e-451f-9abb-0f3732f92f06.png)

期望的结构：props: { inputs: { fieldIds: [] } }

实际的数据结构是：props: { fieldIds: [] }；

**Comment by hjgeek** [comment]
之前刚研究过, 分享给你
![image](https://user-images.githubusercontent.com/45581788/209173633-5ba3dc70-fc5c-4c20-b678-a1fd30400eeb.png)
