### ISSUE TITLE
关于数据源面板的几个疑问

### ISSUE THREAD

**Issue by luotongxin1998** [alibaba/lowcode-engine#1385]
## **关于数据源面板的几个疑问**

1. 数据源面板是如何和内置的请求工具handler通信的？

2. 用this.state.XX作为params ,如何获取真实的value？
---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

![1671593286737](https://user-images.githubusercontent.com/59943386/208813919-8e26e8b1-a194-4d8b-80db-88319f83b943.png)

**Comment by JackLian** [comment]
数据源面板不负责运行时，是生产内容进入schema，然后运行时有renderer处理，可以看一下renderer-core的代码
https://github.com/alibaba/lowcode-engine/tree/main/packages/renderer-core
