### ISSUE TITLE
npm run build执行构建报错

### ISSUE THREAD

**Issue by Ronchan0805** [alibaba/lowcode-engine#1387]
## **Describe the bug (required)** / **详细描述 bug（必填）**
执行工程构建报错。对比旧版本发现可能为工程中"build-plugin-component"这个包版本更新的影响, 之前我在使用的版本是0.2.10， 拉下最新的lowcode-engine工程发现“build-plugin-component”这个包被升级为1.0.0。

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

按步骤拉下项目工程:
1. git clone 
2. npm install
3. npm run setup
4. npm run build

运行后报错
![image](https://user-images.githubusercontent.com/74052977/208829391-0d9ef607-f512-4067-b27d-149e6759d1b3.png)

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: 1.0.18
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by JackLian** [comment]
不瞒你说，我也在受这个困扰....正在努力解决....

**Comment by zhouxinxing** [comment]
"build-plugin-component": "^1.12.0"   可以，12.1 就不行。 给版本锁死。

**Comment by zhouxinxing** [comment]
发现问题出在  **build-plugin-component**  这个插件，在插件的内部 **build-plugin-component/src/utils/getCompileBabel.js**  里面 ， 第16行 ` [require.resolve('@babel/plugin-proposal-class-properties'), { loose: true }],  `

改成  `[require.resolve('@babel/plugin-proposal-class-properties'), { loose: true },"uuid-plugin-proposal-class-properties"], `
就可以了,主要是 babel 冲突了,要一个唯一名
