### ISSUE TITLE
在数据源配置接口，但是接口请求一直跨域，配置的本地接口支持跨域操作。

### ISSUE THREAD

**Issue by daXinLucas** [alibaba/lowcode-engine#1391]
![image](https://user-images.githubusercontent.com/85987644/208857839-c1d76a24-d20a-4869-8790-5efedaf502a5.png)

正常配置，相关接口也能在本地网页成功发出请求。
请求头的Status Code为200

**Comment by LeoYuan** [comment]
参考下 https://github.com/alibaba/lowcode-engine/issues/1129~
