### ISSUE TITLE
demo中，拖拽formily组件，没有默认值

### ISSUE THREAD

**Issue by shuxiaoman** [alibaba/lowcode-engine#1392]
## **Describe the bug (required)** / **详细描述 bug（必填）**

进入[官网demo](https://lowcode-engine.cn/demo/demo-antd-pro-with-formily/index.html)，拖拽ArrayCards组件，没有添加按钮。

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1. 打开 [demo](https://lowcode-engine.cn/demo/demo-antd-pro-with-formily/index.html)；
2. 拖拽一个FormilyForm组件；
3. 再往里面拖拽一个ArrayCards组件；
4. ArrayCards组件没有添加按钮；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
拖拽ArrayCards组件后，能有添加按钮

---

## **Screenshots (optional)** / **bug 截图（可选）**
![image](https://user-images.githubusercontent.com/40754866/208858318-ae1a2f5a-9e3e-4a01-9d60-f15c26911f81.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [1.0.18] / 低代码引擎版本
 - AliLowCodeEngineExt version: [1.0.5] / 低代码引擎扩展包版本
 - Browser [chrome] / 浏览器版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by JackLian** [comment]
这个要麻烦去这里问一下 https://github.com/seada-low-code/lowcode-ecology/tree/main/packages/formily-materials
