### ISSUE TITLE
Component/Block 在非顶层使用时提示component not found in components list

### ISSUE THREAD

**Issue by hezhirong** [alibaba/lowcode-engine#1398]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
---
Component/Block 在非顶层使用时提示component not found in components list

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---
1、打开 https://lowcode-engine.cn/demo/demo-general/index.html
2、粘贴以下schema
`{
  "componentName": "Page",
  "id": "node_dockcviv8fo1",
  "props": {
    "ref": "outerView",
    "style": {
      "height": "100%"
    }
  },
  "fileName": "/",
  "dataSource": {
    "list": [
      {
        "type": "fetch",
        "isInit": true,
        "options": {
          "params": {},
          "method": "GET",
          "isCors": true,
          "timeout": 5000,
          "headers": {},
          "uri": "mock/info.json"
        },
        "id": "info",
        "shouldFetch": {
          "type": "JSFunction",
          "value": "function() { \n  console.log('should fetch.....');\n  return true; \n}"
        }
      }
    ]
  },
  "state": {
    "text": {
      "type": "JSExpression",
      "value": "\"outer\""
    },
    "isShowDialog": {
      "type": "JSExpression",
      "value": "false"
    }
  },
  "css": "body {\n  font-size: 12px;\n}\n\n.button {\n  width: 100px;\n  color: #ff00ff\n}",
  "lifeCycles": {
    "componentDidMount": {
      "type": "JSFunction",
      "value": "function componentDidMount() {\n  console.log('did mount');\n}"
    },
    "componentWillUnmount": {
      "type": "JSFunction",
      "value": "function componentWillUnmount() {\n  console.log('will unmount');\n}"
    }
  },
  "methods": {
    "testFunc": {
      "type": "JSFunction",
      "value": "function testFunc() {\n  console.log('test func');\n}"
    },
    "onClick": {
      "type": "JSFunction",
      "value": "function onClick() {\n  this.setState({\n    isShowDialog: true\n  });\n}"
    },
    "closeDialog": {
      "type": "JSFunction",
      "value": "function closeDialog() {\n  this.setState({\n    isShowDialog: false\n  });\n}"
    }
  },
  "originCode": "class LowcodeComponent extends Component {\n  state = {\n    \"text\": \"outer\",\n    \"isShowDialog\": false\n  }\n  componentDidMount() {\n    console.log('did mount');\n  }\n  componentWillUnmount() {\n    console.log('will unmount');\n  }\n  testFunc() {\n    console.log('test func');\n  }\n  onClick() {\n    this.setState({\n      isShowDialog: true\n    })\n  }\n  closeDialog() {\n    this.setState({\n      isShowDialog: false\n    })\n  }\n}",
  "hidden": false,
  "title": "",
  "isLocked": false,
  "condition": true,
  "conditionGroup": "",
  "children": [
    {
      "componentName": "NextPage",
      "id": "node_ockzs2vw431",
      "props": {
        "headerDivider": true,
        "minHeight": "100vh",
        "presetNav": true,
        "presetAside": true,
        "footer": false,
        "nav": false,
        "aside": false,
        "placeholderStyle": {
          "gridRowEnd": "span 1",
          "gridColumnEnd": "span 12"
        },
        "headerProps": {
          "background": "surface"
        },
        "header": {
          "type": "JSSlot",
          "value": [
            {
              "componentName": "NextPageHeader",
              "id": "node_ockzs2vw433",
              "props": {},
              "title": "页面头部",
              "hidden": false,
              "isLocked": false,
              "condition": true,
              "conditionGroup": "",
              "children": [
                {
                  "componentName": "NextRowColContainer",
                  "id": "node_ockzs2vw434",
                  "props": {
                    "rowGap": 20,
                    "colGap": 20
                  },
                  "title": "行列容器",
                  "hidden": false,
                  "isLocked": false,
                  "condition": true,
                  "conditionGroup": "",
                  "children": [
                    {
                      "componentName": "NextRow",
                      "id": "node_ockzs2vw435",
                      "props": {},
                      "title": "行",
                      "hidden": false,
                      "isLocked": false,
                      "condition": true,
                      "conditionGroup": "",
                      "children": [
                        {
                          "componentName": "NextCol",
                          "id": "node_ockzs2vw436",
                          "props": {
                            "colSpan": 1
                          },
                          "title": "列",
                          "hidden": false,
                          "isLocked": false,
                          "condition": true,
                          "conditionGroup": "",
                          "children": [
                            {
                              "componentName": "NextP",
                              "id": "node_ockzvfoetv17",
                              "props": {
                                "wrap": false,
                                "type": "body2",
                                "verAlign": "middle",
                                "textSpacing": true,
                                "align": "left"
                              },
                              "docId": "dockzvfoetv",
                              "title": "段落",
                              "hidden": false,
                              "isLocked": false,
                              "condition": true,
                              "conditionGroup": "",
                              "children": [
                                {
                                  "componentName": "NextText",
                                  "id": "node_ockzvfoetv18",
                                  "props": {
                                    "type": "h5",
                                    "children": {
                                      "type": "JSExpression",
                                      "value": "this.state.info?.info",
                                      "mock": "标题标题"
                                    },
                                    "mark": false,
                                    "code": false,
                                    "delete": false,
                                    "underline": false,
                                    "strong": false
                                  },
                                  "docId": "dockzvfoetv",
                                  "hidden": false,
                                  "title": "",
                                  "isLocked": false,
                                  "condition": true,
                                  "conditionGroup": ""
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ],
          "title": "header"
        },
        "isTab": false,
        "contentAlignCenter": false,
        "contentProps": {
          "style": {
            "background": "rgba(255,255,255,0)"
          }
        },
        "navProps": {
          "width": 200
        },
        "asideProps": {
          "width": 200
        },
        "background": "lining"
      },
      "title": "页面",
      "hidden": false,
      "isLocked": false,
      "condition": true,
      "conditionGroup": "",
      "children": [
        {
          "componentName": "NextBlock",
          "id": "node_ockzs2vw437",
          "props": {
            "placeholderStyle": {
              "height": "100%"
            },
            "noPadding": false,
            "noBorder": false,
            "title": "区域标题",
            "rowGap": 20,
            "colGap": 20,
            "background": "surface",
            "layoutmode": "O",
            "strict": true,
            "colSpan": 12,
            "rowSpan": 1,
            "mode": "transparent",
            "childTotalColumns": 12
          },
          "title": "区域",
          "hidden": false,
          "isLocked": false,
          "condition": true,
          "conditionGroup": "",
          "children": [
            {
              "componentName": "NextBlockCell",
              "id": "node_ockzs2vw438",
              "props": {
                "colSpan": 12,
                "rowSpan": 1,
                "mode": "procard",
                "isAutoContainer": true,
                "title": "区块标题",
                "hasDivider": true,
                "loading": false,
                "hasCollapse": false,
                "text": true,
                "operations": [],
                "isFillContainer": true
              },
              "hidden": false,
              "title": "",
              "isLocked": false,
              "condition": true,
              "conditionGroup": "",
              "children": [
                {
                  "componentName": "NextRowColContainer",
                  "id": "node_ockzs2vw439",
                  "props": {
                    "rowGap": 20,
                    "colGap": 20
                  },
                  "title": "行列容器",
                  "hidden": false,
                  "isLocked": false,
                  "condition": true,
                  "conditionGroup": "",
                  "children": [
                    {
                      "componentName": "NextRow",
                      "id": "node_ockzs2vw43a",
                      "props": {},
                      "title": "行",
                      "hidden": false,
                      "isLocked": false,
                      "condition": true,
                      "conditionGroup": "",
                      "children": [
                        {
                          "componentName": "NextCol",
                          "id": "node_ockzs2vw43b",
                          "props": {
                            "colSpan": 1
                          },
                          "title": "列",
                          "hidden": false,
                          "isLocked": false,
                          "condition": true,
                          "conditionGroup": "",
                          "children": [
                            {
                              "componentName": "NextP",
                              "id": "node_oclbyidlg92l",
                              "props": {
                                "wrap": false,
                                "type": "body2",
                                "verAlign": "middle",
                                "textSpacing": true,
                                "align": "left"
                              },
                              "docId": "doclbyidlg9",
                              "title": "段落",
                              "hidden": false,
                              "isLocked": false,
                              "condition": true,
                              "conditionGroup": "",
                              "children": [
                                {
                                  "componentName": "Block",
                                  "id": "node_oclbyidmyc2",
                                  "props": {
                                    "className": "luna-page",
                                    "style": {
                                      "background": "#dd2727"
                                    }
                                  },
                                  "fileName": "block-1",
                                  "state": {
                                    "btnText": "submit"
                                  },
                                  "css": "body {font-size: 12px;}",
                                  "lifeCycles": {
                                    "componentDidMount": {
                                      "type": "JSFunction",
                                      "value": "function() {\nconsole.log('block did mount');\n}"
                                    },
                                    "componentWillUnmount": {
                                      "type": "JSFunction",
                                      "value": "function() {\nconsole.log('block will unmount');\n}"
                                    }
                                  },
                                  "hidden": false,
                                  "title": "",
                                  "isLocked": false,
                                  "condition": true,
                                  "conditionGroup": "",
                                  "children": [
                                    {
                                      "componentName": "Button",
                                      "id": "node_oclbyidmyc3",
                                      "props": {
                                        "text": {
                                          "type": "JSExpression",
                                          "value": "this.state.btnText"
                                        },
                                        "children": "dddddddd",
                                        "type": "primary",
                                        "size": "small",
                                        "iconSize": "xxs",
                                        "loading": false,
                                        "warning": false,
                                        "disabled": false
                                      },
                                      "hidden": false,
                                      "title": "",
                                      "isLocked": false,
                                      "condition": true,
                                      "conditionGroup": ""
                                    }
                                  ]
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}`
3、没按预期执行容器组件的生命周期，state等逻辑，提示Block component is not found in components list! component list is

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---
能按照文档
[容器组件描述](https://lowcode-engine.cn/site/docs/specs/lowcode-spec#233%E5%AE%B9%E5%99%A8%E7%BB%93%E6%9E%84%E6%8F%8F%E8%BF%B0-a
)的预期执行Block组件的lifeCycles和显示Button按钮的文案 this.state.btnText

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by liujuping** [comment]
Component/Block 等组件只支持在顶层使用。By design

**Comment by hezhirong** [comment]
那[容器组件](https://lowcode-engine.cn/site/docs/specs/lowcode-spec#233%E5%AE%B9%E5%99%A8%E7%BB%93%E6%9E%84%E6%8F%8F%E8%BF%B0-a)如何嵌入到底码页面中使用，有没有这块的案例或者schema描述
