### ISSUE TITLE
请问workspace功能正式版的上线时间

### ISSUE THREAD

**Issue by Cossey11111** [alibaba/lowcode-engine#1400]
因为项目中有多视图的需求，想问下workspace这个功能正式版的预计上线时间

**Comment by JackLian** [comment]
建议等春节后再看看

**Comment by yeaicc** [comment]
官方已发布API：[workspace - 应用级 API](https://lowcode-engine.cn/site/docs/api/workspace)
出个体验报告不[手动狗头]
