### ISSUE TITLE
疑问：能否使用此框架自定义渲染器来实现 DataV这样的大屏设计器？

### ISSUE THREAD

**Issue by 1021683053** [alibaba/lowcode-engine#1403]
现在想用这个来实现大屏设计器的相关功能，与页面设计器有些差别
1，所有的组件都是基于定位来实现的，很少有使用流式布局来实现。
2，大屏设计器支持组件的大小拖拽。
3，大屏尺寸固定，随着屏幕的宽度变化整体显示也是放大缩小的状态。

**Comment by JackLian** [comment]
理论上能，现成的没有

**Comment by 1021683053** [comment]
> 理论上能，现成的没有

如果我想做到这一点我需要对哪个模块进行二开？或者替换？
是：react-renderer & react-simulator-renderer 还是 lowcode-designer？
