### ISSUE TITLE
引擎升级后报错

### ISSUE THREAD

**Issue by Ronchan0805** [alibaba/lowcode-engine#1406]
## **Describe the bug (required)** / **详细描述 bug（必填）**

之前一直在使用的低代码项目，最近突然发现浏览器窗口控制台报错无法渲染，发现是最新的引擎（v1.0.3-beta.0 ）中新增了一个host.i18nConsumer.consume(xxx)逻辑

---

## **Screenshots (optional)** / **bug 截图（可选）**
![image](https://user-images.githubusercontent.com/74052977/209488947-feda7123-603a-4a5f-afd5-1f160fdeeddb.png)
![image](https://user-images.githubusercontent.com/74052977/209488961-e80788a2-075b-4edb-8d47-25c73ccfd31a.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: v1.0.3-beta.0 
 - AliLowCodeEngineExt version:  v1.0.3 
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
看起来像是一个多语言的东西

**Comment by JackLian** [comment]
首先，不建议使用beta版，其次，现在最新版本已经是1.0.18，可以先升级再说

**Comment by ZhangMengNan** [comment]
如何升级？

**Comment by LeoYuan** [comment]
> 如何升级？

把 html 中的 script 改版本就好了

**Comment by ZhangMengNan** [comment]
![image](https://user-images.githubusercontent.com/26115941/209602726-02f8651e-fd33-43b7-b8ea-28f0ff83787f.png)
这样的报错有遇到吗？版本也是1.0.3

**Comment by Ronchan0805** [comment]
> ![image](https://user-images.githubusercontent.com/26115941/209602726-02f8651e-fd33-43b7-b8ea-28f0ff83787f.png) 这样的报错有遇到吗？版本也是1.0.3

在html把版本固定一下，simulatorUrl里lowcode-react-simulator-renderer版本也固定一下，demo里原本好像用的是@last版本

**Comment by Ronchan0805** [comment]
![image](https://user-images.githubusercontent.com/74052977/209784996-ea728ca9-133f-44c9-83b3-817794357715.png)

![92642571a1ed9891ad20ab9ad456d1f](https://user-images.githubusercontent.com/74052977/209784619-30300624-01a5-499b-a507-12d091c55449.png)
![image](https://user-images.githubusercontent.com/74052977/209785339-ade878f7-447e-4159-b526-1736b80e8d9b.png)

我今天在另外一个工程，自定义物料扩展的工程($ npm init @alilc/element your-element-name)里也发现了和你一样的报错，看起来是在源码逻辑里注册了一个https://unpkg.com/@alilc/lowcode-react-simulator-renderer@beta/dist/js/react-simulator-renderer.js测试版本的包导致的，但是这个工程没找到UMD引入的入口

**Comment by LeoYuan** [comment]
从你的描述，依然看不出：
1. 为什么引用了 LCE 1.0.3-beta.0 版本？
2. 为什么引用了 react-simulator-renderer `beta` / `unpkg.com` 版本？
3. 为什么引用的不是 `https://unpkg.com/@alilc/lowcode-engine@1.0.18/dist/js/react-simulator-renderer.js`，而是 `https://unpkg.com/@alilc/lowcode-react-simulator-renderer@beta/dist/js/react-simulator-renderer.js`？

这也是我们为什么一直 **强烈建议把最小复现步骤明确地写出来**，不然大家都知道有问题，但没人知道问题在哪，也就没人会回答你~

先关闭了，再 **按规范** 提一个 issue 吧~

**Comment by jiechud** [comment]
如果是用脚手架开发物料库也有这个问题的话，升级一下 ` "@alifd/build-plugin-lowcode": "^0.3.8"` 这个包最新版本。
