### ISSUE TITLE
用create-element脚手架搭建项目，挂载外部库在window上

### ISSUE THREAD

**Issue by beautiful-boyyy** [alibaba/lowcode-engine#1411]
脚手架搭建的项目默认window全局对象下面没有antd，有什么方法可以实现把指定库挂载到window下面吗，源码面板中就可以使用了。

**Comment by eternalsky** [comment]
搭建项目是指什么？组件、插件还是？

**Comment by beautiful-boyyy** [comment]
> 搭建项目是指什么？组件、插件还是？



> 搭建项目是指什么？组件、插件还是？

组件，react组件库

**Comment by beautiful-boyyy** [comment]
> 搭建项目是指什么？组件、插件还是？

组件，react组件库

**Comment by eternalsky** [comment]
那这里的源码面板是指？是指在组件开发时起的调试窗口里吗，注入调试(inject) 还是普通调试

**Comment by beautiful-boyyy** [comment]
> 那这里的源码面板是指？是指在组件开发时起的调试窗口里吗，注入调试(inject) 还是普通调试

就是 run lowcode:dev里面的js 面板，

**Comment by eternalsky** [comment]
这样有什么意义吗？调试的窗口是为了生成物料描述，在这个 js 面板写的都是为了开发为目的，不会保存下来。如果是为了验证一个地方是否可以渲染 jsx。那只要返回一段 <div> 即可，能识别普通元素，当然也能识别 Component，本质上最终都是 createElement。

**Comment by beautiful-boyyy** [comment]
> 这样有什么意义吗？调试的窗口是为了生成物料描述，在这个 js 面板写的都是为了开发为目的，不会保存下来。如果是为了验证一个地方是否可以渲染 jsx。那只要返回一段
> 
> 即可，能识别普通元素，当然也能识别 Component，本质上最终都是 createElement。

确实没啥意义。。。主要是最近用这个来搭页面就有点钻牛角尖了，谢谢了
