### ISSUE TITLE
自定义solution，通过设计器插件使用时报错

### ISSUE THREAD

**Issue by GentleSen** [alibaba/lowcode-engine#1418]
##  **详细描述 bug**

**请提供清晰且精确的 bug 描述**

自定义solution，通过自定义设计器插件的方式使用时出现报错

---

## **如何复现 bug？**

**详细复现步骤：**
1、使用 npx @alilc/lowcode-code-generator init-solution testSolution 初始化项目。
2、发包之后，在 designer 中使用。 关键代码如下：
``` typescript
import testSolution from 'testSolution';
// 开启出码功能
await plugins.register(testSolution, {});
```
3、执行 npm run start 启动 designer，出现报错，报错内容如下：
```
 WARNING  Compiled with 2 warnings                                                                                                                11:32:07
 warning  in ./node_modules/_@alilc_lowcode-code-generator@1.0.6@@alilc/lowcode-code-generator/es/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 warning  in ./node_modules/_@alilc_lowcode-code-generator@1.0.6@@alilc/lowcode-code-generator/es/index.js
Critical dependency: require function is used in a way in which dependencies cannot be statically extracted
 ERROR  Failed to compile with 2 errors                                                                                                           11:32:07
This dependency was not found:
* fs in ./node_modules/_@alilc_lowcode-code-generator@1.0.6@@alilc/lowcode-code-generator/es/index.js, ./node_modules/_snapdragon@0.8.2@snapdragon/lib/source-maps.js
To install it, you can run: npm install --save fs
```

##  **预期行为**
**请清晰和精确的描述你预期的行为**

可以正常使用 自定义 solution.

---

## **bug 截图**

![image](https://user-images.githubusercontent.com/26702657/209753435-f6101581-52cc-46e3-9334-2ee329a08dbb.png)

---

##  **请提供如下信息**

 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本 
   - @alilc/lowcode-engine： 1.0.18
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

**Comment by LeoYuan** [comment]
建议先尝试把 testSolution 在 node 端可以正常运行，再去弄 browser 里的吧，browser 里可能会有一些约束~

**Comment by Wangjing991** [comment]
请问这个问题怎么解决的呢？

**Comment by LeoYuan** [comment]
1. 先按照 node 端可以跑通的标准把自定义 solution 搞好；
2. 再看看 browser 上如何打包这个 solution，参考 https://github.com/alibaba/lowcode-code-generator-demo 的代码；

**Comment by Wangjing991** [comment]
> 1. 先按照 node 端可以跑通的标准把自定义 solution 搞好；
> 2. 再看看 browser 上如何打包这个 solution，参考 https://github.com/alibaba/lowcode-code-generator-demo 的代码；

![image](https://user-images.githubusercontent.com/19301714/233929301-956b89a2-87f7-4ee6-802b-46d818ac16e2.png)
node端出码没问题，现在就是生成的包 接入 [lowcode-code-generator-demo](https://github.com/alibaba/lowcode-code-generator-demo)这个项目的时候报错

**Comment by LeoYuan** [comment]
这个你自己研究研究。。。standalone 版本似乎是没有 fs polyfill

**Comment by Wangjing991** [comment]
> 这个你自己研究研究。。。standalone 版本似乎是没有 fs polyfill

![image](https://user-images.githubusercontent.com/19301714/233933269-6bcf705a-7203-4955-af6f-063ba6801b8f.png)
g构建的时候忽略了这个，solution  脚手架生成的是esm包，是不是可以考虑生成包的地方优化
