### ISSUE TITLE
Table 的分页配置切换到变量输入后， 很容易丢失

### ISSUE THREAD

**Issue by leoner** [alibaba/lowcode-engine#142]
https://alifd.alicdn.com/npm/@alilc/lowcode-demo@1.0.2/build/index.html  在这个页面上可以反复重现。

![image](https://user-images.githubusercontent.com/546535/158742660-9c0341a2-53ac-4b24-9907-c1285e74c22a.png)

就是这个分页配置成， 变量配置后， 稍微在页面操作下， 就丢失了

![image](https://user-images.githubusercontent.com/546535/158742807-8b7b6e33-7ccc-454e-9c6f-115af4aa0aa6.png)

**Comment by LeoYuan** [comment]
试试 https://alifd.alicdn.com/npm/@alilc/lowcode-demo@1.0.7/build/index.html ?

**Comment by liujuping** [comment]
> 试试 https://alifd.alicdn.com/npm/@alilc/lowcode-demo@1.0.7/build/index.html ?

问题还是存在

**Comment by yuhonyon** [comment]
这个bug 没人解吗

**Comment by JackLian** [comment]
时间太长了，引擎和demo都发了很多版，可在最新版体验下，如有问题可重新提个issue反馈
