### ISSUE TITLE
EventSetter生成的schema 缺少return

### ISSUE THREAD

**Issue by KeithMo0425** [alibaba/lowcode-engine#1420]
## **Describe the bug (required)** / **详细描述 bug（必填）**

FunctionSetter 和 EventSetter 产生的schema 会 "return" 的区别。
缺少return ，对于有返回值 和 异步处理的 的组件事件没法处理

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1. 使用EventSetter绑定事件
2. 查看对应的schema

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
EventSetter 生成的schema不应该缺少 return

---

## **Screenshots (optional)** / **bug 截图（可选）**
![image](https://user-images.githubusercontent.com/16830533/209917986-c0d14e8e-02fe-47ca-8a33-c251e1af92ed.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 lowcode-engine@1.0.17
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 lowcode-engine-ext@1.0.5
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

**Comment by AndyJinSS** [comment]
期望统一成return，没有return导致例如提交按钮的loading状态无法通过判断使用侧绑定的函数来更改状态。
