### ISSUE TITLE
parts 造物平台构建的物料描述缺少css

### ISSUE THREAD

**Issue by zxtyjx** [alibaba/lowcode-engine#1426]
![image](https://user-images.githubusercontent.com/8037264/210032331-b9cdb584-a460-4b8d-b185-c60224b0e9f7.png)
通过造物平台构建的物料描述中缺少css的引用，这里需要我们自己处理吗？另外通过造物平台构建的内容在这个https://g.alicdn.com/legao-comp上面是永久保存的吗？

**Comment by eternalsky** [comment]
内容是存在 cdn 上的，我们服务还稳定存在甚至服务不存在了一大段时间里应该还是有的。css 的问题，指给 @otakuXv 看了~

**Comment by qingniaotonghua** [comment]
检查下 js代码里面有没有引入 样式，如果没有的话，就不会含有css文件

**Comment by yuanhua118** [comment]
楼主解决了吗？我目前创建的也是失败。
