### ISSUE TITLE
文本组件能不能支持富文本文字样式操作

### ISSUE THREAD

**Issue by mixtan** [alibaba/lowcode-engine#1429]
发布新闻资讯的时候通常需要局部设置文字的大小颜色加粗等样式，而我们的文本组件不支持局部设置文字，简单的说就是只想设置一段文本里面某个文字的样式，请问官方有支持吗？如果不支持，源码应该改哪个地方？

![Dingtalk_20221230211014](https://user-images.githubusercontent.com/17632154/210073834-7161c8e5-d5b7-4b8f-b291-bd0200a1eab8.jpg)

**Comment by JackLian** [comment]
找个支持这个能力的组件来用吧，已经不在本项目能力范畴了

**Comment by mixtan** [comment]
只能自定义组件支持了呀
