### ISSUE TITLE
物料在左侧物料面板中不显示, 设置 `hidden: true` 缺少ts类型。

### ISSUE THREAD

**Issue by jiechud** [alibaba/lowcode-engine#1430]
## 在`meta.ts`中，设置`hidden:true`, 缺少ts类型。

在`meta.ts`中，设置了`hidden:true`，包`@alilc/lowcode-types`中的`interface ComponentMetadata`确少`hidden`属性。

内容如下:
<img width="599" alt="image" src="https://user-images.githubusercontent.com/9709396/210169631-bb37c619-56af-42c2-b41b-ea611ff33ae8.png">

报错提示：
<img width="722" alt="image" src="https://user-images.githubusercontent.com/9709396/210169652-c11e7440-0b5b-4d68-890c-0134397faa87.png">

---

##  **预期行为**

`interface ComponentMetadata` 有`hidden`属性。
---

## **Environments** 
 - `@alilc/lowcode-types`      `  1.0.18`

**Comment by JackLian** [comment]
这个属性不在物料描述协议中，可以认为是当前组件面板使用的扩展协议的部分，是否会加到物料协议中还需要再考虑下
