### ISSUE TITLE
Question : Pro-Layout repo?

### ISSUE THREAD

**Issue by aderici** [alibaba/lowcode-engine#1431]
In the "general demo" a package called @alifd/pro-layout is used. Do you know the github repo for this? i'd like to fork and translate the components

**Comment by JackLian** [comment]
pro-layout is not open-sourced yet , it was implemented using some private apis ,and is being refactored before we put it on github

**Comment by decadef20** [comment]
> In the "general demo" a package called @alifd/pro-layout is used. Do you know the github repo for this? i'd like to fork and translate the components

Here is the [link](https://github.com/alibaba/lowcode-engine/issues/1431#issue-1516563724)

**Comment by carvinlo** [comment]
Is there any progress?

**Comment by JackLian** [comment]
再等一周

**Comment by liujuping** [comment]
https://github.com/alibaba-fusion/layout
