### ISSUE TITLE
低代码设置器右边面板展示区域，有其中包含 属性、样式、事件、高级，如何新增一个自定义tab

### ISSUE THREAD

**Issue by anpmd** [alibaba/lowcode-engine#1439]
![image](https://user-images.githubusercontent.com/121105955/210479212-1592ac71-5cbd-4a5b-a920-0c19637f46fe.png)
比如我希望在属性，样式 ，事件，高级，中间加一个数据，如何新增一个自定义tab？
![image](https://user-images.githubusercontent.com/121105955/210479547-1f965b8a-a162-4abb-b458-cef389fa9790.png)

**Comment by JackLian** [comment]
https://lowcode-engine.cn/site/docs/api/material#%E7%89%A9%E6%96%99%E5%85%83%E6%95%B0%E6%8D%AE%E7%AE%A1%E9%81%93%E5%87%BD%E6%95%B0
参考这个

**Comment by hinhinlaw** [comment]
> https://lowcode-engine.cn/site/docs/api/material#%E7%89%A9%E6%96%99%E5%85%83%E6%95%B0%E6%8D%AE%E7%AE%A1%E9%81%93%E5%87%BD%E6%95%B0 参考这个

你好，根据文档例子使用了material.registerMetadataTransducer之后，确实是添加了一个新的Tab，但是内置的“属性”、“样式”和”事件“都没了，怎么把这些内置的Tab显示回来呢

**Comment by LeoYuan** [comment]
你看看你的 combined 是 push 还是直接赋值的。。。

**Comment by liujuping** [comment]
Duplicete of https://github.com/alibaba/lowcode-engine/issues/2159

**Comment by hinhinlaw** [comment]
> 你看看你的 combined 是 push 还是直接赋值的。。。

直接赋值的，material.registerMetadataTransducer回调函数的参数里面，也没有combined字段可以给我push啊
<img width="485" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/61171216/c8c32a53-daed-445a-b959-3998cd26fcd7">
![image](https://github.com/alibaba/lowcode-engine/assets/61171216/e8db05c9-017e-44a8-aed4-7bf939f90a62)

另外我看 @liujuping 在 https://github.com/alibaba/lowcode-engine/issues/2159 说的，combined是根据物料协议的部分字段生成的，那combined字段应该是引擎内部处理的，没有暴露出来给开发者吧。。。
