### ISSUE TITLE
怎么去新建一个新的页面呢？

### ISSUE THREAD

**Issue by lulg** [alibaba/lowcode-engine#144]
怎么去新建一个新的页面呢？我看来来回回都只有这一个页面呢。没有页面管理的功能吗？

**Comment by LeoYuan** [comment]
参考：https://github.com/alibaba/lowcode-engine/issues/86#issuecomment-1061442039

后面计划在 [demo](https://github.com/alibaba/lowcode-demo/pull/7) 中补充相关示例代码，也欢迎大家 PR~
