### ISSUE TITLE
datasource-pane插件，handleEditorDidMount回调未返回manaco实例

### ISSUE THREAD

**Issue by Lock-And-Key** [alibaba/lowcode-engine#1443]
datasource-pane插件，handleEditorDidMount回调未返回manaco实例,manaco的值是undefined
![image](https://user-images.githubusercontent.com/20486947/210500086-9411d636-2f1d-458a-a8e0-e3b9ab2350eb.png)

启动frontend主工程和datasource-pane插件子包，引用插件后该文件路径下代码中manaco实例返回undefined
lowcode/packages/plugins/datasource-pane/src/components/lowcode/packages/plugins/datasource-pane

**Comment by alvarto** [comment]
@xingmolu monaco editor 的回调形式很早就调整了哈，直接改代码实现即可：

- 0.1.0-beta.3
  - editorDidMount 函数签名改为：`(monaco: IMonacoInstance, editor: IEditorInstance) => void;` 此前为 `(isFullsreen: boolean, editor: IEditorInstance, monaco: IMonacoInstance) => void;`
