### ISSUE TITLE
拖拽到编辑器内的组件不能选中，怎么解决

### ISSUE THREAD

**Issue by ZhangJiaWeiready** [alibaba/lowcode-engine#1446]
大部分组件是可以选中的，但是有一个组件我们是通过forwardRef导出的，所以说在拖拽到编辑器区域的时候无法达到点击即选中组件的目的，请问有什么方法可以解决这个问题吗？

**Comment by Shaliluya** [comment]
大佬 你是怎么解决的可以分享一下么

**Comment by monkeying-boy** [comment]
请问一下你是怎么处理的呢？现在我也遇到这个问题了
