### ISSUE TITLE
开发调试plugin时报错

### ISSUE THREAD

**Issue by hezhirong** [alibaba/lowcode-engine#1449]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
使用 @alilc/element 创建 plugin 通过https://lowcode-engine.cn/demo/demo-general/index.html?debug 调试时出错。
提示：
![image](https://user-images.githubusercontent.com/4240262/210920633-808e44a3-0d72-4a1e-8023-7b77247b9e14.png)

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

1. 通过 @alilc/element 创建plugin 【npm init @alilc/element my-plugin】选择插件
2. 不改任何代码，运行 npm start
3. 打开 https://lowcode-engine.cn/demo/demo-general/index.html?debug 进行注入调试。
4. 页面出现白屏，打开控制台，提示：![image](https://user-images.githubusercontent.com/4240262/210920633-808e44a3-0d72-4a1e-8023-7b77247b9e14.png)

---

English version example：
5. Click on '....'
6. Scroll down to '....'
7. See error

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为
能正常调整plugin
---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
![image](https://user-images.githubusercontent.com/4240262/210920633-808e44a3-0d72-4a1e-8023-7b77247b9e14.png)
---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by eternalsky** [comment]
@LeoYuan 这个报错是因为 plugin 里缺什么？

**Comment by LeoYuan** [comment]
> @LeoYuan 这个报错是因为 plugin 里缺什么？

https://github.com/alibaba/lowcode-engine/blob/33ed67ab577e8870b2f4131b10d1abd6d6e7e98a/packages/designer/src/plugin/plugin-manager.ts#L164

看起来是 EditorInitPlugin 没有初始化成功~

**Comment by LeoYuan** [comment]
![image](https://user-images.githubusercontent.com/1195765/219544464-b18477e0-94f5-4797-804c-24229e3ca98b.png)

@liujuping @JackLian 这个文案看起来有点歧义~

代码里表示 [missingTasks] 是当前插件依赖的插件缺失了，而文案显示 plugin dependency missing in [missingTasks]，以为是 [missingTasks] 的依赖缺失了~

**Comment by eternalsky** [comment]
@liujuping 目前 debug 发现的原因是新版的 engine plugins register 不会等 plugin 的 async init 结束。导致 debug 的时候，因为 EditorInitPlugin 里面要请求远程注入资源init 较慢，还未初始化完成，其他插件已经开始初始化，其他插件又依赖了 EditorInit ，导致报错。

**Comment by eternalsky** [comment]
又仔细看了一下，应该不是上面的原因，而是 inject 插件对新协议的支持有问题，pluginName 没有识别，导致 EditorInitPlugin 被注入的插件替换了。这里 inject 兼容处理一下。

**Comment by eternalsky** [comment]
lowcode-plugin-inject 已经发版修复了，线上demo @JackLian 大佬更新。如果是本地 demo，更新 lowcode-plugin-inject 即可。

**Comment by JackLian** [comment]
官网demo已更新

**Comment by QwangMobile** [comment]
我用脚手架创建了插件plugins，将build.js配置里的openUrl打开，访问官方还是有同样的报错

**Comment by eternalsky** [comment]
可能有缓存，强制刷新一下看看

**Comment by eternalsky** [comment]
或者提供一下你的插件，我看看有没有报错

**Comment by QwangMobile** [comment]
> 或者提供一下你的插件，我看看有没有报错

我是直接用脚手架创建的plugins，一行代码都没改，只是把build.js中注释的openUrl打开了

试过浏览器强刷，更换浏览器也试过，都是同样的报错

**Comment by QwangMobile** [comment]
> 或者提供一下你的插件，我看看有没有报错

已经解决了，多谢
