### ISSUE TITLE
请问页面公共部分的最佳实践是什么？

### ISSUE THREAD

**Issue by lulg** [alibaba/lowcode-engine#145]
页面公共部分的最佳实践是什么？
比如我很多模块页面的头部、左侧、底部都是一样的内容，只有中间部分变化，应该通过什么方式达到这种共用。
不用每个页面都去设计一遍吧，那就麻烦了。

**Comment by LeoYuan** [comment]
有几种方式：
1. 封装 Header 和 Footer 组件，每次拖入即可；
2. 使用页面模板的方式，组件面板的实现是拖入一段类似 { componentName: 'Button' } 到画布中，页面模板只不过是更大粒度的「组件」， 比如：{ componentName: 'Page', children: [{ componentName: 'Header', ... }, { componentName: 'Footer', ... }] }，可以写个页面模板插件来承载；
3. 写一个 Page 组件，自带 Header 和 Footer，中间留个插槽部分；（高级主题，得好好读读文档）

**Comment by lulg** [comment]
好的，谢谢。
