### ISSUE TITLE
locode-demo 的index.html的依赖为什么不使用package.json管理？

### ISSUE THREAD

**Issue by jacktao007** [alibaba/lowcode-engine#1450]
locode-demo 的index.html的依赖为什么不使用package.json管理？
为什么使用的cdn+ script进行管理依赖？

**Comment by JackLian** [comment]
demo不是整体作为一个项目提供给大家用，要用具体的demo工程目录， 参考这个
https://lowcode-engine.cn/site/docs/guide/quickStart/start#%E9%80%89%E6%8B%A9%E4%B8%80%E4%B8%AA-demo-%E9%A1%B9%E7%9B%AE

**Comment by jacktao007** [comment]
用这个生成出来的代码也是 用的 cdn+ script进行管理依赖

**Comment by JackLian** [comment]
啥叫生成出来的代码

**Comment by jacktao007** [comment]
npm init @alilc/element  选择编辑器 ，问题不大 我感觉我整明白了
