### ISSUE TITLE
使用react-router切换路由时报错

### ISSUE THREAD

**Issue by jacktao007** [alibaba/lowcode-engine#1451]
### Describe the bug (required) / 详细描述 bug（必填）
使用react-router切换路由时报错

### To Reproduce (required) / 如何复现 bug？（必填，非常重要）
版本:
lowcode-engine 1.0.13
lowcode-engine-ext 1.0.5-beta.6

加入依赖 "react-router-dom": "5.3.4"

使用react-dom的history进行跳转另一个页面，另一个页面再跳转回来，多次来回跳转，会发生如上异常
history.push(/form-editor/${match?.params?.id}?${getAppQueryString()})

### Screenshots (optional) / bug 截图（可选）
![image](https://user-images.githubusercontent.com/1073365/210937006-ba404a6f-7337-4f7c-9083-dc747fd17817.png)

### Environments (please complete the following information) (required): / 请提供如下信息（必填）
AliLowCodeEngine version: [e.g. 1.0.13] / 低代码引擎版本
AliLowCodeEngineExt version: [e.g. 1.0.5-beta.6] / 低代码引擎扩展包版本
Browser [e.g. chrome, edge] / 浏览器版本
Microsoft Edge
版本 108.0.1462.46 (正式版本) (64 位)
materials / plugins / tools / 其他物料 / 插件 / 工具链版本
    "@alifd/theme-lowcode-light": "0.2.1",
    "@alilc/lowcode-datasource-fetch-handler": "^1.1.4",
    "@alilc/lowcode-datasource-sql-handler": "^1.0.4",
    "@alilc/lowcode-plugin-code-editor": "^1.0.3",
    "@alilc/lowcode-plugin-components-pane": "^1.0.2",
    "@alilc/lowcode-plugin-inject": "^1.0.0",
    "@alilc/lowcode-plugin-manual": "^1.0.3",
    "@alilc/lowcode-plugin-schema": "^1.0.1",
    "@alilc/lowcode-plugin-simulator-select": "^1.0.0",
    "@alilc/lowcode-plugin-undo-redo": "^1.0.0",
    "@alilc/lowcode-plugin-zh-en": "^1.0.0",
    "@alilc/lowcode-react-renderer": "^1.0.0",
    "@alilc/lowcode-setter-behavior": "^1.0.0",
    "@alilc/lowcode-setter-title": "^1.0.2",
    "@alilc/lowcode-types": "^1.0.0",

**Comment by jacktao007** [comment]
版本:
lowcode-engine 1.0.13
lowcode-engine-ext 1.0.5-beta.6

加入依赖 "react-router-dom": "5.3.4"

使用react-dom的history进行跳转另一个页面，另一个页面再跳转回来，多次来回跳转，会发生如上异常
 history.push(`/form-editor/${match?.params?.id}?${getAppQueryString()}`)

**Comment by JackLian** [comment]
是说把引擎放到一个spa里面了？

**Comment by jacktao007** [comment]
> 是说把引擎放到一个spa里面了？

是的 在一个spa里面

**Comment by JackLian** [comment]
这个确实不是本项目by design 的使用场景，建议使用单独的页面来承载引擎，未来也不打算做这方面特别的支持

**Comment by jacktao007** [comment]
已解决，升级到最新的1.0.18

**Comment by jacktao007** [comment]
#178 相关问题
