### ISSUE TITLE
低代码引擎如何接入后台系统或已有项目中？

### ISSUE THREAD

**Issue by mixtan** [alibaba/lowcode-engine#1455]
我的后台系统是antdpro开发的，现在想接入低代码引入到项目中，当打开某个菜单页面就是低代码引擎设计器，是不是只能单独项目使用这个低代码引擎？

**Comment by JackLian** [comment]
建议是单独一个页面的形式，现有系统里链接 过来

**Comment by mixtan** [comment]
> 建议是单独一个页面的形式，现有系统里链接 过来

怎么样才能嵌入现有react后台系统里？通过新增一个路由页面打开就是这个低代码引擎

**Comment by mixtan** [comment]
> 

你的意思是后台系统和低代码引擎分开两个项目，或者iframe，或者微应用，对吧？

**Comment by JackLian** [comment]
对的

**Comment by mixtan** [comment]
> 对的

我的项目需求是基于低代码引擎开发一个低代码平台，低代码引擎只是满足在线设计的功能，其他业务：应用、模板、组件、部署等功能都是在低代码平台系统里，如果低代码引擎单独一个项目就存在和低代码平台通信的问题，低代码引擎在线设计好的数据是存数据库里面，这个低代码平台通过后端接口获取，但前端相关的低代码引擎数据就只能通过微应用或postmessage去相关通信了，比较麻烦。分开也有一个好处就是解耦低代码平台的配置，毕竟低代码引擎的包含东西太多了。

**Comment by AndyJinSS** [comment]
使用微前端方案来实现。我目前是将编辑器和渲染器分成两个应用，编辑器就简单的用iframe引入（因为是单独页面打开，iframe的缺点可以避免），渲染部分采用的wujie引入（我fork后改动部分代码，实现物料动态加载的顺序执行）。我们对内是提供一个前端SDK+后端SDK，集成到多个业务系统中。前端SDK由umi插件（基本的低代码管理crud、版本管理）+渲染器+编辑器，后面两个是独立的前端项目打包后通过插件引入到宿主工程中的public下，完成集成。
如果要使用wujie的话可以使用我简单修改的版本andy-wujie-react@1.0.5-rc.10。

**Comment by WHSnhcZDYRZC** [comment]
可以去看下这个库的解决方案哦
https://github.com/WHSnhcZDYRZC/umi4-lowcode-engine-solutions

**Comment by wangshuaixue** [comment]
> > 对的
> 
> 我的项目需求是基于低代码引擎开发一个低代码平台，低代码引擎只是满足在线设计的功能，其他业务：应用、模板、组件、部署等功能都是在低代码平台系统里，如果低代码引擎单独一个项目就存在和低代码平台通信的问题，低代码引擎在线设计好的数据是存数据库里面，这个低代码平台通过后端接口获取，但前端相关的低代码引擎数据就只能通过微应用或postmessage去相关通信了，比较麻烦。分开也有一个好处就是解耦低代码平台的配置，毕竟低代码引擎的包含东西太多了。

我也要开发这种 请问你接入成功有示例可以参考吗
