### ISSUE TITLE
feature:  希望能够暴露 plugin-code-editor 插件的 loader 配置

### ISSUE THREAD

**Issue by dukeP** [alibaba/lowcode-engine#1456]
目前有在内部网络环境部署的场景， base-monaco-editor 默认的 monaco load path 是在 alicdn；然而 plugin-code-editor 并没有将 loader 配置暴露出来，导致无法自定义 monaco 相关文件引入地址；

https://github.com/alibaba/lowcode-plugins/blob/main/packages/plugin-code-editor/src/components/JSEditor/JsEditor.tsx#L220
https://github.com/alibaba/lowcode-plugins/blob/main/packages/plugin-code-editor/src/components/CssEditor/CssEditor.tsx#L65

**Comment by alvarto** [comment]
是可以进行定制的。

```
import { configure, getSingletonMonaco } from '@alilc/lowcode-plugin-base-monaco-editor/es/monaco'

// 保证 monaco editor 是单例
configure({
  singleton: true,
})
getSingletonMonaco({
  paths: {
    // 自定义你的路径
    vs: 'https://g.alicdn.com/code/lib/monaco-editor/0.33.0/min/vs',
  },
})

// 然后再加载编辑器
```

**Comment by dukeP** [comment]
> 是可以进行定制的。
> 
> ```
> import { configure, getSingletonMonaco } from '@alilc/lowcode-plugin-base-monaco-editor/es/monaco'
> 
> // 保证 monaco editor 是单例
> configure({
>   singleton: true,
> })
> getSingletonMonaco({
>   paths: {
>     // 自定义你的路径
>     vs: 'https://g.alicdn.com/code/lib/monaco-editor/0.33.0/min/vs',
>   },
> }).then(() => {
>   // 然后再加载编辑器
> })
> ```
lowcode-plugin-base-monaco-editor 可以配置，但是 plugin-code-editor 和 plugin-datasource-pane 这两个插件没有把这个配置项暴露出来 😄

**Comment by alvarto** [comment]
@dukeP 开启单例模式以后，统一都是引用的一个 monaco 实例，他们底层都是引用的 @alilc/lowcode-plugin-base-monaco-editor，通过这样的配置是通用的。

**Comment by SSSliangfeng** [comment]
真服了这玩意，非要搞个plugin-base-monaco出来，现在加了这项配置后又出现loader重复加载等问题。。。
