### ISSUE TITLE
点击出码，Sandbox 中报错 Slot is not defined

### ISSUE THREAD

**Issue by smallersoup** [alibaba/lowcode-engine#1458]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

最新版 [ca4ac6e](https://github.com/alibaba/lowcode-demo/commit/ca4ac6e44e58789648ee51e9a32864362061b38c) ，进入 demo-general 目录，npm start 启动后，不进行任何修改，直接点击 出码，预览报错：
![32061673180480_ pic](https://user-images.githubusercontent.com/21979752/211237047-bc3f1c5c-b22d-41e2-8c68-8225e46ae32c.jpg)

版本：
```shell
$ node -v
v14.17.0
$ npm -v
6.14.13
```
---

## **To Reproduce (required)** / **如何复现 bug？**

Steps to reproduce the behavior: / 详细复现步骤：

---

```shell
nvm install v14.17.0
nvm use v14.17.0
cd ~/github

wget https://github.com/alibaba/lowcode-demo/archive/refs/heads/main.zip
unzip main.zip
cd lowcode-demo-main

cd demo-general
npm install
npm run start
```
- 启动成功，localhost:5556 访问成功。

预览正常：
<img width="702" alt="image" src="https://user-images.githubusercontent.com/21979752/211237356-d2c9ecf9-b5f9-4021-9685-c76c838b93f7.png">

 - 点击出码；
 - Sandbox 中报错：Slot is not defined
 
<img width="1104" alt="image" src="https://user-images.githubusercontent.com/21979752/211237235-979c6ded-fdab-4f67-96e0-f20fbeb53dcb.png">

## **Expected behavior (required)** / **预期行为**

预期：Sandbox 中可以看到和预览一样的效果。

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - https://github.com/alibaba/lowcode-demo 版本，commitID：[ca4ac6e](https://github.com/alibaba/lowcode-demo/commit/ca4ac6e44e58789648ee51e9a32864362061b38c)
 - 浏览器版本：chrome， 版本 108.0.5359.124（正式版本） (x86_64)

**Comment by LeoYuan** [comment]
![image](https://user-images.githubusercontent.com/1195765/211253618-d6c53524-b07d-469d-864a-cb4360b00e9e.png)

@liujuping `render` 导出模式不应该有 Slot 节点，麻烦看一下

**Comment by mixtan** [comment]
出码的源码中不应该有Slot组件的，把Slot改成div标准就好了，这个需要官方修复 @JackLian 
![Dingtalk_2023011015491118](https://user-images.githubusercontent.com/17632154/211492293-71ec63d1-44a0-4283-8ce6-d3e33f9a4046.jpg)
![Dingtalk_20230110154854](https://user-images.githubusercontent.com/17632154/211492311-610ee4cd-c2ee-4448-9459-bff592209b0d.jpg)

**Comment by JackLian** [comment]
demo中已修改
