### ISSUE TITLE
物料组件、setter能和源码面板进行交互吗？

### ISSUE THREAD

**Issue by lulg** [alibaba/lowcode-engine#146]
![image](https://user-images.githubusercontent.com/28698352/158770082-fa1cd1db-b828-48c5-9d9e-b4c83b675f00.png)

比如我自定义了一个物料组件，页面中拖入组件，我想在源码面板中暴露一些组件特有的方法，供其他组件或事件去调用。可以做到吗？

ps:最近提的问题较多，请见谅。

**Comment by LeoYuan** [comment]
@alvarto 源码面板应该没有这样的 API 暴露吧？

**Comment by alvarto** [comment]
https://www.yuque.com/lce/usage/trgdtr#NaS58

源码面板可以引用全局和局部的部分 API，此部分能力一方面由引擎（ctx 对象）提供，一方面由物料本身提供（UMD 加载方式的副作用），看看这篇文章能不能解决你的疑惑？
