### ISSUE TITLE
导入schema 后如何直接默认选中一个物料

### ISSUE THREAD

**Issue by luotongxin1998** [alibaba/lowcode-engine#1462]
## **导入schema 后如何面板直接默认选中一个物料**

![image](https://user-images.githubusercontent.com/59943386/211258597-e257f55c-74b0-450e-92f0-66960fe63e49.png)
想实现import后默认选中，像下图那样
![image](https://user-images.githubusercontent.com/59943386/211258711-a0fac8f6-46ad-48dd-b9ee-01400e193fd6.png)

**Comment by JackLian** [comment]
找到那个节点，然后选中它
https://lowcode-engine.cn/site/docs/api/model/node#select
