### ISSUE TITLE
请问如何覆盖 @alilc/lowcode-editor-skeleton 库的代码？

### ISSUE THREAD

**Issue by yz1311** [alibaba/lowcode-engine#1463]
## **详细描述 bug（必填）**

@alilc/lowcode-editor-skeleton 里面的代码有很多不满足当前的要求，请问能否将代码下载到本地，以plugin的方式覆盖已有的？

**Comment by JackLian** [comment]
这个不可以覆盖的，有什么不满足可以提出来讨论下，或者提pr，skeleton是有限开放的，不能自定义

**Comment by yz1311** [comment]
@JackLian  其实很简单的一个需求，就是需要在lc-field的旁边增加一个图标，做一个提示功能

![image](https://user-images.githubusercontent.com/9854019/211261718-afc64e83-730e-4267-bbd4-67fec08a65d7.png)

**Comment by JackLian** [comment]
<img width="492" alt="Screen Shot 2023-01-09 at 15 54 19" src="https://user-images.githubusercontent.com/2149847/211262031-9f363ff2-3a44-42ca-b2ac-d5e2afc0bc74.png">
已有类似功能

**Comment by yz1311** [comment]
> <img alt="Screen Shot 2023-01-09 at 15 54 19" width="492" src="https://user-images.githubusercontent.com/2149847/211262031-9f363ff2-3a44-42ca-b2ac-d5e2afc0bc74.png">
> 
> 已有类似功能

是在type: 'group'  这种分组的右边，不是这种标题上的提示（这种标题上的，前面也有一个需求的，就是一些必填字段，标题的左侧显示一个红色的星号，没法改就去掉这个需求了）

**Comment by JackLian** [comment]
目前没啥太好的办法，要么提PR，加通用的能力，要么等未来提供更多的主题皮肤定制能力的吧
