### ISSUE TITLE
请问monaco-editor如何设置禁用any？

### ISSUE THREAD

**Issue by yz1311** [alibaba/lowcode-engine#1464]
## **详细描述 bug（必填）**

目前所有的变量都是any，都没有提示，太容易写错代码了
<img width="456" alt="微信图片_20230109154502" src="https://user-images.githubusercontent.com/9854019/211260727-a95d05e4-d37f-4ebb-851f-10d6492f6e4e.png">

## **预期行为（必填，非常重要）**
只要是为未声明的变量都提示

**Comment by alvarto** [comment]
无论是否使用 TypeScript，不通过 let / var / const 声明，都不会有提示。如果正常使用 let / var / const 声明，是有提示的。

<img width="443" alt="image" src="https://user-images.githubusercontent.com/1797855/211274467-b84e9b73-496c-476f-b521-71d5e976647a.png">

其他层面的 ts 提示，需要主动给 monaco-editor 喂，参考这里：
https://github.com/alibaba/lowcode-engine/issues/1191

**Comment by yz1311** [comment]
> 无论是否使用 TypeScript，不通过 let / var / const 声明，都不会有提示。如果正常使用 let / var / const 声明，是有提示的。
> 
> <img alt="image" width="443" src="https://user-images.githubusercontent.com/1797855/211274467-b84e9b73-496c-476f-b521-71d5e976647a.png">
> 
> 其他层面的 ts 提示，需要主动给 monaco-editor 喂，参考这里： #1191

我感觉还是应该将代码编辑器的代码类型从JavaScript改为typescript，typescript的判错能力比JavaScript强一大堆，虽然不写typescript代码，但是还是可以发现很多错误

![image](https://user-images.githubusercontent.com/9854019/211988176-1ae7c122-15f2-45d5-b226-86036406ac6d.png)

**Comment by alvarto** [comment]
嗯这个我们有计划，不过在排期中，到时候会推送新版本 plugin-code-editor 的，同时增补引擎侧常用 ts 定义哈，目前在我们内部系统测试中

**Comment by yz1311** [comment]
> 嗯这个我们有计划，不过在排期中，到时候会推送新版本 plugin-code-editor 的，同时增补引擎侧常用 ts 定义哈，目前在我们内部系统测试中

请问，我记得你们的文档说过目前的代码，是不支持转换typescript的，如果我将编辑器的代码类型改为typescript，但是写代码的时候不写typescript的语言特性，只写纯JavaScript，这样也应该是可以的吧？

**Comment by alvarto** [comment]
是的。

不过 plugin-code-editor 已经内置了一些编译过程了（JSX / ?. 等语法），所以支持 TS 倒是比较简单，但是系统中有很多别的 monaco-editor 入口，如函数绑定和变量绑定，这些需要额外做编译过程
