### ISSUE TITLE
通过插件功能直接用接口数据在低代码引擎中渲染出表单，有无更好的生成方式

### ISSUE THREAD

**Issue by hustwebh** [alibaba/lowcode-engine#1468]
这里有一个需求是通过接口数据生成表单，我暂时的想法是通过插件来实现，目前的实现方法能直接取得页面中的schema并且修改其children属性，有没有像通过官方api的一些其他修改方法来实现这个功能？
本身有个想法是修改ConponentsMap,但是需求方要求生成时候就绑定数据（比如单选框组能直接绑定options），如果这样做好像绑定不了

**Comment by JackLian** [comment]
直接通过接口按一定规则生成好schema，然后 importSchema

**Comment by hustwebh** [comment]
> 生成好Schema这一步骤,目前的实现方法是复制页面schema,再直接生成对应obj插入到页面Schema复制对象中，然后替换页面Schema，因为目前实现目标还比较简单；我注意到官方api中有创建插入节点等API,（https://lowcode-engine.cn/site/docs/api/model/document-model#insertnode）
>这些是否可用于这种场景

**Comment by hustwebh** [comment]
> 直接通过接口按一定规则生成好schema，然后 importSchema

生成好Schema这一步骤,目前的实现方法是复制页面schema,再直接生成对应obj插入到页面Schema复制对象中，然后替换页面Schema，因为目前实现目标还比较简单；我注意到官方api中有创建插入节点等API,（[https://lowcode-engine.cn/site/docs/api/model/document-model#insertnode）](https://lowcode-engine.cn/site/docs/api/model/document-model#insertnode%EF%BC%89)
这些是否可用于这种场景

**Comment by JackLian** [comment]
用api哪有直接生成schema更快....

**Comment by hustwebh** [comment]
> 用api哪有直接生成schema更快....

thx
