### ISSUE TITLE
如果在旧项目中嵌入 渲染模块？

### ISSUE THREAD

**Issue by Darcrandex** [alibaba/lowcode-engine#147]
## **Describe the bug (required)** / **详细描述 bug（必填）**

根据官方提供 demo，我尝试把渲染部分（preview.tsx）中的内容嵌入到旧项目中，但出现了问题，多次尝试后还是没有找到解决方法。

错误：
`Failed to parse source map from '${my-app}\node_modules\power-di\lib\utils\types.js.map' file: Error: ENOENT: no such file or directory, open '${my-app}\node_modules\power-di\lib\utils\types.js.map'`

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

复现项目地址：[ali-lowcode-view](https://github.com/Darcrandex/ali-lowcode-view)
相关的复现步骤和错误信息在 readme.md 中描述。

---

**Comment by LeoYuan** [comment]
预览态出现了设计态的引用模块，猜测跟 #alilc/lowcode-engine 被重新打包导致的，

试一下：https://github.com/alibaba/lowcode-engine/issues/137#issuecomment-1070148043

ps：`import { injectComponents } from "@alilc/lowcode-plugin-inject";` 仅为调试组件用途，正常渲染不需要~

**Comment by Darcrandex** [comment]
> 预览态出现了设计态的引用模块，猜测跟 #alilc/lowcode-engine 被重新打包导致的，
> 
> 试一下：[#137 (comment)](https://github.com/alibaba/lowcode-engine/issues/137#issuecomment-1070148043)
> 
> ps：`import { injectComponents } from "@alilc/lowcode-plugin-inject";` 仅为调试组件用途，正常渲染不需要~

我进行了以下修改：
```
    // const components = await injectComponents(buildComponents(libraryMap, componentsMap));
    const components = buildComponents(libraryMap, componentsMap);
```
但是发现 `components` 为空对象。

[具体代码内容](https://github.com/Darcrandex/ali-lowcode-view/blob/master/src/CodeRender/index.jsx#L56)

**Comment by Darcrandex** [comment]
我的问题解决了。原因是在 `index.html` 忘了引入依赖包。
完整的 demo 在 [ali-lowcode-view](https://github.com/Darcrandex/ali-lowcode-view)，希望对各位有所帮助。

**Comment by LoveRecall** [comment]
好人
