### ISSUE TITLE
appHelper中的属性如何在组件中使用

### ISSUE THREAD

**Issue by zaraChun** [alibaba/lowcode-engine#1472]
代码？
<ReactRenderer
        className="lowcode-plugin-sample-preview-content"
        schema={schema}
        components={components}
        appHelper={{
          utils: {
            aaa: () => { return 'test'; }
          }
        }}
      />

组件：
![image](https://user-images.githubusercontent.com/118963745/211511145-c2c07a06-9db2-44de-a544-ad41a72a89f5.png)

打出来的属性里面并没有appHelpler中的属性
![image](https://user-images.githubusercontent.com/118963745/211511252-f6a2cc8a-c7cc-40a2-94c1-7db89bdf46f1.png)

**Comment by JackLian** [comment]
你想要的用法是没有的，并没有提供一个全局变量让组件内也能直接访问，如果需要使用AppHelper里的内容，可在设计器里给组件的prop 绑定 appHelper里注入的内容，参考demo中 AppHelpers 示例
https://lowcode-engine.cn/demo/demo-general/index.html
