### ISSUE TITLE
资产包或者讲物料定制的几点疑问

### ISSUE THREAD

**Issue by xuhacker** [alibaba/lowcode-engine#148]
源码组件转化为低代码组件有一个具体的demo么，比如我想把一个antd的表单源码组件想转化为低代码组件，怎么操作呢？如果按照阿里前端物料规范去配置，究竟是怎么配置呢？还是必须要按照Fusion去配置，Fusion那些物料能不能自己自定义呢？因为内置的这些业务组件不符合我们的业务需求呀，希望有大佬可以帮忙解答一下疑问，谢谢！

**Comment by lijiaxu1996** [comment]
兄弟，我一直研究这个问题，感觉还是研究不出来，看来这是个很难的问题啊

**Comment by LeoYuan** [comment]
duplicate of https://github.com/alibaba/lowcode-engine/issues/135
