### ISSUE TITLE
丰富demo：目前快速上手文档包括一些组件(主要是表格)在实际使用时可参考性较弱，导致上手难度增加

### ISSUE THREAD

**Issue by huchuansai** [alibaba/lowcode-engine#1480]
## **Describe the bug (required)** / **详细描述 bug（必填）**
场景：一个常见的需求，基于lowcode-engine搭建一个简单的表格页面，包括列表的筛选+CRUD+分页+导出功能(基于外部数据源)

现状：根据【精选组件-高级表格】+【列表筛选】页去搭建，发现很多地方都是寸步难行，比如根据筛选项去重置table等

建议：lowcode-engine应该提供一些场景丰富的模板，而不像宜搭那样失去了灵活性

愿景：主要还是为了让开发人员真正做到快速上手吧，这样大家才能更好的去熟悉lowcode-engine的设计理念和规范

附件：开放出我自己的[Schema](https://live-cloud-cvoon.oss-cn-hangzhou.aliyuncs.com/attachment/1673424075158-7f46a2b8-7752-4e46.json)，供大家做一个起步，使用时清空本地的Schema重新复制导入即可

<img width="1778" alt="image" src="https://user-images.githubusercontent.com/50079978/211750785-e67ecc71-7162-46bd-8aa2-f4a84e3d058c.png">

<img width="1791" alt="image" src="https://user-images.githubusercontent.com/50079978/211750117-2cc82107-e2d1-4f38-877f-2ea092792d23.png">

**Comment by JackLian** [comment]
demo的作用主要是展示引擎功能，组件并不是展示重点哈

**Comment by huchuansai** [comment]
> demo的作用主要是展示引擎功能，组件并不是展示重点哈

同意。但是现有组件的摸索以及一些常用语法、内置API的探索你们应该给使用者一个完整的demo吧？这些东西踩起坑来还是hi劝退一部分人的，还是说你们自己也没办法用现有组件搭建出来一些稍微完善的页面

**Comment by JackLian** [comment]
https://lowcode-engine.cn/site/docs/demoUsage/intro

**Comment by JackLian** [comment]
想用demo、搭建复杂的东西，并不是demo提供的初衷，未来也不会这么提供，也许会有个单独的免费产品来给大家用（非开源）

**Comment by huchuansai** [comment]
个人看法：
那demo的初衷是什么？主要是没有一个完整的demo，用户很难把你们基础的能力串起来。
看着你们的gif点来点去都没点到关键功能上，文档也不够完善，demo也不够丰富，不是很好深入探索下去。

**Comment by liujuping** [comment]
低代码引擎的 demo 只是为了展示引擎提供的能力，包括物料是如何开发和提供给用户使用、插件是如何使用的等等。

这里提到的提供一个完整的 demo，不是我们这个项目投入的重点，主要区别在于，demo 需要投入的重点是物料，而我们提供的重点是引擎，包括渲染、画布、出码、脚手架等等。

当然物料层面也就是 demo 我们更希望有小伙伴来进行贡献。另外如果想更为完整的 demo 可以直接开箱使用，建议可以找找其他开源的低代码产品。

**Comment by huchuansai** [comment]
懂了，你们也弄不出来这样的demo，因为还是挺复杂的
开玩笑，那就我们自己制作一个物料出来并开放吧，希望可以登上你们的awesome
