### ISSUE TITLE
拖一个表格怎么去绑定一个数据源呢

### ISSUE THREAD

**Issue by lulg** [alibaba/lowcode-engine#149]
![image](https://user-images.githubusercontent.com/28698352/158953634-208fc20d-e51e-401c-af17-606229081a61.png)

1.拖一个表格怎么去绑定一个数据源呢，没有文档中的配数据源的选项。
2。数据源怎么能通过函数调用重新加载呢。

**Comment by alvarto** [comment]
1. 如何绑定数据源？这里：
![image](https://user-images.githubusercontent.com/1797855/159113136-9aee58f4-0127-4ec5-a1fb-a7a24f3702c4.png)

2. 如何重新加载？
绑定数据源后，源码面板 setState

总体流程都可以通过我们的产品使用引导看到：https://www.yuque.com/lce/usage/lsyhxn

**Comment by xuwei21** [comment]
数据源和表格每列的数据怎么一一对应啊 试了引导 结果不一样 ID和时间不会自动映射
