### ISSUE TITLE
又是乐高，受够了

### ISSUE THREAD

**Issue by komagic** [alibaba/lowcode-engine#15]
又是乐高，受够了。。

**Comment by LeoYuan** [comment]
客官，欢迎光临，你有故事，我有酒，想听听：
1. 你与乐高的故事；
2. 乐高与低代码引擎的关系；

**Comment by charmtiger** [comment]
是对低代码可能会加剧内卷，减少工作岗位的焦虑和不满是吗？我也有点，但是还是希望低代码只是用来减轻工作压力，而不是单纯为企业减少人力成本。

**Comment by akirakai** [comment]
低代码更多是为了赋能非研发人员的，毕竟不是所有企业都养得起研发团队。
就算是研发人员手写，也可以先用低代码搭好布局，然后再用源码继续开发，毕竟有些重复的布局工作很乏味。
再退一步讲，AI也是需要结构化的数据作为输入的，而低代码协议天生是结构化的。

**Comment by JackLian** [comment]
低代码更多的是工作转移的过程，将原有专业人士才能做的事情变成不需要那么专业的人也能做，是用于解决研发资源瓶颈的一种方案，专业人士会聚焦在更需要他们的岗位上，并不会因为这些技术的变革而被替代，尤其工程师群体是最擅长学习和创造的，本就不该被困在简单重复性的工作上~

**Comment by LeoYuan** [comment]
低代码也只是一个工具，一种新的可选工具，给了大家解决问题的一种新的途径~

低代码的出现也不是来一统天下，解决问题时，啥工具更好用，更高效就用哪种。我们在很多场景也用 ProCode，我们思考问题总是要站在效率的角度，比如有时用 ProCode 好，有时用 LowCode 好，那么我们就会去思考如何让两者并存，即如何做 **混合渲染**。

另外，低代码引擎更多提供的低代码的底层基础能力，若干类的 API，扩展机制 等，具体某个低代码平台能否针对其客群提供良好用户体验，这需要不断打磨优化~

**Comment by komagic** [comment]
低代码平台其实挺多

wix看起来还可以

我说的是乐高

假如乐高平台能够让不会写代码的人用的很好

乐高要是好用我专程跑来吐槽搞撒子，嘿嘿
