### ISSUE TITLE
在组件库中的精选组件、原子组件扩展一个新的tab，修改assets.json中的sort部分内容不起作用

### ISSUE THREAD

**Issue by ajieying** [alibaba/lowcode-engine#151]
修改lowcode-demo项目下 public/assets.json文件中 sort.groupList为["精选组件"，"原子组件"，"Antd组件"]，查看本地demo，组件库中找不到Antd组件 这个tab

详细复现步骤：
1、修改lowcode-demo项目下 public/assets.json文件中 sort.groupList，如下图：
<img width="450" alt="image" src="https://user-images.githubusercontent.com/9877509/158988565-c483ddd1-4797-4cfc-bb0e-126dbfad6d71.png">

2、执行 npm run start；

3、查看本地demo中的组件库，没有Antd组件的Tab

**Comment by mark-ck** [comment]
应该是没这个问题，可以检查下增加了 group 之后对应 group 下是否有组件，这个 issue 时间有点久了，先暂时关闭

**Comment by mathYang1224** [comment]
我也遇到了这个问题，具体怎么配置啊

**Comment by 1474282816** [comment]
@ajieying 请问解决了吗？我也碰到这个问题了

**Comment by ajieying** [comment]
解决了当时，好像是配置问题，之前的代码带不出来，所以无法上图了

**Comment by 1474282816** [comment]
@mathYang1224 请问解决了吗？
@ajieying 能麻烦回忆下哪里的配置有问题吗

**Comment by ajieying** [comment]
这套低代码系统是由好多部分组成的，上面的这块只是一个系统，你看下现有的组件库的数据从哪来的，参考下应该就可以
