### ISSUE TITLE
projectSchema对象存在localStorage中可以预览，但是通过http请求获取就会显示“模型结构异常”

### ISSUE THREAD

**Issue by xiongyechang** [alibaba/lowcode-engine#1513]
## **Describe the bug (required)** / **详细描述 bug（必填）**

我把拖拽出来的页面projectSchema对象放在mongodb数据库中存储，然后通过node.js服务返回，这样做预览页面就会显示“模型结构异常”，但是编辑页面是正常展示。同时，我把projectSchema对象存在localStorage里面，这样预览就是OK的，不知道这两种方式有什么区别，我试了你们官方的[lowcode-demo](https://github.com/alibaba/lowcode-demo)也存在这个问题

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---
![从localstorage获取schema](https://cdn.xiongyechang.com/Snipaste_2023-01-30_23-23-55.png)
![从http请求获取schema](https://cdn.xiongyechang.com/Snipaste_2023-01-30_23-26-15.png)
![获取schema代码如图](https://cdn.xiongyechang.com/Snipaste_2023-01-30_23-31-44.png)
![渲染页面代码如图](https://cdn.xiongyechang.com/Snipaste_2023-01-30_23-33-94.png)

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by JackLian** [comment]
最简单的方式，你对比下存入前后有啥差异就好了

**Comment by xiongyechang** [comment]
> 最简单的方式，你对比下存入前后有啥差异就好了

谢谢，比较了下，缺少props这个空对象，mongodb存储时把空对象都删除了，我添加上去就好了，对比了好几次没想到是这个问题
