### ISSUE TITLE
Block页面组件创建的在出码的时候会放在共用组件中，怎么使用？怎么创建业务组件？

### ISSUE THREAD

**Issue by yinxuejiang** [alibaba/lowcode-engine#1515]
## **Describe the bug (required)** / **详细描述 bug（必填）**

![image](https://user-images.githubusercontent.com/18732567/215713556-b6c7579a-456c-4282-96a9-79c02b0c5234.png)

![image](https://user-images.githubusercontent.com/18732567/215713749-e47ff43d-2b69-46d2-a40b-628ecc337fbf.png)

创建的公用组件，在其他页面组件中怎么使用？
---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by LeoYuan** [comment]
理论上非 Page 类型的容器型组件，比如 Component / Block 都会单独保存到后端服务，然后在组件面板或者其他插件中透出来~

Demo 在产品形态上并没有呈现多页面编排的能力，也没有单独打开 Component / Block 设计器，不过技术上是完全 OK 的。

更多细节，我们团队光弘同学会在 GMTC 2023.02.06 上分享低代码组件（Component）的设计实现，后续应该也会在阿里巴巴终端委员会的微信公众号透出文章，敬请关注
