### ISSUE TITLE
我本地生成的物料如何放到官方demo里面的assets.json里面呢

### ISSUE THREAD

**Issue by lijiaxu1996** [alibaba/lowcode-engine#152]
1. npm init @alilc/element 之后新增组件，并运行npm run lowcode:dev之后显示默认的两个colorful组件
<img width="1276" alt="image" src="https://user-images.githubusercontent.com/59685169/159110425-678a0fec-b1ca-4004-a50e-79d9524c2643.png">
2.没有出码，数据源、JS面板等插件好像不能使用
3. 是不是需要我们结合官网demo一样，添加对应的插件，完善自己的脚手架才行呢?
4. 这是官方demo里面的assets.json

![image](https://user-images.githubusercontent.com/59685169/159113139-7e7271e8-a487-47fd-a7cc-82519b51829f.png)

6.那么这个assets.json需要手动改属性么，还是有啥办法自动生成这些属性呢?

**Comment by LeoYuan** [comment]
可以试试在 demo 项目中 inject 调试方式，文档：https://www.yuque.com/lce/doc/ulvlkz （推荐）

假如不想在项目中 inject 调试，可以参考：https://github.com/alibaba/lowcode-demo/blob/main/src/scenarios/basic-fusion-with-single-component 中的 assets.json 配置，搜索 M220318 在 packages / components / componentList 等字段的配置~

另外，建议先整体把低代码引擎的文档通读一遍 https://www.yuque.com/lce/doc 可以对整体有个更好的了解~

**Comment by lijiaxu1996** [comment]
> 可以试试在 demo 项目中 inject 调试方式，文档：https://www.yuque.com/lce/doc/ulvlkz （推荐）
> 
> 假如不想在项目中 inject 调试，可以参考：https://github.com/alibaba/lowcode-demo/blob/main/src/scenarios/basic-fusion-with-single-component 中的 assets.json 配置，搜索 M220318 在 packages / components / componentList 等字段的配置~
> 
> 另外，建议先整体把低代码引擎的文档通读一遍 https://www.yuque.com/lce/doc 可以对整体有个更好的了解~

@LeoYuan Leo 老哥，谢谢哈，终于知道怎么把我自定义的放进去了，真滴蛮详细的
