### ISSUE TITLE
物料开发按官网步骤，npm publish报错

### ISSUE THREAD

**Issue by junegod** [alibaba/lowcode-engine#1523]
## **Describe the bug (required)** / **详细描述 bug（必填）**

物料开发按官网步骤，npm publish报错

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

1.初始化react组件库项目
2.安装依赖，安装是成功的
3.发布

```
npm init @alilc/element my-lowcode-com2
npm install
npm publish
```

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
发布成功

---

## **Screenshots (optional)** / **bug 截图（可选）**
报2个错
ERR! Addon value should end in /manager or /preview or /register OR it should be a valid preset https://storybook.js.org/docs/react/addons/writing-presets/

ERR! TypeError: Cannot read property 'replace' of undefined

<img width="1140" alt="image" src="https://user-images.githubusercontent.com/2197929/216212898-2b798b5b-0fe8-4006-889d-011d0e6ce6c5.png">

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 
node v14.18.0
npm 6.14.15

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

**Comment by eternalsky** [comment]
组件库项目需要添加一点附加信息才能构建成功。build.json 里需要加上 addon。
```js
{
"plugins": [
    ["build-plugin-component-multiple", {
      "themePackage": "@alifd/theme-2",
      "addon": "@storybook/addon-outline"
    }]
  ]
}

```

@mark-ck 之前说是要替换掉这个 build-plugin，不知道进度如何？

**Comment by junegod** [comment]
> 组件库项目需要添加一点附加信息才能构建成功。build.json 里需要加上 addon。
> 
> ```js
> {
> "plugins": [
>     ["build-plugin-component-multiple", {
>       "themePackage": "@alifd/theme-2",
>       "addon": "@storybook/addon-outline"
>     }]
>   ]
> }
> ```
> 
> @mark-ck 之前说是要替换掉这个 build-plugin，不知道进度如何？

可以了

**Comment by junegod** [comment]
> 组件库项目需要添加一点附加信息才能构建成功。build.json 里需要加上 addon。
> 
> ```js
> {
> "plugins": [
>     ["build-plugin-component-multiple", {
>       "themePackage": "@alifd/theme-2",
>       "addon": "@storybook/addon-outline"
>     }]
>   ]
> }
> ```
> 
> @mark-ck 之前说是要替换掉这个 build-plugin，不知道进度如何？

可以了
