### ISSUE TITLE
按官方步骤开发组件，预览组件报错ColorfulButton Component Not Found

### ISSUE THREAD

**Issue by junegod** [alibaba/lowcode-engine#1524]
## **Describe the bug (required)** / **详细描述 bug（必填）**

同问题：https://github.com/alibaba/lowcode-engine/issues/1009

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

插件配置
<img width="780" alt="image" src="https://user-images.githubusercontent.com/2197929/216309441-4a38e1f9-cceb-4f1f-af27-5b894d5341b0.png">

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
正常预览

---

## **Screenshots (optional)** / **bug 截图（可选）**
<img width="2460" alt="image" src="https://user-images.githubusercontent.com/2197929/216308474-d2d06b42-81e1-485b-a675-8673717b077f.png">

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: 线上版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

**Comment by eternalsky** [comment]
my-lowcode-comp1 目前还会输出 ColorfulButton 吗

**Comment by eternalsky** [comment]
你好，请回答一下上面的问题，时间太久没有响应我们会关闭 issue~
