### ISSUE TITLE
公共数据源 使用报错,是用法不对还是其他？

### ISSUE THREAD

**Issue by yinxuejiang** [alibaba/lowcode-engine#1528]
## **Describe the bug (required)** / **详细描述 bug（必填）**
1. 文档
![image](https://user-images.githubusercontent.com/18732567/216558150-2ec7d8da-d054-4a07-aec3-39b2d8e96cc5.png)
2. 我的配置
![image](https://user-images.githubusercontent.com/18732567/216558627-23dfed4d-5b9d-4700-a980-b5d2af42859f.png)

3. 我的使用

![image](https://user-images.githubusercontent.com/18732567/216558905-4e449e0b-8000-4115-897e-2b212af14ed6.png)

4. 错误信息
![image](https://user-images.githubusercontent.com/18732567/216559073-ceb3a86c-9e74-45c2-8e5e-fca10c6ce3ff.png)

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by JackLian** [comment]
也许是没实现....需要确认下

**Comment by liujuping** [comment]
未复现，提供可以复现的步骤 / schema。

**Comment by yinxuejiang** [comment]
> 未复现，提供可以复现的步骤 / schema。

{
  "version": "1.0.0",
  "componentsMap": [
    {
      "devMode": "lowCode",
      "componentName": "Page"
    }
  ],
  "componentsTree": [
    {
      "componentName": "Page",
      "id": "node_dockcviv8fo1",
      "props": {
        "ref": "outerView",
        "style": {
          "height": "100%"
        }
      },
      "fileName": "/dashboard",
      "dataSource": {
        "list": [
          {
            "type": "fetch",
            "isInit": false,
            "options": {
              "params": {},
              "method": "GET",
              "isCors": true,
              "timeout": 5000,
              "headers": {},
              "uri": "mock/info.json"
            },
            "id": "info"
          }
        ]
      },
      "state": {
        "text": {
          "type": "JSExpression",
          "value": "\"outer\""
        },
        "isShowDialog": {
          "type": "JSExpression",
          "value": "false"
        }
      },
      "css": "body {\n  font-size: 12px;\n}\n\n.button {\n  width: 100px;\n  color: #ff00ff\n}",
      "lifeCycles": {
        "componentDidMount": {
          "type": "JSFunction",
          "value": "function componentDidMount() {\n  console.log('did mount');\n}"
        },
        "componentWillUnmount": {
          "type": "JSFunction",
          "value": "function componentWillUnmount() {\n  console.log('will unmount');\n}"
        }
      },
      "methods": {
        "testFunc": {
          "type": "JSFunction",
          "value": "function testFunc() {\n  console.log('test func');\n}"
        },
        "onClick": {
          "type": "JSFunction",
          "value": "function onClick() {\n  this.setState({\n    isShowDialog: true\n  });\n}"
        },
        "closeDialog": {
          "type": "JSFunction",
          "value": "function closeDialog() {\n  this.setState({\n    isShowDialog: false\n  });\n}"
        }
      },
      "originCode": "class LowcodeComponent extends Component {\n  state = {\n    \"text\": \"outer\",\n    \"isShowDialog\": false\n  }\n  componentDidMount() {\n    console.log('did mount');\n  }\n  componentWillUnmount() {\n    console.log('will unmount');\n  }\n  testFunc() {\n    console.log('test func');\n  }\n  onClick() {\n    this.setState({\n      isShowDialog: true\n    })\n  }\n  closeDialog() {\n    this.setState({\n      isShowDialog: false\n    })\n  }\n}",
      "hidden": false,
      "title": "dashboard",
      "isLocked": false,
      "condition": true,
      "meta": {
        "router": "/dashboard"
      },
      "conditionGroup": ""
    }
  ],
  "i18n": {},
  "constants": {
    "ENV": "prod",
    "DOMAIN": "xxx.com"
  },
  "dataSource": {
    "list": [
      {
        "type": "fetch",
        "isInit": false,
        "options": {
          "params": {},
          "method": "GET",
          "isCors": true,
          "timeout": 5000,
          "headers": {},
          "uri": "mock/info.json"
        },
        "id": "infoList"
      }
    ]
  }
}

**Comment by yinxuejiang** [comment]
> 未复现，提供可以复现的步骤 / schema。

{
  "version": "1.0.0",
  "componentsMap": [
    {
      "package": "@alilc/antd-lowcode-materials",
      "version": "1.1.1",
      "exportName": "Icon",
      "main": "",
      "destructuring": true,
      "componentName": "Icon"
    },
    {
      "package": "@alilc/antd-lowcode-materials",
      "version": "1.1.1",
      "exportName": "Button",
      "main": "",
      "destructuring": true,
      "componentName": "Button"
    },
    {
      "devMode": "lowCode",
      "componentName": "Page"
    }
  ],
  "componentsTree": [
    {
      "componentName": "Page",
      "id": "node_dockcviv8fo1",
      "props": {
        "ref": "outerView",
        "style": {
          "height": "100%"
        }
      },
      "fileName": "/dashboard",
      "dataSource": {
        "list": [
          {
            "type": "fetch",
            "isInit": false,
            "options": {
              "params": {},
              "method": "GET",
              "isCors": true,
              "timeout": 5000,
              "headers": {},
              "uri": "mock/info.json"
            },
            "id": "info"
          }
        ]
      },
      "state": {
        "text": {
          "type": "JSExpression",
          "value": "\"outer\""
        },
        "isShowDialog": {
          "type": "JSExpression",
          "value": "false"
        }
      },
      "css": "body {\n  font-size: 12px;\n}\n\n.button {\n  width: 100px;\n  color: #ff00ff\n}",
      "lifeCycles": {
        "componentDidMount": {
          "type": "JSFunction",
          "value": "function componentDidMount() {\n  console.log('did mount');\n}",
          "source": "function componentDidMount() {\n  console.log('did mount');\n}"
        },
        "componentWillUnmount": {
          "type": "JSFunction",
          "value": "function componentWillUnmount() {\n  console.log('will unmount');\n}",
          "source": "function componentWillUnmount() {\n  console.log('will unmount');\n}"
        }
      },
      "methods": {
        "testFunc": {
          "type": "JSFunction",
          "value": "function testFunc() {\n  console.log('test func');\n}",
          "source": "function testFunc() {\n  console.log('test func');\n}"
        },
        "onClick": {
          "type": "JSFunction",
          "value": "function onClick() {\n  this.dataSourceMap['info'].load({\n    id: 1\n  });\n}",
          "source": "function onClick() {\n  this.dataSourceMap['info'].load({\n    id: 1\n  });\n}"
        },
        "onClick_new": {
          "type": "JSFunction",
          "value": "function onClick_new() {\n  this.dataSourceMap['infoList'].load({\n    id: 1\n  });\n}",
          "source": "function onClick_new() {\n  this.dataSourceMap['infoList'].load({\n    id: 1\n  });\n}"
        }
      },
      "originCode": "class LowcodeComponent extends Component {\n  state = {\n    \"text\": \"outer\",\n    \"isShowDialog\": false\n  }\n  componentDidMount() {\n    console.log('did mount');\n  }\n  componentWillUnmount() {\n    console.log('will unmount');\n  }\n  testFunc() {\n    console.log('test func');\n  }\n  onClick() {\n    this.dataSourceMap['info'].load(\n      { id: 1 }\n    )\n  }\n  onClick_new() {\n    this.dataSourceMap['infoList'].load(\n      { id: 1 }\n    )\n  }\n}",
      "hidden": false,
      "title": "dashboard",
      "isLocked": false,
      "condition": true,
      "meta": {
        "router": "/dashboard"
      },
      "conditionGroup": "",
      "children": [
        {
          "componentName": "Button",
          "id": "node_ocldwi9tvv1",
          "props": {
            "type": "primary",
            "children": "页面数据",
            "__component_name": "Button",
            "htmlType": "button",
            "size": "middle",
            "shape": "default",
            "icon": {
              "type": "JSSlot",
              "value": [
                {
                  "componentName": "Icon",
                  "id": "node_ocldwi9tvv3",
                  "props": {
                    "type": "SmileOutlined",
                    "size": 20,
                    "rotate": 0,
                    "spin": false,
                    "__component_name": "Icon"
                  },
                  "hidden": false,
                  "title": "",
                  "isLocked": false,
                  "condition": true,
                  "conditionGroup": ""
                }
              ]
            },
            "block": false,
            "danger": false,
            "ghost": false,
            "disabled": false,
            "__events": {
              "eventDataList": [
                {
                  "type": "componentEvent",
                  "name": "onClick",
                  "relatedEventName": "onClick"
                }
              ],
              "eventList": [
                {
                  "name": "onClick",
                  "template": "onClick(event,${extParams}){\n// 点击按钮时的回调\nconsole.log('onClick', event);}",
                  "disabled": true
                }
              ]
            },
            "onClick": {
              "type": "JSFunction",
              "value": "function(){return this.onClick.apply(this,Array.prototype.slice.call(arguments).concat([])) }"
            }
          },
          "hidden": false,
          "title": "",
          "isLocked": false,
          "condition": true,
          "conditionGroup": ""
        },
        {
          "componentName": "Button",
          "id": "node_ocldwi9u322",
          "props": {
            "type": "primary",
            "children": "公共数据源",
            "__component_name": "Button",
            "htmlType": "button",
            "size": "middle",
            "shape": "default",
            "icon": {
              "type": "JSSlot",
              "value": [
                {
                  "componentName": "Icon",
                  "id": "node_ocldwi9u325",
                  "props": {
                    "type": "SmileOutlined",
                    "size": 20,
                    "rotate": 0,
                    "spin": false,
                    "__component_name": "Icon"
                  },
                  "hidden": false,
                  "title": "",
                  "isLocked": false,
                  "condition": true,
                  "conditionGroup": ""
                }
              ]
            },
            "block": false,
            "danger": false,
            "ghost": false,
            "disabled": false,
            "__events": {
              "eventDataList": [
                {
                  "type": "componentEvent",
                  "name": "onClick",
                  "relatedEventName": "onClick_new"
                }
              ],
              "eventList": [
                {
                  "name": "onClick",
                  "template": "onClick(event,${extParams}){\n// 点击按钮时的回调\nconsole.log('onClick', event);}",
                  "disabled": true
                }
              ]
            },
            "onClick": {
              "type": "JSFunction",
              "value": "function(){return this.onClick_new.apply(this,Array.prototype.slice.call(arguments).concat([])) }"
            },
            "style": {
              "marginLeft": "10px"
            }
          },
          "hidden": false,
          "title": "",
          "isLocked": false,
          "condition": true,
          "conditionGroup": ""
        }
      ]
    }
  ],
  "i18n": {},
  "constants": {
    "ENV": "prod",
    "DOMAIN": "xxx.com"
  },
  "dataSource": {
    "list": [
      {
        "type": "fetch",
        "isInit": false,
        "options": {
          "params": {},
          "method": "GET",
          "isCors": true,
          "timeout": 5000,
          "headers": {},
          "uri": "mock/info.json"
        },
        "id": "infoList"
      }
    ]
  }
}

**Comment by yinxuejiang** [comment]
> schema 导入失败，请检查并保证复现路径可行
项目初始化时候加上公共数据源
![image](https://user-images.githubusercontent.com/18732567/217707659-0f871326-e45c-4b5b-9dc6-0ac5f06d3a0b.png)

**Comment by liujuping** [comment]
建议从 demo 的 schema 面板里面复制 schema，可以在 demo 导入并且可以复现。如果必须要改动代码，最好提供改动好的代码仓库。

**Comment by liujuping** [comment]
还是不行，你代码复制过去更改可以成功？

**Comment by yinxuejiang** [comment]
demo的schema是只展示页面部分，无法显示公共的数据源，修改本地缓存，是可以的。看我的截图就在demo上。
页面数据源
![image](https://user-images.githubusercontent.com/18732567/217710331-360708f4-c553-41a5-9cfc-7ecfd0accb04.png)

公共数据源

![image](https://user-images.githubusercontent.com/18732567/217710398-ceda0695-fafe-400a-8f9a-e48ff02fb7d0.png)

**Comment by liujuping** [comment]
![image](https://user-images.githubusercontent.com/11935995/217710716-48041887-7361-4324-bfec-faf24c8d6069.png)

schema 放到缓存上，刷新页面会报错。

**Comment by yinxuejiang** [comment]
是不是编辑器，改了代码。
上传个源码
https://github.com/yinxuejiang/lowcode

**Comment by liujuping** [comment]
目前渲染模块主要是页面级别的，没有对应用级别的能力进行支持，比如公共数据源。

目前可以处理的方式时，在预览时获取到公共数据源的配置，并合并到页面的 schema 的数据源配置中。

后续关于应用级别的渲染我们再考虑一下怎么进行支持。
