### ISSUE TITLE
lowcode-materials/src/components/next-text/index.tsx 报错

### ISSUE THREAD

**Issue by phggg** [alibaba/lowcode-engine#153]
官方物料库的lowcode-materials/src/components/next-text/index.tsx文件中，没有引入PropTypes就直接使用了，导致出码后显示PropTypes is undefined
![image](https://user-images.githubusercontent.com/49742402/159119270-f231212f-2426-4124-ab87-187fb775b023.png)

**Comment by LeoYuan** [comment]
可以参考下 demo 项目里的配置：
1. html 中引入：https://github.com/alibaba/lowcode-demo/blob/68ff211662e2c813272cb9489996d063f833865f/public/index.ejs#L23
2. webpack 配置加上：https://github.com/alibaba/lowcode-demo/blob/68ff211662e2c813272cb9489996d063f833865f/build.json#L13

**Comment by phggg** [comment]
> 可以参考下demo项目里的配置：
> 
> 1. html中引入：https://github.com/alibaba/lowcode-demo/blob/68ff211662e2c813272cb9489996d063f833865f/public/index.ejs#L23
> 2. webpack配置添加：https://github.com/alibaba/lowcode-demo/blob/68ff211662e2c813272cb9489996d063f833865f/build.json#L13

成功了，感谢回复
