### ISSUE TITLE
如何让引擎初始化后将SimulatorResizer默认选中手机

### ISSUE THREAD

**Issue by Pzy1990** [alibaba/lowcode-engine#1542]
1、引擎的init API中配置了device为’mobile‘，但是初始化后SimulatorResizer选中的不是手机。
2、如何设置画布的高度？
<img width="804" alt="Snipaste_1" src="https://user-images.githubusercontent.com/89261896/217488046-2808622a-154d-4c8f-8dca-b075adb64abb.png">
![Snipaste_2](https://user-images.githubusercontent.com/89261896/217488085-0b75c4f6-cbe1-440a-b712-7f212681386d.png)

**Comment by JackLian** [comment]
1. SimulatorResizer 这个插件应该是有bug
2. 目前应该没有高度设置的能力

我们后续优化下，当然也欢迎PR

**Comment by liujuping** [comment]
如何设置画布的高度的问题可以重新提个 issue。默认选中手机已经解决了，device: 'phone',

**Comment by Pzy1990** [comment]
> 如何设置画布的高度的问题可以重新提个 issue。默认选中手机已经解决了，device: 'phone',

好的，那我是要更新一下哪个依赖呢？是@alilc/lowcode-plugin-simulator-select这个吗？

**Comment by liujuping** [comment]
是的。

**Comment by Pzy1990** [comment]
> @alilc/lowcode-plugin-simulator-select

好的，已解决

**Comment by Wangjing991** [comment]
组件库工程是用@alifd/build-plugin-lowcode这个包打包的，不支持device:'phone' 参数？
