### ISSUE TITLE
低代码编辑器能实现基准线自动对齐的吗

### ISSUE THREAD

**Issue by wenlai** [alibaba/lowcode-engine#1544]
低代码编辑能实现类似蓝湖、墨刀这些工具的，拖动组件时候，能自动显示基准线对齐的吗？如下图所示，如果可以，大概思路是怎样的？谢谢了
<img width="380" alt="image" src="https://user-images.githubusercontent.com/7650650/217688655-ea42f6a3-02c5-4546-8766-93bb5a82a8ca.png">

**Comment by wenlai** [comment]
<img width="359" alt="image" src="https://user-images.githubusercontent.com/7650650/217688943-d452fcd3-d490-4c02-8511-c87cf1d19efe.png">
同时显示边距这些数字指标

**Comment by JackLian** [comment]
理论上能做，不过这种首先是更适合绝对布局（自由布局）的画布，需要实现一个这样的画布才行，目前官方还没有这个实现计划
