### ISSUE TITLE
功能权限控制的最佳实践是什么

### ISSUE THREAD

**Issue by lulg** [alibaba/lowcode-engine#155]
比如：我一个页面上有10个按钮，要根据不同的权限来显示\隐藏部分按钮。

通过数据源加载权限数据，然后通过表达式控制显示隐藏？还是有更好的办法。

**Comment by JackLian** [comment]
一种是平台层（比如宜搭）做成内置功能，一种是平台层也不做管理，由平台上的业务开发自行实现，很多面向开发者的低代码平台就是这样
