### ISSUE TITLE
开发新组建时如何配置代理

### ISSUE THREAD

**Issue by goyidao** [alibaba/lowcode-engine#1556]
我正在开发一个新组件: demo，按照[文档](https://lowcode-engine.cn/site/docs/guide/expand/editor/material#%E6%96%B0%E5%BC%80%E5%8F%91%E7%BB%84%E4%BB%B6)，我的目录结构如图1。我想在该组件中请求本地的一个服务 http://localhost:8080/addData，遇到错误：
`Access to XMLHttpRequest at 'http://localhost:8080/addData' from origin 'http://172.18.218.120:3333' has been blocked by CORS policy: Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

我该如何添加配置文件解决这个问题？

- 图1：
![image](https://user-images.githubusercontent.com/22759537/217994785-e84654b4-d31d-46e6-9a57-18b761a2b92c.png)

**Comment by guohejun** [comment]
https://github.com/alibaba/lowcode-engine/issues/1129

**Comment by eternalsky** [comment]
既然是 addData 失败，那你应该解决的是 addData 的跨域限制，详细去看 mdn 的 cors 介绍。https://developer.mozilla.org/zh-CN/docs/Web/HTTP/CORS。
