### ISSUE TITLE
单独使用渲染模块时报错

### ISSUE THREAD

**Issue by Zenilia** [alibaba/lowcode-engine#1557]
## **Describe the bug (required)** / **详细描述 bug（必填）**
项目启动时报错
![image](https://user-images.githubusercontent.com/22741303/218036848-5a9ab729-ec8b-4882-b93a-6bef0efd162f.png)

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
import React, { useEffect, useState } from 'react';
import ReactDom from 'react-dom';
import PropTypes from 'prop-types';
import * as Next from '@alifd/next';
import { AssetLoader, buildComponents } from '@alilc/lowcode-utils';
import ReactRenderer from '@alilc/lowcode-react-renderer';

import { createFetchHandler } from '@alilc/lowcode-datasource-fetch-handler'
import { injectComponents } from '@alilc/lowcode-plugin-inject';
import styles from './index.module.css';

window.ReactDOM = ReactDom;
window.React = React;
window.Next = Next;
window.PropTypes = PropTypes;
interface ComponentProps {
  /** Title for MetapageLowcodeRenderer. */
  title: string;
}

export default function MetapageLowcodeRenderer(props: ComponentProps) {
  const { title = 'Hello World!' } = props;
  const [data, setData] = useState({});

  const init = async () => {
    try {
      const { schema: projectSchema, packages } = {
        schema: {
          version: '1.0.0',
          componentsMap: [
            {
              package: '@alifd/pro-layout',
              version: '1.0.1-beta.6',
              exportName: 'Col',
              main: 'lib/index.js',
              destructuring: true,
              subName: '',
              componentName: 'NextCol',
            },
            {
              package: '@alifd/pro-layout',
              version: '1.0.1-beta.6',
              exportName: 'Row',
              main: 'lib/index.js',
              destructuring: true,
              subName: '',
              componentName: 'NextRow',
            },
            {
              package: '@alifd/pro-layout',
              version: '1.0.1-beta.6',
              exportName: 'RowColContainer',
              main: 'lib/index.js',
              destructuring: true,
              subName: '',
              componentName: 'NextRowColContainer',
            },
            {
              package: '@alifd/pro-layout',
              version: '1.0.1-beta.6',
              exportName: 'BlockCell',
              main: 'lib/index.js',
              destructuring: true,
              subName: '',
              componentName: 'NextBlockCell',
            },
            {
              package: '@alifd/pro-layout',
              version: '1.0.1-beta.6',
              exportName: 'Block',
              main: 'lib/index.js',
              destructuring: true,
              subName: '',
              componentName: 'NextBlock',
            },
            {
              package: '@alilc/lowcode-materials',
              version: '1.0.5',
              exportName: 'NextText',
              main: 'lib/index.js',
              destructuring: true,
              subName: '',
              componentName: 'NextText',
            },
            {
              package: '@alifd/pro-layout',
              version: '1.0.1-beta.6',
              exportName: 'P',
              main: 'lib/index.js',
              destructuring: true,
              subName: '',
              componentName: 'NextP',
            },
            {
              package: '@alifd/pro-layout',
              version: '1.0.1-beta.6',
              exportName: 'PageHeader',
              main: 'lib/index.js',
              destructuring: true,
              subName: '',
              componentName: 'NextPageHeader',
            },
            {
              package: '@alifd/pro-layout',
              version: '1.0.1-beta.6',
              exportName: 'Page',
              main: 'lib/index.js',
              destructuring: true,
              componentName: 'NextPage',
            },
            { devMode: 'lowCode', componentName: 'Page' },
          ],
          componentsTree: [
            {
              componentName: 'Page',
              id: 'node_dockcviv8fo1',
              props: { ref: 'outerView', style: { height: '100%' } },
              fileName: '/',
              dataSource: {
                list: [
                  {
                    type: 'fetch',
                    isInit: true,
                    options: {
                      params: {},
                      method: 'GET',
                      isCors: true,
                      timeout: 5000,
                      headers: {},
                      uri: 'mock/info.json',
                    },
                    id: 'info',
                    shouldFetch: {
                      type: 'JSFunction',
                      value:
                        "function() { \n  console.log('should fetch.....');\n  return true; \n}",
                    },
                  },
                ],
              },
              state: {
                text: { type: 'JSExpression', value: '"outer"' },
                isShowDialog: { type: 'JSExpression', value: 'false' },
              },
              css: 'body {\n  font-size: 12px;\n}\n\n.button {\n  width: 100px;\n  color: #ff00ff\n}',
              lifeCycles: {
                componentDidMount: {
                  type: 'JSFunction',
                  value: "function componentDidMount() {\n  console.log('did mount');\n}",
                },
                componentWillUnmount: {
                  type: 'JSFunction',
                  value: "function componentWillUnmount() {\n  console.log('will unmount');\n}",
                },
              },
              methods: {
                testFunc: {
                  type: 'JSFunction',
                  value: "function testFunc() {\n  console.log('test func');\n}",
                },
                onClick: {
                  type: 'JSFunction',
                  value:
                    'function onClick() {\n  this.setState({\n    isShowDialog: true\n  });\n}',
                },
                closeDialog: {
                  type: 'JSFunction',
                  value:
                    'function closeDialog() {\n  this.setState({\n    isShowDialog: false\n  });\n}',
                },
              },
              originCode:
                'class LowcodeComponent extends Component {\n  state = {\n    "text": "outer",\n    "isShowDialog": false\n  }\n  componentDidMount() {\n    console.log(\'did mount\');\n  }\n  componentWillUnmount() {\n    console.log(\'will unmount\');\n  }\n  testFunc() {\n    console.log(\'test func\');\n  }\n  onClick() {\n    this.setState({\n      isShowDialog: true\n    })\n  }\n  closeDialog() {\n    this.setState({\n      isShowDialog: false\n    })\n  }\n}',
              hidden: false,
              title: '',
              isLocked: false,
              condition: true,
              conditionGroup: '',
              children: [
                {
                  componentName: 'NextPage',
                  id: 'node_ockzs2vw431',
                  props: {
                    headerDivider: true,
                    minHeight: '100vh',
                    presetNav: true,
                    presetAside: true,
                    footer: false,
                    nav: false,
                    aside: false,
                    placeholderStyle: { gridRowEnd: 'span 1', gridColumnEnd: 'span 12' },
                    headerProps: { background: 'surface' },
                    header: {
                      type: 'JSSlot',
                      value: [
                        {
                          componentName: 'NextPageHeader',
                          id: 'node_ockzs2vw433',
                          props: {},
                          title: '页面头部',
                          hidden: false,
                          isLocked: false,
                          condition: true,
                          conditionGroup: '',
                          children: [
                            {
                              componentName: 'NextRowColContainer',
                              id: 'node_ockzs2vw434',
                              props: { rowGap: 20, colGap: 20 },
                              title: '行列容器',
                              hidden: false,
                              isLocked: false,
                              condition: true,
                              conditionGroup: '',
                              children: [
                                {
                                  componentName: 'NextRow',
                                  id: 'node_ockzs2vw435',
                                  props: {},
                                  title: '行',
                                  hidden: false,
                                  isLocked: false,
                                  condition: true,
                                  conditionGroup: '',
                                  children: [
                                    {
                                      componentName: 'NextCol',
                                      id: 'node_ockzs2vw436',
                                      props: { colSpan: 1 },
                                      title: '列',
                                      hidden: false,
                                      isLocked: false,
                                      condition: true,
                                      conditionGroup: '',
                                      children: [
                                        {
                                          componentName: 'NextP',
                                          id: 'node_ockzvfoetv17',
                                          props: {
                                            wrap: false,
                                            type: 'body2',
                                            verAlign: 'middle',
                                            textSpacing: true,
                                            align: 'left',
                                          },
                                          docId: 'dockzvfoetv',
                                          title: '段落',
                                          hidden: false,
                                          isLocked: false,
                                          condition: true,
                                          conditionGroup: '',
                                          children: [
                                            {
                                              componentName: 'NextText',
                                              id: 'node_ockzvfoetv18',
                                              props: {
                                                type: 'h5',
                                                children: {
                                                  type: 'JSExpression',
                                                  value: 'this.state.info?.info',
                                                  mock: '标题标题',
                                                },
                                                mark: false,
                                                code: false,
                                                delete: false,
                                                underline: false,
                                                strong: false,
                                              },
                                              docId: 'dockzvfoetv',
                                              hidden: false,
                                              title: '',
                                              isLocked: false,
                                              condition: true,
                                              conditionGroup: '',
                                            },
                                          ],
                                        },
                                      ],
                                    },
                                  ],
                                },
                              ],
                            },
                          ],
                        },
                      ],
                      title: 'header',
                    },
                    isTab: false,
                    contentAlignCenter: false,
                    contentProps: { style: { background: 'rgba(255,255,255,0)' } },
                  },
                  title: '页面',
                  hidden: false,
                  isLocked: false,
                  condition: true,
                  conditionGroup: '',
                  children: [
                    {
                      componentName: 'NextBlock',
                      id: 'node_ockzs2vw437',
                      props: {
                        placeholderStyle: { height: '100%' },
                        noPadding: false,
                        noBorder: false,
                        title: '区域标题',
                        rowGap: 20,
                        colGap: 20,
                        background: 'surface',
                        layoutmode: 'O',
                        strict: true,
                        colSpan: 12,
                        rowSpan: 1,
                        mode: 'transparent',
                        childTotalColumns: 12,
                      },
                      title: '区域',
                      hidden: false,
                      isLocked: false,
                      condition: true,
                      conditionGroup: '',
                      children: [
                        {
                          componentName: 'NextBlockCell',
                          id: 'node_ockzs2vw438',
                          props: {
                            colSpan: 12,
                            rowSpan: 1,
                            mode: 'procard',
                            isAutoContainer: true,
                            title: '区块标题',
                          },
                          hidden: false,
                          title: '',
                          isLocked: false,
                          condition: true,
                          conditionGroup: '',
                          children: [
                            {
                              componentName: 'NextRowColContainer',
                              id: 'node_ockzs2vw439',
                              props: { rowGap: 20, colGap: 20 },
                              title: '行列容器',
                              hidden: false,
                              isLocked: false,
                              condition: true,
                              conditionGroup: '',
                              children: [
                                {
                                  componentName: 'NextRow',
                                  id: 'node_ockzs2vw43a',
                                  props: {},
                                  title: '行',
                                  hidden: false,
                                  isLocked: false,
                                  condition: true,
                                  conditionGroup: '',
                                  children: [
                                    {
                                      componentName: 'NextCol',
                                      id: 'node_ockzs2vw43b',
                                      props: { colSpan: 1 },
                                      title: '列',
                                      hidden: false,
                                      isLocked: false,
                                      condition: true,
                                      conditionGroup: '',
                                    },
                                  ],
                                },
                              ],
                            },
                          ],
                        },
                      ],
                    },
                  ],
                },
              ],
            },
          ],
          i18n: {},
        },
        packages: [
          {
            package: 'moment',
            version: '2.24.0',
            urls: ['https://g.alicdn.com/mylib/moment/2.24.0/min/moment.min.js'],
            library: 'moment',
          },
          {
            package: 'lodash',
            library: '_',
            urls: ['https://g.alicdn.com/platform/c/lodash/4.6.1/lodash.min.js'],
          },
          {
            title: 'fusion组件库',
            package: '@alifd/next',
            version: '1.26.4',
            urls: [
              'https://g.alicdn.com/code/lib/alifd__next/1.26.4/next.min.css',
              'https://g.alicdn.com/code/lib/alifd__next/1.26.4/next-with-locales.min.js',
            ],
            library: 'Next',
          },
          {
            title: 'NextTable',
            package: 'NextTable',
            version: '1.0.1',
            urls: [
              'https://g.alicdn.com/fusion-platform/pro-table/1.0.1/next-table.js',
              'https://g.alicdn.com/fusion-platform/pro-table/1.0.1/next-table.css',
            ],
            library: 'NextTable',
          },
          {
            package: '@alilc/lowcode-materials',
            version: '1.0.4',
            library: 'AlilcLowcodeMaterials',
            urls: [
              'https://alifd.alicdn.com/npm/@alilc/lowcode-materials@1.0.5/dist/AlilcLowcodeMaterials.js',
              'https://alifd.alicdn.com/npm/@alilc/lowcode-materials@1.0.5/dist/AlilcLowcodeMaterials.css',
            ],
            editUrls: [
              'https://alifd.alicdn.com/npm/@alilc/lowcode-materials@1.0.5/build/lowcode/view.js',
              'https://alifd.alicdn.com/npm/@alilc/lowcode-materials@1.0.5/build/lowcode/view.css',
            ],
          },
          {
            package: '@alifd/pro-layout',
            version: '1.0.1-beta.6',
            library: 'AlifdProLayout',
            urls: [
              'https://alifd.alicdn.com/npm/@alifd/pro-layout@1.0.1-beta.6/dist/AlifdProLayout.js',
              'https://alifd.alicdn.com/npm/@alifd/pro-layout@1.0.1-beta.6/dist/AlifdProLayout.css',
            ],
            editUrls: [
              'https://alifd.alicdn.com/npm/@alifd/pro-layout@1.0.1-beta.6/build/lowcode/view.js',
              'https://alifd.alicdn.com/npm/@alifd/pro-layout@1.0.1-beta.6/build/lowcode/view.css',
            ],
          },
          {
            package: '@alifd/fusion-ui',
            version: '1.0.5',
            library: 'AlifdFusionUi',
            urls: [
              'https://alifd.alicdn.com/npm/@alifd/fusion-ui@1.0.5/dist/AlifdFusionUi.js',
              'https://alifd.alicdn.com/npm/@alifd/fusion-ui@1.0.5/dist/AlifdFusionUi.css',
            ],
            editUrls: [
              'https://alifd.alicdn.com/npm/@alifd/fusion-ui@1.0.5/build/lowcode/view.js',
              'https://alifd.alicdn.com/npm/@alifd/fusion-ui@1.0.5/build/lowcode/view.css',
            ],
          },
        ],
      };
      const { componentsMap: componentsMapArray, componentsTree } = projectSchema;
      console.log(componentsMapArray, componentsTree, packages, projectSchema);
      const componentsMap: any = {};
      componentsMapArray.forEach((component: any) => {
        componentsMap[component.componentName] = component;
      });
      const schema = componentsTree[0];

      const libraryMap = {};
      const libraryAsset: any[] = [];
      packages.forEach(({ package: _package, library, urls, renderUrls }) => {
        libraryMap[_package] = library;
        if (renderUrls) {
          libraryAsset.push(renderUrls);
        } else if (urls) {
          libraryAsset.push(urls);
        }
      });

      // TODO asset may cause pollution
      const assetLoader = new AssetLoader();
      console.log(libraryAsset);
      await assetLoader.load(libraryAsset);
      const components = await injectComponents(buildComponents(libraryMap, componentsMap));
      console.log(schema, components)
      setData({
        schema,
        components,
      });
    } catch (e) {}
  };

  useEffect(() => {
    const x = init();
  }, [props.id]);

  return (
    <div className={styles.MetapageLowcodeRenderer}>{data.components && (
      <ReactRenderer
        className="lowcode-plugin-sample-preview-content"
        schema={data.schema}
        components={data.components}
        appHelper={{
          requestHandlersMap: {
            fetch: createFetchHandler(),
          },
        }}
      />
    )}</div>
  );
}
package依赖为：

    "prop-types": "^15.8.1",
    "@alifd/next": "^1.26.12",
    "@alilc/lowcode-datasource-fetch-handler": "^1.1.4",
    "@alilc/lowcode-plugin-inject": "^1.2.0",
    "@alilc/lowcode-react-renderer": "^1.0.18",
    "@alilc/lowcode-utils": "^1.0.18",
    "@swc/helpers": "^0.4.14"

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by liujuping** [comment]
参考这个文档：https://lowcode-engine.cn/site/docs/faq/faq014
