### ISSUE TITLE
build-plugin-lowcode /templates/index.jsx 文件的 basePackages的  antd固定为4.17.3

### ISSUE THREAD

**Issue by rudyzou** [alibaba/lowcode-engine#1560]
build-plugin-lowcode  /templates/index.jsx 文件的 basePackages的  antd固定为4.17.3 ，如果我想做一些跟antd5  相关的物料，会有版本冲突，希望可以把antd从basePackages中移除，或者basePackages可配置？
![image](https://user-images.githubusercontent.com/4281891/218120456-9e23d165-6f76-429b-b7eb-cf879c73283a.png)

**Comment by eternalsky** [comment]
可以试下配置 builtinAssets
