### ISSUE TITLE
低代码右侧属性编辑区无任何内容

### ISSUE THREAD

**Issue by enjoyWeb** [alibaba/lowcode-engine#1564]
网页地址  [https://lowcode-engine.cn/demo/demo-general/index.html](https://lowcode-engine.cn/demo/demo-general/index.html)
![image](https://user-images.githubusercontent.com/8252286/218359029-abab45d2-a347-4e61-a575-20793bef3907.png)

**Comment by JackLian** [comment]
未复现，麻烦提供下复现步骤

**Comment by enjoyWeb** [comment]
> 未复现，麻烦提供下复现步骤
打开这个线上地址 [https://lowcode-engine.cn/demo/demo-general/index.html](https://lowcode-engine.cn/demo/demo-general/index.html)，不会出现那个问题麽

**Comment by JackLian** [comment]
没啥问题

**Comment by enjoyWeb** [comment]
> 没啥问题

那奇怪了，怎么我这边看到的是长这样子，难道是我网络有问题哭😢
![image](https://user-images.githubusercontent.com/8252286/218359828-90339d12-fd6e-4aec-9004-8d08e7d5b46c.png)

**Comment by JackLian** [comment]
看看控制台有啥报错吗

**Comment by enjoyWeb** [comment]
> 看看控制台有啥报错吗

这个报错
![image](https://user-images.githubusercontent.com/8252286/218360522-297d878f-6788-4f1b-85f3-757ad1c5c9d6.png)

**Comment by alvarto** [comment]
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/1797855/218360738-b9f601c3-b614-4313-99c0-e252c2c18727.png">

浏览器版本过低，请仔细查看 README.md 里的浏览器版本要求。

**Comment by alvarto** [comment]
@hzd822 度城看看为啥 mixed setter 没有经过打包？浏览器基线是 Chrome 80，这里用了一个 Chrome 92 才支持的 API

**Comment by enjoyWeb** [comment]
> <img alt="image" width="1172" src="https://user-images.githubusercontent.com/1797855/218360738-b9f601c3-b614-4313-99c0-e252c2c18727.png">
> 
> 浏览器版本过低，请仔细查看 README.md 里的浏览器版本要求。

我用的360浏览器，谷歌确实是可以，尴尬了
