### ISSUE TITLE
【图片轮播】组件中的图片设置循环数据后，切换时会先跳第1张再跳对应的第n张

### ISSUE THREAD

**Issue by guohejun** [alibaba/lowcode-engine#1567]
描述(内网不方便贴图，请谅解)
【图片轮播】组件中的图片，【循环数据】绑定后，轮播滑动总是会先回到第一张图，再跳回到正常的第n张图

详细复现步骤：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 添加【图片轮播】组件；
3. 删除【图片轮播】中的图片，只保留一张；
4. 打开【源码面板】-JS中，给state中添加变量imgs，值为：
"imgs": [
    "https://img.alicdn.com/tps/TB1bewbNVXXXXc5XXXXXXXXXXXX-1000-300.png",
    "https://img.alicdn.com/tps/TB1xuUcNVXXXXcRXXXXXXXXXXXX-1000-300.jpg",
    "https://img.alicdn.com/tps/TB1ikP.NVXXXXaYXpXXXXXXXXXX-1000-300.jpg",
    "https://img.alicdn.com/tps/TB1s1_JNVXXXXbhaXXXXXXXXXXX-1000-300.jpg"
  ]
6. 选中仅剩的这张图片，设置-高级-循环，绑定[循环数据]为this.state.imgs；设置-属性-图片链接，绑定为this.item；
7. 点击【图片轮播】右箭头切换图片，发现图片总是**会先回到第一张图，再跳回到正常的第n张图**；

预期行为
每次点击箭头切换轮播图片，直接跳到对应顺序的图片即可

 - AliLowCodeEngine version: [1.0.18] / 低代码引擎版本
 - AliLowCodeEngineExt version: [1.0.5] / 低代码引擎扩展包版本
 - Browser [chrome 109.0.5414.120（正式版本)] / 浏览器版本

**Comment by JackLian** [comment]
建议先看看是否组件本身的问题，本项目核心是维护低代码相关的内容，组件本身的问题可以去对应的社区问一下，比如这个轮播底层是fusion组件，需要去fusion问问

**Comment by guohejun** [comment]
@JackLian 如果是直接在【图片轮播】组件中添加四照片是没有这个问题的，只要对其中一个使用了【循环数据】就能复现，麻烦大佬帮忙看下，我去看了fusion这个组件，是fork自react-slick仓库的，Issue翻看了很多，没有人遇到呢

**Comment by JackLian** [comment]
噢，你是对组件内的一张图片设置循环...那应该是不行的，循环只能设置在组件一级，不能设置在内部，一般来说可能会破坏组件原本的逻辑

**Comment by guohejun** [comment]
@JackLian 那像我这种场景，服务端返回的图片数量不定，是不是没办法使用【图片轮播】了？有没有别的建议方案呢

**Comment by guohejun** [comment]
【图片轮播】也算比较常见的使用场景，后面会处理下这种问题吗？

**Comment by JackLian** [comment]
确实现在这个轮播组件对低代码场景还不太友好，不过也确实不在本项目范畴内，可以自行开发一个轮播组件，暴露一个数据源prop，接受动态的图片数据即可。
后续我们也不太会处理这种问题

**Comment by guohejun** [comment]
@JackLian 好的，非常感谢~
