### ISSUE TITLE
关于TAB选项卡出码错误问题

### ISSUE THREAD

**Issue by frogo** [alibaba/lowcode-engine#1568]
关于选项卡出码错误的问题，之前已经提交了 issue，

![1676259972767](https://user-images.githubusercontent.com/3413313/218405975-cfe34c6d-55ab-446e-a88b-c3ce6f90b6e6.jpg)

LeoYuan大佬给出解决答案如下：

“问题出在 esmodule.ts 里处理 componentName 没有考虑 name.subName 格式~”

本人比较迷惑，不知道如何下手解决这个问题，不知道修改哪个文件，也没搜索到esmodule.ts在哪个模块，想请教修改哪个文件，才能让出码功能正常，希望大佬百忙中给予解答，谢谢

**Comment by LeoYuan** [comment]
duplicate of #1565
