### ISSUE TITLE
在outline tree/大纲树中根据disableBehaviors禁止部分组件功能

### ISSUE THREAD

**Issue by huxingyi1997** [alibaba/lowcode-engine#1569]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

在物料的configure中有disableBehaviors选项可以禁止默认行为，我在物料中配置了某个组件的disableBehaviors为["lock", "unlock"]，发现只能禁止画布上的"lock", "unlock"事件，无法禁止outline-tree上的"lock", "unlock"事件。

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

1. 配置物料的disableBehaviors选项可以禁止默认行为，我在物料中配置了某个组件的disableBehaviors为["lock", "unlock"]
2. 将该物料拖入画布
3. 打开outline-tree，选择该物料，发现可以通过outline-tree右侧的实现该物料的lock/unlock

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

打开outline-tree，根据物料的disableBehaviors禁止对应的事件图标。

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.18] / 低代码引擎版本 1.0.18
 - AliLowCodeEngineExt version: [e.g. 1.0.18] / 低代码引擎扩展包版本 1.0.18
 - Browser [e.g. chrome, safari] / 浏览器版本 chrome
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本 1.0.18

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
愿意协助开发

**Comment by JackLian** [comment]
建议等两天，1.1.0版本发了之后，再给大纲树提个PR~
