### ISSUE TITLE
预先检测下是否在内网环境中 的判断逻辑是否有更好的方式？

### ISSUE THREAD

**Issue by leoner** [alibaba/lowcode-engine#157]
https://github.com/alibaba/lowcode-code-generator-demo/blob/main/src/components/CodeGenPreview/useIsInIntranet.tsx

![image](https://user-images.githubusercontent.com/546535/159212180-2cb48825-0ddd-4f94-9739-93e3ba51be7b.png)

看代码目前是通过网络探测的方式来检查是否在内网， 但是这样会导致控制台有一个报错， 虽然不影响， 但是就是看着有些别扭。 

![image](https://user-images.githubusercontent.com/546535/159212079-381713e0-2b9a-4ff9-9344-0b6a32b97d2b.png)

**Comment by LeoYuan** [comment]
@Clarence-pan try catch 一下？😄

**Comment by supportUkr** [comment]
mark

**Comment by Clarence-pan** [comment]
@LeoYuan 已经有 try...catch 了的  只是网络请求失败即使 catch 了也会有个控制台报错的
