### ISSUE TITLE
用@alilc/element脚手架lowcode:build出来的资产包的地址是阿里内网的

### ISSUE THREAD

**Issue by wssgchungang** [alibaba/lowcode-engine#158]
### **问题描述：**
用@alilc/element脚手架lowcode:build出来的资产包的地址是阿里内网的

### **复现流程：**
1. npm init @alilc/element demo-material；
2. npm run lowcode:dev
3. npm run lowcode:build

### **问题截图：**
![image](https://user-images.githubusercontent.com/29122164/159228804-8ca301fc-3709-4e76-b180-b8f49ca67495.png)

**Comment by mark-ck** [comment]
fixed
