### ISSUE TITLE
今天早上本地运行和线上运行突然报错

### ISSUE THREAD

**Issue by JUNHAN12138** [alibaba/lowcode-engine#1584]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
本地运行和线上版本运行时报错
![image](https://user-images.githubusercontent.com/65531323/219254257-0fcf8978-84c6-4659-90e8-154202643069.png)

昨晚正常，
---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

复现bug，本人使用的是如下版本的
![image](https://user-images.githubusercontent.com/65531323/219254558-49afbcf2-cd4b-4df3-9934-8a1c469284a0.png)
运行之后报错，昨晚修改组件库时正常，

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
![image](https://user-images.githubusercontent.com/65531323/219254072-c7f4376f-e506-4de0-a021-3a6054e23190.png)

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by JackLian** [comment]
你得给复现的方法啊....
（如果是昨天好的今天坏了，那就看看这一晚上啥变了也行

**Comment by JUNHAN12138** [comment]
@JackLian 
![image](https://user-images.githubusercontent.com/65531323/219257120-3c3144d4-3655-4bc0-87f8-ec4fb8ef8271.png)
如何将这个版本改成现在的
![image](https://user-images.githubusercontent.com/65531323/219257158-fc624411-f4f6-40a3-9c0d-2d1f07f41970.png)

**Comment by liujuping** [comment]
看一下是不是配置了 simulatorUrl 如下：

```
simulatorUrl: [
    'https://alifd.alicdn.com/npm/@alilc/lowcode-react-simulator-renderer@latest/dist/css/react-simulator-renderer.css',
    'https://alifd.alicdn.com/npm/@alilc/lowcode-react-simulator-renderer@latest/dist/js/react-simulator-renderer.js'
],
```

需要去掉改配置，保持和引擎版本一致，或者引擎升级到最新版本。

**Comment by JUNHAN12138** [comment]
我把
![image](https://user-images.githubusercontent.com/65531323/219257940-ef328fd5-2a81-4517-b296-35e1bc47f33c.png)
这个版本号改成了1.1.1
![image](https://user-images.githubusercontent.com/65531323/219258047-e606016b-fdde-4cbf-880e-d3e5c7b4c319.png)
然后就不报错了，
看样子是版本不兼容老版本的一些逻辑吧

**Comment by liujuping** [comment]
是的，simulatorUrl 本身是会使用引擎相关的 api 的，如果一直使用 @latest，在比较大的版本升级的时候，不会对老的版本进行兼容。

建议将 simulatorUrl 配置去掉，否则后续还会出现类似的问题。

我们这边也会将 demo 和文档中类似的配置给去掉，防止给大家带来误解。

**Comment by JUNHAN12138** [comment]
好的，感谢

**Comment by Tanyangfan** [comment]
线上项目直接炸了。。。还好找到地方了
