### ISSUE TITLE
官网文档是不是写错了?

### ISSUE THREAD

**Issue by CaptainJon** [alibaba/lowcode-engine#1586]
这里的描述应该是`src/index.ts`吧？
![image](https://user-images.githubusercontent.com/51065061/219256875-9cb137fd-eb75-43f2-84d9-9dbb2fcdb241.png)

问题链接：[官网文档](https://lowcode-engine.cn/site/docs/guide/quickStart/start)

**Comment by JackLian** [comment]
已修复，今天上线
