### ISSUE TITLE
数据源绑定

### ISSUE THREAD

**Issue by caoshaohua1025** [alibaba/lowcode-engine#159]
1、请问下表格和柱状图等展示组件数据如何与数据源绑定
2、数据源添加参数问题，别人已经提过
3、添加数据源处理函数没作用，需要自己在出码的时候再写吗

**Comment by Clarence-pan** [comment]
1、请问下表格和柱状图等展示组件数据如何与数据源绑定 
 -- 组件数据可以通过变量绑定的方式跟数据源来绑定（绑定的数据的格式要跟组件需要的一致）
![image](https://user-images.githubusercontent.com/8750132/162875075-a86775f1-b4fc-441b-bc8c-479c148f5400.png)


2、数据源添加参数问题，别人已经提过

-- 如图所示
![image](https://user-images.githubusercontent.com/8750132/162875300-3f056d6a-95fe-4680-8b4d-033b3821638a.png)


3、添加数据源处理函数没作用，需要自己在出码的时候再写吗

-- 麻烦提供个最小可复现的 schema 吧  我这边看是没问题的

**Comment by liujuping** [comment]
这个问题应该是已经修复了，如果有没有修复的 Case 可以再重新打开一个。
