### ISSUE TITLE
渲染模式demo搭建报错

### ISSUE THREAD

**Issue by zhangxinGithub** [alibaba/lowcode-engine#1590]
![image](https://user-images.githubusercontent.com/16219343/219316890-2c77e0ec-9859-4e9c-81b7-56474cfcb366.png)
代码为官方文档示例
<img width="1419" alt="image" src="https://user-images.githubusercontent.com/16219343/219317210-4d2cea40-7f76-4931-a22f-909017b58207.png">
控制台报错

**Comment by liujuping** [comment]
看一下官网预览 html 的 js 资源是否都加载了，目测是 react 资源和 prop-types 资源不存在

![image](https://user-images.githubusercontent.com/11935995/219321238-8ad112a4-8eec-48d4-82bf-252c6fa8ac3b.png)

**Comment by liujuping** [comment]
https://lowcode-engine.cn/site/docs/faq/faq014

**Comment by zhangxinGithub** [comment]
<img width="1173" alt="image" src="https://user-images.githubusercontent.com/16219343/219334984-e6a2654b-8091-4814-b763-d8b0823fd88c.png">
打不开....

**Comment by zhangxinGithub** [comment]
@liujuping  谢谢你 解决啦
