### ISSUE TITLE
请教两个问题

### ISSUE THREAD

**Issue by KellenHe** [alibaba/lowcode-engine#1591]
1、请问低代码如何初始化编辑器中组件库的状态，和实际运行时保持一致。例如使用antd组件，需要初始化一些context，目前来看只有在物料中执行才会生效。
2、如何做代码的模块化，目前好像只能把代码全部写在源码面板里。在一个较为复杂的页面，源码面板的代码会比较多，能不能把reactrenderer当作物料，拖入设计器，来实现模块化。

**Comment by JackLian** [comment]
1. 目前没啥好方案，设计态和运行态需要比较明显的区分，毕竟是完全不同的两种使用场景和交互模式
2. 低代码组件不就是咯，https://lce.alibaba-inc.com/site/docs/guide/expand/editor/parts/partslcc
