### ISSUE TITLE
低代码搭建时，能否自定义编辑器画布？

### ISSUE THREAD

**Issue by Ambition-li** [alibaba/lowcode-engine#1592]
问题描述：低代码搭建时，能否自定义编辑器画布？例如用iframe插入一个页面，将组件往iframe中拖拽。或者，是否支持开发者自己开发编辑器画布？

**Comment by JackLian** [comment]
可以，有团队实现基于vue的或者G6的，稍后我们也会开源基于G6 X6的画布

**Comment by Ambition-li** [comment]
别的团队大概是怎么实现的？基于G6 X6的画布什么时候开源？

**Comment by LeoYuan** [comment]
> 别的团队大概是怎么实现的？基于G6 X6的画布什么时候开源？

@lukeup 接客~

后续是这个同学开源 g6 / x6 的引擎画布~

**Comment by yuanAIhan** [comment]
https://lowcode-engine.cn/site/docs/guide/expand/editor/graph 我看官网上给出来的例子里面是指

**Comment by yuanAIhan** [comment]
https://lowcode-engine.cn/site/docs/guide/expand/editor/graph 你好，我看官网给出来的例子里面，现在是已经支持X6来实现画布啦，想问一下，在X6的节点定义的时候https://x6.antv.antgroup.com/tutorial/getting-started，其是支持使用react组件来作为X6的节点的，其使用了使用 X6 配套的 React 渲染包 @antv-x6-react-shape，如果我想定义物料的时候也按照这种方式来实现，请问可以指点一下吗？目前没有头绪
