### ISSUE TITLE
出码后下载的 Zip 包里面的文件名有前导的反斜杠（\）

### ISSUE THREAD

**Issue by heiing** [alibaba/lowcode-engine#1593]
问题描述：

出码后下载的 Zip 包里面的文件名有前导的反斜杠（\）。如下图：

![20230217113012](https://user-images.githubusercontent.com/169673/219544696-67d72494-9074-49f2-9da3-1805e7405eb5.png)

影响：

- Windows 的文件浏览器（explorer）打开 zip 包，显示【此文件夹为空】，无法看到文件。用户认为在此场景下以为没有文件、以为出码有问题（空包），实际上是有目录和文件的。
- 在 Linux 下 unzip 解压缩，会出现一大堆告警消息，大意为：文件是绝对路径，剪裁掉变成相对路径。

---

复现步骤：

1. 打开 https://lowcode-engine.cn/demo/demo-general/index.html 
2. 点击 【出码】
3. 点击【导出/下载 zip 包】
4. 在 Windows 11 中用文件浏览器（explorer）打开 zip 包，不要用 winrar 或其它压缩软件。复现【此文件夹为空】的问题
5. 上传到 Linux 系统中，用 unzip 解压缩，复现出现一大堆 warning 消息的问题

---

期望：

- 删除每个目录与文件名的前导反斜杠（\）。
- 在压缩包内加一层目录（比如 exported-code），所有源码文件及目录放到 exported-code 目录中，避免把一堆的文件解压到当前工具目录。

**Comment by LeoYuan** [comment]
![image](https://user-images.githubusercontent.com/1195765/220002119-60780b60-3e6a-40bc-93a6-b6d40f4c215a.png)

@Clarence-pan 这里特意加了前缀“/”是为啥呀？

**Comment by LeoYuan** [comment]
> 在压缩包内加一层目录（比如 exported-code），所有源码文件及目录放到 exported-code 目录中，避免把一堆的文件解压到当前工具目录。

@heiing 这个需求建议你自己 fork 出码 demo 来支持吧~

**Comment by LeoYuan** [comment]
+ @alilc/lowcode-plugin-code-generator@1.0.6

**Comment by heiing** [comment]
> 这个需求建议你自己 fork 出码 demo 来支持吧~

好的~

看到文件名的前导反斜杠已经去除，非常感谢！
