### ISSUE TITLE
最新版本有问题，导致组件的子项无法使用

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#1595]
例如`Radio.Group`无法使用，但是`Radio`可以正常使用，你们官方的demo都有这个问题
你们demo上的表单项、单选组、多选组 全都有问题，这几个组件的特点都是子组件。

![image](https://user-images.githubusercontent.com/50658231/219647376-a7688864-e141-4de6-b9f5-3e809fb96821.png)

目前发现可能是这个库有问题，我锁死了版本，但是你们有几个包没锁死版本导致还是用了最新的包。
![image](https://user-images.githubusercontent.com/50658231/219646890-b965bfe0-c69d-44fb-90bf-207449a42d0b.png)

**Comment by Andrew-Zn** [comment]
啥情况哇，没人维护了？一早上起来打不开了

**Comment by JackLian** [comment]
> 啥情况哇，没人维护了？一早上起来打不开了

咋说话呢

**Comment by oneQiu** [comment]
> 咋说话呢

hhhh 今天要发版本，大佬看看能不能搞定一下这个bug，或者锁死下包版本呢

**Comment by LeoYuan** [comment]
> 啥情况哇，没人维护了？一早上起来打不开了

试着删除一下 init 启动时传入的 simulatorUrl 参数~

**Comment by oneQiu** [comment]
新问题，现在编辑页面进不去了。。和楼上老哥估计一样

**Comment by oneQiu** [comment]
![image](https://user-images.githubusercontent.com/50658231/219992438-d17c1edf-8581-4923-8415-bf6251f9f156.png)
![image](https://user-images.githubusercontent.com/50658231/219992459-16fdd3ba-5071-4836-b72d-48f7ebe18951.png)

**Comment by Andrew-Zn** [comment]
> > 什么情况哇，没人维护了？一早起来就打不开了
> 
> 尝试着删除一下init 启动时传入的simulatorUrl 参数~
感谢回复完美觉解问题

**Comment by Andrew-Zn** [comment]
> 

感谢回复完美觉解问题

**Comment by oneQiu** [comment]
总结一下：
Radio.Group的问题解决方案 暂时通过resolutions锁死版本，具体版本以自己项目之前使用的为准。
页面编辑打不开的解决方案：init的simulatorUrl锁死版本别用latest或者固定版本

**Comment by JackLian** [comment]
子组件问题，1.1.2 版本修复，已发
