### ISSUE TITLE
引用多个资产包，包中有重复组件名，组件被覆盖

### ISSUE THREAD

**Issue by yangye0817** [alibaba/lowcode-engine#1597]
目前是否有办法可以支持引用多个资产包，包中有相同组件名，组件被覆盖

**Comment by liujuping** [comment]
不可以的，如果有相同的组件名字，在组件渲染的时候没有办法知道获取的是哪个资产包里面的组件。

建议将不同的资产包增加一个前缀之类的标识，使组件名是唯一的。
