### ISSUE TITLE
源码面板创建事件会出现在class外面

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#1600]
复现步骤
1. 打开源码面板，在class外面敲一个空行
2. 选择组件，点击事件，创建
![image](https://user-images.githubusercontent.com/50658231/220006174-07c8b905-ccb4-4272-9834-988be7aeb917.png)

**Comment by alvarto** [comment]
我接手的时候源码面板/变量面板/事件面板都是用正则操作了，而代码操作应当在 AST 上操作才能保证 100% 稳妥。

因此低代码整体匹配模式都应该升级，不是这一个局部区块的问题。改动面有点大，不是短时间能 push 上来的。

不过针对这个 case 可以去微调正则，欢迎有志之士来 pr。
