### ISSUE TITLE
支持修改ProjectSchema的config

### ISSUE THREAD

**Issue by eightHundreds** [alibaba/lowcode-engine#1602]
# 背景

- 现有的project.importSchema,内部会新建一个document,旧的document不会删除. 用多了有内存泄露问题. 
- 我的需求会大量的修改ProjectSchema的config属性,所以只能用project.importSchema修改

同时希望提供类似DocumentModel.onImportSchema的事件, 我希望能监听到`project.importSchema`的调用

**Comment by liujuping** [comment]
“监听到project.importSchema的调用”

可以使用这个 API，https://lowcode-engine.cn/site/docs/api/project#onchangedocument

**Comment by eightHundreds** [comment]
> “监听到project.importSchema的调用”
> 
> 可以使用这个 API，https://lowcode-engine.cn/site/docs/api/project#onchangedocument

这个是document的,不是project的. 而且我只想监听导入的动作, 这个事件似乎拖拉拽页面元素也会触发

**Comment by eightHundreds** [comment]
顺便咨询一个问题

`project.documents`是一个数组, 这样的设计是为了实现一个project下多个page吗? 
但是我研究了宜搭的接口, 发现每个宜搭的页面都是一个新的project,且project下都只有有个page。
问这个问题是希望我二开的低代码能匹配上官方的设计思路

**Comment by JackLian** [comment]
协议设计时候关注通用性，但实际场景里，要看产品具体情况，宜搭每个页面就是独立的，单独编辑就好了，没必要都塞到一份schema里

**Comment by eightHundreds** [comment]
> 协议设计时候关注通用性，但实际场景里，要看产品具体情况，宜搭每个页面就是独立的，单独编辑就好了，没必要都塞到一份schema里

@JackLian 

我的诉求还有一部分没解答.

我希望支持修改ProjectSchema的config(不使用project.importSchema的方式, 原因见上面写的背景)

**Comment by JackLian** [comment]
上面不是答复你了吗....
