### ISSUE TITLE
物料内部使用react-router-dom的<Link>路由跳转组件，引擎会报错

### ISSUE THREAD

**Issue by ittat** [alibaba/lowcode-engine#1603]
## **Describe the bug (required)** / **详细描述 bug（必填）**

我希望提供<Link>提供界面点击跳转到项目站内其他页面，
但是，在物料内部使用react-router-dom的<Link>路由跳转组件，引擎会引起报错。

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

正常无报错，

---

## **Screenshots (optional)** / **bug 截图（可选）**

![image](https://user-images.githubusercontent.com/24728356/220028423-a55c5550-8a7b-440d-b270-e4bc6512b870.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by JackLian** [comment]
引擎引擎提供的renderer是页面/组件级的，不是应用级的，要实现你要的效果需要自行在产品层面实现一下，引擎目前没提供相关能力，短期也没有提供的计划

**Comment by ittat** [comment]
@JackLian 我实现了多页面。我想绕开引擎限制，让不同页面直接相互路由跳转。我参考了的这个物料的代码：https://github.com/alibaba/lowcode-materials/blob/main/packages/fusion-lowcode-materials/src/components/link/index.tsx#L23， 所以我试图通过在自定义的物料添加路由<Link>跳转到对应的页面。于是就出现了这个issue的报错，但是如果我改成html的<a>直接跳转就不会出现这个问题。我想确认一下，我这个<Link>方法是否可行?

**Comment by JackLian** [comment]
建议在appHelper上挂个utils方法，专门处理跳转

**Comment by ittat** [comment]
谢谢指引，非引擎侧问题，先关闭issue
