### ISSUE TITLE
关于lowcode-demo自由布局

### ISSUE THREAD

**Issue by tangxiao-8** [alibaba/lowcode-engine#1604]
## 关于lowcode-demo 自由布局设计

请问之前参照文档，lowcod-engine可以将布局改成自由布局的方式，但是当使用了lowcode-demo里面的综合场景后， 也能修改布局为自由布局嘛？

**Comment by JackLian** [comment]
没印象哪里提供过自由布局的能力....虽然能做，但官方还没做过，也没见有其他实现的

**Comment by SuperChrisliu** [comment]
> 没印象哪里提供过自由布局的能力....虽然能做，但官方还没做过，也没见有其他实现的

不提供自由布局的考虑是啥呢，这算是比较常见的的需求了，官方考虑支持吗

**Comment by JackLian** [comment]
目前没这个计划（自由带来的并不是自由，而是无所适从
