### ISSUE TITLE
schema面板渲染后，此后的schema变化，面板里不更新

### ISSUE THREAD

**Issue by wendell0316** [alibaba/lowcode-engine#1605]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 打开schema；
3. schema渲染后关闭schema面板；
4. 修改任意组件属性；
5. 打开schema面板；
6. schema面板内容没有更新

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
 schema面板内容会随任意属性变化而更新

---

## **Screenshots (optional)** / **bug 截图（可选）**
![image](https://user-images.githubusercontent.com/20490844/220038498-010fd9e3-7a3c-435f-8681-edfc7d08d98b.png)
![image](https://user-images.githubusercontent.com/20490844/220038635-54488c15-9f37-4ce3-925b-8678945a4e6d.png)
![image](https://user-images.githubusercontent.com/20490844/220038721-17094638-2f83-408d-95a4-1bb714f1cee9.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by JackLian** [comment]
你得保存... schema面板取的的是当前已保存的

**Comment by wendell0316** [comment]
未保存的情况下，先不打开schema面板，变更任意属性值之后再打开schema面板，取得是变化后的值，不是之前保存的。感觉像是面板渲染一次后就不会更新了。

**Comment by wendell0316** [comment]
我尝试了保存，但是也没有更新

**Comment by JackLian** [comment]
复现了，应该是个bug

**Comment by weibin529** [comment]
![image](https://user-images.githubusercontent.com/12807137/220045319-f5426e79-c91e-4a21-a0be-e0903cd65d90.png)
代码中这个事件没有触发

**Comment by JackLian** [comment]
> ![image](https://user-images.githubusercontent.com/12807137/220045319-f5426e79-c91e-4a21-a0be-e0903cd65d90.png) 代码中这个事件没有触发

可以帮忙提个PR ，参考这个地方写法改下 ，skeleton.onShowPanel
https://github.com/alibaba/lowcode-engine/blob/main/packages/plugin-outline-pane/src/index.tsx

**Comment by wuliupo** [comment]
> 我尝试了保存，但是也没有更新

我也是，感觉打开了以后不会更新了。类似的有两个，都不更新：
 lowcode-plugins/packages/plugin-schema
 lowcode-plugins/packages/plugin-code-editor

看了源码，ctx 下面的 plugin 事件有当前两个，event 和 pluginEvent，不清楚触发的机理是什么
我手动抛出事件，也不更新
