### ISSUE TITLE
源码面板可以在内网使用吗

### ISSUE THREAD

**Issue by catchingdream** [alibaba/lowcode-engine#1607]
![image](https://user-images.githubusercontent.com/20159168/220046601-0489b0c9-72ce-4de6-975e-a59071ef1a82.png)

**Comment by alvarto** [comment]
不太理解你的问题，只要有网，就能用源码面板，它是用阿里的 CDN 请求的 monaco-editor 的封装

**Comment by catchingdream** [comment]
> 
谢谢，我是说在没有网络的情况下。因为有些办公环境是局域网。

**Comment by alvarto** [comment]
可以把对应文件下载下来私有部署。
