### ISSUE TITLE
高级表格，编辑数据列的数据字段，增加操作列的事件，打印输出当前列数据，预览，打印当前数据列的 数据字段错误。

### ISSUE THREAD

**Issue by jurieo** [alibaba/lowcode-engine#1608]
## **Describe the bug (required)** / **详细描述 bug（必填）**

高级表格，编辑数据列的数据字段，增加操作列的事件，打印输出当前列数据，预览，打印当前数据列的 数据字段错误。影响所有已存在的数据源数据，新增的数据不会出现此错误。

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
Steps to reproduce the behavior: / 详细复现步骤：

1、打开demo
2、拖入高级表格
3、编辑任一数据列的数据字段，编辑完成关掉
4、编辑 操作列任一按钮事件，比如“查看”
5、在js源码新增相关的事件。
6、保存。然后预览。
7，打开控制台，点击“查看”，发现刚刚修改的字段，是修改过程的字段。

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

正常展示不包含数据字段输入过程的一条数据。

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
![image](https://user-images.githubusercontent.com/18009286/220047472-4be7eeb8-9d85-44ea-8c52-db5ce44f384f.png)

![image](https://user-images.githubusercontent.com/18009286/220047369-3e6c2251-128e-4141-8773-8bce04b4a16c.png)

![image](https://user-images.githubusercontent.com/18009286/220047130-90f39b09-f30f-4806-a72d-ae4af3791f5c.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.1.2] / 低代码引擎版本 v1.1.2
 - AliLowCodeEngineExt version: [e.g. 1.0.5] / 低代码引擎扩展包版本 v1.0.5
 - Browser [e.g. chrome, safari] / 浏览器版本 chrome，v106
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本  fusion-ui

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by eternalsky** [comment]
没看懂，是什么报错？
