### ISSUE TITLE
导出的schema的字段顺序应该进行排序，特别是布局字段

### ISSUE THREAD

**Issue by yz1311** [alibaba/lowcode-engine#1611]
## **详细描述 bug（必填）**

每次导出的schema排序字段感觉像随机的，导致整个schema改变了很多
1.会导致，如果比较判断页面是否发生变化，仅仅通过字符串JSON.stringify(schemaA ) == JSON.stringify(schemaB ),这样判断往往是不靠谱的，需要对对象进行深度比较
2.如果作代码比较，每次都是有不同点，下面是官方易搭的截图，明明字段值都没变，但是提交的时候，字段的顺序变了，然后就提示页面有变化

![image](https://user-images.githubusercontent.com/9854019/220229380-c46c8eb6-a241-4695-bcaa-ed3daa587341.png)

## **预期行为（必填，非常重要）**
api导出的schema的字段应该是进行过排序的

**Comment by LeoYuan** [comment]
JSON 怎么排序。。。

正常我理解判断 schema 是否有更改，应该用 history 的相关 API，再不济比对 schema 也得写个健全点的 json 比对函数，不是 stringify 去比对

**Comment by yz1311** [comment]
> JSON 怎么排序。。。
> 
> 正常我理解判断 schema 是否有更改，应该用 history 的相关 API，再不济比对 schema 也得写个健全点的 json 比对函数，不是 stringify 去比对

判断是否有更改这个倒还好，但是像 宜搭 的对比功能，字段值其实没有变化，但是顺序就全乱了，压根就不知道自己本次更改了什么东西，像对比功能我感觉是很重要的东西，不然每次提交都不知道自己改了什么东西（因为有一大堆本来没变，但是因为顺序变化导致的diff）

![image](https://user-images.githubusercontent.com/9854019/220231891-60d4d778-9214-4545-8ee4-1c132e9c1735.png)

有类似的库可以实现

https://github.com/ShivrajRath/jsonabc

**Comment by liujuping** [comment]
可以通过这个 api，自行对项目中的 props 等字段进行排序。

https://lowcode-engine.cn/site/docs/api/project#addpropstransducer

**Comment by LeoYuan** [comment]
是LeGao的diff界面？仅通过json行比对是做不了好用的diff的，想象一个节点的移动后的画面。。。建议看看 https://mp.weixin.qq.com/s/DmwxL67htHfTUP1U966N-Q

**Comment by yz1311** [comment]
> 是LeGao的diff界面？仅通过json行比对是做不了好用的diff的，想象一个节点的移动后的画面。。。建议看看 https://mp.weixin.qq.com/s/DmwxL67htHfTUP1U966N-Q

只是对组件属性排序，children或者items里面这种数组不处理(但是数组里面的对象顺序也进行排序)，这种也会导致节点顺序混乱吗?

**Comment by LeoYuan** [comment]
呃，那你先自己用jsonabc试试哈

**Comment by yz1311** [comment]
> 呃，那你先自己用jsonabc试试哈

好的，目前做的东西已经加了这个东西，暂待后续情况
