### ISSUE TITLE
如何通过ref获取focus

### ISSUE THREAD

**Issue by luotongxin1998** [alibaba/lowcode-engine#1615]
##  **详细描述 bug（必填）**
想知道物料和js面板之间如何去获取ref的焦点focus()
已经写了ref并获取到示例,但是this.$('checkBox_khk8').focus() 不生效
![image](https://user-images.githubusercontent.com/59943386/220295696-cf0fa526-9594-4c42-8bca-a1455b3e8e58.png)
![image](https://user-images.githubusercontent.com/59943386/220296598-1f8d331c-deb1-4ac8-aca3-891990abfc80.png)
![image](https://user-images.githubusercontent.com/59943386/220296779-71a92d34-cd69-4291-8a9c-6c2798e2424d.png)

**Comment by LeoYuan** [comment]
首先，设计器页面是不会执行 componentDidMount 等声明周期的，运行时会执行，
其次，this.$() 获取到组件 ref 之后，ref.xxx() 都是组件自身的行为，你需要看看 antCheckbox 的实现。
