### ISSUE TITLE
物料组件不能正常构建和发布

### ISSUE THREAD

**Issue by gu-xiaohui** [alibaba/lowcode-engine#162]
## **Describe the bug (required)** / **详细描述 bug（必填）**

自定义组件物料，lowcode:build报错
![image](https://user-images.githubusercontent.com/25246071/159412854-1a5b8d06-19f4-41ee-ba66-316c325ec31d.png)
再次执行 lowcode:dev或者build提示build-plugin-lowcode包不存在，执行过程中居然把包删掉了？这是什么操作
![image](https://user-images.githubusercontent.com/25246071/159413067-ca9bbd79-9877-466d-adac-210d1e5ef102.png)

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

用`@alilc/element` 新建一个组件物料，构建/发布试试就能复现

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
预期每一个操作都能正常进行

---

## **Screenshots (optional)** / **bug 截图（可选）**
上面描述有截图

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本 1.0.3
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本1.0.3
 - Browser [e.g. chrome, safari] / 浏览器版本 chrome 99
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

**Comment by LeoYuan** [comment]
![image](https://user-images.githubusercontent.com/1195765/159483816-37d5ed8b-6f53-4d33-b85c-ee6f157817d8.png)

无法复现啊，不过我是 m1 的电脑，多了个无限调用的问题。。。

**Comment by gu-xiaohui** [comment]
我给你录个视频，你看下吧，[视频链接](https://www.aliyundrive.com/s/YAhxP8Bb7mp)
你看我install之后，所有的包都是有的，包括那个types，但是执行lowcode:build之后，所有的包和types都自动被删除了

**Comment by gu-xiaohui** [comment]
我又调试了一下，发现执行这一步的时候，把所有的包都删掉了，但是具体为什么没找着原因，我看再往下就是调用了一个cross-spawn-promise的包去执行`npm i @types/react` 的操作，我单独启了一个项目去执行同样的操作，没有复现这个问题，但是在低代码组件库中就有这种现象
![20220324103025](https://user-images.githubusercontent.com/25246071/159830493-397c26c2-4a96-4934-838b-f302e5f4ae9d.jpg)

**Comment by LeoYuan** [comment]
你要不再把复现步骤按照1 2 3 4写一下，应该说你是目前唯一一个遇到这种问题的，需要非常精确的重现步骤🙏🏻

@mark-ck 也关注下哈

**Comment by gu-xiaohui** [comment]
1、npm install 安装好所有依赖
2、npm run lowcode:build

然后就自动把包全删了，后面就报错了

**Comment by LeoYuan** [comment]
无法复现~

你的 npm 是不是有 alias？

**Comment by gu-xiaohui** [comment]
> 无法复现~
> 
> 你的 npm 是不是有 alias？

没有alias，我怀疑我们说的不是一个东西，我说的是物料，用@alilc/element创建出来的物料组件，我这边找好几个同事试了都是一样的，必现的

**Comment by mark-ck** [comment]
> > 无法复现~
> > 你的 npm 是不是有 alias？
> 
> 没有alias，我怀疑我们说的不是一个东西，我说的是物料，用@alilc/element创建出来的物料组件，我这边找好几个同事试了都是一样的，必现的

![image](https://user-images.githubusercontent.com/44559440/160530556-42e6a195-eb9a-4be8-9f3d-3eaa8dfec870.png)

我这边没办法复现

**Comment by mark-ck** [comment]
@gu-xiaohui 你再 npm update 重新安装下依赖试试，我更新了下入料模块，现在 run lowcode:build 会检查是否已安装 `@types/react` ，如果已安装就不会再执行 install 操作，应该就不会出现上面的问题了。

**Comment by gu-xiaohui** [comment]
> @gu-xiaohui 你再 npm update 重新安装下依赖试试，我更新了下入料模块，现在 run lowcode:build 会检查是否已安装 `@types/react` ，如果已安装就不会再执行 install 操作，应该就不会出现上面的问题了。

更新之后，成功了一半，出现了新的报错
<img width="1792" alt="image" src="https://user-images.githubusercontent.com/25246071/160968883-b13b92b8-9fbc-4a01-8427-44a8b5916415.png">
新创建的组件库package.json多了一个逗号,，install的时候会报错
![image](https://user-images.githubusercontent.com/25246071/160969037-9d131312-b76a-4709-80b5-302aca376c4c.png)
![image](https://user-images.githubusercontent.com/25246071/160969174-767cf463-cf52-4691-aacc-ee66fc6e9d96.png)

**Comment by wangwenbin0035** [comment]
我在mac m1上用 iTerm dev, build 均成功，vscode无法运行，是否是这个问题 #176

**Comment by gu-xiaohui** [comment]
> 我在mac m1上用 iTerm dev, build 均成功，vscode无法运行，是否是这个问题 #176

应该不是一个问题

**Comment by mark-ck** [comment]
@gu-xiaohui 确实 react 组件库模板多了个 `,`，现在改好了

**Comment by gu-xiaohui** [comment]
> 

scss没找到那个问题还是有

**Comment by mark-ck** [comment]
> > 
> 
> scss没找到那个问题还是有

这个我没办法复现，你看看 src 下是否有那几个 scss 文件

**Comment by gu-xiaohui** [comment]
> 
文件是有的
![image](https://user-images.githubusercontent.com/25246071/161021768-2baabc3e-9c49-41c8-9fb8-44b77b33f253.png)

**Comment by mark-ck** [comment]
重新安装依赖再试试吧，应该没有这个问题了
