### ISSUE TITLE
自定义Setter如何实现变量绑定

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#1622]
例如我某个自定义Setter是个对象，对象内某个属性想实现变量绑定，有什么相关的文档可以满足开发吗？
就比如下面的自定义里面的【触发条件】字段

![image](https://user-images.githubusercontent.com/50658231/220544665-5e10de3e-f54e-4ef8-bfa6-26022aef9c27.png)

![image](https://user-images.githubusercontent.com/50658231/220544625-3afb9881-7768-4dba-8504-afd2c5b1843c.png)

**Comment by ittat** [comment]
@oneQiu Hi,请问你的问题解决了吗？我也遇到了这个问题， @hzd822 大佬，麻烦解答一下哦

**Comment by hzd822** [comment]
自定义setter想要绑定变量需要自己实现，具体可以有以下几个步骤
* 弹出绑定变量弹窗，具体可以看ext/plugin-variable-bind-dialog的打开函数，是通过event的事件进行绑定的common:variableBindDialog.openDialog
* 回填的时候需要将schema转变成普通的变量绑定格式，例如
*`"cardProps": {
                                  "actionButtons": [
                                    {
                                      "children": {
                                        "type": "JSExpression",
                                        "value": "this.state.text",
                                        "mock": "操作"
                                      }
                                    },
                                    {
                                      "children": "操作"
                                    },
                                    {
                                      "children": "操作"
                                    }
                                  ]
                                }`
