### ISSUE TITLE
已有项目添加编辑器引用@alilc/lowcode-plugin-inject 会报错

### ISSUE THREAD

**Issue by zhangxinGithub** [alibaba/lowcode-engine#1626]
![image](https://user-images.githubusercontent.com/16219343/220581030-5c0ba708-d410-4d57-bd44-8023d4526c4b.png)
<img width="1413" alt="image" src="https://user-images.githubusercontent.com/16219343/220581229-7c31e9b2-13e9-4465-80c5-3c8a4bc670a1.png">

**Comment by liujuping** [comment]
查看这个文档

https://lowcode-engine.cn/site/docs/faq/faq014

原来没有问题只是因为使用的 window.AliLowcodeEngine，但是插件的包是很有可能引 npm 包的，也得配置相关的构建配置项

**Comment by zhangxinGithub** [comment]
<img width="688" alt="image" src="https://user-images.githubusercontent.com/16219343/220828240-95113d74-fc1b-4508-8274-9583f0a356dc.png">
你好  之前的我是理解的  我想问题的是import InjectPlugin from '@alilc/lowcode-plugin-inject';  这个包我怎么引用才不会报错
