### ISSUE TITLE
引擎测功能增强建议

### ISSUE THREAD

**Issue by menkeydyvh** [alibaba/lowcode-engine#1628]
## **Describe the bug (required)** / ** 建议描述 **

在api->[node](https://lowcode-engine.cn/site/docs/api/model/node)处可以扩展一些对当前node对象的设置器【增、删、改、查】的api方法

## **Describe the bug (required)** / ** 目的 **
1. 增强了引擎的扩展性
2. 可以同一物料多人引入后根据自己的需求进行调整，减少相似物料库的重复自定义创建

**Comment by JackLian** [comment]
2 这个场景不理解是啥意思，你举个具体点的例子吧

**Comment by JackLian** [comment]
没太懂，那你写个自定义的图标setter应该也行吧

**Comment by JackLian** [comment]
所以你到底看没看文档.....

**Comment by LeoYuan** [comment]
试试这个：[registerMetadataTransducer](https://lowcode-engine.cn/site/docs/api/material#registermetadatatransducer)
