### ISSUE TITLE
引入物料库出现Bug,无法初始化

### ISSUE THREAD

**Issue by hustwebh** [alibaba/lowcode-engine#1629]
##  **详细描述 bug（必填）**
>引入物料库出现Bug,无法初始化
 请提供清晰且精确的 bug 描述
无论是在官方场景下https://alifd.alicdn.com/npm/@alilc/antd-lowcode-materials@1.1.0/build/lowcode/index.html
还是自己项目中，引入物料资源异常报错
---

## **如何复现 bug？（必填，非常重要）**
官方路径直接打开链接即可发现;
页面初始化一直卡在画布加载最后阶段并且无法获取组件库

##  **预期行为（必填，非常重要）**
应该正常完成初始化，在大约半个月前该功能完全正常

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
官方项目
![图片](https://user-images.githubusercontent.com/76393033/221006789-a7c6f019-dd3a-4fc8-80e1-6e95743f1c14.png)
同时加载官方物料资源和自定义物料资源
![图片](https://user-images.githubusercontent.com/76393033/221008510-b11471f2-98b7-42e5-b1c0-098ece533859.png)
仅加载自定义封装物料
![图片](https://user-images.githubusercontent.com/76393033/221009286-1346d808-a9c2-4b76-b171-2a8f7f03c570.png)
将引入物料语句注释后，控制台不再报错，但是物料组件功能无法使用
![图片](https://user-images.githubusercontent.com/76393033/221009565-89af92ae-33c0-40c5-b589-a39bbab0c044.png)
![图片](https://user-images.githubusercontent.com/76393033/221009662-0fa49cb9-ad94-4c13-b1f2-a5029c088638.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [1.0.10] / 低代码引擎版本
 - AliLowCodeEngineExt version: [^1.0.5] / 低代码引擎扩展包版本
 - Browser [firefox] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本
![图片](https://user-images.githubusercontent.com/76393033/221010385-52118ea6-7341-4286-9e18-ed8fe6c272ba.png)

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by JackLian** [comment]
看你截图，你用的demo工程挺古老了，可以试试最新的demo

**Comment by hustwebh** [comment]
> 看你截图，你用的demo工程挺古老了，可以试试最新的demo

我尝试更新依赖版本和使用最新demo,发现最新的demo正常使用，但是在自己项目中还是发生一样的Bug,在最新demo中引入自定义物料也没问题，但是在自己的项目中还是这个问题，甚至能够正常log出await injectAssets(assets.json),但是Bug没解决，主要是定位不到问题出在哪里
![图片](https://user-images.githubusercontent.com/76393033/221096037-5bf1dfbf-eac9-4521-98c7-b0cc4033ba8e.png)

**Comment by JackLian** [comment]
那继续对比下哪里不一样呗

**Comment by hustwebh** [comment]
> 那继续对比下哪里不一样呗
基于现有情形（可以正常加载页面但是组件加载有问题）可以确定出一定是加载物料资源这个插件初始化出现了问题吗？
