### ISSUE TITLE
lowcode-demo数据源希望增加代理,目前数据源数据源仅支持mock内的json数据.

### ISSUE THREAD

**Issue by duoduoObama** [alibaba/lowcode-engine#163]
需求: lowcode-demo数据源希望增加代理,目前数据源数据源仅支持mack内的json数据.

1.数据源目前仅支持mock json数据,数据不灵活.
2.增加了lowcode-demo 项目下build.json :
`
  "devServer": { 
    "proxy": {
      "/api": "https://www.baidu.com/",
      "client": {
        "logging": "info"
      }
    }
`
运行命令: npm run start 
控制台提示: use config proxy instead of devServer.proxy
但是代理不成功.
目前不清楚是功能未实现还是bug.

系统 / 浏览器: 5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/99.0.4844.74 Safari/537.36 Edg/99.0.1150.46

npm: v6.14.14
node: v14.17.5

**Comment by lijiaxu1996** [comment]
https://www.yuque.com/lce/usage/lsyhxn
可以动态调用接口啊
![image](https://user-images.githubusercontent.com/59685169/159426907-8b8619b0-08a1-4e89-9f73-470db870948a.png)
调用之后你绑定数据源就好了啊

**Comment by duoduoObama** [comment]
> 

这也是个方案,但我目前想要的是数据源这块,在启动项目的时候开发的阶段,启动项目能成功转发其它接口的功能.

目前我在飞冰(ice)1.x使用教程了解到build.json的代理配置.,https://www.bookstack.cn/read/ice-1.x/advance-proxy.md.成功使用了代理配置.他们工具链应该是互通的吧.

**Comment by lijiaxu1996** [comment]
这个应该是可以的，它这个demo启动好像就是用的ice

**Comment by rongrongt** [comment]
我试了下修改build.plugin.js文件可以设置本地代理成功
![image](https://user-images.githubusercontent.com/21823510/226566698-0096e865-decf-4360-ba55-ce91a677ff9a.png)
