### ISSUE TITLE
如何在js文件里面 通过事件  去改 mate.js  定义的值

### ISSUE THREAD

**Issue by 13508601302** [alibaba/lowcode-engine#1633]
例：defaultValue 的值 我是在mate.js  中定义的  
但是我想js这样去修改defaultValue ：
const onChange = (e) => {
        defaultValue = e.target.value +'123'  
    }
如何可以实现

**Comment by liujuping** [comment]
![image](https://user-images.githubusercontent.com/11935995/227890073-302babfd-c849-4515-937f-723bdf9762dc.png)
参考 lowcode-materials 中的 pagination 配置 packages/antd-lowcode-materials/lowcode/list/meta.ts
