### ISSUE TITLE
布局、菜单组件是出码后默认自带的吗？可以通过配置去掉吗？

### ISSUE THREAD

**Issue by guohejun** [alibaba/lowcode-engine#1634]
## **详细描述 bug**
【出码】后的代码包含BasicLayout

##  **如何复现 bug？**
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击【出码】；
3. 解压代码，npm install、npm run start，打开页面，发现页面带有顶部导航、侧边栏和底部这些布局组件；

## **预期行为**
期望【出包】后的代码npm run start运行之后，和【预览】时的效果一致！

**Comment by guohejun** [comment]
@LeoYuan 大佬，帮忙看下这个问题哈

**Comment by LeoYuan** [comment]
自定义自己的出码解决方案就行～

**Comment by guohejun** [comment]
![image](https://user-images.githubusercontent.com/27323522/221450660-fa7c6638-d2e0-44dc-8f21-dbdd2a9bd194.png)

**Comment by guohejun** [comment]
@LeoYuan 我在schema中将布局相关的属性都设置为了false，但【出码】后还是有那些组件出来。

**Comment by LeoYuan** [comment]
哪些是布局相关的？协议里有相关的行为描述么？

**Comment by guohejun** [comment]
@LeoYuan 抱歉哈，看了下协议，好像里面确实没有，这些是我看字面意思猜测的...
那您的意思是【出码】是没有相关配置去决定是否生成布局组件吗，如果是的话，那我就手动调整出码后的代码吧

**Comment by LeoYuan** [comment]
再解释一下，出码应该大致包含两个部分：出码引擎 + 出码解决方案，后者是一批自定义的插件、插槽、模块等，运行在出码引擎之上，目前在 demo 上展示的是一个内置的示范性的 icejs 项目出码方案，不一定功能完备，但是展示了出码引擎的功能以及出码解决方案应该如何写~

所以，你的需求实现的最佳方式应该是：
1. 自定义一个出码解决方案；
2. 复用 icejs 解决方案中的部分（参考出码引擎导出的[exports](https://github.com/alibaba/lowcode-engine/blob/2cf788c1716ae63fef20004348c59a5a65c6b3d2/modules/code-generator/src/index.ts#L37)），关闭 template 里定义的 layout 之类的部分；

**Comment by LeoYuan** [comment]
出码布局 / 路由相关的我们正在探索和制定中，后续将会在已有协议的基础上增补这块~

**Comment by guohejun** [comment]
好的，明白了，非常感谢[抱拳]
