### ISSUE TITLE
在dom节点层级和数量多的时候出现卡顿

### ISSUE THREAD

**Issue by Cossey11111** [alibaba/lowcode-engine#1635]
在dom节点层级和数量多的时候出现卡顿
并且chrome浏览器中出现如下警告
![image](https://user-images.githubusercontent.com/99870810/221149221-9e79bad3-72af-4c6c-a570-29e9e0b42df3.png)
这个问题有解决方案吗？

**Comment by JackLian** [comment]
有复现的方式吗
