### ISSUE TITLE
4 次 连续 config.set 会  白屏

### ISSUE THREAD

**Issue by ranyue** [alibaba/lowcode-engine#1636]
## **Screenshots (optional)** / **bug 截图（可选）**
![image](https://user-images.githubusercontent.com/22008492/221161436-2489fbe2-da3d-484d-ab36-a0c468ea90d3.png)
![image](https://user-images.githubusercontent.com/22008492/221161505-67b01fbd-4260-4d77-aeeb-91c22cc46cf7.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.10] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.10] / 低代码引擎扩展包版本
 - Browser [chrome] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

**Comment by liujuping** [comment]
尝试在 demo 中直接设置了多次，没有复现。需要提供可复现的代码和相关的步骤。

参考：https://lowcode-engine.cn/site/community/issue
