### ISSUE TITLE
运行demo报错(node_modules/@alifd/next/es/grid/main.scss)

### ISSUE THREAD

**Issue by EnglishVillage** [alibaba/lowcode-engine#1639]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
ERROR  Failed to compile with 1 errors                                                                       9:03:03 PM

 error  in ./node_modules/@alifd/next/es/grid/main.scss

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Expected whitespace.
   ╷
24 │                 @media (min-width: 320px)and(max-width: 479px){ @content; }
   │                                             ^
   ╵
  node_modules/@alifd/next/es/grid/scss/mixin.scss 24:45  breakpoint()
  node_modules/@alifd/next/es/grid/scss/mixin.scss 147:9  visible-hidden-all-points()
  node_modules/@alifd/next/es/grid/main.scss 2590:1       root stylesheet
    at /mnt/c/tmp/ali-lowcode-generated-sources/node_modules/webpack/lib/NormalModule.js:316:20
    at /mnt/c/tmp/ali-lowcode-generated-sources/node_modules/loader-runner/lib/LoaderRunner.js:367:11
    at /mnt/c/tmp/ali-lowcode-generated-sources/node_modules/loader-runner/lib/LoaderRunner.js:233:18
    at context.callback (/mnt/c/tmp/ali-lowcode-generated-sources/node_modules/loader-runner/lib/LoaderRunner.js:111:13)
    at /mnt/c/tmp/ali-lowcode-generated-sources/node_modules/sass-loader/dist/index.js:62:7
    at Function.call$2 (/mnt/c/tmp/ali-lowcode-generated-sources/node_modules/sass/sass.dart.js:102264:16)
    at render_closure1.call$2 (/mnt/c/tmp/ali-lowcode-generated-sources/node_modules/sass/sass.dart.js:87080:12)
    at _RootZone.runBinary$3$3 (/mnt/c/tmp/ali-lowcode-generated-sources/node_modules/sass/sass.dart.js:30345:18)
    at _FutureListener.handleError$1 (/mnt/c/tmp/ali-lowcode-generated-sources/node_modules/sass/sass.dart.js:28874:21)
    at _Future__propagateToListeners_handleError.call$0 (/mnt/c/tmp/ali-lowcode-generated-sources/node_modules/sass/sass.dart.js:29181:49)
    at Object._Future__propagateToListeners (/mnt/c/tmp/ali-lowcode-generated-sources/node_modules/sass/sass.dart.js:4014:77)
    at _Future._completeError$2 (/mnt/c/tmp/ali-lowcode-generated-sources/node_modules/sass/sass.dart.js:29027:9)
    at _AsyncAwaitCompleter.completeError$2 (/mnt/c/tmp/ali-lowcode-generated-sources/node_modules/sass/sass.dart.js:28675:12)
    at Object._asyncRethrow (/mnt/c/tmp/ali-lowcode-generated-sources/node_modules/sass/sass.dart.js:3816:17)
    at /mnt/c/tmp/ali-lowcode-generated-sources/node_modules/sass/sass.dart.js:20297:20
    at _wrapJsFunctionForAsync_closure.$protected (/mnt/c/tmp/ali-lowcode-generated-sources/node_modules/sass/sass.dart.js:3841:15)
    at _wrapJsFunctionForAsync_closure.call$2 (/mnt/c/tmp/ali-lowcode-generated-sources/node_modules/sass/sass.dart.js:28694:12)
    at _awaitOnObject_closure0.call$2 (/mnt/c/tmp/ali-lowcode-generated-sources/node_modules/sass/sass.dart.js:28688:25)
    at _RootZone.runBinary$3$3 (/mnt/c/tmp/ali-lowcode-generated-sources/node_modules/sass/sass.dart.js:30345:18)
    at _FutureListener.handleError$1 (/mnt/c/tmp/ali-lowcode-generated-sources/node_modules/sass/sass.dart.js:28874:21)
    at _Future__propagateToListeners_handleError.call$0 (/mnt/c/tmp/ali-lowcode-generated-sources/node_modules/sass/sass.dart.js:29181:49)
    at Object._Future__propagateToListeners (/mnt/c/tmp/ali-lowcode-generated-sources/node_modules/sass/sass.dart.js:4014:77)

 @ ./node_modules/@alifd/next/es/grid/style.js 1:0-21
 @ ./node_modules/@alifd/next/es/form/style.js
 @ ./node_modules/@alifd/pro-layout/es/style.js
 @ ./node_modules/@alifd/pro-layout/es/index.js
 @ ./node_modules/@alifd/fusion-ui/lib/index.js
 @ ./src/pages/$/index.jsx
 @ ./src/routes.js
 @ ./node_modules/build-plugin-ice-router/lib/runtime.js
 @ ./.ice/loadRuntimeModules.ts
 @ ./.ice/runApp.ts
 @ ./src/app.js
 @ multi ./node_modules/build-plugin-react-app/node_modules/react-dev-utils/webpackHotDevClient.js ./src/app.js

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
wsl ubuntu 20.04.5 LTS
node -v
v16.18.0
npm -v
9.5.1

# 安装依赖
$ npm install
# 启动服务
$ npm start
---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by JackLian** [comment]
是一直没成功过还是？

**Comment by EnglishVillage** [comment]
> 是一直没成功过还是？

对阿,一直失败,不知道到底是甚麽原因导致这个报错的!!!
是版本不对吗?

**Comment by JackLian** [comment]
按提示提供下上下文信息，node版本试试14

**Comment by wangzhenxi** [comment]
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/21288246/223599132-383ed77f-f177-47e4-9fcb-9792be2aee44.png">
<img width="781" alt="image" src="https://user-images.githubusercontent.com/21288246/223599144-b0c8eef9-1c8d-494f-8efc-befc16805740.png">

@alilc/lowcode-materials@1.1.0下@alifd/next的版本是1.25.14，这个版本素材出码后打包会出现同样的异常，@alifd/next新版本我看了，他是修复了scss打包的异常，我尝试把@alilc/lowcode-materials下的alifd/next版本升级，打包后发现版本还是1.25.14，可能是姿势不对

**Comment by eternalsky** [comment]
> <img alt="image" width="1175" src="https://user-images.githubusercontent.com/21288246/223599132-383ed77f-f177-47e4-9fcb-9792be2aee44.png">
> 
> <img alt="image" width="781" src="https://user-images.githubusercontent.com/21288246/223599144-b0c8eef9-1c8d-494f-8efc-befc16805740.png">
> 
> @alilc/lowcode-materials@1.1.0下@alifd/next的版本是1.25.14，这个版本素材出码后打包会出现同样的异常，@alifd/next新版本我看了，他是修复了scss打包的异常，我尝试把@alilc/lowcode-materials下的alifd/next版本升级，打包后发现版本还是1.25.14，可能是姿势不对

@wangzhenxi 哪里看到 @alilc/lowcode-materials@1.1.0下@alifd/next的版本是1.25.14~

**Comment by eternalsky** [comment]
这个问题应该是 alifd next 或者主题包的版本太低导致的，首先检查一下本地的主题包和 alifd/next 的版本，然后试着更新一下依赖。

**Comment by wangzhenxi** [comment]
> > <img alt="image" width="1175" src="https://user-images.githubusercontent.com/21288246/223599132-383ed77f-f177-47e4-9fcb-9792be2aee44.png">
> > <img alt="image" width="781" src="https://user-images.githubusercontent.com/21288246/223599144-b0c8eef9-1c8d-494f-8efc-befc16805740.png">
> > @alilc/lowcode-materials@1.1.0下@alifd/next的版本是1.25.14，这个版本素材出码后打包会出现同样的异常，@alifd/next新版本我看了，他是修复了scss打包的异常，我尝试把@alilc/lowcode-materials下的alifd/next版本升级，打包后发现版本还是1.25.14，可能是姿势不对
> 
> @wangzhenxi 哪里看到 @alilc/lowcode-materials@1.1.0下@alifd/next的版本是1.25.14~

不好意思，是1.25.23，这个版本是有问题的，我看1.26.14是正常的

**Comment by wangzhenxi** [comment]
> 这个问题应该是 alifd next 或者主题包的版本太低导致的，首先检查一下本地的主题包和 alifd/next 的版本，然后试着更新一下依赖。

我这边assets.json的@alifd/next是1.26.14，主题包@alifd/theme-design-pro是依赖"@alifd/next": "~1.25.x"，出码后的package.json还是1.25.23

**Comment by wangzhenxi** [comment]
<img width="1511" alt="image" src="https://user-images.githubusercontent.com/21288246/224025564-1be74f5c-6b43-4fd8-a86e-dd2b0291727b.png">
发现修改@alilc/lowcode-materials的build.lowcode.js不生效，但是修改@alifd/build-plugin-lowcode下BASIC_LIBRARY_VERSION的版本后，出码的@alifd/next版本才正常了

**Comment by hengyanqwe** [comment]
> <img alt="image" width="1511" src="https://user-images.githubusercontent.com/21288246/224025564-1be74f5c-6b43-4fd8-a86e-dd2b0291727b.png">
> 
> 发现修改@alilc/lowcode-materials的build.lowcode.js不生效，但是修改@alifd/build-plugin-lowcode下BASIC_LIBRARY_VERSION的版本后，再打包@alilc/lowcode-materials，这时候出码的@alifd/next版本才正常了

我也有这个问题，我是用lowcode-demo出码的，把出码后的@alifd/next改成1.25.51就不报错了，但是我没在lowcode-demo里找到BASIC_LIBRARY_VERSION的相关配置，现在懵逼中不知道咋改

**Comment by eternalsky** [comment]
报错是由于本地安装的 alifd/next 版本过低导致，和 assets 或者其他地方的配置无关。

**Comment by hengyanqwe** [comment]
> 报错是由于本地安装的 alifd/next 版本过低导致，和 assets 或者其他地方的配置无关。

那怎么解决呢？每次都要改出码后的package.json中的alifd/next才能跑？

**Comment by eternalsky** [comment]
> > 报错是由于本地安装的 alifd/next 版本过低导致，和 assets 或者其他地方的配置无关。
> 
> 那怎么解决呢？每次都要改出码后的package.json中的alifd/next才能跑？

出码后依赖的什么版本？

**Comment by hengyanqwe** [comment]
> > > 报错是由于本地安装的 alifd/next 版本过低导致，和 assets 或者其他地方的配置无关。
> > 
> > 
> > 那怎么解决呢？每次都要改出码后的package.json中的alifd/next才能跑？
> 
> 出码后依赖的什么版本？

出码后原本的版本是"@alifd/next": "1.25.23",

**Comment by eternalsky** [comment]
> > 报错是由于本地安装的 alifd/next 版本过低导致，和 assets 或者其他地方的配置无关。
> 
> 那怎么解决呢？每次都要改出码后的package.json中的alifd/next才能跑？

另外你这个问题，貌似已经和题主的不是同一个问题，题主是说 lowcode-demo 运行不起来，最好不要放在一个帖子里讨论。
如果有问题，建议提个出码的issue，再进行讨论。
