### ISSUE TITLE
创建物料的时候，抱this.getOption 错误

### ISSUE THREAD

**Issue by galenjiang** [alibaba/lowcode-engine#1649]
创建物料的时候，抱this.getOption 错误
安装less-loader@2.x后正常

出现这个问题的原因是，物料模版遗漏了一些依赖，并且lock文件没有包含在内，导致编译错误

**Comment by galenjiang** [comment]
当然，不单是模版有问题，整个lowcode-engine项目都没有lock文件，请问下是出于什么情况的考虑

**Comment by galenjiang** [comment]
名字搞错了，是 style-loader @eternalsky

**Comment by eternalsky** [comment]
请说明创建物料执行的命令，所处的操作系统、node 环境等

**Comment by galenjiang** [comment]
[脚手架初始化](https://lowcode-engine.cn/site/docs/guide/expand/editor/cli#%E8%84%9A%E6%89%8B%E6%9E%B6%E5%88%9D%E5%A7%8B%E5%8C%96)
mac13.2.1, node v16.13.1 但和版本没有关系，按照这个走一遍，正常的流程都走不通的。

**Comment by eternalsky** [comment]
初始化的是哪种元素？物料？具体的分类选的哪个？

**Comment by galenjiang** [comment]
组件/物料 ->  react-单组件

**Comment by eternalsky** [comment]
刚刚试了一下，没有发现你说的问题，你是在创建的时候就报错了吗，还是后面执行什么命令的时候报的错，用的npm 是哪个(yarn/npm/pnpm 哪个)版本多少？

**Comment by galenjiang** [comment]
pnpm 6.11.0的问题，npm跑了一下，没有问题

**Comment by eternalsky** [comment]
ok，那 issue close？还是要继续看下 pnpm 的问题？

**Comment by goodchax** [comment]
用pnpm有问题，npm没有问题。
