### ISSUE TITLE
按照官网例子的流程，使用npm init @aliac/element my-material创建的例子，在运行时控制台报错，求解

### ISSUE THREAD

**Issue by scyblyj** [alibaba/lowcode-engine#1656]
硬件：Apple M1 Pro ，操作系统：macOS Ventura13.1
1.首先通过npm init @aliac/element my-material初始化物料项目
2.执行npm install时，经过测试，node16.18.0（官方推荐）、node 19.1.0下都会安装不成功，现在node14.21.2上安装成功，但是不知道会不会有其他问题，所以想明确一下哪个版本的node最适合
3.执行npm run lowcode:dev运行成功，但是浏览器控制台报错：
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/21094742/222024119-feee0ccd-6885-44b9-96be-c7da1fd3ef80.png">
4.执行npm publish成功后，按照官网说明，把assets-prod.json的packages和components在demo-general项目中进行merge，但是使用时报组件渲染异常：
<img width="1060" alt="image" src="https://user-images.githubusercontent.com/21094742/222075768-b048b837-43e7-4331-a24a-69eefc323cea.png">
<img width="1508" alt="image" src="https://user-images.githubusercontent.com/21094742/222075842-c5f4e19a-e85d-47a8-8171-d0fc9fc6d6ca.png">

**Comment by LeoYuan** [comment]
node 16 无法运行的问题，@eternalsky 可以帮忙看下~

Button 获取不到，是因为没有注入 Next/Fusion 资源，检查下资产包里的 library 字段~

**Comment by scyblyj** [comment]
可以说具体一些吗？我是按照官网步骤进行的，如果build出来的assets.json中缺少资源，应该怎样着手解决呢？

**Comment by LeoYuan** [comment]
> 把assets-prod.json的packages和components在demo-general项目中进行merge

怎么 merge 的？注意依赖顺序，你的组件得在 @alifd/next 之后哈

**Comment by eternalsky** [comment]
初始化物料的时候选择的是什么？

**Comment by scyblyj** [comment]
> 初始化物料的时候选择的是什么？

选择的React-组件库

**Comment by scyblyj** [comment]
> > 把assets-prod.json的packages和components在demo-general项目中进行merge
> 
> 怎么 merge 的？注意依赖顺序，你的组件得在 @alifd/next 之后哈

手动复制粘贴的，好像确实把组件的packages和schema放到了最前面。

**Comment by eternalsky** [comment]
> 

这个里面用到一个 build 插件，里面依赖了 node-sass ，在 16 下编译不过去，最近准备重新整理这块的东西。目前选择组件库的话只能在 14 来进行。

**Comment by scyblyj** [comment]
> > 
> 
> 这个里面用到一个 build 插件，里面依赖了 node-sass ，在 16 下编译不过去，最近准备重新整理这块的东西。目前选择组件库的话只能在 14 来进行。

意思是这个脚手架工具最近会更新吗？大概时间是多久呢？更新后支持的node版本是哪个呢？

**Comment by eternalsky** [comment]
> 

应该在这个月内会更新。

**Comment by eternalsky** [comment]
@scyblyj 尝试一下最新初始化是否还有问题

**Comment by tive6** [comment]
@eternalsky 在mac m1 pro系统脚手架构建组件库 npm i 后运行 npm run lowcode:build 还有问题

`
ERR! (undefined) ./src/index.scss
ERR! TypeError: this.getOptions is not a function
ERR! 
ERR! (undefined) ./node_modules/.store/@alilc+lowcode-utils@1.1.6/node_modules/@alilc/lowcode-utils/es/cursor.less
ERR! TypeError: this.getOptions is not a function
ERR! 
ERR! (undefined) ./src/components/colorful-input/index.scss
ERR! TypeError: this.getOptions is not a function
ERR! 
ERR! (undefined) ./src/components/colorful-button/index.scss
ERR! TypeError: this.getOptions is not a function
ERR! 
ERR! (undefined) ./node_modules/.store/@alilc+lowcode-renderer-core@1.1.6/node_modules/@alilc/lowcode-renderer-core/es/components/VisualDom/index.css
ERR! TypeError: this.getOptions is not a function
`

**Comment by eternalsky** [comment]
> @eternalsky 在mac m1 pro系统脚手架构建组件库 npm i 后运行 npm run lowcode:build 还有问题
> 
> `ERR! (undefined) ./src/index.scss ERR! TypeError: this.getOptions is not a function ERR! ERR! (undefined) ./node_modules/.store/@alilc+lowcode-utils@1.1.6/node_modules/@alilc/lowcode-utils/es/cursor.less ERR! TypeError: this.getOptions is not a function ERR! ERR! (undefined) ./src/components/colorful-input/index.scss ERR! TypeError: this.getOptions is not a function ERR! ERR! (undefined) ./src/components/colorful-button/index.scss ERR! TypeError: this.getOptions is not a function ERR! ERR! (undefined) ./node_modules/.store/@alilc+lowcode-renderer-core@1.1.6/node_modules/@alilc/lowcode-renderer-core/es/components/VisualDom/index.css ERR! TypeError: this.getOptions is not a function`

这是因为你的工程中，可能从哪里引入了 webpack5，可以将 webpack 全局锁定到 4，再尝试一下。
