### ISSUE TITLE
根据文档 已有的源码组件转化为低代码物料过程中报错

### ISSUE THREAD

**Issue by ajieying** [alibaba/lowcode-engine#166]
1、根据文档https://www.yuque.com/lce/doc/funcv8#ehg7Q 转化我们内部已有的基于antd的组件库为低代码物料；
2、安装相关依赖npm install -D @alifd/build-plugin-lowcode build-scripts
3、根据文档，在根目录新增build.lowcode.js文件；
4、在package中，新增lowcode:dev, lowcode:build命令："lowcode:dev": "build-scripts start --config ./build.lowcode.js",
"lowcode:build": "build-scripts build --config ./build.lowcode.js",
5、执行 npm run lowcode:dev 
结果：报错，参考下图
<img width="1259" alt="image" src="https://user-images.githubusercontent.com/9877509/159500252-4638a835-acf8-4755-8a22-119a58f6f197.png">

请问这个是什么问题?

本地环境：node:v14.18.2; npm:v6.14.15; macOS Monterey12.2.1
本地已经安装webpack 
webpack 4.44.2
webpack-cli 4.8.0

**Comment by ajieying** [comment]
<img width="1572" alt="image" src="https://user-images.githubusercontent.com/9877509/159616224-8d7343e7-98ab-42ae-bf7f-06c5be46037d.png">
按照上面的方法直行之后，还是会报错，如上图所示

**Comment by mark-ck** [comment]
tsconfig.json 打开看看，看报错像是内容不对，需要是合法的 json 数据

**Comment by ajieying** [comment]
上面是我的tsconfig.js的问题，调整之后的如下图：
<img width="713" alt="image" src="https://user-images.githubusercontent.com/9877509/159620722-735a39c5-0e78-43ab-8928-40f8e5821a77.png">
在执行 npm run lowcode:dev之后，能正常的产出.tmp文件夹及其中的文件，但是还是会报下面的错误：
<img width="1130" alt="image" src="https://user-images.githubusercontent.com/9877509/159621042-646e052b-a21a-4d62-88c6-f816f9ffc207.png">
生成的meta.js中的antd的版本是4.17.3，如下图
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/9877509/159621136-de89bdfc-a762-4fbc-a8bc-43513ed4cbcd.png">
和我们组件库中试用的antd的版本不一样，我们用的antd版本是4.16.13，不知道是不是这个版本不一致引起的问题；

**Comment by mark-ck** [comment]
style-loader 需要安装一下😂，另外两个问题需要设置下 alias ，我看是 components 和 utils 找不到

**Comment by ajieying** [comment]
<img width="703" alt="image" src="https://user-images.githubusercontent.com/9877509/159627101-4a26df94-eeb0-4b3c-8961-5668b9957bbe.png">
您好，别的问题我这都解决了，麻烦看下上面这个是什么问题？

**Comment by mark-ck** [comment]
看起来像是 less-loader 版本问题，试试这个 `npm install less-loader@7.3.0 --save-dev`

**Comment by ajieying** [comment]
还是不行，还是有这个问题

**Comment by mark-ck** [comment]
我这边的项目都复现不了，方便发一个复现项目给我看看吗？

**Comment by ajieying** [comment]
请问build.config.js 都支持哪些配置啊，有文档吗？

**Comment by ajieying** [comment]
> 我这边的项目都复现不了，方便发一个复现项目给我看看吗？

公司有限制，上传还需要审批😓

**Comment by LeoYuan** [comment]
建议直接来个可复现项目~

项目结构支不支持、webpack loader 缺失、依赖版本号不对，可能的问题太多了，能提供可复现 demo，排查人员一次性就给你答案，这不香么😄
