### ISSUE TITLE
rax物料库问题

### ISSUE THREAD

**Issue by chenld1113** [alibaba/lowcode-engine#1663]
https://github.com/alibaba/lowcode-tools/blob/f7a6b1e57236770ad075d67b13f7eaa415dd60f2/packages/build-plugin-lowcode/src/templates/index.jsx#L59 ,外网不能访问https://mc-fusion.alibaba-inc.com/
![image](https://user-images.githubusercontent.com/32389179/222327183-637c4af8-8baa-4188-bc8f-56026984d83c.png)

**Comment by JackLian** [comment]
官方未提供rax物料库，后续也没计划提供
