### ISSUE TITLE
如何让组件库工程初始化后将SimulatorResizer默认选中手机

### ISSUE THREAD

**Issue by Wangjing991** [alibaba/lowcode-engine#1664]
![image](https://user-images.githubusercontent.com/19301714/222350593-b7781722-52ec-4e34-a3e6-07ec5cb8899b.png)
![image](https://user-images.githubusercontent.com/19301714/222350611-ca706f27-e4f1-4377-8fe9-bece52914c1f.png)
这个依赖用的是cdn 资源 不支持配置 device:'mobile' 参数

**Comment by liujuping** [comment]
Duplicate of
https://github.com/alibaba/lowcode-engine/issues/1542

**Comment by Wangjing991** [comment]
![image](https://user-images.githubusercontent.com/19301714/222599557-40c1e6ad-4b28-46dc-b7e9-0eaafa972bbc.png)
配置presetConfig 参数不生效，@alifd/lowcode-preset-plugin这个包使用的是cdn资源

**Comment by Wangjing991** [comment]
> Duplicate of #1542
这个是编辑器工程可以设置，我这边遇到的是组件库工程
