### ISSUE TITLE
咨询：引擎是否支持在拖入画布前，用户做一些预处理

### ISSUE THREAD

**Issue by hjgeek** [alibaba/lowcode-engine#1669]
场景：
一个表格组件，拖入到画布中后，弹出弹框配置字段（字段从数据源的入参获得）
1、用户点击确认，将组装新的schema插入画布
2、用户点击取消，则阻止schema插入画布

现状：
拖入到画布中，直接就插入进去了。
引擎有没有什么办法，或者钩子方法，来支持这样的场景呢？

**Comment by liujuping** [comment]
比如可以在这个 API 中监听 Node 新增事件

https://lowcode-engine.cn/site/docs/api/model/document-model#onaddnode

当组件时表格组件的时候，

1.弹出弹框配置字段，用户确定的时候，node.importschema 修改 schema

https://lowcode-engine.cn/site/docs/api/model/node#importschema

2.用户点击取消，node.remove 删除这个 node。

https://lowcode-engine.cn/site/docs/api/model/node#remove

不一定非要用拦截的方式来做预处理。

**Comment by hjgeek** [comment]
![image](https://user-images.githubusercontent.com/45581788/223054589-24851ab1-c515-435a-b142-8a3056705c70.png)
感谢感谢~~
