### ISSUE TITLE
使用skeletonCabin.Workbench方式接入报o.skeleton.buildFromConfig is not a function

### ISSUE THREAD

**Issue by baieceo** [alibaba/lowcode-engine#167]
## **Describe the bug (required)** / **详细描述 bug（必填）**

按照官网 https://lowcode-engine.cn/docV2/start-with-lce 方法 2.2 使用 skeletonCabin.Workbench 方式初始化接入报错

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

```
/* eslint-disable react-hooks/exhaustive-deps */
import React, { useState, useEffect } from 'react';
import { init, common, plugins, config, project, skeleton } from '@alilc/lowcode-engine';

import '../universal/global.less';

const preference = new Map();

preference.set('DataSourcePane', {
  importPlugins: [],
  dataSourceTypes: [
    {
      type: 'fetch',
    },
    {
      type: 'jsonp',
    },
  ],
});

function FormDesigner() {
  /** 插件是否已初始化成功，因为必须要等插件初始化后才能渲染 Workbench */
  const [hasPluginInited, setHasPluginInited] = useState(false);

  async function main() {
    config.setConfig({
      // designMode: 'live',
      // locale: 'zh-CN',
      enableCondition: true,
      enableCanvasLock: true,
      // 默认绑定变量
      supportVariableGlobally: true,
      // simulatorUrl 在当 engine-core.js 同一个父路径下时是不需要配置的！！！
      // 这里因为用的是 alifd cdn，在不同 npm 包，engine-core.js 和 react-simulator-renderer.js 是不同路径
      simulatorUrl: [
        'https://alifd.alicdn.com/npm/@alilc/lowcode-react-simulator-renderer@latest/dist/css/react-simulator-renderer.css',
        'https://alifd.alicdn.com/npm/@alilc/lowcode-react-simulator-renderer@latest/dist/js/react-simulator-renderer.js',
      ],
    });

    await plugins.init(preference);

    setHasPluginInited(true);
  }

  useEffect(() => {
    plugins
      .init()
      .then(() => {
        setHasPluginInited(true);
      })
      .catch((err) => console.error(err));
  }, []);

  return <div>{hasPluginInited && <common.skeletonCabin.Workbench skeleton={skeleton} />}</div>;
}

export default FormDesigner;
```

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
![image](https://user-images.githubusercontent.com/19337357/159620437-2f62c74f-9505-4655-9c74-442c47a6a3ca.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.1] / https://alifd.alicdn.com/npm/@alilc/lowcode-engine@1.0.1/dist/js/engine-core.js
 - AliLowCodeEngineExt version: [e.g. 1.0.2] / https://alifd.alicdn.com/npm/@alilc/lowcode-engine-ext@1.0.2/dist/js/engine-ext.js
 - Browser [e.g. chrome, safari] / Chrome 版本 98.0.4758.102（正式版本） （64 位）
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本
 - 

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by LeoYuan** [comment]
参考 demo 中的示例，以及使用最新版的引擎就好
