### ISSUE TITLE
在outline tree/大纲树中 1.1.2版本出现组件展开失常问题

### ISSUE THREAD

**Issue by huxingyi1997** [alibaba/lowcode-engine#1672]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

在outline tree/大纲树中 1.1.2版本中，在右侧panel区域显示大纲树后，左侧大纲树插件中容器组件展开功能失常，无法展开

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

1. 打开 [demo](https://lowcode-engine.cn/demo/demo-general/index.html)；
2. 打开左侧大纲树，注意不要展开Page
![image](https://user-images.githubusercontent.com/58174093/222688398-b333dd20-12dc-4876-ba0d-5f79cf6abc18.png)
3. 拖拽新的组件至Page内部，注意右侧出现大纲树，且Page处于展开状态
![image](https://user-images.githubusercontent.com/58174093/222689115-7abf97cb-d833-4365-b63d-c88c28c81fdc.png)
4. 重新打开左侧大纲树，此时Page无法展开
![Screen Shot 2023-03-03 at 5 57 13 PM](https://user-images.githubusercontent.com/58174093/222692591-1e8f34c7-57e5-49c6-b424-1ee55013f1aa.png)
其他容器组件也会出现同样的问题

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

修复右侧大纲树与左侧大纲树展开不同插件后左侧大纲树插件容器组件展开功能失常的问题，左侧大纲树中的容器组件能够正常展开

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---
在复现步骤中

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version / 低代码引擎版本: 1.1.2
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本: 1.1.2
 - Browser / 浏览器版本: chrome
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本: 1.1.2

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
在packages/plugin-outline-pane/src/index.tsx文件中，可以看出左右2个plugin-outline-tree共用了同一个TreeMaster实例，经过短暂测试使用不同TreeMaster实例不会产生此问题，但不知道是否可能产生其他潜在问题，愿意辅助开发

**Comment by jurieo** [comment]
我还发现大纲树其他的问题，比如弹框在大纲树中的隐藏显示问题，多点几次，隐藏和显示的状态就不一致了，页面组件越多，这个问题更明显。

**Comment by JackLian** [comment]
试试最新的demo看还有没有问题，目前最新的基于1.1.3-beta.x
