### ISSUE TITLE
antd高级组件----CURD表格中的编辑按钮获取“点击行数据失败”

### ISSUE THREAD

**Issue by Dawei921** [alibaba/lowcode-engine#1679]
## **Describe the bug (required)** / **详细描述 bug（必填）**

antd高级组件----CURD表格中的编辑按钮获取“点击行数据失败”

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1.直接访问官方demo: https://lowcode-engine.cn/demo/demo-antd-pro-with-formily/index.html
<img width="1191" alt="image" src="https://user-images.githubusercontent.com/20964884/223069574-98645609-3b47-44f3-804a-17ec33c8421f.png">
给操作列添加参数
<img width="944" alt="image" src="https://user-images.githubusercontent.com/20964884/223081720-40ee9ed9-cbe8-4f3a-95cd-f73f8a92ff35.png">

2.给编辑按钮添加onClick事件
<img width="1480" alt="image" src="https://user-images.githubusercontent.com/20964884/223069898-a6921c57-8dab-4650-90fc-ac89d734e465.png">
3.添加 打印
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/20964884/223070254-f020574e-1b39-4387-8f17-475e0f8bffad.png">

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
打印出行信息

---

## **Screenshots (optional)** / **bug 截图（可选）**
<img width="1016" alt="image" src="https://user-images.githubusercontent.com/20964884/223070503-15f5d02b-5720-44cf-80af-42dee03368c3.png">

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
官方demo环境

**Comment by Dawei921** [comment]
解决了

**Comment by hinhinlaw** [comment]
> 解决了

你好，请问怎么解决的呢？碰到同样问题
