### ISSUE TITLE
SlotSetter如何设置默认开启插槽，不用每次手动点击switch去开启

### ISSUE THREAD

**Issue by ChiZng** [alibaba/lowcode-engine#1681]
## SlotSetter如何设置默认开启插槽，不用每次手动点击switch去开启

在组件描述文件meta.ts中设置组件属性为SlotSetter，如何设置可以将SlotSetter设置为默认开启，不用每次在组件属性设置中点击Switch开关开启才能往Slot中拖组件
---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
SlotSetter设置
```
{
    name: 'children4',
    title: 'children4',
    setter: {
      componentName: 'SlotSetter',
      isRequired: true,
      title: 'children4',
      initialValue: {
        type: 'JSSlot',
        value: [],
      },
    }
  }
```
![image](https://user-images.githubusercontent.com/27946984/223349154-5dc7370a-11f4-4d24-8e6b-50117b6d50ff.png)

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngineExt version: [e.g. 1.0.6] / 低代码引擎扩展包版本

**Comment by liujuping** [comment]
配置如下 initialValue，具体的 value 可以看默认插槽的内容是什么来设置即可

```
 initialValue: {
    type: 'JSSlot',
    params: [''],
    value: [
      {
        componentName: 'Box',
      },
    ],
  },
```
