### ISSUE TITLE
求助：在拖入组件之后更改组件的可见性属性以及绑定变量

### ISSUE THREAD

**Issue by hustwebh** [alibaba/lowcode-engine#1687]
**需求场景是这样的：希望自定义一个物料容器，里面包含一个开关，被拖入该容器的组件可见性将受到这个开关的checked状态控制**

在低代码引擎中，可以通过绑定开关onChange事件到源码面板state变量并且将其他目标物料的是否渲染属性从Boolean值变成JS表达式，但是现在要求将物料拖入就自动受控

目前实现思路是用代码复刻上述操作，但是第一不知道如何在初始化之后不手动的生成源码面板内容，同时，安插在物料Meta中的State并不能反映到源码面板中去（也就是无法被变量绑定Setter识别到）
不知道有没有什么建议的实现方法

**Comment by eternalsky** [comment]
有两种思路，基于容器的开关属性的 setValue，在他改变的时候更改他的children 的对应可见性属性。或者children 的可见性的属性 的 getValue 去拿他父容器的 开关属性状态。https://lowcode-engine.cn/site/docs/specs/material-spec#22241-%E5%B1%9E%E6%80%A7%E9%9D%A2%E6%9D%BF%E9%85%8D%E7%BD%AE-props-a
