### ISSUE TITLE
数据源插件，删除icon有没有提供回调方法

### ISSUE THREAD

**Issue by ssjjdd** [alibaba/lowcode-engine#1689]
目的：想在点击删除的时候，写一些业务代码

![image](https://user-images.githubusercontent.com/23442317/223664394-90973b38-4ff6-4a91-a324-55fa6dcb24d5.png)

**Comment by JackLian** [comment]
如果业务定制比较多，建议可以直接fork这个插件自行修改

**Comment by Z-Champion** [comment]
> 

请问一下新增一些其他功能要如何修改？

**Comment by ssjjdd** [comment]
> > 
> 
> 请问一下新增一些其他功能要如何修改？

我一般把官方的插件源码下载下来，改完以后打个包，然后把项目中的插件引用改成自己的打的包

**Comment by PineSongCN** [comment]
> > > 
> > 
> > 
> > 请问一下新增一些其他功能要如何修改？
> 
> 我一般把官方的插件源码下载下来，改完以后打个包，然后把项目中的插件引用改成自己的打的包

请问插件名和修改数据源插件引用的文档路径是否可以发一下？

**Comment by ssjjdd** [comment]
> > > > 
> > > 
> > > 
> > > 请问一下新增一些其他功能要如何修改？
> > 
> > 
> > 我一般把官方的插件源码下载下来，改完以后打个包，然后把项目中的插件引用改成自己的打的包
> 
> 请问插件名和修改数据源插件引用的文档路径是否可以发一下？
可以看一下这个
[plugin-datasource-pane](https://github.com/alibaba/lowcode-plugins/tree/main/packages/plugin-datasource-pane)

**Comment by PineSongCN** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 请问一下新增一些其他功能要如何修改？
> > > 
> > > 
> > > 我一般把官方的插件源码下载下来，改完以后打个包，然后把项目中的插件引用改成自己的打的包
> > 
> > 
> > 请问插件名和修改数据源插件引用的文档路径是否可以发一下？
> > 可以看一下这个
> > [plugin-datasource-pane](https://github.com/alibaba/lowcode-plugins/tree/main/packages/plugin-datasource-pane)

谢谢

**Comment by ssjjdd** [comment]
> > > > > 
> > > > 
> > > > 
> > > > 请问一下新增一些其他功能要如何修改？
> > > 
> > > 
> > > 我一般把官方的插件源码下载下来，改完以后打个包，然后把项目中的插件引用改成自己的打的包
> > 
> > 
> > 请问插件名和修改数据源插件引用的文档路径是否可以发一下？
> > 可以看一下这个
> > [plugin-datasource-pane](https://github.com/alibaba/lowcode-plugins/tree/main/packages/plugin-datasource-pane)


/

> > > > > > 
> > > > > 
> > > > > 
> > > > > 请问一下新增一些其他功能要如何修改？
> > > > 
> > > > 
> > > > 我一般把官方的插件源码下载下来，改完以后打个包，然后把项目中的插件引用改成自己的打的包
> > > 
> > > 
> > > 请问插件名和修改数据源插件引用的文档路径是否可以发一下？
> > > 可以看一下这个
> > > [plugin-datasource-pane](https://github.com/alibaba/lowcode-plugins/tree/main/packages/plugin-datasource-pane)
> 
> 谢谢

修改完后，打包成dist，放到你原有项目里，然后把项目本身引用node_modules里数据源的路径改成指向这个dist

**Comment by PineSongCN** [comment]
> > > > > > 
> > > > > 
> > > > > 
> > > > > 请问一下新增一些其他功能要如何修改？
> > > > 
> > > > 
> > > > 我一般把官方的插件源码下载下来，改完以后打个包，然后把项目中的插件引用改成自己的打的包
> > > 
> > > 
> > > 请问插件名和修改数据源插件引用的文档路径是否可以发一下？
> > > 可以看一下这个
> > > [plugin-datasource-pane](https://github.com/alibaba/lowcode-plugins/tree/main/packages/plugin-datasource-pane)
> 
> /
> 
> > > > > > > 
> > > > > > 
> > > > > > 
> > > > > > 请问一下新增一些其他功能要如何修改？
> > > > > 
> > > > > 
> > > > > 我一般把官方的插件源码下载下来，改完以后打个包，然后把项目中的插件引用改成自己的打的包
> > > > 
> > > > 
> > > > 请问插件名和修改数据源插件引用的文档路径是否可以发一下？
> > > > 可以看一下这个
> > > > [plugin-datasource-pane](https://github.com/alibaba/lowcode-plugins/tree/main/packages/plugin-datasource-pane)
> > 
> > 
> > 谢谢
> 
> 修改完后，打包成dist，放到你原有项目里，然后把项目本身引用node_modules里数据源的路径改成指向这个dist

嗯嗯，谢谢
