### ISSUE TITLE
 VERSION_PLACEHOLDER is not defined

### ISSUE THREAD

**Issue by leoner** [alibaba/lowcode-engine#169]
就是自定义项目打包的时候， 发现页面引用 这个文件 node_modules/@alilc/lowcode-engine/es/engine-core.js 的时候， 页面有一个变量， 这个变量是在什么时候替换的呢？

![image](https://user-images.githubusercontent.com/546535/159639584-3c9db6e5-4bf0-42c7-ae5b-985f65e390f1.png)

**Comment by liujuping** [comment]
目前仅支持 cdn 的用法，这确实也是个bug，后面会再考虑是否修复。

暂时可以先在项目配置上 extends 掉。

**Comment by liujuping** [comment]
Duplicate of https://github.com/alibaba/lowcode-engine/issues/137

**Comment by leoner** [comment]
![image](https://user-images.githubusercontent.com/546535/162764409-5356d23d-4c50-4303-a7d1-837877eb0ad4.png)

嗯， 加上这个是可以了。
