### ISSUE TITLE
好像本地跑不起来

### ISSUE THREAD

**Issue by tanyo520** [alibaba/lowcode-engine#17]
引擎考虑的还是挺全面的

**Comment by liujuping** [comment]
目前提供交流的有社区钉钉群。

![IMG_1324 JPG](https://user-images.githubusercontent.com/11935995/154631409-8529a1ef-08f5-4114-8fba-84f0e783838c.JPG)

**Comment by Zian502** [comment]
本地跑起来，有些资源请求不到
![Uploading image.png…]()

**Comment by Zian502** [comment]
![image](https://user-images.githubusercontent.com/26033663/154806774-b0244931-7041-4714-a6dd-7258c919f8b9.png)

**Comment by LeoYuan** [comment]
请看 demo 项目~
