### ISSUE TITLE
如果现有组件库中antd的版本和@alifd/build-plugin-lowcode这个包中规定的antd版本不一致，会有什么问题?

### ISSUE THREAD

**Issue by ajieying** [alibaba/lowcode-engine#170]
<img width="907" alt="image" src="https://user-images.githubusercontent.com/9877509/159640152-f93b512a-aab5-4426-9001-d6f8246a700a.png">
如题，包里的antd版本是4.17.3，我本地组件库的antd版本是4.16.13

**Comment by LeoYuan** [comment]
低代码物料描述是对已有 ProCode 的描述，假如版本对不上，描述则不准确~

假设 1.x antd Button 提供了 size 属性，2.x 不再提供，那么低代码描述中的 size 描述属性将不再对 2.x 有效~

**Comment by ajieying** [comment]
那我能修改这个基础的antd版本吗？
