### ISSUE TITLE
不部署到npm怎么扩展组件

### ISSUE THREAD

**Issue by SunTaiBai** [alibaba/lowcode-engine#1701]
不部署到npm怎么扩展组件

无网络环境下，想把资源导入进开发机自己搞物料，如何扩展组件呢，不想npm那种方式

**Comment by SunTaiBai** [comment]
可怜可怜孩子吧，领导让搞这低代码，我们开发还没有网，只能一次性导入资源干活，有没有啥方法可以不npm p扩展组件啊

**Comment by JackLian** [comment]
目前官方没有可行的方案建议

**Comment by guohejun** [comment]
> 目前官方没有可行的方案建议

@JackLian 我现在搞的自定义物料没有部署到npm，目前可以在demo中拖拽使用。但是点击出码后，自定义物料会以npm包的形式在package.json中引入。请问这个有办法解决吗？我们公司不给部署npm...

**Comment by JackLian** [comment]
> > 目前官方没有可行的方案建议
> 
> @JackLian 不知道你们说的是我这种情况吗？ 我现在搞的自定义物料没有部署到npm，目前可以在demo中拖拽使用。但是点击出码后，自定义物料会以npm包的形式在package.json中引入。请问这个有办法解决吗？我们公司不给部署npm...

定制出码的逻辑吧，出码本身就是一个定制的过程，将npm包形式引入的逻辑改成你们自己的逻辑

**Comment by guohejun** [comment]
@JackLian 好的，感谢，我找下怎么定制出码逻辑的，感觉这块还挺复杂的，这个有参考的案例吗，不会是参考demo的ice出码方案吧

**Comment by JackLian** [comment]
> @JackLian 好的，感谢，我找下怎么定制出码逻辑的，感觉这块还挺复杂的，这个有参考的案例吗，不会是参考demo的ice出码方案吧

是的，参考那个

**Comment by guohejun** [comment]
> > @JackLian 好的，感谢，我找下怎么定制出码逻辑的，感觉这块还挺复杂的，这个有参考的案例吗，不会是参考demo的ice出码方案吧
> 
> 是的，参考那个
好吧，谢谢~
