### ISSUE TITLE
如何实现SPA应用

### ISSUE THREAD

**Issue by Yan1** [alibaba/lowcode-engine#1702]
## **如何实现SPA应用**

官方案例中使用的是多入口，index.html为编辑器，preview.html 为预览页面
如何实现SPA，使得预览时，通过不同的path，渲染不同的页面

---

**可使用官方的案例demo-basic-demo**

**Comment by JackLian** [comment]
目前没有这样的应用demo，以目前的设计理念来说，官方也不打算提供这个使用方式
