### ISSUE TITLE
请问lowcode-engine和阿里之前开源的designable有什么差异，内部赛马？

### ISSUE THREAD

**Issue by KevinylZhao** [alibaba/lowcode-engine#1706]
想了解下两者的能力上的差异，阿里内部维护的团队是否有交流，两者后续的发展路线是否有重复，从场景看都是低代码编辑器，能力上也相近，有考虑合并吗

**Comment by JackLian** [comment]
是并行发展的两个项目，没啥直接关系，也没有合并的计划
