### ISSUE TITLE
配置StyleSetter属性时，想只展示文字的配置，却不生效

### ISSUE THREAD

**Issue by bingfenglengyan** [alibaba/lowcode-engine#1707]
## **Describe the bug (required)** / **详细描述 bug（必填）**
使用物料库项目
配置组件属性，使用了StyleSetter，配置了"showModuleList": ['font'],但是不生效
代码如下
![image](https://user-images.githubusercontent.com/35730201/224619459-16f4cac4-b379-4aea-8fcf-9a9431ce2ab5.png)
实际展示效果如下
![image](https://user-images.githubusercontent.com/35730201/224619567-f067c188-d77a-4902-8562-18faa1516202.png)

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by hzd822** [comment]
看下依赖的ext依赖的版本是多少

**Comment by bingfenglengyan** [comment]
> 看下依赖的ext依赖的版本是多少
这个是物料库的项目，直接用build-script生成的，没有直接按照这两个包，通过window变量，查看包的版本如下
AliLowCodeEngineExt:1.0.4
AliLowCodeEngine: 1.0.12

**Comment by beautiful-boyyy** [comment]
showModuleList要放在props里面

**Comment by bingfenglengyan** [comment]
> ![Screenshot 2023-03-15 at 11 28 16](https://user-images.githubusercontent.com/66351806/225198727-44a301b5-920b-4bbb-9cef-c6b1ed733a33.png)

这种写法也是不行的
![image](https://user-images.githubusercontent.com/35730201/225265559-12badd8b-64b6-4a78-b019-6680fa7c2519.png)
![image](https://user-images.githubusercontent.com/35730201/225265649-279f1319-783a-49d3-bfed-ddba090af036.png)

**Comment by bingfenglengyan** [comment]
已经找到原因了 是@alifd/build-plugin-lowcode这个npm包和github的代码不一致，已经在交流群里和金蝉大佬确认了

**Comment by xiaoshan100** [comment]
所以@alilc/lowcode-engine应该用哪个版本的

> 已经找到原因了 是@alifd/build-plugin-lowcode这个npm包和github的代码不一致，已经在交流群里和金蝉大佬确认了
