### ISSUE TITLE
能否提供动态修改schema的api

### ISSUE THREAD

**Issue by ChiZng** [alibaba/lowcode-engine#1709]
需求背景：拖入组件的时候想通过程序修改容器schema中的methods和state，不用在拖入组件后在源码面板中手写state和methods。现在只能先project.exportSchema()修改了之后再importSchema()。但是这样会导致页面重新加载。能不能提供一些api来修改这个结构描述，并且不让页面来重新加载。 现在修改了源码面板，页面也会重新加载导致失去选中的组件。

或者能不能提供一些实现的思路。

**Comment by ChiZng** [comment]
主要是修改rootSchema中ContainerSchema的属性。例如state，methods，css等

**Comment by ChiZng** [comment]
@liujuping 我看现在Node对象中extras使用props处理的，没有保存状态。能不想像project对象中`set(key:|'version' | 'componentsTree' | 'componentsMap'...)` 这个方法这样将Root Container Extra Properties的值保存到node中然后开放出来修改api。这么做有什么问题吗，修改的时候需要注意什么？

**Comment by LeoYuan** [comment]
参考这个？https://github.com/alibaba/lowcode-engine/issues/1712#issuecomment-1467264368

**Comment by ChiZng** [comment]
热心群众那个方法可以:+1:
