### ISSUE TITLE
使用umijs切换路由导致 Unhandled Rejection (Error): Plugin with name PluginManual exists

### ISSUE THREAD

**Issue by baieceo** [alibaba/lowcode-engine#171]
## **Describe the bug (required)** / **详细描述 bug（必填）**

使用umijs，demo中的registerPlugins方式注册插件，从引擎所在页跳转至别的页面，再切回来会报插件名已存在问题

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
1. 打开引擎页
2. 切换至其它页
3. 再切换至引擎页
---

```
/* eslint-disable react-hooks/exhaustive-deps */
import React, { useState, useEffect } from 'react';
import { init, common, plugins, config, project, skeleton } from '@alilc/lowcode-engine';

import '../universal/global.less';
import registerPlugins from './universal/plugin';

const preference = new Map();

preference.set('DataSourcePane', {
  importPlugins: [],
  dataSourceTypes: [
    {
      type: 'fetch',
    },
    {
      type: 'jsonp',
    },
  ],
});

function FormDesigner() {
  /** 插件是否已初始化成功，因为必须要等插件初始化后才能渲染 Workbench */
  const [hasPluginInited, setHasPluginInited] = useState(false);

  async function main() {
    config.setConfig({
      // designMode: 'live',
      // locale: 'zh-CN',
      enableCondition: true,
      enableCanvasLock: true,
      // 默认绑定变量
      supportVariableGlobally: true,
      // simulatorUrl 在当 engine-core.js 同一个父路径下时是不需要配置的！！！
      // 这里因为用的是 alifd cdn，在不同 npm 包，engine-core.js 和 react-simulator-renderer.js 是不同路径
      simulatorUrl: [
        'https://alifd.alicdn.com/npm/@alilc/lowcode-react-simulator-renderer@latest/dist/css/react-simulator-renderer.css',
        'https://alifd.alicdn.com/npm/@alilc/lowcode-react-simulator-renderer@latest/dist/js/react-simulator-renderer.js',
      ],
    });

    await registerPlugins();  // 注册插件
    await plugins.init(preference);

    setHasPluginInited(true);
  }

  useEffect(() => {
    main();
  }, []);

  return (
    <div style={{ margin: -24 }}>
      {hasPluginInited && <common.skeletonCabin.Workbench skeleton={skeleton} />}
    </div>
  );
}

export default FormDesigner;
```

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
切换回来不报错

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
![image](https://user-images.githubusercontent.com/19337357/159641223-8c15a33c-e444-47b9-a19c-d9844244a303.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. beta] / https://unpkg.com/@alilc/lowcode-engine@beta/dist/js/engine-core.js
 - AliLowCodeEngineExt version: [e.g. beta] / https://unpkg.com/@alilc/lowcode-engine-ext@beta/dist/js/engine-ext.js
 - Browser [e.g. chrome, safari] / 版本 98.0.4758.102（正式版本） （64 位）
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

**Comment by LeoYuan** [comment]
说明多次执行了 init，可以自己设置个标志位处理一下就好了~

**Comment by sy296565890** [comment]
> 说明多次执行了 init，可以自己设置个标志位处理一下就好了~

init之后再次进入就不能init了，在切换路由后应该如何操作呢，还请大佬指点一二，

**Comment by xiechong** [comment]
> 说明多次执行了 init，可以自己设置个标志位处理一下就好了~

用plugins.has()方法检测插件注册后，就不执行init方法，或者在plugins.register()时配置options: { override: true }，虽然不报Plugin with name xx exists了， 但是两种方法都无法解决路由跳转，返回时页面不加载的问题，这个问题有解吗
