### ISSUE TITLE
ReactRenderer的appHelper，能否自定义方法或者变量到上下文this

### ISSUE THREAD

**Issue by 1377023219** [alibaba/lowcode-engine#1712]
## **Describe the bug (required)** / **详细描述 bug（必填）**

ReactRenderer的appHelper，能否自定义方法或者变量到上下文this

---

## **Screenshots (optional)** / **截图（可选）**

![image](https://user-images.githubusercontent.com/36667646/224657784-444a34b6-edcb-4b37-94ca-2394cce608a8.png)
![image](https://user-images.githubusercontent.com/36667646/224657970-5575bc79-c289-4421-8d41-14cb94c2a8e8.png)

---

**Comment by JackLian** [comment]
你直接试试咯

**Comment by 1377023219** [comment]
> 你直接试试咯

就是好像是不支持的，现在有什么方法实现吗？

**Comment by 1377023219** [comment]
@JackLian 就是好像是不支持的，现在有什么方法实现吗？

**Comment by 1377023219** [comment]
@liujuping 请问有什么方法实现吗？

**Comment by LeoYuan** [comment]
变量在协议的state字段定义，通过this.state获取，appHelper定义的在this.utils字段，不是吗？

**Comment by 1377023219** [comment]
@LeoYuan 对啊，但是想实现this.xxx。现在在appHelper实现的是this.utils.xxx，隔了一层utils

**Comment by LeoYuan** [comment]
那就挂到schema中的methods字段

**Comment by 1377023219** [comment]
> 那就挂到schema中的methods字段

那就是，目前没办法实现这个功能了。（挂methods，js面板一改又会重新生成methods）

**Comment by LeoYuan** [comment]
![image](https://user-images.githubusercontent.com/1195765/224879064-7ae5225f-4163-424c-b56c-c3b9fe23d36f.png)


小试了一下，貌似可以~（非权威解答，热心群众贡献）

**Comment by 1377023219** [comment]
> ![image](https://user-images.githubusercontent.com/1195765/224879064-7ae5225f-4163-424c-b56c-c3b9fe23d36f.png)
> 
> 小试了一下，貌似可以~（非权威解答，热心群众贡献）

![image](https://user-images.githubusercontent.com/36667646/224880521-715697ba-8650-403e-a1ca-a239487584a3.png)
![image](https://user-images.githubusercontent.com/36667646/224880723-71a2b09a-58ce-4159-8826-5a65681ccec3.png)

**Comment by LeoYuan** [comment]
那就是这个面板不支持从协议中读取新的变更，面板回写也是直接覆盖原协议内容，建议fork该面板插件自己改
