### ISSUE TITLE
保存schema报错 open undefined

### ISSUE THREAD

**Issue by vjzning** [alibaba/lowcode-engine#1715]
打开schema，直接保存没有做任何修改，
<img width="948" alt="image" src="https://user-images.githubusercontent.com/5629031/224923858-6f026762-5893-44ca-bc7a-3440bd51ff26.png">
 
<img width="806" alt="image" src="https://user-images.githubusercontent.com/5629031/224923942-78207e1a-28b5-4ff9-8484-8cdc8f9feab9.png">

- AliLowCodeEngine version: [e.g. 1.1.3] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.5] / 低代码引擎扩展包版本

**Comment by beautiful-boyyy** [comment]
我这边是正常的
