### ISSUE TITLE
设置器异常，全部都开启变量绑定，supportVariable无效

### ISSUE THREAD

**Issue by 1377023219** [alibaba/lowcode-engine#1730]
## **Describe the bug (required)** / **详细描述 bug（必填）**

设置器异常，全部都开启变量绑定，supportVariable无效
---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

这是官网DEMO的综合场景，还有antd场景，里面看了很多组件，全部属性都是开启变量绑定的
![image](https://user-images.githubusercontent.com/36667646/225491307-181b957a-3f4d-4699-9e48-cb26d5f03dd3.png)

这是我本地的代码，关掉了supportVariable，但是依旧还是开启变量绑定
![image](https://user-images.githubusercontent.com/36667646/225491676-a4423631-9129-4bf4-b95c-9786dfead04e.png)
![image](https://user-images.githubusercontent.com/36667646/225491730-3b994d31-8847-468c-b44f-c8831d77e235.png)

**Comment by 1377023219** [comment]
刚刚把库升级到最新也一样
![image](https://user-images.githubusercontent.com/36667646/225492502-dd7d4430-84b9-4f67-8fb5-31a7e89516e4.png)

**Comment by beautiful-boyyy** [comment]
![Screenshot 2023-03-16 at 10 54 46](https://user-images.githubusercontent.com/66351806/225498445-5058ea45-7895-4d0e-9cff-a293d85ff6ac.png)

demo里面index.ts配的

**Comment by 1377023219** [comment]
> ![Screenshot 2023-03-16 at 10 54 46](https://user-images.githubusercontent.com/66351806/225498445-5058ea45-7895-4d0e-9cff-a293d85ff6ac.png)
> 
> demo里面index.ts配的

谢谢了，以前的老版本好像没默认开启，以为是新版出BUG了
