### ISSUE TITLE
低码组件资产的实现与协议规范中约定的不一致

### ISSUE THREAD

**Issue by Carrotzpc** [alibaba/lowcode-engine#1735]
## **官方低码组件 demo 里低码组件资产的 schema 结构跟协议里约定的不一致**

![4f9625118a85cae58763ae31a7fbfd16](https://user-images.githubusercontent.com/10265417/225557389-5523a545-6775-4af6-838a-5c1dc3aa6836.png)
![85d07f13e8385cdd8d3ba557c953360e](https://user-images.githubusercontent.com/10265417/225557418-88a76d7a-22af-425a-9f28-ca0ddb3de64c.png)
![275c4039c4fa9251bcd84946ff910e8e](https://user-images.githubusercontent.com/10265417/225557435-61507c23-3063-472a-a3d3-dd3342680b09.png)

我按照协议里约定的格式添加低码组件资产不成功，必须按照 demo 中的格式才可以。如果按照 demo 中的格式，低码组件的 utils、constants、i18n 这些都是得拖拽添加低码组件后手动处理吗？

---

## 看官方 demo 及协议规范即可

- demo: https://github.com/alibaba/lowcode-demo/blob/2db4b6ee3f/demo-lowcode-component/src/services/assets.json#L319
- 协议：https://lowcode-engine.cn/site/docs/specs/assets-spec#22-packages-a

## 预期行为

期望低码组件资产的实现与协议规范中约定一致，这样更利于低码资产的 utils、constants、i18n 的处理

---

## 环境信息
 - AliLowCodeEngine version: v1.1.2 / 低代码引擎版本
 - AliLowCodeEngineExt version: v1.0.5 / 低代码引擎扩展包版本
 - Browser : chrome

**Comment by eternalsky** [comment]
我们 review 了一下，这里引擎和资产包的实现确实有点问题，我们最近会做这个地方的修改，和协议对齐。

**Comment by Carrotzpc** [comment]
用最新的 beta 版本尝试了下，目前已经可以支持完整的 ComponentSchema 了👍，不过有个小问题：

![image](https://user-images.githubusercontent.com/10265417/229010301-de39c400-3eef-4631-99f2-008d1cc36d77.png)

当引入的低码组件 schema 是一个完整的 ComponentSchema 时，将低码组件拖拽到画布中后，低码组件外层会包裹一个 div，导致低码组件会一直是一个块级元素

**Comment by eternalsky** [comment]
组件最外层是会有个容器的，但是可以通过配置样式设置器来改变这层的样式。

**Comment by Carrotzpc** [comment]
这个容器的默认样式能改吗？用样式设置器的话设置的是组件的样式，应该影响不了外层容易的@eternalsky ：
![image](https://user-images.githubusercontent.com/10265417/229042784-1bac8743-ab4a-48c1-8bc9-1c7b8c779ccb.png)

**Comment by liujuping** [comment]
这里可能是因为没有 Component 这个组件，如果有 Component 这个组件，就没有 div 这一层了，可以试一下。

**Comment by Carrotzpc** [comment]
资产里面引入了，还需要在哪里配置吗？
![image](https://user-images.githubusercontent.com/10265417/229046674-24c3d113-9811-4040-a1ac-ff7d4a1a367d.png)

**Comment by Carrotzpc** [comment]
问题是这一层不是 Component 渲染出来的，感觉是画布本身的逻辑@eternalsky：
![image](https://user-images.githubusercontent.com/10265417/229048103-6d1d9aa4-2c65-498a-bc98-7e88fcfd8c31.png)

**Comment by Carrotzpc** [comment]
应该是是我自定义了 lowcode-react-simulator-renderer 导致的，换成官方的可以了，感谢回复 @eternalsky @liujuping
