### ISSUE TITLE
是否可以生成 Vue 页面代码？有没有详细一点的啊

### ISSUE THREAD

**Issue by ganziqiang** [alibaba/lowcode-engine#1738]
文档写出这些，不知从哪下手。
![image](https://user-images.githubusercontent.com/39983456/225575525-616fb497-5797-4587-8d81-282b3a175309.png)
![1678959329036](https://user-images.githubusercontent.com/39983456/225575623-99209679-da53-442e-95fb-81ace0e0cb43.png)

**Comment by jiangtao** [comment]
自己撸 或 静待其他团队开源

**Comment by LeoYuan** [comment]
基于出码引擎写 solution 的基本思路是：

1. 根据出码的目标应用结构，该分成几个模块，这样就可以确定 template 怎么写；（这些术语建议直接在源码中搜）
2. 确定 template 后，再确定要分成多少个 module/slot；
3. 每个 module/slot 上可以挂载多个插件，每个插件基本都是处理文件级别的代码（chunk）生成和拼装；

除此之外，出码引擎还定义了项目级 AOP 切面、module 级 AOP 切面~

按照以上思路，再去读读内置的 icejs / rax solution 的源码，很容易就理解了的~

>  generated by ChatGPT 🎉
