### ISSUE TITLE
数据源 dataSourceItem.load 未更新状态

### ISSUE THREAD

**Issue by sundi78634** [alibaba/lowcode-engine#174]
## **Describe the bug (required)** / **详细描述 bug（必填）**

RT. 数据源item load()方法触发请求成功后，没有把最新数据setState。导致this.state.[dataSourceItemId]未更新，绑定该数据源的组件也无法拿到最新数据。

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1. 打开 [demo](https://alifd.alicdn.com/npm/@alilc/lowcode-demo@1.0.7/build/index.html)。
2. 创建一个fetch数据源list，能够根据不同参数返回不同结果。
3. 添加一个查询筛选组件，文本组件；文本组件展示内容绑定数据源list。
4. 查询筛选绑定onSearch事件，onSearch事件中触发数据源load方法 `this.dataSourceMap.list.load(params);`。
5. 预览。
6. 预览页面中，生命周期中的`reloadDataSource` 请求数据源后能够更新文本组件的展示内容。查询筛选组件查询后，network中能看到请求到了新的数据，但是文本组件内容未更新。

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

数据源item load方法能够更新数据。

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
- 引擎版本 1.0.3-beta.0
- ext 版本 1.0.3
- 物料
  - moment﹫2.24.0
  - lodash
  - ﹫alifd/next﹫1.24.18
  - NextTable﹫1.0.1
  - ﹫alilc/lowcode-materials﹫1.0.1
  - ﹫alifd/pro-layout﹫1.0.1-beta.5
  - ﹫alifd/fusion-ui﹫1.0.5-beta.1

**Comment by LeoYuan** [comment]
load 并不会去刷数据，调用 setState 了么？

**Comment by sundi78634** [comment]
没有调用setState。是要在load 返回的Promise中拿到数据，再手动setState更新吗？
有没有什么方法能触发数据源Item重新发送请求，自动刷新绑定该数据源的组件？

**Comment by LeoYuan** [comment]
没有~目前只有修改了 state 才会刷新视图
