### ISSUE TITLE
编辑器只提供init初始引擎后，能否提供销毁的方法

### ISSUE THREAD

**Issue by 286yym** [alibaba/lowcode-engine#175]
import { init } from @alilc/lowcode-engine
场景: 根据官方dome去初始化引擎，init方法一旦初始化后，路由跳转后无法重新初始化（init），看dome是将init初始化的引擎数据是全局共用的（不能根据不同路由生成不同的设计器），导致路由跳转无法打开多个设计器，或者重新打开已经初始化过的设计器也做不到
需求：可以提供重新打开设计器的方法，或者提供将之前init初始的实例，进行销毁的方法，可以重新进行init也行，谢谢

**Comment by baieceo** [comment]
不能销毁引擎，注册过的插件也会导致不能销毁，切换回来会导致重复注册问题

**Comment by LiuLingyang** [comment]
遇到同样的问题，init 引擎后，切换路由，再切换回来，设计器无法再次打开；
插件注册会提示重复；
跳过插件注册，重新 init 或者 openDocument 等方法都不生效；
请问该如何处理这种情况？

**Comment by baieceo** [comment]
> 遇到同样的问题，init 引擎后，切换路由，再切换回来，设计器无法再次打开； 插件注册会提示重复； 跳过插件注册，重新 init 或者 openDocument 等方法都不生效； 请问该如何处理这种情况？

官方小哥让设置个标志，但是不管用，准备先用window.reload()刷新页面处理

**Comment by liujuping** [comment]
Duplicate of https://github.com/alibaba/lowcode-engine/issues/178

**Comment by xiyuanwang** [comment]
> > 遇到同样的问题，init 引擎后，切换路由，再切换回来，设计器无法再次打开； 插件注册会提示重复； 跳过插件注册，重新 init 或者 openDocument 等方法都不生效； 请问该如何处理这种情况？
> 
> 官方小哥让设置个标志，但是不管用，准备先用window.reload()刷新页面处理



> > 遇到同样的问题，init 引擎后，切换路由，再切换回来，设计器无法再次打开； 插件注册会提示重复； 跳过插件注册，重新 init 或者 openDocument 等方法都不生效； 请问该如何处理这种情况？
> 
> 官方小哥让设置个标志，但是不管用，准备先用window.reload()刷新页面处理

我也遇到这个问题，切换路由时，各种清理缓存，删除插件，删除document，各种清除后再切回来，设计器加载后，组件拖拽到画布后松开没有反应。能有一个清除方法就好了。
