### ISSUE TITLE
ObjectSetter的子属性使用extraProps.setValue后，修改时不触发上层的setValue

### ISSUE THREAD

**Issue by Momic9** [alibaba/lowcode-engine#1756]
## **Describe the bug (required)** / **详细描述 bug（必填）**

内部物料，使用了ArraySetter嵌套ObjectSetter的配置方式，ArraySetter对应字段items 与 ObjectSetter的props下的对应字段prop 都使用了extraProps.setValue

实际操作中发现在展开的编辑器中对prop进行设置时 不会触发items的setValue，但是在列表中进行配置就能触发(prop设置了isRequire=true)

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

在展开的面板中编辑label和prop时，label能触发items的setValue，但是prop不行
属性代码demo：
```javascript
{
    "name": "items",
    "title": {
        "label": "表单项",
    },
    display: 'accordion',
    virtual: true,
    extraProps: {
        getValue: itemsGetValue,
        setValue: itemsSetValue,
    },
    "setter": {
        "componentName": "ArraySetter",
        "props": {
            "itemSetter": {
                "componentName": "ObjectSetter",
                "props": {
                    "config": {
                        items: [
                            {
                               "name": "label",
                               "setter": "StringSetter",
                               "isRequired": true,
                               defaultValue: '标题',
                            },
                            {
                               "name": "prop",
                               "setter": "StringSetter",
                               "isRequired": true,
                               defaultValue: '',
                               extraProps: {
                                  setValue: (target: any, value: any) => {}
                               }
                            }
                        ]
                    },
                },
            }
        }
    }
}
```

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

在展开的编辑器编辑时能触发外层的setValue

---

## **Screenshots (optional)** / **bug 截图（可选）**

![image](https://user-images.githubusercontent.com/48303646/226303244-993fdf13-e7f4-43ad-88b2-276dd54cd057.png)
右侧没问题，左侧无法触发

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本：lowcode-engine@1.0.14
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本：lowcode-engine-ext@1.0.6-beta.8（beta.17也试过，有相同的问题）
 - Browser [e.g. chrome, safari] / 浏览器版本：chrome
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by liujuping** [comment]
可以看看这个 issue 

https://github.com/alibaba/lowcode-engine/issues/1721
