### ISSUE TITLE
官方demo中的Text组件，如何将&nbsp;渲染成空格，而不是普通字符串？

### ISSUE THREAD

**Issue by guohejun** [alibaba/lowcode-engine#1759]
`官方demo中的Text组件，如何将&nbsp;渲染成空格，而不是普通字符串？`

**Comment by guohejun** [comment]
@LeoYuan 大佬，求助下哈[抱拳]

**Comment by LeoYuan** [comment]
直接用空格字符` `或者写个utils处理字符实体 `&xxx;` ？

**Comment by guohejun** [comment]
应该是Text组件会trim掉首尾的空格空白字符吧
![image](https://user-images.githubusercontent.com/27323522/226509132-073a7ec9-e45c-4fa7-854c-13168b4cde55.png)
![image](https://user-images.githubusercontent.com/27323522/226509215-3ea75b43-6981-4eb5-a0c0-39258b33f3f4.png)

**Comment by LeoYuan** [comment]
那就是物料 by design 了，你可以自己去写个符合你要求的 Text 组件~

**Comment by guohejun** [comment]
聚焦时，能看到里面是有空格的，失焦就没了。
如果utils处理成`&nbsp;`，它会直接渲染出字符`&nbsp;`而不是空格。

**Comment by guohejun** [comment]
OK，那我自己写个吧，谢谢[抱拳]

**Comment by guohejun** [comment]
@LeoYuan 大佬，我拖拽任何一个组件到画布，它都会产生一个[区域]-[区块]等好几个层级元素，这个有配置可以去掉嘛？
![image](https://user-images.githubusercontent.com/27323522/226538701-2e88f2cb-4f5c-4b63-ad84-a87e2e96d30d.png)

**Comment by LeoYuan** [comment]
物料中把 pro-layout 的去掉~

**Comment by guohejun** [comment]
> 物料中把 pro-layout 的去掉~
谢谢[抱拳]
对应问题：拖拽任意一个组件到画布中，总是会多出来几个层级元素：
![image](https://user-images.githubusercontent.com/27323522/226540248-db280258-0130-4a93-817b-9d21847ff4b9.png)
