### ISSUE TITLE
在对物料进行扩展的时候，无法启动 lowcode 环境进行调试预览

### ISSUE THREAD

**Issue by PearpearS** [alibaba/lowcode-engine#176]
重现步骤
1 npm init @alilc/element threeD-comps
2 cd threeD-comps
3 npm install
(以上步骤正常)
4. npm run lowcode:dev 报错
![image](https://user-images.githubusercontent.com/25281421/159670887-51fe59ae-b708-41e5-bee2-b94e56066892.png)

**Comment by lijiaxu1996** [comment]
推荐使用wsl、其实也就是你得使用linux/mac等有shell命令编辑器开发~

**Comment by PearpearS** [comment]
> 推荐使用wsl、其实也就是你得使用linux/mac等有shell命令编辑器开发~

还真是这样，换成mac就好了，这是啥情况啊

**Comment by liujuping** [comment]
官网有相关说明

**Comment by CL008** [comment]
> 

有什么方法可以在windows 运行
