### ISSUE TITLE
@alilc/lowcode-types 之前用的1.0.6，升级后1.1.3后很多ts的声明都没了

### ISSUE THREAD

**Issue by wssgchungang** [alibaba/lowcode-engine#1766]
## **Describe the bug (required)** / **详细描述 bug（必填）**

@alilc/lowcode-types 之前用的1.0.6，昨天用脚手架@alilc/element重新初始化了一个项目，@alilc/lowcode-types版本变成了1.1.3后很多ts的声明都没了

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

![image](https://user-images.githubusercontent.com/29122164/226786987-31d122c7-5883-4dbc-912e-5b3b3de9e2ea.png)
![image](https://user-images.githubusercontent.com/29122164/226787266-c1194672-346b-41cb-b3ee-802b12d299cc.png)
这些ts的类型都没导出了

还有个怎么页面头部怎么风格也变了，能切回以前的白色头部吗
![image](https://user-images.githubusercontent.com/29122164/226787573-4a87169f-5931-4377-915a-24000272e4a2.png)

**Comment by JackLian** [comment]
1.1 类型系统做了大升级，你可以看一下源码，类型基本就是加了前缀

**Comment by wssgchungang** [comment]
> 1.1 类型系统做了大升级，你可以看一下源码，类型基本就是加了前缀

好像改动有点大，有些类型结构都变了 比如
ComponentMetadata中的configure 之前是
![image](https://user-images.githubusercontent.com/29122164/226796144-fa1ad39c-18e7-4191-a92e-3b66ac0baabf.png)
现在
![image](https://user-images.githubusercontent.com/29122164/226796178-8edc861d-557a-473a-a56f-8023025a4f5f.png)
少了Configure这个类型 新的在物料协议规范里也没有体现，还是老的

**Comment by JackLian** [comment]
是的，变化很大，升级时候可以综合考虑下成本
