### ISSUE TITLE
设置 supportVariable: false 后属性面板仍然显示变量绑定操作按钮

### ISSUE THREAD

**Issue by mirages** [alibaba/lowcode-engine#177]
## **Describe the bug (required)** / **详细描述 bug（必填）**

调用 `material.registerMetadataTransducer` 方法修改官方资产包中某个组件配置属性的 supportVariable 设置成 `supportVariable: false`，该属性后面仍然显示 `{ / }` 变量绑定操作按钮。

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1. 运行 lowcode-demo 项目
2. 在 `src/universal/plugin.tsx` 中调用 `material.registerMetadataTransducer` 方法修改某个属性配置项，并注册自定义 setter
```js
// import ....

material.registerMetadataTransducer((data) => {
  if (data.group === '原子组件' && data.category === '信息输入' && data.componentName === 'DatePicker') {
    console.log('replaceDateSetter', data)
    if (data.configure.props) {
      const props = Array.isArray(data.configure.props) ? data.configure.props : (data.configure.props as any).override || []
      const defaultValProp = props.find((item:any) => item.name === 'defaultValue')

      defaultValProp.setter = 'AltStringSetter'
      defaultValProp.supportVariable = false
    }
  }

  return data
}, 1000, 'replaceDateSetter')

export default async function registerPlugins() {
  // ...
  const customSetter = (ctx: ILowCodePluginContext) => {
    return {
      name: '___registerCustomSetter___',
      async init() {
        const { setters } = ctx;

        setters.registerSetter('TitleSetter', TitleSetter);
        setters.registerSetter('BehaviorSetter', BehaviorSetter);
        setters.registerSetter('CustomSetter', CustomSetter);
        setters.registerSetter('AltStringSetter', AltStringSetter);
      },
    };
  }
  customSetter.pluginName = 'customSetter';
  await plugins.register(customSetter);
}
```
3. 拖入**组件库--->原子组件--->信息输入--->日期选择框**到编辑器中
4. 查看该组件的属性配置面板，看到“默认值”对应的 setter 已经替换成自定义 setter 了，但是后边仍然有 `{ / }` 变量绑定操作按钮

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
设置属性配置 `supportVariable: false` 后不展示 `{ / }` 变量绑定操作按钮

---

## **Screenshots (optional)** / **bug 截图（可选）**
<img width="1303" alt="iShot2022-03-23 20 03 03" src="https://user-images.githubusercontent.com/12791299/159695184-b712442d-5d86-4da1-87dc-18259129946a.png">

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: 1.0.1
 - AliLowCodeEngineExt version: 1.0.2
 - Browser chrome

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
查看源码[https://github.com/alibaba/lowcode-engine/blob/main/packages/editor-skeleton/src/components/settings/settings-pane.tsx#L114](https://github.com/alibaba/lowcode-engine/blob/main/packages/editor-skeleton/src/components/settings/settings-pane.tsx#L114)，因为 init() 方法设置了 `supportVariableGlobally: true` 导致该段逻辑始终会自动添加一个 `VariableSetter`

**Comment by mirages** [comment]
目前还没有找到解决方法，希望设置 `supportVariableGlobally: true` 后可以设置属性配置的 `supportVariable: false` 单独控制是否需要变量绑定

**Comment by yz1311** [comment]
是的，现在我想关闭几个特殊的都不得行

**Comment by oneQiu** [comment]
+1

**Comment by JackLian** [comment]
@hzd822 帮忙鉴定下

**Comment by lmm1990** [comment]
遇到了同样的问题
