### ISSUE TITLE
调用config.set(key, value)这个值持久化到了哪里？

### ISSUE THREAD

**Issue by ChiZng** [alibaba/lowcode-engine#1771]
## 问题描述：
调用config.set(key, value)这个api后然后，使用官方demo中的`保存到本地`插件。然后发现localStorage中的projectSchema下没有config字段。
## 预想的结果：
调用config.set(key, value)这个api后然后，使用官方demo中的`保存到本地`插件。应该能在localStorage中的projectSchema下找到该信息。看ProjectSchema中有config属性。
## 复现过程：
1.  使用官方demo，demo-basic-antd 在初始化插件最后加上`config.set("keyA", 'hello word');` 控制台有刚才设置的打印
    ![image](https://user-images.githubusercontent.com/27946984/226915702-3e81ac88-5816-460e-9dfe-4ddc990e69b0.png)
![image](https://user-images.githubusercontent.com/27946984/226916451-76d83ae8-a6b2-46b2-a8b2-17078ed9f50d.png)

3. 点击浏览器右上角的`保存到本地`插件
4. 查看schema，发现没有自己设置的这个config
    
![image](https://user-images.githubusercontent.com/27946984/226915474-89b186d2-a7b6-46ab-871a-fb0c310c8035.png)

**Comment by liujuping** [comment]
这个 config 的值并没有持久化。schema 里面的 config 和这里的 config 的概念不一样。

需要持久化可以自己对 config 进行存储。

**Comment by ChiZng** [comment]
@liujuping 知道了，感谢。之后版本会暴漏出修改schema里这个config的api吗

**Comment by liujuping** [comment]
已经有人贡献 PR 了，待文档更新后，下一个正式版本会带上这个 api。

https://github.com/alibaba/lowcode-engine/pull/1742
