### ISSUE TITLE
fusion的nextTable组件在编辑数据列时组件报错

### ISSUE THREAD

**Issue by RichadoM** [alibaba/lowcode-engine#1773]
demo github项目中的fusion组件项目，拖入nextTable组件后，点击数据列的第一项后组件会直接报错

![image](https://user-images.githubusercontent.com/56419029/227115891-492694e0-34e3-42c8-8252-4152f385809d.png)
![image](https://user-images.githubusercontent.com/56419029/227115946-306a7b69-cc98-4b87-86b3-9bcc8a771423.png)
![image](https://user-images.githubusercontent.com/56419029/227116009-a791225f-d8bb-44cb-b8f6-aa9d0d57dc8c.png)
![image](https://user-images.githubusercontent.com/56419029/227116065-d3c40bd1-6959-4131-93cc-3c2d038fa359.png)

复现步骤：
1. 拖入nextTable组件
2. 选中nextTable组件
3. 点击数据列的第一项的编辑按钮

**Comment by JackLian** [comment]
https://github.com/alibaba/lowcode-engine/releases
版本信息可以这里看
