### ISSUE TITLE
官方formily的在线demo报错，另外预览时arraytable功能不正常，以及该页面也有127.0.0.1d请求

### ISSUE THREAD

**Issue by rongrongt** [alibaba/lowcode-engine#1778]
![image](https://user-images.githubusercontent.com/21823510/227440685-66a46f7f-5f3c-4c68-b7d6-f642b9515268.png)
![image](https://user-images.githubusercontent.com/21823510/227441456-ff60d3b4-b3d5-445b-8c81-3a2e9b62e8f0.png)

复现步骤，官方demo，拖入formilyform，再拖入array-table到from里，再拖入iinput到table里

**Comment by liujuping** [comment]
可以到这里提问哈。

https://github.com/seada-low-code/lowcode-ecology/tree/main/packages/formily-materials
