### ISSUE TITLE
获取外部数据是否支持通过自定义sql查库？后期是否有做这个功能的计划？

### ISSUE THREAD

**Issue by mexhfl** [alibaba/lowcode-engine#1781]
类似于illa或者appsmith，可以连接到数据库，做一些自定义查询，然后引用数据

**Comment by JackLian** [comment]
本项目的定位不会提供类似的能力

**Comment by mexhfl** [comment]
> 本项目的定位不会提供类似的能力

本项目的定位主要是解决前端低代码研发的问题对吗？

**Comment by JackLian** [comment]
参考这个说明https://lowcode-engine.cn/site/docs/guide/quickStart/intro
