### ISSUE TITLE
build-plugin-lowcode 是否能支持lowcode:build打包时的参数 UNPKG_BASE_URL 可配置

### ISSUE THREAD

**Issue by wssgchungang** [alibaba/lowcode-engine#1788]
build-plugin-lowcode 的lowcode:build打包后的unpkg域名看源码是固定的，得要发布到内网，是否可支持配置UNPKG_BASE_URL

**Comment by eternalsky** [comment]
run lowcode:build 之后真正有用的是构建出的 view.js 和 meta.js，unpkg 只是一种简便的拿 npm 包里的文件内容的方式罢了，如果你想要使用内网源，只要这个包同步到你说的内网，或者这个包直接发布到内网，然后通过内部的 unpkg 去那就好了

**Comment by wssgchungang** [comment]
> run lowcode:build 之后真正有用的是构建出的 view.js 和 meta.js，unpkg 只是一种简便的拿 npm 包里的文件内容的方式罢了，如果你想要使用内网源，只要这个包同步到你说的内网，或者这个包直接发布到内网，然后通过内部的 unpkg 去那就好了

我只是想省略每次打包后还得手动去改下资产包的域名，所以只是建议能否加个配置省略这一步

**Comment by eternalsky** [comment]
> 

构建出的 assets.json 只是为了快速做验证，真正在项目中使用的时候，一般 assets 都是要重新拼装起来的（通常不会只有一个包），因此感觉意义不大，当然如果需求很强，可以 pr 哈，给 build-plugin-lowcode 增加参数。

**Comment by jinchanz** [comment]
@wssgchungang 试试这个 [baseUrl](https://github.com/alibaba/lowcode-materials/blob/main/packages/fusion-lowcode-materials/build.lowcode.js#L42) 的配置，应该能满足你的需求
