### ISSUE TITLE
请问有考虑出vue版本的低码引擎吗

### ISSUE THREAD

**Issue by qiqilie** [alibaba/lowcode-engine#179]
希望能出一套支持vue3 + Ant Design Vue的的低代码引擎，目前只能出码react是吧？有考虑开发一套吗

**Comment by LeoYuan** [comment]
有外部共建的同学在弄，有消息会发公告哈。不一定基于ant design vue，大概率是基于自己团队的物料库😃

**Comment by liujuping** [comment]
Duplicate of https://github.com/alibaba/lowcode-engine/discussions/47

**Comment by keminu** [comment]
这个低代码引擎设计是否有问题？跟react强绑定
