### ISSUE TITLE
lowcodeengine 关于多人协同的问题

### ISSUE THREAD

**Issue by Cossey11111** [alibaba/lowcode-engine#1790]
在项目中遇到多人协同编辑同一个页面的问题。 请教下：
1. 看到https://juejin.cn/post/7179800384066551867 这篇文章中，有一个「可视化多分支协同」方案，请问这个部分计划开源吗？
3. 基于目前的引擎，有什么好的方案吗？

**Comment by JackLian** [comment]
目前还没有开源计划，整体上我们也在不断探索，大家可以借鉴文章中的思路
