### ISSUE TITLE
自定义物料库时引入element-react UI库  项目所有组件无法拖到画布，且未报任何错误

### ISSUE THREAD

**Issue by snowFlower110** [alibaba/lowcode-engine#1792]
![微信截图_20230327141216](https://user-images.githubusercontent.com/15030694/227855936-d37f14a1-53d9-44a5-8916-caaa5600b944.png)

![微信截图_20230327141523](https://user-images.githubusercontent.com/15030694/227856299-0e9ffe4e-ffd8-4099-acd7-4bc3a727b900.png)

**Comment by liujuping** [comment]
请按照文档提供快捷复现路径

https://lowcode-engine.cn/site/community/issue

**Comment by snowFlower110** [comment]
> 
![image](https://user-images.githubusercontent.com/15030694/227884344-85957f72-7cfd-4630-829d-abbf12a5b961.png)
步骤一：新开发组件库
步骤二：引入react-elementUI库
![image](https://user-images.githubusercontent.com/15030694/227885888-8e431afd-c706-4126-85ca-78b7ee505c74.png)

步骤三：引入react-element UI组件并导出
![image](https://user-images.githubusercontent.com/15030694/227886031-fc6134f9-9af1-4bfc-ab27-d9a39bb3d978.png)
步骤四：无法拖入组件到画布中，且控制台无报错
![image](https://user-images.githubusercontent.com/15030694/227886538-4b5b80e9-2674-405f-af40-5d9222e950ed.png)
![image](https://user-images.githubusercontent.com/15030694/227886708-70883313-2bac-4b4d-91e4-c287b2c3359b.png)

**Comment by eternalsky** [comment]
查看一下大纲树，确认一下是没拖进去，还是拖进去了，但是没有样式加上配置，导致没有显示

**Comment by snowFlower110** [comment]
> 

大纲树下是空的   而且只要引入这个ui库  所有组件就都拖入不进去了  大纲树下没任何东西

**Comment by eternalsky** [comment]
请提供可以复现的方式
