### ISSUE TITLE
物料的lowcode:build 和 build打出来的文件有什么区别

### ISSUE THREAD

**Issue by wendell0316** [alibaba/lowcode-engine#1793]
看了下现在assets文件里urls和editUrl 使用了不同的地址
<img width="940" alt="image" src="https://user-images.githubusercontent.com/20490844/227858572-988cdcee-0e93-4a17-9088-6721d5c6c466.png">
两个文件的构建过程有什么区别么？
layout的包我使用lowcode:build构建出来的js会报错，有大佬能解释下原因不

**Comment by eternalsky** [comment]
lowcode:build 是构建组件的低代码部分，主要是低代码的设计态、物料描述等。build 是构建组件作为源码组件的部分，和市面上其他react 组件脚手架的性质一致。在发包前，两个 build 都是要进行的。可以参见组件 npm scirpts 里的 prePublishOnly
