### ISSUE TITLE
项目打包时报错

### ISSUE THREAD

**Issue by Z-Champion** [alibaba/lowcode-engine#1795]
bug 描述
---
release/1.0.18版本执行npm run build打包时报错

详细复现步骤
---
1. npm i
2. npm run setup
3. npm run build 

预期的行为
---
打包成功

打包日志
---
> build
> ./scripts/build.sh
lerna notice cli v4.0.0
lerna notice filter including ["@alilc/lowcode-types","@alilc/lowcode-utils","@alilc/lowcode-shell","@alilc/lowcode-editor-core","@alilc/lowcode-editor-skeleton","@alilc/lowcode-designer","@alilc/lowcode-plugin-designer","@alilc/lowcode-plugin-outline-pane","@alilc/lowcode-rax-renderer","@alilc/lowcode-rax-simulator-renderer","@alilc/lowcode-react-renderer","@alilc/lowcode-react-simulator-renderer","@alilc/lowcode-renderer-core","@alilc/lowcode-engine"]
lerna info filter [
lerna info filter   '@alilc/lowcode-types',
lerna info filter   '@alilc/lowcode-utils',
lerna info filter   '@alilc/lowcode-shell',
lerna info filter   '@alilc/lowcode-editor-core',
lerna info filter   '@alilc/lowcode-editor-skeleton',
lerna info filter   '@alilc/lowcode-designer',
lerna info filter   '@alilc/lowcode-plugin-designer',
lerna info filter   '@alilc/lowcode-plugin-outline-pane',
lerna info filter   '@alilc/lowcode-rax-renderer',
lerna info filter   '@alilc/lowcode-rax-simulator-renderer',
lerna info filter   '@alilc/lowcode-react-renderer',
lerna info filter   '@alilc/lowcode-react-simulator-renderer',
lerna info filter   '@alilc/lowcode-renderer-core',
lerna info filter   '@alilc/lowcode-engine'
lerna info filter ]
lerna info Executing command in 14 packages: "yarn run build"
lerna WARN ECYCLE Dependency cycles detected, you should fix these!
lerna WARN ECYCLE @alilc/lowcode-designer -> @alilc/lowcode-shell -> @alilc/lowcode-editor-skeleton -> @alilc/lowcode-designer
@alilc/lowcode-types: yarn run v1.22.19
@alilc/lowcode-types: warning package.json: No license field
@alilc/lowcode-types: $ build-scripts build --skip-demo
@alilc/lowcode-types: @alib/build-scripts 0.1.32
@alilc/lowcode-types: info Can not find demo folder for component development 
@alilc/lowcode-types: ERR! Duplicate plugin/preset detected.
@alilc/lowcode-types: If you'd like to use two separate instances of a plugin,
@alilc/lowcode-types: they need separate names, e.g.
@alilc/lowcode-types:   plugins: [
@alilc/lowcode-types:     ['some-plugin', {}],
@alilc/lowcode-types:     ['some-plugin', {}, 'some unique name'],
@alilc/lowcode-types:   ]
@alilc/lowcode-types: Duplicates detected are:
@alilc/lowcode-types: [
@alilc/lowcode-types:   {
@alilc/lowcode-types:     "alias": "/usr/src/lowcode-engine/node_modules/@babel/plugin-proposal-class-properties/lib/index.js",
@alilc/lowcode-types:     "options": {
@alilc/lowcode-types:       "loose": true
@alilc/lowcode-types:     },
@alilc/lowcode-types:     "dirname": "/usr/src/lowcode-engine/packages/types",
@alilc/lowcode-types:     "ownPass": false,
@alilc/lowcode-types:     "file": {
@alilc/lowcode-types:       "request": "/usr/src/lowcode-engine/node_modules/@babel/plugin-proposal-class-properties/lib/index.js",
@alilc/lowcode-types:       "resolved": "/usr/src/lowcode-engine/node_modules/@babel/plugin-proposal-class-properties/lib/index.js"
@alilc/lowcode-types:     }
@alilc/lowcode-types:   },
@alilc/lowcode-types:   {
@alilc/lowcode-types:     "alias": "/usr/src/lowcode-engine/node_modules/@babel/plugin-proposal-class-properties/lib/index.js",
@alilc/lowcode-types:     "options": {
@alilc/lowcode-types:       "loose": true
@alilc/lowcode-types:     },
@alilc/lowcode-types:     "dirname": "/usr/src/lowcode-engine/packages/types",
@alilc/lowcode-types:     "ownPass": false,
@alilc/lowcode-types:     "file": {
@alilc/lowcode-types:       "request": "/usr/src/lowcode-engine/node_modules/@babel/plugin-proposal-class-properties/lib/index.js",
@alilc/lowcode-types:       "resolved": "/usr/src/lowcode-engine/node_modules/@babel/plugin-proposal-class-properties/lib/index.js"
@alilc/lowcode-types:     }
@alilc/lowcode-types:   }
@alilc/lowcode-types: ] 
@alilc/lowcode-types: Error: Duplicate plugin/preset detected.
@alilc/lowcode-types: If you'd like to use two separate instances of a plugin,
@alilc/lowcode-types: they need separate names, e.g.
@alilc/lowcode-types:   plugins: [
@alilc/lowcode-types:     ['some-plugin', {}],
@alilc/lowcode-types:     ['some-plugin', {}, 'some unique name'],
@alilc/lowcode-types:   ]
@alilc/lowcode-types: Duplicates detected are:
@alilc/lowcode-types: [
@alilc/lowcode-types:   {
@alilc/lowcode-types:     "alias": "/usr/src/lowcode-engine/node_modules/@babel/plugin-proposal-class-properties/lib/index.js",
@alilc/lowcode-types:     "options": {
@alilc/lowcode-types:       "loose": true
@alilc/lowcode-types:     },
@alilc/lowcode-types:     "dirname": "/usr/src/lowcode-engine/packages/types",
@alilc/lowcode-types:     "ownPass": false,
@alilc/lowcode-types:     "file": {
@alilc/lowcode-types:       "request": "/usr/src/lowcode-engine/node_modules/@babel/plugin-proposal-class-properties/lib/index.js",
@alilc/lowcode-types:       "resolved": "/usr/src/lowcode-engine/node_modules/@babel/plugin-proposal-class-properties/lib/index.js"
@alilc/lowcode-types:     }
@alilc/lowcode-types:   },
@alilc/lowcode-types:   {
@alilc/lowcode-types:     "alias": "/usr/src/lowcode-engine/node_modules/@babel/plugin-proposal-class-properties/lib/index.js",
@alilc/lowcode-types:     "options": {
@alilc/lowcode-types:       "loose": true
@alilc/lowcode-types:     },
@alilc/lowcode-types:     "dirname": "/usr/src/lowcode-engine/packages/types",
@alilc/lowcode-types:     "ownPass": false,
@alilc/lowcode-types:     "file": {
@alilc/lowcode-types:       "request": "/usr/src/lowcode-engine/node_modules/@babel/plugin-proposal-class-properties/lib/index.js",
@alilc/lowcode-types:       "resolved": "/usr/src/lowcode-engine/node_modules/@babel/plugin-proposal-class-properties/lib/index.js"
@alilc/lowcode-types:     }
@alilc/lowcode-types:   }
@alilc/lowcode-types: ]
@alilc/lowcode-types:     at assertNoDuplicates (/usr/src/lowcode-engine/node_modules/@babel/core/lib/config/config-descriptors.js:182:13)
@alilc/lowcode-types:     at createDescriptors (/usr/src/lowcode-engine/node_modules/@babel/core/lib/config/config-descriptors.js:106:3)
@alilc/lowcode-types:     at createDescriptors.next (<anonymous>)
@alilc/lowcode-types:     at createPluginDescriptors (/usr/src/lowcode-engine/node_modules/@babel/core/lib/config/config-descriptors.js:98:17)
@alilc/lowcode-types:     at createPluginDescriptors.next (<anonymous>)
@alilc/lowcode-types:     at /usr/src/lowcode-engine/node_modules/@babel/core/lib/config/config-descriptors.js:64:32
@alilc/lowcode-types:     at Generator.next (<anonymous>)
@alilc/lowcode-types:     at Function.<anonymous> (/usr/src/lowcode-engine/node_modules/@babel/core/lib/gensync-utils/async.js:21:3)
@alilc/lowcode-types:     at Generator.next (<anonymous>)
@alilc/lowcode-types:     at evaluateSync (/usr/src/lowcode-engine/node_modules/gensync/index.js:251:28)
@alilc/lowcode-types: error Command failed with exit code 1.
@alilc/lowcode-types: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build exited 1 in '@alilc/lowcode-types'
lerna notice cli v4.0.0
lerna notice filter including ["@alilc/lowcode-engine","@alilc/lowcode-rax-simulator-renderer","@alilc/lowcode-react-simulator-renderer","@alilc/lowcode-react-renderer"]
lerna info filter [
lerna info filter   '@alilc/lowcode-engine',
lerna info filter   '@alilc/lowcode-rax-simulator-renderer',
lerna info filter   '@alilc/lowcode-react-simulator-renderer',
lerna info filter   '@alilc/lowcode-react-renderer'
lerna info filter ]
lerna info Executing command in 4 packages: "yarn run build:umd"
@alilc/lowcode-engine: yarn run v1.22.19
@alilc/lowcode-rax-simulator-renderer: yarn run v1.22.19
@alilc/lowcode-react-renderer: yarn run v1.22.19
@alilc/lowcode-react-renderer: warning package.json: No license field
@alilc/lowcode-react-renderer: warning package.json: "dependencies" has dependency "@alifd/next" with range "^1.21.16" that collides with a dependency in "devDependencies" of the same name with version "^1.19.17"
@alilc/lowcode-engine: $ NODE_OPTIONS=--max_old_space_size=8192 build-scripts build --config build.umd.json
@alilc/lowcode-rax-simulator-renderer: $ build-scripts build --config build.umd.json
@alilc/lowcode-react-renderer: $ NODE_OPTIONS=--max_old_space_size=8192 build-scripts build --config build.umd.json
@alilc/lowcode-rax-simulator-renderer: @alib/build-scripts 0.1.32
@alilc/lowcode-engine: @alib/build-scripts 0.1.32
@alilc/lowcode-react-renderer: @alib/build-scripts 0.1.32
@alilc/lowcode-engine: info 使用 Fusion 组件主题包： @alifd/theme-lowcode-light
@alilc/lowcode-react-renderer: info WEBPACK Hash: [1m8736a0dced8c5ffbfe83[39m[22m
@alilc/lowcode-react-renderer: info WEBPACK Version: webpack [1m4.46.0[39m[22m
@alilc/lowcode-react-renderer: info WEBPACK Child [1mweb[39m[22m:
@alilc/lowcode-react-renderer: info WEBPACK     Hash: [1m8736a0dced8c5ffbfe83[39m[22m
@alilc/lowcode-react-renderer: info WEBPACK     Time: [1m765[39m[22mms
@alilc/lowcode-react-renderer: info WEBPACK     Built at: 03/27/2023 [1m5:26:01 PM[39m[22m
@alilc/lowcode-react-renderer: info WEBPACK                        [1mAsset[39m[22m      [1mSize[39m[22m  [1mChunks[39m[22m  [1m[39m[22m       [1m[39m[22m[1mChunk Names[39m[22m
@alilc/lowcode-react-renderer: info WEBPACK         [1m[32mjs/react-renderer.js[39m[22m  5.73 KiB       [1m0[39m[22m  [1m[32m[39m[22m       react-renderer
@alilc/lowcode-react-renderer: info WEBPACK     [1m[32mjs/react-renderer.js.map[39m[22m  9.27 KiB       [1m0[39m[22m  [1m[32m[dev][39m[22m  react-renderer
@alilc/lowcode-react-renderer: ERR! (web) ./src/index.ts
@alilc/lowcode-react-renderer: ERR! Module not found: Can't resolve '@alilc/lowcode-renderer-core' in '/usr/src/lowcode-engine/packages/react-renderer/src'
@alilc/lowcode-react-renderer: ERR! webpack compile error 
@alilc/lowcode-react-renderer: Error: webpack compile error
@alilc/lowcode-react-renderer:     at /usr/src/lowcode-engine/node_modules/@alib/build-scripts/lib/commands/build.js:91:28
@alilc/lowcode-react-renderer:     at finalCallback (/usr/src/lowcode-engine/node_modules/webpack/lib/MultiCompiler.js:254:12)
@alilc/lowcode-react-renderer:     at /usr/src/lowcode-engine/node_modules/webpack/lib/MultiCompiler.js:277:6
@alilc/lowcode-react-renderer:     at done (/usr/src/lowcode-engine/node_modules/neo-async/async.js:2931:13)
@alilc/lowcode-react-renderer:     at runCompilers (/usr/src/lowcode-engine/node_modules/webpack/lib/MultiCompiler.js:181:48)
@alilc/lowcode-react-renderer:     at /usr/src/lowcode-engine/node_modules/webpack/lib/MultiCompiler.js:188:7
@alilc/lowcode-react-renderer:     at /usr/src/lowcode-engine/node_modules/webpack/lib/MultiCompiler.js:270:7
@alilc/lowcode-react-renderer:     at finalCallback (/usr/src/lowcode-engine/node_modules/webpack/lib/Compiler.js:257:39)
@alilc/lowcode-react-renderer:     at /usr/src/lowcode-engine/node_modules/webpack/lib/Compiler.js:273:13
@alilc/lowcode-react-renderer:     at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/src/lowcode-engine/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:33:1)
@alilc/lowcode-react-renderer:     at AsyncSeriesHook.lazyCompileHook (/usr/src/lowcode-engine/node_modules/tapable/lib/Hook.js:154:20)
@alilc/lowcode-react-renderer:     at onCompiled (/usr/src/lowcode-engine/node_modules/webpack/lib/Compiler.js:271:21)
@alilc/lowcode-react-renderer:     at /usr/src/lowcode-engine/node_modules/webpack/lib/Compiler.js:681:15
@alilc/lowcode-react-renderer:     at AsyncSeriesHook.eval [as callAsync] (eval at create (/usr/src/lowcode-engine/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:6:1)
@alilc/lowcode-react-renderer:     at AsyncSeriesHook.lazyCompileHook (/usr/src/lowcode-engine/node_modules/tapable/lib/Hook.js:154:20)
@alilc/lowcode-react-renderer:     at /usr/src/lowcode-engine/node_modules/webpack/lib/Compiler.js:678:31
@alilc/lowcode-react-renderer: error Command failed with exit code 1.
@alilc/lowcode-react-renderer: info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
lerna ERR! yarn run build:umd exited 1 in '@alilc/lowcode-react-renderer'
lerna WARN complete Waiting for 2 child processes to exit. CTRL-C to exit immediately.
cp: cannot stat './packages/react-simulator-renderer/dist/js/*': No such file or directory
cp: cannot stat './packages/react-simulator-renderer/dist/css/*': No such file or directory
cp: cannot stat './packages/rax-simulator-renderer/dist/js/*': No such file or directory
cp: cannot stat './packages/rax-simulator-renderer/dist/css/*': No such file or directory

环境信息：
---
 - AliLowCodeEngine version: 1.0.18 / 低代码引擎版本
 - AliLowCodeEngineExt version: 1.0.18 / 低代码引擎扩展包版本
 - Browser chrome / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本
 - npm 6.14.18
 - node.js 14.17.0

**Comment by liujuping** [comment]
可以尝试一下，删除依赖，重新安装依赖，再 build

**Comment by JackLian** [comment]
一般来说不建议自行fork维护打包，这种就是官方很难帮到你的情况了，官方也只会维护最新版本，历史版本不建议使用

**Comment by LeoYuan** [comment]
试着去 renderer-core 包下单独 npm run build 一次，然后再在根目录 npm run build~

@Z-Champion
