### ISSUE TITLE
如何实现页面级别的多页签功能?

### ISSUE THREAD

**Issue by Z-Champion** [alibaba/lowcode-engine#1797]
title: How to implement the page-level multi-tab function?

页签功能是后台管理系统较为常见的功能，各位乡亲父老有没有实践经历，能否提供一下思路！感谢！
The page tab function is a relatively common function in the background management system. I would be very grateful if you folks and elders have any practical experience, and can you provide some ideas！

**Comment by JackLian** [comment]
1. 你可能对本项目的定位有点误解，这个不是一个开源的低代码平台，而是一个用于开发低代码平台的前端研发框架
2. 你的问题更偏向于如何用一个低代码平台做实现某个功能，这个一般跟具体的平台有关，每个平台可能有自己的实现方式，一般是用tab组件
