### ISSUE TITLE
预览模式会Slot, 组件会报错

### ISSUE THREAD

**Issue by Wangjing991** [alibaba/lowcode-engine#1798]
页面预览的时候Slot会报错
![image](https://user-images.githubusercontent.com/19301714/228096999-05886043-cde6-4f76-9d99-a5737b8dbf7d.png)

**Comment by Wangjing991** [comment]
![image](https://user-images.githubusercontent.com/19301714/228097721-a571158b-8d08-4e27-a824-5a870e52891e.png)
预览模式 Slot 没有注册，导致这个地方报错

**Comment by JackLian** [comment]
可能schema里有脏数据，历史上某个版本会产生slot脏数据，用最新的引擎和demo试试

**Comment by Wangjing991** [comment]
![image](https://user-images.githubusercontent.com/19301714/228102414-2fed5b04-2449-47ac-870a-cebf6ffa9e44.png)
Schema 里面不用保存Slot组件数据？
目前我使用的是1.1.3版本

**Comment by Wangjing991** [comment]
![image](https://user-images.githubusercontent.com/19301714/228119918-a239f114-9822-48d0-944a-0270e0593952.png)

![image](https://user-images.githubusercontent.com/19301714/228119767-ac0d8d87-5c2a-489e-a750-387a528b975e.png)
![image](https://user-images.githubusercontent.com/19301714/228119775-29012f80-b08e-40e0-9351-d8992969ed23.png)
应该是这个方法，组件meta文件里面 type是JSSlot  会注入Slot组件进去

**Comment by liujuping** [comment]
页面预览的 API 看看参数是否正确
```
project.exportSchema(TransformStage.Save)
```

没有 TransformStage.Save 就会出现这个问题

**Comment by Wangjing991** [comment]
![image](https://user-images.githubusercontent.com/19301714/228154929-7cc206ee-7955-45d0-9fee-af52179325f2.png)
通过添加参数  导出数据还是会增加 Slot 节点数据

**Comment by liujuping** [comment]
得先清空这个数据，有可能是脏数据。如果清空之后还是不行，得提供详细的复现步骤。

**Comment by Wangjing991** [comment]
> 得先清空这个数据，有可能是脏数据。如果清空之后还是不行，得提供详细的复现步骤。

清空数据后好了
