### ISSUE TITLE
官方demo打包出来index文件体积过大，是否有优化方案？

### ISSUE THREAD

**Issue by RichadoM** [alibaba/lowcode-engine#1799]
![image](https://user-images.githubusercontent.com/56419029/228106349-f248fe7e-2a2c-4e52-b9e6-609adb330966.png)打包出来的index文件体积有5m之多，看analyze打包分析babel占了2m多，请问这部分是否有打包体积优化指北呢？

**Comment by JackLian** [comment]
官方目前没有计划对demo做什么优化，一般来说是某个插件引入的什么依赖，你可以自行分析处理下
