### ISSUE TITLE
新增物料setter设置器meta.ts里面的props属性是不是默认都放到configure,没有旧的那种propType设置了？？？

### ISSUE THREAD

**Issue by lijiaxu1996** [alibaba/lowcode-engine#180]
**问题描述:**
1. npm run lowcode:dev 形成meta.ts，自定义属性都放在confgure里面了
![image](https://user-images.githubusercontent.com/59685169/159836143-a3ed9660-1e97-470d-88df-1e712eea6cc7.png)
2. 没有以前那种单独设置的props?了么？
![image](https://user-images.githubusercontent.com/59685169/159836328-1724df3a-1572-4b22-9f3a-ba370ccdd975.png)

**Comment by LeoYuan** [comment]
我们一般这样区分内外 props 的定位：
- 外层的 props，由出码模块扫描 npm 组件后推断得出的属性以及类型
- 内层的 props（configure.props），由用户补充/修正属性

所以到了人工补充这一步，通常建议直接写到 configure 里~
