### ISSUE TITLE
ArraySetter 删除第一项会导致全部清空

### ISSUE THREAD

**Issue by izuomeng** [alibaba/lowcode-engine#1800]
## **Describe the bug (required)** / **详细描述 bug（必填）**

ArraySetter 删除第一项会导致所有项被清空

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1. 打开 [demo](https://lowcode-engine.cn/demo/demo-basic-antd/index.html)；
2. 拖入表格组件；
3. 在表格列配置中删除第一项

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
只有第一列配置被删除

---

## **Screenshots (optional)** / **bug 截图（可选）**
<img width="1862" alt="image" src="https://user-images.githubusercontent.com/28486975/228150868-b572d353-9a72-438d-ac06-51f2068df8da.png">

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: 1.1.5-beta.5
 - AliLowCodeEngineExt version: 1.0.6-beta.19
 - Browser: edge 109.0.1518.52 
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by izuomeng** [comment]
最新版确实不会，但我看版本是1.1.5-beta，这个等你们发布正式版就行了吗？

**Comment by liujuping** [comment]
是的。
