### ISSUE TITLE
SlotSetter 插槽开启后不生效

### ISSUE THREAD

**Issue by izuomeng** [alibaba/lowcode-engine#1802]
## **Describe the bug (required)** / **详细描述 bug（必填）**

SlotSetter 插槽开启后，不会出现展占位的容器

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1. 打开 [demo](https://lowcode-engine.cn/demo/demo-basic-antd/index.html)；
2. 拖入表格；
3. 表格列配置中打开自定义渲染；
<img width="1819" alt="image" src="https://user-images.githubusercontent.com/28486975/228178718-2b1d5e3e-dd7d-43bd-b435-187ba7232591.png">
4. 表格单元格中没有出现对应的插槽容器；

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
表格单元格中出现插槽容器，并可以拖入组件

---

## **Screenshots (optional)** / **bug 截图（可选）**
<img width="1863" alt="image" src="https://user-images.githubusercontent.com/28486975/228177721-9939594b-c205-4824-824c-8f660787ca1e.png">

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by JackLian** [comment]
看 #1810 应该是搞定了，先关闭了，再有问题可以继续提issue
