### ISSUE TITLE
画布中无法添加组件动作按钮，addBuiltinComponentAction执行报错

### ISSUE THREAD

**Issue by dlutwuwei** [alibaba/lowcode-engine#1816]
## **Describe the bug (required)** / **详细描述 bug（必填）**

通过插件加载自定义ComponentAction失败，有报错日志

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1. 创建插件，从material中引出addBuiltinComponentAction
2. 插件init方法中，调用addBuiltinComponentAction加载任意action
3. 刷新页面，自定义aciton没有展示，有相关报错日志
---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

组件选中态的action按钮能正常展示，点击执行相应逻辑

---

## **Screenshots (optional)** / **bug 截图（可选）**
加载action时发生空引用错误，看上去是designer会初始化完成，插件名称为addAction
<img width="894" alt="截屏2023-03-29 14 50 52" src="https://user-images.githubusercontent.com/3362483/228451307-4288bfa6-0ebf-4bcd-a128-30df5044d359.png">

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: 1.1.4
 - AliLowCodeEngineExt version: 1.0.5
 - Browser: chrome
 - materials: -

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
无

**Comment by eightHundreds** [comment]
https://lowcode-engine.cn/site/docs/guide/expand/editor/pluginContextMenu

<img width="716" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/18695431/327b5743-76f2-495d-9947-f23a462eefd3">

文档有问题
