### ISSUE TITLE
自定义物料如何获取数据源数据

### ISSUE THREAD

**Issue by qq527488061** [alibaba/lowcode-engine#1817]
有对应的数据源及接口，现在新建了一个物料，如何在物料中获取数据源信息

![aeaec6cc81e7d2cbd7c76803dd0ba2b](https://user-images.githubusercontent.com/18611044/228495380-27bf7645-b458-4ad1-8b4c-6ca74809ede4.png)

![a31b9c1ee1ee84c2919289ddf8c0855](https://user-images.githubusercontent.com/18611044/228495436-1aacae1c-6ea5-4922-8a2c-3b5a4f6122a4.png)

**Comment by eternalsky** [comment]
![2023-04-07 17 16 57](https://user-images.githubusercontent.com/8038928/230582272-07e7fd0b-fdef-4371-afea-c4c1d06a59ba.gif)
