### ISSUE TITLE
官方dome无法运行编辑器

### ISSUE THREAD

**Issue by 286yym** [alibaba/lowcode-engine#182]
## **Describe the bug (required)** / **详细描述 bug（必填）**
官方dome无法运行编辑器，导致事件无法编辑
A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
正常下载dome，执行npm i  && npm start
运行成功后无法打开事件编辑，源码编辑，schema编辑等
‘https://github.com/alibaba/lowcode-demo’ or ‘https://github.com/alibaba/lowcode-code-generator-demo’都是
打开内置编辑器会报错 ?? 错误

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
下载dome，安装依赖后运行，dome无法打开内置编辑器

Steps to reproduce the behavior: / 详细复现步骤：

---

中文版示例：

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为
希望官方能过提供正确的内置依赖，或者提供正常执行的dome示例
---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
![image](https://user-images.githubusercontent.com/47840563/159853950-3bddd9b5-c66b-41af-88c4-f2c01b6a5774.png)
![image](https://user-images.githubusercontent.com/47840563/159854101-80d070e5-34aa-415b-b708-206bdb27759f.png)
![image](https://user-images.githubusercontent.com/47840563/159854218-36a59ca7-df47-4f9e-a223-eb54ca1bd514.png)
---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.3] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.3] / 低代码引擎扩展包版本

**Comment by alvarto** [comment]
升级你的 Chrome / Edge 浏览器版本吧。

目前低代码引擎内部的编译目标是 Chrome 80+。于两年前发布的 Chrome 80 是支持了 Nullish Coalescing 的版本：https://v8.dev/blog/v8-release-80

**Comment by alvarto** [comment]
README 的第二章节也描述了这个部分：

<img width="692" alt="image" src="https://user-images.githubusercontent.com/1797855/159857021-34e35842-1f89-4547-b13c-d8032f1e294d.png">

**Comment by 286yym** [comment]
好的，谢谢，经过提示，发现这边使用的是QQ浏览器，导致的报错，改为Chrome 80+的谷歌浏览器后可以正常执行，问题搞定
