### ISSUE TITLE
官网demo中tabs标签页不显示

### ISSUE THREAD

**Issue by zhouxiny1** [alibaba/lowcode-engine#1821]
![image](https://user-images.githubusercontent.com/111745349/228717094-9eaa0178-06b4-4488-ac0d-28e858af1fcb.png)
从官网中antd组件库中拖拽出tabs组件，配置相中有默认的标签项值，但是左侧面板显示空白，更改值点预览也不显示

**Comment by liujuping** [comment]
https://4x.ant.design/components/tabs-cn/

![image](https://github.com/alibaba/lowcode-engine/assets/11935995/5cff983c-021d-4baa-b3c5-cb27402f2014)

升级 antd 版本到 4.23.0 即可
