### ISSUE TITLE
ArraySetter 输入后立刻失焦导致无法输入

### ISSUE THREAD

**Issue by izuomeng** [alibaba/lowcode-engine#1823]
## **Describe the bug (required)** / **详细描述 bug（必填）**

ArraySetter 输入后立刻失焦导致无法输入

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

https://user-images.githubusercontent.com/28486975/228724533-b90c7bb4-3520-4bb2-8a4a-f7f022a592ec.mov

1. 打开 [demo](https://lowcode-engine.cn/demo/demo-basic-antd/index.html)；
2. 拖入表格；
3. 在右侧修改表格数据字段为“name1”；
4. 输入框失焦

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

输入框焦点继续保留

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by izuomeng** [comment]
#1810

**Comment by canyuegongzi** [comment]
最近自定义setter 时也发现了这个问题，解决了吗
