### ISSUE TITLE
请问是否有提供api根据schema里的datasource数据，让Datasource面板也回显配置时的对应的请求

### ISSUE THREAD

**Issue by rongrongt** [alibaba/lowcode-engine#1837]
把页面的的schema存到服务器后成功回显到了页面上，回显后schema里的datasourse接口数据没有回显到插件面板上，请问是否有提供api根据schema里的datasource数据，让Datasource面板也回显配置时的对应的请求

复现步骤；
1、使用关键project.exportSchema(IPublicEnumTransformStage.Save)将页面数据保存到服务器
2、使用project.removeDocument(project.currentDocument as any);清除当前页面的数据
3、将保存的数据从服务器请求回本地，假设变量为schema
4、 再使用project.openDocument(schema.componentsTree[0]);渲染页面。

预期：能成功在datasource插件面板上回显页面上使用的接口配置信息

实际：没有回显datasurce

![image](https://user-images.githubusercontent.com/21823510/229427536-65d551dd-cb67-489e-a996-6538f4573406.png)

**Comment by huyuanxin** [comment]
![image](https://user-images.githubusercontent.com/42336113/229438452-5d3c9cd3-5036-4db1-bec7-c44a99e0affd.png)
我的文件切换是这样子的，数据源没啥问题

**Comment by rongrongt** [comment]
> ![image](https://user-images.githubusercontent.com/42336113/229438452-5d3c9cd3-5036-4db1-bec7-c44a99e0affd.png) 我的文件切换是这样子的，数据源没啥问题

我按照你的方法试了，还是不行。数据源面板在切换页面前先打开一下数据源面板，然后再去切换页面，就不会更新成新页面的数据源数据。但如果不要先去打开数据源面板，而是先将页面用scheam渲染出来，再去展开就有了，但是如果你再切换页面就是还是上一页的数据，就是数据源面板好像只会在第一次展示时更新数据

**Comment by huyuanxin** [comment]
> > ![image](https://user-images.githubusercontent.com/42336113/229438452-5d3c9cd3-5036-4db1-bec7-c44a99e0affd.png) 我的文件切换是这样子的，数据源没啥问题
> 
> 我按照你的方法试了，还是不行。数据源面板在切换页面前先打开一下数据源面板，然后再去切换页面，就不会更新成新页面的数据源数据。但如果不要先去打开数据源面板，而是先将页面用scheam渲染出来，再去展开就有了，但是如果你再切换页面就是还是上一页的数据，就是数据源面板好像只会在第一次展示时更新数据

我尝试预览数据源的内容时，切换页面，数据源不会刷新。
如果只是简单打开数据源面板，然后切换到页面面板切换页面，就会正常刷新

**Comment by rongrongt** [comment]
> > > ![image](https://user-images.githubusercontent.com/42336113/229438452-5d3c9cd3-5036-4db1-bec7-c44a99e0affd.png) 我的文件切换是这样子的，数据源没啥问题
> > 
> > 
> > 我按照你的方法试了，还是不行。数据源面板在切换页面前先打开一下数据源面板，然后再去切换页面，就不会更新成新页面的数据源数据。但如果不要先去打开数据源面板，而是先将页面用scheam渲染出来，再去展开就有了，但是如果你再切换页面就是还是上一页的数据，就是数据源面板好像只会在第一次展示时更新数据
> 
> 我尝试预览数据源的内容时，切换页面，数据源不会刷新。 如果只是简单打开数据源面板，然后切换到页面面板切换页面，就会正常刷新

你可以做到不刷新的情况下多次切换页面schema数据，然后datasource数据源面板那里跟着scheam里规定的api变？

**Comment by rongrongt** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/42336113/229438452-5d3c9cd3-5036-4db1-bec7-c44a99e0affd.png) 我的文件切换是这样子的，数据源没啥问题
> > > > 
> > > > 
> > > > 我按照你的方法试了，还是不行。数据源面板在切换页面前先打开一下数据源面板，然后再去切换页面，就不会更新成新页面的数据源数据。但如果不要先去打开数据源面板，而是先将页面用scheam渲染出来，再去展开就有了，但是如果你再切换页面就是还是上一页的数据，就是数据源面板好像只会在第一次展示时更新数据
> > > 
> > > 
> > > 我尝试预览数据源的内容时，切换页面，数据源不会刷新。 如果只是简单打开数据源面板，然后切换到页面面板切换页面，就会正常刷新
> > 
> > 
> > 你可以做到不刷新的情况下多次切换页面schema数据，然后datasource数据源面板那里跟着scheam里规定的api变？
> 
> 是的，可以正常切换然后数据源面板也会跟着刷新

我按照你提供的关键代码是没有任何用的，有咩有可能有些关键代码你没有提供？

**Comment by rongrongt** [comment]
> > > > > ![image](https://user-images.githubusercontent.com/42336113/229438452-5d3c9cd3-5036-4db1-bec7-c44a99e0affd.png) 我的文件切换是这样子的，数据源没啥问题
> > > > 
> > > > 
> > > > 我按照你的方法试了，还是不行。数据源面板在切换页面前先打开一下数据源面板，然后再去切换页面，就不会更新成新页面的数据源数据。但如果不要先去打开数据源面板，而是先将页面用scheam渲染出来，再去展开就有了，但是如果你再切换页面就是还是上一页的数据，就是数据源面板好像只会在第一次展示时更新数据
> > > 
> > > 
> > > 我尝试预览数据源的内容时，切换页面，数据源不会刷新。 如果只是简单打开数据源面板，然后切换到页面面板切换页面，就会正常刷新
> > 
> > 
> > 你可以做到不刷新的情况下多次切换页面schema数据，然后datasource数据源面板那里跟着scheam里规定的api变？
> 
> 是的，可以正常切换然后数据源面板也会跟着刷新

我按照你提供的关键代码是没有任何用的，有咩有可能有些关键代码你没有提供？

**Comment by huyuanxin** [comment]
> > > > > > ![image](https://user-images.githubusercontent.com/42336113/229438452-5d3c9cd3-5036-4db1-bec7-c44a99e0affd.png) 我的文件切换是这样子的，数据源没啥问题
> > > > > 
> > > > > 
> > > > > 我按照你的方法试了，还是不行。数据源面板在切换页面前先打开一下数据源面板，然后再去切换页面，就不会更新成新页面的数据源数据。但如果不要先去打开数据源面板，而是先将页面用scheam渲染出来，再去展开就有了，但是如果你再切换页面就是还是上一页的数据，就是数据源面板好像只会在第一次展示时更新数据
> > > > 
> > > > 
> > > > 我尝试预览数据源的内容时，切换页面，数据源不会刷新。 如果只是简单打开数据源面板，然后切换到页面面板切换页面，就会正常刷新
> > > 
> > > 
> > > 你可以做到不刷新的情况下多次切换页面schema数据，然后datasource数据源面板那里跟着scheam里规定的api变？
> > 
> > 
> > 是的，可以正常切换然后数据源面板也会跟着刷新
> 
> 我按照你提供的关键代码是没有任何用的，有咩有可能有些关键代码你没有提供？

我这个是整个选择页面的逻辑，你看看？
```ts

// 切换
const onSelect = async (item: string) => {
    const current = await getCurrent()
    if (current===item){
      return
    }
    const schema = await getProjectSchemaFromLocalStorage(item);
    console.log('current schema: ', schema);
    // 加载 schema
    project.removeDocument(project.currentDocument as any);
    project.importSchema(schema)
    project.simulatorHost?.rerender();

    // config.set('currentPage', scenarioName);
    await setCurrent(item)
  };

// 取出
export const getProjectSchemaFromLocalStorage = (scenarioName: string) => {
  console.log("current scenarioName:", scenarioName)
  if (!scenarioName) {
    console.error('scenarioName is required!');
    return undefined;
  }
  const localValue = SchemaMap.get(scenarioName)
  if (localValue === undefined) {
    console.log("rollback to default")
    return defaultSchema
  }
  if (localValue) {
    return JSON.parse(localValue);
  }
  return undefined;
}

// 保存
export const setProjectSchemaToLocalStorage = (scenarioName: string) => {
  if (!scenarioName) {
    console.error('scenarioName is required!');
    return;
  }
  SchemaMap.set(scenarioName, JSON.stringify(project.exportSchema(IPublicEnumTransformStage.Save)))
}
```
