### ISSUE TITLE
可以直接在lowcode-materials项目中增加自定义组件吗？

### ISSUE THREAD

**Issue by MrShenPH** [alibaba/lowcode-engine#1838]
我在fusion-lowcode-materials的项目中尝试增加自定义组件，但是在run的时候没有自动生成lowcode文件夹下的meta文件是为什么呢

**Comment by eternalsky** [comment]
没必要在 lowcode-materials 里增加组件，参考文档：https://lowcode-engine.cn/site/docs/guide/expand/editor/material
