### ISSUE TITLE
物料包新增组件，组件报错：Component Not found

### ISSUE THREAD

**Issue by douyaya** [alibaba/lowcode-engine#1839]
### 步骤：
npm init @alilc/element my-compoennts
新增一个依赖@ant-design/pro-components的自定义组件MyTable，
npm run owcode:dev
拖入新增组件至画布
报错： MyTable component is not found in components list! component list is: 
---

### 复现地址：https://github.com/douyaya/my-components

备注：把自定义组件中引用的ProTable换成antd的table就不会报这个错，应该是依赖@ant-design/pro-components的问题，关键是我应该怎么样引入@ant-design/pro-components呢？

**Comment by eternalsky** [comment]
打开控制台，查看一下有什么报错

**Comment by eternalsky** [comment]
这些都是 react 的warning ，不影响使用，看看有没有 error 的提示

**Comment by liujuping** [comment]
可以参考这个文档自查一下

https://lowcode-engine.cn/site/docs/faq/faq009

**Comment by eternalsky** [comment]
> > 这些都是 react 的warning ，不影响使用，看看有没有 error 的提示
> > 难道是因为这个？
> > ![image](https://user-images.githubusercontent.com/34003600/229470362-8f44b7a8-1db6-4941-9362-da6734ac6e37.png)

看起来是这个，所有的 error 类都会产生问题。尤其是这个 error 还是报在组件里的。

**Comment by douyaya** [comment]
> > > 这些都是 react 的warning ，不影响使用，看看有没有 error 的提示
> > > 难道是因为这个？
> > > ![image](https://user-images.githubusercontent.com/34003600/229470362-8f44b7a8-1db6-4941-9362-da6734ac6e37.png)
> 
> 看起来是这个，所有的 error 类都会产生问题。尤其是这个 error 还是报在组件里的。

感觉应该是demo使用的pro-components版本比我自定义组件内使用的版本低导致的？这个报错应该是demo本身的报错，我组件内没有使用pro-layout

**Comment by eternalsky** [comment]
目前可以明确是这个报错就是你这个组件引入导致的，如果在入口注释了 my-table 的导出的话，就不会有这个报错了。这个报错是在类定义的，即使不引用，只要打包打进去就会有影响。

**Comment by eternalsky** [comment]
自己排查了一下，出不来的原因是因为你把 packageName 改成了 my-components-new，但是 meta 信息里还指定了这些组件从 my-components 里导出，导致对不上，packageName 改为 my-components 后就可以显示了。

**Comment by eternalsky** [comment]
另外还有两个小问题，一个是 @ant-design/icons 报找不到，这个是 build-plugin-lowcode 里 external 到 window.icons 了，但其实 assets 里也没有引 @ant-design/icons  的umd 导致报错，很奇怪，后面准备去掉。还有就是默认情况下开发环境引用的 antd 版本是 4.17.3，如果你引用的是更高级的版本，请通过设置 extraAssets 来更改。

**Comment by eternalsky** [comment]
上面提到的第一个小问题已发版修复，更新依赖即可。

**Comment by douyaya** [comment]
> 上面提到的第一个小问题已发版修复，更新依赖即可。

好的，感谢

**Comment by douyaya** [comment]
> 



> 另外还有两个小问题，一个是 @ant-design/icons 报找不到，这个是 build-plugin-lowcode 里 external 到 window.icons 了，但其实 assets 里也没有引 @ant-design/icons 的umd 导致报错，很奇怪，后面准备去掉。还有就是默认情况下开发环境引用的 antd 版本是 4.17.3，如果你引用的是更高级的版本，请通过设置 extraAssets 来更改。
> 
> build-plugin-lowcode 文档：https://www.npmjs.com/package/@alifd/build-plugin-lowcode

这个怎么配呢，我这两种写法怎么都报错了
![L1VzZXJzL2Fsc2MvTGlicmFyeS9BcHBsaWNhdGlvbiBTdXBwb3J0L2lEaW5nVGFsay8zMTc4MTE1NzAyX3YyL0ltYWdlRmlsZXMvMTY4MTEwMTA4MDAzM18wMDVERjBDMy0yRUE4LTQ2Q0QtQjNERC02NDBEQzM2MEIxM0EucG5n](https://user-images.githubusercontent.com/34003600/230826288-a9559782-eb91-4c29-bd73-28a3e87ee594.png)
