### ISSUE TITLE
build-scripts: command not found

### ISSUE THREAD

**Issue by cnqiuxue** [alibaba/lowcode-engine#1844]
# 错误描述：
![image](https://user-images.githubusercontent.com/26665435/230069376-eba9fbd1-f0a7-4c05-9008-9f64e157776a.png)
demo-general -- > node_modules下也是有build-scripts包的：
![image](https://user-images.githubusercontent.com/26665435/230071019-43d9bab8-5e60-4bf5-aa92-ec5a8ac7714d.png)
尝试全局安装 build-scripts 后依然如此
```
npm install -D  @alib/build-scripts --save-dev
npm i build-scripts -g
```

# 具体步骤如下：
> 按照低代码引擎官网的快速开始步骤启动项目：
（https://lowcode-engine.cn/site/docs/guide/quickStart/start）
```
git clone https://github.com/alibaba/lowcode-demo.git
cd lowcode-demo
cd demo-general
npm install
npm run start
```

# 环境：
> 中途尝试将node跟换v16.18.1 ，还是报同样的错误。

![image](https://user-images.githubusercontent.com/26665435/230069377-4d51ef97-f19c-491e-a878-128d79c0e57c.png)

# 系统：
![image](https://user-images.githubusercontent.com/26665435/230070456-fb0bb53d-7713-4123-96e0-2adb5dc6f630.png)

**Comment by cnqiuxue** [comment]
1、在终端尝试安装：
```
npm i @alib/build-scripts -g
```
2、然后查看以下命令：
![image](https://user-images.githubusercontent.com/26665435/230074602-560cdab8-cf88-4d55-a266-0c0d3caf5629.png)
3、项目可以运行了

**Comment by LeoYuan** [comment]
`npm run xxx` 的时候会临时将 `${curDir}/node_modules/.bin` 加入到系统 PATH 路径下，可以自查一下，可能是 .bin 在使用 npm/cnpm/yarn/pnpm 安装依赖时没有正确生成~

**Comment by cnqiuxue** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
