### ISSUE TITLE
ArraySetter 拖拽排序失效

### ISSUE THREAD

**Issue by izuomeng** [alibaba/lowcode-engine#1845]
## **Describe the bug (required)** / **详细描述 bug（必填）**

ArraySetter 拖拽排序失效

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

https://user-images.githubusercontent.com/28486975/230262303-1ff5f239-7e31-4495-9010-25396918bab8.mov

1. 打开 [demo](https://lowcode-engine.cn/demo/demo-basic-antd/index.html)；
2. 拖入表格组件；
3. 拖拽列排序；
4. 设置面板里的列排序不变；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

设置面板里的列排序变成拖拽后的样子

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by izuomeng** [comment]
@liujuping 官网demo现在还是坏的，并没有修复

**Comment by eightHundreds** [comment]
+1 @liujuping

**Comment by liujuping** [comment]
哪个物料方便复现？目前我在表格物料上复现是没有问题的，但是物料没有配置快捷编辑项，点开 item 的编辑，可以看到配置的顺序是改变了的。

**Comment by eightHundreds** [comment]
![2023-04-26 11 01 33](https://user-images.githubusercontent.com/18695431/234462501-e1962db6-9384-4762-bda9-245333920702.gif)
