### ISSUE TITLE
ObjectSetter文档优化

### ISSUE THREAD

**Issue by eightHundreds** [alibaba/lowcode-engine#1853]
**可能是Bug**

https://github.com/alibaba/lowcode-engine/blob/main/docs/docs/guide/appendix/setterDetails/array.md
<img width="1040" alt="image" src="https://user-images.githubusercontent.com/18695431/230584696-b0266d32-a14c-4e23-979a-251ff79fcdb6.png">

实际上漏写了一个条件, 即`isRequired:true`的item必须放在items数组靠前的位置

因为[这里](https://github.com/alibaba/lowcode-engine-ext/blob/066c36897241f223aca0f7a8db1aadf4beb3d7fe/src/setter/object-setter/index.tsx#L62), `l` 的最大值为`4`，所以它只会从前4个item中找`isRequired`为true的

<img width="712" alt="image" src="https://user-images.githubusercontent.com/18695431/230585460-7a512029-3cee-4a95-9141-123deaff93c6.png">

**Comment by AndyJinSS** [comment]
看了下代码是个bug，我提交了pr

**Comment by lijicheng123** [comment]
兄弟好细~

**Comment by eightHundreds** [comment]
> 兄弟好细~

![749f2472-e7b4-4407-9c3d-16d15f7d42fa](https://user-images.githubusercontent.com/18695431/231724595-d05032b2-e480-4e02-8bf0-a53289da29e7.jpg)
