### ISSUE TITLE
打包报错

### ISSUE THREAD

**Issue by ZFzzz** [alibaba/lowcode-engine#1861]
错误描述:
![EBFE8DC8-D10F-41CF-82BD-B4C0161217D6](https://user-images.githubusercontent.com/29327965/231323549-5e536a4e-fae2-482f-8200-2f29bb023e99.png)
具体步骤如下：
下载lowcode-engine release_1.1.6
npm install
npm run build:umd
报错build-script:command not found 后安装build-scripts
npm i @alib/build-scripts -g

然后执行npm run build:umd还是报如上错误

**Comment by JackLian** [comment]
那直接从官方cdn搬过去吧
