### ISSUE TITLE
现有组件库作为物料库接入lowcode-engine报错

### ISSUE THREAD

**Issue by douyaya** [alibaba/lowcode-engine#1862]
## **现有组件库作为物料库接入lowcode-engine报错**

组件库是基于dumi2创建的，执行lowcode:build后生成的文件缺少meta.js，导致lowcde:dev时报错：

![image](https://user-images.githubusercontent.com/34003600/231104343-9d0d1d69-b017-4854-8d45-40e20eac55e7.png)

---

Steps to reproduce the behavior: / 详细复现步骤：

---

1. 打开demo: ,https://github.com/douyaya/citd
2. npm i
3. npm run lowcode:dev
4. 运行不起来，报错参见上图

**Comment by eternalsky** [comment]
这个项目是 @alilc/elements 创建的吗

**Comment by douyaya** [comment]
> 这个项目是 @alilc/elements 创建的吗

不是

**Comment by douyaya** [comment]
> 这个项目是 @alilc/elements 创建的吗

不是，是直接dumi创建的

**Comment by eternalsky** [comment]
看了一下是入料模块没有解析出来你的组件，可以按照lowcode 目录的要求自行补齐。

**Comment by douyaya** [comment]
> lowcode:build 和 lowcode:dev 没有关系，lowcode:dev 执行不需要依赖 lowcode:build

我表述有误，我是想说都没有产出meta.js

**Comment by douyaya** [comment]
> 看了一下是入料模块没有解析出来你的组件，可以按照lowcode 目录的要求自行补齐。
具体怎么搞有参考模块可以提供嘛？

**Comment by eternalsky** [comment]
> > 看了一下是入料模块没有解析出来你的组件，可以按照lowcode 目录的要求自行补齐。
> > 具体怎么搞有参考模块可以提供嘛？

可以参考 lowcode-materials 仓库，或其他可以正确解析出来的。
