### ISSUE TITLE
lowcode-graph项目加载PluginMaterialsPane失败

### ISSUE THREAD

**Issue by ChiZng** [alibaba/lowcode-engine#1866]
## 详细描述
启动项目后在浏览器中打开，左侧扩展区中不展示PluginMaterialsPane。打开控制台发现报了一个错。
![image](https://user-images.githubusercontent.com/27946984/231369422-7898f4d5-2d88-4e68-a6b8-8376d8936a41.png)
## 复现步骤
拉取lowcode-graph项目，执行npm install、npm run setup、npm run start:x6。打开浏览器查看物料面板。
## 版本
lowcode-graph main分支。
## 其他
浏览器控制台看到
![image](https://user-images.githubusercontent.com/27946984/231370610-5ca09bdc-ec38-4312-b957-3da58855e3a1.png)
。官方提供的体验地址上的版本为
![image](https://user-images.githubusercontent.com/27946984/231370396-3fd76c70-72f7-4067-b294-ef014b43ffcd.png)

将lowcodeengine和ext版本升级到和体验地址相同，左侧的物料插件面板可以出来，但是画布面板会报错。

**Comment by lukeup** [comment]
已更新主包demo内容
