### ISSUE TITLE
Schema中的Page元素来自哪个物料库？

### ISSUE THREAD

**Issue by douyaya** [alibaba/lowcode-engine#1869]
## **Describe the bug (required)** / **详细描述 bug（必填）**

线上demo中的schema最上层是个Page元素，但是出码结果中处理成了div元素。（https://lowcode-engine.cn/demo/demo-basic-fusion/index.html）
![image](https://user-images.githubusercontent.com/34003600/231642110-e6a3bf3d-7ba1-40c7-99cf-a5a70734a7d4.png)
![image](https://user-images.githubusercontent.com/34003600/231642132-b1be2314-6561-43d9-994b-5406db9e6019.png)

问题场景：
同样的schema，使用单页面模块出码，出码结果中元素还是Page，但是不知道这个Page来自哪个物料库，没法指定依赖，导致生成代码中没有Page相关的import代码。
https://aliyuque.antfin.com/ali-lowcode/docs/uhh8gc#Ratke
![image](https://user-images.githubusercontent.com/34003600/231642321-f5a03ff8-8664-4632-8745-024921b58e01.png)

---

**Comment by LeoYuan** [comment]
Demo 中没有提供 Page 组件，在渲染器中默认渲染成 div 了，出码也做了类似设置~

https://github.com/alibaba/lowcode-engine/blob/d0c3c0f13c10a5e9545c680e4a6b12128c0720c6/modules/code-generator/src/solutions/icejs.ts#L76-L84
