### ISSUE TITLE
为 AlifdFusionUiMeta 物料的 EditTable 组件添加自定义数据源，编辑器中表格数据和数据源数据不同步

### ISSUE THREAD

**Issue by mirages** [alibaba/lowcode-engine#187]
## **Describe the bug (required)** / **详细描述 bug（必填）**

给 AlifdFusionUiMeta 的 EditTable 组件添加 dataSource 属性配置，出码结果显示表格 dataSource prop 数据已经更新，但是编辑器中表格数据没有同步更新。

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1. 运行 lowcode-demo 应用
2. 调用 material.registerMetadataTransducer 修改物料元数据信息：
```js
material.registerMetadataTransducer((metadata) => {
  let props = null
  let hasDataSource = false

  if (metadata.componentName === 'EditTable') {
    props = metadata.configure.props
    hasDataSource = props.find(item => item.name === 'dataSource')
  }

  if (props && !hasDataSource) {
    props.push({
      display: 'accordion',
      name: 'dataSource',
      type: 'field',
      title: {
        label: '数据源',
        tip: '设置表格数据源'
      },
      setter: (target: any) => {
        const columns = target.getProps().getPropValue('columns')
        if (!columns || columns.type === 'JSExpression') {
          return {
            componentName: 'ExpressionSetter'
          }
        }

        return {
          componentName: 'MixedSetter',
          props: {
            setters: [
              {
                componentName: 'ArraySetter',
                props: {
                  itemSetter: {
                    componentName: 'ObjectSetter',
                    props: {
                      config: {
                        items: columns.map((item: any, index: number) => {
                          return {
                            name: item.dataIndex,
                            title: item.title,
                            setter: {
                              componentName: 'StringSetter'
                            },
                            isRequired: index < 3, // 设置前三个为快捷编辑项
                            defaultValue: ''
                          }
                        })
                      }
                    }
                  }
                },
                initialValue: []
              },
              'ExpressionSetter'
            ]
          }
        }
      }
    })
    console.log('EditTable', props)
  }

  return metadata
}, 1000, 'EditTable')
```
3. 拖入**组件库--->精选组件--->表格类--->可编辑表格**到编辑器中
4. 查看右侧属性配置面板中增加了“数据源”配置项，修改数据源数据，编辑器中表格数据没有同步更新，查看出码结果显示表格 dataSource prop 已经更新了。

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
修改可编辑表格自定义的数据源属性配置，编辑器中表格数据同步发生更新

---

## **Screenshots (optional)** / **bug 截图（可选）**
<img width="1755" alt="iShot2022-03-24 20 28 44" src="https://user-images.githubusercontent.com/12791299/159917289-deccc7d0-73c2-4722-bfdf-07117e7b8b4c.png">
<img width="1490" alt="iShot2022-03-24 20 30 10" src="https://user-images.githubusercontent.com/12791299/159917318-0db402c0-00d4-4592-a1bd-86a4b0c97f16.png">

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: 1.0.1
 - AliLowCodeEngineExt version: 1.0.2
 - Browser chrome

**Comment by liujuping** [comment]
1.EditTable 的 dataSource props 变化是不会触发组件根据新的 dataSource props 更新的，和物料内部行为有关。
2.可以使用 ProTable 组件，dataSource props 变化可以更新。

**Comment by mirages** [comment]
@liujuping 好的，了解了。那 EditTable 后续会开放数据源配置吗？

**Comment by liujuping** [comment]
不确定，editTable 组件的数据源交互设计还在和物料负责人沟通。

**Comment by mirages** [comment]
好的，希望能够支持，多谢！:pray:
