### ISSUE TITLE
容器的循环能力

### ISSUE THREAD

**Issue by gofancyever** [alibaba/lowcode-engine#1872]
## **Describe the bug (required)** / **详细描述 bug（必填）**
官方组件布局容器是否可以实现循环
A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
希望实现循环拖拽搭建出的组件
---

**Comment by JackLian** [comment]
https://lowcode-engine.cn/site/docs/demoUsage/appendix/loop

**Comment by gofancyever** [comment]
> https://lowcode-engine.cn/site/docs/demoUsage/appendix/loop

布局容器中并有循环的配置项
![截屏2023-04-14 08 57 01](https://user-images.githubusercontent.com/17694833/231914113-3ebae11a-cde3-4f99-b7e2-95d0442774b7.png)

**Comment by JackLian** [comment]
如果说的是自然布局下的容器，那就是by design没有的，因为这个如果提供了循环能力，会破坏整体布局设计
