### ISSUE TITLE
物料包太大，分包之后没办法按顺序引入

### ISSUE THREAD

**Issue by Sarali2022** [alibaba/lowcode-engine#1873]
目前我们通过各种方式，把引用第三方包隔离出去之后，当前物料包打包之后，仍然还有4m左右，我们用webpack进行分包处理，但是在demo项目引入分包文件时，没办法确认分包之后的先后顺序。这块有解决方案吗？

**Comment by liujuping** [comment]
可以尝试一下，

1.获取 schema，根据 schema 里面的 componentsMap，获取 schema 需要的资产包

2.通过 material.setAssets 设置资产包

3.在设计器渲染完成之后，再异步通过 material.loadIncrementalAssets 设置剩下的资产包

**Comment by liujuping** [comment]
是的，要么拆包。要么线上版本根据使用的组件，打包一个新的文件。
