### ISSUE TITLE
ExpressionSetter 下拉框不显示可选的表达式，但是可点击选择

### ISSUE THREAD

**Issue by mirages** [alibaba/lowcode-engine#188]
## **Describe the bug (required)** / **详细描述 bug（必填）**

ExpressionSetter 下拉框不显示可选的表达式，但是仍然可以点击下拉框选项

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1. 运行 lowcode-demo 应用
2. 添加一个按钮组件
3. 查看属性设置面板，将“按钮内容”配置切换到“表达式输入”
4. 点击输入框，显示一个空白下拉框，但是仍然可点击并选择内容

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
下拉框内显示可选的表达式

---

## **Screenshots (optional)** / **bug 截图（可选）**
<img width="1047" alt="iShot2022-03-24 21 17 30" src="https://user-images.githubusercontent.com/12791299/159924603-5a4bff39-1601-4cc5-9f47-da1e0c82abfe.png">

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: 1.0.1
 - AliLowCodeEngineExt version: 1.0.2
 - Browser chrome

**Comment by LeoYuan** [comment]
![image](https://user-images.githubusercontent.com/1195765/160114046-95666aa2-fe15-4c05-b9de-fd4de0f1d46a.png)

建议使用最新版的 demo 来体验~
