### ISSUE TITLE
如何控制节点操作项的显隐

### ISSUE THREAD

**Issue by jiamengnan** [alibaba/lowcode-engine#1880]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

根据物料协议，通过控制condition即可控制操作项的显隐
![image](https://user-images.githubusercontent.com/39615009/232266069-d55eb09e-1152-44b7-92be-8b62464096d3.png)
但是，我在代码里设置了condition：false，发现操作项还是可见的
代码如下：
![image](https://user-images.githubusercontent.com/39615009/232266223-2789c368-8dd1-4fe9-a107-6e27aa7f4f66.png)
想问下应该怎么条件控制这里的显隐呢？

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

可以通过condition条件控制显隐

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: 1.1.6/ 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by liujuping** [comment]
目前的逻辑是：当 disableBehaviors 配置了 * 的时候，actions 下的 condition 才生效。

**Comment by jiamengnan** [comment]
> 当前的发布是：当disableBehaviors配置了*的时候，actions下的condition才有效。

貌似并没有生效
![image](https://user-images.githubusercontent.com/39615009/232363063-ad3dad64-04da-4912-ae16-6ef5c483abdb.png)

![image](https://user-images.githubusercontent.com/39615009/232362863-21a26f27-4f7e-40b0-a52e-f1203c9ad718.png)
并且根据代码的逻辑，只对always进行了过滤？想问一下，应该怎么实现分条件控制呢？比如button组件，在某个条件下不展示remove操作项，其他情况展示

**Comment by jiamengnan** [comment]
@liujuping 大佬帮忙再看下这个问题吧~目前我在meta中配置了disableBehaviors 为 * ，但是依旧没有生效

**Comment by LeoYuan** [comment]
看起来结构不太对啊，你参考下其他物料的写法😃搜condition

**Comment by jiamengnan** [comment]
> 

我看文档里是这样写的，和控制物料的显隐写法不一样
![image](https://user-images.githubusercontent.com/39615009/233819037-250eff8d-6e87-4649-b478-f52633a2a68a.png)

**Comment by jiamengnan** [comment]
> > 
> 
> @LeoYuan 感谢大佬帮我看这个问题~~~我看文档里是这样写的，和控制物料的显隐写法不太一样 ，请问这里有什么例子可以参考嘛~~我的诉求就是想动态控制节点操作项的显隐~~~![image](https://user-images.githubusercontent.com/39615009/233819037-250eff8d-6e87-4649-b478-f52633a2a68a.png)

**Comment by LeoYuan** [comment]
https://lowcode-engine.cn/site/docs/api/material#modifybuiltincomponentaction

试一下这个 API~
