### ISSUE TITLE
iframe下的跨域问题

### ISSUE THREAD

**Issue by ssjjdd** [alibaba/lowcode-engine#1881]
## **Describe the bug (required)** / **详细描述 bug（必填）**

![image](https://user-images.githubusercontent.com/23442317/232308962-9a5fc6c8-2069-40a2-80ad-7344cbdbac86.png)

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

demo-general启动
新建html
![image](https://user-images.githubusercontent.com/23442317/232309505-dfa59c11-742d-43bd-a01b-2d10a1823a34.png)

general项目在iframe打开中

**Comment by JackLian** [comment]
低代码引擎by design是独立页面使用的，可以自行研究下跨域问题的原因，如果发现是引擎的哪个部分导致，也可以提pr
