### ISSUE TITLE
【咨询】关于JSExpression中mock的问题

### ISSUE THREAD

**Issue by zboMa** [alibaba/lowcode-engine#1882]
版本1.1.2

在setValue中，设置JSExpression的时候，如果原值也是JSExpression，则将原值的值设置到新值的value中，新值设置到了mock中，但是在parseExpression中，使用的仍旧是.value取值。

另外，想咨询一下mock这个属性的作用是什么，JSExpression中，如果有mock，好像要使用mock，value反倒不是真正的值。
另外，mock还有两种格式，一种是普通的数据，一种是JSExpression，则parseExpression则需要判断多种情况。

```ts
if (str.mock) {
  if (isJSExpression(str.mock) || isJSFunction(str.mock)) {
    // todo
  } else {
    // 这时的mock好像不是新值，而是旧值，来源于variable-dialog
  }
} else {
  // 取值value
}

```

**Comment by liujuping** [comment]
版本 1.1.6 已经修复过这个问题

**Comment by zboMa** [comment]
好的 感谢 我升级试试
