### ISSUE TITLE
关于物料扩展脚手架 @alilc/element 的几个问题

### ISSUE THREAD

**Issue by Darcrandex** [alibaba/lowcode-engine#189]
1. 如何给组件添加默认内容插槽
2. `ComponentMetadata` 中的描述不是很明确
3. `build.json`是否支持配置`publicPath`
4.  其他的小问题

## 如何给组件添加默认内容插槽
通过 `@alilc/element` 创建物料组件库后，我想定义一个类似 `行-列容器` 的容器类组件，支持把其他组件拖入主组件的功能。
根据 [SlotSetter](https://www.yuque.com/lce/doc/af5vba) 的描述进行了配置，但似乎不是我想达到的效果。
是否有类似功能的demo提供参考？

## `ComponentMetadata` 中的描述不是很明确
通过 `npm run lowcode:build` 执行后生成的 `meta.ts` 中，`ComponentMetadata` 和 `Snippet` 的类型描述太简短了，有些还有 `@todo 待补充文档` 的内容。是否有关于脚手架比较完整的文档，或者在类型文件中多加点描述也行。

## `build.json`是否支持配置`publicPath`
脚手架打包后的配置文件中，url 都是以 `https://unpkg.alibaba-inc.com` 开头的，但是 `npm publish` 又没法用。每次手动修改真的很麻烦。
打包配置文件 `build.json` 中是否可以添加类似 `publicPath` 的字段用于定义资源路径前缀？

## 其他的小问题
1. 自动生成的 `meta.ts` 中 `"devMode": "proCode"` 应该是 `procode`。
2. 组件定义时，如果不引入 `createElement` 会在打包时报错。但是 `createElement` 没有被使用，是否是必须的？
3. 脚手架中似乎依赖了 `node-sass@4.12.0` 。目前必须使用 `node@14` `npm@6` 才能正常打包，后续是否可以考虑替换成 `dart-sass` 或者 `sass`。

以上。

`lowcode-engine`这个项目很有价值，但目前还有很多问题需要解决。希望官方团队可以继续优化和维护。谢谢。

**Comment by LeoYuan** [comment]
> 如何给组件添加默认内容插槽

都不用插槽，写一个父组件-行，配置 isContainer 为 true，写一个子组件，配置 nestingRule.parentWhitelist: ['YourRow'] 就行~

> ComponentMetadata 中的描述不是很明确

有这么几个地方可以查看：
- [搭建物料协议结构](https://lowcode-engine.cn/docV2/sde3wf)
- [类型定义源码](https://github.com/alibaba/lowcode-engine/blob/4f4ac5115d18357a7399632860808f6cffc33fad/packages/types/src/metadata.ts#L346)
- [物料协议](https://lowcode-engine.cn/lowcode)
- [基础 fusion 物料的描述实例](https://github.com/alibaba/lowcode-demo/blob/main/src/scenarios/basic-fusion/assets.json)

> build.json是否支持配置publicPath

可以试一下直接配置，不行的话参考 [build-scripts](https://github.com/ice-lab/build-scripts/) 如何写插件可以扩展该功能~

> 其他的小问题
- procode typo 问题 @mark-ck 辛苦跟进一下
- createElement @mark-ck 
- node-sass@4.12.0 @mark-ck

**Comment by Darcrandex** [comment]
好的，问题已解决。谢谢。

**Comment by Darcrandex** [comment]
修改打包基础路径的方法：
修改 `build.lowcode.js`
```js
module.exports = {
  alias: {
    '@': './src',
  },
  plugins: [
    [
      '@alifd/build-plugin-lowcode',
      {
        // 打包基础路径
        baseUrl: { prod: 'http://my-npm-lib/prod', dev: 'http://my-npm-lib/dev', daily: 'http://my-npm-lib/daily' },
        engineScope: '@alilc',
      },
    ],
  ],
}

```
