### ISSUE TITLE
pro-layout 物料问题

### ISSUE THREAD

**Issue by ChiZng** [alibaba/lowcode-engine#1890]
`综合场景`下的`页面组件` 扩展区域是空的。但是语雀文档中扩展区域中是有`左侧区域`和`右侧区域`的。想问一下综合场景下的这个pro-layout低代码组件是版本不对还是现在不开放这个扩展区域。
![image](https://user-images.githubusercontent.com/27946984/232424201-f21b8a4f-c509-4bba-aae9-01b4e09e6523.png)
![image](https://user-images.githubusercontent.com/27946984/232424394-ad3b2417-305c-4c38-896d-22322881b5e1.png)

## 版本
在线项目https://lowcode-engine.cn/demo/demo-general/index.html
![image](https://user-images.githubusercontent.com/27946984/232424949-9a2c9990-47dd-4b0e-ab8f-36cd4985425a.png)
物料版本
![image](https://user-images.githubusercontent.com/27946984/232425163-936c15c8-c76b-47a2-b4c1-a98937df8baf.png)

**Comment by JeanIO** [comment]
经过验证和比较，是自然布局自身的问题，并非集成问题。
在官方demo中也是同样的展现: https://g.alipay.com/@alifd/layout@2.0.10/build/lowcode/index.html。
可以通过代理得知，目前可以使用拓展区域的最近版本为**2.0.1**。
![image](https://user-images.githubusercontent.com/23093076/232443326-49f203bd-8de6-4da2-b78d-7391f1923392.png)，如果有该紧急需求可以使用该版本。

当然后面修复后，我们也会同步将该物料进行升级。
