### ISSUE TITLE
如何批量将左侧面板全部固定，并统一宽度？

### ISSUE THREAD

**Issue by StringKe** [alibaba/lowcode-engine#1896]
## **Describe the bug (required)** / **详细描述 bug（必填）**

如何固定左侧 PanelDock 的展现方式，并且统一所有的宽度

尝试自己找对应的修改发现里面存储是一个 Symbol 不知道要如何下一步了

**Comment by liujuping** [comment]
目前可以通过这个方式，将面板固定住

```javascript
import { config } from '@alilc/lowcode-engine';

const panelName = 'outline-master-pane';

// 设置大纲树面板钉住，在大纲树下次重新打开时生效
config.getPreference().set(`${panelName}-pinned-status-isFloat`, false, 'skeleton')
```

相关 demo 已补充：https://github.com/alibaba/lowcode-engine/pull/1908

统一宽度没有 api 可以提供，这个要么所有的插件提供配置项来修改宽度，要么自己定制插件。

**Comment by StringKe** [comment]
@liujuping 那如何获取已注册所有的 panel 呢

**Comment by liujuping** [comment]
通过这个找到 panel name。

![image](https://github.com/alibaba/lowcode-engine/assets/11935995/661b4e7d-493b-411a-8a49-e531cfdd0b53)

目前还没有对外的 api 帮助获取，目前只能先写死。
