### ISSUE TITLE
在低代码引擎js源码面板中，增加constructor，保存成功，但是提示部分函数解析出错，其内容无法保存

### ISSUE THREAD

**Issue by ajieying** [alibaba/lowcode-engine#190]
<img width="416" alt="image" src="https://user-images.githubusercontent.com/9877509/160068360-8a6bba35-99c7-4988-91cd-650d67dbc927.png">
如上图，在源码面板增加constructor之后，点击保存，上方提示保存成功，但是中间部分提示部分函数解析出错，其内容无法保存；
请问这个是什么原因呢？要怎么接收props

**Comment by LeoYuan** [comment]
现在应该是不支持接收 props 吧？
@alvarto
