### ISSUE TITLE
这两天弹窗自动显示并且关不掉吗？

### ISSUE THREAD

**Issue by lijicheng123** [alibaba/lowcode-engine#1902]
## **Describe the bug (required)** / **详细描述 bug（必填）**

记得前两天尝试使用弹窗的时候，点击节点的右上角的隐藏，去预览的时候不会自动显示，点击关闭按钮或者取消按钮会关闭。
这两天同样的操作就不行了，预览的时候弹窗会自动显示，同时点击任意按钮都关闭不了，不知道是不是bug。

![image](https://user-images.githubusercontent.com/15669871/232693954-ab3c16da-3a3f-4987-85c4-73304db541ab.png)

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

中文版示例：
1. 打开 [demo](https://lowcode-engine.cn/demo/demo-lowcode-component/index.html)；
2. 创建一个弹窗，复制他的refid，隐藏弹窗
3. 绑定一个按钮打开按钮，this.$('dialog-51fb11ff').open();
4. 保存后去预览

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

弹窗不是自动显示，而是先隐藏，点击按钮后再触发
---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

![image](https://user-images.githubusercontent.com/15669871/232694385-092c2ab8-b7e4-42a9-a5b1-562746b65906.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

在线demo：https://lowcode-engine.cn/demo/demo-lowcode-component/index.html
Chrome和Safari都尝试过了，不符合预期

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by liujuping** [comment]
这里的弹窗是用变量来控制的，你之前用的弹窗可能是这个 demo 的。两个弹窗用的物料不一样，用法也不一样。

https://lowcode-engine.cn/demo/demo-general/index.html

**Comment by lijicheng123** [comment]
但是文档：https://lowcode-engine.cn/site/docs/demoUsage/makeStuff/dialog是这么写的哦，
我按照你给的这个demo地址：https://lowcode-engine.cn/demo/demo-general/index.html，也是需要手动写js状态，那是不是需要把文档修改一下呢
