### ISSUE TITLE
演示站点打不开

### ISSUE THREAD

**Issue by wuliupo** [alibaba/lowcode-engine#1909]
## 演示站点打不开

演示站点打不开：
https://lowcode-engine.cn/demo/demo-general/index.html

浏览器：Microsoft Edge 112
`Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/112.0.0.0 Safari/537.36 Edg/112.0.1722.48`

用 Safari 可以

<img width="1047" alt="截屏2023-04-19 14 34 06" src="https://user-images.githubusercontent.com/1187809/232988497-893f699d-3271-4d64-b0dd-8a747129f7d5.png">
<img width="696" alt="截屏2023-04-19 14 37 40" src="https://user-images.githubusercontent.com/1187809/232988526-acc0208c-b3bf-47ac-9447-b9dde1184d80.png">

**Comment by JackLian** [comment]
这个就不知道怎么帮你了，检查下自己的网络情况吧，另外那个df-pub什么的地址是啥，阿里内部员工吗？

**Comment by wuliupo** [comment]
感觉就是很奇怪的问题，互联网用户可以公开访问，
问了内部阿里同事，有人也会有这个错误

**Comment by JackLian** [comment]
可能触发了啥安全拦截误报吧...

**Comment by LeoYuan** [comment]
AdBlock？

**Comment by wuliupo** [comment]
> AdBlock？

没有安装 AdBlock 也这样，几个同事都可以重现，应该是网络拦截了吧 @JackLian

**Comment by LeoYuan** [comment]
自己排查一下，假如是 g.alicdn.com 访问不了，那试试其他阿里系的网站，比如淘宝之类的是不是也不行

**Comment by JackLian** [comment]
建议找你们IT看看吧

**Comment by loujiali** [comment]
我们公司内网也报错 只能用热点或者guest网络访问
