### ISSUE TITLE
数据源编辑时，点击不同的数据源，相关信息没有切换

### ISSUE THREAD

**Issue by sunnyguohua** [alibaba/lowcode-engine#191]
## **详细描述 bug（必填）**
数据源编辑时，点击不同的数据源，相关信息没有切换

---

## **如何复现 bug？（必填，非常重要）**
1. 打开数据源设置
2. 点击左侧另外一个数据源的编辑按钮
3. 数据源编辑信息没有变化
<img width="966" alt="image" src="https://user-images.githubusercontent.com/6479673/160118275-17392333-ae12-4d06-91fa-96b12ab63726.png">

**Comment by LeoYuan** [comment]
@xingmolu
