### ISSUE TITLE
物料包太大请问如何进行拆包？

### ISSUE THREAD

**Issue by Super-Rz** [alibaba/lowcode-engine#1911]
物料库构建后view.js 过大，如何进行拆包优化

**Comment by eternalsky** [comment]
view.js 的规模，取决于你引入组件的规模，如果不希望引入过多的话，可以按需引入组件。

**Comment by Super-Rz** [comment]
这边是需要全量引入组件的，能不能支持在拖拽组件后才去加载组件的资源呢

**Comment by huliang56** [comment]
> view.js 的规模，取决于你引入组件的规模，如果不希望引入过多的话，可以按需引入组件。

如何进行按需引入，有案例吗？ 目前物料库构建是将所有物料全部放入一个view.js，是可以按什么规则构建多个js文件吗

**Comment by eternalsky** [comment]
> > view.js 的规模，取决于你引入组件的规模，如果不希望引入过多的话，可以按需引入组件。
> 
> 如何进行按需引入，有案例吗？ 目前物料库构建是将所有物料全部放入一个view.js，是可以按什么规则构建多个js文件吗

如果是一个物料仓库，那就是一起加载的。如果希望分开多个加载，可以拆成多个物料库。然后根据情况，选择性加载。

**Comment by eternalsky** [comment]
> 这边是需要全量引入组件的，能不能支持在拖拽组件后才去加载组件的资源呢

组件在面板里显示的时候，就需要这些资源了。当然如果你熟悉插件的改造的话，你也可以在任何你想做的时刻再去加载。

**Comment by Super-Rz** [comment]
官方后续是否有优化view.js过大的优化方案，不拆分物料库的情况

**Comment by eternalsky** [comment]
不拆分的情况下，view.js 的问题不可能得到根本性的解决

**Comment by Tourscholar** [comment]
> > 希望
> 
> > > > view.js 的规模，取决于你引入组件的规模，如果不希望引入过多的话，可以按需引入组件。
> > > 
> > > 
> > > 如何进行按需引入，有案例吗？ 目前物料库构建是将所有物料全部放入一个view.js，是可以按什么规则构建多个js文件吗
> > 
> > 
> > 如果是一个物料仓库，那就是一起加载的。如果希望分开多个加载，可以拆成多个物料库。然后根据情况，选择性加载。
> 
> 请问有啥字段或者api进行区分嘛

请问解决了吗 怎么做分包处理的？
