### ISSUE TITLE
[@alilc/lowcode-engine-ext] 如何调试 @alilc/lowcode-engine-ext 这个包

### ISSUE THREAD

**Issue by SageKwun** [alibaba/lowcode-engine#1915]
尝试了一下步骤：
参考 https://www.yuque.com/lce/doc/ulvlkz#l9SjH 在本地 @alilc/lowcode-engine-ext 中

1. 安装了 @alilc/build-plugin-alt
2. 参考文档修改了 build.json
3. 在根目录新建了 build.lowcode.js
4. npm run start
5. 打开 https://lowcode-engine.cn/demo/demo-general/index.html?debug

**Comment by hzd822** [comment]
https://github.com/alibaba/lowcode-engine-ext

**Comment by ming001** [comment]
我的意思是没办法debug lowcode-engine-ex源码的方法，我想去实时调试，看arraySetter里面逻辑和变量是什么意思

**Comment by hzd822** [comment]
代理调试  https://lowcode-engine.cn/site/docs/participate/prepare
{
  "proxy": [
    [
      "https://alifd.alicdn.com/npm/@alilc/lowcode-engine-ext@(.*)/dist/js/engine-ext.js", // https://www.sample.com/path1/path2/index.js
      "http://localhost:4008/js/engine-ext.js", // http://127.0.0.1:3000/index.js
    ],
    [
      "https://alifd.alicdn.com/npm/@alilc/lowcode-engine-ext@(.*)/dist/css/engine-ext.css", // https://www.sample.com/path1/path2/index.js
      "http://localhost:4008/css/engine-ext.css", // http://127.0.0.1:3000/index.js
    ],
  ],
}

**Comment by shiwofeiwo** [comment]
> 代理调试 https://lowcode-engine.cn/site/docs/participate/prepare { "proxy": [ [ "https://alifd.alicdn.com/npm/@alilc/lowcode-engine-ext@(._)/dist/js/engine-ext.js", // https://www.sample.com/path1/path2/index.js "http://localhost:4008/js/engine-ext.js", // http://127.0.0.1:3000/index.js ], [ "https://alifd.alicdn.com/npm/@alilc/lowcode-engine-ext@(._)/dist/css/engine-ext.css", // https://www.sample.com/path1/path2/index.js "http://localhost:4008/css/engine-ext.css", // http://127.0.0.1:3000/index.js ], ], }

链接找不到了，能否再发一个

**Comment by JackLian** [comment]
https://lowcode-engine.cn/site/docs/participate/
