### ISSUE TITLE
NextTable不能打开新增，编辑等操作页面

### ISSUE THREAD

**Issue by sunnyguohua** [alibaba/lowcode-engine#192]
## **详细描述 bug（必填）**
NextTable不能打开新增，编辑等操作页面

---

## **如何复现 bug？（必填，非常重要）**
1. 启动最新版本
2. 拖拽原子组件 NextTable到设计页面
3. 预览，点击新增，没有反应；也没有明确的方式可以设置调出新增对话框
<img width="902" alt="image" src="https://user-images.githubusercontent.com/6479673/160119205-a5ca3bd4-ca1a-4187-b2b3-b19e976a496a.png">

**Comment by LeoYuan** [comment]
需要你自己实现的~

拖入对话框，绑定显隐变量，点击新增 / 编辑，设置显隐变量~
