### ISSUE TITLE
物料开发中可以写meta.design.ts的文件，想问下在设计态中时如何使用，是否有相关文档的说明

### ISSUE THREAD

**Issue by qizilin** [alibaba/lowcode-engine#1921]
<img width="874" alt="image" src="https://user-images.githubusercontent.com/7828239/233792266-8224c4c4-0c1b-44ef-9c18-ceb4092532ec.png">

**Comment by eternalsky** [comment]
看下你说的是哪个文档

**Comment by qizilin** [comment]
> 看下你说的是哪个文档

就是官方物料中的这种文件，比如：
<img width="609" alt="image" src="https://user-images.githubusercontent.com/7828239/233793253-b4adbde2-c7ef-49ab-8860-5c0d0d00a151.png">
然后想问下，在设计态中是如何约定就是加载这些地址的？
这边有个实践是，通过url参数约定或者是根据当前角色（develop或者design），在 ` await material.setAssets(await injectAssets(assets));`  代码中，新增一个插件处理对应的 url 进行加载处理。想问下官方是否也是推荐这样去进行处理？

**Comment by eternalsky** [comment]
> > 看下你说的是哪个文档
> 
> 就是官方物料中的这种文件，比如： <img alt="image" width="609" src="https://user-images.githubusercontent.com/7828239/233793253-b4adbde2-c7ef-49ab-8860-5c0d0d00a151.png"> 然后想问下，在设计态中是如何约定就是加载这些地址的？ 这边有个实践是，通过url参数约定或者是根据当前角色（develop或者design），在 ` await material.setAssets(await injectAssets(assets));` 代码中，新增一个插件处理对应的 url 进行加载处理。想问下官方是否也是推荐这样去进行处理？

目前内部也是这样处理的。
