### ISSUE TITLE
如何定义 children 可以是多个类型？

### ISSUE THREAD

**Issue by StringKe** [alibaba/lowcode-engine#1925]
## **Describe the bug (required)** / **详细描述 bug（必填）**

`<Button />` 一个按钮组件他可以是

 ```jsx 
<Button>click</Button>
<Button><PlusIcon/></Button>
 ```

`configure.component.isContainer` 可以标记成，内部可被拽拖。但是非这种情况的下的不知道怎么处理了

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：
4. Scroll down to '....'
5. See error

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by daifuyang** [comment]
设置器里面增加一个children为stringSetter就可以了

**Comment by eternalsky** [comment]
isContainer 不就解决了是文本或者其他类型的问题了吗，如果是文本再拖入进来一个文本组件进插槽就可以了。

**Comment by StringKe** [comment]
> isContainer 不就解决了是文本或者其他类型的问题了吗，如果是文本再拖入进来一个文本组件进插槽就可以了。

```javascript
{
        componentName: 'MantineButton',
        title: '按钮',
        devMode: 'proCode',
        npm: {
            package: '@app/mantine-components',
            version: '0.0.0',
            exportName: 'MantineButton',
            main: 'libs/components/src/components/atomic/Buttons/Button/component.tsx',
            destructuring: true,
            subName: '',
        },
        props: [
            {
                name: 'children',
                propType: {
                    type: 'oneOfType',
                    value: ['string', 'number'],
                },
                title: {
                    label: '文本',
                    tip: 'children | 按钮内置文案',
                },
            },
        ],
        group: 'UI 组件',
        category: '按钮',
        configure: {
            component: {
                isContainer: true,
            },
            supports: {
                style: true,
            },
        },
        snippets: [
            {
                title: '按钮',
                schema: {
                    componentName: 'MantineButton',
                    props: {},
                    children: '按钮',
                },
            },
            {
                title: '自定义按钮',
                schema: {
                    componentName: 'MantineButton',
                    props: {},
                },
            },
        ],
    }
    
```

拽拖一个 `snippets[0]` 如果我拖进去一个组件 `props.children` 然后修改右侧设置面板中的 `children` 。

然后大纲书就对不上了。 实际行为上已经把拖进去的内容替换成修改的。

**Comment by eternalsky** [comment]
> > isContainer 不就解决了是文本或者其他类型的问题了吗，如果是文本再拖入进来一个文本组件进插槽就可以了。
> 
> ```js
> {
>         componentName: 'MantineButton',
>         title: '按钮',
>         devMode: 'proCode',
>         npm: {
>             package: '@app/mantine-components',
>             version: '0.0.0',
>             exportName: 'MantineButton',
>             main: 'libs/components/src/components/atomic/Buttons/Button/component.tsx',
>             destructuring: true,
>             subName: '',
>         },
>         props: [
>             {
>                 name: 'children',
>                 propType: {
>                     type: 'oneOfType',
>                     value: ['string', 'number'],
>                 },
>                 title: {
>                     label: '文本',
>                     tip: 'children | 按钮内置文案',
>                 },
>             },
>         ],
>         group: 'UI 组件',
>         category: '按钮',
>         configure: {
>             component: {
>                 isContainer: true,
>             },
>             supports: {
>                 style: true,
>             },
>         },
>         snippets: [
>             {
>                 title: '按钮',
>                 schema: {
>                     componentName: 'MantineButton',
>                     props: {},
>                     children: '按钮',
>                 },
>             },
>             {
>                 title: '自定义按钮',
>                 schema: {
>                     componentName: 'MantineButton',
>                     props: {},
>                 },
>             },
>         ],
>     }
>     
> ```
> 
> 拽拖一个 `snippets[0]` 如果我拖进去一个组件 `props.children` 然后修改右侧设置面板中的 `children` 。
> 
> 然后大纲书就对不上了。 实际行为上已经把拖进去的内容替换成修改的。

右侧面板的 children？，如果 isContainer 的情况下， children默认就是接受插槽里的内容了，在右边设置 children 没有效果的。

**Comment by StringKe** [comment]
我 props 里不是定义了 children 么，这个在右侧是可修改的。

**Comment by eternalsky** [comment]
> 我 props 里不是定义了 children 么，这个在右侧是可修改的。

isContainer 的情况下，children就已经被接管了，要么就是不要设置isContainer。

**Comment by StringKe** [comment]
如果要实现 
```jsx
<Button>click</Button>
<Button><PlusIcon/></Button>
```

其实最好的方案是定制两个组件，一个仅接受文本，一个接受任意内容对么？

**Comment by eternalsky** [comment]
> 如果要实现
> 
> ```js
> <Button>click</Button>
> <Button><PlusIcon/></Button>
> ```
> 
> 其实最好的方案是定制两个组件，一个仅接受文本(isContainer false)，一个接受任意内容(isContainer true)对么？

如果我做的话，我只会做 isContainer，另一个只是传一个文本组件进去就好了

**Comment by StringKe** [comment]
> > 如果要实现
> > ```js
> > <Button>click</Button>
> > <Button><PlusIcon/></Button>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 其实最好的方案是定制两个组件，一个仅接受文本(isContainer false)，一个接受任意内容(isContainer true)对么？
> 
> 如果我做的话，我只会做 isContainer，另一个只是传一个文本组件进去就好了

另一个可以锁定文本组件不被删除之类的规则么？

**Comment by eternalsky** [comment]
这个都是可以做的，可以在 dropin 或者组件 mount 的时机设置子组件不可删除，具体可以看文档。但文本不被删除的话，你怎么替换成其他的 element 呢？你的初衷不就是这里可以传任何元素。

**Comment by StringKe** [comment]
> 这个都是可以做的，可以在 dropin 或者组件 mount 的时机设置子组件不可删除，具体可以看文档。但文本不被删除的话，你怎么替换成其他的 element 呢？你的初衷不就是这里可以传任何元素。

我期望是这个配置项在 snappets 上，这样可以控制一个不允许修改，一个允许。

**Comment by eternalsky** [comment]
> > 这个都是可以做的，可以在 dropin 或者组件 mount 的时机设置子组件不可删除，具体可以看文档。但文本不被删除的话，你怎么替换成其他的 element 呢？你的初衷不就是这里可以传任何元素。
> 
> 我期望是这个配置项在 snappets 上，这样可以控制一个不允许修改，一个允许。

这个好像跟 snippets 的能力匹配不上，snippet 只是一个 schema 片段，不具备控制是否删除的能力。

**Comment by eternalsky** [comment]
还有一个方案就是配置 mixedSetter，不要 isContainer，手动设置 children，可以在 stringSetter 和 slotSetter 之间切换

**Comment by StringKe** [comment]
> > > 这个都是可以做的，可以在 dropin 或者组件 mount 的时机设置子组件不可删除，具体可以看文档。但文本不被删除的话，你怎么替换成其他的 element 呢？你的初衷不就是这里可以传任何元素。
> > 
> > 
> > 我期望是这个配置项在 snappets 上，这样可以控制一个不允许修改，一个允许。
> 
> 这个好像跟 snippets 的能力匹配不上，snippet 只是一个 schema 片段，不具备控制是否删除的能力。

可以提一个这样的需求么。

目前我暂时写两个组件完成吧。

**Comment by StringKe** [comment]
> 还有一个方案就是配置 mixedSetter，不要 isContainer，手动设置 children，可以在 stringSetter 和 slotSetter 之间切换

这样感觉不太好，需要一个额外的 props 字段

**Comment by eternalsky** [comment]
> 

如果 snippets 还带有控制能力的话，就不是 snippets 了，控制能力只能是在 configure 中定义，snippets 里只定义 schema 片段。
