### ISSUE TITLE
配置相关疑问

### ISSUE THREAD

**Issue by 123456dengting** [alibaba/lowcode-engine#1928]
如何控制根据年龄小于5的时候, 编辑按钮禁用

![image](https://user-images.githubusercontent.com/28246564/233301473-4b6d889e-f8cc-4fbc-941d-028b3d6609e0.png)

**Comment by JackLian** [comment]
这个跟组件强相关，首先得知道是哪个组件，然后看这个组件的api文档
另外本项目原则上不包括组件部分

**Comment by 123456dengting** [comment]
> 这个跟组件强相关，首先得知道是哪个组件，然后看这个组件的api文档 另外本项目原则上不包括组件部分

我看点到这个编辑按钮有个地方是可以设置是否禁用的表达式, 但是不知道怎么获取当前这一列的数据,所以表达式不知道怎么写

**Comment by LeoYuan** [comment]
看了下，当前「高级表格」没有提供该功能~

提供一点实现该功能的思路，在操作列配置中支持一个函数，函数签名设计成：
```js
function shouldHideAction(idx, rowData) {
  if (rowData.age < 5) return false;
  // something else
  return true;
}
```

相对应的组件内部渲染流程使用 idx / rowData 调用 shouldHideAction 即可~

**Comment by 123456dengting** [comment]
![image](https://user-images.githubusercontent.com/28246564/233817580-1a8386e6-1cb5-4129-8fb9-e62acbd6c109.png)
我在这个是否禁用这里绑定了一个函数,但是这个函数接受不到你这个函数李的idx,和rowData这两个参数,所以判断不了. 不知道你说的这个操作列是不是我这个意思

**Comment by 123456dengting** [comment]
> 看了下，当前「高级表格」没有提供该功能~
> 
> 提供一点实现该功能的思路，在操作列配置中支持一个函数，函数签名设计成：
> 
> ```js
> function shouldHideAction(idx, rowData) {
>   if (rowData.age < 5) return false;
>   // something else
>   return true;
> }
> ```
> 
> 相对应的组件内部渲染流程使用 idx / rowData 调用 shouldHideAction 即可~
我写过一个函数,在这个是否禁用里绑定一个函数,但是拿不到你这个函数里面的idx,和rowData这两个参数.所以没有办法判断里面的返回值
![image](https://user-images.githubusercontent.com/28246564/233817654-7de5b915-a32d-4e92-9097-dd64fb4d6f40.png)

**Comment by LeoYuan** [comment]
应该是组件该属性本身不支持绑定函数，而通用的绑定变量的「/」*不恰当地/错误地*提示可以绑定函数~

**Comment by 123456dengting** [comment]
> 应该是组件该属性本身不支持绑定函数，而通用的绑定变量的「/」_不恰当地/错误地_提示可以绑定函数~

那你说的这个函数是写在哪里的

**Comment by LeoYuan** [comment]
说了需要组件实现啊。。。我只是告诉你假如自己实现的思路

**Comment by 123456dengting** [comment]
> 说了需要组件实现啊。。。我只是告诉你假如自己实现的思路

就是需要去组件源码内部写这部分逻辑是吧,
