### ISSUE TITLE
低代码示例仓库lowcode-engine-demo里面的demo-antd-pro-with-formily示例运行不了

### ISSUE THREAD

**Issue by zjtnumber2** [alibaba/lowcode-engine#1929]
## 详细描述 bug（必填）

低代码示例仓库lowcode-engine-demo里面的demo-antd-pro-with-formily示例，运行报语法错误

---

## 如何复现 bug？（必填，非常重要）

详细复现步骤：
1. 下载lowcode-engine-demo仓库，选择main分支
2. 进入demo-antd-pro-with-formily文件夹，通过yarn安装依赖
3. 执行npm start, 控制台报错

##  预期行为（必填，非常重要）
可以正常运行，并能通过浏览器正常访问

---

## bug 截图（可选）
<img width="1378" alt="image" src="https://user-images.githubusercontent.com/5959721/233523339-6bbc45b8-ae9f-4bb1-a7d5-230bb90fc502.png">
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/5959721/233523360-f01520cd-78f9-423a-abfa-168e2bc6360f.png">

---

##  请提供如下信息（必填）
 - 低代码引擎版本   1.1.6
 - 低代码引擎扩展包版本 1.0.6-beta.23
 - 浏览器版本 chrome 112.0.5615.49
 - 其他物料 / 插件 / 工具链版本 参考lowcode-engine-demo仓库中demo-antd-pro-with-formily使用
 - 操作系统  win10/macOs 12.5

##  其他
  lowcode-engine-demo仓库中其他demo可以跑起来

**Comment by JackLian** [comment]
试试用npm安装呢

**Comment by zjtnumber2** [comment]
> 试试用npm安装呢

尝试了用yarn和npm都一样的问题。

**Comment by zjtnumber2** [comment]
另外还有在线demo，https://lowcode-engine.cn/demo/demo-antd-pro-with-formily/index.html，数据源面板选择默认的数据源info, 点编辑，界面显示渲染异常

**Comment by JackLian** [comment]
已修复
