### ISSUE TITLE
设计对话框会挡住原来的页面

### ISSUE THREAD

**Issue by sunnyguohua** [alibaba/lowcode-engine#193]
## **详细描述 bug（必填）**
设计对话框会挡住原来的页面，有没有更好的方式？

---

## **如何复现 bug？（必填，非常重要）**
1. 编辑页面时，拖入一个高级对话框，对话框悬浮在页面上
2. 在编辑完高级对话框以后，没法隐藏和编辑对话框下面的页面
<img width="1422" alt="image" src="https://user-images.githubusercontent.com/6479673/160131236-5f2176a9-d5b3-4db7-9fe9-65c0eedeccea.png">

**Comment by liujuping** [comment]
编辑完弹窗之后可以点击大纲树上的小眼睛进行隐藏，组件选中之后右上角也有小眼睛进行隐藏。
