### ISSUE TITLE
绑定事件的上下文问题，无法解除bind的限制

### ISSUE THREAD

**Issue by 1377023219** [alibaba/lowcode-engine#1933]
我有一个Table列表，里面会拖入一个Button，按钮有绑定一个onClick事件：
![image](https://user-images.githubusercontent.com/36667646/233581439-c8104a51-e7b6-4ae1-83cf-45ee71605043.png)

因为Table有多行数据，我想Button触发onClick时，onClick可以通过【this.record】拿到Button所在当行的数据。

所以我计划在Table中修改Button的this：
![image](https://user-images.githubusercontent.com/36667646/233582656-a6be67fd-b766-4084-8480-83f8b0932dd1.png)

【问题】后来发现引擎给button的onClick函数，是被bind过后的。导致Table无法通过call或apply修改this。

【诉求】有什么办法修改onClick函数的this，或者拿到在bind前的onClick函数。

**Comment by 1377023219** [comment]
@JackLian

**Comment by 1377023219** [comment]
暂时不考虑使用component.props.onClick(record)的方式传递，因为实际场景不止有Button，也不只有onClick等问题，this.xxx更符合需求

**Comment by JackLian** [comment]
没有，this不可以乱改，引擎给到的是执行所需的上下文，你改了那肯定会有别的影响
