### ISSUE TITLE
选项卡组件标签卡绑定变量时报错

### ISSUE THREAD

**Issue by hezhirong** [alibaba/lowcode-engine#1935]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

选项卡组件标签卡绑定变量时报错
--- 

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

1、打开[demo](https://lowcode-engine.cn/demo/demo-general/index.html)
2、搜索【选项卡】组件拖拽进编辑器并选中
3、选择右侧边栏的属性选择卡，点击【标签项】右上角的【切换设置器】中的【变量输入】
4、切换后再次点击【标签项】对应的输入框，会导致输入框消失并报错。
---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

选项卡的【标签项】可以正常绑定变量
---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

![image](https://user-images.githubusercontent.com/4240262/233602836-8922e348-ddcc-409e-a6e0-976c6eeae449.png)
---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by eternalsky** [comment]
duplicate https://github.com/alibaba/lowcode-engine/issues/1716
