### ISSUE TITLE
自定义物料下的自定义设置器不需要显示变量绑定，通过supportVariable: false无法隐藏

### ISSUE THREAD

**Issue by daifuyang** [alibaba/lowcode-engine#1938]
## **Describe the bug (required)** / **详细描述 bug（必填）**

自定义物料下的自定义设置器不需要显示变量绑定，通过supportVariable: false无法隐藏

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
meta.js
configure: {
    props: [
      {
        name: 'test',
        title: {
          label: '测试',
          tip: '',
        },
        setter: DataListSetter, // 自定义的设置器
        supportVariable: false,
        defaultValue:'',
      },
    ],
}

**Comment by zzuer** [comment]
这个我之前好像遇到过，你看下你demo项目里src下的index.ts文件，有个supportVariableGlobally的配置，把它改成false应该就行了

**Comment by daifuyang** [comment]
@zzuer 不行，我试过了

**Comment by daifuyang** [comment]
supportVariableGlobally这个是针对全部页面的,我需要的是默认显示，不需要隐藏

**Comment by LeoYuan** [comment]
> supportVariableGlobally这个是针对全部页面的,我需要的是默认显示，不需要的在隐藏

这个我看了下逻辑，是有 bug 的，后面我提个 PR 修复下~
