### ISSUE TITLE
将antd-mobile组件库转成低代码组件报错

### ISSUE THREAD

**Issue by czxzc** [alibaba/lowcode-engine#1940]
问题：如何将antd-mobile组件库转化成低代码组件，从而可以在低代码引擎中作为物料组件使用？

环境信息：
node版本：v16.18.0
os信息：Mac OS Monterey 12.4

复现步骤：
1. 拉取antd-mobile的代码到本地；https://github.com/ant-design/ant-design-mobile
2. npm install --force, 装依赖包；
3. 根据[现存组件低代码化](https://lowcode-engine.cn/site/docs/guide/expand/editor/material#%E7%8E%B0%E5%AD%98%E7%BB%84%E4%BB%B6%E4%BD%8E%E4%BB%A3%E7%A0%81%E5%8C%96)文档指示，安装好依赖包和相关配置；
![image](https://user-images.githubusercontent.com/36975789/233822448-ca972777-e841-4f85-b16e-414678d478a9.png)
4. npm run lowcode:build, 报错，提示如下：
![image](https://user-images.githubusercontent.com/36975789/233822492-c64718d3-fca4-4eab-826e-56b4fb5425b4.png)

**Comment by eternalsky** [comment]
请提供可以复现的代码包和仓库地址。

**Comment by czxzc** [comment]
复现地址：https://github.com/czxzc/ant-design-mobile

**Comment by eternalsky** [comment]
<img width="736" alt="截屏2023-06-13 下午2 16 18" src="https://github.com/alibaba/lowcode-engine/assets/8038928/8b1cf4ef-e85e-4e57-ae27-c4a067e1910e">
我这边测试，可以正常 build。猜测可能的原因是因为你使用了 --force 来强制安装 peer 依赖，导致依赖不正确导致的。建议改用 --legacy-peer-desp

**Comment by chenxlkamino** [comment]
> <img alt="截屏2023-06-13 下午2 16 18" width="736" src="https://user-images.githubusercontent.com/8038928/245369509-8b1cf4ef-e85e-4e57-ae27-c4a067e1910e.png"> 我这边测试，可以正常 build。猜测可能的原因是因为你使用了 --force 来强制安装 peer 依赖，导致依赖不正确导致的。建议改用 --legacy-peer-desp

改用npm i --legacy-peer-deps 安装，我这也不行。看了下好像是@alib/build-scripts依赖的webpack版本为4，但是antd-mobile 依赖的webpack版本为5 冲突了

**Comment by eternalsky** [comment]
组件库是不会依赖 webpack 的。

**Comment by chenxlkamino** [comment]
您的邮件已经收到，我会尽快给您回复-------陈孝亮
祝您生活愉快！

**Comment by chenxlkamino** [comment]
您的邮件已经收到，我会尽快给您回复-------陈孝亮
祝您生活愉快！
