### ISSUE TITLE
事件绑定：内置函数用法

### ISSUE THREAD

**Issue by llllllllr** [alibaba/lowcode-engine#1946]
查看多个组件都无法点击**内置函数**，在文档没找到相关内容。辛苦帮忙解答一下内置函数的配置在哪里以及含义，感谢～

![image](https://user-images.githubusercontent.com/35605494/234192264-bf77b92a-ad91-4415-a81a-2cc09d56dc82.png)

**Comment by JackLian** [comment]
目前内置函数功能在demo中无法提供，如果想体验可以在lab平台 https://lab.lowcode-engine.cn/#/ 看到
