### ISSUE TITLE
物料开发环境如何使用react-router

### ISSUE THREAD

**Issue by Great-old-one** [alibaba/lowcode-engine#1952]
##  **详细描述 bug（必填）**

使用官方物料开发脚手架搭建物料开发环境，将包含withRouter的组件拖入编辑器时报错
![image](https://user-images.githubusercontent.com/26474262/234446466-0b6ff7c7-ae9f-4fdc-90ae-5a1719adb75a.png)

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

详细复现步骤：
1. 在源码仓库安装 @alib/build-scripts、@alifd/build-plugin-lowcode
2. 通过npm run lowcode:dev启动开发环境
3. 向编辑器中拖入含有withRouter组件的时候出现报错

---
##  **预期行为（必填，非常重要）**
 - 组件正常渲染
 - 提供解决方案或文档

---

##  **bug 截图（可选）**
![image](https://user-images.githubusercontent.com/26474262/234447305-dee0e1c6-8420-4cdc-8fd7-1b9fd10d5ab8.png)
![image](https://user-images.githubusercontent.com/26474262/234447345-cd774ed8-d3a8-4b35-b154-dc617a2e1602.png)
<img width="1018" alt="image" src="https://user-images.githubusercontent.com/26474262/234447480-99509d5c-cc6c-4f1c-96c4-3a1ec70d22f5.png">

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - "@alib/build-scripts": "^0.1.32"
 - "@alifd/build-plugin-lowcode": "^0.3.8"
 - "react": "^16.8.6"
 - "react-dom": "^16.8.6",
 -  "react-router": "^5.0.1"
 - "react-router-dom": "^5.0.1"
 -  "typescript": "4.6.3"
 - node:14.16.1
 - npm: 6.14.12

    

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**

**Comment by eternalsky** [comment]
一般组件是不处理路由问题的，页面里才会真正的管控路由。 通常如果点击某处需要跳转，一般是以回调函数 props 的形式通知给页面，然后由页面级做好路由跳转。

**Comment by eightHundreds** [comment]
其实官方的react-simulator-renderer内部已经有react-router(external的), 是在最外层包了一层<Router> 
我猜测没效果是因为, 你的组件内用的react-router和react-simulator-renderer内部的不是同一个包

我自己的做法是

![image](https://user-images.githubusercontent.com/18695431/234463341-24c78c14-9bfd-4d61-9161-71ea14b9084d.png)

自己开发一个Layout组件(放到物料库里), 设计器会自动渲染这个组件包裹simulator

**Comment by Great-old-one** [comment]
> 其实官方的react-simulator-renderer内部已经有react-router(external的), 是在最外层包了一层`<Router>` 我猜测没效果是因为, 你的组件内用的react-router和react-simulator-renderer内部的不是同一个包
> 
> 我自己的做法是
> 
> ![image](https://user-images.githubusercontent.com/18695431/234463341-24c78c14-9bfd-4d61-9161-71ea14b9084d.png)
> 
> 自己开发一个Layout组件(放到物料库里),Layout组件配一堆ConfigProvider,Router什么的, 最后配置在ProjectSchema里, 设计器会自动渲染这个组件包裹simulator
> 
> 当然这个Layout只能用在设计态

感谢，通过这种方法能解决我的问题。希望官方能尽快完善相应文档或提供更好的解决方案，比如在物料开发插件中提供相应配置。
