### ISSUE TITLE
咨询：可否跳过发包直接使用物料扩展进行组件开发、页面出码？

### ISSUE THREAD

**Issue by Honjaychang** [alibaba/lowcode-engine#1956]
在调研低代码引擎是否可以接入第三方组件库的过程中，发现 `npm init @alilc/element your-material-name` 生成的项目具备和低代码引擎demo一样的能力。如果只依赖自己开发的组件，并在 `your-material-name` 开发生成对应组件的描述文件，是否可以将`your-material-name` 当作引擎来使用进行页面开发出码？ 这样做和使用官方推荐的使用引擎+资产包导入开发模式相比有哪些缺点或潜在的问题呢？

另外：是否有方法将执行 `npm run lowcode:dev` 后的页面作为入口文件引入到其他单页应用的entry中呢？

**Comment by eternalsky** [comment]
lowcode:dev 只用于开发组件，不具备 production 能力。

**Comment by eternalsky** [comment]
这不是哪些缺点或潜在问题，而是 lowcode:dev 的承诺只是用于开发组件，任何用于生产环境的行为都不是官方认同和提供维护支持的。

**Comment by Honjaychang** [comment]
好的 感谢答疑～
