### ISSUE TITLE
lowcode-engine-ext1.0.6版本下arraySetter问题

### ISSUE THREAD

**Issue by 501981732** [alibaba/lowcode-engine#1958]
## 详细描述 bug**
目前我在用ant开发类似fusion-ui高级表单,发现配置表单项时会发生数据混乱。经排查在lowcode-engine-ext@1.0.6-beta.25下 会复现，lowcode-engine-ext@1.0.5没有问题。

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1. 打开 [[demo](http://lowcode-engine.cn/demo)；](https://lowcode-engine.cn/demo/demo-general/index.html)。
2. 拖拽高级表格。
3. 新增 6个表单项。
4. 修改第一个表单项内容后，其余三个消失，修改中间几个表单项内容，表单项也会混乱。

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
预期能正确修改表单项
---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: 1.1.7-beta.11
 - AliLowCodeEngineExt version: v1.0.6-beta.25

**Comment by 501981732** [comment]
![20230426175958_rec_](https://user-images.githubusercontent.com/20636097/234541827-f8af31b8-ad0f-4f9a-aa4b-c62a80fa2f0b.gif)

**Comment by eightHundreds** [comment]
我是fork后自己改造的，真实原因非常难找，只能用临时方案.

因为ArraySetter本身存在一些奇奇怪怪的，负负得正的写法。而且这个问题原因可能是SettingFieldView等底层模块自身bug。

<img width="705" alt="企业微信截图_91397533-f03d-4597-955b-6c4d6c3a0004" src="https://user-images.githubusercontent.com/18695431/236631789-b2107e46-1e3d-4cf6-a30a-c3e6cdccf037.png">
<img width="553" alt="企业微信截图_416caa4f-a7e6-4b7a-8f13-df0f7b49e83c" src="https://user-images.githubusercontent.com/18695431/236631796-eff2850a-7fab-49f7-93c1-d1b6e7cb26af.png">
