### ISSUE TITLE
关于自由容器组件的问题

### ISSUE THREAD

**Issue by ChiZng** [alibaba/lowcode-engine#1966]
### 1. 把组件拖入自由容器组件中，拖入组件位置问题。
1. 被拖入组件的位置经常不是鼠标松开时的位置，有时候是自由容器组件的左上角，有时候时左边，反正就是位置很不确定。没有找到规律。
2. 在自由容器中拖入新的组件，新拖入的组件经常会导致之前已经拖入容器组件中的组件位置发生变化。
### 2. 自由容器配置中层级是做什么的，有什么文档说明吗？好像是自由容器中新增一个组件就会自动新加一个配置
![image](https://user-images.githubusercontent.com/27946984/234847536-ca9457a8-665c-4f84-a3f9-6ecd42f712a2.png)

反正就是当前这个自由容器布局很不好用。我想使用这个组件有什么好的建议，比如等几天官方会发新的版本或者就当前版本使用有什么版本避免这些问题。

### 3. 自由容器中关于辅助线或者刻度尺的需求
这个组件官方近期会考虑增加这个功能吗？
![image](https://user-images.githubusercontent.com/27946984/234848729-cfad7705-2ba0-449e-9c36-f20a5defe1c8.png)

**Comment by eternalsky** [comment]
第二个问题可以回答一下，层级对应的就是 css 里的 z-index，用于设定当组件重叠时谁显示在谁上方的问题。

**Comment by guohejun** [comment]
官方有自由容器组件了吗，怎么用的
