### ISSUE TITLE
BUG：demo 示列中图表切换根容器后无限刷新

### ISSUE THREAD

**Issue by zhang8043** [alibaba/lowcode-engine#197]
## 详细描述 bug

demo 示列中图表切换根容器后，图表高度为0,并无限刷新，每次刷新增加高度。

---

## 如何复现 bug？

![1648351791878_F82DFA22-1E8D-4cc9-93E0-97877073A713](https://user-images.githubusercontent.com/31415437/160265447-64a46e78-c876-41d2-abb1-f07d3f516b5f.png)

---

**Comment by liujuping** [comment]
看了一下，引擎层面没有触发组件渲染，这块可能是物料的 bug，@mark-ck 看看。

**Comment by lijianmincn** [comment]
我在官网综合场景测试的也是同样的问题。
进入首页，点击“add section”，再将图表（柱状、折线、饼形……）拖入容器中，图表会不断刷新增高。
或者，拖入容器组件，将容器剪成两块，再将图表（柱状、折线、饼形……）拖入其中一块，图表也会不断刷新增高。

**Comment by eternalsky** [comment]
这是由于自然布局和图表合在一起产生的反应。因为布局中的容器高度是随内容撑高，而图表有 autofit 的特性，会观察到容器高度变化后重新计算自己高度。两者互相反应产生了问题，如果设置了容器定高则不会有这个问题，fusion-ui 2.1.0 开放了 autofit 和 height 的配置，可以自行配置完成。
