### ISSUE TITLE
开发物料引用静态资源（图片）时，编辑器加载资源路径异常

### ISSUE THREAD

**Issue by 947291135** [alibaba/lowcode-engine#1970]
## **Describe the bug (required)** / **详细描述 bug（必填）**
开发物料组件的时候，需用到一些图片资源，如果图片过小则会转base 64，如果图片过大则会是相对路径；
1.图片过大时，在编辑器中调试发现img src 为物料开发相对路径
2.怎么样在build.plugin.js中调整转换base64中图片大小限制（尝试使用url-loader失败）

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
1.物料代码使用图片资源
<img width="745" alt="微信截图_20230428172200" src="https://user-images.githubusercontent.com/26854734/235109230-bd92d763-0965-4f87-898b-f3b757722e6e.png">
2.在低代码平台图片资源路径错误
<img width="768" alt="test" src="https://user-images.githubusercontent.com/26854734/235109856-7c4a6d66-cfd5-4320-ac36-3077101f1538.png">

Steps to reproduce the behavior: / 详细复现步骤：

---
1. 开发物料时引用静态资源图片；
2. 物料打包后低代码平台使用该物料；
3. 物料组件展示图片异常；
4. 图片异常原因为请求路径错误，加载为相对路径，；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
1.如果解决路径问题
2.怎么调整图片转化base64时希望调整最小文件大小转化如：
![image](https://user-images.githubusercontent.com/26854734/235110897-e65bff06-eb1f-46a5-aa8a-2632eb79265a.png)
3. url-loader 设置最小limit 无发生效
---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: 最新版本
 - Chrome 版本 112.0.5615.138

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

**Comment by eternalsky** [comment]
这其实是不同项目打包资源时的策略问题，再怎么调整参数，也是存在有些资源是通过 url ，有些资源是 base64，最好的办法还是引用的资源先上传至 cdn，再在组件里引用。

**Comment by 947291135** [comment]
> 

暂时不通过cdn方式，因为物料在频繁修改，会给覆盖
![image](https://user-images.githubusercontent.com/26854734/236594701-88e4403b-fa89-4875-ad9d-9a097c194ad2.png)
想在问下通过修改build.json 中url-loader limit 配置不会覆盖吗，图片都在50KB以下 还是没被转base64

**Comment by eternalsky** [comment]
如果你的修改正确的话，是可以覆盖的。
