### ISSUE TITLE
demo-antd-pro-with-formily示例运行报错

### ISSUE THREAD

**Issue by ddsomav8** [alibaba/lowcode-engine#1980]
## **Describe the bug (required)** / **详细描述 bug（必填）**

低代码示例仓库lowcode-engine-demo里面的demo-antd-pro-with-formily示例，运行报语法错误。

已使用npm多次进行安装

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

详细复现步骤：

下载lowcode-engine-demo仓库，选择main分支
进入demo-antd-pro-with-formily文件夹，通过yarn安装依赖
执行npm start, 控制台报错

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
可以正常运行，并能通过浏览器正常访问
---

## **Screenshots (optional)** / **bug 截图（可选）**
![image](https://user-images.githubusercontent.com/34079919/236249233-a2c8a624-0aa9-4268-bd2f-a95ce69c326b.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
低代码引擎版本 1.1.6
低代码引擎扩展包版本 1.0.6-beta.23
浏览器版本 chrome 112.0.5615.49
其他物料 / 插件 / 工具链版本 参考lowcode-engine-demo仓库中demo-antd-pro-with-formily使用
操作系统 win10/macOs 12.5

**Comment by JackLian** [comment]
试试删掉nodemodules，用 npm install (不用yarn）

**Comment by ddsomav8** [comment]
试过了，还是有问题

**Comment by wdlnydhcg** [comment]
+1

**Comment by JackLian** [comment]
拉一下最新代码看看，刚加了个resolution

**Comment by ddsomav8** [comment]
目前排查下来是monaco-editor/react和monaco-editor/loader版本不匹配，现在是通过人工手动安装"@monaco-editor/react": "^4.4.5"版解决的。

**Comment by wdlnydhcg** [comment]
> monaco-editor/loader的版本是什么呢

**Comment by wdlnydhcg** [comment]
> >

感谢，确实降低版本到4.4.5就可以了
