### ISSUE TITLE
官网antd-pro例子里，导航菜单组件报错

### ISSUE THREAD

**Issue by CheesySir** [alibaba/lowcode-engine#1982]
进入官网demo页面，选择如下demo
![image](https://user-images.githubusercontent.com/35730201/236406242-b5839e2e-5270-4439-9364-22ab04f11ba2.png)

选择导航菜单组件
![image](https://user-images.githubusercontent.com/35730201/236406116-33983722-578d-4d4a-a3db-96a0b2542bf9.png)

该demo中以及目前自己项目中使用的antd 是>4.23.0版本，导致这个问题，是否更新下antd-material的逻辑，解决下这个问题。选择antd 4.19.4的版本是正常的。

**Comment by JackLian** [comment]
https://github.com/seada-low-code/lowcode-ecology/tree/main/packages/antd-materials
这个要这里提下issue，是社区大佬贡献的
