### ISSUE TITLE
TAB选项卡出码错误，修复后如何集成到lowCode的demo中

### ISSUE THREAD

**Issue by frogo** [alibaba/lowcode-engine#1985]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---
![218365909-dfec123d-c6c9-4a5c-b18c-5dd46f3d6c41](https://user-images.githubusercontent.com/3413313/236434128-590d95a8-6988-4903-bf27-ffeb3cd8eb09.jpg)
之前提了一个Issue (https://github.com/alibaba/lowcode-engine/issues/1565)
后来大佬给我了一个解答，似乎是这个问题解决了

当 componentName 跟所属模块的 exportName 和 subName 毫无关系时，如此例：

componentName: Tab.Item
exportName: TabContainer
subName: Item

修复方式有两种：

将 componentName 设置成 exportName + subName；
在出码中，特别处理上面的情况，个人觉得 1 这种约束是合理的，没有额外成本，建议此次先按 1 处理；
（https://github.com/alibaba/lowcode-materials/pull/51）

我看到了代码的修复和提交（https://github.com/alibaba/lowcode-materials/pull/51/commits/52061fe7dd85285ce321fcbb534233155bbae433）

但是不知道如何才能让https://lowcode-engine.cn/demo/demo-general/index.html 这个页面拖拽一个选项卡，出码不报错

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by frogo** [comment]
我好像知道怎么更新了，demo-general下面有个资产包，引入了demo-general/src/services/assets.json这个文件，然后把里面所有 @alifd/fusion-ui@2.0.0改成2.0.1
![image](https://user-images.githubusercontent.com/3413313/236437644-8c14d91e-e4f2-4cf1-84ed-be390da9af97.png)
我先去验证下
![image](https://user-images.githubusercontent.com/3413313/236437331-5d97a7a8-6c6e-4f6b-8cee-ef23479e7ba8.png)

**Comment by frogo** [comment]
> 我好像知道怎么更新了，demo-general下面有个资产包，引入了demo-general/src/services/assets.json这个文件，然后把里面所有 @alifd/fusion-ui@2.0.0改成2.0.1 ![image](https://user-images.githubusercontent.com/3413313/236437644-8c14d91e-e4f2-4cf1-84ed-be390da9af97.png) 我先去验证下 ![image](https://user-images.githubusercontent.com/3413313/236437331-5d97a7a8-6c6e-4f6b-8cee-ef23479e7ba8.png)

好像不行，改了以后

**Comment by LeoYuan** [comment]
怎么不行？加载的资源是 2.0.1 版本了么？

**Comment by frogo** [comment]
> 怎么不行？加载的资源是 2.0.1 版本了么？

对，我在demo-general/src/services/assets.json 这个json中凡是涉及到fusion-ui的版本都改成2.0.1了，但是不生效

**Comment by frogo** [comment]
> > 怎么不行？加载的资源是 2.0.1 版本了么？
> 
> 对，我在demo-general/src/services/assets.json 这个json中凡是涉及到fusion-ui的版本都改成2.0.1了，但是不生效

{
  "packages": [
    {
      "package": "moment",
      "version": "2.24.0",
      "urls": [
        "https://g.alicdn.com/mylib/moment/2.24.0/min/moment.min.js"
      ],
      "library": "moment"
    },
    {
      "package": "lodash",
      "library": "_",
      "urls": [
        "https://g.alicdn.com/platform/c/lodash/4.6.1/lodash.min.js"
      ]
    },
    {
      "title": "fusion组件库",
      "package": "@alifd/next",
      "version": "1.26.4",
      "urls": [
        "https://g.alicdn.com/code/lib/alifd__next/1.26.4/next.min.css",
        "https://g.alicdn.com/code/lib/alifd__next/1.26.4/next-with-locales.min.js"
      ],
      "library": "Next"
    },
    {
      "title": "NextTable",
      "package": "NextTable",
      "version": "1.0.1",
      "urls": [
        "https://g.alicdn.com/fusion-platform/pro-table/1.0.1/next-table.js",
        "https://g.alicdn.com/fusion-platform/pro-table/1.0.1/next-table.css"
      ],
      "library": "NextTable"
    },
    {
      "package": "@alilc/lowcode-materials",
      "version": "1.0.7",
      "library": "AlilcLowcodeMaterials",
      "urls": [
        "https://alifd.alicdn.com/npm/@alilc/lowcode-materials@1.0.7/dist/AlilcLowcodeMaterials.js",
        "https://alifd.alicdn.com/npm/@alilc/lowcode-materials@1.0.7/dist/AlilcLowcodeMaterials.css"
      ],
      "editUrls": [
        "https://alifd.alicdn.com/npm/@alilc/lowcode-materials@1.0.7/build/lowcode/view.js",
        "https://alifd.alicdn.com/npm/@alilc/lowcode-materials@1.0.7/build/lowcode/view.css"
      ]
    },
    {
      "package": "@alifd/layout",
      "version": "2.0.12",
      "library": "AlifdLayout",
      "urls": [
        "https://alifd.alicdn.com/npm/@alifd/layout@2.0.12/dist/AlifdLayout.js",
        "https://alifd.alicdn.com/npm/@alifd/layout@2.0.12/dist/AlifdLayout.css"
      ],
      "editUrls": [
        "https://alifd.alicdn.com/npm/@alifd/layout@2.0.12/build/lowcode/view.js",
        "https://alifd.alicdn.com/npm/@alifd/layout@2.0.12/build/lowcode/view.css"
      ]
    },
    {
      "package": "@alifd/fusion-ui",
      "version": "2.0.1",
      "library": "AlifdFusionUi",
      "urls": [
        "https://alifd.alicdn.com/npm/@alifd/fusion-ui@2.0.1/dist/AlifdFusionUi.js",
        "https://alifd.alicdn.com/npm/@alifd/fusion-ui@2.0.1/dist/AlifdFusionUi.css"
      ],
      "editUrls": [
        "https://alifd.alicdn.com/npm/@alifd/fusion-ui@2.0.1/build/lowcode/view.js",
        "https://alifd.alicdn.com/npm/@alifd/fusion-ui@2.0.1/build/lowcode/view.css"
      ]
    }
  ],
  "components": [
    {
      "exportName": "AlilcLowcodeMaterialsMeta",
      "npm": {
        "package": "@alilc/lowcode-materials"
      },
      "url": "https://alifd.alicdn.com/npm/@alilc/lowcode-materials@1.0.7/build/lowcode/meta.js",
      "urls": {
        "default": "https://alifd.alicdn.com/npm/@alilc/lowcode-materials@1.0.7/build/lowcode/meta.js",
        "design": "https://alifd.alicdn.com/npm/@alilc/lowcode-materials@1.0.7/build/lowcode/meta.design.js"
      }
    },
    {
      "exportName": "AlifdLayoutMeta",
      "npm": {
        "package": "@alifd/layout",
        "version": "2.0.12"
      },
      "url": "https://alifd.alicdn.com/npm/@alifd/layout@2.0.12/build/lowcode/meta.js",
      "urls": {
        "default": "https://alifd.alicdn.com/npm/@alifd/layout@2.0.12/build/lowcode/meta.js"
      }
    },
    {
      "exportName": "AlifdFusionUiMeta",
      "npm": {
        "package": "@alifd/fusion-ui"
      },
      "url": "https://alifd.alicdn.com/npm/@alifd/fusion-ui@2.0.1/build/lowcode/meta.js",
      "urls": {
        "default": "https://alifd.alicdn.com/npm/@alifd/fusion-ui@2.0.1/build/lowcode/meta.js",
        "design": "https://alifd.alicdn.com/npm/@alifd/fusion-ui@2.0.1/build/lowcode/meta.design.js"
      }
    }
  ],
  "sort": {
    "groupList": [
      "精选组件",
      "原子组件",
      "低代码组件"
    ],
    "categoryList": [
      "基础元素",
      "布局容器类",
      "表格类",
      "表单详情类",
      "帮助类",
      "对话框类",
      "业务类",
      "通用",
      "引导",
      "信息输入",
      "信息展示",
      "信息反馈"
    ]
  },
  "groupList": [
    "精选组件",
    "原子组件",
    "低代码组件"
  ],
  "ignoreComponents": {}
}
这是修改后的json文件，大佬帮忙看看

**Comment by LeoYuan** [comment]
好的，我复现了，我再看看~

*题外话，兄弟看一下 [code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)，能更好得看代码。。。*

**Comment by frogo** [comment]
> 好的，我复现了，我再看看~
> 
> _题外话，兄弟看一下 [code blocks](https://docs.github.com/en/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks)，能更好得看代码。。。_

好的袁哥，上面代码已更新。

**Comment by frogo** [comment]
> fusion-ui 已经发布新版 2.0.2 了，你可以直接使用~
> 
> 官方 demo 还要等 [PR](https://github.com/alibaba/lowcode-demo/pull/130) 合并以及服务重启~
> 
> @frogo
非常感谢皓哥，已经验证可以工作了！给大佬点赞

**Comment by LeoYuan** [comment]
看下是不是 fusion-ui 的样式没有引入？

**Comment by frogo** [comment]
> 看下是不是 fusion-ui 的样式没有引入？
在出码后的工程中public/indexhtml中加了<link href="https://g.alicdn.com/code/lib/alifd__next/1.23.24/next.min.css" rel="stylesheet">，OK了。
![1683885447495](https://github.com/alibaba/lowcode-engine/assets/3413313/7b538621-81a6-4ece-a343-933fb3e45c9d)
