### ISSUE TITLE
antd__WEBPACK_IMPORTED_MODULE_4__.Form.useFormInstance is not a function

### ISSUE THREAD

**Issue by QiYunMeng1126** [alibaba/lowcode-engine#1986]
我是用这种方式初始化物料项目
![1683281289649](https://user-images.githubusercontent.com/13884135/236434136-616fad41-7dc1-40ef-8260-2d35f41c4b27.jpg)

引入了 pro-components  对应的版本 如下
    "@ant-design/pro-components": "^2.3.5",
    "antd": "^5.4.6",

异常错误明细
![image](https://user-images.githubusercontent.com/13884135/236435247-3ada3143-73b4-457b-aff0-2190041fdc12.png)

错误原因
Form. useFormInstance  这个方法 antd 4.20.0 版本支持
yarn lowcode:dev  / yarn build:dev  之后, .tmp/build  目录下 index.js  antd 是4.17.3
![1683281190089](https://user-images.githubusercontent.com/13884135/236436065-f1a6b85a-a180-4796-8cff-72180b29f884.jpg)

求助:
编译的时候怎么设置.tmp/build  目录下的 index.js 中 antd 的版本.

**Comment by beautiful-boyyy** [comment]
你build.lowcode.js里面的antd版本是多少

**Comment by QiYunMeng1126** [comment]
build.lowcode.js   代码如下
![image](https://user-images.githubusercontent.com/13884135/236590880-24d90f23-5114-4de1-af82-3bebe0be8857.png)

build.json 代码如下
![image](https://user-images.githubusercontent.com/13884135/236590967-9ebef2d8-8e3d-466a-8b28-cb56979334b1.png)



补充: 
编译之后的.temp/build 目录下的 index.jsx 中的antd  信息是否来源这里
![image](https://user-images.githubusercontent.com/13884135/236590926-d0dfcf8e-ac84-4a6f-b0d7-286c6258fbe5.png)

**Comment by beautiful-boyyy** [comment]
> build.lowcode.js 代码如下 ![image](https://user-images.githubusercontent.com/13884135/236590880-24d90f23-5114-4de1-af82-3bebe0be8857.png)
> 
> build.json 代码如下 ![image](https://user-images.githubusercontent.com/13884135/236590967-9ebef2d8-8e3d-466a-8b28-cb56979334b1.png)
> 
> 补充: 编译之后的.temp/build 目录下的 index.jsx 中的antd 信息是否来源这里 ![image](https://user-images.githubusercontent.com/13884135/236590926-d0dfcf8e-ac84-4a6f-b0d7-286c6258fbe5.png)

有个 builtinAssets字段，你参照官方物料库里面build.lowcode.js文件的写法改antd版本，不过最终还是以demo项目里面用的为准

**Comment by QiYunMeng1126** [comment]
![image](https://user-images.githubusercontent.com/13884135/236612149-55477fb7-3eb9-4246-a39b-0858b0a72b84.png)
已解决, 感谢!!!!
