### ISSUE TITLE
设置面板-设置器未正常加载

### ISSUE THREAD

**Issue by Honjaychang** [alibaba/lowcode-engine#1988]
引擎项目基于 https://github.com/alibaba/lowcode-demo/blob/main/demo-custom-initialization/src/index.tsx 创建。

将 `public/index.ejs` 作为 `njk` 模版，将 `src/index.tsx` 作为入口文件应用在自己的业务中。

![截图](https://user-images.githubusercontent.com/48197745/236606169-689a2617-a87d-43ef-97d9-981597fa8214.png)

本地运行后功能正常，控制台无报错，但发现右侧设置器未正常显示，无法编辑（未使用官方提供的 `build-scripts start` 启动项目）。这个有什么排查思路吗？

**Comment by LeoYuan** [comment]
检查一下 `setters.getSetter('YourSetterName')`（单个） / `setters.getSettersMap()`（全量） 看看你的 setter 是否注册成功了~

**Comment by Honjaychang** [comment]
> 检查一下 `setters.getSetter('YourSetterName')`（单个） / `setters.getSettersMap()`（全量） 看看你的 setter 是否注册成功了~

感谢答疑～

我在 `plugin-default-setters-registry` 目录下测试了下，应该是注册成功了。还有其他排查思路吗？
![image](https://github.com/alibaba/lowcode-engine/assets/48197745/ac72f92a-acd1-4558-a33a-970e5e342f77)


![image](https://github.com/alibaba/lowcode-engine/assets/48197745/3b5dd07e-ea31-4952-8f07-126ad2424895)

**Comment by LeoYuan** [comment]
看看这几个位置有没有 React 组件的渲染，针对性看下具体用了哪个 setter 以及 setter 的样式，甚至在 js 里打个断点看看渲染代码

![image](https://github.com/alibaba/lowcode-engine/assets/1195765/a25b44b9-2495-4c8f-bb3a-04b8ac36eda0)

**Comment by LeoYuan** [comment]
再不行，就只能提供一个简单的可复现 demo 了，这样排查问题效率是低了点😄

**Comment by liujuping** [comment]
由于没有复现环境，这个 issue 暂时关闭，有需要再重新打开。
