### ISSUE TITLE
组件面板-效果图展示太小无法看清

### ISSUE THREAD

**Issue by lhbxs** [alibaba/lowcode-engine#199]
建议修改 img 图片样式

width: 100%;
height: 100%;
obj-fit: contain;

父级容器 width:56px 去除

**Comment by liujuping** [comment]
组件面板不同的低代码平台要求不一样，可以根据自己的需求进行定制。

**Comment by liujuping** [comment]
https://github.com/alibaba/lowcode-plugins/tree/main/packages/plugin-components-pane
