### ISSUE TITLE
使用自定义的属性设置器，会出现设计器未即时渲染的问题

### ISSUE THREAD

**Issue by wojiaofengzhongzhuifeng** [alibaba/lowcode-engine#1990]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

编写自定义的复杂属性设置器，在使用自定义设置器设置属性的时候，设计器没有即时渲染，需要手动触发设计器的渲染，期待能即时渲染；

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：
1. git clone https://github.com/wojiaofengzhongzhuifeng/question-lowcode
2. 使用编辑器打开项目
3. yarn
4. yarn lowcode:dev
5. 打开 http://localhost:3333/
6. 选择这个自定义 FAQ 组件
![image](https://user-images.githubusercontent.com/25478678/236614419-ffcca57f-5192-4a00-838d-993274320750.png)
7. 在自定义设置器填写一些内容，发现设计器没有即时渲染
![image](https://user-images.githubusercontent.com/25478678/236614558-749aadb0-a1b0-4d00-88df-5ffbd08d8cb2.png)
8. 如果我放一个新的组件，就可以正常渲染
![image](https://user-images.githubusercontent.com/25478678/236614677-904a7de6-1e17-4d4a-ad68-3bdc97825a0e.png)

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
在上述操作的第七步，即设置器设置属性 FaqList.faqTitle，设计器能即时渲染最新属性

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**

**下方的获取版本的方法似乎失效了？**

 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by liujuping** [comment]
![image](https://user-images.githubusercontent.com/11935995/236728250-f0f0e3ae-36d1-412f-b1b5-99cb4e93f36d.png)

设计器将新的 props 提供给 FAQ 这个组件了，看看 FAQ 这个组件内部的逻辑，以及输出一些 props 自查一下。

**Comment by wojiaofengzhongzhuifeng** [comment]
@liujuping 在 FAQ 组件内部确实获取了新的props ，所以这才是问题所在呀，现在的问题就是已经传了新 props，但是设计器却没有重新渲染

**Comment by liujuping** [comment]
设计器只更新到 FAQS 这一层，剩下的是 FAQ 这一个组件内部的渲染逻辑，包括 FAQ 下面的子组件之类的。

假设 FAQS 下的逻辑出现问题了，这个引擎是没有办法处理的。可以看到上面的 schema，已经没有 children 了，也就是 props.xxx 怎么渲染，都是 FAQS 里面的逻辑了。

**Comment by wojiaofengzhongzhuifeng** [comment]
@liujuping  非常感谢您的回答，是 FAQ 组件内部的问题
