### ISSUE TITLE
【Table】无法在按钮的事件中获取table的record等信息

### ISSUE THREAD

**Issue by li379395535** [alibaba/lowcode-engine#1993]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
无法在按钮的事件中获取table的record等信息
---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
---
Steps to reproduce the behavior: / 详细复现步骤：
1. 在table组件中新增一列操作列
<img width="795" alt="image" src="https://user-images.githubusercontent.com/21994087/236617551-3d9dc0de-a751-4400-9d2f-9ddcfa85a7fa.png">
2. 启用自定义渲染
<img width="330" alt="image" src="https://user-images.githubusercontent.com/21994087/236617616-c74dbfe5-ea96-4248-91ad-35738ddc1bc2.png">
3. 给按钮绑定事件输出自定义渲染提供的参数
<img width="1372" alt="image" src="https://user-images.githubusercontent.com/21994087/236617702-8072c8ea-820b-439e-89d9-3488f5d8150a.png">

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

期望输出record对象
实际输出undefined
<img width="553" alt="image" src="https://user-images.githubusercontent.com/21994087/236618143-a16ead6a-b089-4f28-b9cc-087635b632f3.png">

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: 1.1.7-beta.11 / 低代码引擎版本
 - AliLowCodeEngineExt version: 1.0.6-beta.25 / 低代码引擎扩展包版本
 - Browser: chrome 113.0.5672.63 / 浏览器版本
 - materials: antd-lowcode-materials@1.1.1 / @seada/antd-materials@1.0.0-rc.27 / @seada/formily-materials@1.0.0-rc.27

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

**Comment by eternalsky** [comment]
@liujuping 看下 slot 里的组件事件获取参数的问题~

**Comment by liujuping** [comment]
1.绑定扩展参数

![image](https://user-images.githubusercontent.com/11935995/236726105-36367ce9-2e80-4e46-8a80-8c35d3124732.png)

2.在点击函数的第二个参数里面可以获取到。

![image](https://user-images.githubusercontent.com/11935995/236726123-cfffcff8-4f2f-43a3-ab76-f80914750058.png)

![image](https://user-images.githubusercontent.com/11935995/236726155-1efe3b5e-71e8-467e-b375-d1a40e4b2d92.png)
