### ISSUE TITLE
把低代码引擎集成到umi4中，物料的img的src引用的是静态文件地址会失效

### ISSUE THREAD

**Issue by wssgchungang** [alibaba/lowcode-engine#1995]
## **Describe the bug (required)** / **详细描述 bug（必填）**

把低代码引擎集成到umi4中，物料的img的src引用的是静态文件地址会失效

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

比如一个空状态的物料组件在用低代码引擎脚手架启用的时候是正常的，他的图片引用地址是 如下
![image](https://user-images.githubusercontent.com/29122164/236716601-b9f0b4fd-9742-4910-a2c6-50484f9bbf5d.png)

把低代码引擎集成到umi4中，空状态物料的img的src引用的是静态文件地址会失效，如下
![image](https://user-images.githubusercontent.com/29122164/236716970-77f6e04a-ca95-4e15-a5d0-0843c33475fe.png)

**Comment by JackLian** [comment]
低代码引擎 by design 是独立页面使用的，不考虑被集成到某个spa框架中
