### ISSUE TITLE
在新版本物料开发脚手架下，slot重写后在预览模式下失效

### ISSUE THREAD

**Issue by wssgchungang** [alibaba/lowcode-engine#1996]
## **Describe the bug (required)** / **详细描述 bug（必填）**

在最新版本物料开发脚手架下，slot重写后在预览模式下失效，原本的slot组件会生成个div包裹住组件，所以重写了slot取消这个div，在引擎的编辑模式下是正常的，但是预览模式下又用回原来的slot了，原本以前的老版本的脚手架是正常的。

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
下图是编辑模式下，slot是正常的，按钮的文字内容和icon都没有div包裹
![image](https://user-images.githubusercontent.com/29122164/236717489-1ffe4eb1-f9bd-4508-b8fd-af67eeec8329.png)

下图是最新版本预览模式下又用回原来的slot了
![image](https://user-images.githubusercontent.com/29122164/236717805-bba1520c-6dd7-42e2-83e0-dc3a453da5a7.png)

下图是老版本预览模式下是正常的
![image](https://user-images.githubusercontent.com/29122164/236718397-9083942f-77e8-4b18-89ad-1aa3ad10118d.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
老版本：
@alifd/build-plugin-lowcode@0.2.10
@alilc/lowcode-react-renderer@1.0.6

出问题的版本：
@alifd/build-plugin-lowcode@0.3.9
@alilc/lowcode-react-renderer@1.1.4

**Comment by Great-old-one** [comment]
请问这个问题解决了吗？ 我也遇到了
