### ISSUE TITLE
在新版本的物料脚手架下，重写slot组件，在预览模式下失效

### ISSUE THREAD

**Issue by wssgchungang** [alibaba/lowcode-engine#1998]
## **Describe the bug (required)** / **详细描述 bug（必填）**

在新版本的物料脚手架下，原本slot组件会有一个div包裹，所以重写了slot组件，就跟antd物料重写的那个slot组件一样，编辑模式下是正常的，但是在预览模式下又用回了原来的slot组件，在老版本下是正常的

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

在新版本的编辑模式下是正常的，按钮的icon和内容都没有div包裹，如下图
![image](https://user-images.githubusercontent.com/29122164/236720103-9d37e9a7-3ab8-4f50-8373-e5fae2fbd0c8.png)

在预览模式下就不正常了，如下图
![image](https://user-images.githubusercontent.com/29122164/236720257-8b2e95ec-e0a9-4f15-aa6c-790f18ab1ae6.png)

在老版本的预览模式下是正常的，如下图
![image](https://user-images.githubusercontent.com/29122164/236720320-f7e1e17d-7ee1-4ee0-b7f1-209a4dd63c1f.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
老版本：
@alifd/build-plugin-lowcode@0.2.10
@alilc/lowcode-react-renderer@1.0.6

出问题的版本：
@alifd/build-plugin-lowcode@0.3.9
@alilc/lowcode-react-renderer@1.1.4

**Comment by liujuping** [comment]
辛苦看一下在线上 demo 的调试模式下是否正常。

**Comment by liujuping** [comment]
由于 issue 没有反馈，暂时关闭，有需要再重新打开。
