### ISSUE TITLE
几个问题

### ISSUE THREAD

**Issue by r4ggj** [alibaba/lowcode-engine#20]
1. 目前项目启动有问题，在windows上没法起来。只有装个ubuntu，还要整各种编译依赖，node-sass的兼容问题
2. 文档目前不够健全，希望能整个umi类似的文档
3. 项目启动速度太慢
4. 运行时的一个js文件差不多2M多，体积太大了

**Comment by abnerCrack** [comment]
@r4ggj 
1.启动问题，正式版demo会修复，目前在准备阶段未正式发布，还请耐心等待一下
2.文档也会慢慢跟进
3.运行时启动速度这个只是脚手架的问题，后续会跟进优化
4.设计器本身代码量是非常大的，设计态加载了非常多的插件以及资源，用来增强开发体验以及设计能力，
但是正式运行的时候，只会使用设计器产物加渲染器，体积会相应的下降。

**Comment by LeoYuan** [comment]
启动脚本的问题，readme 里有写建议 Windows 下用 WSL 终端，以及 node-sass 对 node 版本有要求，建议 14

**Comment by wuliupo** [comment]
+1 
建议 node-sass 改成 Dart-Saas，就是 npm 包 saas
前者已经停止维护了
