### ISSUE TITLE
如何自定义选中物料的操作工具栏？

### ISSUE THREAD

**Issue by guohejun** [alibaba/lowcode-engine#2001]
![image](https://user-images.githubusercontent.com/27323522/236751840-c2992a12-e962-4f7b-b5bf-6ec9b7f6639f.png)
当画布中物料被选中时，右上角的工具栏，请问怎么自定义？

**Comment by liujuping** [comment]
https://lowcode-engine.cn/site/docs/api/material#addbuiltincomponentaction
