### ISSUE TITLE
@alifd/pro-layout 升级到 @alifd/layout 之后  component is not found in components list! co

### ISSUE THREAD

**Issue by QiYunMeng1126** [alibaba/lowcode-engine#2002]
@alifd/pro-layout  1.0.1
@alifd/layout  2.0.1

升级前提基础
![image](https://user-images.githubusercontent.com/13884135/236773469-5edd39d9-f0bb-4d2c-b5f8-e286dc53ca63.png)

升级原因
@alifd/pro-layout   编辑器状态下, 行列容器下行拆出来的两个列 调节宽度类型或者设置固定宽度的时候. 编辑器状态下样式正常
预览状态下样式未达到预期效果
@alifd/layout 未发现此问题

编辑器如下

![Snipaste_2023-05-08_16-34-09](https://user-images.githubusercontent.com/13884135/236776659-9efe7446-dff2-4fc3-bf80-4040cf2c4321.png)

![Snipaste_2023-05-08_16-26-25](https://user-images.githubusercontent.com/13884135/236776757-2bce3960-edf3-4a6b-9157-180775e5b439.png)

预览状态下

![Snipaste_2023-05-08_16-28-33](https://user-images.githubusercontent.com/13884135/236776824-d9c90489-3d45-470d-ab6a-e2055781b16d.png)

替换成 @alifd/layout  2.0.1 异常错误如下
![image](https://user-images.githubusercontent.com/13884135/236777341-47c59663-795a-426c-b6a5-7a8842a34d2b.png)

请大佬抽时间看下,谢谢!

**Comment by JackLian** [comment]
这两套布局组件是不兼容升级，存量的schema没法直接升上去

**Comment by JackLian** [comment]
@alifd/pro-layout 1.0.1
@alifd/layout 2.0.1
这两个并不是兼容的，你替换之后schema需要重新搭，没办法自动升级

**Comment by QiYunMeng1126** [comment]
@alifd/pro-layout 编辑器状态下, 行列容器下行拆出来的两个列 调节宽度类型或者设置固定宽度的时候. 编辑器状态下样式正常
预览状态下样式未达到预期效果

编辑器如下

![236776659-9efe7446-dff2-4fc3-bf80-4040cf2c4321](https://user-images.githubusercontent.com/13884135/237055446-d4fdc057-5169-47be-9333-c89cce310481.png)
![236776757-2bce3960-edf3-4a6b-9157-180775e5b439](https://user-images.githubusercontent.com/13884135/237055468-9efe3735-1e4c-4eb1-832a-64b571d425fe.png)



预览状态下
![236776824-d9c90489-3d45-470d-ab6a-e2055781b16d](https://user-images.githubusercontent.com/13884135/237055496-cb4776ef-02e2-47c2-8b11-0a59fe6a65db.png)
