### ISSUE TITLE
复制组件报找不到 getRGL 函数

### ISSUE THREAD

**Issue by cbqqkcel** [alibaba/lowcode-engine#2007]
## **Describe the bug (required)** / **详细描述 bug（必填）**

官网综合场景demo复制组件报找不到 getRGL 函数

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1.打开控制台
2.任意添加一个组件
2.点击组件复制按钮
---

---

## **Screenshots (optional)** / **bug 截图（可选）**
![image](https://user-images.githubusercontent.com/4516585/236837576-cf6a4739-4987-4439-8eb1-a0e585620bd9.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g.  v1.1.7-beta] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. v1.0.6-beta.25] / 低代码引擎扩展包版本

## **Additional context (optional)** / **更多额外信息（可选）**
用快捷键复制不会报错

**Comment by daifuyang** [comment]
+1
