### ISSUE TITLE
在低代码平台，通过 npm 的方式注册自定义组件（该组件含有自定义设置器）出错

### ISSUE THREAD

**Issue by wojiaofengzhongzhuifeng** [alibaba/lowcode-engine#2009]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：
1. git clone git@github.com:wojiaofengzhongzhuifeng/question-lowcode-1.git
2. yarn
3. yarn start
4. 使用 colorful-button 组件，发现可以正常使用
![image](https://user-images.githubusercontent.com/25478678/236977622-86699cc9-a0da-4304-9b87-ea2d862b6dd4.png)
5. 修改 src/services/assets.json 的 packages 和 components 最后一项（实际修改版本：0.2.1 => 0.2.2）

```
packages 最后一项内容为
    {
      "package": "gate-lowcode-component",
      "version": "0.2.2",
      "library": "gate-lowcode-component",
      "urls": [
        "https://unpkg.com/gate-lowcode-component@0.2.2/build/lowcode/render/default/view.js",
        "https://unpkg.com/gate-lowcode-component@0.2.2/build/lowcode/render/default/view.css"
      ],
      "editUrls": [
        "https://unpkg.com/gate-lowcode-component@0.2.2/build/lowcode/view.js",
        "https://unpkg.com/gate-lowcode-component@0.2.2/build/lowcode/view.css"
      ],
      "advancedUrls": {
        "default": [
          "https://unpkg.com/gate-lowcode-component@0.2.2/build/lowcode/render/default/view.js",
          "https://unpkg.com/gate-lowcode-component@0.2.2/build/lowcode/render/default/view.css"
        ]
      },
      "advancedEditUrls": {}
    }
```

```
components 最后一项内容为
    {
      "exportName": "GateLowcodeComponentMeta",
      "npm": {
        "package": "gate-lowcode-component",
        "version": "0.2.2"
      },
      "url": "https://unpkg.com/gate-lowcode-component@0.2.2/build/lowcode/meta.js",
      "urls": {
        "default": "https://unpkg.com/gate-lowcode-component@0.2.2/build/lowcode/meta.js"
      },
      "advancedUrls": {
        "default": [
          "https://unpkg.com/gate-lowcode-component@0.2.2/build/lowcode/meta.js"
        ]
      }
    }
```

6. 使用 colorful-button 组件，发现不可以正常使用，检查控制台，发现报错内容如下
![image](https://user-images.githubusercontent.com/25478678/236978480-7e3f64bd-bb24-4bb1-b77f-e4d2dfb6e8c8.png)

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

希望可以通过 npm 的方式注册自定义组件（该组件含有自定义设置器）正常

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

![image](https://user-images.githubusercontent.com/25478678/236978480-7e3f64bd-bb24-4bb1-b77f-e4d2dfb6e8c8.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**

 - AliLowCodeEngine version: 1.0.5
 - AliLowCodeEngineExt version: 1.0.5
 - Browser chrome
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

[0.2.1](https://github.com/wojiaofengzhongzhuifeng/question-lowcode-2/blob/4f679e0be4d120f76604973906236af949aeedfc/src/index.tsx#L15) 版本注册的自定义组件，没有注册自定义设置器；
[0.2.2](https://github.com/wojiaofengzhongzhuifeng/question-lowcode-2/blob/2e17678a0e50f5bba4ce6327d7bfa433730587b7/src/index.tsx#L15) 版本注册的自定义组件，注册了自定义设置器，根据[官网的文档](https://lowcode-engine.cn/site/docs/guide/expand/editor/setter#%E6%B3%A8%E5%86%8C-altstringsetter)，应该执行如下代码进行自定义组件的注册
```
import AltStringSetter from './AltStringSetter';
const registerSetter = window.AliLowCodeEngine.setters.registerSetter;
registerSetter('AltStringSetter', AltStringSetter);
```
这是否是错误的原因？

**Comment by liujuping** [comment]
看一下，window.AliLowCodeEngine 是在哪一层执行的，如果是组件内部，就是在 simulator，也就是画布内部执行的，在画布内部是不存在 window.AliLowCodeEngine 全局变量的，这块逻辑执行就会有问题。

只有 meta 相关的信息会在引擎层面执行，才会存在 widnow.AliLowCodeEngine，可以修改自定义组件相关的逻辑。
