### ISSUE TITLE
想把lowcode-demo迁移到内网当中，怎么解决，不会真要一个一个下载js包然后引入吧？？？

### ISSUE THREAD

**Issue by lijiaxu1996** [alibaba/lowcode-engine#201]
## 问题描述:
demo如何引入内网，好多资源url连接都是alicdn引入的，我该如何引入**内网**当中呢，引入的话，太多了吧，而且性能也不好吧，所以看看有啥解决办法呀！

**Comment by baieceo** [comment]
按文档是要一个个引入的

**Comment by baieceo** [comment]
目前还不太稳定，有些功能会报错

**Comment by lijiaxu1996** [comment]
> 

引入之后需要重新编写build.plugin.js文件么，比如像对css，svg的打包@[baieceo](https://github.com/baieceo)
