### ISSUE TITLE
脚手架生成的设置器项目不能用

### ISSUE THREAD

**Issue by AdmireWang** [alibaba/lowcode-engine#2011]
使用脚手架初始化一个自定义设置器项目，默认是非inject模式，此时，plugin都没有注册，如图：
![image](https://user-images.githubusercontent.com/5096573/237006533-35835cb3-1d85-4eb3-bdb0-c66c70235684.png)
![image](https://user-images.githubusercontent.com/5096573/237006446-cef240ea-c8e9-408e-ad9f-0bc0aaa88e0e.png)
而如果是设成inject模式，只能inject一个设置器，而物料里没有用到这个设置器的，无法调试。

**Comment by eternalsky** [comment]
确实，现在本地开发 setter 有些问题，我来跟进一下

**Comment by AdmireWang** [comment]
> @alilc/build-plugin-alt@1.3.3 已修复

可以了，感谢大佬！
