### ISSUE TITLE
使用咨询：demo处异步加载资源和自然布局的含义是？

### ISSUE THREAD

**Issue by llllllllr** [alibaba/lowcode-engine#2012]
1. 异步加载资源的含义是？
![image](https://user-images.githubusercontent.com/35605494/237050014-82f294a2-c1ef-4d30-b56a-aa92488feafd.png)

2. 自然布局的用法？点击自然布局组件，拖拽到右边没有反应，想咨询下正确的使用姿势

**Comment by JackLian** [comment]
1. 是异步加载资源的示例插件，用来演示在设计器加载过程中，先加载一批组件，然后后续再通过api加载一批组件的场景
2. 参考 https://www.yuque.com/fusion-design/layout/yzx8g4
