### ISSUE TITLE
可不可以在低代码A 页面 打开低代码B 页面配置的弹窗呢？

### ISSUE THREAD

**Issue by handwill** [alibaba/lowcode-engine#2015]
如题，我们业务是在procode 项目中通过 lowcode-react-renderer渲染每个低代码页面的。遇到个场景，A 页面有个编辑弹窗，这个编辑弹窗想在 B 页面点击某个按钮的时候也能弹出来。想问下这个场景怎么实现呢？

**Comment by JackLian** [comment]
很难想象这是个啥场景

**Comment by yz1311** [comment]
> 

就是在建站中不同页面之间如何复用代码？目前也碰到这个问题了

**Comment by LeoYuan** [comment]
可以去搜搜阿里终端微信公众号里的一篇文章，标题大概是 **后半场物料体系的思考和实践**，里面会讲到 **低代码组件** 的相关概念，就类似 ProCode 里的用于页面间/应用间可复用的组件~

**Comment by LeoYuan** [comment]
也可以催一下在官方的 [lab](https://lab.lowcode-engine.cn/#/) 里放出低代码组件功能预览版~😄

**Comment by handwill** [comment]
> 很难想象这是个啥场景

就是一个编辑弹窗，可以在多个不同的低代码页面里面打开。

**Comment by JackLian** [comment]
做多份，或者使用低代码组件，低代码方式开发一个组件，并且被其他页面使用，参考
https://lowcode-engine.cn/site/docs/guide/expand/editor/parts/partslcc
