### ISSUE TITLE
自定义物料可以开发区块吗？现在只可以开发单个组件吗？

### ISSUE THREAD

**Issue by Underthenightskyo** [alibaba/lowcode-engine#2016]
目前是不适配h5的，所有我想自己开发一个区块，这个区块内的内容我自己适配一下h5，想问下是和自定义物料是一样的吗？

**Comment by liujuping** [comment]
不清楚你的区块指的是什么，以及和物料的区别是什么？如果是为了适配 H5，可以开发一个适配 H5 的自定义物料。
