### ISSUE TITLE
点击组件库面板添加到内容区

### ISSUE THREAD

**Issue by l704863851** [alibaba/lowcode-engine#2018]
## **Describe the bug (required)** / **详细描述 bug（必填）**

如何通过点击组件库面板组件添加到页面

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

中文版示例：
1. 打开 [demo](https://l704863851.github.io/lowcode-rgl-demo/)；
2. 点击组件库面板；
3. 如何做到点击Button组件直接加入到内容区

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - 低代码引擎版本v1.1.7-beta 
 - 低代码引擎扩展包版本v1.0.6-beta.25 
 - 浏览器版本 google chrome最新版

**Comment by liujuping** [comment]
可以使用这个 api，在根节点插入
