### ISSUE TITLE
ArraySetter 遇到重新赋值时无效

### ISSUE THREAD

**Issue by rainke** [alibaba/lowcode-engine#2019]
## **Describe the bug (required)** / **详细描述 bug（必填）**

假设我原来一个值 list 为 [{a: '2', b: '2'}]
通过 setPropValue，将 list 改为  [{a: '3', b: '3'}]

发现 arraysetter 的组件没有变化

https://github.com/alibaba/lowcode-engine-ext/blob/890565f5b80dbe1a40d873555caac7d5d3fbb07c/src/setter/array-setter/index.tsx#LL82C1-L83C19

**Comment by liujuping** [comment]
![image](https://github.com/alibaba/lowcode-engine/assets/11935995/c330f1db-9ff4-4efa-be56-2b5bf2c299ae)

在 demo 上，没有复现你说的这个情况。

https://lowcode-engine.cn/demo/demo-general/index.html

**Comment by rainke** [comment]
![image](https://github.com/alibaba/lowcode-engine/assets/13936318/3452233b-c769-4fa4-9d2a-74e84b051eef)

将两个改成一个，`ArraySetter` 组件 没有任何变化，再获取 `items` 时，多了一个 undefined

**Comment by rainke** [comment]
每次执行 'setValue' 的时候应该重新审视一下当前的 `_items` 是否合适
https://github.com/alibaba/lowcode-engine/blob/ee80fb12b864f2ddd657fe1503e57f755697d07a/packages/designer/src/document/node/props/prop.ts#L360

**Comment by liujuping** [comment]
这个问题和 setValue 没有关系，而是这里的 props 变化之后没有触发组件的更新，具体的问题还得定位。

**Comment by ming001** [comment]
这个问题修复并发beta包了吗。
我使用@alilc/lowcode-engine-ext /1.0.6-beta.28版本，还是有这样的问题。执行
target.parent.setPropValue('columns', [
    { title: 'jack1', dataIndex: 'jack1', valueType: 'text' },
  ]);
  画布UI界面变了，setter还是没变更新
  
![image](https://github.com/alibaba/lowcode-engine/assets/24415457/e2c0537a-bcfc-4b91-be41-28329849dd2a)

**Comment by ming001** [comment]
在控制台执行，也能复现在这个问题
![image](https://github.com/alibaba/lowcode-engine/assets/24415457/db65dc95-b40d-4b19-8c49-25e0fcfc8e7c)

**Comment by ming001** [comment]
在控制台执行也能复现，画布UI界面变了，也能获取，但是setter界面还是没变更新
![image](https://github.com/alibaba/lowcode-engine/assets/24415457/2e678d8f-244c-4938-90d5-ef5c6b42943f)

**Comment by liujuping** [comment]
引擎需要是最新的 beta 版本。
