### ISSUE TITLE
保存已有数据源报错

### ISSUE THREAD

**Issue by baieceo** [alibaba/lowcode-engine#202]
## **Describe the bug (required)** / **详细描述 bug（必填）**
保存已有数据源报错

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
新增数据源保存后，再次编辑，保存报错
![image](https://user-images.githubusercontent.com/19337357/160374071-b4e72b26-38ec-41d7-9a41-1b07772d09d1.png)

AliLowCodeEngine  v1.0.1-beta.1 
index.tsx:231  AliLowCodeExt  v1.0.2

**Comment by LeoYuan** [comment]
@xingmolu 帮忙看看~

另外， @baieceo 不要用 beta 版本。。。

**Comment by baieceo** [comment]
> @xingmolu 帮忙看看~
> 
> 另外， @baieceo 不要用 beta 版本。。。

版本是从https://lowcode-engine.cn/docV2/start-with-lce这里抄过来的，1.0版本用workbench方式引入有问题

**Comment by twinkle77** [comment]
@baieceo  现在应该没问题的  我用的workbench
