### ISSUE TITLE
lowcode-materials物料工程下面的antd-lowcode-marterials和fusion-lowcode-materials两个工程拉下来安装完依赖运行lowcode:dev就报错

### ISSUE THREAD

**Issue by 123456dengting** [alibaba/lowcode-engine#2024]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1. 切换到packages/fusion-lowcode-materials
2. cnpm i
3. cnpm run lowcode:dev

![image](https://github.com/alibaba/lowcode-engine/assets/28246564/2376715b-6000-4e6e-95e7-27d51fd14854)

---

English version example：
5. Click on '....'
6. Scroll down to '....'
7. See error

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by 123456dengting** [comment]
![image](https://github.com/alibaba/lowcode-engine/assets/28246564/81b08a14-98b1-40fc-8d8d-f4937a6b70bb)
对比了下 看起来是这边生成的路径少了个斜杠,我这边另外那个fusion-ui可以正常包的生成的是双斜杠的.不知道怎么生成的

**Comment by eternalsky** [comment]
官方没有承诺对 windows 的全面支持，推荐 windows 用户在 wsl 环境下进行开发。但欢迎提交 pr，以让工具在 windows 下运行更加符合预期。

**Comment by 123456dengting** [comment]
奇怪的是我在fusion-ui下面是正常的

**Comment by liujuping** [comment]
> 奇怪的是我在fusion-ui下面是正常的

windows 下，fusion-ui 和 lowcode-materials 之间的差异可以研究一下。欢迎提交 pr，以让工具在 windows 下运行更加符合预期。
