### ISSUE TITLE
使用antd的表格列，最后一列使用自定义渲染，拖拽进一个按钮，给按钮绑定事件后，怎么拿到插槽内透漏出的变量params

### ISSUE THREAD

**Issue by wssgchungang** [alibaba/lowcode-engine#2028]
## **Describe the bug (required)** / **详细描述 bug（必填）**

使用antd的表格列，最后一列使用自定义渲染，拖拽进一个按钮，给按钮绑定事件后，怎么拿到插槽内透漏出的变量params

**Comment by wssgchungang** [comment]
试了下，直接自定义渲染一个按钮，按钮绑定onClick事件后， onClick怎么拿到render下的params

**Comment by boboyes** [comment]
使用扩展参数
![image](https://github.com/alibaba/lowcode-engine/assets/33591654/c6e2cf1d-f99d-4f77-af94-114234c6bae2)

**Comment by wssgchungang** [comment]
> 使用扩展参数 ![image](https://user-images.githubusercontent.com/33591654/237847748-c6e2cf1d-f99d-4f77-af94-114234c6bae2.png)

啊 我以为报红以为不支持这样写就没用 😂
