### ISSUE TITLE
@alilc/element 创建组件库报错

### ISSUE THREAD

**Issue by Darcrandex** [alibaba/lowcode-engine#203]
## **Describe the bug (required)** / **详细描述 bug（必填）**

通过物料库脚手架创建新项目，运行后报错

```
Error: Cannot find module 'react-dom/package.json'
```

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

```
npm init @alilc/element my-material-name
cd my-material-name
npm install
npm start
```

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

**Comment by mark-ck** [comment]
之前模板缺失的依赖已经加上，已经初始化过的项目可以手动加一下依赖，或者重新初始化一个组件试试

```
"react": "^16.x",
"react-dom": "^16.x"
```
