### ISSUE TITLE
demo-general出码后无样式

### ISSUE THREAD

**Issue by eurekazheng** [alibaba/lowcode-engine#2034]
## **Describe the bug (required)** / **详细描述 bug（必填）**

demo-general出码后无样式，无论是浏览器还是服务端。其他issue中有提到过，但是解决不了。

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1. 使用最新的lowcode-demo。设计以下schema：[https://gist.github.com/eurekazheng/183a45eb7c181e7e17a990d5be31d3a0](https://gist.github.com/eurekazheng/183a45eb7c181e7e17a990d5be31d3a0)
2. 无论使用浏览器出码，还是服务端（最新的@alilc/lowcode-code-generator@1.1.2）（`npx @alilc/lowcode-code-generator -i example-schema.json -o generated -s icejs`）,都无法生成样式。（如果使用浏览器出码，code-sandbox同时还会出Could not find dependency: '@alifd/pro-layout' relative to '/src/index.js'的错误）

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

生成网页有样式。

## **Screenshots (optional)** / **bug 截图（可选）**

![image](https://github.com/alibaba/lowcode-engine/assets/17842184/b764f659-c2d9-44da-8d8e-dac4dbcedbbd)
![image](https://github.com/alibaba/lowcode-engine/assets/17842184/2582a521-0233-4896-9983-75226b63cff5)
![image](https://github.com/alibaba/lowcode-engine/assets/17842184/21bde154-d775-4688-b377-d3ad8b48a7fb)

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**

 - AliLowCodeEngine version: 1.1.2 / 低代码引擎版本
 - AliLowCodeEngineExt version: 1.0.0 / 低代码引擎扩展包版本
 - Browser Chrome / 浏览器版本

## **Additional context (optional)** / **更多额外信息（可选）**

因为比较急用，希望能提供一个临时能work的历史版本也可以，谢谢！

**Comment by eurekazheng** [comment]
目前我唯一能做的workaround是从codesandbox上下载代码然后自己部署react-scripts，再修改一下结构。可是即便如此样式仍然是很有问题：

正常（预览）：
![image](https://github.com/alibaba/lowcode-engine/assets/17842184/073b6763-d60a-4a33-ae5f-24183fdf83b6)

CodeSandbox：
![image](https://github.com/alibaba/lowcode-engine/assets/17842184/50a39298-aaa8-413f-8072-c309527fc8ba)

求教如何获得预览界面展示的代码！

**Comment by eurekazheng** [comment]
我发现另一个workaround，就是直接`npm run build` demo-general，剥离出生成的build/preview.html作为工程文件。

**Comment by LeoYuan** [comment]
![image](https://github.com/alibaba/lowcode-engine/assets/1195765/75de8b9b-2b9e-4526-8ead-d50f8f8666e3)

手工引入一下这个 style.js 试试~

**Comment by LeoYuan** [comment]
![image](https://github.com/alibaba/lowcode-engine/assets/1195765/2e2d5d9a-9faf-479e-895e-b382aa90d482)

测试 OK，稍后我改下代码~

**Comment by LeoYuan** [comment]
+ @alilc/lowcode-code-generator@1.1.3-beta.1

**Comment by hinhinlaw** [comment]
> ![image](https://user-images.githubusercontent.com/1195765/239425177-75de8b9b-2b9e-4526-8ead-d50f8f8666e3.png)
> 
> 手工引入一下这个 style.js 试试~

请问这个style.js引入到哪里呢
