### ISSUE TITLE
hotkey 撤销 /恢复 node ，不会触发 onAddNode/ onRemoveNode

### ISSUE THREAD

**Issue by ranyue** [alibaba/lowcode-engine#2037]
添加节点，然后点击节点上的 删除icon，可以正常触发  onAddNode/ onRemoveNode
如果通过hotkey 撤销/恢复，完成节点的删除/添加行为，不能触发  onAddNode/ onRemoveNode

**Comment by ranyue** [comment]
AliLowCodeEngine  v1.1.3

**Comment by liujuping** [comment]
撤销/恢复的操作是重新导入完整的 schema，相当于使用了这个 API：https://lowcode-engine.cn/site/docs/api/model/document-model#importschema

这时候可能会触发多次 onAddNode/ onRemoveNode 事件，和你期望的行为应该不一致。

**Comment by ranyue** [comment]
感谢，我调整成 importschema监听
