### ISSUE TITLE
请问，能用来生成vue页面代码吗？

### ISSUE THREAD

**Issue by bingxueyinlian** [alibaba/lowcode-engine#204]

**Comment by Clarence-pan** [comment]
低代码引擎在架构上是和具体语言无关的，通过一定的扩展和插件是可以生成 Vue 页面代码的。
如果只是用现有的基于 React 的 fusion 物料来搭建，只是在最终出码的时候生成 Vue 页面代码，那您需要准备一套和 fusion 兼容的 vue 物料，并定制个出码方案，将[下面的一些出码插件](https://github.com/alibaba/lowcode-engine/blob/main/modules/code-generator/src/solutions/icejs.ts)替换成生成 Vue 框架的即可：
![image](https://user-images.githubusercontent.com/8750132/160738850-f90a083d-c205-4870-a828-cc9f9f69ce6d.png)


详细定制方案可以参考下[《自定义出码》](https://lowcode-engine.cn/docV2/cplfv0#857ba793)。
如果您希望在搭建的时候也使用 Vue 的物料，则还需要扩展定制入料、画布和渲染器等模块，详细方案请参考下[《扩展低代码编辑器》](https://lowcode-engine.cn/docV2/srdo3s)
