### ISSUE TITLE
[Question]低代码引擎的setter的props如何设计成异步的？

### ISSUE THREAD

**Issue by jqhr** [alibaba/lowcode-engine#2040]
具体场景是这边有一个表格组件自定义操作按钮的选项操作
![图片](https://github.com/alibaba/lowcode-engine/assets/23305067/6e5c8651-41db-4f5d-8714-d09d84b20650)
就像这样，这个关联页面的选项是异步请求出来的，SelectSetter的options是不支持异步请求的，怎么办？

**Comment by LeoYuan** [comment]
HOC 包装一层就好~

setter 伪码：

```js
function YourSelectSetter({ value }) {
  const [ds, setDs] = useState(value || []);

  useEffect(async () => {
    const newDs = await getDsSomehow();
    setDs(newDs);
  }, []);

  return <SelectSetter value={ds} />;
}
```

prop 声明：
```js
{
  name: 'xxx',
  ...
  setter: { componentName: 'YourSelectSetter' },
}
```

**Comment by jqhr** [comment]
> HOC 包装一层就好~
> 
> setter 伪码：
> 
> ```js
> function YourSelectSetter({ value }) {
>   const [ds, setDs] = useState(value || []);
> 
>   useEffect(async () => {
>     const newDs = await getDsSomehow();
>     setDs(newDs);
>   }, []);
> 
>   return <SelectSetter value={ds} />;
> }
> ```
> 
> prop 声明：
> 
> ```js
> {
>   name: 'xxx',
>   ...
>   setter: { componentName: 'YourSelectSetter' },
> }
> ```

没有别的办法了？
自定义SelectSetter需要在引擎那边全局注册，而assets.json里的库是可以动态更新，更新引擎的话比更新assets.json麻烦的多，
因此我想问问有没有别的解决方案？
@LeoYuan

**Comment by LeoYuan** [comment]
你哪里更新引擎了？

Setter 一样可以动态注册呀，动态注册物料的同时把 Setter 也注册不就行了

**Comment by jqhr** [comment]
不好意思，我的意思是说引擎侧要注册东西，这部分属于基础设施的部分，而assets.json里的物料属于更上层的东西，它可以托管到服务器，setters属于更基础的东西。因此升级会更麻烦一些，毕竟牵一发动全身嘛

**Comment by LeoYuan** [comment]
我觉得没区别，物料和 Setter 都属于广义上引擎消费的元素，修改带来的危险性是一样的~

**Comment by jqhr** [comment]
OK，这里主要是因为assets.json依赖setters，而且我这边会有好几个物料都会依赖这个setters。
如果确实是没有办法的话，那我就关了issue

**Comment by LeoYuan** [comment]
嗯嗯~

物料 prop 定义时，还有个动态 setter 的能力，更精细化控制单个物料的单个属性，可以试试~

```js
{
  setter: () => {
     // 方式一：
     return <YourSelectSetter />; // 内部处理 ds 来源
     // 方式二：
     return <SelectSetter value={window.ds} />; // window.ds 预先准备好了
  }
}
```

**Comment by jqhr** [comment]
ok
