### ISSUE TITLE
Feature: 常量实时同步

### ISSUE THREAD

**Issue by eightHundreds** [alibaba/lowcode-engine#2041]
# 背景

”众所周知“，只有应用级常量在大型项目中是不够用的。开发者常常会为某个模块，某个页面定义一些常量。
因此，我会在源码面板出新增页面级常量编辑.

# 问题

目前常量通过.init方法的appHelper配置注入, 是一次性的,不可修改的。

# 诉求

希望引擎能监听ProjectSchema的constants变化，实时地修改SimulatorRendererContainer.context

# 相关
https://github.com/alibaba/lowcode-engine/issues/1253

**Comment by liujuping** [comment]
可以通过支持调用下面的 API 来修改 SimulatorRenderer 下的 appHelper 的值。

```
config.set('appHelper', newAppHelper)
```

思路是：这里修改成响应式的，比如利用：config.onGet 方法监听 appHelper 的变化。修改成响应式的之后，render 下面的 appHelper 即可响应到 appHelper 的变化。

![image](https://github.com/alibaba/lowcode-engine/assets/11935995/5c4c78fd-9c69-4d79-b6dc-9b753fd78cca)

![image](https://github.com/alibaba/lowcode-engine/assets/11935995/71cdeb82-1c45-47f4-be9f-b94ebe13afb6)

欢迎 PR。

**Comment by proclml** [comment]
确实需要。
现在的做法本质上是在每次切换页面时把contants重新注入一遍，如果有需要在组件内响应式，就需要在组件生命周期constructor把变量塞到state，在组件销毁时把state填回contants。
也不是不行，就是有点麻烦

**Comment by eightHundreds** [comment]
> 可以通过支持调用下面的 API 来修改 SimulatorRenderer 下的 appHelper 的值。
> 
> ```
> config.set('appHelper', newAppHelper)
> ```
> 
> 思路是：这里修改成响应式的，比如利用：config.onGet 方法监听 appHelper 的变化。修改成响应式的之后，render 下面的 appHelper 即可响应到 appHelper 的变化。
> 
> ![image](https://user-images.githubusercontent.com/11935995/238886831-5c4c78fd-9c69-4d79-b6dc-9b753fd78cca.png)
> 
> ![image](https://user-images.githubusercontent.com/11935995/238887541-71cdeb82-1c45-47f4-be9f-b94ebe13afb6.png)
> 
> 欢迎 PR。

这个方案似乎不行.

<img width="512" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/18695431/6cac0d8c-be7a-49d0-9294-bdcddd362e67">
我将coconstants变成Proxy后, 在`merge`后, this._appContext的constants会变成普通对象

**Comment by eightHundreds** [comment]
难道你指的是,在我的业务代码中,写这段?
```
config.set('appHelper', mobox对象)
```

**Comment by eightHundreds** [comment]
config.onGet 方法监听 appHelper 的变化。修改成响应式的之后
====
这句话不理解
意思是config.onGet回调里吧appHelper改成响应式?
```
config.onGot('appHelper',(val)=>{
  config.set('appHelper', observable(val))
})
```
这样?, 不会循环触发onGot吗

**Comment by liujuping** [comment]
这个能力引擎还不支持，并且优先级不高，有需要欢迎提 PR。

目前只能提供简单的解决思路：

1.在引擎相关模块支持监听 appHelper 的变化，比如之前截图的位置，具体可能还得看看代码。

2.在上一步支持之后，业务可以通过配置新 appHelper，来更新对应的 appHelper。

```
config.set('appHelper', 新 appHelper)
```

**Comment by eightHundreds** [comment]
close by #2186 

开发者可以通过`config.set('appHelper',...)`修改画布中使用的常量
