### ISSUE TITLE
表格的一行里面不支持图片的存在吗，这是个很常见的需求吧

### ISSUE THREAD

**Issue by xinxi053** [alibaba/lowcode-engine#2057]
ui组件库里面所有的组件都看了，发现没法再表格组件了的一行添加图片。

**Comment by LgnMs** [comment]
每一个表格的cell都可以开启插槽的，你只需要在插槽中拖入图片组件，并从表格中获取参数即可，比如参考这个：
https://lowcode-engine.cn/site/docs/faq/faq003
这是demo中NextTable的做法
<img width="1282" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/20039598/370f5d00-2331-427a-8c12-29162febc49f">
