### ISSUE TITLE
@alilc/element 如何生成带有初始 props 值的 Snippet 片段

### ISSUE THREAD

**Issue by mirages** [alibaba/lowcode-engine#206]
在使用 @alilc/element 工具创建物料时，生成物料的 Snippet 片段的 props 都是一个空对象，如何能将组件 props 的默认值自动填充到 Snippet 中呢？

**Comment by mark-ck** [comment]
@mirages 我已经在入料模块中补充(#227 )了生成 defaultValue 的逻辑，你需要重新安装下依赖；

现在支持两种 defaultValue 的写法：
1. 静态 defaultProps : 
```
interface ComponentProps {
  /**
   * @default Title from js doc
   */
  title: string;
  content: string;
}
```
2. js doc:
```
RefExampleComponent.defaultProps = {
  title: 'Title',
  content: 'Contents',
};
```

**Comment by zhengsusu2014** [comment]
手动升级后依然无法生成默认值，而且该修改未合并到后面的正式版本
