### ISSUE TITLE
官方demo的undo报错，且之后无法操作画布。

### ISSUE THREAD

**Issue by doudou673** [alibaba/lowcode-engine#2061]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
demo-general 项目启动 undo点击不生效，报错。且之后无法再对画布进行操作。
<img width="897" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/54931067/3632c061-b4f4-4040-9159-1f2acced9b40">

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

打开 https://lowcode-engine.cn/demo/demo-general/index.html
随便修改个什么
点击右上角的撤销按钮
不生效，打开控制台，发现报错了
之后无法操作画布，例如删除组件、添加组件、移动组件位置

**Comment by liujuping** [comment]
没有复现，看报错跟物料有关，跟你的 schema 上的物料相关，可以先看看是哪个物料影响的。

**Comment by liujuping** [comment]
这个问题和这里的代码有关系。

https://github.com/alibaba-fusion/layout/blob/master/lowcode/common/split/auto-block.ts#LL114C58-L114C58

在新增一个容器之后，撤销，会出现 afterTreeGroup 的长度是 3，i 是 3，afterTreeGroup[groupIndex]) 是 undefined 之后执行 [...undefined] 会报错。

具体原因 @eternalsky 看看？

**Comment by eternalsky** [comment]
已在对应组件仓库提 issue，待跟进。
