### ISSUE TITLE
弹窗消失后无法再次打开

### ISSUE THREAD

**Issue by sweida** [alibaba/lowcode-engine#2062]
## **Describe the bug (required)** / **详细描述 bug（必填）**

每次点开js【源码面板】后，再打开大纲树，模态视图层的按钮失效，弹窗无法再次打开，必现
![WX20230523-112220@2x](https://github.com/alibaba/lowcode-engine/assets/23181508/fd65aa7f-20ea-40b7-9c08-330ec3aa7b0c)

![WX20230523-112246@2x](https://github.com/alibaba/lowcode-engine/assets/23181508/2ae80692-13d2-4902-b5b7-9ab55636fa52)

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

每次点开js后，再打开大纲树，模态视图层的按钮失效，弹窗无法在此打开，必现
---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
1、先打开 js（源码面板），关闭js（源码面板）后，弹窗消失后就无法再次打开了

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本
 
版本：官网demo
https://lowcode-engine.cn/demo/demo-general/index.html

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

每次需要重新点击大纲树的 固定按钮 后就正常，弹窗才可以正常显示
<img width="367" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/23181508/6aef20fd-c521-4f55-9a0c-20a4ea7fab26">

**Comment by sweida** [comment]
<img width="916" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/23181508/3bff5288-9ff1-434d-959d-4cfdcee1e9d6">
现在1.1.7版本看到的还是无法打开弹窗

**Comment by liujuping** [comment]
在这里试一下。

https://lowcode-engine.cn/demo/demo-general/index.html

**Comment by 947291135** [comment]
> 在这里试一下。
> 
> https://lowcode-engine.cn/demo/demo-general/index.html

官方DEMO也有这类BUG，弹窗绑定是否显示变量就会复现该bug

**Comment by 947291135** [comment]
![msedge_p4eQOPivZ4](https://github.com/alibaba/lowcode-engine/assets/26854734/58b2b803-3bac-4df8-80f4-245ba74776cc)

**Comment by liujuping** [comment]
弹窗绑定是否显示变量，在值为 false 的情况下，组件控制了不显示弹窗，和引擎逻辑没有关系，符合组件逻辑预期。

不算 bug。
