### ISSUE TITLE
状态码200, 后端已配置接口支持cors跨域, 但还是显示cors错误

### ISSUE THREAD

**Issue by avocadowang** [alibaba/lowcode-engine#2063]
## **Describe the bug (required)** / **详细描述 bug（必填）**
直接点击后端提供的链接是能访问成功的, 但是配到平台上就不行, 状态码200, 后端已配置接口支持cors跨域, 但还是显示cors错误, 
response显示无法加载响应数据, 如下图

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

Steps to reproduce the behavior: / 详细复现步骤：
1. 数据源配置开发的接口
2. 报错

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
能正确的收到后端返回数据不报错

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
<img width="1020" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/18697326/78c2aaea-79ec-4732-a477-7afb0523763d">
<img width="1024" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/18697326/3f88f212-fd12-48d0-a4fa-643411738fa8">

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
版本如图
![Uploading image.png…]()
![Uploading image.png…]()

 - AliLowCodeEngine version: 1.0.18/ 低代码引擎版本
 - AliLowCodeEngineExt version: 1.0.5 / 低代码引擎扩展包版本
 - Browser [113.0.5672.126（正式版本） (x86_64)] / 浏览器版本

**Comment by avocadowang** [comment]
补充 版本截图
<img width="482" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/18697326/41af4c47-a11c-44bc-9ddd-9431c232ffc3">
<img width="1206" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/18697326/2313e633-bc25-4e69-b2ff-5b4f74fe263b">

**Comment by JackLian** [comment]
这个就是不是本项目业务范畴了，让你们后端看看是用的什么跨域配置吧，对请求侧有什么要求，结合排查一下，跨域并不是简单的服务配置了就一定work的

**Comment by LeoYuan** [comment]
For requests without credentials, the literal value "*" can be specified as a wildcard; the value tells browsers to allow requesting code from any origin to access the resource. Attempting to use the wildcard with credentials [results in an error](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials).

ref: 
- https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin
- https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS/Errors/CORSNotSupportingCredentials

**Comment by avocadowang** [comment]
补充- 通过配nginx反代解决了
<img width="662" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/18697326/da9a0947-a3f9-41dd-9626-1d4bda3a1bf4">
