### ISSUE TITLE
demo-general启动后选择器组件绑完表达式保存后切回来丢失设置值

### ISSUE THREAD

**Issue by avocadowang** [alibaba/lowcode-engine#2065]
## **Describe the bug (required)** / **详细描述 bug（必填）**
demo-general启动后选择器组件绑完表达式保存后切回来丢失设置值
A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
1.拖入选择器
2.组件配置里绑定state设置的值
3.保存代码
4.刷新或者点其他组件再点回来

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
不该丢失
---

## **Screenshots (optional)** / **bug 截图（可选）**
<img width="1633" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/18697326/add8efb6-2fda-465c-a67e-3047dc3fd13f">
<img width="1071" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/18697326/c4ca2fc6-ad9e-45b6-a329-233a7924c528">
<img width="1199" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/18697326/fd134d0d-ef04-4065-8109-6fad8abb20ee">

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.18] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.5] / 低代码引擎扩展包版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by liujuping** [comment]
可以在这里测试一下，刚刚尝试了一下，没有复现。

https://lowcode-engine.cn/demo/demo-general/index.html

**Comment by avocadowang** [comment]
升级引擎包和扩展后可以了![image](https://github.com/alibaba/lowcode-engine/assets/18697326/d07ce215-250a-42c8-8beb-5a9de3d0a01b)
