### ISSUE TITLE
setter如何获取appHelper中的数据

### ISSUE THREAD

**Issue by starsoul666** [alibaba/lowcode-engine#2066]
SelectSetter的options数据是appHelper中的constants常量，如何在setter中获取到常量数据?

**Comment by liujuping** [comment]
config.get('appHelper')

**Comment by starsoul666** [comment]
在设计模式Select组件如何响应交互，查看options选项，类似时间选择控件；设计模式是禁用了组件的交互吗，还是需要组件去实现编辑模式的交互？

**Comment by liujuping** [comment]
1.设计器禁用了部分交互
2.组件做设计模式下缺少了部分交互。

我们一般都在预览下查看响应交互。
