### ISSUE TITLE
如何实现一个Message 全局提示

### ISSUE THREAD

**Issue by taolei1990** [alibaba/lowcode-engine#2069]
// 我这边有个接口 想接口调用成功后提示成功
this.dataSourceMap['addUser'].load({
    data: {}
}).then(res => {
// 想在这里通过Message 提示 添加成功
})
  .catch(error => {});

**Comment by lyllovelemon** [comment]
如果是antd组件，

> this.dataSourceMap['addUser'].load({
> data: {}
> }).then(res => {
> window.antd.message.success("添加成功");
> })
> .catch(error => {});

**Comment by taolei1990** [comment]
> 如果是antd组件，
> 
> > this.dataSourceMap['addUser'].load({
> > data: {}
> > }).then(res => {
> > window.antd.message.success("添加成功");
> > })
> > .catch(error => {});


非常感谢 window.antd.message.success("添加成功") 可以使用
