### ISSUE TITLE
物料拖到画布之后无法在画布上选中，只能在图层上选

### ISSUE THREAD

**Issue by suiwisdom** [alibaba/lowcode-engine#2074]
https://github.com/alibaba/lowcode-engine中的antd物料clone到本地使用的时候会出现无法选中组件的问题
![image](https://github.com/alibaba/lowcode-engine/assets/24563930/792678ad-366d-49c9-919b-a47d6bce3315)
如图只能选中表单项，选中不了里面的input输入框

**Comment by JackLian** [comment]
就是这么设计的....

**Comment by suiwisdom** [comment]
问下这样设计怎么对input输入框做属性配置呢，而且直接引用@alilc/antd-lowcode-materials是可以的，只是调试https://github.com/alibaba/lowcode-materials 中的组件不能选中

**Comment by lynsun** [comment]
> 问下这样设计怎么对input输入框做属性配置呢，而且直接引用@alilc/antd-lowcode-materials是可以的，只是调试https://github.com/alibaba/lowcode-materials 中的组件不能选中

我也遇到这个问题了，求解，是不是组件本地调试自带的设计器版本过低？
