### ISSUE TITLE
高级表格 - 属性 - 分页器无法设置事件

### ISSUE THREAD

**Issue by avocadowang** [alibaba/lowcode-engine#2076]
## **Describe the bug (required)** / **详细描述 bug（必填）**

高级表格组件里开启分页器后功能没法设置对分页器的监听和一些补充操作

## **Screenshots (optional)** / **bug 截图（可选）**
<img width="420" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/18697326/a2998799-aa1d-47db-a4b9-00d2b26a46ea">

**Comment by JackLian** [comment]
物料的需求本项目大概率不会跟进，可以定制组件来实现
