### ISSUE TITLE
[Question]开发链接块组件如何在设计模式下禁止输入？

### ISSUE THREAD

**Issue by jqhr** [alibaba/lowcode-engine#2079]
我想开发一个链接块组件，开发的时候在设计模式下面点击这个组件就会跳转，我想点击来选中这个组件，怎么做呢？

**Comment by liujuping** [comment]
https://lowcode-engine.cn/site/docs/guide/expand/editor/material#%E7%BC%96%E8%BE%91%E6%80%81%E8%A7%86%E5%9B%BE

可以通过开发编辑态视图，来定制编辑态下的逻辑。
