### ISSUE TITLE
报错 Warning: Invalid DOM property `class`. Did you mean `className`

### ISSUE THREAD

**Issue by gu-xiaohui** [alibaba/lowcode-engine#208]
## **Describe the bug (required)** / **详细描述 bug（必填）**
这个svg-icon组件，引擎使用的时候给设置了class属性，会报错
![image](https://user-images.githubusercontent.com/25246071/160525186-a6ec8c3b-6a25-4978-bba7-149c1649d309.png)

![image](https://user-images.githubusercontent.com/25246071/160525134-26c90c49-e5f8-462b-b487-dc2a174783fc.png)

**Comment by LeoYuan** [comment]
某些极端场景下需要 class，先忽略吧~
