### ISSUE TITLE
[question] 为什么这里会用 action

### ISSUE THREAD

**Issue by rainke** [alibaba/lowcode-engine#2084]
https://github.com/alibaba/lowcode-engine/blob/9d2214e0fc3b70adad1717b3e2ea5281a0ad23aa/packages/designer/src/document/node/props/prop.ts#LL254C7-L254C7

**Comment by rainke** [comment]
我想了一下还是没想明白这个 action 装饰器有啥用

**Comment by liujuping** [comment]
action 本身可以带来性能优化，可以看看 mobx 相关的文档。

这里的 action 带来了什么问题吗？

**Comment by rainke** [comment]
> action 本身可以带来性能优化，可以看看 mobx 相关的文档。
> 
> 这里的 action 带来了什么问题吗？

那倒没有，只是我一直以为要改变 state 的时候才会用到 action
