### ISSUE TITLE
请问React renderer渲染器如何进行数据联动

### ISSUE THREAD

**Issue by RichadoM** [alibaba/lowcode-engine#2085]
使用@alilc/lowcode-react-renderer这个包进行渲染schema时，如何进行数据联动？

比如一个表格页，想搜索后把值更新给下方表格。或者一个表单页，填了A、B项后，C项的值会自动带出，该如何处理？

**Comment by liujuping** [comment]
一个 @alilc/lowcode-react-renderer 渲染的 schema 之间的数据联动，还是多个 @alilc/lowcode-react-renderer 渲染的 schema  之间的数据联动？

**Comment by RichadoM** [comment]
一个 renderer 渲染的 schema 中的联动

**Comment by liujuping** [comment]
那就是组件之间的联动逻辑。可以看看

demo使用文档：https://lowcode-engine.cn/site/docs/demoUsage/intro

lab 平台试用一下：https://lab.lowcode-engine.cn/

**Comment by RichadoM** [comment]
好的，感谢
