### ISSUE TITLE
希望面板提供修改插件位置的功能

### ISSUE THREAD

**Issue by starsoul666** [alibaba/lowcode-engine#2089]
官方提供的插件位置是写死的，例如：@alilc/lowcode-plugin-code-editor、plugin-undo-redo插件，位置是固定topArea，想移动插件位置展示在toolbar位置，目前没找到这个功能，只能fork源代码修改吗？

**Comment by liujuping** [comment]
可以提 PR 给插件暴露参数，通过配置参数修改插件要注册的位置信息
