### ISSUE TITLE
物料无法打包@alilc/element

### ISSUE THREAD

**Issue by 286yym** [alibaba/lowcode-engine#209]
## **Describe the bug (required)** / **详细描述 bug（必填）**
官方lowcode-materials或@alilc/element自定义物料，下载执行npm install & npm run lowcode:build ，命令执行失败

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---
无其它操作，下载安装依赖后无法正常执行dev或build命令

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---
npm run lowcode:build 命令报错
![image](https://user-images.githubusercontent.com/47840563/160527058-22939224-a01c-4578-ada9-4bb90928e1ac.png)
npm run lowcode:dev  命令报错

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

**Comment by 286yym** [comment]
![Uploading image.png…]()

**Comment by mark-ck** [comment]
📢 Windows environment must use [WSL](https://docs.microsoft.com/zh-cn/windows/wsl/install), other terminals are not guaranteed to work normally

**Comment by 286yym** [comment]
![image](https://user-images.githubusercontent.com/47840563/160545451-231f9622-a1b0-472b-9760-1b1dd9586fe4.png)
使用WSL运行，也是版本有误，能具体使用哪个版本的node吗，我当"node" ->  v14.19.0,  版本需求范围"node": ">=14.17.0 <16"

**Comment by LeoYuan** [comment]
上边都写了怎么处理了。。。

```npm rebuild node-sass```

**Comment by 286yym** [comment]
好的，谢谢，已解决，本质错误的解决处理，是使用WSL运行
