### ISSUE TITLE
Formily物料无法使用

### ISSUE THREAD

**Issue by hyy984750073** [alibaba/lowcode-engine#2090]
## **Describe the bug (required)** / **详细描述 bug（必填）**
Formily物料报错无法使用

-----

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1. 打开 [demo](https://lowcode-engine.cn/demo/demo-antd-pro-with-formily/index.html)；
2. 组件库-->Formily组件-->拖拽到 编辑器；

----

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
正常且正确显示并使用组件

-----

## **Screenshots (optional)** / **bug 截图（可选）**
![image](https://github.com/alibaba/lowcode-engine/assets/22184934/572a898d-6be4-4887-81f2-6c1e8b2e5204)

**Comment by liujuping** [comment]
这里文案说明了，要先拖拽 form 组件，再拖拽其他的组件。
