### ISSUE TITLE
低代码编辑器中，打开源码面板后，弹窗绑定变量时，大纲树点击弹框显示按钮，弹窗无法显示

### ISSUE THREAD

**Issue by 947291135** [alibaba/lowcode-engine#2092]
每次点开js【源码面板】后，再打开大纲树，模态视图层的按钮失效，弹窗无法再次打开，必现 #2062 
必须时弹窗绑定变量时才会出现，在官方demo 也会出现该问题
![image](https://github.com/alibaba/lowcode-engine/assets/26854734/52ae773c-3dc7-4b48-8efb-52cb788fe2b7)
![image](https://github.com/alibaba/lowcode-engine/assets/26854734/c895406e-6fba-48bd-a752-76cb07abfca9)

**Comment by liujuping** [comment]
这里弹窗的是否显示，如果是 false 的话，是组件层面控制的，相当于组件在这个条件下不再显示弹窗。

符合预期

**Comment by 947291135** [comment]
> 这里弹窗的是否显示，如果是 false 的话，是组件层面控制的，相当于弹窗组件在这个条件下不再显示弹窗。
> 
> 符合预期

但是以前弹框绑定变量后，就算是为false时，点击大纲树弹框也会显示欸，这样比较方便在低代码编辑器查看弹窗内容。

**Comment by liujuping** [comment]
试了一下，至少半年前的版本都是不会显示弹窗。
