### ISSUE TITLE
内网部署下，自定义的组件库在assets.json中的cdn地址无法访问，通过什么方式实现本地链接？

### ISSUE THREAD

**Issue by wangyu142857** [alibaba/lowcode-engine#2097]
![image](https://github.com/alibaba/lowcode-engine/assets/24771813/bf64007f-5f19-476d-881c-85ff4019563d)

**Comment by liujuping** [comment]
看看内部其他的资源是怎么实现的本地访问，

**Comment by wangyu142857** [comment]
> 看看内部其他的资源是怎么实现的本地访问，

其他资源是比如说图片一是放在assets内通过 import 获取，一是放在public下访问。组件库是另外一个工程，目前构建后的文件我只能通过复制一份到public下，但是这样我每次改动组件库都得复制一遍

**Comment by wangyu142857** [comment]
有什么方式可以让组件库跟项目放在一起，不需要每次都构建后再复制出来？

**Comment by eternalsky** [comment]
感觉重复的事情可以通过脚本化来做

**Comment by liujuping** [comment]
可以使用 webpack 之类的构建工具，自定义打包/构建项目放到指定目录下。

怎么实现需要自己根据项目研究改造了。
