### ISSUE TITLE
ice集成CodeEditorPlugin，页面出错

### ISSUE THREAD

**Issue by Gllidan** [alibaba/lowcode-engine#2103]
1. import  @alilc/lowcode-plugin-code-generator 后，编译出错
（Module not found: Error: Can't resolve 'assert' in 'E:\product\bi_analytics_ui\node_modules\.pnpm\regenerator-transform@0.15.1\node_modules\regenerator-transform\lib'

BREAKING CHANGE: webpack < 5 used to include polyfills for node.js core modules by default.
This is no longer the case. Verify if you need this module and configure a polyfill for it.

If you want to include a polyfill, you need to:
	- add a fallback 'resolve.fallback: { "assert": require.resolve("assert/") }'
	- install 'assert'
If you don't want to include a polyfill, you can use an empty module like this:
	resolve.fallback: { "assert": false }）
2. 安装 assert，运行项目
3. 打开引擎页面，执行报错
![image](https://github.com/alibaba/lowcode-engine/assets/27495460/e56b5a30-5562-4579-a43c-1f507741f904)
![image](https://github.com/alibaba/lowcode-engine/assets/27495460/bacde988-9443-4f33-b473-f836dc54da16)

**Comment by Gllidan** [comment]
解决了，UMD包版本问题。。

**Comment by T95tongT** [comment]
请问， 如何解决的呀
