### ISSUE TITLE
请问一下自定义组件接入支持 hooks 写法吗？

### ISSUE THREAD

**Issue by monkeying-boy** [alibaba/lowcode-engine#2104]
请问一下自定义组件支持 hooks 写法吗？我看官方示例的组件大部分都是以 class 写法。如果使用 hooks 写法会导致一些其它问题吗？

**Comment by liujuping** [comment]
没有做新版本 react 的适配，有人用过 hooks，部分 hooks 会导致组件无法选中。

**Comment by monkeying-boy** [comment]
> 没有做新版本 react 的适配，有人用过 hooks，部分 hooks 会导致组件无法选中。

是由于 hooks 语法导致无法选中，还是由于 meta.ts 配置导致无法选中？

**Comment by liujuping** [comment]
hooks 写法没有办法获取 ref，

1.获取不到 ref，没有办法选中

2.this.$('id') 也是根据 ref 来的，在 hooks 下无法正常使用。

**Comment by yz1311** [comment]
> 没有做新版本 react 的适配，有人用过 hooks，部分 hooks 会导致组件无法选中。

原来是这个原因...

**Comment by monkeying-boy** [comment]
> hooks 写法没有办法获取 ref，
> 
> 1.获取不到 ref，没有办法选中
> 
> 2.this.$('id') 也是根据 ref 来的，在 hooks 下无法正常使用。



后续会支持 hooks 写法吗？

**Comment by monkeying-boy** [comment]
自定义的组件使用了 `forwardRef` api ，如果 return 的组件不加上 `ref={ref}` 会导致在画布中无法选中，加上 `ref={ref}` 就可以在画布中选中了。

目前使用的 hooks 有： `useState`、`useEffect`、`useImperativeHandle`。目前没有遇到问题 

```
//  不能在画布中选中
export const Test = forwardRef((props,ref) => {
  return (
   //  Component  为需要返回的自定义组件
    <Component />
  )
})
```

```
// 能正常选中
export const Test = forwardRef((props,ref) => {
  return (
    <Component
      ref={ref} 
    />
  )
})
```
