### ISSUE TITLE
希望增加一个关于当组件找不到时的回调事件

### ISSUE THREAD

**Issue by rongrongt** [alibaba/lowcode-engine#2119]
目前页面偶现会出现组件找不到的情况，刷新一次就好了。当前ReactRenderer已经有关于当组件找不到时，可以通过参数自定义展示文案。希望通过给ReactRenderer主动暴露出组件找不到事件回调函数。可以来根据回调来手动刷新页面或者其他操作等

![image](https://github.com/alibaba/lowcode-engine/assets/21823510/96721ddb-7cee-4b83-8b8c-141a37e2d494)

**Comment by liujuping** [comment]
可以通过 notFoundComponent 写一个自定义组件，这个组件可以自己实现回调。例如：可以在这个组件的生命周期里面发送事件。
