### ISSUE TITLE
lowcode-demo预览失败，启动报js、css缺失

### ISSUE THREAD

**Issue by Gllidan** [alibaba/lowcode-engine#2124]
1. 运行环境：
1）window: wsl \ git
2)  node: 16.18

3) 包管理：npm \ pnpm

3.  操作步骤
1）npm i \ pnpm i 
2) 补齐缺失依赖
3）启动本地服务成功
4）配置组件点击预览
5）提示错误
![image](https://github.com/alibaba/lowcode-engine/assets/27495460/092ca08f-a60d-41a5-a918-5ccbbe3b84fc)

4. 几种方式都尝试过，均无法启动预览（项目原先可以预览，突然失败）

**Comment by LeoYuan** [comment]
本地启动项目后，访问 http://localhost:5556/demo-general/index.html， 需要在本地将 index.ejs / preview.html 里的资源访问路径做如下修改才可访问，知道是怎么回事么？

![image](https://github.com/alibaba/lowcode-engine/assets/1195765/0cce4bb8-3e4d-4c7f-a116-4ae869d5df46)

@liujuping 

![image](https://github.com/alibaba/lowcode-engine/assets/1195765/32c5166e-ccda-4b3a-900b-1400e109ed84)
![image](https://github.com/alibaba/lowcode-engine/assets/1195765/c698ef10-eba3-49a1-ae3c-8e2f18549e9a)

**Comment by Gllidan** [comment]
有点不太理解prevView的执行流程。
我点击预览，不应该是根据build配置的entry进入到对应demo版本的prevView页面吗。
我本地试了好像也没有加载prevView.tsx文件。
另外 对应的模板参数及js \ css 怎么生成的，这块有开源吗，能否指导下是看哪个包的代码，想了解下流程。

**Comment by LeoYuan** [comment]
明白了。。。lowcode-demo 是一个 monorepo，理论上需要进入每一个 scenario 目录下，执行 npm i && npm start，不能在根目录下执行了

**Comment by LeoYuan** [comment]
> 有点不太理解prevView的执行流程。 我点击预览，不应该是根据build配置的entry进入到对应demo版本的prevView页面吗。 我本地试了好像也没有加载prevView.tsx文件。 另外 对应的模板参数及js \ css 怎么生成的，这块有开源吗，能否指导下是看哪个包的代码，想了解下流程。

你都拉 lowcode-demo 的代码了。。。然后你问代码在哪😄？

**Comment by Gllidan** [comment]
> > 有点不太理解prevView的执行流程。 我点击预览，不应该是根据build配置的entry进入到对应demo版本的prevView页面吗。 我本地试了好像也没有加载prevView.tsx文件。 另外 对应的模板参数及js \ css 怎么生成的，这块有开源吗，能否指导下是看哪个包的代码，想了解下流程。
> 
> 你都拉 lowcode-demo 的代码了。。。然后你问代码在哪😄？

哈哈，因为调试了demo包里得代码，貌似都没执行到，而且看着只是最外层的逻辑

**Comment by Gllidan** [comment]
> 明白了。。。lowcode-demo 是一个 monorepo，理论上需要进入每一个 scenario 目录下，执行 npm i && npm start，不能在根目录下执行了

这就试试

**Comment by Gllidan** [comment]
确实可以了，子包独立运行就没问题  @LeoYuan 感谢
