### ISSUE TITLE
[Question] children与props.children的区别?

### ISSUE THREAD

**Issue by eightHundreds** [alibaba/lowcode-engine#2125]
![image](https://github.com/alibaba/lowcode-engine/assets/18695431/59a95845-6bf0-4fcb-a330-1fe4686eb8dc)

什么时候用children存放子元素,什么时候用props.children?

**Comment by LeoYuan** [comment]
通常情况（树分支节点） children 都是 { componentName: 'Xxx', children:[ ... ] } 的结构，对于叶子结点，会出现字符串类型 / 变量类型，比如 { componentName: 'Text', children: 'Haha' }~

props.children 没特别处理过，应该是当成普通属性直接透传给组件~
