### ISSUE TITLE
求助ReactRenderer的components属性

### ISSUE THREAD

**Issue by zxlaole** [alibaba/lowcode-engine#2127]
我有需求将设计器生成的schema自定义渲染，已经知道可以通过ReactRender渲染shema，但这个组件有一个components参数，文档中是需要手写的，而实际场景中是由物料配置自动生成的。

const components = {
  Button,
};

ReactDOM.render((
  <ReactRenderer
    schema={schema}
    components={components}
  />
), document.getElementById('root'));

我想知道从哪里能拿到引擎根据配置的物料，已经动态生成的组件列表传件去，能否从引擎的上下文中得到。

**Comment by LeoYuan** [comment]
https://github.com/alibaba/lowcode-demo/blob/4d1bfef87a42b2633eca0732932239b785a5a36a/demo-basic-antd/src/preview.tsx#L48

看看例子就明白了~

**Comment by zxlaole** [comment]
我这个所谓的渲染实际上是设计时，我自己实现了一个设计器，在设计状态下引擎是否已经做了这件事情，preview的这个我已经实现过，只是认为可能在重复做这件事。

**Comment by LeoYuan** [comment]
底层一定是调用 buildComponents 这个函数，无非是在哪里调用~

ReactSimulatorRenderer: https://github.com/alibaba/lowcode-engine/blob/d64da1e065aa814d221317beead9c9e32f874472/packages/react-simulator-renderer/src/renderer.ts#L362-L372
Preview: https://github.com/alibaba/lowcode-demo/blob/4d1bfef87a42b2633eca0732932239b785a5a36a/demo-basic-antd/src/preview.tsx#L48

**Comment by zxlaole** [comment]
好的，那我先这样用，感谢支持！

**Comment by zxlaole** [comment]
你好还在吗，我还是疑惑buildComponents的第二个参数，componentsMap从哪里获取呢，您给发的例子中是在storeage中获取的，我现在实现的是设计器功能，schema还没有保存。

**Comment by zxlaole** [comment]
而且我想在页面初始化的时候获取组件的全集。
我偿试从project.currentDocument!.getComponentsMap()，这样只有文档中已增加组件，不全。
