### ISSUE TITLE
低代码demo-general中修改@alilc/lowcode-engine这个包后，修改部分不生效

### ISSUE THREAD

**Issue by little-yaonv** [alibaba/lowcode-engine#2128]
由于业务需要，对@alilc/lowcode-engine这个npm包做了部分修改，但是本地调试发现不生效。
然后将修改后的@alilc/lowcode-engine包，进行重命名并发布到npm上，更改index.ts中引用这个包的路径
重新启动项目，可以看到扫描了lowcode-engine包的修改部分，但是浏览器出现了以下报错：
![image](https://github.com/alibaba/lowcode-engine/assets/75791730/620f5544-80e3-4b37-8d2b-db1402f9c0f6)
查看官方文档得知要在build.json文件中进行如下配置：
![image](https://github.com/alibaba/lowcode-engine/assets/75791730/408dbc06-4c9b-401e-96de-b59fdf98126f)
但是在build.json里配置之后，更改的内容就不生效
请问如何让@alilc/lowcode-engine这个npm包中修改的内容生效呢

**Comment by LeoYuan** [comment]
你看看 html 里是不是用的你自己的 umd 文件

**Comment by JackLian** [comment]
只能通过umd方式使用，不支持npm直接使用

**Comment by little-yaonv** [comment]
明白了，感谢两位大佬！
