### ISSUE TITLE
官网综合场景demo出码时在线预览bug

### ISSUE THREAD

**Issue by tcj98** [alibaba/lowcode-engine#2134]
## **Describe the bug (required)** / **详细描述 bug（必填）**

官网综合场景demo出码时，在线预览中提示：Could not find dependency: '@alifd/pro-layout' relative to '/src/index.js'

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
1.官网打开综合场景demo（https://lowcode-engine.cn/demo/demo-general/index.html）
2.点击出码
3.等待出码在线预览

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

能正常完成出码，并且在线预览功能完整

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
![image](https://github.com/alibaba/lowcode-engine/assets/109788621/55656abd-62fe-45c1-a14a-ae00c78ce99c)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本
![image](https://github.com/alibaba/lowcode-engine/assets/109788621/992a5f7e-6135-4d88-9b1d-00aadcb042a0)

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by LeoYuan** [comment]
哪里用到了 pro-layout？不一定支持出码

**Comment by tcj98** [comment]
> 

不清楚，就是官方demo直接点击出码就会有这个bug

**Comment by trcAnew** [comment]
这个问题解决了吗

**Comment by trcAnew** [comment]
我也遇到了这个问题 找不到具体原因
