### ISSUE TITLE
antd物料中的form.list 如何使用，能否提供一份schema参考

### ISSUE THREAD

**Issue by wssgchungang** [alibaba/lowcode-engine#2140]
## **Describe the bug (required)** / **详细描述 bug（必填）**

antd物料中的form.list 如何使用，能否提供一份schema参考

---

**Comment by proclml** [comment]
我是这么玩的

Form.List 把 children 改成 content, 因为 children 没法做成给子组件传参
```typescript
(Form as any).List = class List extends Component {
  render(): React.ReactNode {
    const { content, children, ...rest } = this.props as any;
    return <OriginalForm.List {...rest}>{content}</OriginalForm.List>;
  }
};

```

schema:
```
{
  "componentName": "Component",
  "id": "node_ocliljefmd1",
  "props": {
    "ref": "outerView"
  },
  "state": {
    "formData": {
      "type": "JSExpression",
      "value": "{\n  int: 1,\n  float: 'b',\n  array: [{\n    name: 'bob',\n    age: 12,\n    valid: true\n  }, {\n    name: 'ami',\n    age: 13,\n    valid: false\n  }]\n}"
    }
  },
  "dataSource": {
    "list": []
  },
  "css": "body {\n  font-size: 12px;\n}",
  "methods": {
    "testFunc": {
      "type": "JSFunction",
      "value": "function testFunc() {\n  console.log('test func');\n  return /*#__PURE__*/React.createElement(\"div\", null, this.state.test);\n}",
      "source": "function testFunc() {\n  console.log('test func');\n  return <div>\n        {this.state.test}\n      </div>;\n}"
    }
  },
  "lifeCycles": {},
  "title": "自定义低代码组件",
  "isLocked": false,
  "condition": true,
  "fileName": "/",
  "hidden": true,
  "conditionGroup": "",
  "originCode": "class Page extends Component {\n  state = {\n    formData: {\n      int: 1,\n      float: 'b',\n      array: [\n        {\n          name: 'bob',\n          age: 12,\n          valid: true,\n        },\n        {\n          name: 'ami',\n          age: 13,\n          valid: false,\n        },\n      ]\n    }\n  }\n  \n  testFunc() {\n    console.log('test func');\n    return <div>\n        {this.state.test}\n      </div>;\n  }\n}",
  "children": [
    {
      "componentName": "Form",
      "id": "node_ocliljefoli",
      "props": {
        "labelCol": {
          "span": 6
        },
        "wrapperCol": {
          "span": 14
        },
        "onValuesChange": {
          "type": "JSExpression",
          "value": "function() {\n      const self = this;\n      try {\n        return (function onValuesChange(changedValues, allValues) {\n  console.log('onValuesChange', changedValues, allValues);\n}).apply(self, arguments);\n      } catch(e) {\n        logger.warn('call function which parsed by lowcode failed: ', e);\n        return e.message;\n      }\n    }"
        },
        "onFinish": {
          "type": "JSExpression",
          "value": "function() {\n      const self = this;\n      try {\n        return (function onFinish(values) {\n  console.log('onFinish', values);\n}).apply(self, arguments);\n      } catch(e) {\n        logger.warn('call function which parsed by lowcode failed: ', e);\n        return e.message;\n      }\n    }"
        },
        "onFinishFailed": {
          "type": "JSExpression",
          "value": "function() {\n      const self = this;\n      try {\n        return (function onFinishFailed({ values, errorFields, outOfDate }) {\n  console.log('onFinishFailed', values, errorFields, outOfDate);\n}).apply(self, arguments);\n      } catch(e) {\n        logger.warn('call function which parsed by lowcode failed: ', e);\n        return e.message;\n      }\n    }"
        },
        "name": "basic",
        "ref": "form_g52u",
        "values": {
          "type": "JSExpression",
          "value": "this.state.formData"
        },
        "hideRequiredMark": false,
        "labelAlign": "right",
        "preserve": true,
        "scrollToFirstError": true,
        "size": "middle",
        "validateMessages": {
          "required": "'${name}' 不能为空"
        },
        "colon": true
      },
      "hidden": false,
      "title": "",
      "isLocked": false,
      "condition": true,
      "conditionGroup": "",
      "children": [
        {
          "componentName": "Form.List",
          "id": "node_ocliljehpk4",
          "props": {
            "name": "array",
            "content": {
              "type": "JSSlot",
              "params": [
                "fields",
                "operation",
                "meta"
              ],
              "value": [
                {
                  "componentName": "Row",
                  "id": "node_ocliljehpk6",
                  "props": {
                    "wrap": true,
                    "_unsafe_MixedSetter____loop____select": "VariableSetter"
                  },
                  "hidden": false,
                  "title": "",
                  "isLocked": false,
                  "condition": true,
                  "conditionGroup": "",
                  "loop": {
                    "type": "JSExpression",
                    "value": "this.fields"
                  },
                  "loopArgs": [
                    null,
                    null
                  ],
                  "children": [
                    {
                      "componentName": "Col",
                      "id": "node_ocliljehpk7",
                      "props": {
                        "span": 8,
                        "order": 0
                      },
                      "hidden": false,
                      "title": "",
                      "isLocked": false,
                      "condition": true,
                      "conditionGroup": "",
                      "children": [
                        {
                          "componentName": "Form.Item",
                          "id": "node_ocliljehpk9",
                          "props": {
                            "label": "名字",
                            "trigger": "onChange",
                            "colon": true,
                            "required": false,
                            "hasFeedback": false,
                            "valuePropName": "value",
                            "getValueFromEvent": {
                              "type": "JSFunction"
                            },
                            "getValueProps": {
                              "type": "JSFunction"
                            },
                            "name": {
                              "type": "JSExpression",
                              "value": "[this.item.name, 'name']"
                            }
                          },
                          "hidden": false,
                          "title": "",
                          "isLocked": false,
                          "condition": true,
                          "conditionGroup": "",
                          "children": [
                            {
                              "componentName": "Input",
                              "id": "node_ocliljej241",
                              "props": {
                                "placeholder": "请输入",
                                "bordered": true,
                                "type": "text",
                                "size": "middle",
                                "onChange": {
                                  "type": "JSFunction"
                                },
                                "onPressEnter": {
                                  "type": "JSFunction"
                                },
                                "onFocus": {
                                  "type": "JSFunction"
                                },
                                "onKeyDown": {
                                  "type": "JSFunction"
                                },
                                "onKeyPress": {
                                  "type": "JSFunction"
                                },
                                "onKeyUp": {
                                  "type": "JSFunction"
                                },
                                "onBlur": {
                                  "type": "JSFunction"
                                }
                              },
                              "hidden": false,
                              "title": "",
                              "isLocked": false,
                              "condition": true,
                              "conditionGroup": ""
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "componentName": "Col",
                      "id": "node_ocliljehpk8",
                      "props": {
                        "span": 8,
                        "order": 0
                      },
                      "hidden": false,
                      "title": "",
                      "isLocked": false,
                      "condition": true,
                      "conditionGroup": "",
                      "children": [
                        {
                          "componentName": "Form.Item",
                          "id": "node_ocliljehpka",
                          "props": {
                            "label": "年龄",
                            "trigger": "onChange",
                            "colon": true,
                            "required": false,
                            "hasFeedback": false,
                            "valuePropName": "value",
                            "getValueFromEvent": {
                              "type": "JSFunction"
                            },
                            "getValueProps": {
                              "type": "JSFunction"
                            },
                            "name": {
                              "type": "JSExpression",
                              "value": "[this.item.name, 'age']"
                            }
                          },
                          "hidden": false,
                          "title": "",
                          "isLocked": false,
                          "condition": true,
                          "conditionGroup": "",
                          "children": [
                            {
                              "componentName": "InputNumber",
                              "id": "node_ocliljej242",
                              "props": {
                                "placeholder": "请输入",
                                "controls": true,
                                "bordered": true,
                                "formatter": {
                                  "type": "JSFunction",
                                  "value": "function (value, info) {\n            return value;\n          }"
                                },
                                "parser": {
                                  "type": "JSFunction",
                                  "value": "function (value) {\n            return value;\n          }"
                                },
                                "keyboard": true,
                                "size": "middle",
                                "onChange": {
                                  "type": "JSFunction",
                                  "value": "function (value) {}"
                                },
                                "onPressEnter": {
                                  "type": "JSFunction",
                                  "value": "function (e) {}"
                                },
                                "onStep": {
                                  "type": "JSFunction",
                                  "value": "function (value, info) {}"
                                }
                              },
                              "hidden": false,
                              "title": "",
                              "isLocked": false,
                              "condition": true,
                              "conditionGroup": ""
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "componentName": "Col",
                      "id": "node_ocliljeidv1",
                      "props": {
                        "span": 8,
                        "order": 0
                      },
                      "hidden": false,
                      "title": "",
                      "isLocked": false,
                      "condition": true,
                      "conditionGroup": "",
                      "children": [
                        {
                          "componentName": "Form.Item",
                          "id": "node_ocliljeidv2",
                          "props": {
                            "label": "男生",
                            "trigger": "onChange",
                            "colon": true,
                            "required": false,
                            "hasFeedback": false,
                            "valuePropName": "checked",
                            "getValueFromEvent": {
                              "type": "JSFunction"
                            },
                            "getValueProps": {
                              "type": "JSFunction"
                            },
                            "name": {
                              "type": "JSExpression",
                              "value": "[this.item.name, 'valid']"
                            }
                          },
                          "hidden": false,
                          "title": "",
                          "isLocked": false,
                          "condition": true,
                          "conditionGroup": "",
                          "children": [
                            {
                              "componentName": "Switch",
                              "id": "node_ocliljej243",
                              "props": {
                                "defaultChecked": true,
                                "checked": false,
                                "autoFocus": false,
                                "disabled": false,
                                "loading": false
                              },
                              "hidden": false,
                              "title": "",
                              "isLocked": false,
                              "condition": true,
                              "conditionGroup": ""
                            }
                          ]
                        }
                      ]
                    },
                    {
                      "componentName": "Button",
                      "id": "node_ocliljej245",
                      "props": {
                        "type": "primary",
                        "children": "删除",
                        "htmlType": "button",
                        "size": "middle",
                        "shape": "default",
                        "onClick": {
                          "type": "JSFunction",
                          "value": "function(e) {\r\n  this.operation.remove(this.item.name)\r\n}"
                        }
                      },
                      "hidden": false,
                      "title": "",
                      "isLocked": false,
                      "condition": true,
                      "conditionGroup": ""
                    }
                  ]
                },
                {
                  "componentName": "Button",
                  "id": "node_ocliljej244",
                  "props": {
                    "type": "default",
                    "children": "添加",
                    "htmlType": "button",
                    "size": "middle",
                    "shape": "default",
                    "block": true,
                    "onClick": {
                      "type": "JSFunction",
                      "value": "function(e) {\r\n  this.operation.add()\r\n}"
                    }
                  },
                  "hidden": false,
                  "title": "",
                  "isLocked": false,
                  "condition": true,
                  "conditionGroup": ""
                }
              ],
              "id": "node_ocliljehpk5"
            }
          },
          "hidden": false,
          "title": "",
          "isLocked": false,
          "condition": true,
          "conditionGroup": ""
        }
      ]
    }
  ]
}
```

效果：
![1](https://github.com/alibaba/lowcode-engine/assets/38473196/2a1475bd-0b22-4898-b747-853cf983b7cc)

**Comment by wssgchungang** [comment]
> 我是这么玩的
> 
> Form.List 把 children 改成 content, 因为 children 没法做成给子组件传参
> 
> ```ts
> (Form as any).List = class List extends Component {
>   render(): React.ReactNode {
>     const { content, children, ...rest } = this.props as any;
>     return <OriginalForm.List {...rest}>{content}</OriginalForm.List>;
>   }
> };
> ```
> 
> schema:
> 
> ```
> {
>   "componentName": "Component",
>   "id": "node_ocliljefmd1",
>   "props": {
>     "ref": "outerView"
>   },
>   "state": {
>     "formData": {
>       "type": "JSExpression",
>       "value": "{\n  int: 1,\n  float: 'b',\n  array: [{\n    name: 'bob',\n    age: 12,\n    valid: true\n  }, {\n    name: 'ami',\n    age: 13,\n    valid: false\n  }]\n}"
>     }
>   },
>   "dataSource": {
>     "list": []
>   },
>   "css": "body {\n  font-size: 12px;\n}",
>   "methods": {
>     "testFunc": {
>       "type": "JSFunction",
>       "value": "function testFunc() {\n  console.log('test func');\n  return /*#__PURE__*/React.createElement(\"div\", null, this.state.test);\n}",
>       "source": "function testFunc() {\n  console.log('test func');\n  return <div>\n        {this.state.test}\n      </div>;\n}"
>     }
>   },
>   "lifeCycles": {},
>   "title": "自定义低代码组件",
>   "isLocked": false,
>   "condition": true,
>   "fileName": "/",
>   "hidden": true,
>   "conditionGroup": "",
>   "originCode": "class Page extends Component {\n  state = {\n    formData: {\n      int: 1,\n      float: 'b',\n      array: [\n        {\n          name: 'bob',\n          age: 12,\n          valid: true,\n        },\n        {\n          name: 'ami',\n          age: 13,\n          valid: false,\n        },\n      ]\n    }\n  }\n  \n  testFunc() {\n    console.log('test func');\n    return <div>\n        {this.state.test}\n      </div>;\n  }\n}",
>   "children": [
>     {
>       "componentName": "Form",
>       "id": "node_ocliljefoli",
>       "props": {
>         "labelCol": {
>           "span": 6
>         },
>         "wrapperCol": {
>           "span": 14
>         },
>         "onValuesChange": {
>           "type": "JSExpression",
>           "value": "function() {\n      const self = this;\n      try {\n        return (function onValuesChange(changedValues, allValues) {\n  console.log('onValuesChange', changedValues, allValues);\n}).apply(self, arguments);\n      } catch(e) {\n        logger.warn('call function which parsed by lowcode failed: ', e);\n        return e.message;\n      }\n    }"
>         },
>         "onFinish": {
>           "type": "JSExpression",
>           "value": "function() {\n      const self = this;\n      try {\n        return (function onFinish(values) {\n  console.log('onFinish', values);\n}).apply(self, arguments);\n      } catch(e) {\n        logger.warn('call function which parsed by lowcode failed: ', e);\n        return e.message;\n      }\n    }"
>         },
>         "onFinishFailed": {
>           "type": "JSExpression",
>           "value": "function() {\n      const self = this;\n      try {\n        return (function onFinishFailed({ values, errorFields, outOfDate }) {\n  console.log('onFinishFailed', values, errorFields, outOfDate);\n}).apply(self, arguments);\n      } catch(e) {\n        logger.warn('call function which parsed by lowcode failed: ', e);\n        return e.message;\n      }\n    }"
>         },
>         "name": "basic",
>         "ref": "form_g52u",
>         "values": {
>           "type": "JSExpression",
>           "value": "this.state.formData"
>         },
>         "hideRequiredMark": false,
>         "labelAlign": "right",
>         "preserve": true,
>         "scrollToFirstError": true,
>         "size": "middle",
>         "validateMessages": {
>           "required": "'${name}' 不能为空"
>         },
>         "colon": true
>       },
>       "hidden": false,
>       "title": "",
>       "isLocked": false,
>       "condition": true,
>       "conditionGroup": "",
>       "children": [
>         {
>           "componentName": "Form.List",
>           "id": "node_ocliljehpk4",
>           "props": {
>             "name": "array",
>             "content": {
>               "type": "JSSlot",
>               "params": [
>                 "fields",
>                 "operation",
>                 "meta"
>               ],
>               "value": [
>                 {
>                   "componentName": "Row",
>                   "id": "node_ocliljehpk6",
>                   "props": {
>                     "wrap": true,
>                     "_unsafe_MixedSetter____loop____select": "VariableSetter"
>                   },
>                   "hidden": false,
>                   "title": "",
>                   "isLocked": false,
>                   "condition": true,
>                   "conditionGroup": "",
>                   "loop": {
>                     "type": "JSExpression",
>                     "value": "this.fields"
>                   },
>                   "loopArgs": [
>                     null,
>                     null
>                   ],
>                   "children": [
>                     {
>                       "componentName": "Col",
>                       "id": "node_ocliljehpk7",
>                       "props": {
>                         "span": 8,
>                         "order": 0
>                       },
>                       "hidden": false,
>                       "title": "",
>                       "isLocked": false,
>                       "condition": true,
>                       "conditionGroup": "",
>                       "children": [
>                         {
>                           "componentName": "Form.Item",
>                           "id": "node_ocliljehpk9",
>                           "props": {
>                             "label": "名字",
>                             "trigger": "onChange",
>                             "colon": true,
>                             "required": false,
>                             "hasFeedback": false,
>                             "valuePropName": "value",
>                             "getValueFromEvent": {
>                               "type": "JSFunction"
>                             },
>                             "getValueProps": {
>                               "type": "JSFunction"
>                             },
>                             "name": {
>                               "type": "JSExpression",
>                               "value": "[this.item.name, 'name']"
>                             }
>                           },
>                           "hidden": false,
>                           "title": "",
>                           "isLocked": false,
>                           "condition": true,
>                           "conditionGroup": "",
>                           "children": [
>                             {
>                               "componentName": "Input",
>                               "id": "node_ocliljej241",
>                               "props": {
>                                 "placeholder": "请输入",
>                                 "bordered": true,
>                                 "type": "text",
>                                 "size": "middle",
>                                 "onChange": {
>                                   "type": "JSFunction"
>                                 },
>                                 "onPressEnter": {
>                                   "type": "JSFunction"
>                                 },
>                                 "onFocus": {
>                                   "type": "JSFunction"
>                                 },
>                                 "onKeyDown": {
>                                   "type": "JSFunction"
>                                 },
>                                 "onKeyPress": {
>                                   "type": "JSFunction"
>                                 },
>                                 "onKeyUp": {
>                                   "type": "JSFunction"
>                                 },
>                                 "onBlur": {
>                                   "type": "JSFunction"
>                                 }
>                               },
>                               "hidden": false,
>                               "title": "",
>                               "isLocked": false,
>                               "condition": true,
>                               "conditionGroup": ""
>                             }
>                           ]
>                         }
>                       ]
>                     },
>                     {
>                       "componentName": "Col",
>                       "id": "node_ocliljehpk8",
>                       "props": {
>                         "span": 8,
>                         "order": 0
>                       },
>                       "hidden": false,
>                       "title": "",
>                       "isLocked": false,
>                       "condition": true,
>                       "conditionGroup": "",
>                       "children": [
>                         {
>                           "componentName": "Form.Item",
>                           "id": "node_ocliljehpka",
>                           "props": {
>                             "label": "年龄",
>                             "trigger": "onChange",
>                             "colon": true,
>                             "required": false,
>                             "hasFeedback": false,
>                             "valuePropName": "value",
>                             "getValueFromEvent": {
>                               "type": "JSFunction"
>                             },
>                             "getValueProps": {
>                               "type": "JSFunction"
>                             },
>                             "name": {
>                               "type": "JSExpression",
>                               "value": "[this.item.name, 'age']"
>                             }
>                           },
>                           "hidden": false,
>                           "title": "",
>                           "isLocked": false,
>                           "condition": true,
>                           "conditionGroup": "",
>                           "children": [
>                             {
>                               "componentName": "InputNumber",
>                               "id": "node_ocliljej242",
>                               "props": {
>                                 "placeholder": "请输入",
>                                 "controls": true,
>                                 "bordered": true,
>                                 "formatter": {
>                                   "type": "JSFunction",
>                                   "value": "function (value, info) {\n            return value;\n          }"
>                                 },
>                                 "parser": {
>                                   "type": "JSFunction",
>                                   "value": "function (value) {\n            return value;\n          }"
>                                 },
>                                 "keyboard": true,
>                                 "size": "middle",
>                                 "onChange": {
>                                   "type": "JSFunction",
>                                   "value": "function (value) {}"
>                                 },
>                                 "onPressEnter": {
>                                   "type": "JSFunction",
>                                   "value": "function (e) {}"
>                                 },
>                                 "onStep": {
>                                   "type": "JSFunction",
>                                   "value": "function (value, info) {}"
>                                 }
>                               },
>                               "hidden": false,
>                               "title": "",
>                               "isLocked": false,
>                               "condition": true,
>                               "conditionGroup": ""
>                             }
>                           ]
>                         }
>                       ]
>                     },
>                     {
>                       "componentName": "Col",
>                       "id": "node_ocliljeidv1",
>                       "props": {
>                         "span": 8,
>                         "order": 0
>                       },
>                       "hidden": false,
>                       "title": "",
>                       "isLocked": false,
>                       "condition": true,
>                       "conditionGroup": "",
>                       "children": [
>                         {
>                           "componentName": "Form.Item",
>                           "id": "node_ocliljeidv2",
>                           "props": {
>                             "label": "男生",
>                             "trigger": "onChange",
>                             "colon": true,
>                             "required": false,
>                             "hasFeedback": false,
>                             "valuePropName": "checked",
>                             "getValueFromEvent": {
>                               "type": "JSFunction"
>                             },
>                             "getValueProps": {
>                               "type": "JSFunction"
>                             },
>                             "name": {
>                               "type": "JSExpression",
>                               "value": "[this.item.name, 'valid']"
>                             }
>                           },
>                           "hidden": false,
>                           "title": "",
>                           "isLocked": false,
>                           "condition": true,
>                           "conditionGroup": "",
>                           "children": [
>                             {
>                               "componentName": "Switch",
>                               "id": "node_ocliljej243",
>                               "props": {
>                                 "defaultChecked": true,
>                                 "checked": false,
>                                 "autoFocus": false,
>                                 "disabled": false,
>                                 "loading": false
>                               },
>                               "hidden": false,
>                               "title": "",
>                               "isLocked": false,
>                               "condition": true,
>                               "conditionGroup": ""
>                             }
>                           ]
>                         }
>                       ]
>                     },
>                     {
>                       "componentName": "Button",
>                       "id": "node_ocliljej245",
>                       "props": {
>                         "type": "primary",
>                         "children": "删除",
>                         "htmlType": "button",
>                         "size": "middle",
>                         "shape": "default",
>                         "onClick": {
>                           "type": "JSFunction",
>                           "value": "function(e) {\r\n  this.operation.remove(this.item.name)\r\n}"
>                         }
>                       },
>                       "hidden": false,
>                       "title": "",
>                       "isLocked": false,
>                       "condition": true,
>                       "conditionGroup": ""
>                     }
>                   ]
>                 },
>                 {
>                   "componentName": "Button",
>                   "id": "node_ocliljej244",
>                   "props": {
>                     "type": "default",
>                     "children": "添加",
>                     "htmlType": "button",
>                     "size": "middle",
>                     "shape": "default",
>                     "block": true,
>                     "onClick": {
>                       "type": "JSFunction",
>                       "value": "function(e) {\r\n  this.operation.add()\r\n}"
>                     }
>                   },
>                   "hidden": false,
>                   "title": "",
>                   "isLocked": false,
>                   "condition": true,
>                   "conditionGroup": ""
>                 }
>               ],
>               "id": "node_ocliljehpk5"
>             }
>           },
>           "hidden": false,
>           "title": "",
>           "isLocked": false,
>           "condition": true,
>           "conditionGroup": ""
>         }
>       ]
>     }
>   ]
> }
> ```
> 
> 效果： ![1](https://user-images.githubusercontent.com/38473196/244237249-2a1475bd-0b22-4898-b747-853cf983b7cc.gif)



> 我是这么玩的
> 
> Form.List 把 children 改成 content, 因为 children 没法做成给子组件传参
> 
> ```ts
> (Form as any).List = class List extends Component {
>   render(): React.ReactNode {
>     const { content, children, ...rest } = this.props as any;
>     return <OriginalForm.List {...rest}>{content}</OriginalForm.List>;
>   }
> };
> ```
> 
> schema:
> 
> ```
> {
>   "componentName": "Component",
>   "id": "node_ocliljefmd1",
>   "props": {
>     "ref": "outerView"
>   },
>   "state": {
>     "formData": {
>       "type": "JSExpression",
>       "value": "{\n  int: 1,\n  float: 'b',\n  array: [{\n    name: 'bob',\n    age: 12,\n    valid: true\n  }, {\n    name: 'ami',\n    age: 13,\n    valid: false\n  }]\n}"
>     }
>   },
>   "dataSource": {
>     "list": []
>   },
>   "css": "body {\n  font-size: 12px;\n}",
>   "methods": {
>     "testFunc": {
>       "type": "JSFunction",
>       "value": "function testFunc() {\n  console.log('test func');\n  return /*#__PURE__*/React.createElement(\"div\", null, this.state.test);\n}",
>       "source": "function testFunc() {\n  console.log('test func');\n  return <div>\n        {this.state.test}\n      </div>;\n}"
>     }
>   },
>   "lifeCycles": {},
>   "title": "自定义低代码组件",
>   "isLocked": false,
>   "condition": true,
>   "fileName": "/",
>   "hidden": true,
>   "conditionGroup": "",
>   "originCode": "class Page extends Component {\n  state = {\n    formData: {\n      int: 1,\n      float: 'b',\n      array: [\n        {\n          name: 'bob',\n          age: 12,\n          valid: true,\n        },\n        {\n          name: 'ami',\n          age: 13,\n          valid: false,\n        },\n      ]\n    }\n  }\n  \n  testFunc() {\n    console.log('test func');\n    return <div>\n        {this.state.test}\n      </div>;\n  }\n}",
>   "children": [
>     {
>       "componentName": "Form",
>       "id": "node_ocliljefoli",
>       "props": {
>         "labelCol": {
>           "span": 6
>         },
>         "wrapperCol": {
>           "span": 14
>         },
>         "onValuesChange": {
>           "type": "JSExpression",
>           "value": "function() {\n      const self = this;\n      try {\n        return (function onValuesChange(changedValues, allValues) {\n  console.log('onValuesChange', changedValues, allValues);\n}).apply(self, arguments);\n      } catch(e) {\n        logger.warn('call function which parsed by lowcode failed: ', e);\n        return e.message;\n      }\n    }"
>         },
>         "onFinish": {
>           "type": "JSExpression",
>           "value": "function() {\n      const self = this;\n      try {\n        return (function onFinish(values) {\n  console.log('onFinish', values);\n}).apply(self, arguments);\n      } catch(e) {\n        logger.warn('call function which parsed by lowcode failed: ', e);\n        return e.message;\n      }\n    }"
>         },
>         "onFinishFailed": {
>           "type": "JSExpression",
>           "value": "function() {\n      const self = this;\n      try {\n        return (function onFinishFailed({ values, errorFields, outOfDate }) {\n  console.log('onFinishFailed', values, errorFields, outOfDate);\n}).apply(self, arguments);\n      } catch(e) {\n        logger.warn('call function which parsed by lowcode failed: ', e);\n        return e.message;\n      }\n    }"
>         },
>         "name": "basic",
>         "ref": "form_g52u",
>         "values": {
>           "type": "JSExpression",
>           "value": "this.state.formData"
>         },
>         "hideRequiredMark": false,
>         "labelAlign": "right",
>         "preserve": true,
>         "scrollToFirstError": true,
>         "size": "middle",
>         "validateMessages": {
>           "required": "'${name}' 不能为空"
>         },
>         "colon": true
>       },
>       "hidden": false,
>       "title": "",
>       "isLocked": false,
>       "condition": true,
>       "conditionGroup": "",
>       "children": [
>         {
>           "componentName": "Form.List",
>           "id": "node_ocliljehpk4",
>           "props": {
>             "name": "array",
>             "content": {
>               "type": "JSSlot",
>               "params": [
>                 "fields",
>                 "operation",
>                 "meta"
>               ],
>               "value": [
>                 {
>                   "componentName": "Row",
>                   "id": "node_ocliljehpk6",
>                   "props": {
>                     "wrap": true,
>                     "_unsafe_MixedSetter____loop____select": "VariableSetter"
>                   },
>                   "hidden": false,
>                   "title": "",
>                   "isLocked": false,
>                   "condition": true,
>                   "conditionGroup": "",
>                   "loop": {
>                     "type": "JSExpression",
>                     "value": "this.fields"
>                   },
>                   "loopArgs": [
>                     null,
>                     null
>                   ],
>                   "children": [
>                     {
>                       "componentName": "Col",
>                       "id": "node_ocliljehpk7",
>                       "props": {
>                         "span": 8,
>                         "order": 0
>                       },
>                       "hidden": false,
>                       "title": "",
>                       "isLocked": false,
>                       "condition": true,
>                       "conditionGroup": "",
>                       "children": [
>                         {
>                           "componentName": "Form.Item",
>                           "id": "node_ocliljehpk9",
>                           "props": {
>                             "label": "名字",
>                             "trigger": "onChange",
>                             "colon": true,
>                             "required": false,
>                             "hasFeedback": false,
>                             "valuePropName": "value",
>                             "getValueFromEvent": {
>                               "type": "JSFunction"
>                             },
>                             "getValueProps": {
>                               "type": "JSFunction"
>                             },
>                             "name": {
>                               "type": "JSExpression",
>                               "value": "[this.item.name, 'name']"
>                             }
>                           },
>                           "hidden": false,
>                           "title": "",
>                           "isLocked": false,
>                           "condition": true,
>                           "conditionGroup": "",
>                           "children": [
>                             {
>                               "componentName": "Input",
>                               "id": "node_ocliljej241",
>                               "props": {
>                                 "placeholder": "请输入",
>                                 "bordered": true,
>                                 "type": "text",
>                                 "size": "middle",
>                                 "onChange": {
>                                   "type": "JSFunction"
>                                 },
>                                 "onPressEnter": {
>                                   "type": "JSFunction"
>                                 },
>                                 "onFocus": {
>                                   "type": "JSFunction"
>                                 },
>                                 "onKeyDown": {
>                                   "type": "JSFunction"
>                                 },
>                                 "onKeyPress": {
>                                   "type": "JSFunction"
>                                 },
>                                 "onKeyUp": {
>                                   "type": "JSFunction"
>                                 },
>                                 "onBlur": {
>                                   "type": "JSFunction"
>                                 }
>                               },
>                               "hidden": false,
>                               "title": "",
>                               "isLocked": false,
>                               "condition": true,
>                               "conditionGroup": ""
>                             }
>                           ]
>                         }
>                       ]
>                     },
>                     {
>                       "componentName": "Col",
>                       "id": "node_ocliljehpk8",
>                       "props": {
>                         "span": 8,
>                         "order": 0
>                       },
>                       "hidden": false,
>                       "title": "",
>                       "isLocked": false,
>                       "condition": true,
>                       "conditionGroup": "",
>                       "children": [
>                         {
>                           "componentName": "Form.Item",
>                           "id": "node_ocliljehpka",
>                           "props": {
>                             "label": "年龄",
>                             "trigger": "onChange",
>                             "colon": true,
>                             "required": false,
>                             "hasFeedback": false,
>                             "valuePropName": "value",
>                             "getValueFromEvent": {
>                               "type": "JSFunction"
>                             },
>                             "getValueProps": {
>                               "type": "JSFunction"
>                             },
>                             "name": {
>                               "type": "JSExpression",
>                               "value": "[this.item.name, 'age']"
>                             }
>                           },
>                           "hidden": false,
>                           "title": "",
>                           "isLocked": false,
>                           "condition": true,
>                           "conditionGroup": "",
>                           "children": [
>                             {
>                               "componentName": "InputNumber",
>                               "id": "node_ocliljej242",
>                               "props": {
>                                 "placeholder": "请输入",
>                                 "controls": true,
>                                 "bordered": true,
>                                 "formatter": {
>                                   "type": "JSFunction",
>                                   "value": "function (value, info) {\n            return value;\n          }"
>                                 },
>                                 "parser": {
>                                   "type": "JSFunction",
>                                   "value": "function (value) {\n            return value;\n          }"
>                                 },
>                                 "keyboard": true,
>                                 "size": "middle",
>                                 "onChange": {
>                                   "type": "JSFunction",
>                                   "value": "function (value) {}"
>                                 },
>                                 "onPressEnter": {
>                                   "type": "JSFunction",
>                                   "value": "function (e) {}"
>                                 },
>                                 "onStep": {
>                                   "type": "JSFunction",
>                                   "value": "function (value, info) {}"
>                                 }
>                               },
>                               "hidden": false,
>                               "title": "",
>                               "isLocked": false,
>                               "condition": true,
>                               "conditionGroup": ""
>                             }
>                           ]
>                         }
>                       ]
>                     },
>                     {
>                       "componentName": "Col",
>                       "id": "node_ocliljeidv1",
>                       "props": {
>                         "span": 8,
>                         "order": 0
>                       },
>                       "hidden": false,
>                       "title": "",
>                       "isLocked": false,
>                       "condition": true,
>                       "conditionGroup": "",
>                       "children": [
>                         {
>                           "componentName": "Form.Item",
>                           "id": "node_ocliljeidv2",
>                           "props": {
>                             "label": "男生",
>                             "trigger": "onChange",
>                             "colon": true,
>                             "required": false,
>                             "hasFeedback": false,
>                             "valuePropName": "checked",
>                             "getValueFromEvent": {
>                               "type": "JSFunction"
>                             },
>                             "getValueProps": {
>                               "type": "JSFunction"
>                             },
>                             "name": {
>                               "type": "JSExpression",
>                               "value": "[this.item.name, 'valid']"
>                             }
>                           },
>                           "hidden": false,
>                           "title": "",
>                           "isLocked": false,
>                           "condition": true,
>                           "conditionGroup": "",
>                           "children": [
>                             {
>                               "componentName": "Switch",
>                               "id": "node_ocliljej243",
>                               "props": {
>                                 "defaultChecked": true,
>                                 "checked": false,
>                                 "autoFocus": false,
>                                 "disabled": false,
>                                 "loading": false
>                               },
>                               "hidden": false,
>                               "title": "",
>                               "isLocked": false,
>                               "condition": true,
>                               "conditionGroup": ""
>                             }
>                           ]
>                         }
>                       ]
>                     },
>                     {
>                       "componentName": "Button",
>                       "id": "node_ocliljej245",
>                       "props": {
>                         "type": "primary",
>                         "children": "删除",
>                         "htmlType": "button",
>                         "size": "middle",
>                         "shape": "default",
>                         "onClick": {
>                           "type": "JSFunction",
>                           "value": "function(e) {\r\n  this.operation.remove(this.item.name)\r\n}"
>                         }
>                       },
>                       "hidden": false,
>                       "title": "",
>                       "isLocked": false,
>                       "condition": true,
>                       "conditionGroup": ""
>                     }
>                   ]
>                 },
>                 {
>                   "componentName": "Button",
>                   "id": "node_ocliljej244",
>                   "props": {
>                     "type": "default",
>                     "children": "添加",
>                     "htmlType": "button",
>                     "size": "middle",
>                     "shape": "default",
>                     "block": true,
>                     "onClick": {
>                       "type": "JSFunction",
>                       "value": "function(e) {\r\n  this.operation.add()\r\n}"
>                     }
>                   },
>                   "hidden": false,
>                   "title": "",
>                   "isLocked": false,
>                   "condition": true,
>                   "conditionGroup": ""
>                 }
>               ],
>               "id": "node_ocliljehpk5"
>             }
>           },
>           "hidden": false,
>           "title": "",
>           "isLocked": false,
>           "condition": true,
>           "conditionGroup": ""
>         }
>       ]
>     }
>   ]
> }
> ```
> 
> 效果： ![1](https://user-images.githubusercontent.com/38473196/244237249-2a1475bd-0b22-4898-b747-853cf983b7cc.gif)

谢谢，还有问下antd的可编辑表格你有试过吗

**Comment by proclml** [comment]
哪个可编辑表格？你是说antd的table单元格可编辑吗，还是ant design pro的可编辑表格。前者试过，后者没有
