### ISSUE TITLE
低码引擎spa页面切换，画布交互渲染bug

### ISSUE THREAD

**Issue by Gllidan** [alibaba/lowcode-engine#2141]
一、操作步骤
1. 项目集成spa页面
2. 打开引擎页面，添加物料
3. 未点击页面保存，直接跳转其他路由
4. 从其他路由跳转回引擎页面，会出现3种情况
1）画布显示历史配置物料，只可选中，但不可删除，画布辅助线也无法正常显示，无法正常添加物料。
 
![image](https://github.com/alibaba/lowcode-engine/assets/27495460/ae09e0c7-e2a5-4311-be6b-3fa68159feca)

2）间隔多几秒或跳转多其他几个路由再跳回引擎页，可正常显示、操作历史配置物料，后续可正常添加物料。

（所有插件均配置 override: true，因切换spa页面回报插件已注册错误）

二、期望
1. 看副作用，每次进引擎页面都会重新走初始化流程，暂未定位到为什么有配置缓存。按正常流程，二次加载应该打开全新画布，且能正常操作，不该显示历史配置的schema。

**Comment by JackLian** [comment]
by design引擎不会支持此类spa集成使用方式，可以考虑单独页面或iframe隔离

**Comment by Gllidan** [comment]
> by design引擎不会支持此类spa集成使用方式，可以考虑单独页面或iframe隔离

额。那我想着使用project.removeDocument移除当前编辑的document实体，为什么也是失效的。。我想着删除后再跳转路由也是可行的

**Comment by Gllidan** [comment]
> > by design引擎不会支持此类spa集成使用方式，可以考虑单独页面或iframe隔离
> 
> 额。那我使用project.removeDocument移除当前编辑的document实体，为什么也是失效的。。我想着删除后再跳转路由也是可行的

project.removeDocument(project.currentDocument)就可行，用documents遍历清除则无效

**Comment by liujuping** [comment]
spa 下没有做过单独的适配，不建议使用。可行和不可行的情况都是不可预测的。
