### ISSUE TITLE
[lowcode-materials开发相关]如何在物料项目中配置外部字体并实现支持

### ISSUE THREAD

**Issue by ColeFong** [alibaba/lowcode-engine#2143]
## **[lowcode-materials开发相关]如何在物料项目中配置外部字体并实现支持** / **疑问求解**

在低代码物料项目中 /src/index.css 直接全局引入TTF字体将会触发报错，具体引入代码如下：
<img width="452" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/81454526/545ea9e6-884e-468c-8e82-be1cb914f726">

---

## Reproduce 复现

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：
1. import *.ttf to your assets
2. import that to your index.scss
3. run the project and then you will find the error in your console.

中文版示例：
1. 在物料项目中的 assets 目录放入 .ttf 字体文件
2. 在全局的 index.scss 引入该字体
3. 运行项目会发现控制台上的报错。

## Screenshots 截图<img width="1221" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/81454526/c2080aef-dafc-4a90-ae3a-f4d8755a6967">

---

## Environments 开发环境
 - AliLowCodeEngine version: [1.1.7] / 低代码引擎版本
 - AliLowCodeEngineExt version: [1.0.5] / 低代码引擎扩展包版本
 - Browser [Chrome 114.0.5735.90（正式版本） (arm64)] / 浏览器版本

**Comment by eternalsky** [comment]
一般字体文件是先传到 cdn 上，然后再引入进来的，如果不具备传到 cdn 上，可以传到服务器里。
