### ISSUE TITLE
[Question] 实现宜搭子表单的组件拖拽效果

### ISSUE THREAD

**Issue by jqhr** [alibaba/lowcode-engine#2144]
我想开发一个子表单组件，其中一个效果是拖拽组件到子表单上生成表格的列，表格的列也可以拖拽。
目前我没看到引擎有这种拖拽效果，请问是不是有相关的API之类的？
或者提供思路也可以

**Comment by Noodles006** [comment]
@jqhr 我们实现了列的单元格可以选中、拖拽的效果；效果图如下：
![image](https://github.com/alibaba/lowcode-engine/assets/8025633/aed0ea1a-cdaf-4cff-9a3f-bd726796d8bd)

具体技术方案：
1. 子表单组件prototype isContainer声明为true；
2. 子表单在渲染的时候将schema中的children翻译为columns传递给deep-table组件；
3. 子表单组件prototypeView中定义样式：
```
// 覆盖设计器样式，使表格列可选中
.engine-design-mode {
  .#{$css-prefix}table {
    pointer-events: initial !important;
  }
}
```
