### ISSUE TITLE
IconSetter如何使用自定义的图标库

### ISSUE THREAD

**Issue by little-yaonv** [alibaba/lowcode-engine#2152]
请问IconSetter这个设置器如何使用自定义的图标库呢
![image](https://github.com/alibaba/lowcode-engine/assets/75791730/826c6fe0-112a-463f-bfd9-11f6f831d7ef)

**Comment by liujuping** [comment]
setter 可以配置 prop.icons

https://lowcode-engine.cn/site/docs/guide/appendix/setterDetails/icon

**Comment by aLily11** [comment]
你好，请问问题解决了嘛，如果我想导入自己的图标库，不在默认图标库里选择，请问现在支持吗

**Comment by little-yaonv** [comment]
还没有解决




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/lowcode-engine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月13日(星期天) 晚上7:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/lowcode-engine] IconSetter如何使用自定义的图标库 (Issue #2152)





 
你好，请问问题解决了嘛，如果我想导入自己的图标库，不在默认图标库里选择，请问现在支持吗

**Comment by hzd822** [comment]
可以参照iconSetter自定义一个setter解决
https://github.com/alibaba/lowcode-engine-ext/blob/main/src/setter/icon-setter/index.tsx

**Comment by little-yaonv** [comment]
好的，谢谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/lowcode-engine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月14日(星期一) 上午10:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/lowcode-engine] IconSetter如何使用自定义的图标库 (Issue #2152)





 
可以参照iconSetter自定义一个setter解决
 https://github.com/alibaba/lowcode-engine-ext/blob/main/src/setter/icon-setter/index.tsx
