### ISSUE TITLE
setter项目：@alilc/lowcode-engine-ext 启动失败

### ISSUE THREAD

**Issue by douyaya** [alibaba/lowcode-engine#2157]
## **拉取github代码后, tnpm i  tnpm run start 后报错**
![image](https://github.com/alibaba/lowcode-engine/assets/34003600/94b66f4d-d5a3-4ed7-bce0-be1cb9e44c8b)

**Comment by hzd822** [comment]
https://lowcode-engine.cn/site/docs/faq/faq016
