### ISSUE TITLE
同时启动inject模式下的设置器项目和物料项目报端口被占用

### ISSUE THREAD

**Issue by jqhr** [alibaba/lowcode-engine#2158]
## **Describe the bug (required)** / **详细描述 bug（必填）**

![图片](https://github.com/alibaba/lowcode-engine/assets/23305067/92accc58-3881-41b2-8a78-2f2199667997)

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
用脚手架创建一个物料库和一个设置器项目，
然后在物料库和设置器库运行
```bash
yarn lowcode:dev
```
build.json
配置如下
```jsonc
// 物料库
{
  alias: {
    '@': './src',
  },
  plugins: [
    [
      "@alilc/build-plugin-alt",
      {
        "type": "component",
        "inject": true
      }
    ],
    [
      '@alifd/build-plugin-lowcode',
      {
        library,
        engineScope: "@alilc",
        noParse: false
      },
    ],
  ],
}
// 设置器
{
  alias: {
    '@': './src',
  },
  plugins: [
    [
      "@alilc/build-plugin-alt",
      {
        "type": "component",
        "inject": true
      }
    ],
    [
      '@alifd/build-plugin-lowcode',
      {
        library,
        engineScope: "@alilc",
        noParse: false
      },
    ],
  ],
}
```

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
能正常启动

---

## **Screenshots (optional)** / **bug 截图（可选）**

![图片](https://github.com/alibaba/lowcode-engine/assets/23305067/92accc58-3881-41b2-8a78-2f2199667997)
---

##  NOTE
BUG是由*@alilc/build-plugin-alt*这个库导致的，版本是1.3.3，和[这一行](https://github.com/alibaba/lowcode-tools/blob/94119258a5d75a006560086069839925634a46a8/packages/build-plugin-alt/src/inject/apis.ts#L45)有关系

**Comment by hinhinlaw** [comment]
我也碰到了同样的问题。我是用官方脚手架npm init @alilc/element创建了一个组件库项目和一个plugin项目，想在官方提供的demo-general编辑器中同时调试 自定义组件 和 自定义plugin，启动组件库项目或者plugin项目，能成功接入demo-general，但是再启动另一个项目就会报上面楼主的错，求助！

plugin项目的build.js
<img width="1057" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/61171216/efe952f5-dc7b-44af-8e6a-bb06d3346aff">

自定义组件项目的build.lowcode.js
<img width="1030" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/61171216/ea07575d-037f-4c77-8804-4de27303c630">

报错：
<img width="842" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/61171216/52b6aef6-100b-450c-b494-5bfa70a74581">

编辑器页面：（只提示成功注入了插件，但是自定义组件并没有注入）
<img width="1675" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/61171216/ace38c95-ea78-43be-992a-7de652e5da69">

**Comment by hinhinlaw** [comment]
> 看起来有些奇怪，代码里是做了端口的冲突检测的，如果 8899 被占用，就不会额外再启动。我这边无法复现这个问题，欢迎可以复现的同学 pr 来帮助优化。

可以尝试下同时将组件项目和插件项目inject到编辑器项目试下，应该就可以复现了，我这边100%复现，但是我不会改:(

**Comment by eternalsky** [comment]
> > 看起来有些奇怪，代码里是做了端口的冲突检测的，如果 8899 被占用，就不会额外再启动。我这边无法复现这个问题，欢迎可以复现的同学 pr 来帮助优化。
> 
> 可以尝试下同时将组件项目和插件项目inject到编辑器项目试下，应该就可以复现了，我这边100%复现，但是我不会改:(

这是这个插件第一个版本就已经测试过的功能，我说不能复现，是我这边这个 case 是没问题的。

**Comment by hinhinlaw** [comment]
> > 看起来有些奇怪，代码里是做了端口的冲突检测的，如果 8899 被占用，就不会额外再启动。我这边无法复现这个问题，欢迎可以复现的同学 pr 来帮助优化。
> 
> 就是这个不会额外启动才会出问题。 alt那个代码我看了，有冲突就停了。

老哥你那边现在可以起吗:(

**Comment by jqhr** [comment]
> 
不能。
我找到报错代码了，@eternalsky。
![图片](https://github.com/alibaba/lowcode-engine/assets/23305067/ca19493b-b795-4196-a3ab-7768b88badd4)
这一行报错。
只要走listen方法，就会报错，我把这一行代码调到`server.on('error')`下面也还是报一样的错，它不走`server.on('error')，直接就终止运行了

**Comment by hinhinlaw** [comment]
> > 
> 
> 不能。 我找到报错代码了，@eternalsky。 ![图片](https://user-images.githubusercontent.com/23305067/245009344-ca19493b-b795-4196-a3ab-7768b88badd4.png) 这一行报错。 只要走listen方法，就会报错，我把这一行代码调到`server.on('error')`下面也还是报一样的错，它不走`server.on('error')，直接就终止运行了

确实，我自己测试了下，如果8899已经被占用，再去监听8899，应该是走server.on('error')才对，但是alt代码里面走了server.on('listening')，然后就报错了

**Comment by jqhr** [comment]
> 

这种情况我测试了两个组件库的项目同时启动没有问题，也确实能够复用。
但是一起跑组件库和设置器就不行了

**Comment by hinhinlaw** [comment]
> 

卧槽我成功同时inject组件库项目和plugin项目到编辑器项目里面了。你尝试下在alt代码里最后app.listen()不要监听8899，换一个端口，就可以了。
<img width="646" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/61171216/adbf9216-74ba-470d-8665-1adfc6ebdf36">
<img width="1676" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/61171216/b67625cc-1a7f-47d2-b067-19ffb4c3e453">
不过具体原因不明白

**Comment by Alubb77** [comment]
> 这种情况我测试了两个组件库的项目同时启动没有问题，也确实能够复用。 但是一起跑组件库和设置器就不行了

是不是因为组件库没有默认开启inject，100%复现的，开启inject的项目，不管是setter、插件、组件，第二个启动的必报错。

**Comment by eternalsky** [comment]
上方报有错误的同学，请回复一下各自的操作系统以及node 版本

**Comment by Alubb77** [comment]
> 上方报有错误的同学，请回复一下各自的操作系统以及node 版本

macOs ，node: v14.21.3

**Comment by Alubb77** [comment]
@eternalsky 有结论了吗，或者提供一个没问题的node版本，我试一下呢

**Comment by hinhinlaw** [comment]
> 上方报有错误的同学，请回复一下各自的操作系统以及node 版本

macOS,
node:v16.17.0

**Comment by Alubb77** [comment]
这个问题我发pr修复了，本质上就是判断端口是否被占用的portIsOccupied方法，因为listen(_port)没有加host，导致一直判断为端口未被占用，加个host就好了：
const server = net.createServer().listen(_port, _host);

https://github.com/alibaba/lowcode-tools/pull/41/commits/1dd5a08bbcb3c89ccef525661ff51ebfc9c8aab9

**Comment by eternalsky** [comment]
> 

pr 已合并，@alilc/build-plugin-alt@1.3.4
