### ISSUE TITLE
关于自定义组件的自定义设置面板的问题

### ISSUE THREAD

**Issue by hinhinlaw** [alibaba/lowcode-engine#2159]
## **Describe the bug (required)** / **详细描述 bug（必填）**
我想在编辑器右侧设置面板中添加一个自定义的Tab，官方虽然提供了material.registerMetadataTransducer方法来修改meta数据，但是这个方法只能在编辑器项目中调用。但是我希望的是在开发自定义组件时，能在自定义组件的项目中一起调试这个自定义Tab。

按照文档material.registerMetadataTransducer的使用例子，我尝试在自定义组件项目中修改组件的 /lowcode/*/meta.ts，添加configure.combined，但是在运行自定义组件项目时报错了。

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
1. 执行npm init @alilc/element xxx
2. 选择“编辑器”，创建一个编辑器项目
3. 执行npm init @alilc/element xxx-comp
4. 选择“组件/物料” -> “react-组件库”，创建一个自定义组件库项目
5. yarn lowcode:dev启动项目，并在根目录下生成 /lowcode/*/meta.ts
6. 修改某个组件的meta.ts，在configure属性下添加"combined"属性，combined的具体值就是官方文档中material.registerMetadataTransducer的使用例子中的combined
7. 刷新页面，报错TypeError: e.forEach is not a function

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
在组件项目中，给组件的meta.ts手动添加configure.combined，自定义组件的右侧设置面板中会出现对应的tab和setter

---

## **Screenshots (optional)** / **bug 截图（可选）**
组件项目中，某个组件的meta.ts配置：
<img width="905" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/61171216/63f22db1-8391-4fc1-a639-9afea3a22d75">

组件项目中的报错：
<img width="1672" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/61171216/e48a4ece-8cd8-4c06-b79f-8526f9aca9b0">

在编辑器项目中，使用material.registerMetadataTransducer修改后的组件的元数据（正确运行）：
<img width="1659" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/61171216/45a579ee-4541-4163-95a5-82a18b2222fb">

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - Browser [e.g. chrome, safari] /  Chrome 113.0.5672.126（正式版本） (arm64)

组件项目的依赖版本：
<img width="380" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/61171216/29b4ba7d-e2ca-4e1d-8bb1-6c70f75691a4">

编辑器项目的依赖版本：
<img width="492" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/61171216/042c4562-1e63-4019-ab31-5d5fe5ff1118">

---

## **Additional context (optional)** / **更多额外信息（可选）**
目前我的需求是开发几个新的组件设置面板Tab，Tab下的内容也是挺多的，除了用material.registerMetadataTransducer，有没有其他更加方便高效的开发调试方式提供呢

**Comment by JackLian** [comment]
https://lowcode-engine.cn/site/docs/guide/expand/editor/cli#-%E5%9C%A8%E4%BD%8E%E4%BB%A3%E7%A0%81%E9%A1%B9%E7%9B%AE%E4%B8%AD%E8%B0%83%E8%AF%95%E7%89%A9%E6%96%99%E6%8F%92%E4%BB%B6%E8%AE%BE%E7%BD%AE%E5%99%A8
用这种方式，把setter和组件同时注入到一个低代码设计器项目（或直接用线上demo）进行调试

**Comment by hinhinlaw** [comment]
> https://lowcode-engine.cn/site/docs/guide/expand/editor/cli#-%E5%9C%A8%E4%BD%8E%E4%BB%A3%E7%A0%81%E9%A1%B9%E7%9B%AE%E4%B8%AD%E8%B0%83%E8%AF%95%E7%89%A9%E6%96%99%E6%8F%92%E4%BB%B6%E8%AE%BE%E7%BD%AE%E5%99%A8 用这种方式，把setter和组件同时注入到一个低代码设计器项目（或直接用线上demo）进行调试

谢谢回复！试了一下上述地方方法是可以在编辑器中调试组件的，但是我这边还有几个问题：

**Comment by hinhinlaw** [comment]
> https://lowcode-engine.cn/site/docs/guide/expand/editor/cli#-%E5%9C%A8%E4%BD%8E%E4%BB%A3%E7%A0%81%E9%A1%B9%E7%9B%AE%E4%B8%AD%E8%B0%83%E8%AF%95%E7%89%A9%E6%96%99%E6%8F%92%E4%BB%B6%E8%AE%BE%E7%BD%AE%E5%99%A8 用这种方式，把setter和组件同时注入到一个低代码设计器项目（或直接用线上demo）进行调试

感谢回答。试了下上述方法确实可以在编辑器中调试自定义组件，但是我还有几个问题想问下：
1. 官网好像没有对material.registerMetadataTransducer中注入的"combined"字段做描述，哪里可以看combined相关的介绍呢？
2. 我在编辑器项目中使用material.registerMetadataTransducer注入自定义的设置器tab后，是不是意味着我在自定义组件meta.ts中配置的configure.props就失效了呢？而且其他的tab“样式”、“事件”和“高级”都会消失。目前看起来效果是这样的。期望的是：我在组件项目中修改meta.ts的configure.props来配置设置器，额外的设置器tab用material.registerMetadataTransducer配置。
3. 基于上一个问题，添加额外的设置器tab，我好像只能在编辑器项目中用material.registerMetadataTransducer注入，那组件的props不就耦合到编辑器项目里面了吗？

期待解答，谢谢！

**Comment by liujuping** [comment]
1.combined 不在物料配置协议中，而是根据物料协议的部分字段进行生成的，属于引擎内部的定义。例如：
- configure.supports.events 存在的情况下，就会有 events Tab
- supports.className || supports.style 存在的情况下，就会有 style Tab

2.如果要想通过 material.registerMetadataTransducer 来处理 combined，引擎内部不会再处理，其他的 tabs 也需要一并处理了。

3.物料协议目前没有 tabs 相关的定义，所以只能通过 material.registerMetadataTransducer 注入。而这里的 props.xxx 对应什么样的 tab 可以是平台自行决定的，比如定义了 props.style 就希望存在 style tab，而不是每一个物料都要在 style 下定义归属于哪个 Tab。因此，你可以考虑如果定义了 props.xxx 就增加一个特殊的 Tab，并封装成一个插件放到你的编辑器中，减轻物料开发者的负担。

**Comment by hinhinlaw** [comment]
> 1.combined 不在物料配置协议中，而是根据物料协议的部分字段进行生成的，属于引擎内部的定义。例如：
> 
> * configure.supports.events 存在的情况下，就会有 events Tab
> * supports.className || supports.style 存在的情况下，就会有 style Tab
> 
> 2.如果要想通过 material.registerMetadataTransducer 来处理 combined，引擎内部不会再处理，其他的 tabs 也需要一并处理了。
> 
> 3.物料协议目前没有 tabs 相关的定义，所以只能通过 material.registerMetadataTransducer 注入。而这里的 props.xxx 对应什么样的 tab 可以是平台自行决定的，比如定义了 props.style 就希望存在 style tab，而不是每一个物料都要在 style 下定义归属于哪个 Tab。因此，你可以考虑如果定义了 props.xxx 就增加一个特殊的 Tab，并封装成一个插件放到你的编辑器中，减轻物料开发者的负担。

感谢回答。

关于第2、3点，我还有点疑问：
1. 按照你的意思，用material.registerMetadataTransducer手动注入combined后，引擎内部不会再处理，那么组件的meta.ts的整个configure会失效，组件的设置器只会按照手动注入的combined来，是这样吗？（至少我目前看到的效果是这样的）
2. 后续会把tabs相关定义放到物料协议中吗？
3. 那就是如果我要定义自定义tab，最佳实践是封装plugin，在plugin中使用registerMetadataTransducer来手动注入combined，但是感觉这种方法 组件跟组件的设置器就分离了，我个人理解最好还是像meta.ts一样，跟组件待在同一个项目里面，不过如果无更好方法那只能用这种方法了:(
4. 你第3点中说的props指的是meta.ts的props还是React组件的props呢，如果是React组件的props，在registerMetadataTransducer的回调中可以拿到这个React组件的props吗？

**Comment by liujuping** [comment]
后续不会把 tabs 相关的定义放到物料协议中，对于物料的开发者来说，只需要定义物料对应的 props，而不需要关心对应的 props 在哪个 tab 下。

这里说的 props 都是 meta.ts 的 props。

至于说组件跟组件的设置器分离的问题，如果是通用的场景，比如 style 的 props 定义，如果要定义到 meta 中，还需要定义相关的 tabs，那么 meta 的信息会更加繁琐。如果说单独就某一个组件需要一个特定的 Tab，也可以在插件中通过 registerMetadataTransducer 支持你们自己定义的物料协议，比如加上某个 tab 字段之后，通过 registerMetadataTransducer 自己组合 combined 字段。

如果要复用引擎的 combined 字段，需要配合插件的顺序，要在引擎处理之后，再进行处理。比如引擎里面相关的处理是这样的：
```
material.registerMetadataTransducer(addonCombine, 10, 'combine-props');
```

自己注册的时候，第二个参数是 9 / 11 得到的结果就会不同，相关问题可以多看看源码。

**Comment by hinhinlaw** [comment]
> 后续不会把 tabs 相关的定义放到物料协议中，对于物料的开发者来说，只需要定义物料对应的 props，而不需要关心对应的 props 在哪个 tab 下。
> 
> 这里说的 props 都是 meta.ts 的 props。
> 
> 至于说组件跟组件的设置器分离的问题，如果是通用的场景，比如 style 的 props 定义，如果要定义到 meta 中，还需要定义相关的 tabs，那么 meta 的信息会更加繁琐。如果说单独就某一个组件需要一个特定的 Tab，也可以在插件中通过 registerMetadataTransducer 支持你们自己定义的物料协议，比如加上某个 tab 字段之后，通过 registerMetadataTransducer 自己组合 combined 字段。
> 
> 如果要复用引擎的 combined 字段，需要配合插件的顺序，要在引擎处理之后，再进行处理。比如引擎里面相关的处理是这样的：
> 
> ```
> material.registerMetadataTransducer(addonCombine, 10, 'combine-props');
> ```
> 
> 自己注册的时候，第二个参数是 9 / 11 得到的结果就会不同，相关问题可以多看看源码。

明白了。原来tabs的配置没设计到物料协议里面原来是这么考虑的，清晰很多了，感谢🙏
