### ISSUE TITLE
如何使用表单输入项

### ISSUE THREAD

**Issue by liulinbo123** [alibaba/lowcode-engine#216]
## **Describe the bug (required)** / **详细描述 bug（必填）**

需要通过变量绑定的方式访问表单的输入项数据，在线demo只有表格的演示，不知道表单的输入数据存在哪里以及如何访问
---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

新建一个输入框
设置区域标题和输入框内容实时同步
按钮的click时间获取表单录入的数据

**Comment by liulinbo123** [comment]
希望在线demo增加表单录入相关操作的演示

**Comment by 2509031645** [comment]
同求，如何实现一个简单的表单提交场景

**Comment by mark-ck** [comment]
可以看看这期直播回放 5分18秒开始介绍表单的使用 https://www.bilibili.com/video/BV13F411s7Nh
