### ISSUE TITLE
关于页面获取url查询参数的问题

### ISSUE THREAD

**Issue by jeffery-zhang** [alibaba/lowcode-engine#2167]
# 问题描述
我希望为页面配置获取urlParams的功能, 在页面的编辑页面预先定义好url中会带有的查询参数的key, 在渲染页面时自动获取对应参数的值并插入schema, 并且可以用于物料的变量绑定

这个需求是否可以利用数据源面板插件来实现

**Comment by JackLian** [comment]
可以实现，产品形态上参考这个 https://lab.lowcode-engine.cn/#/

**Comment by jeffery-zhang** [comment]
请问https://lab.lowcode-engine.cn/#/这个网站的demo有相关的源码吗

**Comment by JackLian** [comment]
lab不开源

**Comment by jeffery-zhang** [comment]
好的 谢谢
