### ISSUE TITLE
[BUG] LC renders component in non-loop mode if loop data is `undefined` or `null`

### ISSUE THREAD

**Issue by yifanwww** [alibaba/lowcode-engine#2172]
## **Describe the bug (required)** / **详细描述 bug（必填）**

When looping to render components, if loop data if `null` or `undefined`, LC will render the component in non-loop mode which cause `Cannot read properties of undefined` errors.

循环渲染组件时，如果循环数据是 `null` 或 `undefined`，LC 会使用非循环渲染方式去渲染组件导致 `Cannot read properties of undefined` 报错

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

en ver:
1. Go to [demo](http://lowcode-engine.cn/demo)
2. Click "add section"
3. add "Text" material into the new section
4. set "loop data" to `this.state.arr` (`this.state.arr` is actually `undefined`)
5. set "text content" to `this.item.name`
6. **open preview page**

cn ver:
1. 打开 [demo](http://lowcode-engine.cn/demo)
2. 点击 "add section"
3. 在新区域中添加 "Text" 物料
4. 将 "循环数据" 设置成 `this.state.arr` (`this.state.arr` 实际上就是 `undefined`)
5. 将 "文本内容" 设置成 `this.item.name`
6. **打开预览页面**

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

**In preview page**, no errors in console, the text won't be rendered.

**在预览页面中**，console 中没有报错，文本不会被渲染出来

---

## **Screenshots (optional)** / **bug 截图（可选）**

**In preview page**, the text isn't rendered which is fine, but there're errors in console.

**在预览页面中**，文本没有被渲染出来（这个是正确的行为），但是 console 中有报错（这个是不正确的）

![image](https://github.com/alibaba/lowcode-engine/assets/55199350/24bd6ccb-0aea-4c8b-ba3e-ed40dcaec9ec)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: see demo / 见 demo
 - AliLowCodeEngineExt version: see demo / 见 demo
 - Browser: chrome version 114.0.5735.106 (official build) (x86_64)

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

en ver:

I read lowcode code and found that [here], it seems that if there is loop data LC will looping to render the component, but if there is no loop data LC will fallback to render the component in non-loop mode. I think this is not correct.

Let's say we are not using lowcode, we are manually writing React code, what we would do if we want to render an array of data? 
 We write
```ts
<List>
{arr?.map((item) => <Component item={item} />)}
</List>
```

But it seems that LC behaves like
```ts
<List>
{
  arr && arr.length > 0
    ? arr.map((item) => <Component item={item} />)
    : <Component item={arr} />
}
</List>
```

Yes we can set "是否渲染" to false if there is no loop data, but this is not intuitive. Just like when we are using `Typography.Text` we don't (need to) set "是否渲染" to false if `text` is `undefined` or an empty string.

-----

cn ver:

我查看了 lowcode 的代码并且看到了 [这个]，看起来像是，如果有循环数据 LC 会循环渲染组件，但是如果没有循环数据 LC 就会尝试将组件单个的渲染出来。我认为这是不对的

举例说，如果我们没在使用 lowcode，我们在手写代码，如果我们想渲染一个列表的数据我们会怎么写？我们会写
```ts
<List>
{arr?.map((item) => <Component item={item} />)}
</List>
```

但 LC 的行为看起来像是这样
```ts
<List>
{
  arr && arr.length > 0
    ? arr.map((item) => <Component item={item} />)
    : <Component item={arr} />
}
</List>
```

我们确实可以在没有循环数据的时候将 "是否渲染" 设置成 false，但这不符合直觉。就像我们使用 `Typography.Text` 的时候，如果 `text` 是 `undefined` 或者空字符串，我们也不会（或没必要）将 "是否渲染" 设置成 false

[here]: https://github.com/alibaba/lowcode-engine/blob/main/packages/renderer-core/src/renderer/base.tsx#L551
[这个]: https://github.com/alibaba/lowcode-engine/blob/main/packages/renderer-core/src/renderer/base.tsx#L551

**Comment by liujuping** [comment]
在设计状态下，如果将 loop 数据设置成 null / undefined / []，为了方便设计，都还会将其渲染出来。否则就只能通过大纲树找到这个组件来修改这个组件的配置了。

**Comment by yifanwww** [comment]
在设计状态下，可以理解
在预览状态下我认为不应该渲染出来
