### ISSUE TITLE
如何使自定义的样式出现在样式名设置器的下拉框中

### ISSUE THREAD

**Issue by little-yaonv** [alibaba/lowcode-engine#2174]
请问如何使自定义的样式出现在样式名设置器的下拉框中，需要怎样配置呢
![image](https://github.com/alibaba/lowcode-engine/assets/75791730/9b8543ff-f24e-4c64-923b-3995369f811a)

**Comment by liujuping** [comment]
![image](https://github.com/alibaba/lowcode-engine/assets/11935995/469ca512-606d-44e8-8f21-c6fd77408234)

看相关的代码，是你全局 css 下有相关的定义才会出现在这里。如果有其他的需要可以提 PR 或者自定义 setter。
