### ISSUE TITLE
@alilc/element创建的物料库如何不联调编辑器更改@alifd/next库版本

### ISSUE THREAD

**Issue by l704863851** [alibaba/lowcode-engine#2180]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

build.lowcode.js如何更改@alifd/next版本,不想去编辑器更改public/index.ejs路径

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**

![image](https://github.com/alibaba/lowcode-engine/assets/29324159/17e58f59-4186-4c5d-b682-60676dec9d36)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - 低代码引擎版本 v1.7.0
 - 低代码引擎扩展包版本 v1.0.5 
 - 浏览器版本 Chrome 已是最新版本 114.0.5735.110（正式版本） （64 位）

**Comment by eternalsky** [comment]
本地调试的话可以通过修改 builtinAssets，详细请看文档：https://www.npmjs.com/package/@alifd/build-plugin-lowcode
注入调试的话，next 使用项目设计器引入，无法通过物料库配置来修改。
