### ISSUE TITLE
LAB设计器中的Button组件，样式均不生效

### ISSUE THREAD

**Issue by 4373979** [alibaba/lowcode-engine#2182]
LAB设计器中的Button组件，样式均不生效
![1111](https://github.com/alibaba/lowcode-engine/assets/58925909/3436c6da-9618-4979-9e34-0401dbf78557)

**Comment by woshilaoge** [comment]
@4373979 

![image](https://github.com/alibaba/lowcode-engine/assets/22810511/e16c9179-7247-4561-9a46-0c22c0fff172)

逻辑是生效的，但是不一定能覆盖掉原有 组件默认样式（因为权重的问题，如截图所示）

LAB 平台的样式设置，类似 css modules，在大部分组件下是没问题的，如遇到组件默认样式的权重较高（一般配合主题设置），可以试试手动修改下。如下图：

![image](https://github.com/alibaba/lowcode-engine/assets/22810511/e561842f-1455-48ab-8157-5a6bc2f80ecf)
