### ISSUE TITLE
【咨询】设置器的自定义tab中的内容可以完全自定义吗？（包括样式、布局等）

### ISSUE THREAD

**Issue by hinhinlaw** [alibaba/lowcode-engine#2187]
## **Describe the bug (required)** / **详细描述 bug（必填）**
目前添加自定义tab可以通过material.registerMetadataTransducer()来修改combined字段，但是本质上还是以“配置”方式来实现需求。但是还不满足场景，希望整个tab都是可以自定义的，比如像这个issue中的设置器面板一样：https://github.com/alibaba/lowcode-engine/issues/1335。
<img width="941" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/61171216/24cd4a83-5835-4f34-8365-e5ff533c65c5">

而不是现在这样，通过配置方法，tab中的setter的样式布局都是固定几个选项。有什么办法吗？

---
## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by liujuping** [comment]
这个问题和这个 issue 是类似的吧

https://github.com/alibaba/lowcode-engine/issues/2159

**Comment by hinhinlaw** [comment]
> 

好像不是哦，我上面截图里面的设置器面板，跟用registerMetadataTransducer配置出来的设置器面板的样式不一样的，截图里面的更加定制化，比如没了setter的标题、有些setter下面有条border-bottom等

**Comment by hinhinlaw** [comment]
> 这个问题和这个 issue 是类似的吧
> 
> #2159

<img width="645" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/61171216/7172c4d3-29af-4ab3-a875-098d705d84d1">
我截图说明下，会清晰点

**Comment by LgnMs** [comment]
> > 这个问题和这个 issue 是类似的吧
> > #2159
> 
> <img alt="image" width="645" src="https://user-images.githubusercontent.com/61171216/245751452-7172c4d3-29af-4ab3-a875-098d705d84d1.png"> 我截图说明下，会清晰点

我觉得你可以去看`lowcode-engine-ext`中style-setter的实现

**Comment by hinhinlaw** [comment]
> 

好吧
