### ISSUE TITLE
组件库中使用antd组件页面报错“组件渲染异常，请查看控制台日志”

### ISSUE THREAD

**Issue by hinhinlaw** [alibaba/lowcode-engine#2188]
## **Describe the bug (required)** / **详细描述 bug（必填）**

我使用官方脚手架创建一个组件库项目，并且将组件库项目通过@alilc/build-plugin-alt注入到编辑器项目（也是通过脚手架生成的）中调试，在组件库项目中安装了antd@5，并且在组件中使用antd的<Input>标签，但是当我将组件拖入画布后，组件显示不出来，显示：组件渲染异常，请查看控制台日志，控制台报错：TypeError: Cannot read properties of undefined (reading 'Input')

PS：
1. 我在编辑器项目中也安装了相同版本的antd依赖
2. **如果组件库项目不使用inject模式，直接启动访问6888，antd组件是正常使用的，问题应该是编辑器中无法找到antd组件？但是我在编辑器项目中封装了些setter，setter中使用antd组件是正常的**

不知道是不是我做漏了哪些步骤呢？

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
1. 通过脚手架创建编辑器项目，在编辑器项目中安装antd@5；
2. 通过脚手架创建组件库项目，在组件库项目中安装antd@5，在build.lowcode.js中使用@alilc/build-plugin-alt开启inject，openUrl为第1步中编辑器项目的localhost地址；
3. 在组件库项目中开发一个组件，并且在组件中使用antd的Input组件；
4. 将组件拖进去画布，显示报错；

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为
组件拖入画布后，能正常显示

---

## **Screenshots (optional)** / **bug 截图（可选）**
<img width="1673" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/61171216/dfd60674-4cbc-4a59-842c-aa1dbfb1a806">

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
组件库项目：
 - "@alilc/build-plugin-alt": "^1.3.3",
 - "antd": "^5.6.1",
编辑器项目：
 - "@alilc/lowcode-engine": "^1.1.4",
 - "@alilc/lowcode-engine-ext": "^1.0.5",

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by hinhinlaw** [comment]
找到原因了，编辑器中要添加第三方库，需要在资产包中的packages添加：
<img width="515" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/61171216/599b7831-36c9-442c-9c38-7eaad9d95551">

虽然一开始也在packages添加了，但是urls里填写的是antd官方介绍的cdnjs中的地址，导致报错了。

后来不使用inject模式打开组件库项目，并且通过控制台找到antd的js地址和css地址，然后cv到packages[].urls中，重新启动项目就可以了
<img width="518" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/61171216/7e2eff9e-87ac-4e57-bc34-dfcd4306844a">

**Comment by hinhinlaw** [comment]
但是即使我在组件库项目中没安装antd，也是能用的，看了下应该是运行时通过cdn方式引入了antd。但是如果我想用antd@5呢？貌似没有地方可以升级antd依赖的版本？

**Comment by 19CherYl95** [comment]
> 但是即使我在组件库项目中没安装antd，也是能用的，看了下应该是运行时通过cdn方式引入了antd。但是如果我想用antd@5呢？貌似没有地方可以升级antd依赖的版本？

所以最后用了antd@5的版本了么

**Comment by renruijun** [comment]
你好，

> 找到原因了，编辑器中要添加第三方库，需要在资产包中的packages添加： <img alt="image" width="515" src="https://private-user-images.githubusercontent.com/61171216/245717847-599b7831-36c9-442c-9c38-7eaad9d95551.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2OTc2MDYsIm5iZiI6MTcyMjY5NzMwNiwicGF0aCI6Ii82MTE3MTIxNi8yNDU3MTc4NDctNTk5Yjc4MzEtMzZjOS00NDJjLTljMzgtN2VhYWQ5ZDk1NTUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDE1MDE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWFhYTAxYzY4NWIyYTYyZDBhZDEyMDJmODUwYjQ4OTMyYTM1NmNkMGYxMWMzNGUwODE3NTkyOTkxYzcwOGYyOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.crbHS0vAxP41qChAAGTOwGh2i7FFMHnfghD7RCN4848">
> 
> 虽然一开始也在packages添加了，但是urls里填写的是antd官方介绍的cdnjs中的地址，导致报错了。
> 
> 后来不使用inject模式打开组件库项目，并且通过控制台找到antd的js地址和css地址，然后cv到packages[].urls中，重新启动项目就可以了 <img alt="image" width="518" src="https://private-user-images.githubusercontent.com/61171216/245718648-7e2eff9e-87ac-4e57-bc34-dfcd4306844a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI2OTc2MDYsIm5iZiI6MTcyMjY5NzMwNiwicGF0aCI6Ii82MTE3MTIxNi8yNDU3MTg2NDgtN2UyZWZmOWUtODdhYy00ZTU3LWJjMzQtZGZjZDQzMDY4NDRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAzVDE1MDE0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyOWU4N2FmMWUzMjdkYTUxODIyZGIzMmRhNWRlYzcxZTgyNWY5ZmVlNzdhOGMyODIzMWUxZmMxNjBiZTg1ZjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.uRtHOeLx9EhOZE_VsDdjuCHqscfzraau9TSzHizeJdQ">

你好，我遇到了和你一样的问题， 但是你的解决方案里面引用的还是4.x版本的antd啊？我使用4.x也可以，但是换成5.19.3版本就会报组件找不到。
