### ISSUE TITLE
@lowcode-code-generator按照文档出码不工作

### ISSUE THREAD

**Issue by frogo** [alibaba/lowcode-engine#2189]
按照https://lowcode-engine.cn/site/docs/guide/expand/runtime/codeGeneration 提示的出码步骤，
node环境下不工作，无法生成ice3.0的框架代码，麻烦大佬帮忙看看是为什么。
我在node环境打印了codeGeneration 变量，并没有solutions。
![微信图片_20230614161430](https://github.com/alibaba/lowcode-engine/assets/3413313/206ccdff-eb0f-4a33-90fa-9f5233acd635)
![微信图片_20230614161435](https://github.com/alibaba/lowcode-engine/assets/3413313/59437182-d69d-419b-9ade-09b6826db44b)

**Comment by LeoYuan** [comment]
有个 issue 讲 default 的问题，这是构建工具会解决的~

**Comment by frogo** [comment]
> 有个 issue 讲 default 的问题，这是构建工具会解决的~

浩哥，没懂是什么意思啊，可否具体点

**Comment by LeoYuan** [comment]
https://github.com/alibaba/lowcode-engine/issues/1260

**Comment by LeoYuan** [comment]
https://github.com/alibaba/lowcode-engine/issues/693#issuecomment-1487875514

**Comment by frogo** [comment]
> #1260

CodeGenerator.default.xxx已经可以工作了，生成的出码框架还是ice.js 1.0不知道3.0怎么配置出来啊·
![1686732575804](https://github.com/alibaba/lowcode-engine/assets/3413313/93ec5416-0f6d-4348-a3cf-18baece14ebc)
