### ISSUE TITLE
高级抽屉组件，默认显示属性（visible），无法用状态动态控制

### ISSUE THREAD

**Issue by baieceo** [alibaba/lowcode-engine#219]
## **Describe the bug (required)** / **详细描述 bug（必填）**
高级抽屉组件的visible属性绑定状态后，只有在初始状态值为true时显示，当通过按钮或其它方式动态修改visible属性对应的状态时无效
A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
https://lowcode-engine.cn/demo

Steps to reproduce the behavior: / 详细复现步骤：
1. 打开 https://lowcode-engine.cn/demo demo页
2. 从组件库中拖拽高级抽屉组件至画布
3. 组件默认显示属性绑定isShowDialog状态
4. 将isShowDialog状态修改为true，并保存代码
5. 从组件面板拖拽按钮组件至画布
6. 给按钮组件绑定已有事件onClick，按钮文字命名为“”打开抽屉“”
7. 点击预览按钮，预览页面，此时抽屉组件显示，证明组件受控于状态isShowDialog
8. 点击抽屉组件上的取消按钮，关闭drawer抽屉组件
9. 点击打开抽屉按钮，抽屉不显示
---

English version example：
10. Click on '....'
11. Scroll down to '....'
12. See error

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为
抽屉组件visible属性受控于所绑定状态
---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
![image](https://user-images.githubusercontent.com/19337357/160588171-600ce6cb-a3e6-4193-bbb4-0887615c3140.png)
![image](https://user-images.githubusercontent.com/19337357/160588392-7e8b1615-8eff-4bb7-8fe9-e21492127ace.png)
![image](https://user-images.githubusercontent.com/19337357/160588591-ee4fe306-e74a-4d24-84da-167dec6f53dd.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g.  v1.0.3-beta.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. v1.0.3] / 低代码引擎扩展包版本
 - Browser [e.g. chrome] / 浏览器版本 版本 99.0.4844.82（正式版本） （64 位）
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by liujuping** [comment]
[drawer.json.zip](https://github.com/alibaba/lowcode-engine/files/8385542/drawer.json.zip)

参考上面的 schema，进行配置。

和 https://github.com/alibaba/lowcode-engine/issues/241 类似

**Comment by baieceo** [comment]
> [drawer.json.zip](https://github.com/alibaba/lowcode-engine/files/8385542/drawer.json.zip)
> 
> 参考上面的 schema，进行配置。
> 
> 和 #241 类似

非常感谢，有两个问题。
1. 宜搭上按照设置visible这种方式可以控制显隐，所以惯性的以为低码引擎也可以，属性上可否多加一些提示。
2. this.$('refId') 确认了确实可以控制，但是找schema有点麻烦，后续是否可以考虑把refId回显在设置器面板上。

**Comment by wujingang** [comment]
还是存在问题呀.   
https://lowcode-engine.cn/demo    =》 schema替换上面的json。 =》 保存
如果抽屉是 选中状态  预览  是正常open
抽屉是隐藏状态 预览，还是取不到实例   实例打印undefined
![image](https://user-images.githubusercontent.com/28778247/161375950-72b5f6ed-d0e5-4ae7-bf66-8df8a7390b0a.png)

**Comment by hhqqnu** [comment]
> 还是存在问题呀. https://lowcode-engine.cn/demo =》 schema替换上面的json。 =》 保存 如果抽屉是 选中状态 预览 是正常open 抽屉是隐藏状态 预览，还是取不到实例 实例打印undefined ![image](https://user-images.githubusercontent.com/28778247/161375950-72b5f6ed-d0e5-4ae7-bf66-8df8a7390b0a.png)

每次预览前，都需要将对话框设置为显示
<img width="1472" alt="image" src="https://user-images.githubusercontent.com/2911670/162565212-386e8b37-9a5d-4f1b-8f82-969187961c60.png">

**Comment by LeoYuan** [comment]
@liujuping https://github.com/alibaba/lowcode-demo/pull/12 是修复这个问题？

**Comment by liujuping** [comment]
> @liujuping [alibaba/lowcode-demo#12](https://github.com/alibaba/lowcode-demo/pull/12) 是修复这个问题？

是的，这个问题也修复了。
