### ISSUE TITLE
如何引用antd的组件，例如按钮、icon等组件

### ISSUE THREAD

**Issue by wlk199718** [alibaba/lowcode-engine#2196]
如题，我看demo里边引入的按钮都是next的， import { Button } from '@alifd/next'; 现在像想用antd的组件要怎么引用 import { Button } from 'antd';吗？

**Comment by JackLian** [comment]
不建议引入antd的，引擎中目前依赖fusion，也建议都是用fusion的基础组件做插件面板

**Comment by wlk199718** [comment]
主要是我看fusion社区不活跃，后续如果出现问题有人协助解决吗
