### ISSUE TITLE
低代码组件之间怎么通信？或者说低代码内部的变量怎么暴露给外部调用？

### ISSUE THREAD

**Issue by zhuyuanmin** [alibaba/lowcode-engine#2199]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

如下截图，我有一个form表单组件，表单字段校验是组件内部维护的，但是正常逻辑应该点击 modal 的确定按钮触发表单的 form.validateFields()，由于内部 form 对象没法暴露出去，所有 modal 组件拿不到 form，没法进行校验，请问解决方案么？

![截图](https://github.com/alibaba/lowcode-engine/assets/23226876/9f27452f-5dda-4ce4-84f5-87ffaab1c332)

**Comment by JackLian** [comment]
就像普通的前端源码开发处理类似情况一样，该暴露成prop就暴露，想提供事件就提供事件，低代码并没有改变这个模式
