### ISSUE TITLE
规划中和nocobase的差异化在哪些点上呢？请指教

### ISSUE THREAD

**Issue by chenshuichao** [alibaba/lowcode-engine#22]
这个项目挺好的，要是和nocobase能够相互借鉴就更好了。

**Comment by JackLian** [comment]
lowcode-engine是阿里巴巴集团内部在低代码领域实践中建设沉淀下来的前端低代码体系，在内部已经打磨了一段时间了，支撑了阿里集团内部几十个低代码相关平台，开源出来一方面是希望能够将我们沉淀的标准和实现开放，一方面也是希望接受更大范围的挑战和打磨，业界有很多已经开源或开放使用的平台和技术产品，不过本引擎主要还是按自己的发展思路向前演进，目前还没有针对哪个竞品进行对标对比。
