### ISSUE TITLE
请教设计器实现拖拽的原理

### ISSUE THREAD

**Issue by zxlaole** [alibaba/lowcode-engine#2203]
html5实现拖动要求设置draggable属性，但引擎源代码中并没有设置draggable，同样实现了通过事件实现组件拖放。
请指点一下实现原理。

**Comment by JackLian** [comment]
https://lowcode-engine.cn/site/docs/guide/design/editor#%E6%8B%96%E6%8B%BD%E5%BC%95%E6%93%8E--%E6%8B%96%E6%8B%BD%E5%AE%9A%E4%BD%8D%E6%9C%BA%E5%88%B6
