### ISSUE TITLE
rax 多组件物料库启动后组件无法渲染

### ISSUE THREAD

**Issue by AliceChenChina** [alibaba/lowcode-engine#2204]
1. 执行 npm init @alilc/element raxs 初始化一个仓库
2. npm install 之后运行npm run lowcode:dev，启动正常，
3. 访问http://localhost:3333/ 控制台报错
4.
![image](https://github.com/alibaba/lowcode-engine/assets/21055858/fec4feb6-c82c-4af4-aa12-c749b629cf3c)
5. 把内嵌的样例组件拖到画布后无法显示，控制台报错如下
![image](https://github.com/alibaba/lowcode-engine/assets/21055858/883268a9-e78d-4079-8dd9-32b6ffc623d8)
![image](https://github.com/alibaba/lowcode-engine/assets/21055858/b1504d2e-a275-41ed-9d88-81bb74a7ee1e)
![image](https://github.com/alibaba/lowcode-engine/assets/21055858/9da65f5f-0471-476e-94ce-9592bec18159)
![image](https://github.com/alibaba/lowcode-engine/assets/21055858/a938df9e-1d33-4cbd-9567-ebc98d3ed45b)

**Comment by eternalsky** [comment]
rax 官方已经停止维护了，我们也即将关闭 rax 物料的初始化入口，建议如果还没有采用 rax 的方案的情况下，还是换用其他方案吧。

**Comment by AliceChenChina** [comment]
> rax 官方已经停止维护了，我们也即将关闭 rax 物料的初始化入口，建议如果还没有采用 rax 的方案的情况下，还是换用其他方案吧。


> rax 官方已经停止维护了，我们也即将关闭 rax 物料的初始化入口，建议如果还没有采用 rax 的方案的情况下，还是换用其他方案吧。

> rax 官方已经停止维护了，我们也即将关闭 rax 物料的初始化入口，建议如果还没有采用 rax 的方案的情况下，还是换用其他方案吧。

你好，在编辑器还是支持rax出码功能的吧？

**Comment by eternalsky** [comment]
同上回复，所有 rax 功能都将停止维护或下线。
