### ISSUE TITLE
给属性绑定变量的时候无法显示state中布尔类型的变量

### ISSUE THREAD

**Issue by little-yaonv** [alibaba/lowcode-engine#2205]
![image](https://github.com/alibaba/lowcode-engine/assets/75791730/6aa77cd7-d27e-4e96-b027-ded12df196b9)
![image](https://github.com/alibaba/lowcode-engine/assets/75791730/470bee00-42f6-422b-9ca6-783b8d55511a)

**Comment by LAMMUpro** [comment]
我也遇到这个问题了，其实不是布尔值不会显示，是值为假值的都不会显示（0|""|null|false|undefined），将@alilc/lowcode-engine-ext版本更新到1.0.7-beta.1
![b1cc0a84a4e8902d8fdff687b7bef63](https://github.com/alibaba/lowcode-engine/assets/38106851/d32286b4-b55f-43ee-be65-b9199d349289)

**Comment by little-yaonv** [comment]
好的，谢谢您！




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/lowcode-engine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年8月9日(星期三) 上午9:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/lowcode-engine] 给属性绑定变量的时候无法显示state中布尔类型的变量 (Issue #2205)





 
***@***.***/lowcode-engine-ext版本更新到1.0.7-beta.1
