### ISSUE TITLE
Duplicate plugin/preset detected

### ISSUE THREAD

**Issue by lilithyang2018** [alibaba/lowcode-engine#2208]
同样的错误
lowcode-plugins/packages/action-block 项目build 报错

![build-error](https://github.com/alibaba/lowcode-engine/assets/39897706/fb7b4222-fe52-4cc2-a3dd-ad7704539704)
依赖的lowcode-engine的版本是最新的1.1.7

_Originally posted by @lilithyang2018 in https://github.com/alibaba/lowcode-engine/issues/1484#issuecomment-1598485278_

**Comment by JackLian** [comment]
应该是buildscript配置问题

**Comment by lilithyang2018** [comment]
@JackLian 今天偶然翻到了你之前在ice那边提交的issue
https://github.com/ice-lab/build-scripts/issues/121

然后我在plugin这边 去掉了resolution中对@builder/babel-preset-ice版本的约束，重新安装依赖 就可以build成功了
![babel-preset-ice](https://github.com/alibaba/lowcode-engine/assets/39897706/a04e044c-c635-452c-a3b1-8ceada5bf92c)

**Comment by JackLian** [comment]
好的，这边先关闭了
