### ISSUE TITLE
Plugin with name LowcodePluginInjectAlt exists

### ISSUE THREAD

**Issue by liulangsven** [alibaba/lowcode-engine#2214]
![image](https://github.com/alibaba/lowcode-engine/assets/33243742/2359e1ae-4732-47a1-bd72-953d787084da)

![image](https://github.com/alibaba/lowcode-engine/assets/33243742/40427350-c7ad-4df4-b333-d608c8632087)

请问这是什么问题 什么情况会报这种错误 全局都没有搜到LowcodePluginInjectAlt这个东西

**Comment by JackLian** [comment]
也可以搜一下Inject关键字

**Comment by liulangsven** [comment]
ok 我知道了

**Comment by ZhengLiJing** [comment]
@liulangsven 请问是如何解决的呢？

**Comment by drizzlesconsin** [comment]
多次调用 `registerPlugins({ a, b, c }); ` 导致的问题，如果有数据要传进去给插件用，数据 ok了再 render registerPlugins 所在的组件。

大概就是 `loading ?  <Loading /> : <LowCode />`

> _留个思路, 给后面遇到这个问题的_
