### ISSUE TITLE
出码后的项目可以去掉左侧菜单栏和顶部栏吗

### ISSUE THREAD

**Issue by hinhinlaw** [alibaba/lowcode-engine#2215]
## **Describe the bug (required)** / **详细描述 bug（必填）**
我是用服务端出码的，也就是用这里的第三点https://lowcode-engine.cn/site/docs/guide/expand/runtime/codeGeneration#%E5%A6%82%E4%BD%95%E4%BD%BF%E7%94%A8。
出码导出的代码，可以去掉左侧菜单栏和顶部栏吗。
如果我只想要我搭建出来的单个页面可以怎么做呢？

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
1. 按照文档的“3) 服务端出码接入”来出码
2. 进入出码的项目，执行npm i和npm run start

---

## **Screenshots (optional)** / **bug 截图（可选）**
<img width="1679" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/61171216/36e20919-8594-4d73-ba5b-2d9049cfc44c">
红色框部分不要

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - "@alilc/lowcode-code-generator": "^1.1.4"

**Comment by wangronglei** [comment]
出码后其实就是正常的icejs react项目了，你修改routes.js以及src/layouts，其实就行了

**Comment by hinhinlaw** [comment]
> 出码后其实就是正常的icejs react项目了，你修改routes.js以及src/layouts，其实就行了

好的，感谢
