### ISSUE TITLE
能了解一下LAB中HTML物料的编辑代码的setter是用什么react 组件实现的吗？

### ISSUE THREAD

**Issue by zhiwei55** [alibaba/lowcode-engine#2217]
有些页面相关当前开源的物料组件无法实现，所以打算实现一个 LAB 那样的HTML物料组件，不知道LAB里的html editor的 setter是用什么三方组件实现的？还是自己实现的？不知道是否会开源HTML物料？

**Comment by woshilaoge** [comment]
@zhiwei55  LAB 中的 HTML 组件是自行实现的，暂不开源。 HTML 组件的属性配置 setter 是 自建的 CodeSetter，非全部自行实现，依赖了三方组件 monaco-editor 。查看这个组件节点也能查得到。
