### ISSUE TITLE
自定义组件出码后丢失样式

### ISSUE THREAD

**Issue by hinhinlaw** [alibaba/lowcode-engine#2221]
## **Describe the bug (required)** / **详细描述 bug（必填）**
自定义组件是基于antd@4进行二次开发的，自定义组件库和编辑器是根据官方脚手架来生成的。自定义组件在编辑器和预览的时候正常，我使用的是服务端出码，出码后用antd二次开发的自定义组件丢失了样式，但是编辑器自带的组件样式是正常的

ps：我服务端出码的做法是：在浏览器编辑器中拿到当前画布的schema，然后手动复制粘贴到node项目的一个.json中，projectBuilder.generateProject传的schema就是这个.json中的数据，出码项目输出到指定目录后，再安装依赖和启动出码项目

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
antd组件也能正常显示样式

---

## **Screenshots (optional)** / **bug 截图（可选）**
编辑器中：
<img width="1680" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/61171216/8a323fbc-8a4c-42fe-934b-cdb4609100a3">
出码：
<img width="1680" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/61171216/565f6e0c-c1bb-468c-83ab-32588d76eb4b">

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - "@alilc/lowcode-engine": "^1.1.4"
 - "@alilc/lowcode-code-generator": "^1.1.4"

---

**Comment by hinhinlaw** [comment]
贴个传递到projectBuilder.generateProject的schema的示例：
{"version":"1.0.0","componentsMap":[{"package":"hc-lc-components-lib","version":"0.1.6","exportName":"HcInput","main":"lib/index.js","destructuring":true,"subName":"","componentName":"HcInput"},{"package":"hc-lc-components-lib","version":"0.1.6","exportName":"HcForm","main":"lib/index.js","destructuring":true,"subName":"","componentName":"HcForm"},{"package":"@alifd/next","version":"1.25.23","exportName":"Divider","main":"","destructuring":true,"subName":"","componentName":"Divider"},{"package":"@alifd/fusion-ui","version":"2.0.0","exportName":"ProTable","main":"lib/index.js","destructuring":true,"subName":"","componentName":"ProTable"},{"devMode":"lowCode","componentName":"Page"}],"componentsTree":[{"componentName":"Page","id":"node_dockcviv8fo1","props":{"ref":"outerView","style":{"height":"100%"}},"docId":"doclaqkk3b9","fileName":"/","dataSource":{"list":[{"type":"fetch","isInit":false,"options":{"params":{},"method":"GET","isCors":true,"timeout":5000,"headers":{},"uri":"http://localhost:22000/listData"},"id":"list_data","dataHandler":{"type":"JSFunction","value":"function(res) {\n  return res.data\n}"}},{"type":"fetch","isInit":false,"options":{"params":{},"method":"POST","isCors":true,"timeout":5000,"headers":{"Content-Type":"application/json; charset=utf-8"},"uri":"http://localhost:22000/listData"},"id":"add_list_data"},{"type":"fetch","isInit":false,"options":{"params":{},"method":"DELETE","isCors":true,"timeout":5000,"headers":{"Content-Type":"application/json; charset=utf-8"},"uri":"http://localhost:22000/listData"},"id":"delete_list_data"},{"type":"fetch","isInit":false,"options":{"params":{},"method":"PUT","isCors":true,"timeout":5000,"headers":{"Content-Type":"application/json; charset=utf-8"},"uri":"http://localhost:22000/listData"},"id":"update_list_data"}]},"state":{"text":{"type":"JSExpression","value":"\"outer\""},"isShowDialog":{"type":"JSExpression","value":"true"},"listData":{"type":"JSExpression","value":"[]"},"isEdit":{"type":"JSExpression","value":"false"},"currEditId":{"type":"JSExpression","value":"null"},"formData":{"type":"JSExpression","value":"{\n  name: '',\n  age: null,\n  gender: null,\n  address: '',\n  phone: ''\n}"}},"css":"body {\n  font-size: 12px;\n}\n\n.button {\n  width: 100px;\n  color: #ff00ff\n}","lifeCycles":{"componentDidMount":{"type":"JSFunction","value":"function componentDidMount() {\n  const fetchData = async () => {\n    // 请求“数据源“面板中配置的接口\n    const res = await this.dataSourceMap.list_data.load();\n    if (res !== null && res !== void 0 && res.length) {\n      this.setState({\n        listData: res\n      });\n    }\n  };\n  fetchData();\n}","source":"function componentDidMount() {\n  const fetchData = async () => {\n    // 请求“数据源“面板中配置的接口\n    const res = await this.dataSourceMap.list_data.load();\n    if (res?.length) {\n      this.setState({\n        listData: res\n      });\n    }\n  };\n  fetchData();\n}"},"componentWillUnmount":{"type":"JSFunction","value":"function componentWillUnmount() {}","source":"function componentWillUnmount() {}"}},"methods":{"handleOpenFormDialog":{"type":"JSFunction","value":"function handleOpenFormDialog() {\n  const {\n    isShowDialog\n  } = this.state;\n  this.setState({\n    isShowDialog: true\n  });\n}","source":"function handleOpenFormDialog() {\n  const {\n    isShowDialog\n  } = this.state;\n  this.setState({\n    isShowDialog: true\n  });\n}"},"handleCancel":{"type":"JSFunction","value":"function handleCancel() {\n  this.setState({\n    isShowDialog: false\n  });\n}","source":"function handleCancel() {\n  this.setState({\n    isShowDialog: false\n  });\n}"},"handleSubmit":{"type":"JSFunction","value":"function handleSubmit(data) {\n  return new Promise(async (resolve, reject) => {\n    try {\n      const values = data.map(item => Object.values(item)[0]);\n      const formData = {\n        name: values[0],\n        age: values[1],\n        gender: values[2],\n        address: values[3],\n        phone: values[4]\n      };\n      let res;\n      if (this.state.isEdit) {\n        res = await this.dataSourceMap.update_list_data.load({\n          ...formData,\n          id: this.state.currEditId\n        });\n      } else {\n        res = await this.dataSourceMap.add_list_data.load(formData);\n      }\n      this.setState({\n        listData: res,\n        isEdit: false,\n        currEditId: null\n      }, () => {\n        resolve(true);\n      });\n    } catch (err) {\n      reject(false);\n    }\n  });\n}","source":"function handleSubmit(data) {\n  return new Promise(async (resolve, reject) => {\n    try {\n      const values = data.map(item => Object.values(item)[0]);\n      const formData = {\n        name: values[0],\n        age: values[1],\n        gender: values[2],\n        address: values[3],\n        phone: values[4]\n      };\n      let res;\n      if (this.state.isEdit) {\n        res = await this.dataSourceMap.update_list_data.load({\n          ...formData,\n          id: this.state.currEditId\n        });\n      } else {\n        res = await this.dataSourceMap.add_list_data.load(formData);\n      }\n      this.setState({\n        listData: res,\n        isEdit: false,\n        currEditId: null\n      }, () => {\n        resolve(true);\n      });\n    } catch (err) {\n      reject(false);\n    }\n  });\n}"},"handleDeleteData":{"type":"JSFunction","value":"async function handleDeleteData(e, data) {\n  const {\n    rowRecord: {\n      id\n    }\n  } = data;\n  const res = await this.dataSourceMap.delete_list_data.load({\n    id\n  });\n  this.setState({\n    listData: res\n  });\n}","source":"async function handleDeleteData(e, data) {\n  const {\n    rowRecord: {\n      id\n    }\n  } = data;\n  const res = await this.dataSourceMap.delete_list_data.load({\n    id\n  });\n  this.setState({\n    listData: res\n  });\n}"},"handleUpdateData":{"type":"JSFunction","value":"function handleUpdateData(e, data) {\n  if (this.$('hcform-68d05888')) {\n    // 通过this.$(refId)可以拿到React组件实例\n    // refId可以在组件设置面板的高级中查看\n\n    // 注意，React组件如果是函数组件，并且需要暴露属性/方法的话，需要用forwardRef转发ref，跟我们写代码一样的\n    // 在使用forwardRef后，return出来的JSX要指定一下ref，否则在画布中，组件无法被选中\n    const ref = this.$('hcform-68d05888');\n    ref.handleSetFieldValues(data.rowRecord);\n    this.setState({\n      currEditId: data.rowRecord.id,\n      isEdit: true\n    });\n  }\n}","source":"function handleUpdateData(e, data) {\n  if (this.$('hcform-68d05888')) {\n    // 通过this.$(refId)可以拿到React组件实例\n    // refId可以在组件设置面板的高级中查看\n\n    // 注意，React组件如果是函数组件，并且需要暴露属性/方法的话，需要用forwardRef转发ref，跟我们写代码一样的\n    // 在使用forwardRef后，return出来的JSX要指定一下ref，否则在画布中，组件无法被选中\n    const ref = this.$('hcform-68d05888');\n    ref.handleSetFieldValues(data.rowRecord);\n    this.setState({\n      currEditId: data.rowRecord.id,\n      isEdit: true\n    });\n  }\n}"},"handleSubmit2":{"type":"JSFunction","value":"async function handleSubmit2(data) {\n  console.log(data);\n  const res = await this.dataSourceMap.add_list_data.load(data);\n  this.setState({\n    listData: res,\n    formData: {}\n  });\n}","source":"async function handleSubmit2(data) {\n  console.log(data);\n  const res = await this.dataSourceMap.add_list_data.load(data);\n  this.setState({\n    listData: res,\n    formData: {}\n  });\n}"},"handleDeleteData2":{"type":"JSFunction","value":"async function handleDeleteData2(e, data) {\n  const {\n    rowRecord: {\n      id\n    }\n  } = data;\n  const res = await this.dataSourceMap.delete_list_data.load({\n    id\n  });\n  this.setState({\n    listData: res\n  });\n}","source":"async function handleDeleteData2(e, data) {\n  const {\n    rowRecord: {\n      id\n    }\n  } = data;\n  const res = await this.dataSourceMap.delete_list_data.load({\n    id\n  });\n  this.setState({\n    listData: res\n  });\n}"},"handleResetFields2":{"type":"JSFunction","value":"function handleResetFields2() {\n  // this.setState({\n  //   formData: {}\n  // })\n}","source":"function handleResetFields2() {\n  // this.setState({\n  //   formData: {}\n  // })\n}"},"handleInputChange":{"type":"JSFunction","value":"function handleInputChange(data) {\n  this.setState({\n    formData: {\n      ...this.state.formData,\n      name: data\n    }\n  });\n}","source":"function handleInputChange(data) {\n  this.setState({\n    formData: {\n      ...this.state.formData,\n      name: data\n    }\n  });\n}"},"handleInputChange1":{"type":"JSFunction","value":"function handleInputChange1(data) {\n  this.setState({\n    formData: {\n      ...this.state.formData,\n      age: Number(data)\n    }\n  });\n}","source":"function handleInputChange1(data) {\n  this.setState({\n    formData: {\n      ...this.state.formData,\n      age: Number(data)\n    }\n  });\n}"},"handleInputChange2":{"type":"JSFunction","value":"function handleInputChange2(data) {\n  this.setState({\n    formData: {\n      ...this.state.formData,\n      gender: Number(data)\n    }\n  });\n}","source":"function handleInputChange2(data) {\n  this.setState({\n    formData: {\n      ...this.state.formData,\n      gender: Number(data)\n    }\n  });\n}"},"handleInputChange3":{"type":"JSFunction","value":"function handleInputChange3(data) {\n  this.setState({\n    formData: {\n      ...this.state.formData,\n      address: data\n    }\n  });\n}","source":"function handleInputChange3(data) {\n  this.setState({\n    formData: {\n      ...this.state.formData,\n      address: data\n    }\n  });\n}"},"handleInputChange4":{"type":"JSFunction","value":"function handleInputChange4(data) {\n  this.setState({\n    formData: {\n      ...this.state.formData,\n      phone: data\n    }\n  });\n}","source":"function handleInputChange4(data) {\n  this.setState({\n    formData: {\n      ...this.state.formData,\n      phone: data\n    }\n  });\n}"}},"originCode":"class LowcodeComponent extends Component {\n  state = {\n    \"text\": \"outer\",\n    \"isShowDialog\": true,\n    \"listData\": [],\n    isEdit: false, // false -> 创建 true -> 编辑\n    currEditId: null, // 编辑的row的id\n    formData: {\n      name: '',\n      age: null,\n      gender: null,\n      address: '',\n      phone: ''\n    }\n  }\n  componentDidMount() {\n    const fetchData = async () => {\n      // 请求“数据源“面板中配置的接口\n      const res = await this.dataSourceMap.list_data.load()\n      if (res?.length) {\n        this.setState({\n          listData: res\n        })\n      }\n    }\n    fetchData()\n  }\n  componentWillUnmount() {\n\n  }\n\n  handleOpenFormDialog() {\n    const { isShowDialog } = this.state\n    this.setState({\n      isShowDialog: true\n    })\n  }\n\n  handleCancel() {\n    this.setState({\n      isShowDialog: false\n    })\n  }\n\n  // 提交表单\n  handleSubmit(data) {\n    return new Promise(async (resolve, reject) => {\n      try {\n        const values = data.map(item => Object.values(item)[0])\n        const formData = {\n          name: values[0],\n          age: values[1],\n          gender: values[2],\n          address: values[3],\n          phone: values[4],\n        }\n        let res\n        if (this.state.isEdit) {\n          res = await this.dataSourceMap.update_list_data.load({\n            ...formData,\n            id: this.state.currEditId\n          })\n        } else {\n          res = await this.dataSourceMap.add_list_data.load(formData)\n        }\n        this.setState({\n          listData: res,\n          isEdit: false,\n          currEditId: null\n        }, () => {\n          resolve(true)\n        })\n      } catch (err) {\n        reject(false)\n      }\n    })\n  }\n\n  // 删除单条数据\n  async handleDeleteData(e, data) {\n    const { rowRecord: { id } } = data\n    const res = await this.dataSourceMap.delete_list_data.load({\n      id\n    })\n    this.setState({\n      listData: res\n    })\n  }\n\n  // 更新数据\n  handleUpdateData(e, data) {\n    if (this.$('hcform-68d05888')) {\n      // 通过this.$(refId)可以拿到React组件实例\n      // refId可以在组件设置面板的高级中查看\n\n      // 注意，React组件如果是函数组件，并且需要暴露属性/方法的话，需要用forwardRef转发ref，跟我们写代码一样的\n      // 在使用forwardRef后，return出来的JSX要指定一下ref，否则在画布中，组件无法被选中\n      const ref = this.$('hcform-68d05888')\n      ref.handleSetFieldValues(data.rowRecord)\n      this.setState({\n        currEditId: data.rowRecord.id,\n        isEdit: true\n      })\n    }\n  }\n\n  // -------- \n  // 自带表单-提交表单\n  async handleSubmit2(data) {\n    console.log(data)\n    const res = await this.dataSourceMap.add_list_data.load(data)\n    this.setState({\n      listData: res,\n      formData: {}\n    })\n  }\n\n  async handleDeleteData2(e, data){\n    const {rowRecord: {id}} = data\n    const res = await this.dataSourceMap.delete_list_data.load({\n      id\n    })\n    this.setState({\n      listData: res\n    })\n  }\n\n  handleResetFields2(){\n    // this.setState({\n    //   formData: {}\n    // })\n  }\n\n  handleInputChange(data) {\n    this.setState({\n      formData: {\n        ...this.state.formData,\n        name: data\n      }\n    })\n  }\n  handleInputChange1(data) {\n    this.setState({\n      formData: {\n        ...this.state.formData,\n        age: Number(data)\n      }\n    })\n  }\n  handleInputChange2(data) {\n    this.setState({\n      formData: {\n        ...this.state.formData,\n        gender: Number(data)\n      }\n    })\n  }\n  handleInputChange3(data) {\n    this.setState({\n      formData: {\n        ...this.state.formData,\n        address: data\n      }\n    })\n  }\n  handleInputChange4(data) {\n    this.setState({\n      formData: {\n        ...this.state.formData,\n        phone: data\n      }\n    })\n  }\n}","hidden":false,"title":"","isLocked":false,"condition":true,"conditionGroup":"","children":[{"componentName":"HcForm","id":"node_oclj43ith71","props":{"value":"","__events":{"eventDataList":[{"type":"componentEvent","name":"onClick","relatedEventName":"handleSubmit"}],"eventList":[{"name":"onClick","disabled":true}]},"onClick":{"type":"JSFunction","value":"function(){return this.handleSubmit.apply(this,Array.prototype.slice.call(arguments).concat([])) }"},"ref":"hcform-68d05888"},"hidden":false,"title":"","isLocked":false,"condition":true,"conditionGroup":"","children":[{"componentName":"HcInput","id":"node_oclj5cmbmd1","props":{"componentName":"","defaultValue":"","state":1,"placeholder":"请输入","prefix":{"type":"text","checked":true,"content":"姓名"},"suffix":{"type":"text","checked":false,"content":""},"title":{"checked":false,"content":"","position":"left_top","space":0,"starPosition":"left","isShowTooltip":false},"visible":true,"validation":{"checked":false,"required":false,"min":{"message":""},"max":{"message":""},"formatCheck":false,"expressionCheck":false},"key":"name","formKey":"name","fieldKey":"name"},"hidden":false,"title":"","isLocked":false,"condition":true,"conditionGroup":""},{"componentName":"HcInput","id":"node_oclj5cmbmd2","props":{"componentName":"","defaultValue":"","state":1,"placeholder":"请输入","prefix":{"type":"text","checked":true,"content":"年龄"},"suffix":{"type":"text","checked":false,"content":""},"title":{"checked":false,"content":"","position":"left_top","space":0,"starPosition":"left","isShowTooltip":false},"visible":true,"validation":{"checked":true,"required":false,"min":{"message":""},"max":{"message":""},"formatCheck":{"checked":true,"value":"number","message":"请输入数字"},"expressionCheck":false},"key":"age","formKey":"age","fieldKey":"age"},"hidden":false,"title":"","isLocked":false,"condition":true,"conditionGroup":""},{"componentName":"HcInput","id":"node_oclj5drnia1","props":{"componentName":"","defaultValue":"","state":1,"placeholder":"请输入","prefix":{"type":"text","checked":true,"content":"性别"},"suffix":{"type":"text","checked":false,"content":""},"title":{"checked":false,"content":"","position":"left_top","space":0,"starPosition":"left","isShowTooltip":false},"visible":true,"validation":{"checked":true,"required":false,"min":{"message":""},"max":{"message":""},"formatCheck":{"checked":false,"value":"number","message":"请输入数字"},"expressionCheck":false},"key":"gender","formKey":"gender","fieldKey":"gender"},"hidden":false,"title":"","isLocked":false,"condition":true,"conditionGroup":""},{"componentName":"HcInput","id":"node_oclj5drnia2","props":{"componentName":"","defaultValue":"","state":1,"placeholder":"请输入","prefix":{"type":"text","checked":true,"content":"地址"},"suffix":{"type":"text","checked":false,"content":""},"title":{"checked":false,"content":"","position":"left_top","space":0,"starPosition":"left","isShowTooltip":false},"visible":true,"validation":{"checked":false,"required":false,"min":{"message":""},"max":{"message":""},"formatCheck":{"checked":false,"value":"number","message":"请输入数字"},"expressionCheck":false},"key":"address","formKey":"address","fieldKey":"address"},"hidden":false,"title":"","isLocked":false,"condition":true,"conditionGroup":""},{"componentName":"HcInput","id":"node_oclj5drnia3","props":{"componentName":"","defaultValue":"","state":1,"placeholder":"请输入","prefix":{"type":"text","checked":true,"content":"电话"},"suffix":{"type":"text","checked":false,"content":""},"title":{"checked":false,"content":"","position":"left_top","space":0,"starPosition":"left","isShowTooltip":false},"visible":true,"validation":{"checked":true,"required":false,"min":{"message":""},"max":{"message":""},"formatCheck":{"checked":true,"value":"number","message":"请输入数字"},"expressionCheck":false},"key":"phone","ref":"hcinput-d9fae3e3","formKey":"phone","fieldKey":"phone"},"hidden":false,"title":"","isLocked":false,"condition":true,"conditionGroup":""}]},{"componentName":"Divider","id":"node_ocljauub611","props":{"prefix":"next-","direction":"hoz","orientation":"center","children":"分隔符","dashed":false},"hidden":false,"title":"","isLocked":false,"condition":true,"conditionGroup":""},{"componentName":"ProTable","id":"node_oclj51h5ph1","props":{"dataSource":{"type":"JSExpression","value":"this.state.listData"},"actionColumnButtons":{"dataSource":[{"children":"编辑","type":"primary","disabled":false,"onClick":{"type":"JSFunction","value":"function(){ return this.handleUpdateData.apply(this,Array.prototype.slice.call(arguments).concat([])) }"}},{"children":"删除","type":"normal","disabled":false,"onClick":{"type":"JSFunction","value":"function(){ return this.handleDeleteData.apply(this,Array.prototype.slice.call(arguments).concat([])) }"}}],"text":true,"visibleButtonCount":3},"actionBarButtons":{"dataSource":[],"visibleButtonCount":3},"paginationProps":{"pageSize":20,"current":1,"hidden":false},"settingButtons":true,"columns":[{"title":"姓名","formatType":"text","dataIndex":"name","_format_options_date":"YYYY-MM-DD HH:mm:ss"},{"title":"年龄","formatType":"text","dataIndex":"age"},{"title":"地址","formatType":"text","dataIndex":"address"},{"title":"性别","formatType":"text","dataIndex":"gender"},{"title":"电话","formatType":"text","dataIndex":"phone"}],"primaryKey":"id","actionColumnProps":{"title":"操作"},"indexColumn":false,"hasBorder":false,"isZebra":false,"fixedHeader":false,"_unsafe_MixedSetter_dataSource_select":"ExpressionSetter","ref":"protable-65e05d28"},"hidden":false,"title":"","isLocked":false,"condition":true,"conditionGroup":""}]}],"i18n":{"zh-CN":{"i18n-jwg27yo4":"你好 ","i18n-jwg27yo3":"{name} 博士"},"en-US":{"i18n-jwg27yo4":"Hello ","i18n-jwg27yo3":"Doctor {name}"}}}

**Comment by LeoYuan** [comment]
检查一下在设计器中的组件样式是哪里来的，正常 antd 组件都是自己 import less 文件，应该不会丢失样式

**Comment by hinhinlaw** [comment]
> 检查一下在设计器中的组件样式是哪里来的，正常 antd 组件都是自己 import less 文件，应该不会丢失样式

在设计器里面我是在assets.json里面添加了antd所以设计器里面样式正常：
<img width="903" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/61171216/1c0c02f7-dd6f-4d51-9845-41faa7489768">
但是出码里面就没有import antd的样式了。

目前解决办法好像只有两个：
1. 在出码里面的/src/pages/$/index.jsx中手动import antd的样式文件
2. 在使用了antd组件的自定义组件里面手动import antd的样式文件，比如：
<img width="1021" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/61171216/461eb5dc-28ee-427b-bec8-c83c5cb9b3d1">

目前来看只能先使用第二种方法解决了。我一开始以为我在自定义组件里面使用了antd组件，在出码里面会自动import样式，但是目前看来不是的。不知道是不是antd组件的问题呢

**Comment by LeoYuan** [comment]
对于antd场景，出码都没有额外引入样式文件，默认是antd物料自己处理样式了。

**Comment by hinhinlaw** [comment]
> 对于antd场景，出码都没有额外引入样式文件，默认是antd物料自己处理样式了。

明白了，谢谢。
不清楚为什么自定义组件内使用了antd@4的组件没有在出码中自动引入样式。目前找到第三个workaround方法，在组件库项目的index.tsx中，手动import antd的样式文件，出码后antd样式就正常了
<img width="606" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/61171216/efe81281-9c24-442d-8c45-20c9c0a23a0c">

那就先这样处理吧

**Comment by wlk199718** [comment]
@hinhinlaw 老哥有联系方式吗请教下自定义出码的问题
