### ISSUE TITLE
设计器画布区，如何屏蔽按钮的点击事件

### ISSUE THREAD

**Issue by lynsun** [alibaba/lowcode-engine#2223]
使用脚手架初始化的编辑器，在设计器的画布区，选中按钮会触发按钮绑定的点击事件

<img width="1353" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/992437/161ab7bf-4c19-4987-8091-74ab818e7e4e">

重现步骤：
1 使用脚手架初始化一个编辑器
2 安装依赖，启动项目
3 拖一个button进去，绑定button的点击事件
4 在设计器画布区选中这个按钮，发现触发了按钮之前绑定的点击事件

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: ^1.1.7
 - AliLowCodeEngineExt version: ^1.0.5
 - Browser： chrome 114

**Comment by liujuping** [comment]
可以通过 config.set('customizeIgnoreSelectors', fun) 配置点击忽略的 selectors。

```
/**
   * 定制画布中点击被忽略的 selectors，默认值：undefined
   */
  customizeIgnoreSelectors?: (defaultIgnoreSelectors: string[]) => string[];
```

**Comment by lynsun** [comment]
> 可以通过 config.set('customizeIgnoreSelectors', fun) 配置点击忽略的 selectors。
> 
> ```
> /**
>  * 定制画布中点击被忽略的 selectors，默认值：undefined
>  */
>   customizeIgnoreSelectors?: (defaultIgnoreSelectors: string[]) => string[];
> ```

好的，多谢，我试一下这个配置
