### ISSUE TITLE
协议错误，线上的低代码配置结果中没有componentsTree这个字段

### ISSUE THREAD

**Issue by shenmingxuanyi** [alibaba/lowcode-engine#2224]
## **Describe the bug (required)** / **详细描述 bug（必填）**
协议错误，线上的低代码配置结果中没有componentsTree这个字段，叫children。

**Comment by JackLian** [comment]
你看错了，另外协议是指导代码实现的，协议本身是正确（typo或表达不清晰可能会有）且稳定的，错的只会是代码实现
