### ISSUE TITLE
关于原子组件及精选组件的一些问题

### ISSUE THREAD

**Issue by zhiwei55** [alibaba/lowcode-engine#2232]
从现有生成的lowcode editor里自带的原子组件及精选组件使用情况来看，一些复杂的组件，比如高级表格，上传组件等，实现的物料属性还是比较有限的，和本身Fusion对应的组件支持的属性比较差距很大，缺失了很大属性和事件，是吗？ 如果需要PR，应该通过Parts来实现，会比较高效吗？

**Comment by eternalsky** [comment]
PR 的话直接去 https://github.com/alibaba/lowcode-materials/tree/main/packages PR 即可，不需要通过 Parts，Parts 也不具备向这个仓库提交 PR 的能力。

**Comment by zhiwei55** [comment]
> PR 的话直接去 https://github.com/alibaba/lowcode-materials/tree/main/packages PR 即可，不需要通过 Parts，Parts 也不具备向这个仓库提交 PR 的能力。

可以通过Parts实现后再手动处理提交PR吗？
