### ISSUE TITLE
如何通过setter的值来动态设置插槽？

### ISSUE THREAD

**Issue by hinhinlaw** [alibaba/lowcode-engine#2233]
## **Describe the bug (required)** / **详细描述 bug（必填）**
目前想写一个栅格布局组件，要求是右侧设置器可以配置一行多少列，比如一行3列的话，那么组件就有三个插槽，类似antd-lowcode-materials这种：
<img width="1395" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/61171216/ffe325e0-d591-4f61-b197-ce526e7a69b2">

根据官方文档，设置插槽有两种：isContianer:true和SlotSetter，但是这两种都不符合需求，isContainer只有单一插槽，而SlotSetter配置后需要在右侧设置器开启。

看了下antd-lowcode-materials的Grid.Row和Grid.Col源码，没有使用SlotSetter，而是使用isContainer: true，但是没看到具体的Grid.Row组件的代码，请问这里要怎么在不使用SlotSetter的情况下一个组件可以有多个插槽呢？
<img width="1219" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/61171216/9e8a62b9-ebd7-48e4-9a43-3c6a231a4e1b">

这里其实是两个问题：
1. 如何在不使用SlotSetter的情况下一个组件设置多个插槽，因为使用SlotSetter右侧会多出相应的setter，不想要这些setter；
2. 在一个组件在不使用SlotSetter的情况下可以设置多个插槽的情况下，如何通过setter的输入，来动态设置插槽个数呢？

---

**Comment by hinhinlaw** [comment]
根据官方文档的 project 模型API实现了

**Comment by MistyZhao** [comment]
> 根据官方文档的 project 模型API实现了

请问是怎么实现的
我现在也有一个需求，是固定8种栅格布局，我试了两种方案都不行，
第一种：自定义行和列，行的snippets种设置布局，但是列组件经常挂载失败，找不到物料。而且也不符合需求，我们也不想让用户拖拽，就是想提供几种布局选项
第二种：定义类似grid的组件，meta中设置props指定列数，组件内通过循环渲染 Col, 但是在拖入其他组件的时候，我只想拖到某一列中，结果却是所有的列都会渲染
![image](https://github.com/user-attachments/assets/97e49df0-7edf-4db4-a271-4570ed1ab62c)
