### ISSUE TITLE
build.json 中怎么配置可以让__screenshots__中的图片不要打包成静态文件

### ISSUE THREAD

**Issue by wssgchungang** [alibaba/lowcode-engine#2235]
## **Describe the bug (required)** / **详细描述 bug（必填）**

用脚手架开发组件时，build.json 中怎么配置可以让__screenshots__中的图片不要打包成静态文件，想直接用base64的格式引入，现在打包完后图片会放在 build/lowcode/assets中，
![image](https://github.com/alibaba/lowcode-engine/assets/29122164/8afc75a2-b3e0-49fb-939b-6eaaccb6843f)

---

**Comment by eternalsky** [comment]
这个是 loader 里根据图片尺寸自动判断的，如果想修改规则需要写一个 build-scripts 插件来修改 webpack 配置。

**Comment by eternalsky** [comment]
插件教程：https://github.com/ice-lab/build-scripts/tree/stable/1.x
