### ISSUE TITLE
demo预览页面，换一下域名，可以直接拿去投放吗？可以针对性的对预览地址做定制吗？

### ISSUE THREAD

**Issue by catchingdream** [alibaba/lowcode-engine#224]
例如第一次进demo，指定预览地址后缀名称。下次进来还是该后缀。下次再指定预览地址后缀名称。再次进来还是该后缀。不同的入口，预览地址不一样。

**Comment by baieceo** [comment]
不同的地址需要存不同的schema，然后根据不同的schema生成不同的地址，这个需要自己开发，不要用demo自带插件的预览

**Comment by mark-ck** [comment]
可以关注低代码引擎项目实战的 b 站直播回放 https://www.bilibili.com/video/BV13F411s7Nh ，这是第一期，从 31分37秒会开始开发项目，前端部分就是基于 demo 修改的
