### ISSUE TITLE
ReactRenderer中的 appHelper的参数接收的值是不会更新的吗

### ISSUE THREAD

**Issue by wssgchungang** [alibaba/lowcode-engine#2240]
## **Describe the bug (required)** / **详细描述 bug（必填）**

ReactRenderer中的 appHelper的参数接收的值只是不会更新的吗，只接收第一次的值吗，比如appHelper.location 我用useLocation() 生成的，url中的query变化的时候，location的值会变化，但是ReactRenderer中的 appHelper.location 不会变化 还是第一次接收的值

---

**Comment by liujuping** [comment]
1.设计态使用 config.appHelper 进行更新，相关 PR https://github.com/alibaba/lowcode-engine/pull/2186

2.预览态正常 appHelper 更新了，重新触发渲染就可以变化。

**Comment by wssgchungang** [comment]
> 1.设计态使用 config.appHelper 进行更新，相关 PR #2186
> 
> 2.预览态正常 appHelper 更新了，重新触发渲染就可以变化。

必须要重新触发渲染吗，重新渲染的话，页面又回到初始状态了，没法满足我上面的需求；
例如低代码目前的组件没法满足，所以我在untils 传进一个组件
![image](https://github.com/alibaba/lowcode-engine/assets/29122164/8d8e1bfd-2c5a-4876-9546-07eaf1100073)
title的初始值是“测试”，setTitle改变后，对应title值并没有变化，一直是“测试”，如果必须要触发重新渲染才会变化，页面就会变到初始状态了，这显然是不行的，如果我这个页面是个表单页，已经填写了很多东西，给Preview加key属性，setTitle的时候改变key值，触发重新渲染，那么页面就会重置到初始状态，表单之前填写的内容也没了；
或者utils传的属性是通过后台获取的，所以刚开始都是undefined, 后续也不会变化，
