### ISSUE TITLE
自定义setter中切换下一级属性面板

### ISSUE THREAD

**Issue by zyp0930** [alibaba/lowcode-engine#2243]
我想问一下物料描述里面，"display": "entry"这个切换下一级属性面板的这个效果，有没有方法或者api可以在自定义setter内部自行进行控制跳转到下一级属性面板？

**Comment by liujuping** [comment]
需要具体描述一下，为什么需要在自定义 setter 内部控制该面板。

**Comment by zyp0930** [comment]
就是我们又个需求，需要给我们的元数据字段配置事件，这个元数据字段的setter是我们自定义的，想要能够实现进入下一级属性面板配置这个事件逻辑

**Comment by liujuping** [comment]
可以利用 createSettingFieldView 在自定义 setter 里面创建 entry 的属性配置。具体使用可以参考一下 lowcode-engine-ext 里面的使用方式。

如果完全是自定义的，比如 props.a 的 setter 想打开 props.b 的属性面板是不支持的。
