### ISSUE TITLE
variableSetter如何获取表格当前行的record

### ISSUE THREAD

**Issue by lynsun** [alibaba/lowcode-engine#2245]
我想给表格的某一列加自定义的className，根据当前列的值绑定不同的className，比如如下表格，当年龄这一列大于30的时候加className = 'red'
<img width="1121" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/992437/58dd111b-6607-4d65-8adb-0e1962378973">

使用variableSetter，写入如下表达式：this.record.age > 30 ? 'red' : 'blue'
<img width="1044" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/992437/6cdb60bc-497f-478d-89ac-3e196c8f5403">

没有生效，如果直接写死'red'是生效的

image
重现步骤：
1 使用官方demo的antd物料
2 拖入一个table，使用variableSetter设置age列的类名，表达式为this.record.age > 30 ? 'red' : 'blue'
3 this.record没有取到，类名没有生效
4 查看table组件这个属性的meta.ts，配置如下：
```
{
                  name: 'className',
                  title: {
                    label: '列样式类名',
                    tip: 'className | 列样式类名',
                  },
                  propType: 'string',
                  setter: ['StringSetter', 'VariableSetter'],
 },
```

Environments (please complete the following information) (required): / 请提供如下信息（必填）
AliLowCodeEngine version: ^1.1.7
AliLowCodeEngineExt version: ^1.0.5
Browser： chrome 114

**Comment by liujuping** [comment]
在使用插槽/自定义渲染的情况下，variableSetter 才能获取到相关组件的上下文（得组件支持）
