### ISSUE TITLE
修改node 节点属性后，右侧配置项中配置属性未同步更新，出码代码结构中已看到有更新，预览报错

### ISSUE THREAD

**Issue by wangwenbin0035** [alibaba/lowcode-engine#225]
## **Describe the bug (required)** / **详细描述 bug（必填）**
修改node 节点属性后，右侧配置项中配置属性未同步更新，出码代码结构中已看到有更新，预览报错
A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
---
使用场景：
在我们自己的元数据平台，建好元数据，在此低代码平台中引用，动态修改表格表头列

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
1. 打开demo 项目，拖入高级表格
2. 在 editor-init 中 修改表格节点 colums 属性值
3. 右侧配置项中列显示非修改后的属性，展开详情配置，发现是修改过后的属性配置
```
  project.currentDocument?.onChangeSelection((ids) => {
    const selected = ids[0];
    if(selected) {
      const node = project.currentDocument?.getNodeById(selected);
      console.log(node.getProp('columns'),'node.getProp()')
      console.log(node.getPropValue('columns'),'node.getPropValue()---1')
      node.setPropValue('columns',newColumns)
      console.log(node.getPropValue('columns'),'node.getPropValue()----2')
    }
  })
```
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/30583349/160733380-4bd09446-0cb0-4667-8c1e-849417e9b709.png">
使用步骤是否有问题，望老哥指正
---

English version example：
5. See error

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by LeoYuan** [comment]
试着不要在选中的时候去改~

选中那一刻右侧设置面板已经开始拿数据渲染了，此时修改时机可能已经晚了~
