### ISSUE TITLE
官方 setter 有办法将属性恢复为未设置的状态吗

### ISSUE THREAD

**Issue by liukairui** [alibaba/lowcode-engine#2250]
比如 StringSetter，当用户输入了值又清空后，会给这个属性赋空字符串而无法回到 undefined 状态，但对于我目前封装组件的方式来说，空字符串和 undefined 的处理方式是不同的。
目前我的方式是变量绑定 undefined，或者去 schema 中手动删除，计划写自定义 setter。
请问官方 setter 在未来有加个类似于清除按钮的计划吗？

**Comment by liujuping** [comment]
API 是支持的，比如：

https://lowcode-engine.cn/site/docs/api/model/setting-top-entry#clearpropvalue

官方 setter 目前没有支持的计划，有兴趣可以 PR，或者写自定义 setter。

**Comment by liukairui** [comment]
好的，感谢回复。
