### ISSUE TITLE
在LAB中使用HTML物料编写的HTML中定义的事件不生效

### ISSUE THREAD

**Issue by shiwofeiwo** [alibaba/lowcode-engine#2252]
如图
![image](https://github.com/alibaba/lowcode-engine/assets/105789907/db82932c-2a51-4235-af59-1040b6b922ad)

**Comment by woshilaoge** [comment]
https://lab.lowcode-engine.cn/help/docs/components/advanced/HTML

见组件使用文档，同时 【HTML 5 中指定不执行由 innerHTML 插入的 [<script>](https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/script) 标签】

这个 html 组件的内部实现如下：（借助 react dangerouslySetInnerHTML）
 ````html
 <div
      className={`vc-html ${className || ''}`}
      dangerouslySetInnerHTML={{ __html: this.props.content }}
/>
````
css 可以生效的， script 是不生效的，详细可见：（https://developer.mozilla.org/zh-CN/docs/Web/API/Element/innerHTML）

**Comment by linqiqi077** [comment]
https://lab.lowcode-engine.cn/help/docs/components/advanced/HTML
这个组件使用文档访问500了，对应的新版本文档的哪一个呢？求解答~~
@woshilaoge

**Comment by liujuping** [comment]
没有 500，

![image](https://github.com/alibaba/lowcode-engine/assets/11935995/52731f9e-9fb5-4d49-853a-cc088357d260)

你可以试一下用隐私窗口打开。

**Comment by woshilaoge** [comment]
可以试试隐私模式，可能是之前的 cdn 缓存。（前段时间 cdn 有了些问题）

**Comment by linqiqi077** [comment]
> 没有 500，
> 
> ![image](https://user-images.githubusercontent.com/11935995/284764955-52731f9e-9fb5-4d49-853a-cc088357d260.png)
> 
> 你可以试一下用隐私窗口打开。

可以打开啦，谢谢

**Comment by linqiqi077** [comment]
> 可以试试隐私模式，可能是之前的 cdn 缓存。（前段时间 cdn 有了些问题）

可以打开啦，谢谢
