### ISSUE TITLE
出码模块官方demo有BUG

### ISSUE THREAD

**Issue by woshikay** [alibaba/lowcode-engine#2265]
## **Describe the bug (required)** / **详细描述 bug（必填）**
使用官方提供的出码模块，构建之后，执行npm run demo命令生成出来的项目无法运行，目前已经确认npm install成功，但是执行npm start后白屏，且调试台报错。更换example-schema.json后生成出来的项目可正常运行。

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
1、使用官方出码模块的npm run demo生成项目
2、进入刚刚生成的项目目录
3、打开命令行，输入npm install
4、等待安装完成后执行npm start

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

应该展示生成出来的页面内容
---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

![image](https://github.com/alibaba/lowcode-engine/assets/9391885/71ebba8c-e969-4a95-8978-3cd126a7aa51)

![image](https://github.com/alibaba/lowcode-engine/assets/9391885/c25aa811-a497-480c-97bb-3e7bbd4aa171)

**Comment by LeoYuan** [comment]
看看是不是 sass 版本问题，这个跟出码关系不大了

**Comment by qingniaotonghua** [comment]
同  https://github.com/alibaba/lowcode-engine/issues/2520
