### ISSUE TITLE
主页面以文件系统的方式展示

### ISSUE THREAD

**Issue by q1979635364** [alibaba/lowcode-engine#2273]
一切正常安装，如下所示：
![image](https://github.com/alibaba/lowcode-engine/assets/25050128/3166a4c0-b43e-4465-9de8-b093d935f855)
但页面进不去，显示的是一个文件系统
![image](https://github.com/alibaba/lowcode-engine/assets/25050128/91a0b9d3-79c4-4599-a64a-11da7f244a3e)

部署环境：
引擎版本是：git@github.com:alibaba/lowcode-engine.git   commit hash：5cc4715daf510a64b6bf10c51b3a12df2bc62a36
操作系统版本：Linux huzz 5.19.0-46-generic #47~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Wed Jun 21 15:35:31 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by JackLian** [comment]
https://lowcode-engine.cn/site/docs/guide/create/useEditor#%E6%96%B9%E6%B3%95-2-%E4%BD%BF%E7%94%A8-umd-%E5%8C%85%E6%96%B9%E5%BC%8F%E9%85%8D%E7%BD%AE
