### ISSUE TITLE
代码下载到本地后，部署后，日常/开发切换环境的悬浮按钮一直存在

### ISSUE THREAD

**Issue by 342164796** [alibaba/lowcode-engine#2277]
## **Describe the bug (required)** / **详细描述 bug（必填）**
代码下载到本地后，部署后，日常/开发切换环境的悬浮按钮一直存在
应用地址：https://lab.lowcode-engine.cn/demo/admin?appKey=test_center&version=0.1.0#/appPublishNew
A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
1.代码下载到本地
2.启动web服务，查看首页有没有悬浮按钮 
---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by woshilaoge** [comment]
@342164796  已 fixed ，感谢反馈

如截图：本地运行效果
![image](https://github.com/alibaba/lowcode-engine/assets/22810511/70b127a4-8b2f-406c-b8b8-5a17595f78db)


PS:已经帮你发布了一个 1.8.0 的版本，可以直接下载使用
![image](https://github.com/alibaba/lowcode-engine/assets/22810511/8ea43b3c-608f-4203-9995-a1dff860ee97)
