### ISSUE TITLE
请教自定义组件这两行代码的作用

### ISSUE THREAD

**Issue by little-yaonv** [alibaba/lowcode-engine#2279]
请问执行npm init @alilc/element your-material-name命令对组件项目进行初始化后，src/index.tsx中的这两行代码是什么作用呢：
const bizCssPrefix = 'bizpack';

export {
  bizCssPrefix
}

![image](https://github.com/alibaba/lowcode-engine/assets/75791730/d802c8cb-bab5-4c87-bd84-1d9870b9a9e4)

**Comment by eternalsky** [comment]
@jinchanz 大佬知道这个的用处吗？

**Comment by jinchanz** [comment]
就是初始化一个 css 前缀，没用的话可以删掉它
这是我们自己写一个组件库的时候会加上，防止样式冲突
