### ISSUE TITLE
virtual 在1.1.9-beta.1引擎版本中无效

### ISSUE THREAD

**Issue by ming001** [alibaba/lowcode-engine#2281]
{ 
    name: 'driverSetter',
    title: 'test',
    virtual: () => true,
    display: 'plain',
    setter: ...
}
在setter设置了virtual属性，在procode的props中还是能看到这个参数传递过去了
![image](https://github.com/alibaba/lowcode-engine/assets/24415457/d4530388-1944-48dd-b728-4a80cc109f7e)

**Comment by eightHundreds** [comment]
https://github.com/alibaba/lowcode-engine/issues/1971

**Comment by liujuping** [comment]
没有 virtual 配置能力，相关文档和定义已提 PR 进行删除，如果需要类似的能力，name可以配置成以 ! 开头，例如：name: '！driverSetter'
