### ISSUE TITLE
[Question] node.importSchema与node.replaceWith的区别?

### ISSUE THREAD

**Issue by eightHundreds** [alibaba/lowcode-engine#2282]
如题
<img width="719" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/18695431/e36584b2-a643-4021-bede-80d1ca06821e">

<img width="658" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/18695431/4520acf2-bfef-4eb4-911e-82f7f411769f">

**Comment by eightHundreds** [comment]
实际使用效果是:
- 两者都能影响到画布
- 只有replaceWith能影响到project.exportSchema结果

**Comment by liujuping** [comment]
1.importSchema 主要是修改 node 的 props、children，但是该 node 类型没有变化。

2.replaceWith 相当于完全产生一个新的 node，替代当前 node，node 的类型也就变化。

比如 Table 组件使用 importSchema({ componentName: 'Button', props: { y: 1 } })，组件类型不变，只修改了 node 的 props
