### ISSUE TITLE
自定义物料上传服务器后使用报错

### ISSUE THREAD

**Issue by dodo2016** [alibaba/lowcode-engine#2283]
自定义物料，通过build 和lowcode:bulid打包后，在项目里面使用，右侧设计器界面不显示，控制台报错。
请问是什么原因，官方代码里面的示例colorful-input 也一样

![6151689326893_ pic](https://github.com/alibaba/lowcode-engine/assets/17449473/73ce0065-ae9e-4a07-be1c-99945b366cda)

![6141689326892_ pic](https://github.com/alibaba/lowcode-engine/assets/17449473/b04f61a4-6786-4814-b043-950c076f7741)

**Comment by eternalsky** [comment]
@liujuping 看起来像是 mixedSetter 报错
