### ISSUE TITLE
提问：如何快速搭建出与 https://lab.lowcode-engine.cn/demo/design 一样的低代码平台

### ISSUE THREAD

**Issue by q1979635364** [alibaba/lowcode-engine#2285]
有没有大佬有整合出来的包可以直接拉出跟 https://lab.lowcode-engine.cn/demo/design 一模一样的运行环境？

**Comment by q1979635364** [comment]
忘记是哪位大佬在哪里回复过我了，这个里面涉及到的技术组件太多了，不方便开源。

**Comment by shmilyCai** [comment]
请问下，有这样的案例嘛？或者有没有什么方式可以多个schema页面出码？
