### ISSUE TITLE
建议更新文档：this.util.showDialog方法不存在

### ISSUE THREAD

**Issue by q1979635364** [alibaba/lowcode-engine#2288]
环境：https://lab.lowcode-engine.cn/demo/design
![image](https://github.com/alibaba/lowcode-engine/assets/25050128/76abfb3b-b809-4fb4-9e74-db4fffe58255)

根据文档：https://lab.lowcode-engine.cn/help/docs/components/advanced/table
![image](https://github.com/alibaba/lowcode-engine/assets/25050128/85151382-5dbf-4cea-aae8-a930befcd44b)

实际上没有`this.util`，应该是`this.utils`，但即使是`this.utils`，也没有`showDialog`方法，如下所示：
![image](https://github.com/alibaba/lowcode-engine/assets/25050128/eb786c20-45c7-4925-a60b-96dcbd0dc631)
但能看到有一个`dialog`方法。
使用`this.utils.dialog`方法展示成功，如下所示：
![image](https://github.com/alibaba/lowcode-engine/assets/25050128/76eb43e0-8da9-42fc-8068-6f817c2fd215)
但这个方法似乎不是传递一个dialog的id，不知道怎么使用。
大佬看能不能更新一下使用文档，感谢~

**Comment by q1979635364** [comment]
找到了，原来showDialog是自定义的一个方法。如果文档上能够做一下说明就非常好了~
![image](https://github.com/alibaba/lowcode-engine/assets/25050128/4ab20c44-25ee-4089-a3c8-f95be2dea018)

**Comment by woshilaoge** [comment]
@q1979635364 

文档已 fix，感谢反馈。

js 面板中，可以操作 dialog 有多种方式，但操作的目标组件不同。

1. this.utils.dialog({ title: 'xxx' }) 这种是使用 utils 上挂在的 全局 工具函数

2. this.$('dialog_id').show()|hide() 这种是操作当前页面具体拖来配置的 dialog 组件

![image](https://github.com/alibaba/lowcode-engine/assets/22810511/0c65d204-ba81-41b6-9c87-84b899e5256b)
