### ISSUE TITLE
出码生成的icejs3项目运行时报错(ReferenceError: React is not defined)

### ISSUE THREAD

**Issue by lilithyang2018** [alibaba/lowcode-engine#2296]
## **Describe the bug (required)** / **详细描述 bug（必填）**

出码生成的icejs3项目运行时报错(ReferenceError: React is not defined)

Steps to reproduce the behavior: / 详细复现步骤：
1.下载这个[https://alifd.alicdn.com/npm/@alilc/lowcode-code-generator@latest/example-schema.json](example-schema.json)文件
2. npx @alilc/lowcode-code-generator -i example-schema.json -o generated -s icejs3
2. cd generated
3. yarn
4. yarn start

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为
项目正常运行不报错
---

**如果使用icejs solution，则生成的项目可以正常运行**

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
![error](https://github.com/alibaba/lowcode-engine/assets/39897706/5580db38-8a29-451c-bf7f-77297929a559)
---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - Browser [e.g. chrome, safari] / 浏览器版本 chrome Version 114.0.5735.199
![version](https://github.com/alibaba/lowcode-engine/assets/39897706/8081f145-8660-43fb-ae9c-06fb6da95448)

**Comment by LeoYuan** [comment]
试试锁定下面两个包的版本~

```
"@ice/app": "~3.1.0",

"@ice/runtime": "~1.1.0",
```

@lilithyang2018

**Comment by lilithyang2018** [comment]
锁定之后能正常启动 但是发现使用的next版本是1.26.15，依赖会404
![cdn](https://github.com/alibaba/lowcode-engine/assets/39897706/07110c81-3b0c-4d31-8a56-a1b030d1d1c0)
需要在document.tsx中修改next的版本为1.19.18

**Comment by LeoYuan** [comment]
嗯嗯~

应该是 CDN 同步的问题，1.26.6是有的，后面就 404 了 @jinchanz
