### ISSUE TITLE
ILowCodePluginContext 类型找不到

### ISSUE THREAD

**Issue by kyoonart** [alibaba/lowcode-engine#2297]
## **Describe the bug (required)** / **详细描述 bug（必填）**

![image](https://github.com/alibaba/lowcode-engine/assets/49586985/c6a7175c-487b-4d79-8ee9-d5fb8fa05079)

@alilc/lowcode-engine 版本 1.1.2

**Comment by JackLian** [comment]
改成这样
import { IPublicModelPluginContext } from '@alilc/lowcode-types';
