### ISSUE TITLE
用npm init @alilc/element demo cli命令初始化组件后,npm install报错

### ISSUE THREAD

**Issue by tanyo520** [alibaba/lowcode-engine#23]
ed. Upgrade to v2.x.x.
Error: Couldn't find package "@ali/lowcode-utils@^1.0.60" required by "@alifd/build-plugin-lowcode@0.1.16-beta.0" on the "npm" registry.

**Comment by eternalsky** [comment]
@alifd/build-plugin-lowcode@0.1.16-beta.1 可以试下

**Comment by mark-ck** [comment]
fixed
