### ISSUE TITLE
咨询： LAB 将不定期根据情况对数据进行删档，请问有没有什么办法确保我可以以邮件或者其他的方式收到通知

### ISSUE THREAD

**Issue by q1979635364** [alibaba/lowcode-engine#2301]
如题，从 [Lab官网文档]( https://lab.lowcode-engine.cn/help/docs/guide/start#%E4%B8%80%E6%9C%8D%E5%8A%A1%E7%A8%B3%E5%AE%9A--%E6%95%B0%E6%8D%AE) 来看，数据可能会被删除。
我这边有几个项目是公司内部使用的一款应用，我需要确保我的数据不会丢失（因为线上环境实在是比我自己搭建的好用多了）。
我从哪里可以收到删档通知呀。
![image](https://github.com/alibaba/lowcode-engine/assets/25050128/541a1310-d031-4ced-b97a-5837e569357b)

**Comment by woshilaoge** [comment]
https://lowcode-engine.cn/index

@q1979635364 感谢对 LAB 的使用支持，从目前数据来看，预设存储使用率大概是 10%，预计近一年不会有数据清理。另外，目前 LAB 暂未提供专属的消息群和账号邮箱，目前整个服务支持体系是复用 低代码引擎社区的。您可以关注或加入社区大群：
![image](https://github.com/alibaba/lowcode-engine/assets/22810511/d6e8b1e2-96f0-440f-a0f9-483d35240986)
（引擎官网尾页），LAB 的文档，晚些也更新下，如果大家需要关注消息推送的话，可以关注这个社区群。
