### ISSUE TITLE
如何让整个自定义组件库都显示在同一组中

### ISSUE THREAD

**Issue by little-yaonv** [alibaba/lowcode-engine#2308]
您好，请问让整个自定义组件库显示在同一组中除了逐个修改每个组件的meta.ts，在其中加上group属性外，在项目的哪个位置能统一的修改一下呢？
例如下图，让整个组件库的组件都显示在精选组件中
![c289f85c7f408bbd789c32366a283c5](https://github.com/alibaba/lowcode-engine/assets/75791730/0d629cca-4706-4b95-a3f8-e93218b443c7)

**Comment by eternalsky** [comment]
只能修改 meta.ts，嫌麻烦的话，可以写些批量脚本去处理一下。
