### ISSUE TITLE
请教高级表单form组件自定义表单项,变量输入时候具体对应的数据格式?

### ISSUE THREAD

**Issue by Nullpointexception6** [alibaba/lowcode-engine#2309]
## **Describe the bug (required)** / **详细描述 bug（必填）**
高级表单form组件自定义表单项,变量输入时候具体对应的数据格式?

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
拖拽组件无法满足业务需求,需求通过接口数据自定义form组件自定义表单项,但是不知道form自定义表单项的数据格式

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
1.拖入form组件
2.切换表单项设置器为变量输入,输入js定义的指定变量,但是数据格式不清楚,无法自定义表单项
![微信图片_20230721113559](https://github.com/alibaba/lowcode-engine/assets/41475725/357b31fe-384c-42cf-99ad-a064b711dfd4)

**Comment by eternalsky** [comment]
格式可以在 schema 面板里对应的属性位置查看，和 schema 内的保持一致即可。

**Comment by owenchen1004** [comment]
请问高级表单是哪里的物料呀？有地址吗？
