### ISSUE TITLE
[Question] 如何获取@alilc/lowcode-editor-core

### ISSUE THREAD

**Issue by eightHundreds** [alibaba/lowcode-engine#2311]
# 背景
我想自己实现一个 designer。根本诉求是把官方的simulator换掉，因为可能与画布的交互方式都可能要换掉，所以是替换designer（而不是替换simulator）。

# 问题

- 实现designer需要用到`@alilc/lowcode-editor-core`的一些api和单例,但是这个包被打包到 `@alilc/lowcode-engine`, 并且没有暴露接口，比如IEditor实例。
- 另外`@alilc/lowcode-engine` 跟官方的`@alilc/lowcode-designer`还是有一定耦合的

# 建议

- 使用`@typescript-eslint/consistent-type-imports`规则, 将类型导入与值导入完全分开。利用`@typescript-eslint/no-restricted-imports`禁止从`@alilc/lowcode-designer`导入非类型成员, 避免在开发其他包依赖了`@alilc/lowcode-designer`的值
- 重构`IDesigner`（或者提供更抽象的IDesigner），目前的接口与目前的搭建场景太耦合了， 比如官方的x6场景就没有实现`IDesigner`, 说明官方目前的`IDesigner`不适合用于扩展。

# @alilc/lowcode-designer与engine-core的强耦合

<details><summary>Details</summary>
<p>

**1**  

<img width="616" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/18695431/6891ea7e-e722-4e4f-b1b0-c5b79aec230e">

应该去掉这里的设置, 因为在插件里已经设置过了。  

<img width="678" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/18695431/e79ae0d3-751c-41da-819b-1ccff08ff106">

**2**

<img width="876" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/18695431/755c7de0-6100-47ec-8f3c-c27d02d9965f">

**3**

<img width="857" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/18695431/ec380300-8c7e-4678-85bb-c89390eb0069">

**4**

`@alilc/lowcode-shell`里面有一堆耦合, 看起来是故意的不是不小心

</p>
</details>

**Comment by eightHundreds** [comment]
**另一个方向**

感觉我可以先尝试自己实现一个simulator, 实在不行再实现一个designer。


**simulator替换方案**

已知 [lowcode-engine-vue](https://github.com/KNXCloud/lowcode-engine-vue) 通过`simulatorUrl`去替换simulator。

但这个方案我不喜欢，我是希望iframe创建也被我控制，所以我打算用`designer.setProps({ simulatorComponent })`去替换（拷贝官方BuiltinSimulator改造）。

但designer并没有暴露出来，无法实现。

**Comment by liujuping** [comment]
目前 @alilc/lowcode-designer 在之前的设计中没有考虑扩展。目前主要扩展方式有两种：

1.使用api，替换 mainArea 区域，相关能力均使用对外 API 来实现，如果有不支持的 API，比如提到的 IEditor 实例，需要先对 API 进行支持，放到 Shell 层。和 x6 场景类似。

2.扩展 simulator
