### ISSUE TITLE
workspace模式下加载不出setter

### ISSUE THREAD

**Issue by proclml** [alibaba/lowcode-engine#2314]
如图，setters都加载不出来，非workspace模式是可以的。请问是我注册的方式不对吗，我在editorView的init方法和resourceType的init方法里面都试过，都显示不出来，且都会提示下面这个错误

AliLowCodeEngine  v1.1.8 
AliLowCodeExt  v1.0.6-beta.25 

![image](https://github.com/alibaba/lowcode-engine/assets/38473196/eb4b1b43-5dd3-499d-9e45-aa0b98442259)
![image](https://github.com/alibaba/lowcode-engine/assets/38473196/e8eda894-4cee-4fff-8cd4-719c32a6a7eb)

**Comment by proclml** [comment]
https://github.com/alibaba/lowcode-engine-ext/blob/6ddcfbff56ce5047e104334f05205128dbe3e6f9/src/setter/mixed-setter/index.tsx#L22

看到这里的setters用的是全局的，这个有问题吗

**Comment by liujuping** [comment]
有可以复现的 demo 吗？

**Comment by proclml** [comment]
之前出错是因为defaultViewType设置的是`editor`，同上面pageView变量的`viewType`，改成`editor1`也就是同pageView.viewName之后就没有这个bug了，是我理解错`defaultViewType`这个域的含义了吗？如果表示的是editorView的viewName，是不是defaultViewType改成defaultViewName好一点 @liujuping 
![image](https://github.com/alibaba/lowcode-engine/assets/38473196/6fc5f48a-d347-45e0-b3cc-b0474ebfa7eb)

**Comment by liujuping** [comment]
defaultViewType 的确改成 defaultViewName 比较好，已经改了，这个问题先关闭了。
