### ISSUE TITLE
组件可以动态生成吗

### ISSUE THREAD

**Issue by 2535744721** [alibaba/lowcode-engine#2319]
自定义组件可以动态生成吗

**Comment by JackLian** [comment]
详细描述下，看不太懂

**Comment by 2535744721** [comment]
物料 里自己写组件，想动态生成snippets里的信息，可以吗
const snippets: IPublicTypeSnippet[] = [
  {
    "title": "Box",
    "screenshot": "/public/screenshots/box.png",
    "schema": {
      "componentName": "Box",
      "props": {
        defaultTransform: [0, 0.5, 0]
      }
    }
  }
];

**Comment by JackLian** [comment]
要怎么个动态，什么环节动态，描述清楚一点吧...

**Comment by 2535744721** [comment]
新开发一个属于自己的组件，然后的场景是3d场景，一个模型对应一个组件，但我要做的是把导入的模型信息自动生成在snippets里面。 下面是我的box 模型信息，写在meta.ts里面的
import { IPublicTypeComponentMetadata, IPublicTypeSnippet } from '@alilc/lowcode-types';
const BoxMeta: IPublicTypeComponentMetadata = {
  group: "模型",
  category: "基础几何",
  "componentName": "Box",
  "title": "Box",
  "docUrl": "",
  "screenshot": "/public/screenshots/box.png",
  "devMode": "proCode",
  "npm": {
    "package": "@zhoufantest/ioc-material",
    "version": "0.1.0",
    "exportName": "Box",
    "main": "src\\index.tsx",
    "destructuring": true,
    "subName": ""
  },
  "configure": {
    "props": [
      {
        name: 'object',
        title: '对象',
        type: 'group',
        display: 'block',
        items: [
          {
            name: 'castShadow',
            title: '透射阴影',
            setter: 'BoolSetter',
          },
          {
            name: 'receiveShadow',
            title: '接受阴影',
            setter: 'BoolSetter',
          },
          {
            name: 'position',
            title: '坐标',
            setter: {
              componentName: 'ObjectSetter',
              props: {
                config: {
                  items: [
                    {
                      name: '0',
                      title: 'X',
                      setter: 'NumberSetter'
                    },
                    {
                      name: '1',
                      title: 'Y',
                      setter: 'NumberSetter'
                    },
                    {
                      name: '2',
                      title: 'Z',
                      setter: 'NumberSetter'
                    }
                  ]
                }
              }
            }
          },
        ]
      },
      {
        name: 'material',
        title: '材质',
        type: 'group',
        display: 'block',
        items: [
          {
            "title": {
              "label": {
                "type": "i18n",
                "en-US": "color",
                "zh-CN": "颜色"
              }
            },
            "name": "material.color",
            "setter": 'ColorSetter'
          },{
            "title": {
              "label": {
                "type": "i18n",
                "en-US": "roughness",
                "zh-CN": "粗糙度"
              }
            },
            "name": "material.roughness",
            "setter": {
              componentName: 'NumberSetter',
              props: {
                min: 0,
                max: 1,
                step: 0.01
              }
            }
          },{
            "title": {
              "label": {
                "type": "i18n",
                "en-US": "color",
                "zh-CN": "金属度"
              }
            },
            "name": "material.metalness",
            "setter": {
              componentName: 'NumberSetter',
              props: {
                min: 0,
                max: 1,
                step: 0.01
              }
            }
          },{
            "title": {
              "label": {
                "type": "i18n",
                "en-US": "emissive",
                "zh-CN": "自发光"
              }
            },
            "name": "material.emissive",
            "setter": "ColorSetter"
          },{
            "title": {
              "label": {
                "type": "i18n",
                "en-US": "emissiveIntensity",
                "zh-CN": "自发光强度"
              }
            },
            "name": "material.emissiveIntensity",
            setter: {
              componentName: 'NumberSetter',
              props: {
                step: 0.01
              }
            },
          },
        ]
      }

    ],
    "supports": {
      "style": false,
        // 支持循环设置
        "loop": false,
        // 支持条件设置
        "condition": false,
    },
    "component": {}
  }
};
const snippets: IPublicTypeSnippet[] = [
  {
    "title": "Box",
    "screenshot": "/public/screenshots/box.png",
    "schema": {
      "componentName": "Box",
      "props": {
        defaultTransform: [0, 0.5, 0]
      }
    }
  }
];

export default {
  ...BoxMeta,
  snippets
};
上面信息是已经在物料里写好的组件，然后我有一个sphere模型，然后我想把模型信息生成到snippets中，如下：
const snippets: IPublicTypeSnippet[] = [
  {
    "title": "Box",
    "screenshot": "/public/screenshots/box.png",
    "schema": {
      "componentName": "Box",
      "props": {
        defaultTransform: [0, 0.5, 0]
      }
    }
  }，
  {
    "title": "sphere",
    "screenshot": "/public/screenshots/sphere.png",
    "schema": {
      "componentName": "Sphere",
      "props": {
        defaultTransform: [0, 0.5, 0]
      }
    }
  }
];
但加入的snippets中我不想手动写进去，想问snippets里面的信息可以动态生成吗

**Comment by JackLian** [comment]
是你开发meta时候不想手写还是说开发时候还没法写，如果是不想手写，那你自己做个工具去生成就好了，如果是必须要在设计器内才知道以什么规则动态生成，那就写个插件处理，参考 https://lowcode-engine.cn/site/docs/api/material#registermetadatatransducer
