### ISSUE TITLE
表单Field对象 怎么用？

### ISSUE THREAD

**Issue by zhugenqiang** [alibaba/lowcode-engine#232]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
field: '表单Field对象' 这个绑定的时候在哪？在didmount 时候this 还没有这个对象吗？什么时候可以用

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
在js 中增加代码显示为undefind

**Comment by mark-ck** [comment]
看看这期直播回放，9分40秒 的位置有介绍 Field 的用法： https://www.bilibili.com/video/BV13F411s7Nh

**Comment by markdashi** [comment]
Field 使用后，出码的地方如何动态引入
