### ISSUE TITLE
自定义组件的时候isContainer属性不生效

### ISSUE THREAD

**Issue by little-yaonv** [alibaba/lowcode-engine#2328]
请问在自定义组件的时候，为什么有些组件的meta.ts文件中设置了isContainer:true，但是并不生效，就是使用组件的时候并不会出现插槽容器
![image](https://github.com/alibaba/lowcode-engine/assets/75791730/5d0c6b44-c7ca-4753-971d-0afdc7917578)

**Comment by eternalsky** [comment]
isContainer 的时候，引擎会自动把 children 作为插槽，需要你的组件能够接收 children 才可以。
