### ISSUE TITLE
在官方提供的物料脚手架中引入formily/antd-v5报错，且会导致所有组件都无法找到无法渲染

### ISSUE THREAD

**Issue by himushroom** [alibaba/lowcode-engine#2330]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
使用官网提供的脚手架方法，新建组件库:
```
npm init @alilc/element your-material-name
```
然后在组件库中引入formily/antd-v5官方要求的包:
```
npm install --save antd dayjs
npm install --save @formily/core @formily/react @formily/antd-v5
```
将其中`colorful-input`组件改造为formily-antd-v5组件，使用formily官网的input demo，完整改造代码在下方详细复现步骤中

启动项目后报错：

![image](https://github.com/alibaba/lowcode-engine/assets/19682322/653b4f54-fc80-471d-a7e9-9c26cd41a1bf)

且会导致组件无法渲染，包括本来能正常渲染的`colorful-button`组件：

![image](https://github.com/alibaba/lowcode-engine/assets/19682322/238e0a8e-8c46-49b6-9507-667ff94bfef2)

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

其中`colorful-input`组件改造为formily-antd-v5组件，使用formily官网的input demo进行了改造：
```
import * as React from 'react';
import { createElement } from 'react';
import { Input } from '@alifd/next';
import { bizCssPrefix } from '../../variables';
import './index.scss';
import { FormButtonGroup, FormItem, Input, Submit } from '@formily/antd-v5';
import { createForm } from '@formily/core';
import { createSchemaField, FormProvider, ISchema } from '@formily/react';

export interface ColorfulInputProps {
  color?: string;
  style?: object;
}

const SchemaField = createSchemaField({
  components: {
    Input,
    FormItem,
  },
});

const form = createForm();

const schema: ISchema = {
  type: 'object',
  properties: {
    input: {
      type: 'string',
      title: '输入框',
      'x-decorator': 'FormItem',
      'x-component': 'Input',
      required: true,
      'x-component-props': {
        style: {
          width: 240,
        },
      },
    },
    textarea: {
      type: 'string',
      title: '文本框',
      required: true,
      'x-decorator': 'FormItem',
      'x-component': 'Input.TextArea',
      'x-component-props': {
        style: {
          width: 400,
        },
      },
    },
  },
};

const ColorfulInput: React.FC<ColorfulInputProps> = function ColorfulInput({
  color,
  style = {},
  ...otherProps
}) {
  const _style = style || {};
  if (color) {
    _style.backgroundColor = color;
  }
  const _otherProps = otherProps || {};
  _otherProps.style = _style;
  return (
    // <Input { ..._otherProps } />
    <FormProvider form={form}>
      <SchemaField schema={schema} />
    </FormProvider>
  );
};

export default ColorfulInput;

```
---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

组件库能支持formily/antd-v5组件，已在github传入相应代码：`https://github.com/himushroom/lowcode-component`

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**

低代码引擎版本/低代码引擎扩展包版本均使用的脚手架提供的版本，除上述操作外，未做其他改动
 - AliLowCodeEngine version:  / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari]：chrome版本 114.0.5735.248（正式版本） （64 位） / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

请问用命令搭建的组件库是不支持antd5吗？非常期待收到您们的答复~

**Comment by eternalsky** [comment]
另外请注意，antd 默认是被 external 出去的，并且脚手架中使用的是 antd4，如果要使用 antd5 ，请替换对应的 cdn 地址。

**Comment by eternalsky** [comment]
替换方式可以通过 插件的 builtInAssets 属性来配置。https://www.npmjs.com/package/@alifd/build-plugin-lowcode

**Comment by himushroom** [comment]
> 替换方式可以通过 插件的 builtInAssets 属性来配置。https://www.npmjs.com/package/@alifd/build-plugin-lowcode

builtinAssets添加了antdv5版本的包，参考的是lowcode-ecology/formily-materials这个项目的物料配置：
```
        builtinAssets: [
          {
            packages: [
              {
                package: 'moment',
                version: '2.24.0',
                urls: ['https://g.alicdn.com/mylib/moment/2.24.0/min/moment.min.js'],
                library: 'moment',
              },
              {
                package: 'lodash',
                library: '_',
                urls: ['https://g.alicdn.com/platform/c/lodash/4.6.1/lodash.min.js'],
              },
              {
                package: 'iconfont-icons',
                urls: '//at.alicdn.com/t/font_2369445_ukrtsovd92r.js',
              },
              {
                package: 'dayjs',
                version: '1.11.9',
                urls: [`https://xxx/assets/dayjs.min.js`],
                library: 'dayjs',
              },
              {
                package: '@ant-design/icons',
                version: '5.0.1',
                urls: [`https://xxx/assets/icons/index.umd.min.js`],
                library: 'icons',
              },
              {
                package: 'antd',
                version: '5.7.3',
                urls: [
                  `https://xxx/assets/antd.min.js`,
                  `https://xxx/assets/reset.css`,
                ],
                library: 'antd',
              },
            ],
          }
        ]
```

因为formily-materials这个库用的是formily/antd是可以正常使用的，换成formily/antd-v5之后就不行了，所以我才怀疑是antd5的问题……但是官网并没有提到antd5和antd4在环境支持上有什么差异，最后只能来问下脚手架了……

demo加上builtinAssets后换了一个报错：
![image](https://github.com/alibaba/lowcode-engine/assets/19682322/0957a2a3-86c3-4955-900f-6195137051dc)
![image](https://github.com/alibaba/lowcode-engine/assets/19682322/952e5f3a-9da0-4116-ac22-51734b98ddd8)


如果我在builtinAssets中再加入@formily/antd-v5的外部引入链接，还会提示`antd is not defined`，但是我的antd5的外部引入链接确实是正常可访问的，不知道是不是打包的问题

这个我实在找不到头绪，只能求助了……

**Comment by eternalsky** [comment]
升级一下最新版的 build-plugin-lowcode 看看
