### ISSUE TITLE
请问如何将BizCharts的图表库引入到低代码的assets里面

### ISSUE THREAD

**Issue by tcj98** [alibaba/lowcode-engine#2335]
请问如何将BizCharts的图表库引入到低代码的assets里面,我看demo-basic-fusion里面的assets是components和componentList，但是其他场景下的都是只有components，请问这里如何兼容？或者有没有类似于其他场景下的格式，只需要导入对应的packages和components就可以引用的方式。
![image](https://github.com/alibaba/lowcode-engine/assets/109788621/ba4581bd-ab13-4729-87a4-5539786286b4)
![image](https://github.com/alibaba/lowcode-engine/assets/109788621/a10d5b31-18d9-409d-8d4c-efc7ef666c47)

**Comment by eternalsky** [comment]
根据文档来即可：https://lowcode-engine.cn/site/docs/guide/expand/editor/material
