### ISSUE TITLE
如何添加社区钉钉群

### ISSUE THREAD

**Issue by ruanlinxin** [alibaba/lowcode-engine#2337]
官网底部提供的社区二维码已经失效，需要在哪里才能进入社区钉钉群
![image](https://github.com/alibaba/lowcode-engine/assets/53412119/4d259c8e-951c-480c-9530-eb50507ae84b)
------------------------------------------------------------------------------------------
![29781690943215_ pic](https://github.com/alibaba/lowcode-engine/assets/53412119/fee6e915-d12e-47b4-b69a-eb05a59e1c9f)

**Comment by liujuping** [comment]
二维码已经更新

**Comment by ruanlinxin** [comment]
> 二维码已经更新

https://lowcode-engine.cn/index是这个页面底部的么，我目前扫还是过期

**Comment by liujuping** [comment]
![IMG_6336](https://github.com/alibaba/lowcode-engine/assets/11935995/67124175-376f-4d34-8055-80573cf5d574)

这个试一下呢？
