### ISSUE TITLE
请问用注入的方式调试插件的时候，如果需要向插件传递参数，需要怎么弄呢

### ISSUE THREAD

**Issue by Choi-Keith** [alibaba/lowcode-engine#2339]
开发一个插件，但是该插件需要传递参数，想通过注入的方式调试，发现不知道怎么配置。
目前能想到的是通过npm link的方式去调试，但是没有通过注入的方式方便，希望增加一个能通过注入的方式调试需要传递参数的插件功能

**Comment by LeoYuan** [comment]
这是个蛮有价值的点，大佬看看~

@eternalsky

**Comment by eternalsky** [comment]
通过给插件设置默认值就可以调试了。
