### ISSUE TITLE
大纲树目前只会列出根节点下的模态框，能不能列出显示出所有层级下的？

### ISSUE THREAD

**Issue by xwinstone** [alibaba/lowcode-engine#2340]
### 问题：

目前页面中有两个Modal，一个在根节点的children里，一个是区块生成的一段scheme中包含的Modal。

![image](https://github.com/alibaba/lowcode-engine/assets/15334559/f697c8d7-9c82-4e63-8e4a-5b3bd6377547)

但大纲树只能显示出来根节点的Modal，展开里面也看不到另外一个。

![image](https://github.com/alibaba/lowcode-engine/assets/15334559/1d6a86d9-2781-4e4e-b94e-f76804626c3b)

### 期望：

在大纲树显示出所有Modal节点。

**Comment by liujuping** [comment]
Modal 正常拖拽进去都会把它插入到根节点上面的，这里的 Modal 如何配置到区块里面的？

**Comment by xwinstone** [comment]
> Modal 正常拖拽进去都会把它插入到根节点上面的，这里的 Modal 如何配置到区块里面的？

不是在界面拖进去的，是通过代码生成的一段schema，然后node.replaceWith进来的

**Comment by liujuping** [comment]
那这里为什么要设计把模态弹窗要放到区块下面？

**Comment by xwinstone** [comment]
方便管理，因为区块就是一系列物料的组合，如果区块内部的弹窗都要放到跟节点，实现上就很变扭。

**Comment by liujuping** [comment]
区块如果放到页面里面了，应该就是页面中的物料了。这时候大纲树如果列出来所有层级下的，要么平铺，要么树状结构，树状结构如果太复杂，也不适合后续操作模态窗的显示和隐藏。如果平铺，那只有 schema 结构是在区块下，对于用户来说，这个弹窗也看不出来是在根节点还是在区块节点。

如果放到下面的树状结构中，同样不利于后续操作模态窗的显示和隐藏。

**Comment by xwinstone** [comment]
使用者可以不关心弹窗真正所在的层级，只需要能在大纲树里面找到就行，就像我们平时写react，弹窗可以写在任意层级的组件，但最终都会渲染到body下面，所以我认为把所有弹窗都放到大纲树最外面是合理的。

**Comment by liujuping** [comment]
既然不用关心所在的层级，那就不应该放到区块里面，因为对于使用者来说，放到区块里面，删除区块的时候，会删除他认为在最外层的弹窗，也是不合理的。

**Comment by xwinstone** [comment]
但现在问题是，如果删除区块，这个弹窗还在，不是更不合理

**Comment by liujuping** [comment]
区块的组件放到页面之后，是散开的，可以删除区块里面任意的组件，如果删除区块和删除弹窗绑定到一起，是不合理的。用户可以选择删除区块而并不想要一起删除弹窗。

在大纲树上，如果弹窗放到最外层，但是区块在里面，会有几个问题
1.如何移动弹窗到外面？如果可以随意移动，那是不是弹窗也可以移动到区块/其他区域里面。
2.如何显示区块和弹窗的关系，表示删除区块，会删除弹窗。

如果在大纲树上不展示在最外层，又回到了最开始我评论的关于交互的问题。
