### ISSUE TITLE
如何在不引用SimulatorResizer插件的情况,初始化引擎使用iphone尺寸

### ISSUE THREAD

**Issue by Super-Rz** [alibaba/lowcode-engine#2343]

**Comment by liujuping** [comment]
init API 中配置 device: 'phone'

**Comment by liujuping** [comment]
没有案例，在 demo 项目的 demo-general/src/index.ts 中

![image](https://github.com/alibaba/lowcode-engine/assets/11935995/c0356516-abef-4a81-8a75-f671de9ef0ba)

**Comment by Super-Rz** [comment]
这个配置在不注册 SimulatorResizer 的情况是不生效的

**Comment by liujuping** [comment]
1.引擎默认支持的 device 有 mobile、iphonex、iphone6

2.在引入 SimulatorResizer 插件的情况下，SimulatorResizer 插件支持 device： phone、tablet、desktop

3.自定义的 device 类型，需要补充 device 类型对应的样式，例如 device 为 phone 时，需要补充样式如下：

```
.lc-simulator-device-phone {
    top: 16px;
    bottom: 16px;
    left: 50%;
    width: 375px;
    transform: translateX(-50%);
    margin: auto;
  }
```

**Comment by Super-Rz** [comment]
1.引擎默认支持的 device 有 mobile、iphonex、iphone6
请问这个配置要在哪里初始化呢

**Comment by liujuping** [comment]
和之前配置 phone 的位置一样，前面有截图
