### ISSUE TITLE
怎么在源码面板通过getNodeById 获取到node实例

### ISSUE THREAD

**Issue by leehomeok** [alibaba/lowcode-engine#235]
请问 ，我想获取editTable的Node 实例并给表格赋值（DataSource），
在源码面板 怎么调用 getNodeById  这个API 获取到Node instance？

**Comment by LeoYuan** [comment]
不能调用~

源码面板的产物都会放入「页面描述」，是渲染态去解析执行的，而 Node 模型等都是设计态的辅助能力，渲染态不可能使用的~

**Comment by leehomeok** [comment]
> 不能调用~
> 
> 源码面板的产物都会放入「页面描述」，是渲染态去解析执行的，而 Node 模型等都是设计态的辅助能力，渲染态不可能使用的~

那么， 有什么方法可以 给editTable设置动态数据源吗

**Comment by LeoYuan** [comment]
看一下物料描述里 ref 的描述，可以通过 this.$(ref) 拿到组件实例（非 Node 实例），然后调用组件实例的方法去设值~

**Comment by leehomeok** [comment]
> 看一下物料描述里 ref 的描述，可以通过 this.$(ref) 拿到组件实例（非 Node 实例），然后调用组件实例的方法去设值~

是通过ref 拿到实例 设置 props.datasource = [{ name: "abc"}] 这样子吗？

**Comment by leehomeok** [comment]
> 看一下物料描述里 ref 的描述，可以通过 this.$(ref) 拿到组件实例（非 Node 实例），然后调用组件实例的方法去设值~
通过这种方式设置datasource, 弹框第一次没法及时显示datasource, 关闭弹框，第二次才是正确的数据

**Comment by kwame998** [comment]
props.datasource = [{ name: "abc"}]  ，，这样不行，应用setState({})方法才行吧

**Comment by leehomeok** [comment]
> props.datasource = [{ name: "abc"}] ，，这样不行，应用setState({})方法才行吧

建议 实操过再来回答
