### ISSUE TITLE
最新的lowcode-demo 起了后，js面板保存或出错，都改成箭头函数才能保存

### ISSUE THREAD

**Issue by wssgchungang** [alibaba/lowcode-engine#2351]
## **Describe the bug (required)** / **详细描述 bug（必填）**
最新的lowcode-demo 起了后，js面板保存或出错，都改成箭头函数才能保存
![image](https://github.com/alibaba/lowcode-engine/assets/29122164/bec59481-d236-49dc-9861-259b4eb72e9e)

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

**Comment by Chrisyjs** [comment]
+1，同样遇到了，不知道怎么解决！！！

**Comment by wssgchungang** [comment]
> 

目前我是全改成箭头函数就行了

**Comment by wssgchungang** [comment]
> +1，同样遇到了，不知道怎么解决！！！

目前我是所有函数都改成箭头函数就能保存了

**Comment by MoLinJie** [comment]
+1
只需要把demo项目clone下来，yarn install就能复现。
@LeoYuan

**Comment by SuSunSam** [comment]
fix(code-editor): fixed @babel/preset-env version (7.22.9)
https://github.com/alibaba/lowcode-plugins/commit/9fff9d69b5d6eeafccd7d8091abc3b68ec332c08

原因：
在 @babel/preset-env 7.22.10 版本中，对 available-plugins 相关的逻辑进行了变更，新增了 babel7SyntaxPlugin 函数，并且通过 require(@babel/plugin-syntax-${name}) 引入部分插件。

https://github.com/babel/babel/blob/v7.22.10/packages/babel-preset-env/src/available-plugins.ts#L147

在浏览器端使用 babel 进行编译的时候，这部分依赖没有成功打包到项目中，因此出现 Cannot find module 'xxx'。
