### ISSUE TITLE
低代码组件部分结构的数据来自于异步请问官方是否有API提供

### ISSUE THREAD

**Issue by ruanlinxin** [alibaba/lowcode-engine#2352]
## **Describe the bug (required)** / **详细描述 bug（必填）**

目前有一个需求是低代码组件部分结构的数据来自于异步请问官方是否有API提供
---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
以一下项目文件为基础
https://github.com/alibaba/lowcode-materials/blob/main/packages/fusion-ui/lowcode/tab-container/meta.ts
目前本人实现如下图，提前创建一个空数组组件加载初期执行请求获取到的数据推入空数组，因为数据是引用关系所以数据返回后拖出来的组件就能根据接口数据进行变换了
![image](https://github.com/alibaba/lowcode-engine/assets/53412119/91faf51a-1c80-4e09-9d9c-e733cde7c4b5)

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by eternalsky** [comment]
我理解应该是不行， @liujuping 看看呢？
