### ISSUE TITLE
编辑器源码面板babel错误

### ISSUE THREAD

**Issue by lilithyang2018** [alibaba/lowcode-engine#2357]
## **Describe the bug (required)** / **详细描述 bug（必填）**
源码面板打开出现babel错误信息
![code-editor](https://github.com/alibaba/lowcode-engine/assets/39897706/bf32af66-82ea-40ce-9e8f-4e3c72c79904)
保存时出现以下错误信息
![code-editor-save](https://github.com/alibaba/lowcode-engine/assets/39897706/8c5719bc-ffb8-4ff0-99b0-d0aea7424eb8)

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
1. npm install -g @alilc/create-element
2. npm init @alilc/element lowcode-editor   元素类型选择编辑器(editor)
![init-editor](https://github.com/alibaba/lowcode-engine/assets/39897706/b15e8e12-59c7-488e-b50e-bd7d22c1d2a1)
3. cd lowcode-editor
4. yarn
5. yarn start
6. 在http://localhost:5556打开源码面板

## **Additional context (optional)** / **更多额外信息（可选）**
node: v16.19.1
npm: 8.19.3
yarn: 1.22.19

经本人测试发现和@babel/preset-env的版本有关，在把插件的@babel/preset-env的版本固定在7.15.8，再删除node_modules和lock文件重新安装，则code-editor可以正常修改和保存
![fix-babel-preset-env-version](https://github.com/alibaba/lowcode-engine/assets/39897706/c90a2f87-5bc9-4e42-8a5b-a87787865a3b)

**Comment by xyouZone** [comment]
<img width="757" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/50430396/47523c0b-76a0-4825-9495-7cb7f6a0e4a7">
<img width="794" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/50430396/2b97dd28-e2e5-456c-8de5-819a1b5e3193">
<img width="1122" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/50430396/4f3f293f-3db7-4428-8214-a146bf1bdde9">
我这么设置了好像还是不行

**Comment by jiatongwu** [comment]
怎么解决啊？

**Comment by hzd822** [comment]
源码编辑器有一个新的支持多文件的升级版，大家可以试用下
https://github.com/alibaba/lowcode-plugins/tree/main/packages/plugin-multiple-editor

**Comment by SuSunSam** [comment]
可以先将@babel/preset-env的版本锁到7.22.9。7.22.10版本目前会引入这个错误，具体原因排查中(https://www.npmjs.com/package/@babel/preset-env/v/7.22.10)

**Comment by SuSunSam** [comment]
> <img alt="image" width="757" src="https://user-images.githubusercontent.com/50430396/259990649-47523c0b-76a0-4825-9495-7cb7f6a0e4a7.png"> <img alt="image" width="794" src="https://user-images.githubusercontent.com/50430396/259990769-2b97dd28-e2e5-456c-8de5-819a1b5e3193.png"> <img alt="image" width="1122" src="https://user-images.githubusercontent.com/50430396/259990972-4f3f293f-3db7-4428-8214-a146bf1bdde9.png"> 我这么设置了好像还是不行

锁一下@babel/preset-env的版本到7.22.9及之前就行。使用了^的话还是会更新到最新版本的。
