### ISSUE TITLE
关于变量绑定VariableSetter中使用 props 相关属性时，不渲染问题

### ISSUE THREAD

**Issue by qizilin** [alibaba/lowcode-engine#2360]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
---

在编排页面，物流的某个属性值，使用VariableSetter中，使用 props 相关属性时，不渲染问题

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
---

1. 在 schema 中添加 componentsTree[0].props.value = 'Hello world!';
<img width="593" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/7828239/8098cd99-d770-4ec1-bbfa-3390cf6c752f">

2. 在官方提供的综合场景中，选中“文本”物料，然后将文本内容，使用变量绑定，输入 props.value
<img width="1270" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/7828239/550efc8c-015d-400d-87f1-fcfae304a9af">
<img width="1071" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/7828239/897a2b4b-a8b2-4324-a22c-4b204826f4b1">

3. “文本”物料渲染内容为空
<img width="1269" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/7828239/ef7fef67-62bb-479d-bd65-714527b79554">

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
---

预期的行为是能正常渲染绑定的属性变量，props 其实是一小部分，实际应该是以下内容也要支持正常使用
<img width="781" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/7828239/81ea1476-99ef-44b1-9fbd-ac4dc174e901">

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本 1.1.9-beta
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本 1.0.6
 - Browser [e.g. chrome, safari] / 浏览器版本 chrome 115.0.5790.170（正式版本） (x86_64)

## **Additional context (optional)** / **更多额外信息（可选）**

我们这边想做想造物中那种可以通过已有物料，发布成一个新的物料，看到一篇文章介绍，文章中有提过 props 的绑定，所以来官方试了下发现不行。希望可以指导下，非常感谢～～
<img width="1075" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/7828239/e95c28b8-c893-455f-a9b0-da9f0999cf64">
文章链接：https://mp.weixin.qq.com/s/rnvbGHImGt6oJuX2wCtaqw

**Comment by liujuping** [comment]
这个文章里面有低代码组件设计器、页面设计器，其中低代码组件设计器中使用 props.xxx，由于 props.xxx 经常不存在，所以低代码组件设计器中还会用到 mock 字段，这里展示的是 mock 字段也就是绑定变量之前的 Hello World 之类的，这部分能力需要自己在设计器中实现。

当在页面设计器中使用低代码组件，这时候支持在页面设计器中使用 低代码组件 设置 props，这时候 props 才是生效的。

**Comment by qizilin** [comment]
> 这个文章里面有低代码组件设计器、页面设计器，其中低代码组件设计器中使用 props.xxx，由于 props.xxx 经常不存在，所以低代码组件设计器中还会用到 mock 字段，这里展示的是 mock 字段也就是绑定变量之前的 Hello World 之类的，这部分能力需要自己在设计器中实现。
> 
> 当在页面设计器中使用低代码组件，这时候支持在页面设计器中使用 低代码组件 设置 props，这时候 props 才是生效的。

好的，感谢，这边去试下
