### ISSUE TITLE
关于区块的一些疑问

### ISSUE THREAD

**Issue by haloworld007** [alibaba/lowcode-engine#2361]
https://github.com/alibaba/lowcode-engine/issues/1398

<img width="942" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/8730698/aebf709a-da80-4eb1-84e8-41768c4fb34c">

这句话是说明 Component/Block 是在设计的时候作为顶层元素使用的，那设计完了我们应该是保存了一份包含完整的包含样式，事件，生命周期管理，状态管理之类的 DSL，比如文档中的描述：

```json
{
  "version": "1.0.0",
  "componentsMap": [{ }],
  "componentsTree": [{                   // 区块组件树，顶层由区块容器组件包裹；
    "componentName": "Block",            // 区块容器组件名
    "fileName": "block1",                // 区块容器 1
    "props": {},
    "css": "body {font-size: 12px;}",
    "state": {
      "name": "lucy"
    },
    "children": [{
      "componentName": "Div",
      "props": {
        "className": "className1"
      },
      "children": [{
        "componentName": "Button",
        "props": {
          "text": "点击弹出我的姓名",
          "onClick": {
            "type": "JSFunction",
            "value": "function(e){\
              alert(this.state.name)\
            }"
          }
        }
      }]
    }]
  }],
  "i18n": { }
}
```

我的问题是：**得到了这一份DSL后怎么在 Page 中使用**。Component/Block 应该都是为了在页面中复用才存在的，如果 Component/Block 只支持在顶层使用，那就没法在 Page 中作为 children 存在。

希望能提供下完整的区块使用示例🙏

**Comment by JackLian** [comment]
1. Block是把内容拆出来塞到Page里的
2. Component可以参考这个demo https://lowcode-engine.cn/demo/demo-lowcode-component/index.html

**Comment by haloworld007** [comment]
> 1. Block是把内容拆出来塞到Page里的
> 2. Component可以参考这个demo https://lowcode-engine.cn/demo/demo-lowcode-component/index.html

这个demo其实没有什么参考价值，因为这里的问题是，既然要把 Block 的内容拆出来，那么 Block 里面的全局描述，比如lifeCycles，比如methods，比如dataSources，这些 Block 的依赖要怎么放到 Page 里面。

**Comment by JackLian** [comment]
平铺放到page里面，注意处理下跟页面已有内容是否会有同名冲突
