### ISSUE TITLE
渲染器怎么更新appHelper传入函数里使用的参数？

### ISSUE THREAD

**Issue by xyouZone** [alibaba/lowcode-engine#2364]
我通过appHelper传入了一个submit函数，里面用到了渲染器项目里面的变量。但是在使用的时候发现好像这个参数一直是固定的没有改变，我想知道该怎么才能获取到最新的参数？
![image](https://github.com/alibaba/lowcode-engine/assets/50430396/4361083d-acba-409c-812e-6de631ee1751)
![image](https://github.com/alibaba/lowcode-engine/assets/50430396/f9f816db-7e56-4a79-a06c-8b360df7f397)

![image](https://github.com/alibaba/lowcode-engine/assets/50430396/e978a4eb-0f8a-4a19-b70b-2814147ed253)
![image](https://github.com/alibaba/lowcode-engine/assets/50430396/53851c05-b952-46cf-91b6-06b5ecb88bd3)
![image](https://github.com/alibaba/lowcode-engine/assets/50430396/d02e7b8a-1ec5-4932-a0ca-6b0185814302)

**Comment by liujuping** [comment]
如果可以的话，麻烦提供一个可以快速复现的 DEMO。

**Comment by xyouZone** [comment]
> 如果可以的话，麻烦提供一个可以快速复现的 DEMO。

https://github.com/xyouZone/lowcode-render-demo.   这个是demo,麻烦帮忙看下
