### ISSUE TITLE
引擎主包调试

### ISSUE THREAD

**Issue by dengtong** [alibaba/lowcode-engine#2368]
初衷：研究引擎源码
目标：通过demo项目对引擎主项目下的所有包都可通过chrome断点形式进行源码级调试，如能实现vscode或webstorm中调试更好
现状：设计态和预览态下部分包无法调试，如utils包
我通过做哪些事情可以实现以上目标呢？

**Comment by JackLian** [comment]
https://lowcode-engine.cn/site/docs/participate/prepare

**Comment by dengtong** [comment]
按照文档操作后，目前设计态可以正常调试。预览态下无法调试，如utils包。如果想在预览态下也可以调试，需要怎么做呢？

**Comment by JackLian** [comment]
预览态utils包官方没提供方案，可以自行link
