### ISSUE TITLE
大纲树插件优化

### ISSUE THREAD

**Issue by kyoonart** [alibaba/lowcode-engine#2372]
## **Describe the bug (required)** / **详细描述 bug（必填）**
请问下这个大纲树插件是哪个呢，当层级过多时就看不了，希望可以左右滚动

<img width="354" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/49586985/1a66b4aa-9cbb-4eef-a4df-719dd52f4ec7">

**Comment by JackLian** [comment]
https://github.com/alibaba/lowcode-engine/tree/main/packages/plugin-outline-pane

**Comment by JackLian** [comment]
欢迎PR~
