### ISSUE TITLE
事件API 销毁事件无效

### ISSUE THREAD

**Issue by chenrunsong** [alibaba/lowcode-engine#2377]
## **Describe the bug (required)** / **详细描述 bug（必填）**
在组件中成功用 event.on('common:DialogComponentEvent.openDialog', ()=>{...}) 注册了一个事件，但是 销毁事件无效
A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

在组件中成功用 event.on('common:DialogComponentEvent.openDialog', ()=>{...}) 注册了一个事件
然后按照官方文档的方式，使用 event.off('DialogComponentEvent.openDialog', ()=>{})来进行销毁 
---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
<img width="1115" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/21167854/aa52ed1a-95da-4684-bb68-8ec07a241d28">
<img width="515" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/21167854/e0abd556-03bb-411f-bc82-a557f2158e00">
在另外一个组件中，触发弹窗中注册的事件：
<img width="644" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/21167854/472e4111-e57c-4242-84e3-8521ae0a78d0">

Steps to reproduce the behavior: / 详细复现步骤：
如上
浏览器console中表现如下：已经触发销毁操作，但是事件依然可以触发
![Uploading image.png…](
<img width="554" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/21167854/aa1778aa-07c9-4e0d-95ca-511154efeed8">
<img width="658" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/21167854/c8543303-acd0-4428-9985-138589e09d7c">

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by liujuping** [comment]
event.on 和 event.off 第二个参数，即 function 得是同一个。下面代码才能成功删除

```
const fun = () => {};

event.on('xx', fun)

event.off('xxx', fun) 
```
