### ISSUE TITLE
@alifd/build-plugin-lowcode这个包升级到 0.2.0版本后，打包出来的文件少了meta.design.js

### ISSUE THREAD

**Issue by ajieying** [alibaba/lowcode-engine#238]
如题,
本地项目是通过npm init @alilc/element your-material-name创建的组件库
<img width="782" alt="image" src="https://user-images.githubusercontent.com/9877509/160836952-cfa952ca-5092-476d-b5cd-667e58e988cd.png">

<img width="287" alt="image" src="https://user-images.githubusercontent.com/9877509/160836723-d52bb672-331e-44bb-ba96-f1b327656578.png">
是不需要meta.design.js了，如果不需要这个js的话，资产包的配置，直接删了这个可以吗，还是这是个bug

**Comment by mark-ck** [comment]
meta.xxx.js 是从 lowcode/组件名称/meta.xxx.ts 打包出来的，如果希望组件在不同的平台有不同的配置项才会用到这个能力，通过 cli 初始化的组件项目本身就是没有 meta.design.js 的。

**Comment by ajieying** [comment]
meta.xxx.js和meta.js 有什么区别呢？

**Comment by mark-ck** [comment]
> meta.xxx.js和meta.js 有什么区别呢？

你有同一个组件在不同平台有不同配置项的诉求的话再去理解它吧，没有这个诉求的话可以不关心
