### ISSUE TITLE
我引入的自己的项目中，使用webpack5+react18报错

### ISSUE THREAD

**Issue by zhengzhuang96** [alibaba/lowcode-engine#2382]
## **Describe the bug (required)** / **详细描述 bug（必填）**

我把这个引入自己的项目中，把他当做一个子组件使用，我的项目使用的是webpack5.88.2，也处理了sass和less但是就是报错

报错图片
![image](https://github.com/alibaba/lowcode-engine/assets/29434858/27432f75-d205-4846-90d8-eb3084cf6d11)
我的样式处理
![image](https://github.com/alibaba/lowcode-engine/assets/29434858/8c9ffe18-ade6-4187-8b08-54ee9d8a1ba6)

我的组件引入
![image](https://github.com/alibaba/lowcode-engine/assets/29434858/6761e384-3309-418e-afbc-eb0b96ef098b)

我的webpack配置
![image](https://github.com/alibaba/lowcode-engine/assets/29434858/a66b39bf-220e-41e9-876e-3023d79f8c1d)

版本号用的react18
![image](https://github.com/alibaba/lowcode-engine/assets/29434858/888f560d-abed-48ce-936c-9761baca0e53)

**Comment by zhengzhuang96** [comment]
请问这是什么问题啊

**Comment by JackLian** [comment]
1. 设计上引擎是作为独立应用使用，不是作为一个组件
2. 没做过react18的适配
