### ISSUE TITLE
老版本基于npm包的写法在cdn下如何兼容？

### ISSUE THREAD

**Issue by dailc** [alibaba/lowcode-engine#2395]
## 问题
现在是基于文档，用cdn引入，externals打包的
老版本基于npm包的写法在cdn下如何兼容？

包括这些代码
```js
import DesignerPlugin, {
    Designer,
    DropLocation,
    isDragNodeDataObject,
    isDragNodeObject,
    isLocationChildrenDetail,
    LocateEvent,
    Node,
    ParentalNode,
    registerMetadataTransducer,
    LowCodePluginManager,
    SettingField,
} from '@alilc/lowcode-designer';


import {
    Editor,
    globalContext,
    registerSetter,
    getSetter,
    runInAction,
} from '@alilc/lowcode-editor-core';

import {
    registerDefaults,
    SettingsPrimaryPane,
    Skeleton,
    createSettingFieldView,
    Workbench,
  } from '@alilc/lowcode-editor-skeleton';
```

在新版本里window.AliLowCodeEngine.common里导出的变量都是阉割版本的，上面这些属性基本都找不到了(会导致直接报错)，应该如何兼容？
![image](https://github.com/alibaba/lowcode-engine/assets/6134890/91017e50-41be-4ba6-8cff-020b964f064e)

## 版本
1.0.18 版本
![image](https://github.com/alibaba/lowcode-engine/assets/6134890/50df5a7c-5cce-47c6-82ae-066fc12fdd62)
![image](https://github.com/alibaba/lowcode-engine/assets/6134890/5dc475e0-d246-4fea-ba3c-36d1ccfce20b)
![image](https://github.com/alibaba/lowcode-engine/assets/6134890/2f2b4f01-60b7-4638-9eeb-1b7e6bdfc0e0)

## 为什么要用？
因为老项目需要升级到新版本（否则无法继续迭代更新功能），而老项目里大量这种写法

**Comment by liujuping** [comment]
这个问题可以私聊一下絮黎，因为不属于外部的 issue 场景，不在这里讨论，先关掉 issue 了。
