### ISSUE TITLE
请问应用级引擎何时落地

### ISSUE THREAD

**Issue by 1490113799** [alibaba/lowcode-engine#2400]
请问应用级引擎何时落地，是否有上线版本计划

**Comment by liujuping** [comment]
对外的 demo 预计这两周。

**Comment by 1490113799** [comment]
应用级demo现在暴露的能力很让人期待，就是还有一些预览态组件加载的bug，以及欠缺出码能力的问题，请问是否有后续的修复、继续完善的计划？

**Comment by JackLian** [comment]
有bug单独提一个issue就行，会进行跟进的
