### ISSUE TITLE
怎么在不修改物料包组件源码的情况下修改组件属性面板没有的属性

### ISSUE THREAD

**Issue by tongren1515** [alibaba/lowcode-engine#2401]
## **Describe the bug (required)** / **详细描述 bug（必填）**

比如：antd组件库树选择TreeSelect怎么设置treeNodeFilterProp属性为title（属性面板没有该属性）配合“筛选节点”属性进行筛选

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

不需要

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
通过修改treeNodeFilterProp为title进行筛选title
---

## **Screenshots (optional)** / **bug 截图（可选）**
![image](https://github.com/alibaba/lowcode-engine/assets/54562296/6e23730e-d6ae-4182-8d5d-129b57cfba28)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本  1.0.28
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

**Comment by eternalsky** [comment]
没看懂什么意思，请再具体描述一下

**Comment by tongren1515** [comment]
> 没看懂什么意思，请再具体描述一下

就是树选择TreeSelect的那个`筛选节点`(图中所示)需要配合treeNodeFilterProp属性来筛选，我想要把treeNodeFilterProp属性值改为title筛选title，但是组件属性面板没有这个属性，我怎么修改这个属性值呢？（试过修改他的props但是不生效）

**Comment by eternalsky** [comment]
那在属性面板上增加这个不就可以了

**Comment by tongren1515** [comment]
有不修改组件源码的处理办法吗

**Comment by eternalsky** [comment]
为什么不修改组件物料描述，而要在没有的情况下设置

**Comment by tongren1515** [comment]
因为要用title筛选呀，value筛选用不上

**Comment by eternalsky** [comment]
还是没懂，你是说属性间有些联动，有些时候某些属性隐藏？那既然隐藏了为什么还要设置它的值
