### ISSUE TITLE
应用级引擎不具备出码能力的问题

### ISSUE THREAD

**Issue by 1490113799** [alibaba/lowcode-engine#2412]
体验了一下应用级的引擎设计器，但是现在看还没有出码的能力，请问是否有补充应用级的出码能力的计划
![image](https://github.com/alibaba/lowcode-engine/assets/40024148/132e6680-89f4-4dc7-81fd-1a692af12574)

**Comment by JackLian** [comment]
能力是有的，如果理解了单页面如何出码，应用如何出码也是不难的，现在的出码demo自行扩展即可，不过这个应用级demo暂无配套提供出码demo的计划
