### ISSUE TITLE
node.toData()方法求助

### ISSUE THREAD

**Issue by kyoonart** [alibaba/lowcode-engine#2416]
## **Describe the bug (required)** / **详细描述 bug（必填）**

升级到 1.1.10 版本后，node.toData()方法报错
<img width="486" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/49586985/4a6e4217-a9e6-4484-9e6f-42a86d9d1d26">

请问这个方法有什么改动吗，调这个方法是想获取当前这个节点的 schema 信息

**Comment by liujuping** [comment]
原来使用的是什么版本？开源版本中 node 是没有提供 toData 方法的

**Comment by kyoonart** [comment]
之前的版本是lowcode-engine@1.0.10 是可以正常使用的

**Comment by liujuping** [comment]
使用的方式截图看一下，直接通过 node 调用是没有这个方法的。

![image](https://github.com/alibaba/lowcode-engine/assets/11935995/4dda2154-4f27-42f6-9d99-893930ba52e3)

另外，这里很有可能是某些事件的回调，没有给 node 包裹 shell 层，导致之前的暴露了不应该暴露的方法。在新的版本修复了这个漏洞，如果使用的不多，建议使用 node.exportschema API 替换一下。

https://lowcode-engine.cn/site/docs/api/model/node#exportschema
