### ISSUE TITLE
FormilySchemaSetter中使用effects报错

### ISSUE THREAD

**Issue by xyouZone** [alibaba/lowcode-engine#2419]
## **Describe the bug (required)** / **详细描述 bug（必填）**
在使用formilySchemaSetter的物料的createFormItemSchema函数中添加effects，报错：Error: Consume method cannot be used in asynchronous function body
![image](https://github.com/alibaba/lowcode-engine/assets/50430396/4ca62571-4ff8-4828-bfb6-befc5a1aed8f)

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
1、运行[lowcode-ecology](https://github.com/seada-low-code/lowcode-ecology)这个仓库
2、在formily-materials/lowcod/utils/formilyFieldShared-index文件中，给FormilySchemaSetter的props添加effects
![image](https://github.com/alibaba/lowcode-engine/assets/50430396/f1e2df58-4b48-4ae9-a25e-2470e6a2b465)

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---
我想实现的功能是在设置器中实现配置的联动，比如在修改一项配置的同时自动修改另一设置项的下拉选项。我看formilySchemaSetter的props里面是有effects这个属性的，是我使用的问题还是bug?

**Comment by JackLian** [comment]
这个不是官方的仓库，需要到这里提issue哈 https://github.com/seada-low-code/lowcode-ecology/issues
