### ISSUE TITLE
添加antd物料组件不生效，报错Component Not found

### ISSUE THREAD

**Issue by zhaoweihan2017** [alibaba/lowcode-engine#2429]
重现步骤：
1、使用官方物料脚手架开发组件 npm init @alilc/element your-material-name 开发antd物料，并发布到npm库中 https://www.npmjs.com/package/zwh-my-material
2、尝试将新开发的antd物料添加到官方提供的demo-basic-antd中，按照教程合并asset.json。如下：
{
    "packages": [
      {
        "package": "moment",
        "version": "2.24.0",
        "urls": ["https://g.alicdn.com/mylib/moment/2.24.0/min/moment.min.js"],
        "library": "moment"
      },
      {
        "package": "lodash",
        "library": "_",
        "urls": ["https://g.alicdn.com/platform/c/lodash/4.6.1/lodash.min.js"]
      },
      {
        "package": "iconfont-icons",
        "urls": "//at.alicdn.com/t/font_2369445_ukrtsovd92r.js"
      },
      {
        "package": "@ant-design/icons",
        "version": "4.7.0",
        "urls": ["//g.alicdn.com/code/npm/@ali/ant-design-icons-cdn/4.5.0/index.umd.min.js"],
        "library": "icons"
      },
      {
        "package": "antd",
        "version": "4.19.5",
        "urls": [
          "//g.alicdn.com/code/lib/antd/4.23.0/antd.min.js",
          "//g.alicdn.com/code/lib/antd/4.23.0/antd.min.css"
        ],
        "library": "antd"
      },
      {
        "title": "fusion组件库",
        "package": "@alifd/next",
        "version": "1.26.4",
        "urls": [
          "https://g.alicdn.com/code/lib/alifd__next/1.26.4/next.min.css",
          "https://g.alicdn.com/code/lib/alifd__next/1.26.4/next-with-locales.min.js"
        ],
        "library": "Next"
      },
      {
        "package": "@alilc/antd-lowcode-materials",
        "version": "1.2.1",
        "library": "AntdLowcode",
        "urls": [
          "https://alifd.alicdn.com/npm/@alilc/antd-lowcode-materials@1.2.1/build/lowcode/view.js",
          "https://alifd.alicdn.com/npm/@alilc/antd-lowcode-materials@1.2.1/build/lowcode/view.css"
        ],
        "editUrls": [
          "https://alifd.alicdn.com/npm/@alilc/antd-lowcode-materials@1.2.1/build/lowcode/view.js",
          "https://alifd.alicdn.com/npm/@alilc/antd-lowcode-materials@1.2.1/build/lowcode/view.css"
        ]
      },
  
      {
        "package": "zwh-my-material",
        "version": "0.1.0",
        "library": "BizComps",
        "urls": [
          "https://unpkg.com/zwh-my-material@0.1.0/build/lowcode/render/default/view.js",
          "https://unpkg.com/zwh-my-material@0.1.0/build/lowcode/render/default/view.css"
        ],
        "editUrls": [
          "https://unpkg.com/zwh-my-material@0.1.0/build/lowcode/view.js",
          "https://unpkg.com/zwh-my-material@0.1.0/build/lowcode/view.css"
        ],
        "advancedUrls": {
          "default": [
            "https://unpkg.com/zwh-my-material@0.1.0/build/lowcode/render/default/view.js",
            "https://unpkg.com/zwh-my-material@0.1.0/build/lowcode/render/default/view.css"
          ]
        },
        "advancedEditUrls": {}
      }
  
    ],
    "components": [
      {
        "exportName": "AlilcAntdLowcodeMaterialsMeta",
        "npm": {
          "package": "@alilc/antd-lowcode-materials",
          "version": "1.2.1"
        },
        "url": "https://alifd.alicdn.com/npm/@alilc/antd-lowcode-materials@1.2.1/build/lowcode/meta.js",
        "urls": {
          "default": "https://alifd.alicdn.com/npm/@alilc/antd-lowcode-materials@1.2.1/build/lowcode/meta.js"
        }
      },
  
      {
        "exportName": "ZwhMyMaterialMeta",
        "npm": {
          "package": "zwh-my-material",
          "version": "0.1.0"
        },
        "url": "https://unpkg.com/zwh-my-material@0.1.0/build/lowcode/meta.js",
        "urls": {
          "default": "https://unpkg.com/zwh-my-material@0.1.0/build/lowcode/meta.js"
        },
        "advancedUrls": {
          "default": [
            "https://unpkg.com/zwh-my-material@0.1.0/build/lowcode/meta.js"
          ]
        }
      }
    ],
    "sort": {
      "groupList": ["精选组件", "原子组件"],
      "categoryList": ["通用", "导航", "信息输入", "信息展示", "信息反馈"]
    },
    "groupList": ["精选组件", "原子组件"],
    "ignoreComponents": {}
  }
  
3、执行npm run start 

4、可以看到添加的新组件
![图片](https://github.com/alibaba/lowcode-engine/assets/47729832/11b5d9d9-3618-45ba-a275-1928f3225035)
5、拖拽组件报错 
![图片](https://github.com/alibaba/lowcode-engine/assets/47729832/d7661f17-bbe7-40d4-8980-231a63344889)

**Comment by JackLian** [comment]
https://lowcode-engine.cn/site/docs/faq/faq009
这个先参考看看
