### ISSUE TITLE
数据源定义增加的数据处理函数保存后丢失

### ISSUE THREAD

**Issue by gaorongfu** [alibaba/lowcode-engine#243]
## **Describe the bug (required)** / **详细描述 bug（必填）**

在demo中，增加数据源“请求成功对结果的处理函数”，确认后丢失。

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
1、在demo中，在左侧数据源菜单选择数据源进行修改；
2、在最下面的下拉框选择“请求成功对结果的处理函数”；
3、然后在出现的输入框中随便加入什么语句，比如console.log(res.data);
4、然后点击数据源对话框右上角的[确认]。
5、再次打开数据源修改面板，发现添加的函数已经消失。
---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

打开后应该可以看到之前填写的函数。

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
![数据源处理函数无法保存](https://user-images.githubusercontent.com/10938991/160989663-2047ae31-9680-421b-b5e1-3999f78e6af8.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: 
 - 1.0.7 / 低代码引擎版本
 - AliLowCodeEngineExt version: 
 - 未额外安装 / 低代码引擎扩展包版本
 - Browser  
 - Microsoft Edge 99.0.1150.55 (正式版本)  / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本
 - 未额外安装

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by LeoYuan** [comment]
@xingmolu 辛苦看下哈

**Comment by twinkle77** [comment]
值是在的，但是没有回显 @gaorongfu 
已修复
