### ISSUE TITLE
官方的LAB源码以及其中的物料组件源码是否可以出售？

### ISSUE THREAD

**Issue by 476743842** [alibaba/lowcode-engine#2439]
## **Describe the bug (required)** / **详细描述 bug（必填）**

官方的LAB源码以及其中的物料组件源码是否可以出售？

**Comment by JackLian** [comment]
目前LAB不开源也不单独售卖，官方团队有个商业产品 [UIPaaS](https://uipaas.net/)，面向大型企业提供低代码能力中台，有意咨询也可联系微信 
![image](https://github.com/alibaba/lowcode-engine/assets/2149847/dd5b38fb-1fa0-4deb-881f-dc5b701e41c1)
