### ISSUE TITLE
如何进行私有化部署

### ISSUE THREAD

**Issue by ruanlinxin** [alibaba/lowcode-engine#2440]
## **Describe the bug (required)** / **详细描述 bug（必填）**
现阶段需要将平台部署在内网环境，物料包中外网cdn资源包已被我调整为项目本地，但是依旧有部分资源请求前往alicdn域名下获取，官方是否有提供相关的部署文档，

需求：期望该平台所有资源不存在外网链接（）

**Comment by ruanlinxin** [comment]
复现方式最简单，安装完依赖后关闭网络，运行项目能正常操作即可

**Comment by JackLian** [comment]
官方无计划提供相关方案

**Comment by hungryoufool** [comment]
@ruanlinxin 你好，我最近也需要在内网部署，请问有找到可以私有化部署的开源项目吗

**Comment by milo-j** [comment]
噗
