### ISSUE TITLE
文档网站存在兼容性问题

### ISSUE THREAD

**Issue by PineSongCN** [alibaba/lowcode-engine#2442]
## **Describe the bug (required)** / **详细描述 bug（必填）**

报错：The resource https://lowcode-engine.cn/site/assets/js/main.f1d54434.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally. 

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

1. 使用Chrome Canary；
2. 打开文档网站；
3. 渲染失败，报错：The resource https://lowcode-engine.cn/site/assets/js/main.f1d54434.js was preloaded using link preload but not used within a few seconds from the window's load event. Please make sure it has an appropriate `as` value and it is preloaded intentionally. 

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
正常渲染

---

## **Screenshots (optional)** / **bug 截图（可选）**
![image](https://github.com/alibaba/lowcode-engine/assets/39976617/928f0733-aae6-4f5c-b418-0097269751ec)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - Browser Chrome Canary / 版本 118.0.5990.1（正式版本）canary-dcheck (arm64)

**Comment by liujuping** [comment]
没有复现你说的问题，可以试一下隐私窗口打开。
