### ISSUE TITLE
自定义物料时，使用ant-style的antd5组件会渲染异常

### ISSUE THREAD

**Issue by option-star** [alibaba/lowcode-engine#2448]
## **Describe the bug (required)** / **详细描述 bug（必填）**

通过npm init @alilc/element your-plugin-name命令构建物料demo，其中引进antd-style, 使用antd-style时，会报组件渲染异常
<img width="860" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/62086599/f34cc559-1522-40d7-8730-7618440cd138">
---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1. node -v (v14.15.3)
2. npm -v(6.14.9)
3. npm init @alilc/element demo(选择构建物料组件库)
4. cd demo
5. npm i 
6. npm i antd
7. npm i antd-style
8. 输入components代码qs-slider
<img width="968" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/62086599/a9ef0943-2606-4f25-909e-70bc249df9b4">
<img width="735" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/62086599/e4723039-0890-4587-8dd2-3baa576991ad">
<img width="905" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/62086599/13662993-a703-493c-a4c8-5f65a922b568">
<img width="839" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/62086599/fdd2f14b-00e7-466d-9d85-b8d6b5748e83">
10. npm run lowcode:dev
11. 拖拽组件至页面
<img width="1080" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/62086599/50d34295-965e-4cb2-9806-10faa178ed89">
12. 显示渲染异常

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

正常渲染组件，不报错

---

## **Screenshots (optional)** / **bug 截图（可选）**

<img width="1151" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/62086599/fb7c3fff-4a33-490a-a70f-7357b7ed4c2f">

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
- node版本： v4.15.3
- 对应复现demo: https://github.com/option-star/lowcode-material-bug

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by eternalsky** [comment]
脚手架里默认集成的是 antd4，如果用到 antd5，需要自己配置

**Comment by option-star** [comment]
1. 好像适用antd5渲染没有问题，只是用了antd-style有问题
2. 如何配置antd5， 有参考的案例吗
