### ISSUE TITLE
图片「热区」组件有没有推荐的实现方案，或者是开源方案

### ISSUE THREAD

**Issue by Anthony-Ghy** [alibaba/lowcode-engine#2449]
## **Describe the bug (required)** / **详细描述 bug（必填）**

可以在 LowCodeEngine 中使用一款图片热区组件，可以导入图片以后针对图片的不同位置增加跳转链接属性，想把它作为一个物料 请问下老师们有相关实现的案例或者思路吗，十分感谢

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by arleyGuoLei** [comment]
+1

**Comment by eternalsky** [comment]
你是问有没有你要的开源组件？还是问如何开发物料。

**Comment by eternalsky** [comment]
开发物料可以查看文档：https://lowcode-engine.cn/site/docs/guide/expand/editor/material

**Comment by Anthony-Ghy** [comment]
> 你是问有没有你要的开源组件？还是问如何开发物料。
想问下有没有之前在 LowCodeEngine  相关热区物料实现方案，或者对应的开源方案能接入到我们搭建平台中去

**Comment by eternalsky** [comment]
目前没有现成的热区实现方案。但你可以自己开发一个物料
