### ISSUE TITLE
自定义setter中如何能监听到组件props属性的变化

### ISSUE THREAD

**Issue by Twlnkle** [alibaba/lowcode-engine#2451]
![image](https://github.com/alibaba/lowcode-engine/assets/48480478/7baf449a-d12a-4b4d-b801-b43f18116918)

以上图为例，图中组件的配置项-默认值 使用的是自定义设置器MyDateSetter，我想在组件的第一个配置项-日期类型 发生变化时，MyDateSetter能监听到变化，并进行后续操作。如何能在自定义setter中监听到组件其他属性的变化呢？ 感谢

**Comment by JackLian** [comment]
让其他的setter通知过来
https://lowcode-engine.cn/site/docs/guide/expand/editor/setter#setter-%E5%92%8C-setterplugin-%E4%B9%8B%E9%97%B4%E7%9A%84%E8%81%94%E5%8A%A8
