### ISSUE TITLE
@alilc/element 相关

### ISSUE THREAD

**Issue by toviLau** [alibaba/lowcode-engine#246]
![161030272-31785253-f7e4-49f8-bcf2-68284d70cb4e](https://user-images.githubusercontent.com/21324302/161165854-dfc99f4f-caef-4b56-832c-fd6beabbb696.png)

环境描述
os: macos 12.2.1
node: v14.17.0
npm: 6.14.13 (--registry=https://registry.npm.taobao.org/)

重现步骤
npm init @alilc/element material > react 组件库 > npm install

相关问题 ===> #70

**Comment by LeoYuan** [comment]
不是写了没有 python 么？

**Comment by toviLau** [comment]
那我是要全局安装 python 与 python2 ?

**Comment by LeoYuan** [comment]
另外，建议 node 换成 readme 中要求的版本，可能跟现在这个问题也有关

**Comment by toviLau** [comment]
好的我试试
