### ISSUE TITLE
antd样式被低代码物料样式(同版本antd)覆盖

### ISSUE THREAD

**Issue by Dogtiti** [alibaba/lowcode-engine#2460]
## **Describe the bug (required)** / **详细描述 bug（必填）**

主项目中使用的是`antd`组件库,其中配置了一些主题色,
```js
  addLessLoader({
    lessLoaderOptions: {
      lessOptions: {
        modifyVars: {
          '@primary-color': '#c8151e',
          '@font-size-base': '12px',
          '@menu-dark-bg': '#283142',
          '@link-color': '#1890ff',
        },
        javascriptEnabled: true,
        math: 'always',
      },
    },
  }),
```
但是在打开低代码页面时由于加载了`antd css`  导致主项目样式被覆盖
```
 {
      "urls": [
        "/cdn/lib/antd/3.26.20/dist/antd.min.css",
        "/cdn/lib/antd/3.26.20/dist/antd.min.js"
      ],
      "library": "antd",
      "package": "antd",
      "version": "3.26.26"
    },
```
如果不引入`css`在设计器物料又没有样式,这里应该如何解决,希望相同的组件库低代码物料能继承到上层样式

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by eternalsky** [comment]
有两个方案：
1. 物料也使用和主项目相同的 antd cdn（配置过主题的）
2. 主项目不使用 bundle 之后的物料，而选择在自己的项目中重新构建出对应的资源。

**Comment by Dogtiti** [comment]
> 有三个方案：
> 
> 1. 物料也使用和主项目相同的 antd cdn（配置过主题的）
> 2. 主项目不使用 bundle 之后的物料，而选择在自己的项目中重新构建出对应的资源。
> 3. 主项目不使用物料提供的构件好的 assets.json ，而是自己组织 assets.json，将原版的 antd cdn 从 packages 里踢出去即可。
第一点应该行不通
第二点没太懂，能稍微解释一下吗
第三点的意思是实际使用时，再把assets过滤一遍？把antd中的css过滤掉

**Comment by eternalsky** [comment]
先走方案3 吧，你们现在是怎么使用物料的 assets.json 的

**Comment by Dogtiti** [comment]
> 先走方案3 吧，你们现在是怎么使用物料的 assets.json 的

现在实际使用的assets和编辑器是同一套

**Comment by eternalsky** [comment]
> > 先走方案3 吧，你们现在是怎么使用物料的 assets.json 的
> 
> 现在实际使用的assets和编辑器是同一套

那也就是说你们的 assets 是自己组织的咯，那如果这样感觉应该没问题啊~ 你只要assets packages 里不引错误版本的 antd 的样式就可以了。

**Comment by Dogtiti** [comment]
是的 我现在直接过滤掉了 跟编辑态使用不一样的样式文件

**Comment by yiRain123** [comment]
大佬，方便指导下怎么解决的吗？我们也遇到同样的问题了

**Comment by yiRain123** [comment]
@Dogtiti 大佬，方便指导下怎么解决的吗？我们也遇到同样的问题了

**Comment by yiRain123** [comment]
@Dogtiti 大佬，再请教您一个问题，我们在设计器引入了一套红色主题的组件库，把原来蓝色主题的组件库样式给覆盖了，比如图中这个收起按钮，以前是蓝色的，现在点过就变红了，选中文字也变成了红色，请问有啥思路指导下吗？
![image](https://github.com/alibaba/lowcode-engine/assets/139101387/df460626-e2b8-43d0-a342-5bf7fcdff2c2)

**Comment by Dogtiti** [comment]
为啥有两套一样的物料？

**Comment by yiRain123** [comment]
其实两套底层都是antd ，只是因为有一套因为有特殊规范，主题样式颜色都改过，目前就是后面这套定制的覆盖了基础库的主题

---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 发送日期 | 2023年12月13日 21:29 |
| 收件人 | alibaba/lowcode-engine ***@***.***> |
| 抄送人 | yiRain123 ***@***.***>,
Mention ***@***.***> |
| 主题 | Re: [alibaba/lowcode-engine] antd样式被低代码物料样式(同版本antd)覆盖 (Issue #2460) |

为啥有两套一样的物料？
