### ISSUE TITLE
请问一下 demo中的 左侧组件库，默认是pc的吗？切换到h5是自动切换吗？

### ISSUE THREAD

**Issue by 18311023368** [alibaba/lowcode-engine#2464]
请问一下 demo中的 左侧组件库，默认是pc的吗？切换到h5是自动切换吗？
左侧用的ant-d的pc库 设备选择h5 的话  是能切换到h5的 ant库吗？还是需要怎么去做

**Comment by JackLian** [comment]
切换不到，antd 和andpro是两套组件，设备选择只是切换设计器内的画布尺寸
