### ISSUE TITLE
高级表格里面的分页器怎么拿到分页点击事件

### ISSUE THREAD

**Issue by taolei1990** [alibaba/lowcode-engine#247]
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 拖拽一个表格组件
3. 在右侧开启表格分页器；
4. 分页器没有提供相应的事件；
![image](https://user-images.githubusercontent.com/23173640/161177262-186daab9-914e-4ef6-8592-52f3e875f1fc.png)

希望提供一下表格分页器的使用方法

**Comment by mark-ck** [comment]
对于物料的问题，如果是有 bug 我们会排期解决，如果是功能需求我们基本上不会接收，并且整体排期迭代会比较慢，这个是由于内部资源调配的问题，望理解。
