### ISSUE TITLE
workspace注册的插件panel要怎么打开 ？通过skeleton.showPanel()打不开

### ISSUE THREAD

**Issue by zhuyuanmin** [alibaba/lowcode-engine#2470]
通过workspace注册的插件panel要怎么打开 ？通过skeleton.showPanel()打不开

**Comment by liujuping** [comment]
需要在 workspace 层级的插件下，调用 ctx.skeleton.showPanel

**Comment by zhuyuanmin** [comment]
> 

如果没有 plugin ctx ，直接从 引擎的 skeleton还是不行吗？现在的应用场景是自定义 i18Setter 要触发 i18 插件打开，不存在 ctx 上下文

**Comment by zhuyuanmin** [comment]
> 上面的 PR 中，可以用新增的 api workspace.skeleton 打开。如果不升级引擎的话，可以通过事件通知应用层的插件打开面板。

好的，了解了！感谢大佬解答
