### ISSUE TITLE
> 我们团队都是用的vue技术栈，应该怎么使用这个引擎

### ISSUE THREAD

**Issue by 110526** [alibaba/lowcode-engine#248]
> 我们团队都是用的vue技术栈，应该怎么使用这个引擎

见 https://github.com/alibaba/lowcode-engine/discussions/47， 官方不会做这个，目前有其他团队正在做，有消息通知大家~
@lpali

_Originally posted by @LeoYuan in https://github.com/alibaba/lowcode-engine/issues/48#issuecomment-1068693970_

您好， 这个链接现在打不开呢？我们也是vue技术栈的， 想来卡看

**Comment by LeoYuan** [comment]
更新为：https://github.com/alibaba/lowcode-engine/issues/236

建议看下代码仓库下子包 react-renderer / react-simulator-renderer，自定义需要对代码比较熟悉，所以文档也没啥用~

**Comment by 110526** [comment]
> > 我们团队都是用的vue技术栈，应该怎么使用这个引擎
> 
> 见 [https://github.com/alibaba/lowcode-engine/discussions/47，](https://github.com/alibaba/lowcode-engine/discussions/47%EF%BC%8C) 官方不会做这个，目前有其他团队正在做，有消息通知大家~ @lpali
> 
> _Originally posted by @LeoYuan in [#48 (comment)](https://github.com/alibaba/lowcode-engine/issues/48#issuecomment-1068693970)_
> 
> 您好， 这个链接现在打不开呢？我们也是vue技术栈的， 想来卡看

**Comment by 110526** [comment]
> 

谢谢
