### ISSUE TITLE
meta.ts 中怎么扩展、修改 schema 的字段？

### ISSUE THREAD

**Issue by linc2023** [alibaba/lowcode-engine#2489]
开发过程中很多组件需要集成权限，我们希望组件自动注册权限，具体如下：
在组件新增一个属性，属性开启后把 ref 和组件名称作为权限的  code、名称保存起来
```javascript
 {
        name: 'hasPermission',
        title: { label: '开启权限' },
        propType: 'bool',
        setter: 'BoolSetter',
        defaultValue: false,
        extraProps: {
          setValue(target: any, value: boolean) {
            // permission 就是权限信息，需要保存到 schema 中
            const permission =  {
              appCode: '', appName: '',parentId: '',type: '',pageId: '',
              code: target.getProps().getPropValue('ref'),
              name: target.getProps().getPropValue('nodeName'),
            };
          },
        },
      }
```
有很多组件都可能有权限，如果保存到组件的 props 里面，提交的时候需要遍历整个树，获得权限，然后提交

![image](https://github.com/alibaba/lowcode-engine/assets/133838877/d92d2d80-59d9-43ae-bba6-af9cc5f10abf)

我希望直接保存到 schema 的根节点上的某个字段上，保存页面的时候直接读取该字段，然后提交给权限系统
![image](https://github.com/alibaba/lowcode-engine/assets/133838877/d0dc1afd-361b-46a4-9def-603c48e1632b)
这时候就需要在 属性的 extraProps/setValue 里面直接修改 schema 内容，有方案吗？并且我发现一个问题，在 schema 中自定义的属性保存时会被删除掉。

**Comment by liujuping** [comment]
可以直接获取根节点的 node，进行相关操作。

**Comment by linc2023** [comment]
@liujuping 
直接获取根节点操作？这个具体这么实现？
我现在这么实现的，挂到了根节点的 props 上，这样也行
![image](https://github.com/alibaba/lowcode-engine/assets/133838877/0eb39186-03b4-4bce-a9d0-6fc8a773f87b)

**Comment by liujuping** [comment]
任意 Node 就可以直接通过这样获取。

Node.document.root

**Comment by linc2023** [comment]
@liujuping 明白了，多谢

**Comment by mywei1989** [comment]
> @liujuping 直接获取根节点操作？这个具体这么实现？ 我现在这么实现的，挂到了根节点的 props 上，这样也行 ![image](https://user-images.githubusercontent.com/133838877/268605636-0eb39186-03b4-4bce-a9d0-6fc8a773f87b.png)

发现一个问题，getExtraPropValue  获取到的是对象的引用    修改完后不需要 setExtraPropValue  在schema里就变了
不确定 getPropValue 是不是也是这样
