### ISSUE TITLE
@alilc/build-plugin-lce 不应该是@alilc/lowcode-designer的依赖

### ISSUE THREAD

**Issue by Zsynuting** [alibaba/lowcode-engine#2490]
## **Describe the bug (required)** / **详细描述 bug（必填）**

![image](https://github.com/alibaba/lowcode-engine/assets/6938179/ee7500d2-c0cc-4f07-a524-6f4709f0a48f)

@alilc/build-plugin-lce 是lowcode-engine 的构建工具，不应该是@alilc/lowcode-designer的依赖

当前包 1.1.10 在业务项目中安装后，会导致@alilc/build-plugin-lce依赖的 npm 包和业务项目中的构建工具冲突，导致业务项目构建失败

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

无需提供

---

**Comment by liujuping** [comment]
可以提 PR，放到  devDependencies 里面

**Comment by Zsynuting** [comment]
> 可以提 PR，放到 devDependencies 里面

https://github.com/alibaba/lowcode-engine/pull/2492
