### ISSUE TITLE
 如何打包的时候，将 js 、 html 等文件哈希

### ISSUE THREAD

**Issue by dongguochao** [alibaba/lowcode-engine#2494]
<img width="216" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/38397735/953a9b49-d3d0-4ad1-8922-16d6c14cf412">
 如何将 html，js，css 哈希生成
<img width="655" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/38397735/f985c72e-3ade-4590-889e-c325d44d0b59">
加入 hash:true 无反应

**Comment by eternalsky** [comment]
额，如有必要请参考 webpack 及其插件相关文档。
