### ISSUE TITLE
出码之后utils中方法没有同步出来，demo好像也是这样子

### ISSUE THREAD

**Issue by 18311023368** [alibaba/lowcode-engine#2496]
## **Describe the bug (required)** / **详细描述 bug（必填）**

![image](https://github.com/alibaba/lowcode-engine/assets/7625304/ddabd4c9-d5b8-4c65-a857-41d680ca6e07)
上面是官网的demo出码之后的有引入这个utils中的方法，但是下面是utils中的全部内容，并没有看到这个方法

import { createRef } from 'react';

export class RefsManager {
  constructor() {
    this.refInsStore = {};
  }

  clearNullRefs() {
    Object.keys(this.refInsStore).forEach((refName) => {
      const filteredInsList = this.refInsStore[refName].filter(
        (insRef) => !!insRef.current
      );
      if (filteredInsList.length > 0) {
        this.refInsStore[refName] = filteredInsList;
      } else {
        delete this.refInsStore[refName];
      }
    });
  }

  get(refName) {
    this.clearNullRefs();
    if (this.refInsStore[refName] && this.refInsStore[refName].length > 0) {
      return this.refInsStore[refName][0].current;
    }

    return null;
  }

  getAll(refName) {
    this.clearNullRefs();
    if (this.refInsStore[refName] && this.refInsStore[refName].length > 0) {
      return this.refInsStore[refName].map((i) => i.current);
    }

    return [];
  }

  linkRef(refName) {
    const refIns = createRef();
    this.refInsStore[refName] = this.refInsStore[refName] || [];
    this.refInsStore[refName].push(refIns);
    return refIns;
  }
}

export default {};

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by 18311023368** [comment]
没人帮忙看看吗

**Comment by wendy0512** [comment]
> 没人帮忙看看吗

我看协议中schema是支持配置utils的，
![image](https://github.com/alibaba/lowcode-engine/assets/44644033/342072da-feae-4115-907b-caec5177d5ba)

不行先在出码之前追加一下utils

**Comment by qingniaotonghua** [comment]
utils.demoUtil 方法是在 demo-general 中的 preview.js 中额外引入的，所以单单通过 Schema的描述 出码也不可能转译出 demoUtil 的，你可以在 schema 中额外补充需要的utils 方法

**Comment by 18311023368** [comment]
需要自己手动补充啊  好的吧
