### ISSUE TITLE
NextTable ui异常

### ISSUE THREAD

**Issue by shiwofeiwo** [alibaba/lowcode-engine#2497]
## **Describe the bug (required)** / **详细描述 bug（必填）**
NextTable组件当hasHeader为false，且theme不等于border时，lock='right',调整width会出现ui异常

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

1.打开demo
2.拖出NextTable
3.在**风格和样式**中打开再关闭**显示表头**
4.去**操作列选项**中增加**操作列宽度**
5.可以看到操作列出现了重复

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

在修改了操作列宽度后，操作列除了宽度，不会出现别的ui变化

## **Screenshots (optional)** / **bug 截图（可选）**

![image](https://github.com/alibaba/lowcode-engine/assets/105789907/fe351194-eab3-435a-ad76-d9b736e47882)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: v1.1.11-beta / 低代码引擎版本
 - AliLowCodeEngineExt version: v1.0.6 / 低代码引擎扩展包版本
 - Browser chrome: 117.0.5938.88 / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by eternalsky** [comment]
这个是因为操作列，选择了右侧列固定，但是由于列太少，宽度被table 重新分配了，两个解法，一个是取消列固定（ActionFixed） 为 none，另一个是列宽足够大。

**Comment by shiwofeiwo** [comment]
好的
