### ISSUE TITLE
utils/logger 输出的日志颜色需要重新定义

### ISSUE THREAD

**Issue by iChengbo** [alibaba/lowcode-engine#2498]
## **Describe the bug (required)** / **详细描述 bug（必填）**

logger 打印的内容颜色不友好，尤其在白色主题时，基本看不到 logger.info() 的内容，其原因是设置的颜色为 #ffffff 和控制台背景色一致。此外，其他等级的日志颜色也不合适，不能很好的区分开等级

参考代码（packages/utils/src/logger.ts）如下：
```js
const bodyColors: Record<string, string> = {
  debug: '#666666',
  log: '#bbbbbb',
  info: '#ffffff',
  warn: '#bbbbbb',
  error: '#bbbbbb',
};
```

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

安装官方文档查看控制台即可 https://lowcode-engine.cn/site/docs/api/logger

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

使用更加友好合适的颜色处理日志

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by liujuping** [comment]
欢迎 PR～
