### ISSUE TITLE
ArraySetter限制数量

### ISSUE THREAD

**Issue by zxlaole** [alibaba/lowcode-engine#2506]
有些需求场景，要求ArraySetter只能添加一项或是几项，不允许无限添加，请问如何实现，我查了ArraySetter的源码，似乎multiValue并不是控制这个的。

**Comment by liujuping** [comment]
ArraySetter 提供了 renderFooter 方法，可以定制底部添加按钮，通过这个可以自己进行相关的逻辑处理。

**Comment by zxlaole** [comment]
interface ArraySetterProps {
  value: any[];
  field: SettingField;
  itemSetter?: SetterType;
  columns?: FieldConfig[];
  multiValue?: boolean;
  hideDescription?: boolean;
  onChange?: Function;
}
我在源代码中没有看到renderFooter的属性呢

**Comment by liujuping** [comment]
https://github.com/alibaba/lowcode-engine-ext/blob/main/src/setter/array-setter/index.tsx#L59

这里，你可能需要更新一下你的本地代码。

**Comment by zxlaole** [comment]
你好，我按您说的做了测试没有效果，可能是您提到的更新本地代码

**Comment by zxlaole** [comment]
我查了engine-1.1.10中引入的lowcode-engine-ext是1.0.0版本，但npm最高应该是1,0.6，请问我是否需要更新引擎的版本才能解决，引擎目前有一个beta版本

**Comment by zxlaole** [comment]
@alilc/lowcode-engine@1.1.11-beta.11，不知道这个版本中是否更新了setter的代码

**Comment by liujuping** [comment]
lowcode-demo 用的是 cdn 地址。

lowcode-engine 使用的是 demo 中引入的 lowcode-engine-ext 的 cdn 地址的版本。

所以版本的化看网页上加载的 cdn 的版本。

**Comment by zxlaole** [comment]
好的，那我去研究一下

**Comment by zxlaole** [comment]
麻烦您帮我看一下我的配置，版本都改过来了但配置并没有生效呢。

name: 'items',
        setter: {
          componentName: 'ArraySetter',
          props: {
            itemSetter: {
              componentName: 'ObjectSetter',
              props: {
                columns: 2,
                config: {
                  items: [
                  ],
                },
              },
            },
            renderFooter: (props: any) => {
              console.log('arraysetter.renderFooter', props);
              if (props.value && props.value.length > 1) {
                return <div>只能放一个</div>;
              }
              return <Button onClick={() => props.onAdd()}>添加一项</Button>;
            },
          },
          isRequired: true,
          initialValue: [],

**Comment by zxlaole** [comment]
粘进来以后格式有点看不清楚，就是写在了和itemSetter同级，renderFooter

**Comment by zxlaole** [comment]
感谢，已经成功实现需求！

**Comment by wywppkd** [comment]
> 感谢，已经成功实现需求！

meta.ts 里面写不了 jsx 怎么解决的?
