### ISSUE TITLE
需要全局隐藏设计右侧属性区域的样式、事件和高级三个选项卡

### ISSUE THREAD

**Issue by zxlaole** [alibaba/lowcode-engine#2507]
需要全局隐藏设计右侧属性区域的样式、事件和高级三个选项卡要怎样操作？

**Comment by liujuping** [comment]
通过这个 API 来处理物料描述协议，删除掉你不需要的选项卡

https://lowcode-engine.cn/site/docs/api/material#registermetadatatransducer
