### ISSUE TITLE
禁用组件属性在右属性窗体的绑定变量按钮不生效

### ISSUE THREAD

**Issue by zxlaole** [alibaba/lowcode-engine#2518]
禁用组件属性在右属性窗体的绑定变量按钮不生效，我参见了https://github.com/alibaba/lowcode-materials/blob/fd2ed7874e8668255ef2c707a51fb13dd4787f75/packages/antd-lowcode-materials/lowcode/form/meta.ts#L20，配置了supportVariable为false，但并未生效。
```
  {
    title: {
      label: {
        type: 'i18n',
        'en-US': 'title',
        'zh-CN': '标题',
      },
      tip: 'title | 标题',
    },
    name: 'title',
    description: '标题',
    defaultValue: '标题',
    setter: {
      componentName: 'StringSetter',
      isRequired: true,
      initialValue: '标题',
    },
    supportVariable: false
  },
```

**Comment by zxlaole** [comment]
我目前做的这版应用相当于是零代码应用，所以实际上我想把所有右侧的绑定变量全部拿掉，如果有全局的开关最好。

**Comment by liujuping** [comment]
引擎版本是多少？升级到最新的试一下。

全局的变量是有的，supportVariableGlobally。

![image](https://github.com/alibaba/lowcode-engine/assets/11935995/fe178e04-7b80-4bb0-900d-3d1754d7f14a)

**Comment by zxlaole** [comment]
按您的方法已解决，可能是我配置的方式不正确。
