### ISSUE TITLE
lowcode-demo出码的代码跑不起来 / The React code exported by lowcode-demo is throwing an error：

### ISSUE THREAD

**Issue by hengyanqwe** [alibaba/lowcode-engine#2520]
## **Describe the bug (required)** / **详细描述 bug（必填）**
在导出的代码npm start时报错 | The React code exported by lowcode-demo is throwing an error:
` error  in ./node_modules/@alifd/next/lib/grid/main.scss
Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: Expected whitespace. `

## **To Reproduce (required)** / **如何复现 bug？**

使用lowcode-demo的出码功能，在导出的代码正常执行npm install ；npm start
Use the export React code feature of lowcode-demo. In the exported project, execute `npm install` and `npm start`.

## **Expected behavior (required)** / **预期行为**

但是当我把package.json中的`"@alifd/next": "1.25.23"`改为`"@alifd/next": "1.25.51"`就不再报错
When I change `"@alifd/next": "1.25.23"` to `"@alifd/next": "1.25.51"` in the `package.json` file, the error no longer occurs.

## **Screenshots (optional)** / **bug 截图**
Sceenshots for further information. (If applicable.) 

![image](https://github.com/alibaba/lowcode-engine/assets/68996932/60c41ec9-5aa0-4dc5-89c2-71852c788eac)

**Comment by qingniaotonghua** [comment]
如报错所示，是 next 组件库引入的 scss 语法错误所导致的 （and 关键字两边少了空格）， 1.25.51 这个版本是已经修复了的，使用这个版本就好。
![image](https://github.com/alibaba/lowcode-engine/assets/10780785/a291f6be-ec2d-4757-a549-64bf33805756)

**Comment by qingniaotonghua** [comment]
如报错所示，是 next 组件库引入的 scss 语法错误所导致的 （and 关键字两边少了空格）， 1.25.51 这个版本是已经修复了的，使用这个版本就好。
![image](https://github.com/alibaba/lowcode-engine/assets/10780785/a291f6be-ec2d-4757-a549-64bf33805756)
