### ISSUE TITLE
新建的单组件物料，咋配置webpack配置呢

### ISSUE THREAD

**Issue by ohlyf** [alibaba/lowcode-engine#2522]
目前需求是里面包一层其他组件库，但是组件库需要配置webpack，或 vite

**Comment by eternalsky** [comment]
物料脚手架基于 [build-scripts 1.x](https://github.com/ice-lab/build-scripts/tree/stable/1.x)，可以通过自定义 build-scripts 插件来完成 webpack config 定制。
