### ISSUE TITLE
求助，多文档结构的使用场景是什么

### ISSUE THREAD

**Issue by avivadepp** [alibaba/lowcode-engine#2529]
我们可以通过project创建多个文档，componentsTree可能是是数组格式，如[《低代码引擎搭建协议规范》](https://lowcode-engine.cn/site/docs/specs/lowcode-spec#2111-router-%E5%BA%94%E7%94%A8%E8%B7%AF%E7%94%B1%E9%85%8D%E7%BD%AE%E7%BB%93%E6%9E%84%E6%8F%8F%E8%BF%B0)中的示例
```
{
  "router": {
    "baseName": "/",
    "historyMode": "hash",
    "routes": [
      {
        "path": "home",
        "page": "home"
      },
      {
        "path": "/*",
        "redirect": "notFound"
      }
    ]
  },
  "componentsTree": [
    {
      "id": "home",
      ...
    },
    {
      "id": "notFound",
      ...
    }
  ]
}
```
但目前的ReactRenderer似乎只能渲染单个componentsTree
```
const schema = componentsTree[0];
```
```
    <ReactRenderer
        className="lowcode-plugin-sample-preview-content"
        schema={schema}
        components={components}
      />
```
请问如何渲染componentsTree数组。
以及目前多文档结构的作用是什么，感觉不管怎么样都只有第一个有作用。

**Comment by JackLian** [comment]
如果你现在找不到场景，说明你确实是不需要，就当成单schema使用即可

**Comment by avivadepp** [comment]
> 如果你现在找不到场景，说明你确实是不需要，就当成单schema使用即可
里面还有一个问题，多个componentsTree如何渲染
