### ISSUE TITLE
在lowcode-demo 代码当中如何控制Widget显示隐藏？

### ISSUE THREAD

**Issue by zhugenqiang** [alibaba/lowcode-engine#253]
## **Describe the bug (required)** / **详细描述 bug（必填）**
在lowcode-demo 代码当中如何控制Widget显示隐藏
## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
` skeleton.add({
          name: 'saveSample',
          area: 'topArea',
          type: 'Widget',
          props: {
            align: 'right',
          },
          content: (
            <div>
            <Button type="primary" onClick={saveSchema}>
              保存
            </Button>
            </div>
          ),
        });
        hotkey.bind('command+s', (e) => {
          e.preventDefault();
          saveSchema();
        });
        skeleton.hideWidget('saveSample');
      },`
Steps to reproduce the behavior: / 详细复现步骤：
         增加了  skeleton.hideWidget('saveSample');，但是并没有生效，保存按钮没有隐藏

**Comment by zhang8043** [comment]
https://www.yuque.com/lce/doc/bv3und#DDNSu

**Comment by zhang8043** [comment]
```
import { skeleton } from '@alilc/lowcode-engine';

skeleton.hideWidget('resetSchema');
```

# hideWidget

hideWidget(name: string)

隐藏指定 widget 实例。

# showWidget

showWidget(name: string)

展示指定 Widget 实例
