### ISSUE TITLE
只能控制一个弹窗打开

### ISSUE THREAD

**Issue by pjtian** [alibaba/lowcode-engine#254]
两个按钮控制两个弹窗(分别使用不同变量控制),只能控制一个打开关闭，有时候两个都不行,需要重新在大纲树勾选才能重新打开,大纲书只能勾选一个对话框

**Comment by LeoYuan** [comment]
设计器里模态框最多只能同时显示一个，互斥的

**Comment by pjtian** [comment]
那如果需要两个需要怎么解决

**Comment by liujuping** [comment]
目前是不支持的。

1.设计态弹窗出现两个也是无法设计的。

2.预览态跟物料有关系，可以定制物料解决。
