### ISSUE TITLE
本地inject数据时，接口'http://127.0.0.1:8899/apis/injectinfo'无返回数据，注册失败

### ISSUE THREAD

**Issue by guowei55555** [alibaba/lowcode-engine#2540]
![c991db39a5724fbe832fa57f01760db](https://github.com/alibaba/lowcode-engine/assets/85118142/f2cd5473-7b0b-4dee-ba68-85465e9c45a7)

![63452f5ae4d250e97f8a49a145a0702](https://github.com/alibaba/lowcode-engine/assets/85118142/a47aa396-c5e2-4d12-b320-17908925b510)

**Comment by eternalsky** [comment]
请描述一下复现步骤，以及可能的话复现的 demo
