### ISSUE TITLE
怎么向form组件绑定field字段

### ISSUE THREAD

**Issue by shiwofeiwo** [alibaba/lowcode-engine#2545]
![image](https://github.com/alibaba/lowcode-engine/assets/105789907/31057af1-9999-4eee-a511-cb56d86d77bc)
lowcode engine demo 综合场景中的原子组件->表单容器，应该如何绑定field实例
通过左侧源码面板无法绑定
![image](https://github.com/alibaba/lowcode-engine/assets/105789907/8d217328-b681-46f1-8f21-f80d38185dc4)
![image](https://github.com/alibaba/lowcode-engine/assets/105789907/078c2735-c6c6-4525-8b50-7ddb77fc828d)

**Comment by eternalsky** [comment]
js 面板里没法写 require/import 这样的逻辑，如果需要用 Field 的话，可能需要引一个 Package，把 Field 在全局导出来。

**Comment by eternalsky** [comment]
其实在低代码里这样使用的场景应该会比较少，更多应该是使用 Form 提供的 saveField 回调保存由 Form 初始化的实例后续调用会比较多。

**Comment by shiwofeiwo** [comment]
解决了，thx
