### ISSUE TITLE
@alilc/lowcode-types@1.1.10版本未导出“ISettingField”类型

### ISSUE THREAD

**Issue by wutingyehe** [alibaba/lowcode-engine#2548]
![image](https://github.com/alibaba/lowcode-engine/assets/6176663/7fd66e8c-c12d-4811-a7c2-2259d7926055)
@alilc/lowcode-types@1.1.10版本未导出“ISettingField”类型
![image](https://github.com/alibaba/lowcode-engine/assets/6176663/9f21acdc-cfbb-4814-a73f-0ad00d95e5fb)
但是在调用items的时候类型检测需要使用。

**Comment by liujuping** [comment]
对外提供的是 IPublicModelSettingField，ISettingField 是内部的。如果有类型错误，可能是类型定义有问题，可以提供一下类型定位报错的复现场景。
