### ISSUE TITLE
 lowcode-demo这个仓库怎么整体进行升级

### ISSUE THREAD

**Issue by ajieying** [alibaba/lowcode-engine#255]
如题，现在我看[lowcode-demo](https://github.com/alibaba/lowcode-demo)这个仓库依赖的lowcode-engine都升级到了1.0.3，请问我怎么整体升级lowcode-demo这个仓库？有文档吗？

**Comment by LeoYuan** [comment]
就是改index.ejs里的script/link（你本地的项目也改script/link就好），具体你可以看下这个仓库的commit记录

**Comment by ajieying** [comment]
OK
