### ISSUE TITLE
预览页面使用资产包配置第三方工具扩展

### ISSUE THREAD

**Issue by lilithyang2018** [alibaba/lowcode-engine#2556]
![utils](https://github.com/alibaba/lowcode-engine/assets/39897706/c02c4e52-26ae-4723-9659-60076d01b290)
目前这种方法只对设计器页面生效，比API配置的方式更加灵活
现在预览页面也有这个需求，请问能否在预览页面也使用资产包注入的方式？
如果可行，能否在下个版本实现？
@LeoYuan

**Comment by JackLian** [comment]
资产包只对设计器生效，不可行
