### ISSUE TITLE
通过npm init @alilc/element XXXXX 这种形式创建的本地组件库，在转化Antd Slider组件的时候报错，不能生成对应的meta.ts

### ISSUE THREAD

**Issue by ajieying** [alibaba/lowcode-engine#257]
<img width="1233" alt="image" src="https://user-images.githubusercontent.com/9877509/161361185-315df005-64e1-4551-817c-45bd7cf91dd8.png">

如题，辛苦看下哈；

<img width="804" alt="image" src="https://user-images.githubusercontent.com/9877509/161361314-f283610f-a378-4ebc-beb1-459b1092e52d.png">
在@alifd/build-plugin-lowcode/utils/parse-props.ts:148:35文件中，按照上图中红框中修改，就整正常编译成功；辛苦看下这个问题哈

本地转化代码如下图：
<img width="978" alt="image" src="https://user-images.githubusercontent.com/9877509/161361405-54598e2c-f739-4461-8c94-9b4d539df59f.png">

**Comment by taolei1990** [comment]
请问你通过npm init @alilc/element XXXXX 这种形式创建的本地组件库执行命令 npm run lowcode:dev 能否正常运行
![image](https://user-images.githubusercontent.com/23173640/161884044-6bf2fff1-67f9-43a7-aaf8-25943e3e7ea8.png)
我这边报这个问题该怎么解决呀

**Comment by ajieying** [comment]
> 请问你通过npm init @alilc/element XXXXX 这种形式创建的本地组件库执行命令 npm run lowcode:dev 能否正常运行 ![image](https://user-images.githubusercontent.com/23173640/161884044-6bf2fff1-67f9-43a7-aaf8-25943e3e7ea8.png) 我这边报这个问题该怎么解决呀

npm run lowcode:dev 不正常 第一个截图就是 执行这个命令产生的

**Comment by baiheinet** [comment]
windows的原因 用wsl

**Comment by mark-ck** [comment]
@ajieying `propType.value.map` 没判断的逻辑已经加上了，@alifd/build-plugin-lowcode@0.2.3

**Comment by ajieying** [comment]
现在有新问题了，我没改配置文件，我把原来的node-modules删除后重新安装，一直报错，打开页面也找不到已经生成的低代码物料如下图：
<img width="1311" alt="image" src="https://user-images.githubusercontent.com/9877509/161920673-2ada7aea-ad1e-4275-a5d9-7cb9037617fb.png">
<img width="426" alt="image" src="https://user-images.githubusercontent.com/9877509/161920806-f9bf1d7b-5e15-4f51-ad36-c9f668bb02d6.png">
辛苦帮忙看下哈@mark-ck

**Comment by ajieying** [comment]
问题已经解决
