### ISSUE TITLE
高级表单取值，saveField事件如何使用

### ISSUE THREAD

**Issue by uiiu** [alibaba/lowcode-engine#2571]
复现路径：
1、复制下面的schema 到 https://lowcode-engine.cn/demo/demo-general/index.html中
2、高级表单，使用 onsubmit事件 点击提交 - 参数中 拿不到表单的 数据
3、高级表单中自带的 saveField 事件  如何使用  怎么才能触发保存表单事件呢
4、上面问题 麻烦解答一下

{
  "version": "1.0.0",
  "componentsMap": [
    {
      "package": "@alilc/lowcode-materials",
      "version": "1.0.7",
      "exportName": "NextText",
      "main": "lib/index.js",
      "destructuring": true,
      "subName": "",
      "componentName": "NextText"
    },
    {
      "package": "@alifd/layout",
      "version": "2.4.1",
      "exportName": "P",
      "main": "lib/index.js",
      "destructuring": true,
      "subName": "",
      "componentName": "FDP"
    },
    {
      "package": "@alifd/layout",
      "version": "2.4.1",
      "exportName": "Cell",
      "main": "lib/index.js",
      "destructuring": true,
      "subName": "",
      "componentName": "FDCell"
    },
    {
      "package": "@alifd/layout",
      "version": "2.4.1",
      "exportName": "Block",
      "main": "lib/index.js",
      "destructuring": true,
      "subName": "",
      "componentName": "FDBlock"
    },
    {
      "package": "@alifd/fusion-ui",
      "version": "2.0.2",
      "exportName": "ProForm",
      "main": "lib/index.js",
      "destructuring": true,
      "subName": "",
      "componentName": "ProForm"
    },
    {
      "package": "@alifd/layout",
      "version": "2.4.1",
      "exportName": "Section",
      "main": "lib/index.js",
      "destructuring": true,
      "subName": "",
      "componentName": "FDSection"
    },
    {
      "package": "@alifd/layout",
      "version": "2.4.1",
      "exportName": "Page",
      "main": "lib/index.js",
      "destructuring": true,
      "componentName": "FDPage"
    },
    {
      "devMode": "lowCode",
      "componentName": "Page"
    },
    {
      "package": "@alifd/fusion-ui",
      "version": "2.0.2",
      "exportName": "FormInput",
      "main": "",
      "destructuring": true,
      "subName": "",
      "componentName": "FormInput"
    },
    {
      "package": "@alifd/fusion-ui",
      "version": "2.0.2",
      "exportName": "FormNumberPicker",
      "main": "",
      "destructuring": true,
      "subName": "",
      "componentName": "FormNumberPicker"
    }
  ],
  "componentsTree": [
    {
      "componentName": "Page",
      "id": "node_dockcviv8fo1",
      "props": {
        "ref": "outerView",
        "style": {
          "height": "100%"
        }
      },
      "docId": "doclaqkk3b9",
      "fileName": "/",
      "dataSource": {
        "list": [
          {
            "type": "fetch",
            "isInit": true,
            "options": {
              "params": {},
              "method": "GET",
              "isCors": true,
              "timeout": 5000,
              "headers": {},
              "uri": "mock/info.json"
            },
            "id": "info",
            "shouldFetch": {
              "type": "JSFunction",
              "value": "function() { \n  console.log('should fetch.....');\n  return true; \n}"
            }
          }
        ]
      },
      "state": {
        "text": {
          "type": "JSExpression",
          "value": "\"outer\""
        },
        "isShowDialog": {
          "type": "JSExpression",
          "value": "false"
        }
      },
      "css": "body {\n  font-size: 12px;\n}\n\n.button {\n  width: 100px;\n  color: #ff00ff\n}",
      "lifeCycles": {
        "componentDidMount": {
          "type": "JSFunction",
          "value": "function componentDidMount() {\n  console.log('did mount');\n}",
          "source": "function componentDidMount() {\n  console.log('did mount');\n}"
        },
        "componentWillUnmount": {
          "type": "JSFunction",
          "value": "function componentWillUnmount() {\n  console.log('will unmount');\n}",
          "source": "function componentWillUnmount() {\n  console.log('will unmount');\n}"
        }
      },
      "methods": {
        "testFunc": {
          "type": "JSFunction",
          "value": "function testFunc() {\n  console.log('test func');\n}",
          "source": "function testFunc() {\n  console.log('test func');\n}"
        },
        "onClick": {
          "type": "JSFunction",
          "value": "function onClick() {\n  this.setState({\n    isShowDialog: true\n  });\n}",
          "source": "function onClick() {\n  this.setState({\n    isShowDialog: true\n  });\n}"
        },
        "closeDialog": {
          "type": "JSFunction",
          "value": "function closeDialog() {\n  this.setState({\n    isShowDialog: false\n  });\n}",
          "source": "function closeDialog() {\n  this.setState({\n    isShowDialog: false\n  });\n}"
        },
        "getHelloWorldText": {
          "type": "JSFunction",
          "value": "function getHelloWorldText() {\n  return this.i18n('i18n-jwg27yo4');\n}",
          "source": "function getHelloWorldText() {\n  return this.i18n('i18n-jwg27yo4');\n}"
        },
        "getHelloWorldText2": {
          "type": "JSFunction",
          "value": "function getHelloWorldText2() {\n  return this.i18n('i18n-jwg27yo3', {\n    name: '絮黎'\n  });\n}",
          "source": "function getHelloWorldText2() {\n  return this.i18n('i18n-jwg27yo3', {\n    name: '絮黎'\n  });\n}"
        },
        "onTestConstantsButtonClicked": {
          "type": "JSFunction",
          "value": "function onTestConstantsButtonClicked() {\n  console.log('constants.ConstantA:', this.constants.ConstantA);\n  console.log('constants.ConstantB:', this.constants.ConstantB);\n}",
          "source": "function onTestConstantsButtonClicked() {\n  console.log('constants.ConstantA:', this.constants.ConstantA);\n  console.log('constants.ConstantB:', this.constants.ConstantB);\n}"
        },
        "onTestUtilsButtonClicked": {
          "type": "JSFunction",
          "value": "function onTestUtilsButtonClicked() {\n  this.utils.demoUtil('param1', 'param2');\n}",
          "source": "function onTestUtilsButtonClicked() {\n  this.utils.demoUtil('param1', 'param2');\n}"
        },
        "onSubmit": {
          "type": "JSFunction",
          "value": "function onSubmit(e) {\n  e.preventDefault();\n  console.log(arguments, '0-0-0--0-');\n}",
          "source": "function onSubmit(e) {\n  e.preventDefault();\n  console.log(arguments, '0-0-0--0-');\n}"
        }
      },
      "originCode": "class LowcodeComponent extends Component {\n  state = {\n    \"text\": \"outer\",\n    \"isShowDialog\": false\n  }\n  componentDidMount() {\n    console.log('did mount');\n  }\n  componentWillUnmount() {\n    console.log('will unmount');\n  }\n  testFunc() {\n    console.log('test func');\n  }\n  onClick() {\n    this.setState({\n      isShowDialog: true\n    });\n  }\n  closeDialog() {\n    this.setState({\n      isShowDialog: false\n    });\n  }\n  getHelloWorldText() {\n    return this.i18n('i18n-jwg27yo4');\n  }\n  getHelloWorldText2() {\n    return this.i18n('i18n-jwg27yo3', {\n      name: '絮黎',\n    });\n  }\n  onTestConstantsButtonClicked() {\n    console.log('constants.ConstantA:', this.constants.ConstantA);\n    console.log('constants.ConstantB:', this.constants.ConstantB);\n\t}\n\tonTestUtilsButtonClicked(){\n    this.utils.demoUtil('param1', 'param2');\n\t}\n\n\tonSubmit(e){\n    e.preventDefault();\n    console.log(arguments,'0-0-0--0-')\n\t}\n}",
      "hidden": false,
      "title": "",
      "isLocked": false,
      "condition": true,
      "conditionGroup": "",
      "children": [
        {
          "componentName": "FDPage",
          "id": "node_oclfjpfqjy5",
          "props": {
            "contentProps": {
              "style": {
                "background": "rgba(255,255,255,0)"
              }
            },
            "ref": "fdpage-bb43fbb0"
          },
          "title": "页面",
          "hidden": false,
          "isLocked": false,
          "condition": true,
          "conditionGroup": "",
          "children": [
            {
              "componentName": "FDSection",
              "id": "node_oclfjpfqjy6",
              "props": {
                "style": {
                  "backgroundColor": "rgba(255,255,255,1)",
                  "minHeight": ""
                }
              },
              "title": "区域",
              "hidden": false,
              "isLocked": false,
              "condition": true,
              "conditionGroup": "",
              "children": [
                {
                  "componentName": "FDBlock",
                  "id": "node_oclfjpfqjy7",
                  "props": {
                    "mode": "transparent",
                    "span": 12
                  },
                  "title": "区块",
                  "hidden": false,
                  "isLocked": false,
                  "condition": true,
                  "conditionGroup": "",
                  "children": [
                    {
                      "componentName": "FDCell",
                      "id": "node_oclfjpfqjy8",
                      "props": {
                        "align": "left",
                        "verAlign": "top",
                        "style": {
                          "backgroundColor": "rgba(255,255,255,1)"
                        },
                        "width": ""
                      },
                      "title": "容器",
                      "hidden": false,
                      "isLocked": false,
                      "condition": true,
                      "conditionGroup": "",
                      "children": [
                        {
                          "componentName": "FDP",
                          "id": "node_oclfjpfqjy10",
                          "props": {},
                          "title": "段落",
                          "hidden": false,
                          "isLocked": false,
                          "condition": true,
                          "conditionGroup": "",
                          "children": [
                            {
                              "componentName": "NextText",
                              "id": "node_oclfjpfqjyz",
                              "props": {
                                "type": "h1",
                                "children": "Home",
                                "mark": false,
                                "code": false,
                                "delete": false,
                                "underline": false,
                                "strong": false,
                                "prefix": "",
                                "classname": "",
                                "style": {
                                  "fontSize": "25px"
                                }
                              },
                              "hidden": false,
                              "title": "",
                              "isLocked": false,
                              "condition": true,
                              "conditionGroup": ""
                            }
                          ]
                        }
                      ]
                    }
                  ]
                },
                {
                  "componentName": "FDBlock",
                  "id": "node_oclfjqcf7z3g",
                  "props": {
                    "mode": "transparent",
                    "span": 12,
                    "style": {
                      "backgroundColor": "rgba(255,255,255,1)",
                      "minHeight": ""
                    }
                  },
                  "title": "区块",
                  "hidden": false,
                  "isLocked": false,
                  "condition": true,
                  "conditionGroup": "",
                  "children": [
                    {
                      "componentName": "FDCell",
                      "id": "node_oclfjqcf7z3h",
                      "props": {
                        "align": "left",
                        "verAlign": "top",
                        "style": {
                          "backgroundColor": "rgba(255,255,255,1)"
                        }
                      },
                      "title": "容器",
                      "hidden": false,
                      "isLocked": false,
                      "condition": true,
                      "conditionGroup": ""
                    }
                  ]
                },
                {
                  "componentName": "FDBlock",
                  "id": "node_oclnmkzvrr1",
                  "props": {
                    "mode": "transparent",
                    "span": 12,
                    "style": {
                      "backgroundColor": "rgba(255,255,255,1)",
                      "minHeight": ""
                    }
                  },
                  "title": "区块",
                  "hidden": false,
                  "isLocked": false,
                  "condition": true,
                  "conditionGroup": "",
                  "children": [
                    {
                      "componentName": "FDCell",
                      "id": "node_oclnmkzvrr2",
                      "props": {
                        "align": "left",
                        "verAlign": "top",
                        "style": {
                          "backgroundColor": "rgba(255,255,255,1)"
                        },
                        "width": ""
                      },
                      "title": "容器",
                      "hidden": false,
                      "isLocked": false,
                      "condition": true,
                      "conditionGroup": ""
                    }
                  ]
                },
                {
                  "componentName": "FDBlock",
                  "id": "node_oclnx0qne81",
                  "props": {
                    "mode": "transparent",
                    "span": 12,
                    "style": {
                      "backgroundColor": "rgba(255,255,255,1)",
                      "minHeight": ""
                    }
                  },
                  "title": "区块",
                  "hidden": false,
                  "isLocked": false,
                  "condition": true,
                  "conditionGroup": "",
                  "children": [
                    {
                      "componentName": "FDCell",
                      "id": "node_oclnx0qne82",
                      "props": {},
                      "title": "容器",
                      "hidden": false,
                      "isLocked": false,
                      "condition": true,
                      "conditionGroup": "",
                      "children": [
                        {
                          "componentName": "ProForm",
                          "id": "node_oclnx0qne86l",
                          "props": {
                            "placeholder": "请在右侧面板添加表单项+",
                            "placeholderStyle": {
                              "height": "38px",
                              "color": "#0088FF",
                              "background": "#d8d8d836",
                              "border": 0,
                              "gridArea": "span 4 / span 4"
                            },
                            "columns": 4,
                            "labelCol": {
                              "fixedSpan": 4
                            },
                            "labelAlign": "top",
                            "emptyContent": "添加表单项",
                            "ref": "pro-form-entrylnx0qqp1",
                            "operations": [
                              {
                                "content": "提交",
                                "action": "submit",
                                "type": "normal"
                              }
                            ],
                            "labelTextAlign": "right",
                            "size": "medium",
                            "device": "desktop",
                            "__events": {
                              "eventDataList": [
                                {
                                  "type": "componentEvent",
                                  "name": "onSubmit",
                                  "relatedEventName": "onSubmit"
                                }
                              ],
                              "eventList": [
                                {
                                  "name": "saveField",
                                  "disabled": false
                                },
                                {
                                  "name": "onSubmit",
                                  "disabled": true
                                },
                                {
                                  "name": "onChange",
                                  "disabled": false
                                }
                              ]
                            },
                            "onSubmit": {
                              "type": "JSFunction",
                              "value": "function(){return this.onSubmit.apply(this,Array.prototype.slice.call(arguments).concat([])) }"
                            }
                          },
                          "title": "高级表单",
                          "hidden": false,
                          "isLocked": false,
                          "condition": true,
                          "conditionGroup": "",
                          "children": [
                            {
                              "componentName": "FormInput",
                              "id": "node_oclnx0qzcjl",
                              "props": {
                                "formItemProps": {
                                  "primaryKey": "2519",
                                  "label": "表单项",
                                  "size": "medium",
                                  "device": "desktop",
                                  "fullWidth": true
                                },
                                "placeholder": "请输入"
                              },
                              "hidden": false,
                              "title": "",
                              "isLocked": false,
                              "condition": true,
                              "conditionGroup": ""
                            },
                            {
                              "componentName": "FormNumberPicker",
                              "id": "node_oclnx0qzcjm",
                              "props": {
                                "formItemProps": {
                                  "primaryKey": "5634",
                                  "label": "表单项",
                                  "size": "medium",
                                  "device": "desktop",
                                  "fullWidth": true
                                },
                                "placeholder": "请输入"
                              },
                              "hidden": false,
                              "title": "",
                              "isLocked": false,
                              "condition": true,
                              "conditionGroup": ""
                            },
                            {
                              "componentName": "FormInput",
                              "id": "node_oclnx0qzcjn",
                              "props": {
                                "formItemProps": {
                                  "primaryKey": "3429",
                                  "label": "表单项",
                                  "size": "medium",
                                  "device": "desktop",
                                  "fullWidth": true
                                },
                                "placeholder": "请输入"
                              },
                              "hidden": false,
                              "title": "",
                              "isLocked": false,
                              "condition": true,
                              "conditionGroup": ""
                            },
                            {
                              "componentName": "FormInput",
                              "id": "node_oclnx0qzcjo",
                              "props": {
                                "formItemProps": {
                                  "primaryKey": "9491",
                                  "label": "表单项",
                                  "size": "medium",
                                  "device": "desktop",
                                  "fullWidth": true
                                },
                                "placeholder": "请输入"
                              },
                              "hidden": false,
                              "title": "",
                              "isLocked": false,
                              "condition": true,
                              "conditionGroup": ""
                            },
                            {
                              "componentName": "FormInput",
                              "id": "node_oclnx0qzcjp",
                              "props": {
                                "formItemProps": {
                                  "primaryKey": "3383",
                                  "label": "表单项",
                                  "size": "medium",
                                  "device": "desktop",
                                  "fullWidth": true
                                },
                                "placeholder": "请输入"
                              },
                              "hidden": false,
                              "title": "",
                              "isLocked": false,
                              "condition": true,
                              "conditionGroup": ""
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  ],
  "i18n": {
    "zh-CN": {
      "i18n-jwg27yo4": "你好 ",
      "i18n-jwg27yo3": "{name} 博士"
    },
    "en-US": {
      "i18n-jwg27yo4": "Hello ",
      "i18n-jwg27yo3": "Doctor {name}"
    }
  }
}

**Comment by eternalsky** [comment]
saveField 不是表单保存的功能，而是用来给外部存储 field 实例用的。可以参考 [fusion form](https://fusion.design/pc/component/form?themeid=2#Form) 里的讲解。这个 saveField 会在组件渲染时触发。

**Comment by eternalsky** [comment]
拿到 field 实例后，就可以调用一系列的 field api，可以参考 [fusion field](https://fusion.design/pc/component/field?themeid=2#demo-api) 文档。
