### ISSUE TITLE
画布区域的根组件不为Page时, 组件源码中的react生命周期不会执行

### ISSUE THREAD

**Issue by jeffery-zhang** [alibaba/lowcode-engine#2576]
画布区域的根组件不为Page时, 组件源码中的react生命周期不会执行, 请问这个问题要怎么处理

**Comment by JackLian** [comment]
为啥不为Page

**Comment by jeffery-zhang** [comment]
> 为啥不为Page

我这边分为两个应用, 一个为构建页面的编辑器, 一个是构建低代码组件的编辑器, 构建页面的画布中就是Page组件, 另一个就用的Component组件

**Comment by JackLian** [comment]
那提供个复现的demo吧，我们看看

**Comment by jeffery-zhang** [comment]
> 那提供个复现的demo吧，我们看看

应该不用提供demo吧, 直接在页面schema中手动把根组件的componentName从Page改为Component之后就不会触发生命周期函数里的打印信息了

**Comment by LAMMUpro** [comment]
> > 为啥不为Page
> 
> 我这边分为两个应用, 一个为构建页面的编辑器, 一个是构建低代码组件的编辑器, 构建页面的画布中就是Page组件, 另一个就用的Component组件

你用编辑器来写组件？自定义组件或者区块没法满足你的需求吗？

**Comment by jeffery-zhang** [comment]
> > > 为啥不为Page
> > 
> > 
> > 我这边分为两个应用, 一个为构建页面的编辑器, 一个是构建低代码组件的编辑器, 构建页面的画布中就是Page组件, 另一个就用的Component组件
> 
> 你用编辑器来写组件？自定义组件或者区块没法满足你的需求吗？

这边的需求就是用编辑器来生成低代码组件然后在页面编辑器中直接拖拽使用, 我参照了官方低代码组件demo来实现的

**Comment by sanmao666** [comment]
请问自己写的物料组件库，物料组件是否生命周期？

**Comment by sanmao666** [comment]
请问自己写的物料组件库，物料组件是否支持生命周期？
