### ISSUE TITLE
project.currentDocument.onMountNode 中的node 缺少方法

### ISSUE THREAD

**Issue by mywei1989** [alibaba/lowcode-engine#2577]
版本号:AliLowCodeEngine  v1.1.10     AliLowCodeExt  v1.0.6 
根据[本文档](https://lowcode-engine.cn/site/docs/api/model/document-model#onmountnode)

```
/**
 * 当前 document 新增节点事件，此时节点已经挂载到 document 上
 * set callback for event on node is mounted to canvas
 */
onMountNode(fn: (payload: { node: IPublicModelNode }) => void): IPublicTypeDisposable;
```
[IPublicModelNode](https://github.com/alibaba/lowcode-engine/blob/main/packages/types/src/shell/model/node.ts) 含有  importSchema 与 exportSchema方法
可是实际使用中缺少这个两个方法 
也不存在 这一对方法  getExtraPropValue   setExtraPropValue
存在 node.schema 属性可以获取到schema 但无法修改

```
project.currentDocument.onMountNode(({ node }) => {
     let nodeSchema = node.exportSchema() //  Uncaught TypeError: node.exportSchema is not a function
    let schemaObj = node.schema 
    node.importSchema(schemaObj) //  Uncaught TypeError: node.importSchema is not a function
})
```

**Comment by eightHundreds** [comment]
+1

原因是 315行抛出的是 INode,而不是IPublicModelNode
https://github.com/alibaba/lowcode-engine/blob/0f02080035923db7b5c39644ad4a41da0f56c892/packages/designer/src/document/node/node-children.ts#L274-L316
