### ISSUE TITLE
添加第 2 个弹窗无法显示

### ISSUE THREAD

**Issue by cnlon** [alibaba/lowcode-engine#2578]
问题描述：添加第 2 个弹窗无法显示
复现步骤：[官方示例](https://lowcode-engine.cn/demo/demo-general/index.html) 也能复现，连续拖入 2 个高级对话框，第 2 个无法显示

**Comment by cnlon** [comment]
拖入第二个组件后组件被 LeafWrapper 了 2 次，导致渲染 2 个弹窗（然后估计是 key 相等或什么原因导致了没有显示）
![image](https://github.com/alibaba/lowcode-engine/assets/13602053/a8707043-4b27-4f6c-b355-b438ee9f59fa)


删除这行代码可以恢复正常，但不知此前添加这样代码是要解决什么问题？ @liujuping @rainke
https://github.com/alibaba/lowcode-engine/commit/ca6fe7c335b5035eba18a8681a4bb7a5ccac83b3#diff-4c87f65a8355f4a627d1577c405163e703dc9040db04fdc5a3f16e9fd89cc22dR619
![image](https://github.com/alibaba/lowcode-engine/assets/13602053/a7181c4a-2644-4864-a71f-88df58343781)

**Comment by liujuping** [comment]
这里的组件被 Hoc 覆盖了，导致出现了问题。已经提 PR 进行修复了。
