### ISSUE TITLE
在win系统下使用wsl启动脚手架工程无法 watch 文件改动进行重新编译，每次修改都要重新run lowcode:dev

### ISSUE THREAD

**Issue by Jveen-D** [alibaba/lowcode-engine#258]

**Comment by WinKi7** [comment]
我也遇到，有点麻烦，run一次要好久，物料经常需要调整， @alilc/lowcode-material-parser 解析本地组件这个方式也引用不下来

**Comment by eternalsky** [comment]
这个问题我来跟进一下

**Comment by eternalsky** [comment]
这个应该检测到 WSL 环境后，webpack 里开启 poll 模式就可以了，后面找 win 机器试验一下。

**Comment by eternalsky** [comment]
plugin/setter 的开发已经修复了，更新到最新的 build-plugin-alt 就可以了。 component 的还在修复

**Comment by eternalsky** [comment]
component 也已经修复了，更新到最新的 build-plugin-lowcode 就可以了。

**Comment by fuzi1996** [comment]
提个醒,通过`wsl`运行`/mnt`下挂载的`win`下的项目,目前也是无法监听到变动从而重新构建的
