### ISSUE TITLE
低代码组件在编辑器中表现正常, 但在ReactRenderer预览时不能触发内部绑定的事件

### ISSUE THREAD

**Issue by jeffery-zhang** [alibaba/lowcode-engine#2582]
## **Describe the bug (required)** / **详细描述 bug（必填）**

项目中利用低代码引擎和基础物料构建的低代码组件, 在构建时有自己的自定义函数, 并且绑定到按钮上点击在控制台中打印一条信息, 在页面编辑的项目中使用时, 在编辑态的渲染器中显示正常, 且点击低代码组件中的按钮能够在控制台打印出正确的信息, 但是在预览态的ReactRenderer中, 该低代码组件能够展示正确的样式 点击按钮却没有任何响应

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

这里有demo: https://github.com/jeffery-zhang/editor-demo.git

Steps to reproduce the behavior: / 详细复现步骤：

1. 将模板01组件拖入画布
![2cd37d64a1d6cfd121314f6db81a760](https://github.com/alibaba/lowcode-engine/assets/40761915/ac489831-aa2b-442a-96f2-3f391a697526)

2. 组件的属性"姓名"输入一个字符串, 能够正确显示在画布中(通过在低代码组件自己的类中定义的函数返回值, 绑定到文本组件上), 并且点击按钮后再控制台能够看到打印信息
![image](https://github.com/alibaba/lowcode-engine/assets/40761915/6e73b2d6-ff59-479c-b958-13980d9fb4ca)

3. 点击预览进入预览页面可以看到组件正常显示, 但是没有展示绑定的文本, 并且点击按钮也没有打印信息(预览态下的组件转换方式参考官方低代码组件demo中的parseAssets函数实现)
![image](https://github.com/alibaba/lowcode-engine/assets/40761915/582d1d91-925d-4560-96cf-6c208dad2cc0)

4. 并且, 低代码组件内部生命周期componentDidMount中的打印信息在编辑态和渲染态都没有触发

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

预期低代码组件在预览态中的行为和编辑态中保持一致

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - - 1.1.11-beta.2
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - - 1.0.7-beta.4
 - Browser [e.g. chrome, safari] / 浏览器版本
 - - chrome
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**

在低代码组件的描述中(即assets的packages中), 低代码组件中的文本组件的文本绑定的是内部定义的getName函数, 按钮点击事件绑定的是test函数
其中文本组件的属性如果直接绑定 this.props.name 则可以在预览页面正常显示
![image](https://github.com/alibaba/lowcode-engine/assets/40761915/92aa7e4a-79c0-4fb5-8685-7827163fcb57)
![image](https://github.com/alibaba/lowcode-engine/assets/40761915/6844cebd-bd8f-4069-87e9-5adb51be5522)
![image](https://github.com/alibaba/lowcode-engine/assets/40761915/0a7643b4-cd80-443b-bf2a-34e22e1ebb71)

**Comment by jeffery-zhang** [comment]
编辑态和渲染态不一致的问题已经解决了, 但低代码组件自身的生命周期不执行的问题依然存在

**Comment by liujuping** [comment]
低代码组件自身的生命周期不执行的问题，最新的 beta 版本已经修复，近期会发布正式版本。
