### ISSUE TITLE
【BUG】造物平台产出的组件，生命周期不执行？

### ISSUE THREAD

**Issue by zhuyuanmin** [alibaba/lowcode-engine#2585]
造物平台产出的组件，生命周期不执行

**Comment by zhuyuanmin** [comment]
![962DD398-A2B7-4957-9A30-4AFC4C3ED362](https://github.com/alibaba/lowcode-engine/assets/23226876/fee68a87-f2a9-4a9c-8869-d028983a480b)


![729446FA-ADE2-4211-9605-FA1B786ADC1D](https://github.com/alibaba/lowcode-engine/assets/23226876/43ba2385-224c-4e1f-aeb7-bb51909dc19e)

看图是没有console.log 输出

**Comment by ctcx** [comment]
+1

**Comment by ctcx** [comment]
@JackLian @liujuping @LeoYuan

**Comment by jeffery-zhang** [comment]
+1
