### ISSUE TITLE
有没有多页面配置、路由配置的更新计划呢？

### ISSUE THREAD

**Issue by crossinfo** [alibaba/lowcode-engine#259]
目前单页面生成代码，一个完整的项目得手动组合多个页面。

**Comment by mark-ck** [comment]
兄弟，可以看看我现场开发多页面插件的直播回放：https://www.bilibili.com/video/BV17a411i73f ，评论区有示例项目的地址

路由配置这部分还没涉及到，可以关注我直播间，后面也会演示开发这部分内容
