### ISSUE TITLE
物料的ignoreDefaultValue 支持boolean类型

### ISSUE THREAD

**Issue by eightHundreds** [alibaba/lowcode-engine#2590]
# 背景

被标记为`ignoreDefaultValue`的属性，在低代码渲染时并不会修改到组件的props上。

![image](https://github.com/alibaba/lowcode-engine/assets/18695431/945ee7f7-50d5-40a7-bfdc-52ec77e610bc)

举一个常见的场景:
antd的button的 size属性默认是`middle`， 这里的默认是它的源代码里默认是`size="middle"`。因此开发者不需要特意地对这个属性赋值。
而低代码场景下，由于button物料的size属性的`defaultValue`被设置为`middle` 导致低代码渲染时为button设置了`size="middle"`属性。

这个行为的影响是  
1. 出码结果可读性差，大量冗余的属性赋值
2. 往画布拖入组件时, `onChangeNodeProp`会触发多次

因此该属性对我的业务场景是高频使用，希望他支持boolean类型

# 相关issue

https://github.com/alibaba/lowcode-engine/pull/1720

**Comment by liujuping** [comment]
这种配置方式不能满足诉求吗？另外，这种情况，该 Button 不应该给 size 设置默认值啊。
```
() => false
```

ignoreDefaultValue 主要是提供给某些情况需要设置默认值，某些情况不需要设置默认值的场景。

**Comment by eightHundreds** [comment]
size 的默认值是为了让setter 面板能正常显示.
![image](https://github.com/alibaba/lowcode-engine/assets/18695431/6d6c731c-77b5-4b00-af8f-16996080291f)


如果不给m默认值, 这个radio button 就没有选中态

**Comment by eightHundreds** [comment]
> 这种配置方式不能满足诉求吗？另外，这种情况，该 Button 不应该给 size 设置默认值啊。
> 
> ```
> () => false
> ```
> 
> ignoreDefaultValue 主要是提供给某些情况需要设置默认值，某些情况不需要设置默认值的场景。

这个可以, 就是有点丑, 基本上每个物料都要这么配一下

**Comment by liujuping** [comment]
> size 的默认值是为了让setter 面板能正常显示. ![image](https://user-images.githubusercontent.com/18695431/278581606-6d6c731c-77b5-4b00-af8f-16996080291f.png)
> 
> 如果不给m默认值, 这个radio button 就没有选中态

这个应该把 defaultValue 配置给 Setter 就可以吧。

**Comment by eightHundreds** [comment]
如果给setter 会不会触发 node.setValue?

**Comment by eightHundreds** [comment]
我刚刚测试了下, `ignoreDefaultValue` 也不能解决问题, 设置`()=>true`, setter面板 显示不正确了.

**Comment by liujuping** [comment]
这个问题我们考虑了一下，如果支持配置 setter显示物料属性默认值，但是实际上没有修改 node 的属性。这里有一个隐藏的问题：即依赖物料的默认值，如果物料默认值和 setter 默认值不一致，则会导致物料最终渲染和 setter 的展示不一致。

因此暂时不会支持该能力。

**Comment by liujuping** [comment]
对于问题 「1.出码结果可读性差，大量冗余的属性赋值」，由于出码我们暂时不考虑可读性，主要考虑性能，所以这个问题还好。
对于 问题「2.往画布拖入组件时, onChangeNodeProp会触发多次」，可以直接在 snapshot 里面初始化好对应的默认值，这个值存在的情况就不会再触发 props change 了。
