### ISSUE TITLE
低代码组件的componentDidMount未被执行

### ISSUE THREAD

**Issue by wstown** [alibaba/lowcode-engine#2592]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

使用造物创建了一个低代码组件，在低代码组件的componentDidMount函数内，调用远程接口获取数据然后更新表格内容，
该功能在低代码组件的调试和预览中正常。
但是在demo项目中引入该低代码组件后执行预览，发现componentDidMount函数没有被调用，导致无法更新表格的内容。
直接使用Demo示例中的 [低代码组件](https://lowcode-engine.cn/demo/demo-lowcode-component/index.html)也能复现该问题——低代码组件中的生命周期函数没有被执行。

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

1. 打开官方的 [低代码组件Demo](https://lowcode-engine.cn/demo/demo-lowcode-component/index.html)；
2. 点击预览；
3. 打开浏览器Console面板；
4. 输出的log中没有低代码组件JS代码中的componentDidMount输出；

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

低代码组件中的生命周期函数应该也能被执行到。

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [1.1.2] / 低代码引擎版本
 - AliLowCodeEngineExt version: [1.0.0] / 低代码引擎扩展包版本
 - Browser [chrome, safari] / 浏览器版本

**Comment by ctcx** [comment]
+1

**Comment by jeffery-zhang** [comment]
+1

**Comment by 1ncounter** [comment]
fix bugs with #2681
