### ISSUE TITLE
/lowcode-materials 下的 antd-lowcode-materials 本地 npm run lowcode:dev打开，页面渲染不出来

### ISSUE THREAD

**Issue by LuxinYing11** [alibaba/lowcode-engine#2593]
## **Describe the bug (required)** / **详细描述 bug（必填）**

**问题描述**：根据 GitHub 里 /lowcode-materials 的 readme 操作，本地打开 antd 项目，但页面渲染不出来。页面如下图展示。

**操作步骤**：
   1. npm i -f
   2. npm run lowcode:dev
      - 出现 .tmp 问题，根据 issue #301 解决
   3. 重新 npm run lowcode:dev
      - 页面打开如下图，根据 301里的解决方法 —— 加斜杆和运行 correctNodeModules 也还是没有解决。
![image](https://github.com/alibaba/lowcode-engine/assets/120176023/30d9d1e2-4b98-466c-878f-bf75b1eadaf7)

**Comment by eternalsky** [comment]
已修复，拉最新的代码看看
