### ISSUE TITLE
setter如何区分空和不存在？

### ISSUE THREAD

**Issue by ChiZng** [alibaba/lowcode-engine#2597]
在物料配置中setter如果不配置默认值，直接在设计器中拖入这个组件schema的props是不会有这个属性的。但是如果我在设计器的右侧属性设置中修改了这个属性，就不会在回到这一项属性是不存在的状态。
例如：
antd 的table column的className属性，他是没有默认值的。我在StringSetter中不配置默认值，用户不在设计器的右侧属性设置中操作这一项，最终schema中是不会有className这个属性的。但是一旦我修改了这个属性，就算把值清空在schema中也会存在`className: ''`的这一项。
![image](https://github.com/alibaba/lowcode-engine/assets/27946984/09dc89e5-a77a-4478-8125-2fc403fe1cbc)

有没有什么办法可以方便的区分空和不存在着两种状态。

**Comment by liukairui** [comment]
#2250

**Comment by liujuping** [comment]
主要的问题是识别用户期望是空还是不存在，一种是给用户选择，一种是平台自定义，比如为空就相当于不存在。

第一种：可以通过自定义设置器，其中加一个单独的 clear 能力，通过 node 相关的 API 进行清空。https://lowcode-engine.cn/site/docs/api/model/prop#remove

第二种：删掉为空的 props 就行。比如用这个 API 删掉，https://lowcode-engine.cn/site/docs/api/project#addpropstransducer

**Comment by ChiZng** [comment]
明白了👍
