### ISSUE TITLE
点击撤销按钮，画布崩溃，导致整个画布不能操作

### ISSUE THREAD

**Issue by yiRain123** [alibaba/lowcode-engine#2599]
使用自然布局，添加文本、输入框、密码框等，点击撤销按钮，画布崩溃，且前端有报错
![image](https://github.com/alibaba/lowcode-engine/assets/139101387/b53f5154-1a1e-4e13-bc21-4fb6737aff6c)

**Comment by zhangzhanbang** [comment]
https://github.com/alibaba/lowcode-engine/issues/2061

**Comment by yiRain123** [comment]
@zhangzhanbang 我看着2061说在跟进，大约啥时候能有方案解决呀

**Comment by eternalsky** [comment]
此问题已修复。
