### ISSUE TITLE
是否支持vue

### ISSUE THREAD

**Issue by fuxiaohui** [alibaba/lowcode-engine#26]

**Comment by h7ml** [comment]
自己整个[vuera](https://www.npmjs.com/package/vuera) 集成进去，不就支持了吗

**Comment by LeoYuan** [comment]
官方应该不会提供 vue 的渲染器，有两个可行方案：
1. 参考 react-renderer 和 react-simulator-renderer，写相应的 vue-renderer 和 vue-simulator-renderer；
2. 将 vue 组件转成 react 组件，在编辑态做所见即所得，运行态还是用 vue-renderer 去做实时协议解析或者用出码框架写出码流程~
