### ISSUE TITLE
请问金蝉大佬，@alifd/lowcode-preset-plugin npm包 404报错 请修复一下

### ISSUE THREAD

**Issue by lijiaxu1996** [alibaba/lowcode-engine#261]
1. 使用npm init @alilc/element 初始化脚手架
2. index.jsx找不到这个依赖
![image](https://user-images.githubusercontent.com/59685169/161590328-460f0ee7-3a5d-4db1-8294-e1f07984878c.png)
3.npm i安装提示报错
![image](https://user-images.githubusercontent.com/59685169/161590499-4c55702d-6991-4180-b26e-e0bdb2d06ef4.png)
4.查看npmjs.org是存在这个包的，但是我npm（淘宝源）下载不了
![image](https://user-images.githubusercontent.com/59685169/161590737-47929445-bd94-4765-a217-06eef3b1ed44.png)

**Comment by mark-ck** [comment]
https://npmmirror.com/package/@alifd/lowcode-preset-plugin
![image](https://user-images.githubusercontent.com/44559440/161684014-77f68bb5-d091-43ec-8208-8bec522849d3.png)

cnpm 也有的，看看是不是版本号不对

**Comment by lijiaxu1996** [comment]
> https://npmmirror.com/package/@alifd/lowcode-preset-plugin ![image](https://user-images.githubusercontent.com/44559440/161684014-77f68bb5-d091-43ec-8208-8bec522849d3.png)
> 
> cnpm 也有的，看看是不是版本号不对

![image](https://user-images.githubusercontent.com/59685169/161697444-22e6d3b6-9da1-43de-a637-9ff075d06487.png)
也是不行的

**Comment by mark-ck** [comment]
> > https://npmmirror.com/package/@alifd/lowcode-preset-plugin ![image](https://user-images.githubusercontent.com/44559440/161684014-77f68bb5-d091-43ec-8208-8bec522849d3.png)
> > cnpm 也有的，看看是不是版本号不对
> 
> ![image](https://user-images.githubusercontent.com/59685169/161697444-22e6d3b6-9da1-43de-a637-9ff075d06487.png) 也是不行的

哦，那这个确实有点问题，但是我暂时也没办法处理，因为这个插件并不是对外的，里面耦合了很多内部判断的逻辑；
我建议别用这个插件吧，可以自己根据 demo 写一个，它本质上就是引擎+常用插件的整合。
