### ISSUE TITLE
1.2.1 没有声明文件

### ISSUE THREAD

**Issue by try2020-code** [alibaba/lowcode-engine#2611]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
![image](https://github.com/alibaba/lowcode-engine/assets/84961646/21bdf422-f5a3-4274-8904-fa937c691300)

我确定是按官方的 方安装依懒包的。进源码看了。的确没有 现在不得不降级
---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by try2020-code** [comment]
有什么变化. 也没有相关文档.尝试按源码中写了. 发现之前的全局事件用不了

**Comment by liujuping** [comment]
具体是什么问题？TS 定义不会全局事件用不了。

**Comment by try2020-code** [comment]
如果用 declare const event: Event;  就不会报错.但运行扔指向react 的event 类. 如果不用declare 哪不管怎么起别名都 会报错 详见我发的图片

**Comment by try2020-code** [comment]
> 具体是什么问题？TS 定义不会全局事件用不了。

如果用 declare const event: Event; 就不会报错.但运行扔指向react 的event 类. 如果不用declare 哪不管怎么起别名都 会报错 详见我发的图片

**Comment by try2020-code** [comment]
> 具体是什么问题？TS 定义不会全局事件用不了。

另外 见官方提供 的https://github.com/alibaba/lowcode-demo  运行之后也是会因为没有声明文件而报错的,  我查了很多资料还是没有解决这个问题  见我发的另一个issue https://github.com/alibaba/lowcode-engine/issues/2626   , 我尝试把导入从engine 改成shell 但就会失去Event 类. 旧版本是"event"   但一导入就出问题, 起别名也好. 动态import都 试了都 会指向react的Event 我确定我的环境没有问题. 因为旧版本也正常.而且是通过官方提供的工具生成的项目

**Comment by liujuping** [comment]
你可以试一下最新的 beta 版本，这个版本已经把声明文件加上了。

**Comment by try2020-code** [comment]
> 你可以试一下最新的 beta 版本，这个版本已经把声明文件加上了。

谢谢你,  希望可以加个联系方式. 付费提供技术支持.  这边走太多坑了.

**Comment by liujuping** [comment]
我们只有企业级别的付费项目，UIPaaS：https://uipaas.net/home
