### ISSUE TITLE
设置器的 label 支持隐藏吗

### ISSUE THREAD

**Issue by lavyun** [alibaba/lowcode-engine#2614]
![image](https://github.com/alibaba/lowcode-engine/assets/22797898/d31adc2a-aaa4-47d1-ae9b-dda15eef1643)
我想让这个自定义setter 宽度展示成 100%，红框处支持隐藏吗

**Comment by liujuping** [comment]
https://lowcode-engine.cn/site/docs/guide/expand/editor/metaSpec#plain
