### ISSUE TITLE
组件高度不断增加的bug

### ISSUE THREAD

**Issue by huci-lingmao** [alibaba/lowcode-engine#2619]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

组件在一点一点不断变高

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 重置页面；
3. 删除页面中的所有元素；
4. 在设计器中增加一个容器；
5. 将容器垂直拆分一次；
6. 在左边容器中拖入一个面积图；

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

页面正常显示

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

![111](https://github.com/alibaba/lowcode-engine/assets/142567585/fe105dde-4c03-42b0-8fcc-19e57aa0b79e)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
在线demo页面 版本1.0.0

**Comment by JackLian** [comment]
参考这个 https://github.com/alibaba/lowcode-engine/issues/197
