### ISSUE TITLE
高级表格能否提供一下选中行事件呀

### ISSUE THREAD

**Issue by taolei1990** [alibaba/lowcode-engine#262]
流程：
1. 拖拽两个高级表格出来
2. 第一个表格添加单选
3. 第二个表格添加操作列设置为对照按钮（如下图）
4. 
![image](https://user-images.githubusercontent.com/23173640/161880520-15294feb-d4ca-48de-8fba-04607d11ae40.png)

5.  表格单选缺失一个选中事件（如下图）
![image](https://user-images.githubusercontent.com/23173640/161880721-d62a90ac-284e-44b5-823a-ceadc655c641.png)

希望能提供一下选中行事件

**Comment by ah-wq** [comment]
精选组件暂时不维护的，自己写一个满足自身需求的表格吧！

**Comment by mark-ck** [comment]
对于物料的问题，如果是有 bug 我们会排期解决，如果是功能需求我们基本上不会接收，并且整体排期迭代会比较慢，这个是由于内部资源调配的问题，望理解。
