### ISSUE TITLE
线上环境addBuiltinComponentAction中的conten.icon为Dropdown，action 函数不触发

### ISSUE THREAD

**Issue by Super-Rz** [alibaba/lowcode-engine#2622]
在设计器辅助层增加一个Fusion Dropdown到的action，点击Dropdown中的子项时，action函数不触发，本地环境是可以的，请问是什么原因呢，有无其他方案？

**Comment by JackLian** [comment]
补充个demo吧

**Comment by Super-Rz** [comment]
material.addBuiltinComponentAction({
          name: 'settetSwitch',
          content: {
            icon:  (
              <Dropdown
              trigger={<Icon type="switch" size="small" />}
              onVisibleChange={() => store.set('setterValue', null)}
              triggerType={['hover']}
            >
              <div>
                {setterModel.map((item) => (
                  <div
                    className="component-select-item"
                    onClick={() => {
                      store.set('setterValue', item.value);
                    }}
                  >
                    {item.label}
                  </div>
                ))}
              </div>
            </Dropdown>
            ),
            title: 'Setter切换',
            action(node: Node) {
              // 本地环境可以触发，线上不行
              const setter = store.get('setterValue');
              if (setter) {
                node?.setPropValue('setter.componentName', setter);
                node?.document?.selection.remove(node.id);
              }
            },
          },
          condition: (node: Node) => {
            return node.componentMeta?.componentName === 'Setters';
          },
          important: true,
        });
