### ISSUE TITLE
渲染时，文本前后空格的问题

### ISSUE THREAD

**Issue by beautiful-boyyy** [alibaba/lowcode-engine#2624]
引擎会对设置器传过来的string类型的变量进行trim操作，个人认为没必要。string主要来源于string setter(input组件) 或者是 textArea setter(textArea组件)，如果trim的话，将会使 textArea不能首行缩进，而且对于input来说，前后存在空格并不是什么大问题。

**Comment by JackLian** [comment]
也可以提个pr，给string setter增加一个配置项来控制是否trim

**Comment by beautiful-boyyy** [comment]
> 也可以提个pr，给string setter增加一个配置项来控制是否trim

Ok，我搞搞

**Comment by beautiful-boyyy** [comment]
> 也可以提个pr，给string setter增加一个配置项来控制是否trim

可是这个是引擎的行为
<img width="1161" alt="Screenshot 2023-11-09 at 11 05 42" src="https://github.com/alibaba/lowcode-engine/assets/66351806/91f24182-0942-4f77-a293-48c7322b1c44">

**Comment by liujuping** [comment]
@1ncounter 看一下渲染模块。这里我还发现两个其他的问题。

问题 1：packages/renderer-core/src/utils/common.ts 这里的 checkPropTypes 函数好像有问题。

![image](https://github.com/alibaba/lowcode-engine/assets/11935995/67d2ef24-7717-42da-93e7-331174052ccc)

比如下面的单测没有办法通过
```
it('should validate correctly with valid prop type', () => {
  const result = checkPropTypes(123, 'age', 'number', 'TestComponent');
  expect(result).toBe(true);
});
```

问题 2：packages/renderer-core/src/renderer/base.tsx 这里的 propType 一直是 undefined。

![image](https://github.com/alibaba/lowcode-engine/assets/11935995/8e3f9019-5392-4a9b-ba60-a5fa0036232d)

比如综合场景下的 Message 组件有定义 propType。

![image](https://github.com/alibaba/lowcode-engine/assets/11935995/3361968c-4094-44cf-a91e-bdda769d7ffb)

看看是代码问题还是使用问题。

**Comment by beautiful-boyyy** [comment]
> @1ncounter 看一下渲染模块。这里我还发现两个其他的问题。
> 
> 问题 1：packages/renderer-core/src/utils/common.ts 这里的 checkPropTypes 函数好像有问题。
> 
> ![image](https://user-images.githubusercontent.com/11935995/282639856-67d2ef24-7717-42da-93e7-331174052ccc.png)
> 
> 比如下面的单测没有办法通过
> 
> ```
> it('should validate correctly with valid prop type', () => {
>   const result = checkPropTypes(123, 'age', 'number', 'TestComponent');
>   expect(result).toBe(true);
> });
> ```
> 
> 问题 2：packages/renderer-core/src/renderer/base.tsx 这里的 propType 一直是 undefined。
> 
> ![image](https://user-images.githubusercontent.com/11935995/282640564-8e3f9019-5392-4a9b-ba60-a5fa0036232d.png)
> 
> 比如综合场景下的 Message 组件有定义 propType。
> 
> ![image](https://user-images.githubusercontent.com/11935995/282640725-3361968c-4094-44cf-a91e-bdda769d7ffb.png)
> 
> 看看是代码问题还是使用问题。

问题2在于调用的时候传了个空对象
![Screenshot 2023-11-14 at 10 17 55](https://github.com/alibaba/lowcode-engine/assets/66351806/3044fbbc-0ee5-4f07-837d-00be969161f7)

**Comment by liujuping** [comment]
@beautiful-boyyy 你的问题应该不存在。

![image](https://github.com/alibaba/lowcode-engine/assets/11935995/e53cd2ab-14c1-486b-a5de-62a68e8d8c3b)

![image](https://github.com/alibaba/lowcode-engine/assets/11935995/497b6a41-511f-4138-a454-5859c553efcc)

对于 props 和 children 都是正常处理的，你截图的地方只是做了 check，没有直接使用该值。

**Comment by liujuping** [comment]
> @1ncounter 看一下渲染模块。这里我还发现两个其他的问题。
> 
> 问题 1：packages/renderer-core/src/utils/common.ts 这里的 checkPropTypes 函数好像有问题。
> 
> ![image](https://user-images.githubusercontent.com/11935995/282639856-67d2ef24-7717-42da-93e7-331174052ccc.png)
> 
> 比如下面的单测没有办法通过
> 
> ```
> it('should validate correctly with valid prop type', () => {
>   const result = checkPropTypes(123, 'age', 'number', 'TestComponent');
>   expect(result).toBe(true);
> });
> ```
> 
> 问题 2：packages/renderer-core/src/renderer/base.tsx 这里的 propType 一直是 undefined。
> 
> ![image](https://user-images.githubusercontent.com/11935995/282640564-8e3f9019-5392-4a9b-ba60-a5fa0036232d.png)
> 
> 比如综合场景下的 Message 组件有定义 propType。
> 
> ![image](https://user-images.githubusercontent.com/11935995/282640725-3361968c-4094-44cf-a91e-bdda769d7ffb.png)
> 
> 看看是代码问题还是使用问题。

问题一已解决，并补充了相关的单测：https://github.com/alibaba/lowcode-engine/pull/2646

**Comment by beautiful-boyyy** [comment]
> @beautiful-boyyy 你的问题应该不存在。
> 
> ![image](https://user-images.githubusercontent.com/11935995/282646292-e53cd2ab-14c1-486b-a5de-62a68e8d8c3b.png)
> 
> ![image](https://user-images.githubusercontent.com/11935995/282646355-497b6a41-511f-4138-a454-5859c553efcc.png)
> 
> 对于 props 和 children 都是正常处理的，你截图的地方只是做了 check，没有直接使用该值。

基础fusion组件demo，拖个button就不行，貌似放在区块才没trim

**Comment by liujuping** [comment]
建议先自查一下，
通过查看预览的 schema，区分一下是 schema 的问题还是其他
通过查看 Element，区分一下是 React 渲染的问题还是渲染器的问题。

**Comment by beautiful-boyyy** [comment]
> 建议先自查一下， 通过查看预览的 schema，区分一下是 schema 的问题还是其他 通过查看 Element，区分一下是 React 渲染的问题还是渲染器的问题。

schema是正常的，element有问题

**Comment by liujuping** [comment]
那这个就是 React 渲染相关的问题了，可以去了解一下。

**Comment by beautiful-boyyy** [comment]
> 那这个就是 React 渲染相关的问题了，可以去了解一下。

你意思是不是引擎的问题？？？

**Comment by liujuping** [comment]
可以写一个 React 组件，前后带上空格，看一下。

**Comment by beautiful-boyyy** [comment]
> 可以写一个 React 组件，前后带上空格，看一下。

<img width="1512" alt="Screenshot 2023-11-15 at 10 49 58" src="https://github.com/alibaba/lowcode-engine/assets/66351806/cd663b31-4403-45ae-8f90-b655fd84cc5d">
react是保留空格的

**Comment by beautiful-boyyy** [comment]
> 可以写一个 React 组件，前后带上空格，看一下。

<img width="1512" alt="Screenshot 2023-11-15 at 10 49 58" src="https://github.com/alibaba/lowcode-engine/assets/66351806/86905a23-3f20-496f-a4b8-a1bbfe88c8c9">
react渲染没问题，感觉是引擎解析schema的逻辑出了问题

**Comment by liujuping** [comment]
> element

那这里说的 element 的问题，截图详细说一下。或者提供可以直接导入复现的 schema。

**Comment by beautiful-boyyy** [comment]
> > element
> 
> 那这里说的 element 的问题，截图详细说一下。或者提供可以直接导入复现的 schema。

<img width="1508" alt="Screenshot 2023-11-15 at 11 00 24" src="https://github.com/alibaba/lowcode-engine/assets/66351806/d4838b20-d21d-4417-a10d-d8ce821099df">

**Comment by liujuping** [comment]
> > > element
> > 
> > 
> > 那这里说的 element 的问题，截图详细说一下。或者提供可以直接导入复现的 schema。
> 
> <img alt="Screenshot 2023-11-15 at 11 00 24" width="1508" src="https://user-images.githubusercontent.com/66351806/282991136-d4838b20-d21d-4417-a10d-d8ce821099df.png">

@1ncounter 看了一下，的确有这个问题。可以排查一下是组件问题还是渲染器的问题。

**Comment by 1ncounter** [comment]
@liujuping  看了一下这个用例的文本显示问题原因有两个：一方面在__getComponentProps方法中调用 __parseProps 方法解析 props 时的将字符串 trim 掉了，另外将第一点的trim取消之后，button也进行了字符串的trim。

**Comment by liujuping** [comment]
> @liujuping 看了一下这个用例的文本显示问题原因有两个：一方面在__getComponentProps方法中调用 __parseProps 方法解析 props 时的将字符串 trim 掉了，另外将第一点的trim取消之后，button也进行了字符串的trim。

可以先解决第一个问题，组件的问题可以让用户/物料侧解决。

**Comment by 1ncounter** [comment]
> @beautiful-boyyy 你的问题应该不存在。
> 
> ![image](https://user-images.githubusercontent.com/11935995/282646292-e53cd2ab-14c1-486b-a5de-62a68e8d8c3b.png)
> 
> ![image](https://user-images.githubusercontent.com/11935995/282646355-497b6a41-511f-4138-a454-5859c553efcc.png)
> 
> 对于 props 和 children 都是正常处理的，你截图的地方只是做了 check，没有直接使用该值。

@liujuping  奇怪的是我并没有复现这个例子。始终都是被 trim 过的

**Comment by 1ncounter** [comment]
> > > @liujuping 看了一下这个用例的文本显示问题原因有两个：一方面在__getComponentProps方法中调用 __parseProps 方法解析 props 时的将字符串 trim 掉了，另外将第一点的trim取消之后，button也进行了字符串的trim。
> > 
> > 
> > 可以先解决第一个问题，组件的问题可以让用户/物料侧解决。
> 
> 我来提个PR吧，不过我比较不解的是，为什么demo-general中放在自由布局里的button没问题...

@beautiful-boyyy  因为需要 render 的 children 是先经过处理的，props中的 children 会被这个 children 覆盖。
![image](https://github.com/alibaba/lowcode-engine/assets/19562558/a9cad84a-f146-419a-b990-5461bf0c7e5c)
所以原先的处理是 children 会先进行parse不会被 trim，但是 props中的空格 会被 parseProps tirm 掉。
@liujuping  知悉一下

**Comment by 1ncounter** [comment]
fixed with pr[2654](https://github.com/alibaba/lowcode-engine/pull/2654)
