### ISSUE TITLE
1.2.2beta3版本的export declare type Node = designerCabin.Node;循环依懒导致类型丢失

### ISSUE THREAD

**Issue by try2020-code** [alibaba/lowcode-engine#2631]
## **Describe the bug (required)** / **详细描述 bug（必填）**
import { Node, event } from '@alilc/lowcode-engine';

Node.xxx 没有任何提示. 经检查是 export * from './document';->export * from './node';->export * from './node'; 缺失或或循环导入无效

![image](https://github.com/alibaba/lowcode-engine/assets/84961646/5fa48f27-54dd-4d6c-ba1e-cf8a14180a46)

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by liujuping** [comment]
import { Node, event } from '@alilc/lowcode-engine';

这里为什么要使用 Node？类型定义从 '@alilc/lowcode-types' 里面引入。

@alilc/lowcode-engine 里面没有暴露 Node 相关的 API。

**Comment by try2020-code** [comment]
> import { Node, event } from '@alilc/lowcode-engine';
> 
> 这里为什么要使用 Node？类型定义从 '@alilc/lowcode-types' 里面引入。
> 
> @alilc/lowcode-engine 里面没有暴露 Node 相关的 API。

官方demo里也是从这引入...  至于应用场景 很多呢. setter 是最需要的  我尝试用types引入试

**Comment by try2020-code** [comment]
> import { Node, event } from '@alilc/lowcode-engine';
> 
> 这里为什么要使用 Node？类型定义从 '@alilc/lowcode-types' 里面引入。
> 
> @alilc/lowcode-engine 里面没有暴露 Node 相关的 API。

![image](https://github.com/alibaba/lowcode-engine/assets/84961646/9835126c-7a72-468c-a66a-1534a20f5c6b)

types里没有相关导出哈。。 只能从engine里引入。 旧版本的从engine里引入时有类型的。。。 的确是存在循环引入问题的。希望大神仔细检查

**Comment by try2020-code** [comment]
> > import { Node, event } from '@alilc/lowcode-engine';
> > 这里为什么要使用 Node？类型定义从 '@alilc/lowcode-types' 里面引入。
> > @alilc/lowcode-engine 里面没有暴露 Node 相关的 API。
> 
> ![image](https://user-images.githubusercontent.com/84961646/281931514-9835126c-7a72-468c-a66a-1534a20f5c6b.png)
> 
> types里没有相关导出哈。。 只能从engine里引入。 旧版本的从engine里引入时有类型的。。。 的确是存在循环引入问题的。希望大神仔细检查

经过新一轮研究。发现shell里引入正常

**Comment by liujuping** [comment]
看你具体用于干什么，比如 Node 的类型定义来源于  '@alilc/lowcode-types' 中的 IPublicModelNode。

shell 和 engine 里面导出的 Node 都是非预期的，不建议使用

**Comment by try2020-code** [comment]
> 看你具体用于干什么，比如 Node 的类型定义来源于 '@alilc/lowcode-types' 中的 IPublicModelNode。
> 
> shell 和 engine 里面导出的 Node 都是非预期的，不建议使用

就是设计器里的普通组件节点啊

**Comment by liujuping** [comment]
说清楚引入之后用来干什么的？

**Comment by try2020-code** [comment]
> > 看你具体用于干什么，比如 Node 的类型定义来源于 '@alilc/lowcode-types' 中的 IPublicModelNode。
> > shell 和 engine 里面导出的 Node 都是非预期的，不建议使用
> 
> 就是设计器里的普通组件节点啊

如设计辅助扩展
`
const addBindBizMemberAction = (ctx: IPublicModelPluginContext) => {
    return {
        async init() {
            ctx.material.addBuiltinComponentAction({
                name: 'hello1',
                content: {
                    icon: <SetterBuiltin />,
                    title: '设置',
                    action(node: Node) {
                        event.emit('BizControlSetter.show', node);
                    },
                },
                condition: (node: Node) => {
                    return true; //node.componentMeta.componentName === 'NextTable';
                },
                important: true,
            });

            //注册setter
            const { setters } = ctx;

            setters.registerSetter('BizControlSetter', BizControlSetter);
        },
    };
};
addBindBizMemberAction.pluginName = 'addBindBizMemberAction';
export default addBindBizMemberAction;
`  这里面的 condition 中的参数 Node 就是engine 里的不是么

**Comment by liujuping** [comment]
这个是类型定义，用 IPublicModelNode，从 '@alilc/lowcode-types'  里面引入。

**Comment by liujuping** [comment]
这块我们的文档有点滞后，我更新一下。
