### ISSUE TITLE
自定义物料，同时自动生成了意外的meta.tsx

### ISSUE THREAD

**Issue by bincooo** [alibaba/lowcode-engine#2632]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

如标题所诉，执行`yarn lowcode:dev`启动后，在lowcode目录中自动生成一个`icon-box`目录；
但实际上，我只定义了一个`icon`:
<img width="201" alt="Screenshot 2023-11-10 at 12 54 20" src="https://github.com/alibaba/lowcode-engine/assets/36452456/7c9f8d2c-858a-4d35-bd4d-051a81a8dfc9">
页面也多出了一个选项（图标名称的为我定义的）：
<img width="257" alt="Screenshot 2023-11-10 at 12 55 25" src="https://github.com/alibaba/lowcode-engine/assets/36452456/a1238afa-c4ab-4ce5-8563-714b681fcb2f">
删除无效，每次启动依旧自动生成该目录

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by bincooo** [comment]
貌似是src导出的组件会和lowcode的目录重合，命名不一样就会生成？
但是为什么group目录我没有定义任何组件也生成了....

**Comment by eternalsky** [comment]
会自动解析 src 下导出的组件，如果 lowcode 里没有对应的，就会自动生成。你也可以关闭此功能。但后续的 meta 初始化就需要你自己手动来完成。

**Comment by bincooo** [comment]
怎么关闭呢

**Comment by bincooo** [comment]
哦，找到了
