### ISSUE TITLE
怎样脱离组件库包在自身添加源码组件

### ISSUE THREAD

**Issue by try2020-code** [alibaba/lowcode-engine#2635]
## **Describe the bug (required)** / **详细描述 bug（必填）**

起因： 因为非团队开发，用 官方（https://lowcode-engine.cn/site/docs/guide/quickStart/start#%E5%BC%80%E5%8F%91%E4%B8%80%E4%B8%AA%E8%87%AA%E5%AE%9A%E4%B9%89%E7%89%A9%E6%96%99） 的说明来另外创建一个组件库项目来调试后发布后再引用到主项目的话。。 就会产生维护成本！ 所以我现在有一个想法就是能像自定义setter 一样 在项目本身就可以创建并通过插件加载， 目前我已经研究过官方组件库编译后的资产包

```
{
  "packages": [
    {
      "package": "lowcode_component",
      "version": "0.1.0",
      "library": "BizComps",
      "urls": [
        "./render/default/view.js",
        "./render/default/view.css"
      ],
      "editUrls": [
        "./view.js",
        "./view.css"
      ],
      "advancedUrls": {
        "default": [
          "./render/default/view.js",
          "./render/default/view.css"
        ]
      },
      "advancedEditUrls": {}
    }
  ],
  "components": [
    {
      "exportName": "LowcodeComponentMeta",
      "npm": {
        "package": "lowcode_component",
        "version": "0.1.0"
      },
      "url": "./meta.js",
      "urls": {
        "default": "./meta.js"
      },
      "advancedUrls": {
        "default": [
          "./meta.js"
        ]
      }
    }
  ],
  "ignoreComponents": {}
}
```
看原理 是可以通过  material.loadIncrementalAssets api来动态加载资产包的， 但里面的 view 和 library（特别这个） 并不知道生成原理 ， 所以希望提供个思路。。或文档什么的， 好实现我的需求

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by liujuping** [comment]
首先，这是一个名为 view.js 的 JavaScript 文件。一旦加载完成，我们可以通过 window.libraryName 来访问其中的库。在这里，libraryName 对应的就是我们在配置中设置的库名。

举个例子，如果我们设置 library 为 'React'，那么我们可以通过 window.React 来访问 React 库。实现这个功能我们通常会使用一些打包工具，比如 webpack，并且结合 webpack 的库配置功能来完成。

**Comment by try2020-code** [comment]
> 首先，这是一个名为 view.js 的 JavaScript 文件。一旦加载完成，我们可以通过 window.libraryName 来访问其中的库。在这里，libraryName 对应的就是我们在配置中设置的 library。
> 
> 举个例子，如果我们设置 library 为 'React'，那么我们可以通过 window.React 来访问 React 库。实现这个功能我们通常会使用一些打包工具，比如 webpack，并且结合 webpack 的 library 配置功能来完成。

最终我的目标就是我想要手动去生成Assets  给  material.loadIncrementalAssets ，哪么有没有view.js 非压缩的ts呢。 给个我研究研究

**Comment by liujuping** [comment]
目前没有示例，可以根据原理研究一下。
