### ISSUE TITLE
@alilc/element 创建的组件库怎样往Render(渲染模块)中注入appHelper

### ISSUE THREAD

**Issue by try2020-code** [alibaba/lowcode-engine#2637]
## **Describe the bug (required)** / **详细描述 bug（必填）**
@alilc/element 创建的组件库怎样往Render(渲染模块)中注入appHelper  我尝试向 .tmp 的 preview.jsx 加入appHelper
![image](https://github.com/alibaba/lowcode-engine/assets/84961646/c43e13d8-85b5-4057-ae49-54ba10c511bd)

但发现一刷新就会变回原来的样子.也就是编辑后会被项目覆盖掉.. 请问该 在哪里修改呢

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by try2020-code** [comment]
研究了下源码..发现固定死了..希望这个得改进

**Comment by try2020-code** [comment]
其实我的最终目标就是把 渲染模块做为一个物料.. 然后本质就是模块怎样拿到父组件(渲染模块) 的props

**Comment by liujuping** [comment]
正常一个 React 组件怎么获取父组件的 props 这里就怎么获取。
