### ISSUE TITLE
应用级引擎 没有Schema

### ISSUE THREAD

**Issue by Zmaxtm** [alibaba/lowcode-engine#2649]
应用级引擎如何设置Schema

**Comment by liujuping** [comment]
应用级设计器，用的还是页面的 schema，只是多了一些概念和功能。具体上层平台怎么整合和处理 schema 都是可以的。

**Comment by Zmaxtm** [comment]
请问怎么设置Schema的内容，api去哪里找?

> 应用级设计器，用的还是页面的 schema，只是多了一些概念和功能。具体上层平台怎么整合和处理 schema 都是可以的。
