### ISSUE TITLE
渲染器内存泄漏

### ISSUE THREAD

**Issue by starsoul666** [alibaba/lowcode-engine#2650]
## **Describe the bug (required)** / **详细描述 bug（必填）**

使用 https://github.com/alibaba/lowcode-demo/blob/main/demo-basic-antd/src/preview.tsx 预览代码，切换加载不同的schema，
之前加载的物料资源没卸载，每切换一次就会重复加载一遍，切换多次以后会导致浏览器卡死

const assetLoader = new AssetLoader();
await assetLoader.load(libraryAsset);

这个代码会导致都次加载物料资源；

渲染器卸载后是否有清楚物料资源的方法？

**Comment by liujuping** [comment]
渲染器目前没有提供清除资源的方法，可以自己实现。
