### ISSUE TITLE
关于demo的运行

### ISSUE THREAD

**Issue by DroganC** [alibaba/lowcode-engine#2657]
demo工程中有个engine-core和engine-core-ext的库，这个库通过npm包引入会报错
这些资源只能和demo一样都通过cdn引入吗

**Comment by DroganC** [comment]
<img width="720" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/32896700/1511e18d-640b-4356-baf0-11eb8f0b6ebe">
不走cdn就会这样

**Comment by DroganC** [comment]
上面那个手动改了之后 还会这样
<img width="775" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/32896700/8a8aa7a2-7949-4aba-beac-1b99c6ad6172">

**Comment by liujuping** [comment]
https://lowcode-engine.cn/site/docs/faq/faq014

这里有说明。
