### ISSUE TITLE
渲染时对 @alifd/next 的强依赖

### ISSUE THREAD

**Issue by arleyGuoLei** [alibaba/lowcode-engine#2676]
![image](https://github.com/alibaba/lowcode-engine/assets/40717741/65d32c8c-ec8e-4695-9cea-c074144b48a3)

`@alilc/lowcode-react-renderer` 渲染模块强依赖 Next.js 感觉不太合理，看了下代码里主要就用到一个 `config-provider` 组件，官方是否可以移除对 `@alifd/next` 在渲染运行时的强依赖或者给一个推荐方案？

```json
{
  "name": "@alilc/lowcode-react-renderer",
  "version": "1.1.4"
}
```

**Comment by liujuping** [comment]
这块应该换成配置会更好。

**Comment by arleyGuoLei** [comment]
> 这块应该换成配置会更好。

没有太理解换配置是什么意思？渲染模块提供一个配置项？

**Comment by liujuping** [comment]
对，这块要考虑向下的兼容性，肯定不能直接删掉，这种情况下，要想去掉 `@alifd/next` 依赖，通过配置的方式来支持比较好。

**Comment by liujuping** [comment]
就算是配置的方式，也得考虑如何上层平台在不需要改动代码的情况下，就能升级到最新版本。

**Comment by arleyGuoLei** [comment]
> 对，这块要考虑向下的兼容性，肯定不能直接删掉，这种情况下，要想去掉 `@alifd/next` 依赖，通过配置的方式来支持比较好。

嗯，是个 break-change 的改动，官方能考虑优化下不 ~ 我不太确定是不是只有我找到的这一处组件依赖，也没深入看用 `config-provider` 的原因

**Comment by liujuping** [comment]
当前，一些业务可能依赖于渲染引擎内置的 config-provider。如果我们在新版本中移除此功能，那么在升级之前，这些业务需要进行必要的调整，以避免兼容性问题，这导致了向后不兼容（break-change）的情况。

对于那些不希望加载整个 Next.js 的业务，可以采取更简洁的方法：只需在 Window 对象上模拟（Mock）一个 Next.js 环境。具体来说，可以简单地在 Window 上挂载一个 Next 对象，而无需加载完整的 Next.js。

鉴于此，除非确有必要，否则我们不建议进行可能导致 break-change 的修改。这样的改动可能会给现有业务带来不必要的复杂性和升级挑战。

**Comment by arleyGuoLei** [comment]
> 当前，一些业务可能依赖于渲染引擎内置的 config-provider。如果我们在新版本中移除此功能，那么在升级之前，这些业务需要进行必要的调整，以避免兼容性问题，这导致了向后不兼容（break-change）的情况。
> 
> 对于那些不希望加载整个 Next.js 的业务，可以采取更简洁的方法：只需在 Window 对象上模拟（Mock）一个 Next.js 环境。具体来说，可以简单地在 Window 上挂载一个 Next 对象，而无需加载完整的 Next.js。
> 
> 鉴于此，除非确有必要，否则我们不建议进行可能导致 break-change 的修改。这样的改动可能会给现有业务带来不必要的复杂性和升级挑战。

理解了，我没考虑业务侧能用 config-provider 来干啥，我也想了 Mock 的方案，晚些我在这里留个 mock 代码

**Comment by liujuping** [comment]
```
import React from 'react';
import { ConfigProvider } from '@alifd/next';
import MyComponent from './MyComponent';

function App() {
  // 定义全局配置，例如主题
  const config = {
    theme: 'dark'
  };

  return (
    <ConfigProvider {...config}>
      {/* ConfigProvider下的所有组件都将应用这些配置 */}
      <MyComponent />
      {/* 其他子组件 */}
    </ConfigProvider>
  );
}

export default App;
```

比如这里的代码可以影响低代码页面的主题。（使用 next.js 组件的低代码页面）

**Comment by arleyGuoLei** [comment]
![image](https://github.com/alibaba/lowcode-engine/assets/40717741/b516436b-35ec-4590-b6fd-abe7d6f42387)

有其他组件依赖，直接进行打包了，不做 external 体积更小一些
