### ISSUE TITLE
@alilc/lowcode-designer/lib/document/node/node.d.ts 丢失

### ISSUE THREAD

**Issue by eightHundreds** [alibaba/lowcode-engine#2677]
https://www.jsdelivr.com/package/npm/@alilc/lowcode-designer?tab=files&path=lib%2Fdocument%2Fnode

有node.js,没有node.d.ts
![image](https://github.com/alibaba/lowcode-engine/assets/18695431/bff81fe6-0d69-44b7-80a3-cd8d44d0472b)

**Comment by liujuping** [comment]
这个对你的项目有什么影响吗？

**Comment by eightHundreds** [comment]
开发体验问题.影响不大.

只是个人理解这个问题修起来比较简单.

**Comment by liujuping** [comment]
什么情况下，会使用到这里的类型定义，可以提供一个示例吗？我需要确定一下。

**Comment by eightHundreds** [comment]
我在替换designer内的simulatorView。会用到一些内部的方法，我绕过了shell层，直接访问IDocument。
// 虽然你们不推荐绕过shell,但这是目前唯一的手段

**Comment by liujuping** [comment]
明白，这块大概率是出现了循环引用，可以帮忙找一下提一下 PR。
