### ISSUE TITLE
在编写组件库项目中,自定义setter引入后报错

### ISSUE THREAD

**Issue by fanwww** [alibaba/lowcode-engine#2679]
## **Describe the bug (required)** / **详细描述 bug（必填）**
![GVA P {@WH XK5Q29P$1MFE](https://github.com/alibaba/lowcode-engine/assets/98572444/55b72413-4f8d-42ca-a70d-544bdc0ee2c3)
![% 5H)4SELI_%{ @USV~Q)DT](https://github.com/alibaba/lowcode-engine/assets/98572444/72b28f6a-2ab7-4ba0-8865-1a5a10438dfd)
![E2A52~P%XUH_4NH% 27 RH](https://github.com/alibaba/lowcode-engine/assets/98572444/7b31b5b5-72a5-4ab1-9ba1-ce43139f397f)
![image](https://github.com/alibaba/lowcode-engine/assets/98572444/078ff695-1519-4146-afe9-d2d48ab70852)

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
拖出colorful-button,由于colorful-button有一项使用自定义setter控制台就会报错
https://github.com/fanwww/lowcode-demo
拉这个仓库代码,运行起来后,把colorful-button拖出来,控制台就会报错
![image](https://github.com/alibaba/lowcode-engine/assets/98572444/aa5424a5-a9d2-4354-9a14-3b598722d890)

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by fanwww** [comment]
![image](https://github.com/alibaba/lowcode-engine/assets/98572444/471e4241-3ef0-4a72-bf90-b2dfbc5f90f1)

这个虽然不用 但是要引入 引入之后就没问题了 不清楚怎么回事

**Comment by eternalsky** [comment]
> ![image](https://user-images.githubusercontent.com/98572444/284809834-471e4241-3ef0-4a72-bf90-b2dfbc5f90f1.png)
> 
> 这个虽然不用 但是要引入 引入之后就没问题了 不清楚怎么回事

怎么会不用，你看看你的 jsx 最终编译出来是什么就知道用不用了。

**Comment by fanwww** [comment]
> > ![image](https://user-images.githubusercontent.com/98572444/284809834-471e4241-3ef0-4a72-bf90-b2dfbc5f90f1.png)
> > 这个虽然不用 但是要引入 引入之后就没问题了 不清楚怎么回事
> 
> 怎么会不用，你看看你的 jsx 最终编译出来是什么就知道用不用了。

我看到编译的时候用到createElement了,这也是我为什么尝试把它引入,但是编写这个文件的时候没有用到,图片上红框内也是未使用状态,虽然知道是怎么回事,但总感觉这种写法有点奇怪

**Comment by eternalsky** [comment]
图片上的红框是未使用状态，这是 ts 的问题，但必须是要写的，具体要写什么，要参考 tsconfig 里的 jsxFactory 的配置。
