### ISSUE TITLE
dataSourceMap挂载到window哪

### ISSUE THREAD

**Issue by pjtian** [alibaba/lowcode-engine#268]
我在物料里面想获取数据源的方法

**Comment by liujuping** [comment]
1, 在设计态和渲染态，dataSourceMap 都是可以自定义传入的，这时候可以在传入之前将其挂在 window 上。（不太推荐）

2, 在写组件的时候，可以穿参数，将 dataSourceMap 作为 props 传入到物料中，物料通过 props.xxx 使用（不用自定义）
