### ISSUE TITLE
[Docs]: Please check if the type notation of array in this picture is correct.

### ISSUE THREAD

**Issue by syy11cn** [alibaba/lowcode-engine#27]
![image](https://user-images.githubusercontent.com/57290456/155111772-64eee311-9d2d-436d-a78e-26a5fcf54c39.png)

I'm not sure whether `Array<SomeType>[]` is written intentionally or by mistake.

Maybe it means `Array<SomeType>` or `SomeType[]`?

URL of the doc: http://lowcode-engine.cn/lowcode .
CDN URL of the pic: https://img.alicdn.com/tfs/TB16BEFeMgP7K4jSZFqXXamhVXa-1456-957.png .

**Comment by LeoYuan** [comment]
um, absolutely it's a mistake, we will fix that~

**Comment by liujuping** [comment]
After discussion we removed the image and the documentation has been updated.
