### ISSUE TITLE
dialog或drawer在编辑器模式下模态视图层不能正常弹出问题

### ISSUE THREAD

**Issue by go-maple** [alibaba/lowcode-engine#270]
1.使用之前issue两个配置
   1).dialog [dialog.json.zip](https://github.com/alibaba/lowcode-engine/files/8439348/dialog.json.zip)
   2).drawer [drawer.json.zip](https://github.com/alibaba/lowcode-engine/files/8439349/drawer.json.zip)
2. 导入上述两个配置中任意一个
3. 在编辑器中将dialog或drawer设置成隐藏模式(下图以drawer)
<img width="1030" alt="image" src="https://user-images.githubusercontent.com/97354215/162113840-141508bd-1989-44d7-b1c8-9a168db19915.png">
编辑器设置成隐藏模式保存以后。预览模式下报错
<img width="1638" alt="image" src="https://user-images.githubusercontent.com/97354215/162114161-bfaa5f2d-417f-422d-8420-e10117ce8830.png">
编辑器设置成显示模式保存以后。预览模式下正常
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/97354215/162114265-6e713419-3337-427a-ae1b-b0d7e629b633.png">
正常显示
<img width="1637" alt="image" src="https://user-images.githubusercontent.com/97354215/162114290-962ed868-ed96-4987-97dd-4eab4943756f.png">
dialog问题也是上面描述类似

**Comment by liujuping** [comment]
![image](https://user-images.githubusercontent.com/11935995/162114741-a951dda5-ffaf-4d12-8945-0396c33b9a1b.png)

**Comment by go-maple** [comment]
![image](https://user-images.githubusercontent.com/97354215/162120546-47a680f3-71e7-4df5-9dbc-15a8c183197b.png)
如图所示 
如下按照步骤步骤操作
1).点击 开启渲染
2).点击设计器隐藏元素(这个时候drawer出问题了)
3).点击 保存到本地
4).点击 预览
5).如下图问题依旧
<img width="1633" alt="image" src="https://user-images.githubusercontent.com/97354215/162120859-3c281866-9abe-4dbe-af74-ed31d9f20173.png">
从逻辑上理解点击设计器隐藏于否开启渲染 这个逻辑要解耦的

**Comment by liujuping** [comment]
确定了一下，现在 demo 这个场景是有问题的，需要处理

**Comment by liujuping** [comment]
最新版本的 demo 已修复该问题
