### ISSUE TITLE
怎么重写一个数据源或者其他leftArea的plugin

### ISSUE THREAD

**Issue by 329697166** [alibaba/lowcode-engine#271]

**Comment by 329697166** [comment]
> 你好 @329697166，由于缺乏必要的信息（如 bug 重现步骤、引擎版本信息 等），无法定位问题，请按照 [issue bug 模板](https://github.com/alibaba/lowcode-engine/blob/main/.github/ISSUE_TEMPLATE/bug-report.md) 补全信息。

![image](https://user-images.githubusercontent.com/8613493/162139984-8c58d34a-14e0-43c9-b8b5-1655df2bf48a.png)
就是我想重写一个数据源,或者plugin放到左侧区域,应该怎么做

**Comment by LeoYuan** [comment]
可以参考文档中的 demo，或者参考 API 里的 skeleton
