### ISSUE TITLE
@alib/build-scripts  地址

### ISSUE THREAD

**Issue by DroganC** [alibaba/lowcode-engine#2720]
大佬 有 @alib/build-scripts  的源码地址吗，这边想做一个参考；

目前只找到了 build-scripts 的，二者有什么区别吗？

**Comment by liujuping** [comment]
![image](https://github.com/alibaba/lowcode-engine/assets/11935995/2556e342-c6cc-4597-b1b0-f7faca0e7000)

https://github.com/ice-lab/build-scripts
