### ISSUE TITLE
lowcode-plugins下的数据源插件跑不起来

### ISSUE THREAD

**Issue by Gllidan** [alibaba/lowcode-engine#273]
## **Describe the bug (required)** / **详细描述 bug（必填）**
根据官方lowcode-plugins-main文档运行项目，出现一系列bug

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
1. 根据要求于plugin-datasource-pane包下执行install
![image](https://user-images.githubusercontent.com/27495460/162201226-73a3f264-0080-43c1-b23f-57767ea88007.png)
2. 执行npm run start
3. 报build-script执行错误
![image](https://user-images.githubusercontent.com/27495460/162204372-f31087cc-bad0-4b53-b352-917939877fdf.png)
4. 切换为node 10.16.0版本 执行 npm i @alib/build-scripts, 安装成功
5. 执行npm run start，提示其他依赖缺失，逐个安装后，start可正常运行
6. 后续报错未能找到demo目录及webpack配置
![1649335918(1)](https://user-images.githubusercontent.com/27495460/162203111-f548719c-785f-41b2-8fc8-c133c3980b52.png)
7. 将根目录lowcode-plugins-main下的demo文件挪至子包后，npm run start 可正常运行，但报js加载出错
![image](https://user-images.githubusercontent.com/27495460/162202926-01c69842-109b-4f05-b387-c20ab622f33b.png)
8. node版本
---
![image](https://user-images.githubusercontent.com/27495460/162204922-51560657-c039-4386-a808-9d9ce43e6b73.png)

English version example：
4. Click on '....'
7. Scroll down to '....'
10. See error

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

**Comment by LeoYuan** [comment]
请通过 npm link 到 demo 项目中来调试~
