### ISSUE TITLE
通过@alilc/lowcode-plugin-set-ref-prop插件设置了refId，如何获取组件实例呢？

### ISSUE THREAD

**Issue by DroganC** [alibaba/lowcode-engine#2732]
大佬，如题；
在设置了refId后，有api能拿到对应的组件实例吗？

**Comment by liujuping** [comment]
这个是给用户用的，使用示例可以看看这个：

https://lowcode-engine.cn/site/docs/demoUsage/makeStuff/dialog#5%E6%8C%89%E9%92%AE%E7%BB%91%E5%AE%9A%E4%BA%8B%E4%BB%B6
