### ISSUE TITLE
【咨询】clearPropValue不能触发prop的change事件，导致functionSetter调用的removeProp不能进到监听里

### ISSUE THREAD

**Issue by zboMa** [alibaba/lowcode-engine#2741]
lowcode-engine@1.1.10
lowcode-engine-ext@1.0.6

functionSetter在移除的时候，内部调用的removeProp，removeProp又调用了Prop类的clearPropValue，这个处理没有触发onChangeNodeProp，导致在处理prop的变更的时候，移除监听不到。

求助：有没有别的方式可以监听到这种变化的处理

**Comment by JackLian** [comment]
描述一下你的场景，想监听什么情况下的什么变化

**Comment by zboMa** [comment]
场景：
table组件中有filter属性，setter类型为FunctionSetter，当filter被修改时，onChangeNodeProp监听获取无误，但是当filter被移除时，无法触发onChangeNodeProp监听，则无法做相应处理。

在监听中，期望获取functionSetter类型的prop变化，包括当functionSetter移除的时候。
