### ISSUE TITLE
线上demo数据源面板，无法新建一个数据源

### ISSUE THREAD

**Issue by andylili21** [alibaba/lowcode-engine#2745]
## **Describe the bug (required)** / **详细描述 bug（必填）**

线上demo数据源面板，无法新建一个数据源

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1. 打开 [demo](https://lowcode-engine.cn/demo/demo-basic-fusion/index.html)；
2. 点击数据源 点击新建；
3. 选择fetch；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；
---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
正常新建一个fetch类型的数据源

---

## **Screenshots (optional)** / **bug 截图（可选）**
<img width="1511" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/101868030/fcde5704-21c0-44fa-8898-bc3366c75968">
---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
Chrome
plugin-datasource-pane

**Comment by JackLian** [comment]
线上已修复
