### ISSUE TITLE
请问下为什么lowcode-engine的源码大多都是class component而不是function component呢

### ISSUE THREAD

**Issue by haloworld007** [alibaba/lowcode-engine#275]
RT，从源码中看到比如说 `Workbench`，`TopArea`、`LeftArea`、`MainArea` 等等，整个设计器的组件基本上都是 class component 去写的，而目前来说 function component 应该是编写 React 组件的主流方式。

问题：
1. 采用 class component 是有什么考虑吗？
2. 如果是历史原因，会有相关的改造计划吗？

**Comment by liujuping** [comment]
引擎研发时 hook 还没出现。目前还没改造计划，有其他优先级更高的事情需要做呢。

有这方面的诉求欢迎 PR 呀～

**Comment by haloworld007** [comment]
> 引擎研发时 hook 还没出现。目前还没改造计划，有其他优先级更高的事情需要做呢。
> 
> 有这方面的诉求欢迎 PR 呀～

好的，感谢回答

**Comment by li9269391** [comment]
期待hook改造~
