### ISSUE TITLE
[BUG] workspace 模式下，打开第二个页面的数据源面板会报错

### ISSUE THREAD

**Issue by zhuyuanmin** [alibaba/lowcode-engine#2756]
官方demo: [https://lowcode-engine.cn/demo/demo-workspace/index.html](https://lowcode-engine.cn/demo/demo-workspace/index.html)

![image](https://github.com/alibaba/lowcode-engine/assets/23226876/dfeb01d6-f0d8-4c52-b502-a87bfc28400c)

**Comment by YSMJ1994** [comment]
Fixed

**Comment by zhuyuanmin** [comment]
请问是在哪个地方解决了？看官方demo还是一样。

**Comment by JackLian** [comment]
线上已经修复了，如果你还是看到一样的，可以提供下复现步骤

**Comment by zhuyuanmin** [comment]
> 线上已经修复了，如果你还是看到一样的，可以提供下复现步骤

**Comment by zhuyuanmin** [comment]
> Fixed

可以问一下是修改的哪里吗？我们公司项目也有这个问题。

**Comment by zhuyuanmin** [comment]
复现步骤：打开线上demo。打开两个页面以上：

点开第一个页面数据源正常：
![image](https://github.com/alibaba/lowcode-engine/assets/23226876/20c2babc-b66d-4ea6-bfa3-283fb8471488)

点开第二个页面数据源就报错：
![image](https://github.com/alibaba/lowcode-engine/assets/23226876/55a94ec9-f1a8-4868-85f3-d74caccc6891)



刷新页面重新操作也是一样。第一个点开的数据源面板正常，第二个之后就不正常了。

**Comment by zhuyuanmin** [comment]
喜大诺奔！！解决了。通过下面帖子解决！

https://github.com/react-dnd/react-dnd/issues/3119

![image](https://github.com/alibaba/lowcode-engine/assets/23226876/0c047d38-94e4-41d1-bd03-8db00f1604e1)
