### ISSUE TITLE
开发物料时, 哪些第三方库会和物料打包到一起?

### ISSUE THREAD

**Issue by wywppkd** [alibaba/lowcode-engine#2760]
如题, 开发物料时, 物料依赖的第三方库没有提供 IIFE 模块, 无法通过 CDN 引入, 想和物料打包到一起怎么操作呢?

**Comment by eternalsky** [comment]
除了跟引擎比较相关的包，如 React、Fusion、Antd 等会被 external，其他都会和物料打包在一起。具体 external 配置，可以看 build-plugin-lowcode 的源码。

**Comment by LeeeeeeM** [comment]
就不能暴露个字段自定义吗，啥东西都看源码，你还开源干啥。我就一个简单需求，把 moment 给 external 出来，做不了
