### ISSUE TITLE
低代码平台LAB，表格分页组件多语言如何设置

### ISSUE THREAD

**Issue by fsinbad** [alibaba/lowcode-engine#2764]
你好，低代码平台LAB，表格分页组件多语言如何设置。
分页组件中的文字“上一页”、“下一页”通过设置分页样式可以不显示文字，但是“总计”这两字无法去除，也无法改成其他语言。
麻烦看一下，谢谢。
![image](https://github.com/alibaba/lowcode-engine/assets/314975/483431e9-51d6-43b3-8adc-380463c1cc3a)

**Comment by woshilaoge** [comment]
@fsinbad 默认组件库内置的多语言设置，默认是中文（zh_CN）和英文（en_US）。不过这个多语言的设置受基础组件库 fusion (next) 影响，和当前页面内组件的属性多语言配置不是一样的设置逻辑。举个例子，这个表格组件可以把分页相关的配置提供一个多语言属性配置，这样这个配置后的属性就可以传入到组件并生效。 不过目前他们读取是全局的多语言配置。

![image](https://github.com/alibaba/lowcode-engine/assets/22810511/a8a27741-9268-415b-8f44-786d4db2c527)
上图是一个英文的效果，需要渲染这个页面时，全局配置英文。即 g_config.local = 'en_US' 。


不过看你目前的场景，一个推荐方案是关闭表格的默认分页配置，手动拖拽一个分组组件，自行搭建一个即可。
至于表格分页读取的全局多语言配置是否可以手动覆盖或修改，这个晚些再给你反馈，需要查下

**Comment by woshilaoge** [comment]
已确认，基础组件库内置的多语言配置，并不支持修改或覆盖。我把这个 issue 转给我们的组件同学，再帮你确认下。

**Comment by woshilaoge** [comment]
-
