### ISSUE TITLE
设置器配置的 defalutValue 属性，会被同步到页面协议里面

### ISSUE THREAD

**Issue by lhbxs** [alibaba/lowcode-engine#2775]
<img width="471" alt="截屏2023-12-14 下午7 43 51" src="https://github.com/alibaba/lowcode-engine/assets/43236919/2f9216cb-eb8f-4028-8e7e-47ecb259685f">

组件配置
{
    name: 'showHeader',
    title: '显示表头',
    setter: 'BoolSetter',
    defaultValue: true
  },

**Comment by lhbxs** [comment]
使用的引擎 js


 
--

  | <script crossorigin="anonymous" src="https://uipaas-assets.com/prod/npm/@alilc/lowcode-engine/1.2.2/dist/js/engine-core.js"></script>
  | 
  | <script crossorigin="anonymous" src="https://uipaas-assets.com/prod/npm/@alilc/lowcode-engine-ext/1.0.6/dist/js/engine-ext.js"></script>
  |

**Comment by lhbxs** [comment]
我记得未开源的版本，逻辑是这样的。

设置器里面的 defaultValue 只控制 设置器本身的状态

不会被同步到页面 schema 中，这个逻辑是非常正确的，这样可以减少 页面 Schema 的 冗余。

举例：Button 的 size 默认是 middle, 那 middle 就没有必要在 页面 Schema 里面出现

**Comment by liujuping** [comment]
https://github.com/alibaba/lowcode-engine/issues/2590

相关的 issue 可以看一下。
