### ISSUE TITLE
自定义的富文本物料无法在编辑模式下正常使用~~~

### ISSUE THREAD

**Issue by wywppkd** [alibaba/lowcode-engine#2777]
问题: 自定义了一个富文本物料, 但是在编辑态下无法正常使用, 但是预览态可以正常用
查询文档好像是因为编辑态屏蔽了物料的部分事件, 想问一下有没有方式取消屏蔽事件

<img width="960" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/20620574/2d57718c-2c16-45c4-89fd-16c74b8baee4">

<img width="1078" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/20620574/e879c3d8-fc37-4bfb-84e8-56c0518bf3aa">

**Comment by liujuping** [comment]
配置这个试一下，

https://lowcode-engine.cn/site/docs/api/configOptions#customizeignoreselectors---%E7%82%B9%E5%87%BB%E5%BF%BD%E7%95%A5

**Comment by wywppkd** [comment]
> 配置这个试一下，
> 
> https://lowcode-engine.cn/site/docs/api/configOptions#customizeignoreselectors---%E7%82%B9%E5%87%BB%E5%BF%BD%E7%95%A5

现在可以了, 之前用这个不生效不知道咋回事
