### ISSUE TITLE
使用 @alilc/lowcode-react-renderer ReactRenderer 渲染低代码页面， 操作时会出现卡顿

### ISSUE THREAD

**Issue by zsj9705** [alibaba/lowcode-engine#2784]
## **Describe the bug (required)** / **详细描述 bug（必填）**

使用最新的 @alilc/lowcode-react-renderer ReactRenderer渲染，在一些配置不高的设备上操作卡顿

---

## **To Reproduce (required)*
* / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

1. 使用antd物料的编辑器 https://lowcode-engine.cn/demo/demo-basic-antd/index.html
2. 导入以下schema后保存
[schema.json.zip](https://github.com/alibaba/lowcode-engine/files/13701179/schema.json.zip)
3. 点击预览进入预览界面
4. 打开控制台 性能 cpu使用6倍降速。
5. 点击页面上列表中的主按钮，可以看到控制台有`[Violation] 'click' handler took 299ms`打印

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为
在相同数据和页面结构下，同样开启cpu6倍降速，使用react和antd组件直接编写的页面不会有这种卡顿情况。
使用引擎搭建的页面在配置不高的设备操作时不会出现卡顿情况。

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
<img width="1344" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/142392685/73b8e593-9eba-459c-9cc5-4fe2a56260a3">

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: 低代码引擎版本 v1.2.4-beta
 - AliLowCodeEngineExt version: 低代码引擎扩展包版本 v1.0.6

**Comment by JackLian** [comment]
render渲染肯定是比不上源码模式的，你这种情况可以选择出码模式，render的性能我们也会持续关注和提升，不过这个是非常长期的任务
