### ISSUE TITLE
关于属性值reset的探讨

### ISSUE THREAD

**Issue by zr443** [alibaba/lowcode-engine#2789]
现在碰到一个问题，用对应的setter给属性设置对应值后，无法重置回默认值了。
以Button的Loading属性为例：
![image](https://github.com/alibaba/lowcode-engine/assets/2201981/22e7595e-4e13-4c9e-b3d4-5dbf57bcc073)

如果通过开关打开/关闭后，就无法改回undefined状态了。
StringSetter也是如此，即便把输入框清空，也是空字符串，不再是undefined状态了。

各位大佬有好办法么？

**Comment by ChiZng** [comment]
#2597 
我给后面搞了一个重置按钮
![image](https://github.com/alibaba/lowcode-engine/assets/27946984/86dc1e8f-01be-4841-bafe-b770f952fdbe)

**Comment by zr443** [comment]
> #2597 我给后面搞了一个重置按钮 ![image](https://private-user-images.githubusercontent.com/27946984/292141143-86dc1e8f-01be-4841-bafe-b770f952fdbe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDMyMjUzODMsIm5iZiI6MTcwMzIyNTA4MywicGF0aCI6Ii8yNzk0Njk4NC8yOTIxNDExNDMtODZkYzFlOGYtMDFiZS00ODQxLWJhZmUtYjc3MGY5NTJmZGJlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjIyVDA2MDQ0M1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5MWRjZTY3NWE0YTJlOTEzOWZhMWM2MWJkMGY1NGMwMWY2YzVkODE5YjJlYWU1ZjFhM2M1MDliOTk0OWVjOWQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.L-MW5z6bLZZCOniKfBjs5gDxFMpxaJgm0GhFhmwLG_o)

请问你是自己开发的吗，有没有提PR啊？

**Comment by ChiZng** [comment]
@zr443 最近在忙项目没提pr。我在搭建协议中(IPublicTypeNodeSchema)加了fileds不知道能不能合进去，毕竟修改了协议

**Comment by zr443** [comment]
@ChiZng 谢谢，至少提供了思路。
