### ISSUE TITLE
@alilc/antd-lowcode-materials Antd Materials for LowCode是否会开源

### ISSUE THREAD

**Issue by better-owlet** [alibaba/lowcode-engine#28]
`@alilc/antd-lowcode-materials` Antd Materials for LowCode是否会开源，何时？

**Comment by hujiulong** [comment]
好奇你怎么知道这个包名的，我们确实已经做了 antd 的低代码组件库，后面应该也会开源，目前没有具体的时间

**Comment by better-owlet** [comment]
小哥哥，源码上一些demo上有啊。我们还是用antd的比较多。如果你们已经打算开源，我们就没必要自己去接入了嘛。尽快开源更好[手动点赞]

**Comment by LeoYuan** [comment]
敬请期待，开放后我们会更新物料的文档~

**Comment by xiemeilong** [comment]
期待开源antd的物料，另外有没有formily的物料会开源吗 @LeoYuan

**Comment by FmaBauer** [comment]
👍 同样等待antd

**Comment by FmaBauer** [comment]
可以了解下antd物料开源的大致计划吗？比如今年上半年或是今年下半年，我们想基于antd pro table做crud的场景物料

**Comment by LeoYuan** [comment]
@hujiulong 催更了😄~

**Comment by mark-ck** [comment]
antd-lowcode 已开源：
组件仓库：https://github.com/alibaba/lowcode-materials/tree/main/antd-lowcode
lowcode-demo 使用示例：https://github.com/alibaba/lowcode-demo/blob/main/src/scenarios/basic-antd/assets.json
体验地址：https://alifd.alicdn.com/npm/@alilc/lowcode-materials@1.0.3/build/antd-lowcode/index.html

**Comment by hujiulong** [comment]
更新一下：
* 组件仓库：https://github.com/alibaba/lowcode-materials/tree/main/packages/antd-lowcode-materials
* npm包: [@alilc/antd-lowcode-materials](https://www.npmjs.com/package/@alilc/antd-lowcode-materials)
* 体验地址：https://alifd.alicdn.com/npm/@alilc/antd-lowcode-materials@1.0.3/build/lowcode/index.html
