### ISSUE TITLE
自定义插件时，icon都是有哪些图标

### ISSUE THREAD

**Issue by ming001** [alibaba/lowcode-engine#2800]
const componentsPane = skeleton.add({
        area: 'leftArea',
        type: 'PanelDock',
        name: 'testPane',
        content: testPane,
        contentProps: {},
        props: {
          align: 'top',
          icon: 'wenjian',    // 就是这个地方，有哪些图标
          description: '测试',
        },
      });

只能在文档上看到有几个icon，不知道具体有哪些icon，和fusion上的icon又对应不起来

**Comment by liujuping** [comment]
https://fusion.design/64063/component/icon?themeid=20133
