### ISSUE TITLE
自定义设置器如何打一个UMD包？

### ISSUE THREAD

**Issue by beautiful-boyyy** [alibaba/lowcode-engine#2806]
![Screenshot 2023-12-28 at 12 09 21](https://github.com/alibaba/lowcode-engine/assets/66351806/4a51f893-507c-4095-a3a9-7eac2f93ff43)
选的第二个，然后构建出来不是UMD包

**Comment by eternalsky** [comment]
插件一般是直接注册在 designer，官方脚手架不提供直接构建成 umd 的链路。

**Comment by beautiful-boyyy** [comment]
> 插件一般是直接注册在 designer，官方脚手架不提供直接构建成 umd 的链路。

但是物料包打包出来是UMD呀
