### ISSUE TITLE
页面之间跳转，可以用React Context来传递数据吗

### ISSUE THREAD

**Issue by mengying0608** [alibaba/lowcode-engine#2811]
比如我画了两个页面， 页面A和页面B
当我想要携带页面A的信息跳转到页面B， 并在页面B中使用
是否可以通过React Context来传递？还是只能通过URL携带信息？
是否有相关文档？

**Comment by zr443** [comment]
你又不指望页面能够实时刷新，没必要整那么复杂，我觉得全局变量，SessionStorage都行。

**Comment by mengying0608** [comment]
有些信息不想暴露出来

**Comment by ppmmwozuiai** [comment]
引擎很多地方用了Mobx，我还想会不会在应用级上套一个mobx store，然而并没有

**Comment by 1ncounter** [comment]
@mengying0608  两个页面指的是什么场景呢？ 设计器还是渲染之后的应用？

**Comment by mengying0608** [comment]
找到了可以用this.context.engine.context来进行传值，文档里似乎没有提及。
@1ncounter 两个页面是指，我用设计器画了两个页面，比如列表页和详情页，我想要把列表页的ID通过context传到详情页用来加载数据。
