### ISSUE TITLE
ResourceConsumer 无法多次消费

### ISSUE THREAD

**Issue by web-linda** [alibaba/lowcode-engine#2812]
## **Describe the bug (required)** / **详细描述 bug（必填）**

引擎设计器作为qiankun的子应用，当设计器组件卸载后，host-view 同样被卸载；当再次加载设计器子应用，react-simulator-renders host.componentsConsumer.consume 无法二次消费，appHelper中 utils 无法正常加载到模拟器中，查看源码得知：
ResourceConsumer consume 函数中有 
if (this._consuming) {
    return;
}
导致二次消费被拦截，无法多次消费。

期望 consume 可以多次消费。

**Comment by web-linda** [comment]
考虑是否可以去掉此拦截

**Comment by JackLian** [comment]
低代码引擎by design是不能作为spa的一部分的

**Comment by web-linda** [comment]
1 可否解释下代码中 if (this._consuming) {return;} 的意义呢？ 
2 如果设计器需要作为组件使用，该如何处理呢？
