### ISSUE TITLE
想在物料拖入设计器时修改一下物料在大纲树的titile，所以就需要问一下，咱们engine项目的物料拖入钩子是哪儿个

### ISSUE THREAD

**Issue by zdgzdgzdg** [alibaba/lowcode-engine#2814]
想在物料拖入设计器时修改一下物料在大纲树的titile，所以就需要问一下，咱们engine项目的物料拖入钩子是哪儿个

**Comment by liujuping** [comment]
https://lowcode-engine.cn/site/docs/api/model/document-model#onaddnode

这里的文档看看
