### ISSUE TITLE
把预览页面集成到umi 中，报scss文件解析不了的错误 

### ISSUE THREAD

**Issue by wssgchungang** [alibaba/lowcode-engine#282]
## **问题描述 **

我把preview.tsx 的内容集成到 umi项目的组件中，页面报无法解析 lowcode-plugin-designer/es/index.scss这个文件，然后我按umi文档将 plugin/sass、node-sass、sass-loader 装上，config中的sass:{} 配置加上，还是报错，有什么解决办法吗
---

## **问题截图**
![image](https://user-images.githubusercontent.com/29122164/162378729-f568b8b5-c76e-4093-8a9b-316b494db381.png)

**Comment by cyh-88** [comment]
预览页面集成到umi 中,报scss文件解析不了的错误,这个问题我解决了，但是遇到了ReferenceError: VERSION_PLACEHOLDER is not defined 这个问题，不知道你遇到了没有

**Comment by liujuping** [comment]
参考：https://github.com/alibaba/lowcode-engine/issues/137

**Comment by wssgchungang** [comment]
> 预览页面集成到umi 中,报scss文件解析不了的错误,这个问题我解决了，但是遇到了ReferenceError: VERSION_PLACEHOLDER is not defined 这个问题，不知道你遇到了没有

@cyh-88  兄弟咋解决的

**Comment by wssgchungang** [comment]
> 预览页面集成到umi 中,报scss文件解析不了的错误,这个问题我解决了，但是遇到了ReferenceError: VERSION_PLACEHOLDER is not defined 这个问题，不知道你遇到了没有

@cyh-88 兄弟咋解决的scss 问题的 急求!

**Comment by wssgchungang** [comment]
已解决。  重新安装依赖就又好了。。。

**Comment by WHSnhcZDYRZC** [comment]
可以去看下这个库的解决方案哦
https://github.com/WHSnhcZDYRZC/umi4-lowcode-engine-solutions
