### ISSUE TITLE
如何限制组件拖放在固定的位置？

### ISSUE THREAD

**Issue by zhuyuanmin** [alibaba/lowcode-engine#2829]
如题，比如，Modal组件只能放置在Page下面。目前如果将Modal组件放置任意位置会导致组件无法选中，无法删除。只有放置在Page下面，大纲树才能出现模态弹窗组件，才可以切换显示隐藏及删除操作。

这个应该可以实现吧，我看有的组件拖放不合适的位置，大纲树、画布区域都会显示红色线条提示组件无法被放置。

**Comment by liujuping** [comment]
https://lowcode-engine.cn/site/docs/specs/material-spec#22243-%E7%BB%84%E4%BB%B6%E8%83%BD%E5%8A%9B%E9%85%8D%E7%BD%AE-component

这里的 childWhitelist 和 parentWhitelist

**Comment by zhuyuanmin** [comment]
已验证，OK。
