### ISSUE TITLE
自定义出码文本有做校检，是否有开头关闭它

### ISSUE THREAD

**Issue by smilecoder** [alibaba/lowcode-engine#2839]
<img width="667" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/2402816/f4f73825-10af-451a-8201-680374a5f901">

**Comment by qingniaotonghua** [comment]
这个是 tsc 命令行单独控制的 build 吧，出码又不会做 build，只生成源码

**Comment by smilecoder** [comment]
这里报错出码目录文件还没有生成了，跟tsc build没有关系

**Comment by smilecoder** [comment]
我只要把fileType修改成java就不会报错，所以肯定是框架内部有处理。

**Comment by smilecoder** [comment]
`postProcessors: [
      //CodeGen.postprocessor.prettier()
 ]
`
好了我知道了，注释这个就可以了。
