### ISSUE TITLE
TypeError: Cannot read properties of null

### ISSUE THREAD

**Issue by shawyb** [alibaba/lowcode-engine#2842]
![image](https://github.com/alibaba/lowcode-engine/assets/32785966/ee22d696-8127-4ee4-90e0-88313d82ff67)
官网的demo打开控制台报错，下载demo项目到本地启动也是同样错误，这是为什么啊

**Comment by liujuping** [comment]
已解决。

**Comment by HAOHAO934753575** [comment]
> 已解决，本地 demo 引擎版本修改成最新的正式版本即可。
引擎怎么修正最新呀，能具体讲讲吗，谢谢啦

**Comment by liujuping** [comment]
拉一下最新的 demo 代码吧。
