### ISSUE TITLE
请教关于数据源模块及物料属性配置模块改造思路

### ISSUE THREAD

**Issue by Gllidan** [alibaba/lowcode-engine#285]
## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
我现在想尝试修改下数据源模块，扩展为支持olap字段配置流程。
但是看插件代码时，有一些疑惑点，不知道怎么处理。
我现在的大体思路

1. 在原有的数据源插件上，扩展olap配置项，增加添加数据集操作，选择后挂载到全局变量。
（这里我碰上几个问题：
      a.官方插件项目跑不起来
      b.通过脚手架创建插件，fetch请求代理失败
      c.看过源码，未能理解状态机相关操作后，如何同步更新dataSourcelist到全局变量上，用于变量输入
 ）

2. 这个olap数据集的全局变量，其实只在编排流程用到，所以只在设计时挂载使用，也是需要处理的点。

3. 扩展自定义setter，专门用于处理物料的数据源字段拖拽配置。

4. 处理直出页面时（渲染），根据物料的schema中的数据源字段配置，拼接成查询语句，发送请求。

5. 物料根据返回数据，回填渲染。

大概想到的这么处理，不知道大佬们是否有更好的建议，或者有哪里不合理，走弯了，希望大佬有空帮忙指点下哈
---

**Comment by LeoYuan** [comment]
1. 数据源引擎：https://github.com/alibaba/lowcode-datasource/tree/main
2. 数据源面板：https://github.com/alibaba/lowcode-plugins/tree/main/packages/plugin-datasource-pane，暂时使用 npm link 的方式启动

**Comment by xingmolu** [comment]
2. Q: 这个olap数据集的全局变量，其实只在编排流程用到，所以只在设计时挂载使用，也是需要处理的点。
     A: 数据集其实只要和当前页面关联即可，无需在低代码数据源体现出来，通过setter可以将olap数据集转换为数据源协议，挂载到低代码schema上；然后就到了第4点的执行了；
4. Q：处理直出页面时（渲染），根据物料的schema中的数据源字段配置，拼接成查询语句，发送请求。
     A：这个可以直接通过自定义handler来实现的，详细可以看文档:https://www.yuque.com/lce/usage/datasource#NVdIn
