### ISSUE TITLE
点击”构建资产包“后，请求的这个接口https://parts.lowcode-engine.cn/material/buildAssets.json 返回错误，页面一直显示“资产包构建中,请勿关闭页面...” ，我自己的理解，上面这个接口返回没找到文件，是不是没有进行资产包构建呢？？

### ISSUE THREAD

**Issue by yunnode** [alibaba/lowcode-engine#2852]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

点击”构建资产包“后，请求的这个接口https://parts.lowcode-engine.cn/material/buildAssets.json
返回错误，
{
    "success": false,
    "errorCode": 500,
    "errorMsg": "/material/buildAssets.json Not Found"
}
页面一直显示“资产包构建中,请勿关闭页面...” ，我自己的理解，上面这个接口返回没找到文件，是不是没有进行资产包构建呢？？

<img width="755" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/48727732/4e636705-0f12-4639-9ba1-26208a2d86cd">

<img width="1315" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/48727732/8c57ee4b-bf90-4fa7-b46a-4d0ea4417bad">

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by eternalsky** [comment]
请重试一下，如果还是不行的话 @qingniaotonghua 来看看具体是什么构建出错导致的~

**Comment by qingniaotonghua** [comment]
这里构建资产包只适用于临时构建，且不能关闭页面，建议到我的资产包中去，将需要的npm包都收纳在 资产包中，然后进行构建，结果以及记录会持久化保存，也可以中途关闭页面 @yunnode

**Comment by yunnode** [comment]
> 这里构建资产包只适用于临时构建，且不能关闭页面，建议到我的资产包中去，将需要的npm包都收纳在 资产包中，然后进行构建，结果以及记录会持久化保存，也可以中途关闭页面 @yunnode
------------------
 @qingniaotonghua  你好，刚构建又失败了。麻烦看下。
![image](https://github.com/alibaba/lowcode-engine/assets/48727732/67fcb98f-da81-4d2e-862c-4d419595d001)

**Comment by qingniaotonghua** [comment]
还是一样的问题，组件依赖问题：
![image](https://github.com/alibaba/lowcode-engine/assets/10780785/328bd432-be29-40b2-9ebf-983022e13fa3)

**Comment by eternalsky** [comment]
看下你的组件是不是使用了 antd-mobile ，但是没有依赖他。

**Comment by yunnode** [comment]
> 看下你的组件是不是使用了 antd-mobile ，但是没有依赖他。

好的

**Comment by yunnode** [comment]
这次构建成功了，感谢。
![image](https://github.com/alibaba/lowcode-engine/assets/48727732/024bab0b-151e-4e8b-8cd3-bcd0582ee071)
