### ISSUE TITLE
【咨询】单选框绑定数据源，如何标识数据源中哪个Item作为默认选中的值

### ISSUE THREAD

**Issue by q1979635364** [alibaba/lowcode-engine#2866]
**环境：**
Lab https://lab.lowcode-engine.cn/

**版本信息：**
![image](https://github.com/alibaba/lowcode-engine/assets/25050128/43cd749d-16ce-4e3f-ba11-cef515e210ae)

**期望：**
单选框绑定数据源后，单选框能有一个默认值被选中。（如果默认让第一个被选中，或者加一个“selected”字段表示是否选中就好了）

**实际情况：**
单选框绑定数据源，无法指定默认值。

**补充信息：**
我的数据源返回的数据格式如下：
`[
    {
        "value": "NONE",
        "text": "非集合类型"
    },
    {
        "value": "LIST",
        "text": "有序列表"
    },
    {
        "value": "SET",
        "text": "无序列表"
    },
    {
        "value": "ARRAY",
        "text": "数组"
    }
]`
![image](https://github.com/alibaba/lowcode-engine/assets/25050128/edf4c977-2168-47a6-8f04-ce5188599e8f)

**Comment by woshilaoge** [comment]
![image](https://github.com/alibaba/lowcode-engine/assets/22810511/1f4246ef-52f3-4939-8853-6d57f988203c)

方式1. 可以查看下组件帮助文档，看是否有满足的示例
方式2. 如截图，你的诉求是合理的，当前组件是有类似  selected 的字段，不过你需要鼠标移动到当前属性上去查看。

**Comment by q1979635364** [comment]
@woshilaoge 我在返回值里面加了```defaultChecked```字段，但似乎不管用。

接口返回值：
![32ed668d5db3bf65b270d1b6cbd67ae](https://github.com/alibaba/lowcode-engine/assets/25050128/e4eb7b0a-53c9-43a0-bb2e-087e8d8195aa)

页面展示效果：
![Uploading 509a5f0e332fa6a7dc56e657e724652.png…]()

下拉选择框绑定的数据源以及数据源信息：
![Uploading b24494306e0f6035d4dde3e25ced390.png…]()
