### ISSUE TITLE
【咨询】如何在onError函数中，获取到http接口返回的body信息

### ISSUE THREAD

**Issue by q1979635364** [alibaba/lowcode-engine#2867]
## **如何在onError函数中，获取到http接口返回的body信息**

在全局配置的onError方法中，只有一个error参数，大概是这样的内容
`
{
    "status": 500,
    "message": "Request Error(Status: 500)",
    "_log_": true
}
`
我的服务端接口在报错后（http状态码为4xx或5xx），会往body里面塞一些错误信息。我想用弹窗把这些错误信息弹出来。
但从目前onError方法的定义来看，我没有渠道获取。

---
## **如何复现 bug**
定义一个服务端接口，服务端接口的http状态码设置为500，以application/json的格式返回任意数据。

---
##  **预期行为**
期望可以在onError里面获取到接口返回的body。

---
## **截图**
这个是打印出来的error
![image](https://github.com/alibaba/lowcode-engine/assets/25050128/0ddbcd5a-6a28-4ce8-9653-41c364851d44)

这个是http接口返回：
![image](https://github.com/alibaba/lowcode-engine/assets/25050128/63d60039-63f7-46c1-b7d2-3689bfb71a38)

---
## **环境信息**
![image](https://github.com/alibaba/lowcode-engine/assets/25050128/6393ace8-5c11-4e94-9220-43c28024fb87)

**Comment by JackLian** [comment]
阿里内部平台问题请去平台答疑群

**Comment by woshilaoge** [comment]
![image](https://github.com/alibaba/lowcode-engine/assets/22810511/683f2367-a5d2-42cc-8edf-55cc72bc83c4)

因为有个全局默认的 fit 处理函数（默认的逻辑），如果你的错误信息不符合它的规范，可以自行定义一这个函数就行。这样你再 回调中就能获取到自己的值了。不过还是建议还是遵循它这个 rpc 的规范，错误信息放在 errorMsg 中合理些

**Comment by q1979635364** [comment]
（备注：我的http接口返回的状态码是500，不是200，我试过了，如果是200的话，可以走到fit方法）
大佬，这个函数的处理顺序似乎不是你预期的，我把fit跟onError方法的方法体都只保留了一个console，打印出来的结果并不包含http接口的返回值：
![image](https://github.com/alibaba/lowcode-engine/assets/25050128/0ec6db61-6d03-4db9-bb49-b4c295b01a03)
这个是浏览器的输出：
![image](https://github.com/alibaba/lowcode-engine/assets/25050128/471ffa3e-eccd-424c-82c3-3ae14bee6291)
