### ISSUE TITLE
lowcode-engine-ext 的ArraySetter问题

### ISSUE THREAD

**Issue by zdgzdgzdg** [alibaba/lowcode-engine#2871]
## **Describe the bug (required)** / **详细描述 bug（必填）**

使用lowcode-engine-ext的分支为feat/array-setter,、
①我们在画布中拖出一个分组表格，
②点击操作列的编辑按钮
![图片](https://github.com/alibaba/lowcode-engine/assets/100658615/5d4c7ea3-963c-4462-972d-92ac933cee8f)
③转换右侧属性面板’type‘的类型为‘nomal’，左侧弹出面板同步转换成功
![图片](https://github.com/alibaba/lowcode-engine/assets/100658615/f039ce27-276a-4c5d-bab0-d94579c52d76)

④转换左侧弹出面板为‘primary’，但是右侧并未同步转化
![图片](https://github.com/alibaba/lowcode-engine/assets/100658615/133cacb0-0ee3-4aac-80fd-67f21bc53b6c)

已经尝试其他分支，但是其他分支的arraySetter多少也有问题，能否修复一下

**Comment by zdgzdgzdg** [comment]
使用lowcode-engine-ext的分支为fix/array-setter,
①拖拽表格组件到画布，编辑右侧数据列属性面板，每输入一次输入框都会失去焦点，希望能够修复
![动画](https://github.com/alibaba/lowcode-engine/assets/100658615/e5dee400-525a-4fbe-b8a4-60d62132cc6d)

**Comment by zdgzdgzdg** [comment]
使用lowcode-engine-ext的分支为fix/array-setter,
编辑右侧数据，画笔处的弹窗并未弹出希望可以修复
![动画](https://github.com/alibaba/lowcode-engine/assets/100658615/b92a175d-6e7e-47a4-8c66-b6c9698a26f4)

**Comment by JackLian** [comment]
不要使用非主干的分支，正式版本如果有问题可以提issue，如果需要提PR也请从main 拉最新代码

**Comment by zdgzdgzdg** [comment]
> 不要使用非主干的分支，正式版本如果有问题可以提issue，如果需要提PR也请从main 拉最新代码
一开始是main 分支是有问题我才用别的分支的，我以为别的分支能用，那我现在来基于main分支重新提issue
