### ISSUE TITLE
在虚拟机上运行报错lowcode-materials

### ISSUE THREAD

**Issue by h459259** [alibaba/lowcode-engine#2884]
## 目前报的错如下方所示**

![image](https://github.com/alibaba/lowcode-engine/assets/78139016/790390df-a57c-43e5-9331-50152c2f93fd)

我在请求里看到的是这个接口报错
![image](https://github.com/alibaba/lowcode-engine/assets/78139016/e129db26-2589-47b4-ade5-a36ac8dbde6a)

然后我去浏览器地址运行这个https://alifd.alicdn.com/npm/@alilc/lowcode-preset-plugin@0.1.2/dist/lowcode-preset-plugin.js,这个压缩代码里面的https://dev.g.alicdn.com/ali-lowcode/ali-lowcode-materials/1.1.0/schema.json这串链接是没有任何反应的

**Comment by JackLian** [comment]
https://dev.g.alicdn.com/ali-lowcode/ali-lowcode-materials/1.1.0/schema.json 这个url是用来检测是否阿里内网cdn的，相关报错可以忽略
