### ISSUE TITLE
antd 日期组件只能部分汉化

### ISSUE THREAD

**Issue by linc2023** [alibaba/lowcode-engine#2895]
## 详细描述

通过 lowcode engine 封装  antd 的日期组件，没法通过 ``ConfigProvider `` 汉化：

```js
import zhCN from 'antd/es/locale/zh_CN';
import 'moment/locale/zh-cn';
import moment from 'moment';
moment.locale('zh-cn')

<ConfigProvider locale={zhCN}>
    <DatePicker showTime picker="month"/>
</ConfigProvider>
```

**官网有个 “全局化配置” 组件，我看了一下代码就是 **ConfigProvider** 和以上代码完全等价，使用这个组件+日期组件可以相当于以上配置。**

---

## 如何复现 bug

- 1.打开 https://lowcode-engine.cn/demo/demo-basic-antd/index.html ；
- 拖入“全局化配置”组件，然后在全局化配置组件中拖入“日期选择框”；
 
![image](https://github.com/alibaba/lowcode-engine/assets/133838877/5ea32bb5-05de-4ef4-bb3f-c2a995c42c24)

- 预览查看效果

---

## 预期行为

希望年月日星期等等都能汉化，目前月、星期没有汉化。

![image](https://github.com/alibaba/lowcode-engine/assets/133838877/706fbd74-0368-4193-bdef-e213d45fd8e2)

---

**Comment by linc2023** [comment]
解决办法：
moment.js 使用了 assets-xxx.json 中的地址，里面没有中文包，在 https://g.alicdn.com/mylib/moment/2.24.0/ 下没找到对应的locale/zh-cn.js，我使用了字节的 cdn

![image](https://github.com/alibaba/lowcode-engine/assets/133838877/ca3a98cb-e098-4b41-ba46-3c29d3d13f9c)

**Comment by little-yaonv** [comment]
感谢大佬！
