### ISSUE TITLE
props及prop的get方法的path入参类型问题

### ISSUE THREAD

**Issue by zboMa** [alibaba/lowcode-engine#2900]
在props.ts和prop.ts两个文件当中，都有一个get方法。
当获取的prop为数组项时，prop中的get有一段代码将无法进入：
```js
if (typeof path !== 'number') {
      const i = path.indexOf('.');
      if (i > 0) {
        nest = path.slice(i + 1);
        if (nest) {
          entry = path.slice(0, i);
        }
      }
    }

    let prop: any;
    if (type === 'list') {
      if (isValidArrayIndex(entry, this.size)) {
        prop = items![entry];
      }
    } else if (type === 'map') {
      prop = maps?.get(entry);
    }
```
这是由于入参作为一个字符串，获取到的entry也将是一个字符串，则数组项的0123这类下标，无法正确的作为number类型进行处理。
例如：
```js
node.getPropValue('items.1')
node.getPropValue('items.0.name');
```

只有当使用`prop.getPropValue(1)`这种用法的时候，才可以正确的进入逻辑，但是实际上几乎不会这样使用。
且由于无法作为number类型处理，此处也无法正确获取到items中已有的数据
```js
let prop: any;
    if (type === 'list') {
      if (isValidArrayIndex(entry, this.size)) {
        prop = items![entry];
      }
    } else if (type === 'map') {
      prop = maps?.get(entry);
    }
```

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
应当正确的识别到数组类型下标项，进入正确的number类型处理逻辑。

---

## **Screenshots (optional)** / **bug 截图（可选）**
- `packages\designer\src\document\node\props\props.ts`
- `packages\designer\src\document\node\props\props.ts`

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.3.1] / 低代码引擎版本

**Comment by liujuping** [comment]
现在是怎么获取不满足预期？有没有线上复现的路径？

**Comment by zboMa** [comment]
线上无复现路径。
我们是采用onChangeNodeProp做监听处理时，发现修改数组类型属性项的变更会出现错误回调，譬如移动某一项时，导致全体内容全部回调一遍。
跟进发现由于无法正确识别数字下标path，也就无法获取到对应的prop缓存实例，每次调用都会新new Prop导致。

**Comment by liujuping** [comment]
现在获取这两个值是可以正常获取的

node.getPropValue('items.1')
node.getPropValue('items.0.name');

没有理解你说的问题具体是哪块。

**Comment by zboMa** [comment]
```js
    let entry = path;
    let nest = '';
    if (typeof path !== 'number') {
      const i = path.indexOf('.');
      if (i > 0) {
        nest = path.slice(i + 1);
        if (nest) {
          entry = path.slice(0, i);
        }
      }
    }

    let prop: any;
    if (type === 'list') {
      if (isValidArrayIndex(+entry, this.size)) {
        prop = items![+entry];
      }
    } else if (type === 'map') {
      prop = maps?.get(entry);
    }

    if (prop) {
      return nest ? prop.get(nest, createIfNone) : prop;
    }

    if (createIfNone) {
      prop = new Prop(this, UNSET, entry);
      this.set(entry, prop, true);
      if (nest) {
        return prop.get(nest, true);
      }

      return prop;
    }
```
上述代码为`packages\designer\src\document\node\props\prop.ts`中get方法的内容。

在使用node.getPropValue('item.0.name')时，递归进入此get方法，当path为`'0.items'`则会如下：
1. path为string，entry为'0'
2. type === 'list'为true
3. isValidArrayIndex(entry, this.size) 为 false（问题就在此处，由于entry是字符串，所以此处返回false）
4. prop不存在
5. createIfNone为true
6. new Prop
上述流程中，第3步理当为true，则prop从items缓存中获取，并直接返回。
但是由于判断错误，每次走到此处都会走到最后的new Prop。

**Comment by zboMa** [comment]
而new Prop导致的一系列后续处理，则是我们不想要的，大体如下，new Prop会导致重新：
```js
    if (value !== UNSET) {
      this.setValue(value, false);
    }
    this.setupItems();
```
而重新setValue和setupItems导致的相关变更，又会导致一系列的回调发生。

**Comment by liujuping** [comment]
这里 key 为 '0' isValidArrayIndex(entry, this.size)  不会导致返回值为 false.

![image](https://github.com/alibaba/lowcode-engine/assets/11935995/f46892b5-7b64-47a4-bb8e-3f566eec29dd)

可以看这个测试用例

**Comment by zboMa** [comment]
抱歉，复现不出来了  - -!
测试用例和方法实现应该是都没问题的。

非常感谢。
