### ISSUE TITLE
这个root是缺少了什么?

### ISSUE THREAD

**Issue by 329697166** [alibaba/lowcode-engine#292]
![1158cf82cb743f1de86b7e12593c244](https://user-images.githubusercontent.com/8613493/162663228-a1145a70-9732-46dd-953c-411988eedb79.png)
![image](https://user-images.githubusercontent.com/8613493/162663284-83eb0f5c-d6c5-4afe-923a-deb1c743d30b.png)

**Comment by 329697166** [comment]
[qiankun_demo.zip](https://github.com/alibaba/lowcode-engine/files/8462507/qiankun_demo.zip)
安装 & 启动步骤
yarn install
yarn allinstall
yarn allstart

**Comment by liujuping** [comment]
请提供更详细的复现步骤，启动之后如何访问等等

**Comment by WHSnhcZDYRZC** [comment]
可以去看下这个库的解决方案哦
https://github.com/WHSnhcZDYRZC/umi4-lowcode-engine-solutions
