### ISSUE TITLE
umi4+lowcode右侧设置器扩展列表点击编辑弹不出来

### ISSUE THREAD

**Issue by zhengzhuang96** [alibaba/lowcode-engine#2924]
![image](https://github.com/alibaba/lowcode-engine/assets/29434858/227586b2-7a67-459f-b3ef-e7304741fc44)
如图所示，点击之后无法弹出，但是在左侧输入框中输入之后，就是里面的值变化之后，扩展弹框才弹出来，可以正常编辑，再次打开点击编辑依旧不发打开，还是需要出入才弹出来
![image](https://github.com/alibaba/lowcode-engine/assets/29434858/453f32bb-ad08-44cd-9a46-fa11be666267)

@alilc/lowcode-engine版本1.1.10和最新1.3.1都这样
@alilc/lowcode-engine-ext：1.0.6

@umijs/max：4.0.89

**Comment by Zhangjin1996** [comment]
请问一下，怎么解决的，遇到同样问题

**Comment by zhengzhuang96** [comment]
降低react版本，用react16版本

**Comment by Zhangjin1996** [comment]
> 降低react版本，用react16版本

多谢，我试一下

**Comment by Zhangjin1996** [comment]
> 降低react版本，用react16版本

是降低umi项目的react版本吗

**Comment by zhengzhuang96** [comment]
对，不是在.umirc.ts里面的headScripts引入react.js文件么，降低那个react版本版本
