### ISSUE TITLE
请问Page页面属性是在哪里定义和扩展的呀？

### ISSUE THREAD

**Issue by yuanAIhan** [alibaba/lowcode-engine#2926]
![image](https://github.com/alibaba/lowcode-engine/assets/80769611/5d23e858-db1b-4755-a042-840189d5f497)
在上面中，基础的demo里面，每次选中对应的页面的时候，会出现页面的一些可设置的属性。
我理解这里是将page作为一个独立的组件来设置其的属性吗？就像自定义物料里面开发一个组件一样？
但是如果我想添加一些额外的属性到page页面之中，我应该如何添加呢？

**Comment by yuanAIhan** [comment]
在另外一个issue里面找到了，只需要定义一个Page一样自定义物料就可以

**Comment by zxfwaxx** [comment]
> 在另外一个issue里面找到了，只需要定义一个Page一样自定义物料就可以

我自定义了一个page物料，但是其他物料拖不进去，要怎么配置一下，可以说明一下吗，麻烦了
