### ISSUE TITLE
生成的schema使用渲染模式嵌套在多tab打开菜单中，内存不回收

### ISSUE THREAD

**Issue by guoxunbo** [alibaba/lowcode-engine#2932]
## **Describe the bug (required)** / **详细描述 bug（必填）**
> 我这边使用了umi创建了一个应用，菜单关联了设计的schema。并且使用预览模式进行渲染页面。菜单关闭了，但是内存不回收。一直增长。
A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
如上菜单关闭，但是内存不回收。请问是什么问题。是否要手动回收？或者是预览模式有问题?
<img width="1280" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/14329149/a1f8b42a-40e2-4eaf-a1c6-c3bf61f23ab1">

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by guoxunbo** [comment]
老早解决了。可以关闭

**Comment by chenxlkamino** [comment]
是在低代码页面中嵌入schema，具体方案是咋实现的啊
