### ISSUE TITLE
请问自定义物料的时候，物料属性如果有一个select下拉框，下拉框的内容来源于网络的话，这个应该如何实现呢？ 

### ISSUE THREAD

**Issue by yuanAIhan** [alibaba/lowcode-engine#2934]
![image](https://github.com/alibaba/lowcode-engine/assets/80769611/fa514414-ad9f-4e09-8c8c-a3d187beb798)
如果在右侧的物料属性里面有一些属性是下拉框的方式来实现的，同时下拉框的内容来源于一个网络请求返回的数据，请问这个应该如何实现呀？

同时右侧的物料属性里面，如果有多个表单字段，表单字段之间如何做联动呢？
类似于antd design里面的ProFormDependency一样，其可以依赖于另外一个表单字段来决定当前字段显示的内容
<ProFormDependency name={['name']}>
  {({ name }) => {
    return (
      <ProFormSelect
        options={[
          {
            value: 'chapter',
            label: '盖章后生效',
          },
        ]}
        width="md"
        name="useMode"
        label={`与《${name}》合同约定生效方式`}
      />
    );
  }}
</ProFormDependency>

**Comment by yuanAIhan** [comment]
我在demo-graph-x6里面使用插件@alilc/lowcode-plugin-code-editor中的CodeEditorPlugin，但是我发现这个插件完全没法打开，即根本不可以使用？其余的demo都可以用，请问是因为demo- graph-x6的特殊性吗

**Comment by yuanAIhan** [comment]
@alilc/lowcode-plugin-datasource-pane 中的 DataSourcePanePlugin也是，其完全没法使用

**Comment by yuanAIhan** [comment]
![image](https://github.com/alibaba/lowcode-engine/assets/80769611/7ff5ce15-55b4-43c9-84a3-636d4def98e8)
我将这个DataSource配置到这里面去了，但是发现没法点击，请问这是为啥呢

**Comment by jiangtao** [comment]
可以自己扩展一个异步 setter，setter 本身是个组件，聚焦/输入的时候触发请求下拉即可。

**Comment by roytian1217** [comment]
setter属性本身就是支持函数的，自己写个setter或者像下面这样也可以

setter: (target) => {
           let options =[{label:'label1',value:1}] //这里做你的网络请求构造options
           return [{
              componentName: 'SelectSetter',
              props: {
                options: options
              }
            }]
}

**Comment by yuanAIhan** [comment]
好的，谢谢你们。学习啦
