### ISSUE TITLE
文档未更新版本，导致实际操作报错

### ISSUE THREAD

**Issue by a1070156174** [alibaba/lowcode-engine#2945]
##  commonUI 在1.17版本中获取不到

 AliLowCodeEngine  v1.1.7-beta  中ctx获取不到commonUI

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
我的代码部分：
<img width="933" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/46166011/9ac10ef2-1121-43f9-9fb4-553507309308">
<img width="728" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/46166011/5e3edb2a-7f2f-4664-8e20-190158e9adcc">

<img width="752" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/46166011/8c6030fe-9a85-4277-990e-df62dd3fcd84">
<img width="1486" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/46166011/f4ff1052-392f-453e-86a5-cbebd356384e">
官方文档说明：

![image](https://github.com/alibaba/lowcode-engine/assets/46166011/dfeda862-ec09-4dde-8b36-a21578888d77)

![image](https://github.com/alibaba/lowcode-engine/assets/46166011/0715b1ff-1b89-4b86-afd8-dab762b12992)

---

**Comment by liujuping** [comment]
可以看一下更新记录

https://github.com/alibaba/lowcode-engine/releases

![image](https://github.com/alibaba/lowcode-engine/assets/11935995/533fe552-7b7b-42d6-9596-fdeed9b03789)

后续文档是否还要加上更新的版本号待定。
