### ISSUE TITLE
render的包是不是写错了

### ISSUE THREAD

**Issue by 1490113799** [alibaba/lowcode-engine#2989]
下面标记的位置是不是应该改成 (window as any).ReactDOM = ReactDOM; （ (window as any).ReactDOM中“DOM”大写）
![image](https://github.com/alibaba/lowcode-engine/assets/40024148/55d63e6b-2dec-438f-9631-f111602eee21)

**Comment by 1ncounter** [comment]
不影响 external 掉的全局依赖，后续会优化掉

**Comment by 1490113799** [comment]
在运用render包对antd 5及更高版本进行渲染时，可能会遭遇渲染失败的困扰（具体报错信息请参见附图），通过设置(window as any).ReactDOM = ReactDOM;后页面可以正常渲染。然而，这样的做法实际上是对全局变量window.ReactDOM进行了污染，请问这个污染会对应用产生影响吗?以及这个问题后续是否会进行优化？
![image](https://github.com/alibaba/lowcode-engine/assets/40024148/cb2d8da7-632b-4815-99ee-e810739a5610)
