### ISSUE TITLE
@alilc/element的 fie问题

### ISSUE THREAD

**Issue by toviLau** [alibaba/lowcode-engine#299]
环境描述
os: macOS 12.2.1
node: v14.19.1
npm: 6.14.16 (--registry=https://registry.npm.taobao.org/)

重现步骤
```shell
npm init @alilc/element material > react 组件库 > npm install
```
---------- 以上正常 ----------

执行`fie start`与 `fie build`
报错提示: 
```
$ command not found: fie
```

尝试解决 --> 全局安装 fie
```shell
npm i -g fie
```
安装完成后,再次执行
```
fie start
# 或
fie build
```

npm报错
```
[core-module] @ali/fie4-plugin-component 安装报错，请确认该package是否存在!
```
![image](https://user-images.githubusercontent.com/21324302/162927223-3e0caf29-3f7c-4b10-8a69-e23eadcf9182.png)

### 去npm查找(@ali/fie4-plugin-component)资源包
![image](https://user-images.githubusercontent.com/21324302/162928563-2094397d-dce1-4d9b-95b3-8688918e5e81.png)

**Comment by mark-ck** [comment]
不建议使用 fie

**Comment by LeoYuan** [comment]
@toviLau 如何会使用到 fie？理论上整个引擎体系只透露了 npm init @alilc/element / npm start / npm build 这种 cli~

**Comment by toviLau** [comment]
在 package.json 里scripts里有这个命令
