### ISSUE TITLE
Error in code preview

### ISSUE THREAD

**Issue by Minfee** [alibaba/lowcode-engine#30]
![image](https://user-images.githubusercontent.com/39008983/155052070-9dcb3c3b-4f79-4ea8-ba8c-114d0d67acba.png)

**Comment by LeoYuan** [comment]
转移 issue~
https://github.com/alibaba/lowcode-engine/discussions/29

**Comment by Clarence-pan** [comment]
o(╯□╰)o  蚂蚁的 Gravity 提供的这个在线预览功能貌似有接口是需要连内网才能访问的……

**Comment by Clarence-pan** [comment]
我回头研究下能否接入别的在线预览服务吧

**Comment by Clarence-pan** [comment]
@Minfee CodeSandbox 你们能用吗？

**Comment by Minfee** [comment]
可以的

**Comment by Clarence-pan** [comment]
@Minfee 已经接入了 CodeSandbox，升级下出码插件即可：

```sh
npm i -S @alilc/lowcode-plugin-code-generator@1.0.2
```

![image](https://user-images.githubusercontent.com/8750132/157211789-b2ff6cff-1b26-4a76-a3ad-077502f6f63a.png)

**Comment by Clarence-pan** [comment]
@alilc/lowcode-plugin-code-generator@1.0.2 已发布

**Comment by Minfee** [comment]
> @Minfee 已经接入了 CodeSandbox，升级下出码插件即可：
> 
> ```shell
> npm i -S @alilc/lowcode-plugin-code-generator@1.0.2
> ```
> 
> ![image](https://user-images.githubusercontent.com/8750132/157211789-b2ff6cff-1b26-4a76-a3ad-077502f6f63a.png)

好的 非常感谢
