### ISSUE TITLE
进入 lowcode-engine仓库下modules/code-generator目录中，执行npm run prepublishOnly 报错

### ISSUE THREAD

**Issue by ajieying** [alibaba/lowcode-engine#300]
复现步骤
1、 拉取lowcode-engine最新代码；
2、通过命令行进入modules/code-generator目录中；
3、安装依赖；
4、执行npm run prepublishOnly
5、查看报错信息如下
[build:types] building types...
[build:standalone] building...
[build:standalone-worker] building...
[build:cli] building...
[build:standalone-loader] build standalone-loader: packageVersion=1.0.4
[build:standalone-loader] building cjs...
[build:standalone-worker] ✘ [ERROR] Could not resolve "@alilc/lowcode-datasource-types"
[build:standalone-worker] 
[build:standalone-worker]     ../../packages/types/src/index.ts:1:14:
[build:standalone-worker]       1 │ export * from '@alilc/lowcode-datasource-types';
[build:standalone-worker]         ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build:standalone-worker] 
[build:standalone-worker]   You can mark the path "@alilc/lowcode-datasource-types" as external to exclude it from the bundle, which will remove this error.
[build:standalone-worker] 
[build:standalone] ✘ [ERROR] Could not resolve "util"
[build:standalone] 
[build:standalone]     node_modules/nanomatch/index.js:7:19:
[build:standalone]       7 │ var util = require('util');
[build:standalone]         ╵                    ~~~~~~
[build:standalone] 
[build:standalone]   The package "util" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
[build:standalone] 
[build:standalone] ✘ [ERROR] Could not resolve "@alilc/lowcode-datasource-types"
[build:standalone] 
[build:standalone]     ../../packages/types/src/index.ts:1:14:
[build:standalone]       1 │ export * from '@alilc/lowcode-datasource-types';
[build:standalone]         ╵               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[build:standalone] 
[build:standalone]   You can mark the path "@alilc/lowcode-datasource-types" as external to exclude it from the bundle, which will remove this error.
[build:standalone] 
[build:standalone-worker] ✘ [ERROR] Could not resolve "util"
[build:standalone-worker] 
[build:standalone-worker]     node_modules/nanomatch/index.js:7:19:
[build:standalone-worker]       7 │ var util = require('util');
[build:standalone-worker]         ╵                    ~~~~~~
[build:standalone-worker] 
[build:standalone-worker]   The package "util" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
[build:standalone-worker] 
[build:standalone-loader] done
[build:standalone-loader] node scripts/build-standalone-loader exited with code 0
[build:cli] done
[build:cli] node scripts/build-cli exited with code 0
[build:cjs] building cjs...
[build:esm] building esm...
[build:esm] built esm in 0.35s
[build:esm] node scripts/build --format=esm --out=es exited with code 0
[build:cjs] built cjs in 0.45s
[build:cjs] node scripts/build --format=cjs --out=lib exited with code 0
[build:standalone-worker] ✘ [ERROR] Could not resolve "util"
[build:standalone-worker] 
[build:standalone-worker]     node_modules/base/index.js:3:19:
[build:standalone-worker]       3 │ var util = require('util');
[build:standalone-worker]         ╵                    ~~~~~~
[build:standalone-worker] 
[build:standalone-worker]   The package "util" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
[build:standalone-worker] 
[build:standalone] ✘ [ERROR] Could not resolve "util"
[build:standalone] 
[build:standalone]     node_modules/base/index.js:3:19:
[build:standalone]       3 │ var util = require('util');
[build:standalone]         ╵                    ~~~~~~
[build:standalone] 
[build:standalone]   The package "util" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
[build:standalone] 
[build:standalone] ✘ [ERROR] Could not resolve "util"
[build:standalone] 
[build:standalone]     node_modules/class-utils/index.js:3:19:
[build:standalone]       3 │ var util = require('util');
[build:standalone]         ╵                    ~~~~~~
[build:standalone] 
[build:standalone]   The package "util" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
[build:standalone] 
[build:standalone-worker] ✘ [ERROR] Could not resolve "util"
[build:standalone-worker] 
[build:standalone-worker]     node_modules/class-utils/index.js:3:19:
[build:standalone-worker]       3 │ var util = require('util');
[build:standalone-worker]         ╵                    ~~~~~~
[build:standalone-worker] 
[build:standalone-worker]   The package "util" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
[build:standalone-worker] 
[build:standalone] ✘ [ERROR] Could not resolve "util"
[build:standalone] 
[build:standalone]     node_modules/snapdragon/lib/parser.js:4:19:
[build:standalone]       4 │ var util = require('util');
[build:standalone]         ╵                    ~~~~~~
[build:standalone] 
[build:standalone]   The package "util" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
[build:standalone] 
[build:standalone-worker] ✘ [ERROR] Could not resolve "util"
[build:standalone-worker] 
[build:standalone-worker]     node_modules/snapdragon/lib/parser.js:4:19:
[build:standalone-worker]       4 │ var util = require('util');
[build:standalone-worker]         ╵                    ~~~~~~
[build:standalone-worker] 
[build:standalone-worker]   The package "util" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
[build:standalone-worker] 
[build:standalone-worker] ✘ [ERROR] Could not resolve "util"
[build:standalone-worker] 
[build:standalone-worker]     node_modules/static-extend/index.js:12:19:
[build:standalone-worker]       12 │ var util = require('util');
[build:standalone-worker]          ╵                    ~~~~~~
[build:standalone-worker] 
[build:standalone-worker]   The package "util" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
[build:standalone-worker] 
[build:standalone] ✘ [ERROR] Could not resolve "util"
[build:standalone] 
[build:standalone]     node_modules/static-extend/index.js:12:19:
[build:standalone]       12 │ var util = require('util');
[build:standalone]          ╵                    ~~~~~~
[build:standalone] 
[build:standalone]   The package "util" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
[build:standalone] 
[build:standalone-worker] ✘ [ERROR] Could not resolve "util"
[build:standalone-worker] 
[build:standalone-worker]     node_modules/map-visit/index.js:3:19:
[build:standalone-worker]       3 │ var util = require('util');
[build:standalone-worker]         ╵                    ~~~~~~
[build:standalone-worker] 
[build:standalone-worker]   The package "util" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
[build:standalone-worker] 
[build:standalone] ✘ [ERROR] Could not resolve "util"
[build:standalone] 
[build:standalone]     node_modules/map-visit/index.js:3:19:
[build:standalone]       3 │ var util = require('util');
[build:standalone]         ╵                    ~~~~~~
[build:standalone] 
[build:standalone]   The package "util" wasn't found on the file system but is built into node. Are you trying to bundle for node? You can use "platform: 'node'" to do that, which will remove this error.
[build:standalone] 
[build:standalone-worker] Error: Build failed with 7 errors:
[build:standalone-worker] ../../packages/types/src/index.ts:1:14: ERROR: Could not resolve "@alilc/lowcode-datasource-types"
[build:standalone-worker] node_modules/base/index.js:3:19: ERROR: Could not resolve "util"
[build:standalone-worker] node_modules/class-utils/index.js:3:19: ERROR: Could not resolve "util"
[build:standalone-worker] node_modules/map-visit/index.js:3:19: ERROR: Could not resolve "util"
[build:standalone-worker] node_modules/nanomatch/index.js:7:19: ERROR: Could not resolve "util"

[build:standalone-worker]     at Socket.emit (events.js:400:28)
[build:standalone-worker]     at addChunk (internal/streams/readable.js:293:12) {
[build:standalone-worker]   errors: [
[build:standalone-worker]     {
[build:standalone-worker]       detail: undefined,
[build:standalone-worker]       location: [Object],
[build:standalone-worker]       notes: [Array],
[build:standalone-worker]       pluginName: '',
[build:standalone-worker]       text: 'Could not resolve "@alilc/lowcode-datasource-types"'
[build:standalone-worker]     },
[build:standalone-worker]     {
[build:standalone-worker]       detail: undefined,
[build:standalone-worker]       location: [Object],
[build:standalone-worker]       notes: [Array],
[build:standalone-worker]       pluginName: '',
[build:standalone-worker]       text: 'Could not resolve "util"'
[build:standalone-worker]     },
[build:standalone-worker]     {
[build:standalone-worker]       detail: undefined,
[build:standalone-worker]       location: [Object],
[build:standalone-worker]       notes: [Array],
[build:standalone-worker]       pluginName: '',
[build:standalone-worker]       text: 'Could not resolve "util"'
[build:standalone-worker]     },
[build:standalone-worker]     {
[build:standalone-worker]       detail: undefined,
[build:standalone-worker]       location: [Object],
[build:standalone-worker]       notes: [Array],
[build:standalone-worker]       pluginName: '',
[build:standalone-worker]       text: 'Could not resolve "util"'
[build:standalone-worker]     },
[build:standalone-worker]     {
[build:standalone-worker]       detail: undefined,
[build:standalone-worker]       location: [Object],
[build:standalone-worker]       notes: [Array],
[build:standalone-worker]       pluginName: '',
[build:standalone-worker]       text: 'Could not resolve "util"'
[build:standalone-worker]     },
[build:standalone-worker]     {
[build:standalone-worker]       detail: undefined,
[build:standalone-worker]       location: [Object],
[build:standalone-worker]       notes: [Array],
[build:standalone-worker]       pluginName: '',
[build:standalone-worker]       text: 'Could not resolve "util"'
[build:standalone-worker]     },
[build:standalone-worker]     {
[build:standalone-worker]       detail: undefined,
[build:standalone-worker]       location: [Object],
[build:standalone-worker]       notes: [Array],
[build:standalone-worker]       pluginName: '',
[build:standalone-worker]       text: 'Could not resolve "util"'
[build:standalone-worker]     }
[build:standalone-worker]   ],
[build:standalone-worker]   warnings: []
[build:standalone-worker] }
[build:standalone] Error: Build failed with 7 errors:
[build:standalone] ../../packages/types/src/index.ts:1:14: ERROR: Could not resolve "@alilc/lowcode-datasource-types"
[build:standalone] node_modules/base/index.js:3:19: ERROR: Could not resolve "util"
[build:standalone] node_modules/class-utils/index.js:3:19: ERROR: Could not resolve "util"
[build:standalone] node_modules/map-visit/index.js:3:19: ERROR: Could not resolve "util"
[build:standalone] node_modules/nanomatch/index.js:7:19: ERROR: Could not resolve "util"
[build:standalone] ...

[build:standalone]     at Socket.emit (events.js:400:28)
[build:standalone]     at addChunk (internal/streams/readable.js:293:12) {
[build:standalone]   errors: [
[build:standalone]     {
[build:standalone]       detail: undefined,
[build:standalone]       location: [Object],
[build:standalone]       notes: [Array],
[build:standalone]       pluginName: '',
[build:standalone]       text: 'Could not resolve "@alilc/lowcode-datasource-types"'
[build:standalone]     },
[build:standalone]     {
[build:standalone]       detail: undefined,
[build:standalone]       location: [Object],
[build:standalone]       notes: [Array],
[build:standalone]       pluginName: '',
[build:standalone]       text: 'Could not resolve "util"'
[build:standalone]     },
[build:standalone]     {
[build:standalone]       detail: undefined,
[build:standalone]       location: [Object],
[build:standalone]       notes: [Array],
[build:standalone]       pluginName: '',
[build:standalone]       text: 'Could not resolve "util"'
[build:standalone]     },
[build:standalone]     {
[build:standalone]       detail: undefined,
[build:standalone]       location: [Object],
[build:standalone]       notes: [Array],
[build:standalone]       pluginName: '',
[build:standalone]       text: 'Could not resolve "util"'
[build:standalone]     },
[build:standalone]     {
[build:standalone]       detail: undefined,
[build:standalone]       location: [Object],
[build:standalone]       notes: [Array],
[build:standalone]       pluginName: '',
[build:standalone]       text: 'Could not resolve "util"'
[build:standalone]     },
[build:standalone]     {
[build:standalone]       detail: undefined,
[build:standalone]       location: [Object],
[build:standalone]       notes: [Array],
[build:standalone]       pluginName: '',
[build:standalone]       text: 'Could not resolve "util"'
[build:standalone]     },
[build:standalone]     {
[build:standalone]       detail: undefined,
[build:standalone]       location: [Object],
[build:standalone]       notes: [Array],
[build:standalone]       pluginName: '',
[build:standalone]       text: 'Could not resolve "util"'
[build:standalone]     }
[build:standalone]   ],
[build:standalone]   warnings: []
[build:standalone] }
[build:standalone] node scripts/build-standalone exited with code 1
--> Sending SIGTERM to other processes..
[build:standalone-worker] node scripts/build-standalone-worker exited with code 1
--> Sending SIGTERM to other processes..
[build:types] sh scripts/build-types exited with code SIGTERM
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @alilc/lowcode-code-generator@1.0.4 build: `npm run clean && node scripts/build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @alilc/lowcode-code-generator@1.0.4 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/liujunjie47/.npm/_logs/2022-04-12T14_42_18_449Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @alilc/lowcode-code-generator@1.0.4 prepublishOnly: `npm run build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @alilc/lowcode-code-generator@1.0.4 prepublishOnly script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/liujunjie47/.npm/_logs/2022-04-12T14_42_18_491Z-debug.log: 

 /Users/liujunjie47/.npm/_logs/2022-04-12T14_42_18_491Z-debug.log日志如下: 
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/Users/liujunjie47/.nvm/versions/node/v14.18.2/bin/node',
1 verbose cli   '/Users/liujunjie47/.nvm/versions/node/v14.18.2/bin/npm',
1 verbose cli   'run',
1 verbose cli   'prepublishOnly'
1 verbose cli ]
2 info using npm@6.14.15
3 info using node@v14.18.2
4 verbose run-script [ 'prepublishOnly' ]
5 info lifecycle @alilc/lowcode-code-generator@1.0.4~prepublishOnly: @alilc/lowcode-code-generator@1.0.4
6 verbose lifecycle @alilc/lowcode-code-generator@1.0.4~prepublishOnly: unsafe-perm in lifecycle true
7 verbose lifecycle @alilc/lowcode-code-generator@1.0.4~prepublishOnly: PATH: /Users/liujunjie47/.nvm/versions/node/v14.18.2/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/liujunjie47/XXXX/lowcode/lowcodeengine/lowcode-engine/modules/code-generator/node_modules/.bin:/Users/liujunjie47/.nvm/versions/node/v14.18.2/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Users/liujunjie47/.nvm/versions/node/v14.18.2/bin
8 verbose lifecycle @alilc/lowcode-code-generator@1.0.4~prepublishOnly: CWD: /Users/liujunjie47/XXXX/lowcode/lowcodeengine/lowcode-engine/modules/code-generator
9 silly lifecycle @alilc/lowcode-code-generator@1.0.4~prepublishOnly: Args: [ '-c', 'npm run build' ]
10 silly lifecycle @alilc/lowcode-code-generator@1.0.4~prepublishOnly: Returned: code: 1  signal: null
11 info lifecycle @alilc/lowcode-code-generator@1.0.4~prepublishOnly: Failed to exec prepublishOnly script
12 verbose stack Error: @alilc/lowcode-code-generator@1.0.4 prepublishOnly: `npm run build`
12 verbose stack Exit status 1
12 verbose stack     at EventEmitter.<anonymous> (/Users/liujunjie47/.nvm/versions/node/v14.18.2/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
12 verbose stack     at EventEmitter.emit (events.js:400:28)
12 verbose stack     at ChildProcess.<anonymous> (/Users/liujunjie47/.nvm/versions/node/v14.18.2/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
12 verbose stack     at ChildProcess.emit (events.js:400:28)
12 verbose stack     at maybeClose (internal/child_process.js:1058:16)
12 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:293:5)
13 verbose pkgid @alilc/lowcode-code-generator@1.0.4
14 verbose cwd /Users/liujunjie47/XXXX/lowcode/lowcodeengine/lowcode-engine/modules/code-generator
15 verbose Darwin 21.4.0
16 verbose argv "/Users/liujunjie47/.nvm/versions/node/v14.18.2/bin/node" "/Users/liujunjie47/.nvm/versions/node/v14.18.2/bin/npm" "run" "prepublishOnly"
17 verbose node v14.18.2
18 verbose npm  v6.14.15
19 error code ELIFECYCLE
20 error errno 1
21 error @alilc/lowcode-code-generator@1.0.4 prepublishOnly: `npm run build`
21 error Exit status 1
22 error Failed at the @alilc/lowcode-code-generator@1.0.4 prepublishOnly script.
22 error This is probably not a problem with npm. There is likely additional logging output above.
23 verbose exit [ 1, true ]

**Comment by Clarence-pan** [comment]
你这个感觉是依赖没装好，要不然不会报错：[ERROR] Could not resolve "@alilc/lowcode-datasource-types"
建议尝试删除 node_modules 然后重装依赖 -- 注意要在  modules/code-generator 下执行 npm install 或 yarn

**Comment by ajieying** [comment]
实际上code-generator这个包打包过程依赖了packages/types/下的资源，在这个目录下安装完依赖，就可以了
