### ISSUE TITLE
低代码Lab平台 导航配置 保存不生效

### ISSUE THREAD

**Issue by sundylink** [alibaba/lowcode-engine#3000]
https://lab.lowcode-engine.cn/demo#/

## 导航管理 -> 配置导航 

1、进行修改配置，然后保存，再次刷新页面，修改配置没有生效

 
高级设置中 应用名称关闭后，再次刷新后 应用名称又开启了
![image](https://github.com/alibaba/lowcode-engine/assets/35475866/718a0ef8-710d-4ad8-b162-44fe7a3eb063)

2、导航配置的布局 顶部导航风格易选择，打包应用然后访问导航也未生效

设置的深邃风格，结果打包应用后页面不是深邃风格， 是最后一张图效果
![image](https://github.com/alibaba/lowcode-engine/assets/35475866/fe81b572-2787-411c-916e-11c7a1f4ee0b)

![image](https://github.com/alibaba/lowcode-engine/assets/35475866/293d017d-2d31-4430-86cf-9cf5421cf5fb)

**Comment by woshilaoge** [comment]
查了下，接口确实有问题，如果打包完毕后本地运行，可以尝试配置

g_config.navConfig.showAppTitle=false; 进行强制覆盖，可以试试，或者等后续修复这个问题

**Comment by woshilaoge** [comment]
@sundylink  问题2，可以描述再清楚下么？或者复现的应用地址
（PS：按照这个描述是设置了 深邃主题，预览是正常的，打包本地运行后导航变成黄色了？）

**Comment by woshilaoge** [comment]
问题1，已 fix 重新配置即可生效。问题2，本地验证了下，打包发布应该是没问题的，可以排查下是否有页面级别的 样式覆盖导致的主题设置不符合预期
