### ISSUE TITLE
windows10 系统下 .tmp 目录内的meta.js 等文件中的路径转义符错误

### ISSUE THREAD

**Issue by infinite2009** [alibaba/lowcode-engine#301]
详细描述 bug
在windows10上使用 @alilc/element 生成组件库项目，编译时生成的 .tmp 目录下的meta.js、view.js 的路径转义符少了一个 “\”

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
1. 在windows10 上使用 powershell 执行 npm init @alilc/element your-material-name 并安装好依赖
2. 使用 yarn lowcode:dev 进行构建
3. 报出 ERR! (undefined) ./.tmp/meta.js
ERR! Module not found: Can't resolve 'C:Workworkspacememy-materiallowcodecolorful-buttonmeta' in 'C:\Work\workspace\me\my-material\.tmp'

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
正常完成编译

---

## **Screenshots (optional)** / **bug 截图（可选）**
![image](https://user-images.githubusercontent.com/7964451/163007095-c52df57e-7588-41b5-ad89-6bc3fe91560c.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
![image](https://user-images.githubusercontent.com/7964451/163007344-611859af-9f66-40b4-8869-f78e46063b80.png)

**Comment by WinKi7** [comment]
修改下build-plugin-lowcode 源码，自己加个斜杆，目前我是这么做的。

**Comment by mark-ck** [comment]
> 

哪个地方加的斜杠？我看看能不能在插件里兼容下

**Comment by taolei1990** [comment]
不是说要在wls上才能运行嘛 我通过@alilc/element 生成组件库项目一直都没运行起来过

**Comment by WinKi7** [comment]
> > 
> 
> 哪个地方加的斜杠？我看看能不能在插件里兼容下

![image](https://user-images.githubusercontent.com/6613429/163346589-7ec5386b-648f-4df1-a560-b1b29046c613.png)
我是在build-plugin-lowcode替换加上斜杆，不知道是不是handlebars 版本问题，斜杠被转移了

**Comment by WinKi7** [comment]
> 不是说要在wls上才能运行嘛 我通过@alilc/element 生成组件库项目一直都没运行起来过

目前我是能windows直接跑起来了，我是改了build-plugin-lowcode

**Comment by infinite2009** [comment]
> 修改下build-plugin-lowcode 源码，自己加个斜杆，有点丑陋，不过能解决运行起来，目前我是这么做的。

嗯嗯，我正在这么做，考虑到其他开发者可能也遇到了类似问题，所以还是提了个issue

**Comment by infinite2009** [comment]
> > 
> 
> 哪个地方加的斜杠？我看看能不能在插件里兼容下

就是 meta.js, view.js 里边，import 语句的路径

**Comment by taolei1990** [comment]
@WinKi7 感谢大佬 加上这个斜杠现在能执行 npm run lowcode:dev 通过了 现在又遇到页面打开组件加载不进来了 好像是class 设置错了 需要className 但是没找到地方修改 能指导下吗
![image](https://user-images.githubusercontent.com/23173640/163512638-508a0836-f16d-45fe-aa3d-41589504a70a.png)

**Comment by smat0096** [comment]
@[taolei1990](https://github.com/taolei1990)
这里斜杆改下
![image](https://user-images.githubusercontent.com/20716152/164445003-b62f644b-25e0-40ca-9365-aa4c48d6c599.png)

**Comment by taolei1990** [comment]
@smat0096 感谢 加上”\\“ 能运行起来了 
![image](https://user-images.githubusercontent.com/23173640/164446277-3ad5cb20-62cf-4e4e-b6ba-a2e773e53d92.png)

**Comment by smat0096** [comment]
@LeoYuan 建议分隔符处理为 path.sep

**Comment by LeoYuan** [comment]
建议来个PR哦

**Comment by mark-ck** [comment]
这个插件由于有很多内部兼容代码还未开源，我按照 @smat0096 的建议改了一下，有没有 windows 用户可以帮我验证下是否可行 @alifd/build-plugin-lowcode@0.3.0-beta.1

**Comment by taolei1990** [comment]
我输出了信息 不晓得是否能提供点有用线索 
![image](https://user-images.githubusercontent.com/23173640/164486820-bf2e2d17-e4c0-439a-90f6-88d2c41ba28b.png)

按照@WinKi7 上面提供的做法 componentsImportStr这个应该是要反斜杠回来的
![image](https://user-images.githubusercontent.com/23173640/164487646-b248e989-b940-4c50-912a-b9b765102b90.png)

**Comment by w4ngzhen** [comment]
根据最新的0.3.0-beta.1，还是有同样的问题，原因为写入.tmp中meta、view.js等文件的路径被转义。如果在windows下，通过path.join拿到路径本身没有问题，例如：
```
path.join('A', 'B') => 'D:\A\B'
```
这个路径在程序使用上没有问题，但是生成.tmp里面的文件的时候，把路径字符串写入到文件后，文件中的文本实际上是一段转义字符串。所以需要在写入文件的时候，把对应的文本进行\替换为\\。
我这边的处理方法是：
对@alifd/build-plugin-lowcode\index.js进行改造，适配windows路径。
具体方案为：
1. 增加 const os = require('os');
2. 在`function getEntry(rootDir, entryPath)`之前加一个方法normalizePathTextForWindows：
```js
function normalizePathTextForWindows(pathText) {
  if (os.platform() === 'win32') {
    return pathText.replace(/\\/g, '\\\\');
  }
  return pathText;
}
```
3. 修改getEntry和getScssEntry方法：
```diff
function getEntry(rootDir, entryPath, needNormalizeForWindows) {
  if (entryPath && fse.existsSync(path.resolve(rootDir, entryPath))) {
-    return path.resolve(rootDir, entryPath)
+    return needNormalizeForWindows ? normalizePathTextForWindows(path.resolve(rootDir, entryPath)) : path.resolve(rootDir, entryPath);
  }
  for (let i = 0; i < defaultEntryPaths.length; i++) {
    const p = path.resolve(rootDir, defaultEntryPaths[i]);
    if (fse.existsSync(p)) {
-       return p;
+      return needNormalizeForWindows ? normalizePathTextForWindows(p) : p;
    }
  }
  return '';
}

function getScssEntry(rootDir, needNormalizeForWindows) {
  for (let i = 0; i < defaultScssEntryPaths.length; i++) {
    const p = path.resolve(rootDir, defaultScssEntryPaths[i]);
    if (fse.existsSync(p)) {
-      return p;
+      return needNormalizeForWindows ? normalizePathTextForWindows(p) : p
    }
  }
  return '';
}
```
4. 找到getEntry和getScssEntry调用点：
getEntry第一个调用点：
```diff
  INIT_STATE = true;
  if (!PARSED_NPM_NAME) {
    PARSED_NPM_NAME = parseNpmName(package.name);
  }
-  const entry = getEntry(rootDir, entryPath);
+ const entry = getEntry(rootDir, entryPath, false); // 这里要设置为false，因为下面使用entry的地方并不是要用路径字符串，所以不能normalize
```
getEntry的第二个调用点传true：
```diff
    componentViewsExportStr = _componentViews
      .map((component) => {
        return `const ${component} = getRealComponent(${component}Data, '${component}');\nexport { ${component} };`;
      })
      .join('\n');
-    componentViewsExportStr += `\nexport { default } from '${getEntry(rootDir, entryPath)}';`;
+   componentViewsExportStr += `\nexport { default } from '${getEntry(rootDir, entryPath, true)}';`;
    componentViewsImportStr = _componentViews
      .map((component) => {
        const componentNameFolder = camel2KebabComponentName(component);
        const viewJsPath = path.resolve(rootDir, `${lowcodeDir}/${componentNameFolder}/view`);
        return `import * as ${component}Data from '${viewJsPath}'`;
      })
      .join('\n');
```
getEntry的第三个调用点和getScss的唯一调用点：
```diff
+  const scssEntry = getScssEntry(rootDir, true);
-  const scssEntry = getScssEntry(rootDir);
  const viewPath = generateEntry({
    template: 'view.js',
    filename: 'view.js',
    rootDir,
    params: {
-      entryPath: getEntry(rootDir, entryPath),
+      entryPath: getEntry(rootDir, entryPath, true),
      scssImport: scssEntry ? `import '${scssEntry}'` : '',
      componentViews,
      componentViewsExportStr,
      componentViewsImportStr,
      library,
      execCompile,
    },
  });

```

**Comment by mark-ck** [comment]
> 根据最新的0.3.0-beta.1，还是有同样的问题，原因为写入.tmp中meta、view.js等文件的路径被转义。如果在windows下，通过path.join拿到路径本身没有问题，例如：
> 
> ```
> path.join('A', 'B') => 'D:\A\B'
> ```
> 
> 这个路径在程序使用上没有问题，但是生成.tmp里面的文件的时候，把路径字符串写入到文件后，文件中的文本实际上是一段转义字符串。所以需要在写入文件的时候，把对应的文本进行`\`替换为`\\`。 我这边的处理方法是： 对@alifd/build-plugin-lowcode\index.js进行改造，适配windows路径。 具体方案为：
> 
> 1. 增加 const os = require('os');
> 2. 在`function getEntry(rootDir, entryPath)`之前加一个方法normalizePathTextForWindows：
> 
> ```js
> function normalizePathTextForWindows(pathText) {
>   if (os.platform() === 'win32') {
>     return pathText.replace(/\\/g, '\\\\');
>   }
>   return pathText;
> }
> ```
> 
> 3. 修改getEntry和getScssEntry方法：
> 
> ```diff
> function getEntry(rootDir, entryPath, needNormalizeForWindows) {
>   if (entryPath && fse.existsSync(path.resolve(rootDir, entryPath))) {
> -    return path.resolve(rootDir, entryPath)
> +    return needNormalizeForWindows ? normalizePathTextForWindows(path.resolve(rootDir, entryPath)) : path.resolve(rootDir, entryPath);
>   }
>   for (let i = 0; i < defaultEntryPaths.length; i++) {
>     const p = path.resolve(rootDir, defaultEntryPaths[i]);
>     if (fse.existsSync(p)) {
> -       return p;
> +      return needNormalizeForWindows ? normalizePathTextForWindows(p) : p;
>     }
>   }
>   return '';
> }
> 
> function getScssEntry(rootDir, needNormalizeForWindows) {
>   for (let i = 0; i < defaultScssEntryPaths.length; i++) {
>     const p = path.resolve(rootDir, defaultScssEntryPaths[i]);
>     if (fse.existsSync(p)) {
> -      return p;
> +      return needNormalizeForWindows ? normalizePathTextForWindows(p) : p
>     }
>   }
>   return '';
> }
> ```
> 
> 4. 找到getEntry和getScssEntry调用点：
>    getEntry第一个调用点：
> 
> ```diff
>   INIT_STATE = true;
>   if (!PARSED_NPM_NAME) {
>     PARSED_NPM_NAME = parseNpmName(package.name);
>   }
> -  const entry = getEntry(rootDir, entryPath);
> + const entry = getEntry(rootDir, entryPath, false); // 这里要设置为false，因为下面使用entry的地方并不是要用路径字符串，所以不能normalize
> ```
> 
> getEntry的第二个调用点传true：
> 
> ```diff
>     componentViewsExportStr = _componentViews
>       .map((component) => {
>         return `const ${component} = getRealComponent(${component}Data, '${component}');\nexport { ${component} };`;
>       })
>       .join('\n');
> -    componentViewsExportStr += `\nexport { default } from '${getEntry(rootDir, entryPath)}';`;
> +   componentViewsExportStr += `\nexport { default } from '${getEntry(rootDir, entryPath, true)}';`;
>     componentViewsImportStr = _componentViews
>       .map((component) => {
>         const componentNameFolder = camel2KebabComponentName(component);
>         const viewJsPath = path.resolve(rootDir, `${lowcodeDir}/${componentNameFolder}/view`);
>         return `import * as ${component}Data from '${viewJsPath}'`;
>       })
>       .join('\n');
> ```
> 
> getEntry的第三个调用点和getScss的唯一调用点：
> 
> ```diff
> +  const scssEntry = getScssEntry(rootDir, true);
> -  const scssEntry = getScssEntry(rootDir);
>   const viewPath = generateEntry({
>     template: 'view.js',
>     filename: 'view.js',
>     rootDir,
>     params: {
> -      entryPath: getEntry(rootDir, entryPath),
> +      entryPath: getEntry(rootDir, entryPath, true),
>       scssImport: scssEntry ? `import '${scssEntry}'` : '',
>       componentViews,
>       componentViewsExportStr,
>       componentViewsImportStr,
>       library,
>       execCompile,
>     },
>   });
> ```

非常棒，我改一下发个版本出来~

**Comment by w4ngzhen** [comment]
还需要补充下：
在750-760左右位置左右的componentViewsImportStr的viewJsPath = path.resolve也需要进行字符替换：
```diff
    componentViewsImportStr = _componentViews
      .map((component) => {
        const componentNameFolder = camel2KebabComponentName(component);
        const viewJsPath = path.resolve(rootDir, `${lowcodeDir}/${componentNameFolder}/view`);
       
-        return `import * as ${component}Data from '${viewJsPath}'`;
+        const normalizedViewJsPath = normalizePathTextForWindows(viewJsPath);
+        return `import * as ${component}Data from '${normalizedViewJsPath}'`;
      })
      .join('\n');
```

**Comment by geeeger** [comment]
我提一点，在通过@alilc/lowcode-material-parser 生成 lowcode/*/meta.ts文件的时候，ComponentMetadata.npm.main是不需要path.sep分隔符的，这里应该使用posix分隔符

path操作会自动使用当前系统分隔符

```diff
diff --git a/node_modules/@alilc/lowcode-material-parser/lib/generate.js b/node_modules/@alilc/lowcode-material-parser/lib/generate.js
index 2897980..8aa8087 100644
--- a/node_modules/@alilc/lowcode-material-parser/lib/generate.js
+++ b/node_modules/@alilc/lowcode-material-parser/lib/generate.js
@@ -20,6 +20,13 @@ async function default_1(matScanModel, matParsedModels, options) {
     return containerList;
 }
 exports.default = default_1;
+
+function coverToPosixSep(p) {
+    return p
+      .replace(/\\\\/g, '/')
+      .replace(/\\/g, '/');
+}
+
 /**
  * 生成 manifest
  *
@@ -41,9 +48,9 @@ async function genManifest(matScanModel, matParsedModel, options) {
             package: matScanModel.pkgName,
             version: matScanModel.pkgVersion,
             exportName: ((_a = matParsedModel.meta) === null || _a === void 0 ? void 0 : _a.exportName) || matParsedModel.componentName,
-            main: options.root && path.isAbsolute(matScanModel.mainFilePath)
+            main: coverToPosixSep(options.root && path.isAbsolute(matScanModel.mainFilePath)
                 ? path.relative(options.root, matScanModel.mainFilePath)
-                : matScanModel.mainFilePath,
+                : matScanModel.mainFilePath),
             destructuring: ((_b = matParsedModel.meta) === null || _b === void 0 ? void 0 : _b.exportName) !== 'default',
             subName: ((_c = matParsedModel.meta) === null || _c === void 0 ? void 0 : _c.subName) || '',
         },

```

**Comment by geeeger** [comment]
还有一个问题，我根据上面大佬的内容改了以后，发现执行lowcode:dev 在win下没法加载meta.js，翻了build cli的代码后看到最终的webpack配置 entry 入口飞了，也是上面一样的原因，分隔符问题。

build函数里找到meta路径以后会以'/'来分割生成entry key， 这就bug了。

```diff
diff --git a/node_modules/@alifd/build-plugin-lowcode/index.js b/node_modules/@alifd/build-plugin-lowcode/index.js
index 72f04f9..8dbc6ca 100644
--- a/node_modules/@alifd/build-plugin-lowcode/index.js
+++ b/node_modules/@alifd/build-plugin-lowcode/index.js
@@ -276,7 +276,7 @@ async function build(options, pluginOptions, execCompile) {
   );
   const metaPathMap = {};
   metaPaths.forEach((item) => {
-    metaPathMap[item.slice(item.lastIndexOf('/') + 1, item.lastIndexOf('.'))] = item;
+    metaPathMap[item.slice(item.lastIndexOf(path.sep) + 1, item.lastIndexOf('.'))] = item;
   });
   const result = {
     metaPathMap,
@@ -435,6 +435,14 @@ async function start(options, pluginOptions) {
   });
 }
```

**Comment by Jin-Yanhong** [comment]
我参考了上面大佬的做法，同样改了 `@alifd\build-plugin-lowcode\utils\index.js`  这个文件，但我是这样改的
![image](https://user-images.githubusercontent.com/106601426/172327405-f28b59b4-ea4b-49af-beb3-ed646e33a95b.png)

```js
function generateEntry({ template, filename = 'index.js', rootDir = process.cwd(), params }) {
  const hbsTemplatePath = path.join(__dirname, `../templates/${template}`);
  const hbsTemplateContent = fse.readFileSync(hbsTemplatePath, 'utf-8');
  const compileTemplateContent = hbs.compile(hbsTemplateContent);

  const tempDir = path.join(rootDir, '.tmp');
  const jsPath = path.join(tempDir, filename).replace(/\\/g,'/');
  //  下面这行代码，替换了原来的，反斜杠
  const jsTemplateContent = compileTemplateContent(params).replace(/\\/g,'/');
  fse.outputFileSync(jsPath, jsTemplateContent);
  return jsPath
}

```

**Comment by fov42550564** [comment]
最权威的解决方法，将代码保存到 correctNodeModules  在githbash中执行 chmod +x correctNodeModules  然后执行./correctNodeModules  
```bash
#!/bin/bash

vim -e -s ../node_modules/@alifd/build-plugin-lowcode/src/index.js \
-c ":%s#componentsImportStr,#componentsImportStr: componentsImportStr.replace(/\\\\\\\\/g, '/'),#" \
-c ":%s#componentViewsExportStr,#componentViewsExportStr: componentViewsExportStr.replace(/\\\\\\\\/g, '/'),#" \
-c ":%s#componentViewsImportStr,#componentViewsImportStr: componentViewsImportStr.replace(/\\\\\\\\/g, '/'),#" \
-c ":%s#getEntry(rootDir, entryPath),#getEntry(rootDir, entryPath).replace(/\\\\\\\\/g, '/'),#" \
-c ":%s#\${scssEntry}#\${scssEntry.replace(/\\\\\\\\/g, '/')}#" \
-c ":%s#item.lastIndexOf('/')#item.lastIndexOf('\\\\\\\\')#" \
-c ":wq"
```

**Comment by LuxinYing11** [comment]
> > > 
> > 
> > 
> > 哪个地方加的斜杠？我看看能不能在插件里兼容下
> 
> ![image](https://user-images.githubusercontent.com/6613429/163346589-7ec5386b-648f-4df1-a560-b1b29046c613.png) 我是在build-plugin-lowcode替换加上斜杆，不知道是不是handlebars 版本问题，斜杠被转义了

  啊？斜杆加在index.js的哪里，我不知道😢
