### ISSUE TITLE
mac下 clone启动项目，运行结果是一个目录结构

### ISSUE THREAD

**Issue by lancertea** [alibaba/lowcode-engine#302]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
mac下 clone启动项目，运行结果是一个目录结构
---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
按官网步骤clone、启动一个项目
---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为
预期是demo页面，实际是一个目录结构
---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
![1](https://user-images.githubusercontent.com/43966458/163094140-192b953d-6f14-4462-a642-3c4d4dbde8fd.jpeg)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本
低代码引擎版本：1.0.4
浏览器版本：Google Chrome 100.0.4896.75

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by zxb5102** [comment]
哈哈哈

**Comment by lancertea** [comment]
> 兄弟，再看下文档，引擎项目启动要代理到 demo 项目中调试

啊，看错了域名 =。=
