### ISSUE TITLE
[Bug] lowcode-engine v1.3.2 构建失败

### ISSUE THREAD

**Issue by Zsynuting** [alibaba/lowcode-engine#3028]
## **Describe the bug (required)** / **详细描述 bug（必填）**

lowcode-engine v1.3.2 构建失败

shell包构建失败，错误如下
<img width="1352" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/6938179/caa2a84d-b991-4ccc-b280-56a2eab0576d">

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

中文版示例：
1. checkout main 分支, git pull拉取最新代码 （当前最新版本 v1.3.2)
2. `npm i` ->  `npm run setup` -> `npm run build` 构建失败

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

可以成功构建

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本: `v1.3.2`
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本: `无关`
 - Browser [e.g. chrome, safari] / 浏览器版本 : `无关`
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本  `无关`

node 版本: 16.x

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by woshilaoge** [comment]
funsion 组件升级导致的 TS 类型不齐导致的编译报错。当前可以合并下 develop 分支，再次构建即可。
