### ISSUE TITLE
antd里面的modal组件推拽到画布中报错，无法渲染

### ISSUE THREAD

**Issue by 780853199** [alibaba/lowcode-engine#3029]
现象：使用物料脚手架生成的物料中使用antd里面的modal推拽到画布中报错，无法渲染
前置条件1、 npm init @alilc/element your-material-name 
               2、选择的是ant-组件库
配置过程：
![1715929632358](https://github.com/alibaba/lowcode-engine/assets/72066390/94a06dfb-258d-4974-9624-785e33033433)

附件为代码示例：
[lowcode-model.zip](https://github.com/alibaba/lowcode-engine/files/15345362/lowcode-model.zip)

**Comment by woshilaoge** [comment]
@780853199  这个问题有些麻烦，我这里统一回复下。（类似的问题还有 https://github.com/alibaba/lowcode-engine/issues/2781）
首先：上图所示这个终端打印的日志不是报错，是警告。不影响当前的组件渲染的。但是为啥没有如预期那样正式调试渲染？

1. 模态框、Drawer 等这类组件一版都是属于默认不渲染（显示），因此一版需要透传一个 props 的默认值（传给组件，让其在设计时，拖拽后就显示），比如你 Meta 中配置的 open: true。因此这类组件我们需要给其传入默认的 props 值，或者判断在 设计器环境强制覆盖下某个值，让其默认效果就显示，比如代码中的（比如下）
![image](https://github.com/alibaba/lowcode-engine/assets/22810511/f8784426-7b40-4805-a072-d1f062d2e6f7)
那为啥我们配置了，设计器拖拽还是未显示呢  ？ ？？
本地排查了下，原因非常巧合 Orz ；我们配置的显示（渲染）属性错了，（PS：肯定说没有，我查了 antd 4.x 文档是 open 这个属性标识显示和隐藏）应该要配置 visiable 。
>  ??? 因为你本地安装的 antd 是 4.x 的最新版本 4.24.16 （官方文档也是这个版本），但是你本地当前设计器加载的 antd 版本是 4.17.3 ，而这个版本恰好不支持 open 属性，只根据 visiable 显示（https://github.com/ant-design/ant-design/blob/6ea37b560cbdc59c14ac46b8dc38482ee49546fe/components/modal/Modal.tsx#L91）
![image](https://github.com/alibaba/lowcode-engine/assets/22810511/c8a2147e-86d2-466d-b912-bacc7d2dfe7a)

原因找到了，简单解释下为啥导致这样
1. antd 默认给做了 externals 处理，类似 "antd": "var window.antd"，因此你本地的代码就默认编译后取 window 下的了
2. 当前的本地启动的调试示例，默认注入了 antd  的资产包数据（即 4.17.3 版本的资源）

怎么解决？？
1. 最快，最简单，改下引入方式，自己手动改为类似如下（亲测可行，因为这样就走 npm 安装的资源了不会被 externals）
````js 
import OriginalModal from 'antd/lib/modal';
````
2. 使用 inject 模式。详细见[inject 调试](https://lowcode-engine.cn/site/docs/guide/expand/editor/cli#-%E5%9C%A8%E4%BD%8E%E4%BB%A3%E7%A0%81%E9%A1%B9%E7%9B%AE%E4%B8%AD%E8%B0%83%E8%AF%95%E7%89%A9%E6%96%99%E6%8F%92%E4%BB%B6%E8%AE%BE%E7%BD%AE%E5%99%A8) 即本地（或使用线上的）启动一个设计器，当前调试的组件动态注入到此设计器中调试。一般来说设计器可控，自行也可以修改。


PS：上述提供的代码中，这个描述配置写错了，多了一层 schema。
![image](https://github.com/alibaba/lowcode-engine/assets/22810511/17eecdd1-6557-4a33-a408-518a37c55a54)

以下是我本地调整后的效果
![image](https://github.com/alibaba/lowcode-engine/assets/22810511/84952d43-8794-4418-bec3-af433e975f2b)

**Comment by 780853199** [comment]
非常感谢！
