### ISSUE TITLE
自定义scss文件引入后，样式不生效

### ISSUE THREAD

**Issue by zyp0930** [alibaba/lowcode-engine#304]
## **Describe the bug (required)** / **详细描述 bug（必填）**
在lowcode-demo项目中

<img width="298" alt="WeChat5d85eccbc2c42a793437587ecce36a9d" src="https://user-images.githubusercontent.com/43630403/163136579-b745c035-0a5c-4a6a-a0e0-60cf612f48fc.png">
定义了一个样式，将这个样式写到global.scss中样式可以正常显示
<img width="817" alt="WeChat613f60d96cb84e6cbcb7898640019372" src="https://user-images.githubusercontent.com/43630403/163137159-b42068f3-8757-40cc-a276-5681655a0e09.png">
但是如果写到自定义的index.scss文件中样式无效
---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
在basic-antd/index.ts文件中引入样式文件，浏览器审查该元素标签样式，发现样式没有
Steps to reproduce the behavior: / 详细复现步骤：
在basic-antd/index.ts文件中引入样式文件，浏览器审查该元素标签样式，发现样式没有
---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
该样式能正常显示生效

---

## **Screenshots (optional)** / **bug 截图（可选）**
![image](https://user-images.githubusercontent.com/43630403/163138898-209a46fe-021e-4ecb-a12b-637fedd8fb12.png)
![image](https://user-images.githubusercontent.com/43630403/163138999-030127b2-5335-461b-819c-b08cf39b8203.png)
样式没有引入

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: 1.0.5
 - AliLowCodeEngineExt version: 1.0.3
 - Browser：100.0.4896.75（正式版本） (x86_64)
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by iDestin** [comment]
似乎并没有fix，目前依然有这个问题，物料的样式文件已经加载了但是并没有应用
