### ISSUE TITLE
组件间通信有通用解决方案么？

### ISSUE THREAD

**Issue by Qiang1996** [alibaba/lowcode-engine#305]
### 举两个场景：

1. 封装了两个业务组件，组件A的某个属性要数据绑定组件B的某个内部状态s1，如何把组件B的内部状态暴露出去并且让组件A以及其他任意组件都可以使用呢？

想到的一个解决方案：
给组件B的内部状态s1加个对应的事件onXxx来抛出内部状态s1的值，然后在编辑器的源码编辑里加个对应的状态s2和事件处理函数，事件处理函数绑定到onXxx上接收S1的值，然后`this.setState({ s2: value })`，其他组件通过绑定`this.state.s2`来和组件B通信。

不过这个这个解决方案比较麻烦，有其他的通用解决方案么？

2. 和第一个场景类似，组件A要调用组件B的某个方法

想到的解决方案也和上一个场景的解决方案类似，组件B通过`ref`把一些内部方法暴露出去，其他组件通过编辑器的源码编辑调用

**有没有官方解决方案或者哪位兄弟有更好的实践，求分享**

**Comment by LeoYuan** [comment]
我理解这就是 React 的状态管理的哲学，要么把 state 提升成多个组件共用，要么通过 onXxx + ref 去直接操作其他组件的实例方法，缺点就是耦合，看你自己的需求了~

**Comment by mark-ck** [comment]
可以看看答疑专场那期直播回放 36:07 秒开始有讨论这个方案的问题，并且演示了 ref 的用法 https://www.bilibili.com/video/BV1k34y1v7YX/
