### ISSUE TITLE
没有找到 @alifd/build-plugin-lowcode 包的文档

### ISSUE THREAD

**Issue by toviLau** [alibaba/lowcode-engine#306]
麻烦大佬把@alifd/build-plugin-lowcode插件的文档开放出来,谢谢啦。

**Comment by mark-ck** [comment]
可以先看这个，我后面补充完整 https://fusion.design/help.html/iuu6cm#xJBge

**Comment by FmaBauer** [comment]
太好啦，找到文档啦
