### ISSUE TITLE
安装包时出现部分node版本不兼容问题

### ISSUE THREAD

**Issue by scottdao** [alibaba/lowcode-engine#3087]
通过git clone 源码，通过yarn进行安装出现问题

我用nvm切换为node版本16.16.0，通过yarn安装包会报错：cheerio@1.0.0: The engine "node" is incompatible with this module. Expected version ">=18.17". Got "16.16.0"

将包切换到18.20.4版本时，通过yarn安装会报错：error @: The engine "node" is incompatible with this module. Expected version ">=14.17.0 <18". Got "18.20.4"

**Comment by scottdao** [comment]
![image](https://github.com/user-attachments/assets/cf3fe061-787a-43b7-aeaf-aedb51215a6d)

**Comment by scottdao** [comment]
![EC9D1C57-85B6-4bc0-A0D4-58E637A1CD59](https://github.com/user-attachments/assets/1b4a39e2-8e3f-44e3-aeea-8aee28cf1274)

**Comment by barryzhang123** [comment]
@scottdao 麻烦问下怎么解决的
