### ISSUE TITLE
从main拉取最新分支后，进入code-generator安装依赖并打包失败

### ISSUE THREAD

**Issue by luckysmithlee** [alibaba/lowcode-engine#3088]
直接拉取分支main，进入/modules/code-generator安装执行npm i 依赖，安装完成后执行npm run build 编译失败

中文版示例：
1. git clone https://github.com/alibaba/lowcode-engine.git
2. npm i
3. 进入/modules/code-generator 执行npm i
4. 在/modules/code-generator目录执行 npm run build 

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为
正常完成打包
---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
<img width="1284" alt="image" src="https://github.com/user-attachments/assets/444ffd53-fba2-42fc-871c-1e8652a464c0">
<img width="1421" alt="image" src="https://github.com/user-attachments/assets/1efcaffc-00c8-451b-82ac-4ee8c72f8534">
<img width="1229" alt="image" src="https://github.com/user-attachments/assets/c86dcb86-11d7-4940-a9bb-e9fdc02d5e2d">

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - main分支最新版

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题
当我把这个包移动到一个单独的文件夹再次build
<img width="1264" alt="image" src="https://github.com/user-attachments/assets/23d8a631-5d9e-4e58-b2fa-6f5814ced3b9">
我在下面三个文件增加了：platform: 'node',其他均未修改，

<img width="937" alt="image" src="https://github.com/user-attachments/assets/e7287517-a93f-4598-9c68-e0b1466ca676">
<img width="975" alt="image" src="https://github.com/user-attachments/assets/c8384618-e6fb-40af-add7-fba7d624ae2d">
<img width="1007" alt="image" src="https://github.com/user-attachments/assets/0e6bd42a-9def-4e8a-aed0-18e0007e5ab3">

再次执行build结果如下：
<img width="968" alt="image" src="https://github.com/user-attachments/assets/42c2e695-0bd3-47af-bad8-a132818ef40c">

此时dist、lib、es文件夹如下：
<img width="444" alt="image" src="https://github.com/user-attachments/assets/bff64839-5c66-487a-ae10-17d81f30eeff">

将打包产物替换项目的依赖资源后运行报错：
![IMG_1077](https://github.com/user-attachments/assets/3bab8578-cd0b-4eab-a9c4-48b42eb4aeca)
使用npm包则无此报错

经过一番排查，猜测应该是打包配置不正确导致，麻烦帮忙看下

**Comment by scottdao** [comment]
你的node版本是多少呢？

**Comment by luckysmithlee** [comment]
这是来自QQ邮箱的自动回复邮件。
 
您好，我已收到你的邮件。

**Comment by luckysmithlee** [comment]
> 你的node版本是多少呢？

我将node切换到14.21.3后，在当前环境是可以使用的，感谢答复
