### ISSUE TITLE
高级表单组件，将其中一个输入框表单项修改为选择器表单项后，右侧属性面板中找不到默认值配置项了

### ISSUE THREAD

**Issue by HAY0526** [alibaba/lowcode-engine#309]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

选择高级表单组件， 默认拖进来会有六个输入框，将其中一个输入框表单项修改为选择器表单项后  右侧属性面板中的组件配置中的默认值配置项没有了  如果想要配置默认选中选项中的一项，就必须在schema中相应的地方加上defaultvalue属性去配置  想问能不能在面板中加上这个默认值配置。但是在原子物料中只拖入一个选择器时右侧是有默认值配置项的

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

1.拖入高级表单组件
2.将其中一个输入框表单项修改为选择器（select）表单项
3.右侧属性面板中找不到默认值配置项了

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

希望和原子物料中的选择器一样，被拖入后，右侧是有默认值配置项的

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

![image](https://user-images.githubusercontent.com/34828918/163307072-e4d0c29b-e1f9-4a4f-8b56-fcda9ad19955.png)
![image](https://user-images.githubusercontent.com/34828918/163307237-ac65ca7a-15a7-4442-80a6-06c90db4f2c4.png)
![image](https://user-images.githubusercontent.com/34828918/163307629-581e7b11-693c-4cc3-bb0c-933ee1b38226.png)

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
官方示例：https://lowcode-engine.cn/demo/index.html

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by LeoYuan** [comment]
@mark-ck 麻烦判断下是不是 bug？

**Comment by mark-ck** [comment]
我看了下，“选择器”确实没有默认值的配置，我可以加一下，不过对于物料的问题，如果是有 bug 我们会排期解决，如果是功能需求我们基本上不会接收，并且整体排期迭代会比较慢，这个是由于内部资源调配的问题，希望理解。

**Comment by HAY0526** [comment]
嗯嗯 理解  我们自己通过修改相应的meta.js给加上了
