### ISSUE TITLE
自定义的数据源列表应该挂载到哪里,有没有详细的示例或文档

### ISSUE THREAD

**Issue by 329697166** [alibaba/lowcode-engine#310]
![image](https://user-images.githubusercontent.com/8613493/163334579-8c8c8694-07c8-4970-abfd-a9e7babed7a6.png)

**Comment by 329697166** [comment]
刚看完昨晚的录播,这个issues是我们这边觉得原来的数据源不符合我们这边的需求,然后改造了一个自定义的数据源界面,现在是不知道该怎么把api列表转到低代码的dataSourceMap里面,想问一下有没有详细的示例和文档

**Comment by liujuping** [comment]
看看更改的时候有没有成功改变协议，https://lowcode-engine.cn/lowcode#233-%E5%AE%B9%E5%99%A8%E7%BB%93%E6%9E%84%E6%8F%8F%E8%BF%B0-a

可以参考原来的数据源面板。

**Comment by xingmolu** [comment]
这里涉及到两个方面：
1. 设计态定制：主要是数据源面板里编辑数据源信息，编辑的协议可以参考：低代码协议 ComponentDataSourceItem部分；面板编辑保存后将信息更新到低代码Schema中；
2. 运行态定制，详细可以参考：https://www.yuque.com/lce/usage/datasource#VHlog

**Comment by 329697166** [comment]
@xingmolu 在低代码协议ComponentDataSourceItem还是没有找到设计态怎么将接口转到schema上面

**Comment by 329697166** [comment]
问题已经解决了
