### ISSUE TITLE
设置器中的【布局模式】点击无效

### ISSUE THREAD

**Issue by yaoboqin** [alibaba/lowcode-engine#311]
![image](https://user-images.githubusercontent.com/8731738/163334381-3ac0fb90-318c-4dba-99a4-0879ca1a9019.png)
在lowcode-demo，基础fusion组件场景下，发现有在容器组件中有【标准模式】组件，点击后，右侧设置器有布局模式的选择，但是点击无效，这个布局模式很常用，希望能尽快修复

**Comment by mark-ck** [comment]
fixed
