### ISSUE TITLE
能否支持主题色配置？

### ISSUE THREAD

**Issue by taolei1990** [alibaba/lowcode-engine#313]
![1649924007(1)](https://user-images.githubusercontent.com/23173640/163343253-e2cdc91a-9d1d-4283-8521-90963531c8bd.jpg)

默认的选择状态想改成其他颜色 该怎么实现呢

**Comment by mark-ck** [comment]
支持主题配置，可以看我这期答疑专场 00:30 开始有讲解 https://www.bilibili.com/video/BV1k34y1v7YX/

**Comment by xmsz** [comment]
能不能直接在线配置额外assets，想更加动态一点，不想写在项目里
