### ISSUE TITLE
容器组件无法拖入段落？

### ISSUE THREAD

**Issue by ah-wq** [alibaba/lowcode-engine#314]
在一个容器组件中无法拖入一个段落？请问这个是否是正常逻辑？
<img width="979" alt="截屏2022-04-14 下午9 50 01" src="https://user-images.githubusercontent.com/20314753/163404876-542b6183-d18c-4fec-bd2e-2aa1bd2e6d35.png">

**Comment by mark-ck** [comment]
是正常逻辑，这是 by design 的，可以根据组件低代码描述协议的规定配置组件的 childWhiteList
