### ISSUE TITLE
【bug】出码一直 loading

### ISSUE THREAD

**Issue by jiangtao** [alibaba/lowcode-engine#318]
## **Describe the bug (required)** / **详细描述 bug（必填）**

地址： https://lowcode-engine.cn/demo/index.html

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

进入 demo，点击出码
<img width="1075" alt="image" src="https://user-images.githubusercontent.com/2155745/163513863-5f38eb12-409f-4220-bee1-e4e20121e609.png">

**Comment by Clarence-pan** [comment]
我刚刚试了下是好的，麻烦打开浏览器的 devtools 看看控制台和网络里有没有啥报错？

**Comment by jiangtao** [comment]
> 

<img width="1748" alt="image" src="https://user-images.githubusercontent.com/2155745/164968944-517fc432-854f-4c6b-873d-9460d1df3aed.png">

**Comment by liujuping** [comment]
我这边也是ok的，辛苦描述一下有没有进行额外的操作。如果没有用隐私窗口打开试一下。
