### ISSUE TITLE
数据源 willFetch 没有执行

### ISSUE THREAD

**Issue by twinkle77** [alibaba/lowcode-engine#319]
## **Describe the bug (required)** / **详细描述 bug（必填）**

<img width="915" alt="image" src="https://user-images.githubusercontent.com/17792166/163515434-31d1ca43-a0ae-404f-8286-74c463d573e6.png">

看了下代码，原因是： ReactRenderer 没有传 appHelper

![image](https://user-images.githubusercontent.com/17792166/163516193-4bcdafc7-15b8-4c71-81f5-83ad7f8f6d44.png)

更改如下就可以了：

<img width="641" alt="image" src="https://user-images.githubusercontent.com/17792166/163516241-f82ba13d-38e7-4c88-9378-0e3099ce2ca7.png">

问题：
为什么 ReactRenderer 默认不是走 lowcode-datasource-engine 的逻辑

**Comment by xingmolu** [comment]
嗨，请问下是否在设计态的时候请求没有执行willFetch吗？还是说预览态哈

**Comment by xingmolu** [comment]
请根据文档设置设计态开启数据源引擎
https://www.yuque.com/lce/usage/datasource#xo5DC

**Comment by sundi78634** [comment]
@xingmolu 看文档是如何定制fetch的，shouldFetch 和 willFetch没有调用不是这个原因吧？
engine dataHelper中只有dataHandler的处理，没有其他钩子的。

**Comment by xingmolu** [comment]
@sundi78634 代码里有的，https://github.com/alibaba/lowcode-datasource/blob/main/packages/datasource-engine/src/core/RuntimeDataSourceItem.ts#L92

你是在设计态的情况下没有触发吧？

**Comment by sundi78634** [comment]
@xingmolu 原来在这里处理，多谢。
设计态是指在editor中吗？编辑和预览都没有调用。

**Comment by xingmolu** [comment]
@sundi78634 设计态是指editor中，编辑中没有调用，需要按照文档手动启用下数据源引擎（后面demo中我们加上这个）；预览没调用，麻烦给个demo看下；

**Comment by sundi78634** [comment]
@xingmolu [lowcode-demo](https://github.com/alibaba/lowcode-demo)main分支`npm run start`可复现，注意demo本地启动为http服务，请求https url有跨域问题。
在线demo后边有时间补上。
