### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by leehomeok** [alibaba/lowcode-engine#32]
有一些 @ali/*  的依赖包没改，
启动后报错  1.TypeError: Cannot set property components of [object Module] which has only a getter
2.process is not defined

**Comment by LeoYuan** [comment]
如何复现？

**Comment by leehomeok** [comment]
> 如何复现？

"@ali/ali-lowcode-materials": "^1.0.26", 
这个依赖包应该是内部NPM的包吧？ 我直接删掉了，下载好其他依赖跑起来，就报了上面2个错误
