### ISSUE TITLE
出码工程，启动报错

### ISSUE THREAD

**Issue by markyun** [alibaba/lowcode-engine#321]
## **Describe the bug (required)** / **详细描述 bug（必填）**

出码后的工程，编译成功，但启动报错

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

run start ok
![image](https://user-images.githubusercontent.com/2833137/163556505-9971649c-0637-4224-9e3b-74f4367201ad.png)

浏览器打开 报错

![image](https://user-images.githubusercontent.com/2833137/163556569-52179121-0f2c-43eb-8521-609fc728d211.png)
![image](https://user-images.githubusercontent.com/2833137/163556601-89411e78-db92-42c5-96a2-5a1782669a76.png)

end.

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by markyun** [comment]
ps:有没有官方支持的钉钉群，或者微信群

**Comment by liujuping** [comment]
> ps:有没有官方支持的钉钉群，或者微信群

看看官网底部。

**Comment by LeoYuan** [comment]
麻烦说一下具体是哪个 demo 场景？在场景上做了什么操作？schema 不同，问题不同

**Comment by markyun** [comment]
@LeoYuan @github-actions ，好的，具体demo是这个库：https://github.com/alibaba/lowcode-demo，

启动运行后，默认点击出码按钮，即可复现。

**Comment by Clarence-pan** [comment]
@markyun 我刚刚试了下，真的无法复现…… 帮忙提供下更多相关信息吧

![image](https://user-images.githubusercontent.com/8750132/163999493-8dcb0653-14d4-487c-81a4-d5229ace53c9.png)

**Comment by markyun** [comment]
@LeoYuan  我更新了库之后，重新出码现在报 【@alilc/lowcode-materials】这个依赖包的错误了。

![image](https://user-images.githubusercontent.com/2833137/164143530-91fc8edd-b42f-464f-9be7-893d125bfd95.png)

**Comment by markyun** [comment]
出码预览也会报错： Slot is not defined


![image](https://user-images.githubusercontent.com/2833137/164145520-6b69332c-9bb8-4580-8262-29ae7bb175be.png)

**Comment by LeoYuan** [comment]
更新到 main 分支最新版，Slot 问题修复了~

**Comment by LeoYuan** [comment]
@markyun 是不是 antd 场景？
