### ISSUE TITLE
setAssets 出现 Cannot read property 'Icon' of Undefined 报错

### ISSUE THREAD

**Issue by zhugenqiang** [alibaba/lowcode-engine#322]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
直接用物料脚手架工具打的包，在demo中通过fetch 方式动态引入报错

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

const editorInit = (ctx: ILowCodePluginContext) => {
    return {
      name: 'editor-init',
      async init() {
        // 修改面包屑组件的分隔符属性setter
        const assets1 = await (
          await fetch(
            `http://127.0.0.1:5500/build/assets-dev.json`
          )
        ).text();
        // 设置物料描述
        const { material, project } = ctx;

        material.setAssets(await injectAssets(assets1));
        //material.loadIncrementalAssets(await injectAssets(assets1));

        const schema = await getPageSchema();

        // 加载 schema
        project.openDocument(schema);
      },
    };
  }
assets-dev.json 内容:
{
  "packages": [
    {
      "package": "matest",
      "version": "0.1.0",
      "library": "Matest",
      "urls": [
        "http://127.0.0.1:5500/build/view.js",
        "http://127.0.0.1:5500/build/view.css"
      ],
      "editUrls": [
        "http://127.0.0.1:5500/build/view.js",
        "http://127.0.0.1:5500/build/view.css"
      ]
    }
  ],
  "components": [
    {
      "exportName": "MatestMeta",
      "npm": {
        "package": "matest",
        "version": "0.1.0"
      },
      "url": "http://127.0.0.1:5500/build/meta.js",
      "urls": {
        "default": "http://127.0.0.1:5500/build/meta.js"
      }
    }
  ],
  "sort": {
    "groupList": [
      "精选组件",
      "原子组件"
    ],
    "categoryList": [
      "基础元素",
      "布局容器类",
      "表格类",
      "表单详情类",
      "帮助类",
      "对话框类",
      "业务类",
      "通用",
      "引导",
      "信息输入",
      "信息展示",
      "信息反馈"
    ]
  },
  "groupList": [
    "精选组件",
    "原子组件"
  ],
  "ignoreComponents": {}
}

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

希望能够正确解析并显示组件

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

![image](https://user-images.githubusercontent.com/9514065/163563110-3ffeb235-0b68-4b3b-84b7-437adf101ff7.png)

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.1] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.2] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

**Comment by liujuping** [comment]
下述资产包是必须的

{
      "title": "fusion组件库",
      "package": "@alifd/next",
      "version": "1.23.0",
      "urls": [
        "https://g.alicdn.com/code/lib/alifd__next/1.23.18/next.min.css",
        "https://g.alicdn.com/code/lib/alifd__next/1.23.18/next-with-locales.min.js"
      ],
      "library": "Next"
    },
