### ISSUE TITLE
base-renderer方法渲染报错, 提示Warning: Each child in a list should have a unique "key" prop.

### ISSUE THREAD

**Issue by Juster5** [alibaba/lowcode-engine#323]
用umi搭建的项目, 在引入lowcode-engine引擎后报错, 但是不影响使用, 很多地方都报了这个错误

devScripts.js:6523 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `base-renderer`. See https://fb.me/react-warning-keys for more information.
    in div (created by base-renderer)
    in base-renderer (created by t)
    in ConfigProvider (created by t)
    in t (created by n)
    in n (created by Context.Consumer)
    in t (created by n)
    in t (created by n)
    in n (created by n)
    in n (created by n)
    in t (created by n)

devScripts.js:6523 Warning: React does not recognize the `__designMode` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `__designmode` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in span (created by ForwardRef(e))
    in ForwardRef(e) (created by NextText)
    in NextText (created by ForwardRef)
    in ForwardRef (created by base-renderer)
    in div (created by Paragraph)
    in Paragraph (created by e)
    in e (created by n)
    in n (created by NextP)
    in NextP (created by ForwardRef)
    in ForwardRef (created by base-renderer)
    in div (created by ForwardRef(e))
    in ForwardRef(e) (created by e)
    in e (created by n)
    in n (created by NextCol)
    in NextCol (created by ForwardRef)
    in ForwardRef (created by base-renderer)
    in div (created by ForwardRef(e))
    in ForwardRef(e) (created by e)
    in e (created by n)
    in n (created by NextRow)
    in NextRow (created by ForwardRef)
    in ForwardRef (created by base-renderer)
    in div (created by ForwardRef(e))
    in ForwardRef(e) (created by e)
    in e (created by n)
    in n (created by NextRowColContainer)

**Comment by Juster5** [comment]
__designMode, 用umi框架启动, 类似这种属性没有转换成小写, 不知道是哪个步骤出错了

**Comment by Juster5** [comment]
仓库地址如下, 只要yarn一下, 就可以跑, 麻烦大佬看一下
https://github.com/Juster5/umi-lowcode-demo

**Comment by Gxiaomin** [comment]
这个问题解决了吗楼主？遇到同样问题

**Comment by Juster5** [comment]
没有哦，在等他们看



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Gxiaomin ***@***.***&gt;
发送时间: 2022年4月20日 09:21
收件人: alibaba/lowcode-engine ***@***.***&gt;
抄送: Juster5 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [alibaba/lowcode-engine] base-renderer方法渲染报错, 提示Warning: Each child in a list should have a unique "key" prop. (Issue #323)





 
这个问题解决了吗楼主？遇到同样问题

**Comment by LeoYuan** [comment]
用 react production 是不是就没有这些 warning 了？哈哈😃

**Comment by Juster5** [comment]
也有的吧，官方提供的demo就是用develop的react版本



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: LeoYuan 袁力皓 ***@***.***&gt;
发送时间: 2022年4月21日 21:17
收件人: alibaba/lowcode-engine ***@***.***&gt;
抄送: Juster5 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [alibaba/lowcode-engine] base-renderer方法渲染报错, 提示Warning: Each child in a list should have a unique "key" prop. (Issue #323)

**Comment by Juster5** [comment]
> 用 react production 是不是就没有这些 warning 了？哈哈😃

TypeError: Cannot read properties of undefined (reading 'createContext')
Module.<anonymous>
./node_modules/mini-create-react-context/dist/esm/index.js:174
  171 |   };
  172 | }
  173 | 
> 174 | var index = React.createContext || createReactContext;
  175 | 
  176 | export default index;
  177 | 
View compiled
Module../node_modules/mini-create-react-context/dist/esm/index.js
http://localhost:8002/umi.js:261120:30
__webpack_require__
./webpack/bootstrap:789
  786 | };
  787 | 
  788 | // Execute the module function
> 789 | modules[moduleId].call(module.exports, module, module.exports, hotCreateRequire(moduleId));
      | ^  790 | 
  791 | // Flag the module as loaded
  792 | module.l = true;
换成production就有这些新的报错, 而且还启动不了页面

**Comment by Juster5** [comment]
@liujuping 请问现在这个问题解决了?

**Comment by liujuping** [comment]
可以使用 react production 版本的资源。

**Comment by Juster5** [comment]
<!-- React，可替换为 production 包 --&gt;
  <script src="https://g.alicdn.com/code/lib/react/16.13.1/umd/react.production.js"&gt;</script&gt;
  <!-- React DOM，可替换为 production 包 --&gt;
  <script src="https://g.alicdn.com/code/lib/react-dom/16.13.1/umd/react-dom.production.js"&gt;</script&gt;


你们用的是哪个版本的? 我直接把链接改成production, 但是报了这个



------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/lowcode-engine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月5日(星期四) 上午10:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/lowcode-engine] base-renderer方法渲染报错, 提示Warning: Each child in a list should have a unique "key" prop. (Issue #323)





 
可以使用 react production 版本的资源。

**Comment by liujuping** [comment]
可以点开看报错信息，使用的是什么版本的。可能没有成功使用 production 版本的。

![image](https://user-images.githubusercontent.com/11935995/166858217-8cdcb788-40e6-466d-8989-16cf7611d149.png)

**Comment by Juster5** [comment]
可以啦，谢谢呀



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: 絮黎 ***@***.***&gt;
发送时间: 2022年5月5日 11:08
收件人: alibaba/lowcode-engine ***@***.***&gt;
抄送: Juster5 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [alibaba/lowcode-engine] base-renderer方法渲染报错, 提示Warning: Each child in a list should have a unique "key" prop. (Issue #323)





 
可以点开看报错信息，使用的是什么版本的。可能没有成功使用 production 版本的。

**Comment by WHSnhcZDYRZC** [comment]
可以去看下这个库的解决方案哦
https://github.com/WHSnhcZDYRZC/umi4-lowcode-engine-solutions

**Comment by WHSnhcZDYRZC** [comment]
> 可以点开看报错信息，使用的是哪个版本的。可能没有成功使用生产版本的。
> 
> ![图像](https://user-images.githubusercontent.com/11935995/166858217-8cdcb788-40e6-466d-8989-16cf7611d149.png)

能推一下这个库吗？我之前做低代码开发时查询了很多 iss 发现没有一套比较好的解决方方案，所以我项目开发完成之后，写了一套解决方案，这个库是我总结的，并且后续准备维护。
