### ISSUE TITLE
Demo出码加载报错“Slot is not defined”

### ISSUE THREAD

**Issue by nemo2000** [alibaba/lowcode-engine#325]
<img width="756" alt="image" src="https://user-images.githubusercontent.com/6717856/163669814-2c949ad5-7942-4268-9cb7-fd8cb164cafb.png">

**Comment by LeoYuan** [comment]
假如引擎导出的 componentsMap 把 Slot 排除掉，能不能避免这个问题？会不会有新问题？
@Clarence-pan

**Comment by markyun** [comment]
@LeoYuan  我的问题和它一样。

**Comment by Clarence-pan** [comment]
![image](https://user-images.githubusercontent.com/8750132/163998370-f850116c-969a-40c8-b62c-520719e825a0.png)


现在我看已经没有 `<Slot>` 了，已经解决了吧？

**Comment by LeoYuan** [comment]
已解决😃

**Comment by Sapphire2k** [comment]
<img width="816" alt="image" src="https://user-images.githubusercontent.com/17328005/165294339-c808e7e7-a65c-4b26-bce3-d39c613212c0.png">
<img width="986" alt="image" src="https://user-images.githubusercontent.com/17328005/165294478-2d95c63e-79b3-4f7b-99bc-f82bab1c2f03.png">

不知道是不是一个问题，编辑了源码+绑定了数据源，出码预览报错了

**Comment by LeoYuan** [comment]
> <img width="816" alt="image" src="https://user-images.githubusercontent.com/17328005/165294339-c808e7e7-a65c-4b26-bce3-d39c613212c0.png">
> 
> <img width="986" alt="image" src="https://user-images.githubusercontent.com/17328005/165294478-2d95c63e-79b3-4f7b-99bc-f82bab1c2f03.png">
> 
> 
> 
> 不知道是不是一个问题，编辑了源码+绑定了数据源，出码预览报错了

最新的demo再试下
