### ISSUE TITLE
Antd Timeline.Item 未加 category 

### ISSUE THREAD

**Issue by twinkle77** [alibaba/lowcode-engine#328]
## **Describe the bug (required)** / **详细描述 bug（必填）**

![image](https://user-images.githubusercontent.com/17792166/163755221-2176178c-bebe-491c-9465-169f1c57f1b0.png)

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

```bash
git clone https://github.com/alibaba/lowcode-materials

cd packages/antd-lowcode-materials

npm run lowcode:dev
```

主要是这行代码造成的： https://github.com/alibaba/lowcode-materials/blob/main/packages/antd-lowcode-materials/lowcode/timeline.item/meta.ts#L7

**Comment by twinkle77** [comment]
而金蝉给的 antd 物料 demo 却没有这个 bug.  https://alifd.alicdn.com/npm/@alilc/antd-lowcode-materials@1.0.3/build/lowcode/index.html

**Comment by hujiulong** [comment]
timeline.item 的 category 是特意设为空的，因为 timeline.item 不能单独使用，所以不展示在物料面板里
