### ISSUE TITLE
有概率不能正常渲染组件

### ISSUE THREAD

**Issue by vs0533** [alibaba/lowcode-engine#329]
## **Describe the bug (required)** / **详细描述 bug（必填）**
点击preview有大概率无法正常渲染组件

下面是正常渲染
<img width="259" alt="截屏2022-04-18 12 42 48" src="https://user-images.githubusercontent.com/13310483/163755770-06510b5e-2665-41da-897a-c9dd9627288b.png">

下面是无法正常渲染
<img width="299" alt="截屏2022-04-18 12 42 42" src="https://user-images.githubusercontent.com/13310483/163755781-4454337c-08a0-4ab7-99f2-725cf4be75e9.png">

下面是出现无法正常渲染时的调试状态
<img width="1122" alt="截屏2022-04-18 12 46 04" src="https://user-images.githubusercontent.com/13310483/163755919-e0a57c20-5d1b-458c-b634-424ece422ef1.png">

同时伴随大量的错误信息
<img width="1679" alt="截屏2022-04-18 12 47 27" src="https://user-images.githubusercontent.com/13310483/163756010-f6b992e0-a1eb-45e1-961f-2c826e5f2eba.png">

**Comment by liujuping** [comment]
需要提供复现的路径或者 schema

**Comment by vs0533** [comment]
1.git clone lowcode-demo
2./lowcode-demo/src/scenarios/index/index.ts 
使用basic-antd 
`import registerPlugins from '../../scenarios/basic-antd/plugin';`
3.打开编辑器 拖入第一个主要按钮
4.点击preview预览
5.打开chrome调试工具
**6.勾选禁用缓存**
7.多次刷新页面有几率出现该bug

不勾选禁用缓存小几率出现

**Comment by w4ngzhen** [comment]
同样的情况，怀疑是异步加载无聊出现了时序问题

**Comment by markyun** [comment]
同样的情况+1

**Comment by windssea** [comment]
同样的情况+1

**Comment by liujuping** [comment]
问题原因：资源加载顺序和执行顺序不一致到的。

我们需要加载的资源如下：

![image](https://user-images.githubusercontent.com/11935995/165219052-8afe930a-6df5-45df-a9f4-4b74eb6dacab.png)

其中 antd-lowcode/view.js 依赖 [4]ant-design-icons-cdn/4.5.0/index.umd.min.js 和  [3]antd.min.js

当 antd 和 icons 加载完成之后再执行 antd-lowcode/view.js 会正常渲染，当资源没有加载完成就执行  antd-lowcode/view.js 会出现报错，相关资源无法正确解析，渲染出现异常。

**Comment by haoziqaq** [comment]
同样的情况+1

**Comment by FmaBauer** [comment]
这个问题看起来比较严重呀，我们引擎设计时候忽略这个点了？物料资源加载是不是需要能够指定顺序？

**Comment by fxhfwf** [comment]
想问下，各位大佬有没有暂时的解决方法呀？

**Comment by liujuping** [comment]
> 想问下，各位大佬有没有暂时的解决方法呀？

可以参考这个，改一下项目。https://github.com/alibaba/lowcode-demo/pull/19

**Comment by haoziqaq** [comment]
@liujuping 我按照它修改了，依然会出现这个问题，资源加载顺序应该是对的。

<img width="1318" alt="image" src="https://user-images.githubusercontent.com/24223652/166861385-73983e60-4ba8-414f-a688-a224bb30ec84.png">
<img width="1392" alt="image" src="https://user-images.githubusercontent.com/24223652/166861583-c72c5972-c3b4-4955-b3c0-bfdf052e3ed8.png">

**Comment by haoziqaq** [comment]
@liujuping 我确定资源加载已经变成了串行的加载

**Comment by liujuping** [comment]
的确是没有 Slot 这个组件的，exportSchema 方法需要加上 Save 的参数，可以看看 demo 最新的代码。

**Comment by haoziqaq** [comment]
好的

**Comment by haoziqaq** [comment]
<img width="1189" alt="image" src="https://user-images.githubusercontent.com/24223652/166862709-9f48c7e7-0ccd-4c18-92c0-294fc778cddd.png">

官方的demo似乎也有问题，复现方式是

1.拉一个按钮
2.点一下源码面板，然后关闭，自动保存
3.预览

就出错了

**Comment by liujuping** [comment]
这个已知，近期会修复。https://github.com/alibaba/lowcode-engine/issues/416

**Comment by haoziqaq** [comment]
好的

**Comment by haoziqaq** [comment]
这个是否是物料包的问题，我要追踪一下具体问题原因，我现在需要基于 antd 的物料去二次开发，刚刚上了点手，希望也可能参与到开源贡献之中

**Comment by liujuping** [comment]
源码面板的问题，不是物料包问题，是插件问题。可以看看这个issue的详情，https://github.com/alibaba/lowcode-engine/issues/367#issuecomment-1109451376

**Comment by haoziqaq** [comment]
多谢

**Comment by fxhfwf** [comment]
没有看到这个https://github.com/alibaba/lowcode-demo/pull/19这个里面有什么东西可以参考
![image](https://user-images.githubusercontent.com/40874982/166882502-d446b399-d5c4-4e03-b183-45e936f643c6.png)

**Comment by liujuping** [comment]
> 没有看到这个[https://github.com/alibaba/lowcode-demo/pull/19这个里面有什么东西可以参考](https://github.com/alibaba/lowcode-demo/pull/19%E8%BF%99%E4%B8%AA%E9%87%8C%E9%9D%A2%E6%9C%89%E4%BB%80%E4%B9%88%E4%B8%9C%E8%A5%BF%E5%8F%AF%E4%BB%A5%E5%8F%82%E8%80%83) ![image](https://user-images.githubusercontent.com/40874982/166882502-d446b399-d5c4-4e03-b183-45e936f643c6.png)

看看变更的代码，可以先临时将资源加载改成串行的。

![image](https://user-images.githubusercontent.com/11935995/166882708-316497f8-8163-497e-b618-048bdaa3f2fe.png)

**Comment by liujuping** [comment]
fixed in lowcode-engine@1.0.8。

使用 1.0.8 版本的引擎即可，不需要修改 demo 相关的代码。
