### ISSUE TITLE
找不到createProjectBuilder函数

### ISSUE THREAD

**Issue by David444588** [alibaba/lowcode-engine#330]
![image](https://user-images.githubusercontent.com/103245240/163780173-82d2416b-4b8e-4c3f-83a5-ee9b99bfdfa8.png)
这个函数找不到

**Comment by LeoYuan** [comment]
我理解这些函数需要根据 Vue 的情况单独都实现一遍，是吧？ @Clarence-pan

**Comment by David444588** [comment]
是的，公司低代码项目需要vue出码，但是我看了文档却找不到入口，是不是改了函数名了？

**Comment by David444588** [comment]
> 我理解这些函数需要根据 Vue 的情况单独都实现一遍，是吧？ @Clarence-pan

是的，公司低代码项目需要vue出码，但是我看了文档却找不到入口，是不是改了函数名了？

**Comment by liujuping** [comment]
点开文档中的链接就可以看到了。

**Comment by David444588** [comment]
我有看文档，上面写了在createProjectBuilder函数修改，但是我在工程中搜索不到这个函数

> 点开文档中的链接就可以看到了。

**Comment by liujuping** [comment]
https://github.com/alibaba/lowcode-engine/blob/main/modules/code-generator/src/generator/ProjectBuilder.ts

**Comment by Clarence-pan** [comment]
![image](https://user-images.githubusercontent.com/8750132/163999999-daeeac94-d731-43af-9cde-170a016ff8e1.png)


> > 我理解这些函数需要根据 Vue 的情况单独都实现一遍，是吧？ @Clarence-pan
> 
> 是的，公司低代码项目需要vue出码，但是我看了文档却找不到入口，是不是改了函数名了？

**Comment by David444588** [comment]
> 

是的，你们那边能给出一些指引或者解决方案吗？
