### ISSUE TITLE
 Cannot read properties of undefined (reading 'getValue')

### ISSUE THREAD

**Issue by leehomeok** [alibaba/lowcode-engine#333]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

我给table组件的操作栏按钮 增加了一个name 为action的设置
function addonCombine(metadata: TransformedComponentMetadata) {
   if(componentName== 'ProTable' || componentName=="EditTable" ){
     let {props} = configure    
     if(props && Array.isArray(props)){
              for(let item of props){
                if(item.title == "操作栏按钮" || item.title == '操作列按钮'){
                  let {setter, title} = item
                  console.log(item, title)
                  let {items} = setter?.props?.config
                  for(let innerItem of items){
                    if(innerItem.name == 'dataSource' && item.name == 'actionBarButtons'){
                      let ArraySetterItems = innerItem?.setter?.props?.itemSetter?.props?.config?.items
                      console.log(ArraySetterItems, 'ArraySetterItems')
                      if(ArraySetterItems && !ArraySetterItems?.some(it => it.name=='action')){
                        let actionSetter = {
                          display: "inline",
                          initialValue: undefined,
                          isRequired: true,
                          name: "action",
                          title:'操作',
                          setter: {
                            componentName: "SelectSetter",
                            props: {
                              options: [
                                {title: '新增', value: 'add'},
                                {title: '查看',value:'view'},
                                {title: '更新',value:'edit'},
                                {title: '打开',value:'open'},
                                {title: '全部导出', value: 'export_all'},
                                {title: '导出选中', value: 'export_select'},
                                {title: '导出本页', value: 'export_page'},
                                {title: '自定义', value: 'custom'},
                              ],
                              onChange (value: string) {
                                console.log(value)
                              }
                            }
                          }
                        }
                        ArraySetterItems.splice(1, 0, actionSetter)
                      }
      
                      if(ArraySetterItems && !ArraySetterItems?.some(it => it.name =='behavior')){
                        let behavior= {
                          name: "behavior",
                          title: "\u4ea4\u4e92\u8bbe\u7f6e",
                          display: "block",
                          condition: function e(t) {
                              var n = t.parent.getPropValue("action");
                              return !n || "custom" === n
                          },
                          setter: {
                              componentName: "BehaviorSetter",
                              props: function e(t) {
                                  return {
                                      actions: ["onClick"],
                                      enableTooltipAction: !1,
                                      enableMessageAction: !1,
                                      extendedOptions: {
                                          
                                      }
                                  }
                              }
                          }
                        }
                        ArraySetterItems.push(behavior)
                      }
                    }
                  }
                }
              }
            }
         return {
              ...metadata,
              configure: {
                ...configure,
                props: props?.length ? [...props, ] : undefined,
              },
            };
}
}

![image](https://user-images.githubusercontent.com/13464485/163807456-c49f9c48-5039-4fb2-9e99-45e83eaece22.png)
 
![image](https://user-images.githubusercontent.com/13464485/163807750-7dc3c019-df9a-4462-8d43-4acaf7ae0daa.png)

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by leehomeok** [comment]
报错信息如下
![image](https://user-images.githubusercontent.com/13464485/163808776-b5224596-99ae-4508-bc30-1f30babbaf57.png)

**Comment by LeoYuan** [comment]
完全看不懂~格式化一下？以及提供一个可复现的 demo？

**Comment by leehomeok** [comment]
> 完全看不懂~格式化一下？以及提供一个可复现的 demo？

![image](https://user-images.githubusercontent.com/13464485/163809640-817f01e8-bc10-4da4-a3ab-aa09f8fa1000.png)

**Comment by leehomeok** [comment]
> > 完全看不懂~格式化一下？以及提供一个可复现的 demo？

按钮下拉框 修改了一下 普通按钮切换成次按钮，就会看到右边的异常捕获 报错

**Comment by fxxjdedd** [comment]
https://github.com/alibaba/lowcode-engine-ext/blob/13ef4b31680ddf5971d843c52885fc97b59d645f/src/setter/array-setter/index.tsx#L62

我觉得这个条件没法保证吧？
