### ISSUE TITLE
使用@alilc/element创建的组件库，在npm install时总是提示python找不到，用yarn则能成功安装

### ISSUE THREAD

**Issue by xusanduo08** [alibaba/lowcode-engine#343]
@alilc/element初始化的组件库，在npm install时报错如下：
![image](https://user-images.githubusercontent.com/17930163/164165657-45dcd769-76fb-48e6-83ad-cefccb8f0654.png)

然而python是有安装的：
![image](https://user-images.githubusercontent.com/17930163/164165761-871676cd-87bb-45c1-88fc-91455525f6c1.png)

另外，用yarn代替npm install时却能成功安装依赖，这是为啥？

**Comment by LeoYuan** [comment]
使用 node 14

**Comment by xusanduo08** [comment]
![image](https://user-images.githubusercontent.com/17930163/164168050-658f7571-cd62-44a1-b259-e8eda395e311.png)

14依然报错

。。。这个issue这么快被close了。

**Comment by mark-ck** [comment]
> ![image](https://user-images.githubusercontent.com/17930163/164168050-658f7571-cd62-44a1-b259-e8eda395e311.png)
> 
> 14依然报错
> 
> 。。。这个issue这么快被close了。

这个报错这么明显，写的很清楚  Python 执行出错啊

**Comment by LeoYuan** [comment]
duplicate of https://github.com/alibaba/lowcode-engine/issues/246
