### ISSUE TITLE
在单独的一个react项目中引入demo-preview.html中localstoreage中的json,渲染报错

### ISSUE THREAD

**Issue by fxhfwf** [alibaba/lowcode-engine#344]
在单独的一个react项目中引入demo-preview.html中localstoreage中的json
![image](https://user-images.githubusercontent.com/40874982/164165616-ff509dc9-bbb2-4b70-8027-6288889a5bd0.png)

package.json中引入了"@alilc/lowcode-react-renderer": "^1.0.0", "@alilc/lowcode-plugin-inject": "^1.0.0",     "@alilc/lowcode-engine": "^1.0.0",

按照demo的git仓库中的代码进行渲染
![image](https://user-images.githubusercontent.com/40874982/164166248-821190b0-5311-40fa-b727-7d29162562b5.png)
 然后会出现如下的报错，找不到原因，有大佬可以帮忙看下吗？

![image](https://pt-starimg.didistatic.com/static/starimg/img/uNsytmtmKO1650437410310.png)

**Comment by Bob984456043** [comment]
请问最后解决了吗，我也遇到这个问题

**Comment by fxhfwf** [comment]
@Bob984456043 解决了，依赖的资源不要少，就是官方demo中preview.tsx中的script

**Comment by yangyangdg** [comment]
> 



> @Bob984456043 解决了，依赖的资源不要少，就是官方demo中preview.tsx中的script

我也是碰到这个问题，不能少了demo中preview.tsx中的script哪个啊，能补充一下吗，急，谢谢

**Comment by LeoYuan** [comment]
盲猜需要把 Next 在 html 中引入？
