### ISSUE TITLE
文档中手工定义资产包说明不明确

### ISSUE THREAD

**Issue by vs0533** [alibaba/lowcode-engine#345]
首先查看文档中有提到

> 手工配置资产包
> 参考 Demo 中的[基础 Fusion Assets 定义](https://github.com/alibaba/lowcode-demo/blob/main/src/scenarios/basic-fusion/assets.json)，如果我们修改 assets.json，我们就能做到配置资产包：
> 
> packages 对象：我们需要在其中定义这个包的获取方式，如果不定义，就不会被低代码引擎动态加载并对应上组件实例。定义方式是 UMD 的包，低代码引擎会尝试在 window 上寻找对应 library 的实例；
> components 对象：我们需要在其中定义物料描述，物料描述我们将在下一节继续讲解。

查看https://github.com/alibaba/lowcode-demo/blob/main/src/scenarios/basic-fusion/assets.json 发现里面多了一个componentList[] 目测components是定义可使用的组件 componentList中有很多与components中重复的内容 不知道这两个的主要区别是什么 另外删除componentList 资产就不能显示了 **请问componentList是必须的吗？** 文档中还提到componentList即将废弃 **如果componentList非必须 去掉componentList应该如何正确使用？**

**Comment by mark-ck** [comment]
[基础 Fusion Assets 定义](https://github.com/alibaba/lowcode-demo/blob/main/src/scenarios/basic-fusion/assets.json) 确实并不符合最新版本协议的定义，是协议迭代的中间态产物，你可以关注这个资产包里 config.props 部分的定义，外层属性可以不需要去参考。

**Comment by SteveCGC** [comment]
如果不用componentList，用components必须配合sort和RemoteComponentDescription用吗？
