### ISSUE TITLE
如何实现自由布局,官方有没有思路

### ISSUE THREAD

**Issue by toviLau** [alibaba/lowcode-engine#346]
RT
我们想实现自由与磁吸并存, 大佬们 有没有方法?

**Comment by theecn** [comment]
低代码又不是无代码-- 出码后自己二次加工

**Comment by toviLau** [comment]
这是我现在的想法
![image](https://user-images.githubusercontent.com/21324302/164206758-7dd42775-6c56-42dd-9698-941256e9c303.png)

但是我捕获不到 onmousedown与 onmousemove 事件, 只能捕获到 onmouseup,  所以没办法计算 x, y

@LeoYuan 大佬给点思路

**Comment by luohe** [comment]
> RT 我们想实现自由与磁吸并存, 大佬们 有没有方法?

https://mp.weixin.qq.com/s/PSTut5ahAB8nlJ9kBpBaxw

**Comment by SuperChrisliu** [comment]
> 低代码又不是无代码-- 出码后自己二次加工

反正要写代码，你用低代码干嘛？

**Comment by loganjingdi** [comment]
https://github.com/loganjingdi/lowcode-material-magneticContainer 一个小demo
