### ISSUE TITLE
[出码]时生成的项目,会缺失部分物料

### ISSUE THREAD

**Issue by theecn** [alibaba/lowcode-engine#347]
## **Describe the bug (required)** / **详细描述 bug（必填）**

克隆官方demo后任意拖拽组件后点击出码,依赖内容有错误,安装缺失模块后依旧不行

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1. 克隆官方demo (http://lowcode-engine.cn/demo)并启动
2. 拖拽任意组件
3. 点击出码

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

出码后的内容下载到本地可正常运行

---

## **Screenshots (optional)** / **bug 截图（可选）**

![image](https://user-images.githubusercontent.com/22100544/164199174-82cffe6f-bb06-4aef-885d-9f78c4f04166.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**

- AliLowCodeEngine version:  1.0.0
- AliLowCodeEngineExt version: 
- chrome 版本 99.0.4844.51（正式版本） (x86_64)

**Comment by LeoYuan** [comment]
@mark-ck 似乎是物料描述不应该把 npm.package 指向 #alilc/lowcode-materials？

**Comment by mark-ck** [comment]
现在应该没这个问题了
