### ISSUE TITLE
物料库开发的文档能否丰富点

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#350]
如题物料库开发的文档能否丰富点

1. 我现在是hooks的函数组件去开发，不去使用PropType我应该怎么开发。尝试了一下是解析jsDoc自动生成物料描述Json，但是并不准确，因为我不知道怎么去写类型描述文件才是正确的。目前生成的描述文件挺多都是不准确的，导致我不能直接使用meta.js，只能复制粘贴
有没有案例可以看一下

2. 子组件我应该怎么开发，怎么书写？我现在是开发整个物料库多组件，不是单组件，没找到对应的文档。（文档看到有子组件导出，但是是单组件脚手架情况下）

**Comment by oneQiu** [comment]
感觉每次都要把dev生成的lowcode目录删除才能重新生成新的。

然后component属性我需要怎么配才能自动生成？

**Comment by mark-ck** [comment]
1. 可以看看这个 必读 https://lowcode-engine.cn/docV2/funcv8#BonMh ，自动生成低代码描述只是作为启动，还需要开发调试的；
2. 不太理解你的问题，通过 npm init @alilc/element your-material-name 生成的组件库示例工程里就有两个组件，可以看看示例工程的结构；

**Comment by oneQiu** [comment]
> 1. 可以看看这个 必读 https://lowcode-engine.cn/docV2/funcv8#BonMh ，自动生成低代码描述只是作为启动，还需要开发调试的；
> 2. 不太理解你的问题，通过 npm init @alilc/element your-material-name 生成的组件库示例工程里就有两个组件，可以看看示例工程的结构；

1. 那意思就是说生成以后描述文件需要自己改才行吗，那是不是就不直接用lowcode:build生成的meta.js了
2. 实例组件里面没有子组件的写法，就是比如Form.Item这种，他是怎么在index.ts导出的。

然后还有个问题想请教下：比如我有个布局组件，我想拖进去的子组件自动添加某个组件包裹着，我需要怎么去实现。相关的API看到不是很懂

**Comment by LeoYuan** [comment]
可以请 @mark-ck 贴一段伪代码，pro-layout 里这种操作简直稀松平常😃

**Comment by oneQiu** [comment]
感谢 文档里找到了对应的API了

**Comment by oneQiu** [comment]
onNodeAdd方法里面如果我要修改currentNode的Props的值，是不是只能通过创建一个新组件的方法去实现，直接修改的方法挂在上面吗

**Comment by oneQiu** [comment]
原型上找到了方法 over
