### ISSUE TITLE
Property 'div' does not exist on type 'JSX.IntrinsicElements'

### ISSUE THREAD

**Issue by xusanduo08** [alibaba/lowcode-engine#351]
脚手架创建的组件代码会提示如下错误：
![image](https://user-images.githubusercontent.com/17930163/164359652-1fcabfb9-9bc3-4af5-808b-95648a797336.png)

`Property 'div' does not exist on type 'JSX.IntrinsicElements'.`

另外，`createElement` 不引入的话会提示 Cannot find name 'createElement'. 这个问题看到有其他issue提到过，请问问题解决了吗，还是我的操作不对？

**Comment by alvarto** [comment]
疑似启动时会自动安装 @types/react 导致的问题，金禅麻烦看看？

临时的 workaround：可以通过配置 build.lowcode.js 部分，追加如下配置即可：

![image](https://user-images.githubusercontent.com/1797855/164362878-a0d6f0c1-6a5d-4b49-9c1a-65be81309266.png)

**Comment by xusanduo08** [comment]
done，加了`noParse: true`后需要删除node_modules后重新install

**Comment by xusanduo08** [comment]
![image](https://user-images.githubusercontent.com/17930163/164445768-a4750495-87e9-4c6e-9e71-57f3032b1ce5.png)

加了noParse后不会自动生成lowcode文件夹了，，，，

**Comment by wulucxy** [comment]
`
import React， { createElement } from 'react'
`
