### ISSUE TITLE
物料开发按照文档的步骤,运行报错

### ISSUE THREAD

**Issue by 329697166** [alibaba/lowcode-engine#354]
![image](https://user-images.githubusercontent.com/8613493/164390091-78db0bc4-5523-4281-b799-13a286d4892c.png)
![image](https://user-images.githubusercontent.com/8613493/164390953-20c758af-d93e-4f8d-bdf2-5feec5d31496.png)

按照官方文档的步骤一步步走的,运行lowcode:dev时就报这样的错误!

**Comment by mark-ck** [comment]
可以试试这个版本的低代码调试插件 @alifd/build-plugin-lowcode@0.3.0-beta.1

或者看看这个[文档](https://lowcode-engine.cn/docV2/funcv8#SIGYf)，使用 [WSL](https://docs.microsoft.com/zh-cn/windows/wsl/install)
