### ISSUE TITLE
DataSource 面板渲染出错

### ISSUE THREAD

**Issue by twinkle77** [alibaba/lowcode-engine#355]
## **Describe the bug (required)** / **详细描述 bug（必填）**

给请求头绑定变量：

<img width="944" alt="image" src="https://user-images.githubusercontent.com/17792166/164396069-a8293945-890e-4b30-96f6-41fcb8a1f933.png">

鼠标选择变量，直接报渲染出错：

<img width="355" alt="image" src="https://user-images.githubusercontent.com/17792166/164396117-58d6dc9c-2676-4168-b601-28a7bed2bd65.png">

**Comment by guohejun** [comment]
我遇过一个类似的，渲染异常：Cannot read properties of null(reading 'createVoidField')刷新面板。当时我的Nodejs是14+的，换成16+的好了...

**Comment by guohejun** [comment]
是不是NodeJS版本问题，我16+的没事，你的多少，我之前遇到一个类似的，14升16就好了
