### ISSUE TITLE
npm run lowcode:dev 不生成meta.ts

### ISSUE THREAD

**Issue by xusanduo08** [alibaba/lowcode-engine#357]
如题，使用脚手架生成的组件库，`npm run lowcode:dev`后不生成meta.ts，控制台没有看到报错

![image](https://user-images.githubusercontent.com/17930163/164414007-df8161f9-3345-48c1-8ac6-ee7914abf65b.png)

![image](https://user-images.githubusercontent.com/17930163/164413774-16201342-2e48-4e53-9130-70e068265f01.png)

相关依赖：

![image](https://user-images.githubusercontent.com/17930163/164437598-73cd9c7d-a1b0-4708-8ad2-59bb700094b1.png)

build.lowcode.js：

```js
module.exports = {
  alias: {
    '@': './src',
  },
  plugins: [
    [
      '@alifd/build-plugin-lowcode',
      {
        engineScope: "@alilc",
        noParse: true
      },
    ],
  ],
};

```

**Comment by xusanduo08** [comment]
很奇怪的问题，上午以及之前都是好的，以前删除了lowcode文件下，再次lowcode:dev完全可以再次生成lowcode文件夹的，这次却不行了

**Comment by xusanduo08** [comment]
#351 https://github.com/alibaba/lowcode-engine/issues/351

又排查了一遍，发现是解决上一个问题时加了noParse配置导致的，期待能彻底解决问题

**Comment by mark-ck** [comment]
noParse 的含义就是不解析生成组件低代码描述，场景是
1. 组件库组件很多的时候，解析会非常慢，需要停止解析；
2. 组件低代码描述已经稳定，不需要自动解析；

#351 这个问题理论上更新 @alilc/lowcode-material-parser@1.0.3 就不会出现了

**Comment by fengyx8** [comment]
如果我的项目中没有设置 “noParse: true”，也是无法自动生成 meta.ts，请问可能的原因是什么呢？如果我在项目中删除了 lowcode 文件夹，在执行 npm run lowcode:dev 后也是无法自动生成 lowcode 文件夹。
