### ISSUE TITLE
关于editor-preset-plugin的问题

### ISSUE THREAD

**Issue by BigMango** [alibaba/lowcode-engine#360]
这个包是否不开源，如果我想使用ant作为整个设计器的环境，是否没有这个包的代码无法做到？
如果不开源，我怎么模拟实现这个包的功能呢？是否有相关文档说明？

**Comment by LeoYuan** [comment]
不确定这个包的用途，理论上引擎不会依赖它，建议从 node_modules 里一探究竟~

**Comment by carvinlo** [comment]
bump

**Comment by carvinlo** [comment]
看了源码，内部包含：
react-is.production.min.js
react-jsx-runtime.production.min.js
react-is.production.min.js
http://github.com/garycourt/uri-js
react-dom-server.browser.production.min.js
https://lodash.com
和一些插件：
    "@ali/fusion-icon-setter": "^1.0.1",
    "@ali/lowcode-component-pane": "^0.1.3",
    "@ali/lowcode-datasource-fetch-handler": "^1.0.21",
    "@ali/lowcode-datasource-jsonp-handler": "^1.0.21",
    "@ali/lowcode-datasource-mtop-handler": "^1.0.22-alpha.1",
    "@ali/lowcode-plugin-base-monaco-editor": "^0.0.3",
    "@ali/lowcode-plugin-components-pane": "^1.0.21",
    "@ali/lowcode-plugin-datasource-pane": "^1.1.0-beta.6",
    "@ali/lowcode-plugin-event-bind-dialog": "^1.0.22",
    "@ali/lowcode-plugin-sample-logo": "^1.0.20",
    "@ali/lowcode-plugin-sample-preview": "^1.0.20",
    "@ali/lowcode-plugin-settings-pane": "^0.8.8",
    "@ali/lowcode-plugin-simulator-select": "^1.0.0",
    "@ali/lowcode-plugin-source-editor": "^1.0.20",
    "@ali/lowcode-plugin-undo-redo": "^1.0.20",
    "@ali/lowcode-plugin-variable-bind-dialog": "^1.0.20",
    "@ali/lowcode-plugin-zh-en": "^1.0.20",
    "@ali/lowcode-setter-behavior": "^0.1.1-beta.12",
    "@ali/lowcode-setter-i18n": "^0.0.5",
    "@ali/radio-group-card-setter": "^0.0.1",
    "@ali/setter-title": "^0.1.3-beta.2",
    "@alifd/next": "^1.21.0",
    "@alifd/theme-lowcode-dark": "^0.5.0",
    "@alife/rich-setter": "^1.0.6",
    "@alife/theme-lowcode-light": "^0.1.0",
    "@alilc/lowcode-plugin-code-editor": "^1.0.1",
    "@alilc/lowcode-plugin-code-generator": "^1.0.2",
    "@alilc/lowcode-plugin-components-pane": "^1.0.1",
    "@alilc/lowcode-plugin-datasource-pane": "^1.0.3",
    "@alilc/lowcode-plugin-schema": "^1.0.0",
    "@alilc/lowcode-plugin-simulator-select": "^1.0.0",
    "@alilc/lowcode-plugin-undo-redo": "^1.0.0",
    "@alilc/lowcode-plugin-zh-en": "^1.0.0",
    "@alilc/magic-editor-setter": "^1.0.3-beta.2",
    "react": "^16.8.1",
    "react-dom": "^16.8.1"

所以这个demo的同类示例源码在 https://github.com/alibaba/lowcode-demo
