### ISSUE TITLE
组件编译scss、less报错

### ISSUE THREAD

**Issue by hmz5** [alibaba/lowcode-engine#361]
## **Describe the bug (required)** / **详细描述 bug（必填）**
@alilc/build-plugin-alt 包安装后出现组件scss、less的编译出错

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：
1. npm init @alilc/element your-element-name
2. 选择组件/物料，并选择组件库
3. 安装插件包@alilc/build-plugin-alt
4. 重新npm run lowcode:dev 报错信息如下
![image](https://user-images.githubusercontent.com/16495308/164615243-77c91c1b-a6a2-4d01-a6d4-a3dacd986483.png)

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by eternalsky** [comment]
组件库这块还没适配过，单个组件应该是没问题的，组件库我最近适配一下，看看哪里有问题。

**Comment by hmz5** [comment]
单组件也是一样的呢，只要加了@alilc/build-plugin-alt这个插件就有问题

**Comment by hmz5** [comment]
> 组件库这块还没适配过，单个组件应该是没问题的，组件库我最近适配一下，看看哪里有问题。

不是服务注册有问题，是组件的编译出了问题，感觉是loader的版本冲突了

**Comment by eternalsky** [comment]
> 

单组件之前试过是没有问题的，我再试下。如果你那边能提供一个可复现 demo 就更好了。

**Comment by eternalsky** [comment]
@hmz5 刚才试了一下，重新初始化一个单组件包，加上 build-plugin-alt 是可以跑通，没有问题的。你那边单包有问题的场景，可以给一个复现 demo 吗？以 git 仓库或者 zip 包都可以

**Comment by hmz5** [comment]
@eternalsky 建议你用tnpm试试，没有任何额外的操作，就是按照demo步骤，只是使用tnpm.

或者，加入build-plugin-alt之后删除node_modules & package.json.lock 文件重新npm install 

同样可以复现出。

**Comment by eternalsky** [comment]
> @eternalsky 建议你用tnpm试试，没有任何额外的操作，就是按照demo步骤，只是使用tnpm.
> 
> 或者，加入build-plugin-alt之后删除node_modules & package.json.lock 文件重新npm install
> 
> 同样可以复现出。

删除后重新安装确实可以复现，我看一下原因

**Comment by eternalsky** [comment]
单包已经解决了，可以重新更新一下依赖试试

**Comment by hmz5** [comment]
> 单包已经解决了，可以重新更新一下依赖试试

@eternalsky 下午试试

**Comment by hmz5** [comment]
@eternalsky 可以了

**Comment by eternalsky** [comment]
组件库看了一下也没有问题
