### ISSUE TITLE
数据源保存设置之后，刷新浏览器配置信息消失，请问持久化数据源有啥好的方案呢？

### ISSUE THREAD

**Issue by lijiaxu1996** [alibaba/lowcode-engine#363]
![image](https://user-images.githubusercontent.com/59685169/164651722-6708401f-d43f-40f3-a0e8-8ce85d9bf93f.png)
下次刷新浏览器默认是这个数据源

**Comment by LeoYuan** [comment]
类似保存 schema 的思路，为了演示就保存到 localStorage 之类的地方，实际项目就保存到远程，初始化引擎之前，从远程获取数据传入到数据源面板插件
