### ISSUE TITLE
getResizingHandlers文档似乎不对

### ISSUE THREAD

**Issue by xusanduo08** [alibaba/lowcode-engine#364]
协议中getResizingHandlers是这么返回的：

返回的是大写字母E

![image](https://user-images.githubusercontent.com/17930163/164674666-9c8e9f0e-1e20-4d68-bf5f-848b6eecd28f.png)

但是在引擎源码里，判断条件里写的确实小写字母：

![image](https://user-images.githubusercontent.com/17930163/164674853-3058d5e0-88fb-473c-a38e-9d3fd6a50b58.png)

试了一下，确实只有小写字母e才能实现拖拽图标

![image](https://user-images.githubusercontent.com/17930163/164675232-cc442a93-fc26-46d9-972c-fa3818658c49.png)

麻烦两边统一一下呢

**Comment by xusanduo08** [comment]
文档地址：https://lowcode-engine.cn/material

**Comment by Ha0ran2001** [comment]
为啥使用了 getResizingHandlers 没有用
```jsx
<div
          className={classNames(baseSideClass, 'e')}
          ref={(ref) => {
            this.outlineE = ref;
          }}
          style={{
            height: offsetHeight,
            transform: `translate(${offsetLeft + offsetWidth - 10}px, ${offsetTop}px)`,
            width: 20,
            display: triggerVisible.includes('E') ? 'flex' : 'none',
          }}
        />
```
这个应该会显示才对啊

**Comment by liujuping** [comment]
看一下引擎版本。如果版本比较低，可以升级看一下。
