### ISSUE TITLE
schema或者大纲树中的页头或者页尾会多次包裹一层slot问题

### ISSUE THREAD

**Issue by HAY0526** [alibaba/lowcode-engine#367]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

页面开启页头或者页尾后，打开schema面板，什么也没有修改，每保存一次schema，大纲树中的页头会多包裹一层slot。schema中的页头也会多包裹一层slot，在lowcode-engine1.0.3版本中没有这个问题，之后的版本中才有

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
中文版示例：
1. 打开官方demo；
2. 选中页面，开启页头或者页尾；
3. 打开schema面板，点击保存schema按钮；
4. 打开大纲树面板，里面的页头多包裹一层slot；schema里面也是一样；
5. 什么也不用修改，重复第三步，页头外层又多包裹了一层slot；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

希望不要每保存一次就多一层slot嵌套

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

![image](https://user-images.githubusercontent.com/34828918/164887748-6d583eae-5169-4910-a2dc-96e0b0124717.png)
![image](https://user-images.githubusercontent.com/34828918/164887789-7bd6de06-5d09-41b8-8cbc-3a82f16ce1a6.png)

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.6] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by LeoYuan** [comment]
![image](https://user-images.githubusercontent.com/1195765/165238446-279cf182-e069-4f0e-ad4b-c99aa600fb8d.png)

辛苦试试最新的 demo 是否还能复现~

**Comment by HAY0526** [comment]
![image](https://user-images.githubusercontent.com/34828918/165241296-d34147f4-9cb4-432b-a04e-d0d048947f2f.png)
官方demo还有问题，版本是1.0.6

**Comment by LeoYuan** [comment]
按照你的操作无法复现啊，重新按照你写的复现步骤试试？另外 metaType 是啥？

**Comment by HAY0526** [comment]
metaType不用管 去掉也是一样，很好复现的。开启页头，打开schema面板，点击schema面板右侧的保存按钮就出现了啊
![image](https://user-images.githubusercontent.com/34828918/165244916-d68351b5-ef9f-4a45-933b-431c24360457.png)

**Comment by alvarto** [comment]
```typescript
        let json
        try {
          json = JSON.parse(monacoEditorRef.current?.getValue() ?? schemaValue)
        } catch (err) {
          Message.error('Cannot save schema. Schema Parse Error.' + err.message)
          return;
        }
    
        project.importSchema({
          ...project.exportSchema(),
          componentsTree: [json],
        });
```

调用的 API 比较简单 @LeoYuan

**Comment by LeoYuan** [comment]
exportSchema() 需要加个参数

exportSchema(TransformStage.Save) // 保存态，也就是标准协议
exportSchema(TransformStage.Render) // 编排渲染态，默认值是这个，会有些额外的协议转换

@alvarto 

此次变更是 https://github.com/alibaba/lowcode-engine/pull/287/files#diff-3bbdaa068ebf71cc814d7f8cc4174c1a7186ee86274e62737b5f149ac16a5e0bR106， 文档里 project / documentModel / node / prop 的 exportSchema 默认值都是 Render，project 在实现时忘了，加上了~

**Comment by alvarto** [comment]
Fixed as of @alilc/lowcode-plugin-schema@1.0.1

Related diff: https://github.com/alibaba/lowcode-plugins/commit/23af4b7fba68b594a91668516478ca569501d9b4

**Comment by alvarto** [comment]
Demo 中已更新到最新版
