### ISSUE TITLE
Antd Input 类组件在画布中无法选中

### ISSUE THREAD

**Issue by twinkle77** [alibaba/lowcode-engine#369]
## **Describe the bug (required)** / **详细描述 bug（必填）**

Antd Input 类组件在画布中无法选中，只能利用大纲树进行操作

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

https://lowcode-engine.cn/demo/basic-antd.html

拖入表单组件如  Input 组件、Password 组件

<img width="551" alt="image" src="https://user-images.githubusercontent.com/17792166/164960667-2d83255a-5835-4a55-91ee-972ca20b1fb3.png">

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
Input 类组件能在画布中选中

**Comment by eightHundreds** [comment]
自定义组件应该会遇到类似问题. 能解释下原因并提供解决方案吗?
