### ISSUE TITLE
编辑器页面Header能否隐藏？

### ISSUE THREAD

**Issue by w4ngzhen** [alibaba/lowcode-engine#373]
lowcode-demo编辑器能否隐藏

**Comment by leehomeok** [comment]
+1，  header里面的slot 经常会无限循环，建议默认为header: false

**Comment by oneQiu** [comment]
感觉header的组件不能用hooks，我想useParams取一下动态路由都不行

**Comment by LeoYuan** [comment]
header 是指啥？

**Comment by w4ngzhen** [comment]
> header 是指啥？

抱歉没讲清楚。是指editor编辑器的topArea部分，这块顶部面板能否隐藏呢？因为想要将编辑器以iframe的方式嵌入到页面中，但是顶部想要隐藏。

**Comment by liujuping** [comment]
是不支持 API 设置的，不过可以通过设置 css 样式，将其隐藏就好。
