### ISSUE TITLE
物料脚手架项目，自定义设置器导致渲染失败

### ISSUE THREAD

**Issue by Jveen-D** [alibaba/lowcode-engine#375]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

--- 
我在使用官方提供的设置器`DateSetter`发现了这个设置器没有做`local`的处理，选项面板不是中文的，所以我自己写了一个设置器`mateDatePickerSetter`，`npm`地址在这里[matecode-date-picker-setter](https://www.npmjs.com/package/matecode-date-picker-setter)，我在使用这个设置器的时候，发现一个问题难以解决，当我初次选择时间的时候，渲染是正常的。但是当我点击清除图标清空的时候，就会渲染失败。改了很多次我都没有解决这个问题，所以我现在的做法是直接将`hasClear`这个选项直接关闭了。
## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---
1. 安装自定义设置器`npm i matecode-date-picker-setter`
2. 注册设置器；
3. 将一个面板属性的`setter`设置为`mateDatePickerSetter`；
4. 使用这个设置器修改日期值；

**or**
直接在demo中注册设置器，设置器代码如下
```typescript
import * as React from "react";
import * as moment from "moment";
moment.locale("zh-cn");
import { DatePicker } from "@alifd/next";

interface mateDatePickerSetterProps {
  // 当前值
  value: moment.Moment;
  // 默认值
  defaultValue: string;
  // setter唯一输出
  onChange: (v) => void;
}
export default class mateDatePickerSetter extends React.PureComponent<mateDatePickerSetterProps> {
  componentDidMount() {
    const { onChange, value, defaultValue } = this.props;
    if (value == undefined && defaultValue) {
      onChange(defaultValue);
    }
  }
  // 声明Setter的title
  static displayName = "mateDatePickerSetter";
  render() {
    const { onChange, value } = this.props;
    return (
      <DatePicker
        value={value}
        hasClear={false}      ###这行代码删掉就会导致上述的bug
        style={{ width: "100%" }}
        onChange={(val: any) => onChange(val)}
      />
    );
  }
}

```

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---
点击清除按钮以后不会造成渲染失败，并且自定义`setter`可以正常交互

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngineExt version: [e.g. 1.0.3] / 低代码引擎扩展包版本
 - Browser [e.g. chrome] / 浏览器版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by LeoYuan** [comment]
bug 是啥？麻烦贴个图以及必要的报错信息，多谢~
