### ISSUE TITLE
lowcode-engine 配合物料库调试失败

### ISSUE THREAD

**Issue by Gllidan** [alibaba/lowcode-engine#380]
## **Describe the bug (required)** / **详细描述 bug（必填）**

lowcode-engine 配合物料库调试失败

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---
执行环境：wsl
node: 14.15
npm: 6.14

 1. npm run steup 执行 lowcode-engine 依赖安装
 2. npm run start 启动 lowcode-engine 本地服务
 3. 这是server启动后的界面
![image](https://user-images.githubusercontent.com/27495460/165063518-630c43db-1c95-4ef7-b5bc-71ee8c30de98.png)
 4. 启动antd物料库 
 5. 配置xSwitch代理
  [
      "https://alifd.alicdn.com/npm/@alilc/lowcode-engine@(.*)/dist/js/engine-core.js",
      "http://localhost:5555/js/engine-core.js"
    ],
    
    [
      "https://alifd.alicdn.com/npm/@alilc/lowcode-engine@(.*)/dist/css/engine-core.css",
      "http://localhost:5555/css/engine-core.css"
    ],
    [
      "https://alifd.alicdn.com/npm/@alilc/lowcode-react-simulator-renderer@(.*)/dist/js/react-simulator-renderer.js",
      "http://localhost:5555/js/react-simulator-renderer.js"
    ],
    [
      "https://alifd.alicdn.com/npm/@alilc/lowcode-react-simulator-renderer@(.*)/dist/css/react-simulator-renderer.css",
      "http://localhost:5555/css/react-simulator-renderer.css"
    ],
    [
      "https://alifd.alicdn.com/npm/@alilc/lowcode-rax-simulator-renderer@(.*)/dist/js/rax-simulator-renderer.js",
      "http://localhost:5555/js/rax-simulator-renderer.js"
    ],
    [
      "https://alifd.alicdn.com/npm/@alilc/lowcode-react-simulator-renderer@(.*)/dist/css/rax-simulator-renderer.css",
      "http://localhost:5555/css/rax-simulator-renderer.css"
    ],
    [
      "https://unpkg.com/@alilc/lowcode-react-simulator-renderer@beta/dist/js/react-simulator-renderer.js",
      "http://localhost:5555/js/react-simulator-renderer.js"
    ],
    [
      "https://unpkg.com/@alilc/lowcode-react-simulator-renderer@beta/dist/css/react-simulator-renderer.css",
      "http://localhost:5555/css/react-simulator-renderer.css"
    ],
    [
      "https://alifd.alicdn.com/npm/@alilc/lowcode-engine@1.0.3/dist/css/engine-core.css",
      "http://localhost:5555/css/engine-core.css"
    ],
    [
      "https://alifd.alicdn.com/npm/@alilc/lowcode-engine@1.0.3/dist/js/engine-core.js",
      "http://localhost:5555/js/engine-core.js"
    ]

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
查看nextwork发现已经代理且运行成功，但本地添加的调试代码并未执行。
执行 lowcode-engine 的run build 也失败
按道理来说，是应该支持本地热更新调试的，还是说需要每次修改后都进行run build呢？

---

**Comment by Gllidan** [comment]
复测发现需要重新执行run start才能更新调试代码，强刷浏览器无效

**Comment by LeoYuan** [comment]
lowcode-engine 这个仓库本身不提供测试物料的功能，应该是 lowcode-demo~

启动 lowcode-demo，配合 XSwitch 代理 lowcode-engine 资源文件，配合 demo 中内置的注入调试能力~

**Comment by 1degrees** [comment]
在lowcode-engine 包中运行
第一步：yarn setup
第二步：yarn start
这时候会发现 
http://localhost:5555/js/engine-core.js
http://localhost:5555/css/engine-core.css
这两个资源文件压根不存在呀， 这里如何做代理呢？
我查看了ignitor 包下面的build.json这个配置，入口文件：
<img width="830" alt="image" src="https://github.com/alibaba/lowcode-engine/assets/30748321/76991d4b-b07f-4bf4-8db9-c2da721a35c1">
它也不会输出上述代理的js，和css文件呀，所以我本地启动demo项目时，无法将资源代理到大佬说的引擎项目呀
