### ISSUE TITLE
antd-lowcode-materials 下扩展 FormItem 问题

### ISSUE THREAD

**Issue by Gllidan** [alibaba/lowcode-engine#382]
## **Describe the bug (required)** / **详细描述 bug（必填）**

基于开源物料，配置表单时，发现给formItem挂载原子组件时，原子组件无法获取form实例对应的value值与onChange事件。

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---
 1. 基于开源物料，配置表单时，发现给formItem挂载原子组件时，原子组件无法获取form实例对应的value值与onChange事件。
 2. 查看formItem的源码与原子组件的源码,都只是柯里化与别名操作 
![image](https://user-images.githubusercontent.com/27495460/165066713-ba68e406-e91d-49af-bc74-e08109be1209.png)
![image](https://user-images.githubusercontent.com/27495460/165066913-901c5ea7-5bf9-48a2-ab29-9221bf0174e0.png)
（这里对 <Form.Item/> 这种写法表示疑惑，Form.Item只支持单个children或函数组件）
 3. 查看 renderer-view 代码，看到里面 customCreateElement 函数对children做了操作，确保容器状态下，children为数组
![image](https://user-images.githubusercontent.com/27495460/165067815-50057525-3dc7-4f4d-b009-dfcf4fd8575d.png)
 4. 感觉是上面的这种写法，使原子组件无法受控。
 5. 另外原子组件也只能通过事件面板，手动挂载change事件，但this无法获取顶层的form实例或对应的受控属性。

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
 
1. 原子组件在formItem容器中，支持受控
2. 手动挂载onChange事件，需要能获取formItem传递的受控属性。

---

**Comment by twinkle77** [comment]
https://github.com/alibaba/lowcode-engine/issues/374
应该是同一个问题 ？

**Comment by twinkle77** [comment]
1. 修改 https://github.com/alibaba/lowcode-materials/blob/main/packages/antd-lowcode-materials/src/components/form/index.tsx#L80 的代码
![image](https://user-images.githubusercontent.com/17792166/165206226-7797a094-6660-4de0-b66b-271d42c3c34e.png)

2. 尝试跑下，Input 收集到的值不对（下拉框跟日期选择是正常的）
<img width="1235" alt="image" src="https://user-images.githubusercontent.com/17792166/165206208-b21f2ede-14b7-4ea2-ae5f-7ab6e872dd82.png">

**Comment by twinkle77** [comment]
fixed
