### ISSUE TITLE
通过脚手架创建的物料库支持设置器?debug吗

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#384]
如题
我先通过脚手架创建了物料库，然后运行lowcode:dev启动项目，同时我想配置另外一个设置器的项目调试
![image](https://user-images.githubusercontent.com/50658231/165239653-2203e18a-abe5-4d88-bdb0-eae652d19b48.png)

但是发现好些没有触发inject插件，想问下是默认没有集成在物料库的demo预览里面吗？如果通过build.lowcode.js配置build-plugin-lowcode的话文档在哪里可以看呢

**Comment by LeoYuan** [comment]
lowcode-demo 支持的，具体配置参考 工具脚手架 那篇文档~

**Comment by oneQiu** [comment]
> lowcode-demo 支持的，具体配置参考 工具脚手架 那篇文档~

我是想在自己的物料库里面调试 ，物料库里面好像是没有配置
![image](https://user-images.githubusercontent.com/50658231/165246088-30a4ec52-df62-46a4-beb3-af5aa197bb0f.png)

**Comment by LeoYuan** [comment]
你就把 物料 和 设置器 当成独立的 生态元素 类型，启动时使用 inject 模式，demo 就能去侦测到并注入~

需要注意的点，比如 设置器的名字是 SomeSetter，那么物料中得有属性配置使用了 SomeSetter

**Comment by oneQiu** [comment]
这是我物料库项目里面配置的
![image](https://user-images.githubusercontent.com/50658231/165253006-fbabbd3c-052c-4a22-90a5-4fda119f9515.png)

![image](https://user-images.githubusercontent.com/50658231/165251152-683f31be-b632-49e5-8aed-7dfebcf94d8a.png)

设置器配置
![image](https://user-images.githubusercontent.com/50658231/165251246-d0219e60-33d2-43cc-967f-d51114404296.png)
![image](https://user-images.githubusercontent.com/50658231/165251380-88eb445d-b459-49cc-8925-f3cf079294e3.png)

但是貌似没有注册成功
![image](https://user-images.githubusercontent.com/50658231/165253111-3a4b3654-9d7c-436c-9f42-e6374f3223dd.png)

**Comment by oneQiu** [comment]
不知道我的理解对不对
