### ISSUE TITLE
【模拟器主进程事件路由】为啥要禁止 点击事件传播 ，导致 antd input 组件无法通过点击focus组件

### ISSUE THREAD

**Issue by zxb5102** [alibaba/lowcode-engine#386]
## **Describe the bug (required)** / **详细描述 bug（必填）**
下面代码中模拟器事件路由，取消了 点击事件向下传递，导致 类似 input 的组件无法进入 focus 状态，所以无法进行交互输入值，
是否可以取消这块的事件捕获呢，为啥一定要拦截掉
![image](https://user-images.githubusercontent.com/18233541/165247003-68bf8c82-19a9-4318-ac9f-387bdb5a3845.png)
如下需要让 input 进入 focus 状态，然后输入值
![image](https://user-images.githubusercontent.com/18233541/165246813-7003a619-9602-4fcc-a273-6eefcddc141a.png)

**Comment by LeoYuan** [comment]
输入值也不会产生新的 schema 内容，有什么用呢？

**Comment by zxb5102** [comment]
是不产生新的schema ，但是如果我的input 组件配置有复杂的联动规则，直接交互我能够看到配置规则的生效效果。

**Comment by zxb5102** [comment]
就是能够和组件进行交互会有更好的配置体验

**Comment by LeoYuan** [comment]
嗯嗯，明白，那暂时还不支持。

设计了几种模式：designMode: 'design' 和 'live'，第一种侧重编辑态只是用来看的，第二种侧重编辑态可以运行，包括你说的可以输入，联动，数据源会发请求等等，悲伤的是，第二种还没实现。。。

**Comment by ljmCoder** [comment]
> 嗯嗯，明白，那暂时还不支持。
> 
> 设计了几种模式：designMode: 'design' 和 'live'，第一种侧重编辑态只是用来看的，第二种侧重编辑态可以运行，包括你说的可以输入，联动，数据源会发请求等等，悲伤的是，第二种还没实现。。。

请问下 现在支持designMode 'live'支持了吗

**Comment by JackLian** [comment]
还没支持
