### ISSUE TITLE
如何在 页面编辑器 和 页面预览 时，都能设置和读取 共同的环境变量？ 例如：BASE_RUL 之类的环境变量

### ISSUE THREAD

**Issue by 946629031** [alibaba/lowcode-engine#393]
我能想到的办法是，设置 appHelper。

但是 appHelper在页面预览时可以设置，但是在页面编辑器里 如何设置appHelper 呢？

appHelper在页面预览时可以设置，如下图
![](https://user-images.githubusercontent.com/17792166/163516241-f82ba13d-38e7-4c88-9378-0e3099ce2ca7.png)
---

但是，在页面编辑器里，如何设置 appHelper ？

```js
// src/scenarios/main/index.ts

import { init, plugins } from '@alilc/lowcode-engine';
import registerPlugins from '../../universal/plugin';
import { scenarioSwitcher } from '../../sample-plugins/scenario-switcher';
import '../../universal/global.scss';

const preference = new Map();
preference.set('DataSourcePane', {
  importPlugins: [],
  dataSourceTypes: [
    {
      type: 'fetch',
    },
    {
      type: 'jsonp',
    }
  ]
});

(async function main() {
  await plugins.register(scenarioSwitcher);
  await registerPlugins();

  init(document.getElementById('lce-container')!, {
    // appHelper={{  // it is not working
    //    utils: {
    //     xxx: () => {}
    //   }
    // }}

    // designMode: 'live',
    // locale: 'zh-CN',
    enableCondition: true,
    enableCanvasLock: true,
    // 默认绑定变量
    supportVariableGlobally: true,
    // simulatorUrl 在当 engine-core.js 同一个父路径下时是不需要配置的！！！
    // 这里因为用的是 alifd cdn，在不同 npm 包，engine-core.js 和 react-simulator-renderer.js 是不同路径
    simulatorUrl: [
      'https://alifd.alicdn.com/npm/@alilc/lowcode-react-simulator-renderer@latest/dist/css/react-simulator-renderer.css',
      'https://alifd.alicdn.com/npm/@alilc/lowcode-react-simulator-renderer@latest/dist/js/react-simulator-renderer.js'
    ]
  }, preference);
})();
```

**Comment by twinkle77** [comment]
```
 init(document.getElementById('lce-container')!, {
    requestHandlersMap: {
      fetch:   xxxxx
    },

    // appHelper={{  // it is not working
    //    utils: {
    //     xxx: () => {}
    //   }
    // }}

    // designMode: 'live',
    // locale: 'zh-CN',
    enableCondition: true,
    enableCanvasLock: true,
    // 默认绑定变量
    supportVariableGlobally: true,
    // simulatorUrl 在当 engine-core.js 同一个父路径下时是不需要配置的！！！
    // 这里因为用的是 alifd cdn，在不同 npm 包，engine-core.js 和 react-simulator-renderer.js 是不同路径
    simulatorUrl: [
      'https://alifd.alicdn.com/npm/@alilc/lowcode-react-simulator-renderer@latest/dist/css/react-simulator-renderer.css',
      'https://alifd.alicdn.com/npm/@alilc/lowcode-react-simulator-renderer@latest/dist/js/react-simulator-renderer.js'
    ]
  }, preference);
```

实测可用

**Comment by 946629031** [comment]
> ```
>  init(document.getElementById('lce-container')!, {
>     requestHandlersMap: {
>       fetch:   xxxxx
>     },
> 
>     // appHelper={{  // it is not working
>     //    utils: {
>     //     xxx: () => {}
>     //   }
>     // }}
> 
>     // designMode: 'live',
>     // locale: 'zh-CN',
>     enableCondition: true,
>     enableCanvasLock: true,
>     // 默认绑定变量
>     supportVariableGlobally: true,
>     // simulatorUrl 在当 engine-core.js 同一个父路径下时是不需要配置的！！！
>     // 这里因为用的是 alifd cdn，在不同 npm 包，engine-core.js 和 react-simulator-renderer.js 是不同路径
>     simulatorUrl: [
>       'https://alifd.alicdn.com/npm/@alilc/lowcode-react-simulator-renderer@latest/dist/css/react-simulator-renderer.css',
>       'https://alifd.alicdn.com/npm/@alilc/lowcode-react-simulator-renderer@latest/dist/js/react-simulator-renderer.js'
>     ]
>   }, preference);
> ```
> 
> 实测可用

要怎么调用呢？ 我试了 在编辑器里的 源码面板 里，console.log(this) 找不到注入的方法呀？

**Comment by twinkle77** [comment]
感觉跟 https://github.com/alibaba/lowcode-engine/issues/419 是同一个问题

**Comment by lonerhan** [comment]
> ```
>  init(document.getElementById('lce-container')!, {
>     requestHandlersMap: {
>       fetch:   xxxxx
>     },
> 
>     // appHelper={{  // it is not working
>     //    utils: {
>     //     xxx: () => {}
>     //   }
>     // }}
> 
>     // designMode: 'live',
>     // locale: 'zh-CN',
>     enableCondition: true,
>     enableCanvasLock: true,
>     // 默认绑定变量
>     supportVariableGlobally: true,
>     // simulatorUrl 在当 engine-core.js 同一个父路径下时是不需要配置的！！！
>     // 这里因为用的是 alifd cdn，在不同 npm 包，engine-core.js 和 react-simulator-renderer.js 是不同路径
>     simulatorUrl: [
>       'https://alifd.alicdn.com/npm/@alilc/lowcode-react-simulator-renderer@latest/dist/css/react-simulator-renderer.css',
>       'https://alifd.alicdn.com/npm/@alilc/lowcode-react-simulator-renderer@latest/dist/js/react-simulator-renderer.js'
>     ]
>   }, preference);
> ```
> 
> 实测可用

这个测试了感觉没用
