### ISSUE TITLE
antd组件 输入框无法输入 绑定了只能显示  无法修改  不能输入，

### ISSUE THREAD

**Issue by 15163789836** [alibaba/lowcode-engine#397]
## 复现截图
![image](https://user-images.githubusercontent.com/104408070/165477696-7f84d9d0-07a7-48b1-bdf1-4ec573aeb840.png)

## 复现流程与链接
![image](https://user-images.githubusercontent.com/104408070/165477701-c2a0e356-7ced-4aef-86c5-7164974b6167.png)
![image](https://user-images.githubusercontent.com/104408070/165477918-ae46adeb-4b6b-4342-a9de-7cb0f9c029bc.png)

## 期望结果
可以修改  更新数据
## 环境信息

- 引擎版本 1.0.3-beta.0
- ext 版本 1.0.3
- 物料
  - moment﹫2.24.0
  - lodash
  - iconfont-icons
  - ﹫ant-design/icons﹫4.7.0
  - antd﹫4.19.5
  - ﹫alifd/next﹫1.23.0
  - ﹫alilc/lowcode-materials﹫1.0.3

**Comment by twinkle77** [comment]
https://github.com/alibaba/lowcode-materials

antd 表单组件的问题已经修复了，但大佬们还没发包

**Comment by 15163789836** [comment]
> https://github.com/alibaba/lowcode-materials
> 
> antd 表单组件的问题已经修复了，但大佬们还没发包

你好 这个是修复的是物料还是引擎呀 怎么解决的

**Comment by LeoYuan** [comment]
@hujiulong 需要发个包？

**Comment by mDing11** [comment]
@hujiulong 你好 antd一些组件不能选中 这个问题有没有其他解决办法 不想对antd进行二次封装

**Comment by panda0000009** [comment]
请问下，这个问题修复了嘛。我用原生的input和Fusion Ui 的input好像都不行，输入框无法输入
我换成浏览器窗口为载体的话，input也是可以的，但是如果是面板为载体的话就不成。

**Comment by hujiulong** [comment]
编辑状态是引擎特意设为不能输入的，不能修改属性的问题应该已经修复了，我明天再确认下是否发布了新版本

**Comment by hujiulong** [comment]
升级 @alilc/antd-lowcode-materials 到1.0.6 ，这些问题已经修复了
