### ISSUE TITLE
发现lowcode-renderer-core中使用的react的写法，如果想实现vue-renderer也是得把里面的写法换成vue的吧？

### ISSUE THREAD

**Issue by qizilin** [alibaba/lowcode-engine#399]
想参考着写一个vue-renderer时，发现react-rednerer又引入了@alilc/lowcode-renderer-core，里面基本都是用react，意思也是的写一套用vue的类似实现了吧？

<img width="807" alt="image" src="https://user-images.githubusercontent.com/7828239/165517342-ac2a491f-4e35-4923-b4cd-4af402c070f0.png">

**Comment by liujuping** [comment]
> > 需要的，主要目的是实现图中的 Runtime 和 Renderers。默认导出的更适合 React 的写法，Vue 需要根据情况进行扩展或者重新写一份。
> > 美团已经有人在实现了，目前实现的差不多了，技术上是可行的，加油～
> 
> 请问有开源吗？

目前还没有

**Comment by starsoul666** [comment]
物料使用现有的react版本的物料，使用vue的reander这种方案可行吗，需要实现@alilc/lowcode-react-renderer和@alilc/lowcode-renderer-core两个包吗？
