### ISSUE TITLE
「讨论」是否需要将引擎文档换成 docusaurus？

### ISSUE THREAD

**Issue by LeoYuan** [alibaba/lowcode-engine#400]
https://docusaurus.io/

感觉这个文档框架不错，有如下几点打动我：

1. github 存储原始 markdown 文件（便于 PR 协作）
2. 文档样式不错
![image](https://user-images.githubusercontent.com/1195765/165668576-08eb0b7c-adc2-4356-ba49-42b004231ecd.png)
3. 搜索能力
![image](https://user-images.githubusercontent.com/1195765/165668608-ea91faac-30f2-4cf2-b7f4-5c37c80f1b02.png)
4. 版本化文档
5. 内置多语言翻译
![image](https://user-images.githubusercontent.com/1195765/165668732-f798a2ca-f5b0-43b5-ac27-dc9368fd4b88.png)

**Comment by JackLian** [comment]
+1

**Comment by leehomeok** [comment]
+2

**Comment by toviLau** [comment]
+4

**Comment by imsobear** [comment]
+5

**Comment by go-maple** [comment]
+1024

**Comment by markyun** [comment]
安排！

**Comment by mark-ck** [comment]
目前引擎官网文档用的是我写的基于语雀的方案，就没有一个人留念吗😂

**Comment by LeoYuan** [comment]
> 目前引擎官网文档用的是我写的基于语雀的方案，就没有一个人留念吗😂

若干年后，大家心中还是会缅怀的~😄

**Comment by Clarence-pan** [comment]
+1 这个搜索能力看起来很厉害的样子

**Comment by alvarto** [comment]
> 目前引擎官网文档用的是我写的基于语雀的方案，就没有一个人留念吗😂

留念！@mark-ck
