### ISSUE TITLE
容器组件接受到的 props.children 需要是一个函数，而不是数组

### ISSUE THREAD

**Issue by twinkle77** [alibaba/lowcode-engine#401]
## **Describe the bug (required)** / **详细描述 bug（必填）**

已知组件是容器组件 ```isContainer: true```，用户拖拽组件进入容器，接受到的  props.chidlren 是一个数组

```
export default Container = ( props ) => {
  return <div>{ props.children }</div>
}
```

但某些场景下 props.children 是一个函数，如 antd 的 Form.List 组件

```
export default Form.List = ( props ) => {
  return <div>{ props.children(上下文) }</div>
}
```

<img width="937" alt="image" src="https://user-images.githubusercontent.com/17792166/165671304-eeec8deb-c55e-48ef-8ea8-f6b1688cd547.png">

请问下大佬们，有没办法使得容器组件接受到的 props.children 是函数，不用再进行转换

**Comment by liujuping** [comment]
这个你可以自己进行包装一下的，比如上面的代码改成

export default Form.List = ( props ) => {
  const children = (props) => {
     // 上下文相关的处理
     return props.children
  }
  return <div>{ children }</div>
}

**Comment by twinkle77** [comment]
好吧，那只能对 antd 的 Form.List 组件进行二封了 @liujuping

**Comment by liujuping** [comment]
是的

**Comment by proclml** [comment]
@liujuping @twinkle77 请问应该怎么封？如何实现图中需求：
如图想让`Space`组件按`fields`数组循环，`Space`组件下的`Form.Item`需要能拿到循环项的 name 字段，`MinusCircleOutlined` 组件能拿到 remove 方法并能调用
