### ISSUE TITLE
在ReactRenderer生成的页面中，组件之间能否通过id获取对应node节点

### ISSUE THREAD

**Issue by 286yym** [alibaba/lowcode-engine#404]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
在ReactRenderer生成的页面中，组件一能否获取到组件二的的node节点，需要关联组件，做联动
---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
无
---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为
在预览文件中，组件联动，组件一改变了值，想拿到组件二的node节点调用联动方法
---

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by liujuping** [comment]
组件之间直接调用是不行，但是可以放到表达式中比如给 A 组件传递一个 props.x，它的值类型是 JSExpression 类型的，如下图所示：

`
{
  "type": "JSExpression",
  "value": "this.$(refId)"
}
`

组件 A 就可以通过 props.x 获取到组件 B 的示例，并调用组件 B 的方法。

**Comment by 286yym** [comment]
那这个“refId”，我这边需要在物料组件上怎么才能进行注册ref，自己写物料，无法准确注册ref编辑器上，导致this.$()的内容一直是空对象，然后this.$(refId)一直为空就无法执行

**Comment by liujuping** [comment]
物料组件参考：https://github.com/alibaba/lowcode-materials/tree/main/packages/fusion-lowcode-materials/lowcode/dialog

**Comment by liujuping** [comment]
@mark-ck 需要大佬指导一下，怎么自己写一个带 ref 配置的物料

**Comment by twinkle77** [comment]
<img width="714" alt="image" src="https://user-images.githubusercontent.com/17792166/167238751-85368943-b2e4-4561-8277-d31679befced.png">

meta.ts 文件描述下就可以的，这样拖拽组件进去画布就会自动生成 ref
