### ISSUE TITLE
ArraySetter使用问题：提示未配置快捷编辑项 

### ISSUE THREAD

**Issue by Cossey11111** [alibaba/lowcode-engine#406]
![image](https://user-images.githubusercontent.com/99870810/165729321-04e1ac8a-7165-4303-b7db-f56bee5356ed.png)
![image](https://user-images.githubusercontent.com/99870810/165729411-9d6a2be3-03e9-46f1-b9e2-11530767e541.png)
请问产生这个问题的原因？

**Comment by oneQiu** [comment]
解决了吗？同问

**Comment by LiuTeiTei** [comment]
解决了吗？同问
