### ISSUE TITLE
有没有布局和菜单的组件呢？Layout and Menu components are missed. 

### ISSUE THREAD

**Issue by richwxd** [alibaba/lowcode-engine#41]
目前只可以实现内部页面，实现一个低代码应用的外框布局和左侧菜单组件缺失了。
Currently it can be used to create a inner page belongs to a web app, but layout and menu components are missed which are most useful to create a whole web app.

**Comment by LeoYuan** [comment]
两个方案供选择：
1. 在设计器里封装一个 [Shell 组件](https://fusion.design/pc/component/shell?themeid=2)，作为默认根组件；
2. 设计器里不处理，在运行时，对编排产生的页面包裹一层 Shell；
