### ISSUE TITLE
有没有考虑formily相关的物料?

### ISSUE THREAD

**Issue by Dogtiti** [alibaba/lowcode-engine#410]
如题，希望表单能使用formily

**Comment by liujuping** [comment]
物料可以自己定制的。官方没有相关定制的规划，如果有需要可以自己进行扩展。

**Comment by xiexingen** [comment]
+1

**Comment by Gllidan** [comment]
可以参考开源的物料库，开发持fromily的自定义组件，具体查看formily的文档，内部支持JSX语法、SchemaField组织组件树。

**Comment by chenfeiwu** [comment]
+1 其实大家都是想用formily的表单场景的那些特性，要是二合一真的太完美了，我现在都不知道怎么选型

**Comment by Dogtiti** [comment]
有没有人有兴趣一起搞个formily的物料库呀，有兴趣的可以@我

**Comment by Immanding** [comment]
formily 物料[@seada/formily-materials](https://github.com/seada-low-code/lowcode-ecology/tree/main/packages/formily-materials)，目前已经支持了多个项目的表单场景，如果有问题可以提issue或mr

**Comment by LeoYuan** [comment]
> formily 物料[@seada/formily-materials](https://github.com/seada-low-code/lowcode-ecology/tree/main/packages/formily-materials)，目前已经支持了多个项目的表单场景，如果有问题可以提issue或mr

👍🏻~

可以去 https://github.com/lowcode-workspace/awesome-lowcode-engine 收录一下~

**Comment by Immanding** [comment]
> 

可以可以～

**Comment by LeoYuan** [comment]
> > 
> 
> 可以可以～

对了，还可以去 lowcode-demo 新建一个场景，直接让用户 0 成本体验一下~😄

**Comment by Immanding** [comment]
> > > 
> > 
> > 
> > 可以可以～
> 
> 对了，还可以去 lowcode-demo 新建一个场景，直接让用户 0 成本体验一下~😄

done
