### ISSUE TITLE
demo中页面的插槽会不断增加的bug

### ISSUE THREAD

**Issue by mark5566** [alibaba/lowcode-engine#416]
## **Describe the bug (required)** / **详细描述 bug（必填）**

页面的插槽会随着‘源码面板“打开次数，逐渐增加

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

1. 打开项目[demo](https://lowcode-engine.cn/demo/index.html)
2. 此时点击打开大纲树，如图所示
![image](https://user-images.githubusercontent.com/11515695/166850277-8a046fe5-5bda-4b66-94aa-41ae962d3db9.png)
此时header为页面的子对象
3. 此时点击“源码面板”
4. 然后关闭“源码面板”
5. 重新点开“大纲树”，发现header的层级结构为Slot>header
![image](https://user-images.githubusercontent.com/11515695/166850422-804a1183-8b6e-4e4a-aff2-ba8fdd0720c3.png)
并且随着如此反复，slot会不断增加

---

English version example：
3. Click on '....'
6. Scroll down to '....'
7. See error

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: 1.0.6
 - AliLowCodeEngineExt version: 1.0.3
 - AliLowCodeEngineDemo : 1.0.17

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by alvarto** [comment]
相关 issue：https://github.com/alibaba/lowcode-engine/issues/367#issuecomment-1109451376

预计将于今日解决

**Comment by alvarto** [comment]
Fixed as of

- @alilc/lowcode-plugin-code-editor@1.0.2
- lowcode-demo 1.0.18
