### ISSUE TITLE
react-renderer 支持定制 appHelper 而 simulator-renderer 不支持定制 appHelper

### ISSUE THREAD

**Issue by twinkle77** [alibaba/lowcode-engine#419]
## **Describe the bug (required)** / **详细描述 bug（必填）**

1. 从官方文档可见， react-renderer 支持传入 appHelper，appHelper 就包括了 constants\utils\requestHandlersMap ...
<img width="1089" alt="image" src="https://user-images.githubusercontent.com/17792166/166859048-79473de9-1d4b-49c4-9064-084d6b7260fa.png">

2.  既然 react-renderer 支持传入 appHelper ，按理说 编辑态 simulator-renderer 也应该支持传入 appHelper，使得运行态跟编辑态统一，但在 simulator-renderer 没有找到配置 appHelper 的口子

下图为源码：

<img width="832" alt="image" src="https://user-images.githubusercontent.com/17792166/166859275-bba3808f-cd9b-4a2c-9541-b026b066781e.png">

appHelper 给写死了

**Comment by twinkle77** [comment]
@LeoYuan 能否加个口子支持传入

**Comment by wulucxy** [comment]
@twinkle77 解决办法能提供下么
