### ISSUE TITLE
setValue 或者 parent.setPropValue("xxx",newData),设置数组ArraySetter嵌套ObjectSetter时，界面ui不会发生变化

### ISSUE THREAD

**Issue by mark5566** [alibaba/lowcode-engine#420]
## **Describe the bug (required)** / **详细描述 bug（必填）**

背景：表格组件的列的配置内容，通过某种方式导入

现实：获取到对应配置信息之后，调用setValue 和 parent.setPropValue("xxx",newData),设置数组ArraySetter嵌套ObjectSetter时，界面ui不会发生变化

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

1. 自定义一个表格
2. 表格的配置列允许通过解析一个对象自动生成
3. 期望通过调用setValue或者setPropValue实现修改为新的数据列的配置内容
![image](https://user-images.githubusercontent.com/11515695/166867418-faf61ad2-f2cc-42dd-ad10-5b35fe3abfaf.png)

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
![image](https://user-images.githubusercontent.com/11515695/166867500-388b2ece-83f9-474b-ac00-d73d2d5f6671.png)
期望将解析之后数据，渲染的setter中
在自定义的setter内，```this.props.field.parent.setPropValue("columns",[])```
发现界面确实发生变化，但是右边setter的内容并未发生变化

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
![image](https://user-images.githubusercontent.com/11515695/166867882-0070b2a2-0d29-474e-a247-f1739f292ac9.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.4] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.3] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by yz1311** [comment]
同样的问题，setPropValue，ArraySetter的界面不会发生变化，但是数据已经改变了

**Comment by zhaoUserName** [comment]
> 同样的问题，setPropValue，ArraySetter的界面不会发生变化，但是数据已经改变了

解决了吗   我这儿是右侧边了  左边数据渲染没变

**Comment by yingzhi8** [comment]
我也是一样，没办法跟schema同步更新,而且，还有另外一个问题，setValue前需要先clear一次，不会替换

**Comment by dlutwuwei** [comment]
研究了一下午，发现还是内部代码的问题，调用setPropValue是会触发setter render,但是内部一些逻辑造成不更新props，目前唯一的处理方式是自定义setter，通过emitter去更新value
```js
import { ReactNode, ComponentType, isValidElement, cloneElement, createElement } from 'react';
import { isReactComponent } from './is-react';

export function createContent(content: ReactNode | ComponentType<any>, props?: Record<string, unknown>): ReactNode {
  if (isValidElement(content)) {
    return props ? cloneElement(content, props) : content;
  }
  if (isReactComponent(content)) {
    return createElement(content, props);
  }
  // 最终逻辑没有props
  return content;
}

```
