### ISSUE TITLE
数据源使用报错，请问数据源应该如何使用？

### ISSUE THREAD

**Issue by CChenXuejun** [alibaba/lowcode-engine#421]
你好，请问我使用数据源报错，是漏了什么步骤吗？
### 复现步骤：
1. 往画布拖入一个TEXT组件
2. 新建一个数据源article，返回数据为json，{"article":"hello lowcode"}
3. 将文本内容绑定为数据源article
4. 预览

### 截图

![数据源](https://user-images.githubusercontent.com/31593062/166870576-221c40ca-f2ad-4c6a-8bdc-4082e29159e8.png)
![绑定数据源](https://user-images.githubusercontent.com/31593062/166870883-7ae74055-6d0b-48f4-9c92-4e6bdd91e3be.png)
![error](https://user-images.githubusercontent.com/31593062/166870891-6f08546c-7590-4b82-9498-f3bceb7839ee.png)

**Comment by xingmolu** [comment]
你的这个报错和数据源是没有关系的，属于组件未加载到，可以查找对应的文档
