### ISSUE TITLE
Demo generates project has js error, can't properly display expected screen.

### ISSUE THREAD

**Issue by bluezealot** [alibaba/lowcode-engine#427]
## 复现截图
1.预览可以表示画面，但是 有很多JS错误
错误内容：base.js:460 Slot component is not found in components list! component list is: Object
截图：
![image](https://user-images.githubusercontent.com/31625086/166912310-51b111b2-8fd3-4043-aa64-55fdbc293e7a.png)
2.下载源码运行，画面出不来，也发生JS错误
错误内容：Uncaught ReferenceError: Slot is not defined
截图：
![image](https://user-images.githubusercontent.com/31625086/166912684-30aec1be-ecab-49ef-bca0-e573a1a7a2e4.png)

## 复现流程与链接
1.启动Demo。
2.执行预览功能，出现上述预览的错误。
3.执行“导出/下载 zip 包”
4.解压缩导出的zip包
请看：
[ali-lowcode-generated-sources (1).zip](https://github.com/alibaba/lowcode-engine/files/8630719/ali-lowcode-generated-sources.1.zip)
5.在解压zip包的目录里执行“npm install”， “npm start”
6.访问 “http://localhost:3333/” ，发生上述下载源码运行的错误

## 期望结果
能够展现出在低代码编辑期里编辑的画面，没有JS错误。

## 环境信息

- 引擎版本 1.0.6

- ext 版本 1.0.3
- 物料
  - moment﹫2.24.0
  - lodash
  - ﹫alifd/next﹫1.24.18
  - NextTable﹫1.0.1
  - ﹫alilc/lowcode-materials﹫1.0.2
  - ﹫alifd/pro-layout﹫1.0.1-beta.6
  - ﹫alifd/fusion-ui﹫1.0.5

**Comment by liujuping** [comment]
不应该有 Slot 组件，相关 bug 修复中
1.可以看看 exportSchema 方法是否有参数（参考最新的 demo 代码）。
2.大纲树组件会带来 Slot，需要升级相关依赖，参考：#367 (comment)

Duplicate of https://github.com/alibaba/lowcode-engine/issues/372
