### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by dj49846917** [alibaba/lowcode-engine#428]
启动npm  run  setup报错，求怎么解决

F:\github\lowcode-engine>npm run setup

> @ setup F:\github\lowcode-engine
> ./scripts/setup.sh

'.' 不是内部或外部命令，也不是可运行的程序
或批处理文件。
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ setup: `./scripts/setup.sh`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ setup script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\Administrator\AppData\Roaming\npm-cache\_logs\2022-05-05T12_39_31_920Z-debug.log

**Comment by liujuping** [comment]
如果是window系统，可以看下这个：https://www.yuque.com/lce/doc/glgn4a

**Comment by dj49846917** [comment]
在windows环境下一定要装WSL才能启动这个项目吗

**Comment by liujuping** [comment]
是的

**Comment by dj49846917** [comment]
我是win10，直接拉下这个项目的master分支，在npm install 之后，执行npm run setup就报上面这个错误了

**Comment by liujuping** [comment]
没有支持win的计划，辛苦装WSL使用。
