### ISSUE TITLE
demo出码后，成功运行 样式丢失

### ISSUE THREAD

**Issue by hongcaohu** [alibaba/lowcode-engine#429]
运用 低代码引擎demo，出码 导出zip包，安装运行后，控制台出现很多warning，关键是样式丢失

---

详细复现步骤：
1. 直接默认页面导出zip代码包
![image](https://user-images.githubusercontent.com/15919714/167053123-26db946d-b42a-472e-90a4-669db1c8d3c8.png)

2. 解压后
   npm install
   npm start
控制台成功运行
![image](https://user-images.githubusercontent.com/15919714/167052927-0e5cd3c2-ff5e-4faa-95bf-7fd5bef025b8.png)

3. 浏览器访问http://localhost:3333，访访问成功，但是样式丢失
![image](https://user-images.githubusercontent.com/15919714/167053045-e9a09797-6a69-42c0-ad36-dbb559540067.png)

4. console控制台报红信息：
index.js:1 Warning: React does not recognize the `verAlign` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `veralign` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Paragraph)
    in Paragraph (created by $$Page)
    in div (created by ForwardRef(Col))
    in ForwardRef(Col) (created by $$Page)
    in div (created by ForwardRef(Row))
    in ForwardRef(Row) (created by $$Page)
    in div (created by ForwardRef(RowColContainer))
    in ForwardRef(RowColContainer) (created by $$Page)
    in div (created by Header)
    in header (created by Header)
    in Header (created by $$Page)
    in div (created by Page)
    in Page (created by $$Page)
    in div (created by $$Page)
    in $$Page (created by WrapperedPageComponent)
    in WrapperedPageComponent (created by RouterWrapperedPage)
    in RouterWrapperedPage (created by WrapperedPageErrorBoundary)
    in WrapperedPageErrorBoundary (created by AuthWrapperedComponent)
    in AuthWrapperedComponent
    in Unknown (created by Context.Consumer)
    in Suspense (created by Context.Consumer)
    in Route (created by Routes)
    in Switch (created by Routes)
    in Routes (created by Routes)
    in div (created by Shell)
    in div (created by Shell)
    in Shell (created by Config(Shell))
    in Config(Shell) (created by BasicLayout)
    in section (created by Shell)
    in section (created by Shell)
    in section (created by Shell)
    in Shell (created by Config(Shell))
    in Config(Shell) (created by BasicLayout)
    in ConfigProvider (created by BasicLayout)
    in BasicLayout (created by Context.Consumer)
    in Route (created by Routes)
    in Switch (created by Routes)
    in Routes
    in Router (created by IceRouter)
    in IceRouter
    in Unknown (created by App)
    in Provider (created by Provider)
    in Provider (created by AuthStoreProvider)
    in AuthStoreProvider (created by App)
    in App

index.js:1 Warning: Each child in a list should have a unique "key" prop.

Check the render method of `Paragraph`. It was passed a child from ForwardRef(Block). See https://fb.me/react-warning-keys for more information.
    in ForwardRef(Cell) (created by ForwardRef(Block))
    in Paragraph (created by ForwardRef(Block))
    in div (created by ForwardRef(Block))
    in div (created by ForwardRef(Block))
    in ForwardRef(Block) (created by $$Page)
    in section (created by PageContent)
    in section (created by PageContent)
    in div (created by PageContent)
    in PageContent (created by Page)
    in div (created by Page)
    in Page (created by $$Page)
    in div (created by $$Page)
    in $$Page (created by WrapperedPageComponent)

index.js:1 Warning: React does not recognize the `isAutoContainer` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `isautocontainer` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Card)
    in Card (created by ForwardRef(BlockCell))
    in div (created by ForwardRef(BlockCell))
    in ForwardRef(BlockCell) (created by $$Page)
    in div (created by ForwardRef(Block))
    in div (created by ForwardRef(Block))

index.js:1 Warning: React does not recognize the `placeholderStyle` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `placeholderstyle` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by ForwardRef(Block))
    in ForwardRef(Block) (created by $$Page)
    in section (created by PageContent)
    in section (created by PageContent)
    in div (created by PageContent)
    in PageContent (created by Page)

index.js:1 Warning: React does not recognize the `headerDivider` prop on a DOM element. If you intentionally want it to appear in the DOM as a custom attribute, spell it as lowercase `headerdivider` instead. If you accidentally passed it from a parent component, remove it from the DOM element.
    in div (created by Page)
    in Page (created by $$Page)
    in div (created by $$Page)
    in $$Page (created by WrapperedPageComponent)
    in WrapperedPageComponent (created by RouterWrapperedPage)
    in RouterWrapperedPage (created by WrapperedPageErrorBoundary)
---

浏览器版本：
chrome 版本 101.0.4951.54（正式版本） （64 位）

**Comment by bluezealot** [comment]
发生了同样的问题。

**Comment by bluezealot** [comment]
添加表格组件之后，居然样式可以正常显示了。还是有一些Bug。也许是demo project的bug.

**Comment by liujuping** [comment]
> 添加表格组件之后，居然样式可以正常显示了。还是有一些Bug。也许是demo project的bug.

可以看看引用的资源有什么差别，大概了是 demo 资产包配置的问题。

**Comment by bluezealot** [comment]
> > 添加表格组件之后，居然样式可以正常显示了。还是有一些Bug。也许是demo project的bug.
> 
> 可以看看引用的资源有什么差别，大概了是 demo 资产包配置的问题。

请问具体是看什么资产包？是demo项目的package.json的内容么？
