### ISSUE TITLE
请问有固定的发包时间节点么？

### ISSUE THREAD

**Issue by haoziqaq** [alibaba/lowcode-engine#430]
希望跟进这个项目的开发进展，我现在就职的公司也选用了这个引擎进行低代码平台开发，请问有固定的发包时间节点么？

**Comment by LeoYuan** [comment]
暂时没有固定发版节奏，目前还是灵活根据解决 bug 的紧急 / 影响大小做判断~

**Comment by haoziqaq** [comment]
了解，感谢感谢，引擎很棒，加油～
