### ISSUE TITLE
物料库的描述有配置能隐藏右侧的配置项吗？

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#431]
比如我想隐藏这个配置项，我并不想删除代码，有什么属性配置吗
![image](https://user-images.githubusercontent.com/50658231/167064229-b323e845-0650-4164-8ebb-b5a01d598d10.png)

**Comment by markyun** [comment]
自定义一个设置器就可以了。

**Comment by LeoYuan** [comment]
condition: () => false
