### ISSUE TITLE
画布设置为 mobile 布局，刷新页面会变成desktop布局，同时缺少设置画布的api暴露。

### ISSUE THREAD

**Issue by markyun** [alibaba/lowcode-engine#432]
## **Describe the bug (required)** / **详细描述 bug（必填）**
    
    1、引擎画布默认设置为： desktop 布局，功能缺少api暴露。
    2、手动设置为 mobile 布局，但刷新页面会变成web布局

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
      
    1、打开 demo： https://lowcode-engine.cn/demo/index.html 
    2、切换为 mobile 布局，刷新页面，又会变成desktop布局。
    

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

期望可以默认设置为 mobile 布局，刷新页面不会修改布局。

 

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
![image](https://user-images.githubusercontent.com/2833137/167066828-38a95ae7-1462-48c7-a934-51938fba05f6.png)

**Comment by LeoYuan** [comment]
```ts
init({
  device: 'mobile', // 可以这样设置
});
```
