### ISSUE TITLE
如何在ReactRenderer组件外（非低代码页面）调用低代码页面的方法

### ISSUE THREAD

**Issue by Dogtiti** [alibaba/lowcode-engine#433]
场景为某个页面是低代码生成的，里面有表单，但是想在外部或者另外的非低代码页面控制表单校验提交等行为，目前不知道将表单实例暴露出来的最佳实践。

实践：
* 使用原子组件中的表单容器组件，该表单组件有事件`onChange` ` onSubmit` ` onSaveField`,经调试发现`onSaveField`事件会在生成页面时就被自动调用并返回`field`实例
![image](https://user-images.githubusercontent.com/38354472/167073863-864e95f2-a440-439d-a4fd-16233dce43fd.png)
于是将`field`传递至自定义方法`getFormField`并挂载到`utils`上，
![image](https://user-images.githubusercontent.com/38354472/167074380-203b801b-5aa5-423e-bab3-8fc2ebbd2a2f.png)

这样在`ReactRenderer`里通过`appHelper`可以拿到回调参数并将`field`暴露出去供外部使用（如下图）
![image](https://user-images.githubusercontent.com/38354472/167073195-0d07a452-d7fa-44bc-8d92-8bdb91aefaa0.png)
这种方法虽然能到达目的但是感觉整个逻辑不够清晰，而且`onSaveField`的调用时机也不太明确，它总是在页面渲染时就被调用，并且每次都需要去手动绑定`onSaveField`事件处理回调，是否有更优雅的方法实现

* 使用精选组件中的电梯表单，该组件只有事件`onChange`,然后通过配置提交、重置等按钮操作来达到对表单的校验等
![image](https://user-images.githubusercontent.com/38354472/167074725-7ce0d202-7bc6-4e7d-962d-0b49c2971c75.png)
这种情况如何将按钮的行为暴露出去由外部调用呢

**Comment by Dogtiti** [comment]
@mark-ck 大佬帮忙看下

**Comment by Tanyangfan** [comment]
我尝试通过onCompGetRef来获取表单实例，你可以试试。
