### ISSUE TITLE
lowcode-material 仓库无法在 windows 电脑下成功打包，原因：路径问题

### ISSUE THREAD

**Issue by blueju** [alibaba/lowcode-engine#434]
## **Describe the bug (required)** / **详细描述 bug（必填）**

lowcode-material 仓库无法在 windows 电脑下成功打包。

报错信息为：
Module not found: Can't resolve 'C:code-workplacelowcode-materials-mainpackagesantd-lowcode-materialssrcindex.scss' in 'C:\code-workplace\lowcode-materials-main\packages\antd-lowcode-materials\.tmp

原因：路径问题，windows 下路径应该是 c:\\xxxx，而 .tmp 目录下的 meta.js 中的路径却是 c:\xxx，从而导致报错

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

在 window 电脑上安装依赖，并在 antd-lowcode-material 目录下运行 npm run lowcode:build 进行打包

Steps to reproduce the behavior: / 详细复现步骤：
---

在 window 电脑上安装依赖，并在 antd-lowcode-material 目录下运行 npm run lowcode:build 进行打包

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

成功打包出物料

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

lowcode-material
https://github.com/alibaba/lowcode-materials

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by blueju** [comment]
@LeoYuan

**Comment by Dogtiti** [comment]
#301 @blueju

**Comment by LeoYuan** [comment]
参见 readme 中对 windows 的要求~

**Comment by blueju** [comment]
不好意思，一时着急没留意 issue，为自己的不经意给你们带来的重复工作感到抱歉
