### ISSUE TITLE
我想修改这块儿的样式，请问应该从哪里入手

### ISSUE THREAD

**Issue by panda0000009** [alibaba/lowcode-engine#435]
![image](https://user-images.githubusercontent.com/49061144/167085788-17d9f5a7-09e6-4d9d-a057-2ae232fa4529.png)

**Comment by LeoYuan** [comment]
css 覆盖？

**Comment by panda0000009** [comment]
> 

![image](https://user-images.githubusercontent.com/49061144/167087456-a7d26abe-c0dc-4df3-840c-da738061b793.png)
![image](https://user-images.githubusercontent.com/49061144/167087552-d6ce1c0a-b7d5-43a1-8ade-da314bd3e0d4.png)
它这块儿用的引擎包里东西，然后babel编译过来的。

css覆盖的话，样式太难调了。
![image](https://user-images.githubusercontent.com/49061144/167088100-70053be0-84bf-44c9-b5ea-5cefa782e0b4.png)

请问下，有什么其他方法嘛，配置项什么的

**Comment by LeoYuan** [comment]
跟 babel 有啥关系。。。

css 覆盖是目前我能想到最简单的方式

**Comment by Ronchan0805** [comment]
> > 
> 
> ![image](https://user-images.githubusercontent.com/49061144/167087456-a7d26abe-c0dc-4df3-840c-da738061b793.png) ![image](https://user-images.githubusercontent.com/49061144/167087552-d6ce1c0a-b7d5-43a1-8ade-da314bd3e0d4.png) 它这块儿用的引擎包里东西，然后babel编译过来的。
> 
> css覆盖的话，样式太难调了。 ![image](https://user-images.githubusercontent.com/49061144/167088100-70053be0-84bf-44c9-b5ea-5cefa782e0b4.png)
> 
> 请问下，有什么其他方法嘛，配置项什么的

从代码上来看确实是babel编译过来的，请问解决了吗
