### ISSUE TITLE
lowcode-demo 发布后直接打开preview.html页面报错 必须先得从index.html页面点右上角预览按钮才能打开preview.html页面

### ISSUE THREAD

**Issue by taolei1990** [alibaba/lowcode-engine#437]
问题：我现在把lowcode-demo部署起来了 也有schema.json数据想着应该可以直接打开preview.html渲染出页面的但是好像有数据了也不能预览 必须先得从index.html页面点右上角预览按钮才能打开preview.html页面
期望：能不能直接用schema.json数据打开preview.html就渲染出页面 

![微信图片_20220506155656](https://user-images.githubusercontent.com/23173640/167091335-baabc1b3-2e5f-4db9-9387-ca3797788ebf.png)

![微信图片_20220506155739](https://user-images.githubusercontent.com/23173640/167091400-bee8acbd-f7ae-4d53-9c49-1f1cec05e652.png)

**Comment by liujuping** [comment]
看看 preview 相关的代码，有从 localStorage 获取 schema 相关的逻辑。

你的需求需要针对这块逻辑进行修改，从你期望的地方获取 schema。
