### ISSUE TITLE
onAddNode 触发有问题

### ISSUE THREAD

**Issue by leehomeok** [alibaba/lowcode-engine#438]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

通过action栏点击高级表单时会触发 project?.currentDocument?.onAddNode((function (node){ }))事件

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
鼠标hover到输入框，点击高级表单

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为
不触发 onAddNode事件

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
![image](https://user-images.githubusercontent.com/13464485/167097853-f3a97343-c2ac-4902-bd1c-05cbd6fa3af8.png)
---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.5] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.3] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本  chrome 100
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

**Comment by leehomeok** [comment]
同样的，点击Filter组件 也会有同样的问题，
![image](https://user-images.githubusercontent.com/13464485/167102374-3bf42b2d-f8e8-49fa-a8ac-8637c29266a8.png)
点击大纲树， 点击对话框，再点击查询筛选，也会触发onAddNode

**Comment by LeoYuan** [comment]
因为高级表单底层会频繁调用 removeNode 和 addNode，所以确实会不断触发事件~
