### ISSUE TITLE
出码引擎发送的请求访问有错误

### ISSUE THREAD

**Issue by haoziqaq** [alibaba/lowcode-engine#439]
出码引擎似乎会发送一个 schema 请求，这个请求是做什么的？并且这个请求似乎无法访问

请求地址: https://dev.g.alicdn.com/ali-lowcode/ali-lowcode-materials/1.1.0/schema.json

<img width="847" alt="image" src="https://user-images.githubusercontent.com/24223652/167108333-77406a11-bb36-47da-b952-74f0e403abf3.png">

**Comment by haoziqaq** [comment]
不知道有没有进展？

**Comment by hi-heshuai** [comment]
有人解决问题吗

**Comment by JackLian** [comment]
曾经用于检测网络环境的，忽略即可

**Comment by ZhangMengNan** [comment]
有人解决吗？

**Comment by JackLian** [comment]
不是写着吗，忽略即可
