### ISSUE TITLE
实体(Entity)设计器、数据建模

### ISSUE THREAD

**Issue by linzer** [alibaba/lowcode-engine#44]
请教下：
1，框架会涉及**实体**设计器、**数据**建模型相关不？
2，框架**只会**涉及客户端相关？还是会涉及**服务端**的实体建模、数据建模、服务端业务服务或插件编码及编排？
3，假如目前规则不涉及实体设计器、数据建模型，有没**建议**的实现及集成思路

**Comment by leehomeok** [comment]
Mark

**Comment by LeoYuan** [comment]
请参考：https://github.com/alibaba/lowcode-engine/discussions/45
