### ISSUE TITLE
 如何在插件内，获取 init 时 preference 设置的值？

### ISSUE THREAD

**Issue by markyun** [alibaba/lowcode-engine#445]
demo项目中，如何获取preference设置的值
![image](https://user-images.githubusercontent.com/2833137/167236634-fea5c92b-bc81-44f5-a071-d6ac7c880742.png)
 
## 设置值：

`
preference.set('simulatorPanes', {
  defaultDevice: 'App1',
});

`

## 获取值？ plugins.get('simulatorPanes');

    
    const simulatorPanes = (ctx: ILowCodePluginContext) => {
      return {
        name: 'simulatorPanes',
        async init() {
          const { skeleton } = ctx;
          //   如何获取值？
          const { defaultDevice } = plugins.get('simulatorPanes');
          skeleton.add({
            name: 'simulatorPanes',
            area: 'toolbar',
            type: 'Widget',
            props: {
              align: 'center',
              description: '切换画布尺寸',
            },
            content: simulatorPane,
          });
        },
      };
    };
    simulatorPanes.pluginName = 'simulatorPanes';
    simulatorPanes.meta = {
      preferenceDeclaration: {
        title: 'simulatorPanes 的参数定义',
        properties: [
          {
            key: 'defaultDevice',
            type: 'string',
            description: 'this is description for defaultDevice',
          },
        ],
      },
    };
    export default simulatorPanes;

**Comment by LeoYuan** [comment]
插件内执行：

```ts
ctx.preference.getPreferenceValue('defaultDevice');
```

**Comment by markyun** [comment]
> 插件内执行：
> 
> ```ts
> ctx.preference.getPreferenceValue('defaultDevice');
> ```

get it. thx.

另外下面这块的写法，是为了限定插件入参的值嘛，只有在preferenceDeclaration定义的，才能被接受？
     
    
    simulatorPanes.pluginName = 'simulatorPanes';
    simulatorPanes.meta = {
      preferenceDeclaration: {
        title: 'simulatorPanes 的参数定义',
        properties: [
          {
            key: 'defaultDevice',
            type: 'string',
            description: 'this is description for defaultDevice',
          },
        ],
      },
    };

**Comment by LeoYuan** [comment]
是的，保留一种技术可能性，从插件市场选择插件，并配置插件参数后，生成设计器～

**Comment by senylin** [comment]
plugins.get('codeEditor')的方式能获取 插件的 exports吗
