### ISSUE TITLE
设计器初始化，Modal 类组件 hidden 属性被强制设置 true，会导致在预览时无法渲染 Modal 组件

### ISSUE THREAD

**Issue by twinkle77** [alibaba/lowcode-engine#446]
## **Describe the bug (required)** / **详细描述 bug（必填）**

设计器初始化，Modal 类组件 hidden 属性被强制设置 true，会导致在预览时无法渲染 Modal 组件

<img width="541" alt="image" src="https://user-images.githubusercontent.com/17792166/167242979-e9d1e11e-0568-4383-a397-d5e60d450b58.png">

复现 schema

```
{
  "componentName": "Page",
  "id": "node_dockcviv8fo1",
  "props": {},
  "fileName": "sample",
  "hidden": false,
  "title": "",
  "isLocked": false,
  "condition": true,
  "conditionGroup": "",
  "children": [
    {
      "componentName": "Dialog",
      "id": "node_ocl2vipavv1",
      "props": {
        "prefix": "next-",
        "footerAlign": "right",
        "title": "Title",
        "footer": true,
        "footerActions": [
          "ok",
          "cancel"
        ],
        "closeable": "esc,close",
        "hasMask": true,
        "align": "cc cc",
        "minMargin": 40,
        "isAutoContainer": true,
        "visible": true
      },
      "hidden": true,
      "title": "",
      "isLocked": false,
      "condition": true,
      "conditionGroup": ""
    }
  ]
}
```

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1.  打开 https://lowcode-engine.cn/demo/basic-fusion.html
2. 拖入一个 dialog 组件，点击 “预览”，由于是第一次拖入，此时 hidden 为 false、 visible 为 true，所以首次"预览"可以看到 dialog 
3. 回到设计器，刷新页面，再点击 “预览“，此时是二次”预览“,  此时 hidden 为 true、 visible 为 true, 发现 dialog 组件渲染不出来

**刷新页面，设计器重新初始化，dialog 的 node 节点， hidden 属性被强制设置为 true 了**

## **Additional context (optional)** / **更多额外信息（可选）**

刷新页面，引擎重新初始化，把 modal 类组件 hidden 设置为 true 是可以理解（因为一进来设计器就显示弹窗，会干扰用户搭建），但 hidden 这个值是否应该在 schema 留存呢？

**Comment by liujuping** [comment]
这个已经解决，可以看看最新的 demo。

1.新增了 Save 态的 propsReducer，会将 hidden props 去掉。

2.保存的 schema 使用的是 Save 态的，即 exportSchema(xxx.Save)

**Comment by twinkle77** [comment]
@liujuping  谢谢 我看下，我马上看下，没问题的话，我马上关掉

**Comment by twinkle77** [comment]
代码位置： https://github.com/alibaba/lowcode-demo/blob/main/src/sample-plugins/delete-hidden-transducer/index.ts

**Comment by 15163789836** [comment]
> 代码位置： https://github.com/alibaba/lowcode-demo/blob/main/src/sample-plugins/delete-hidden-transducer/index.ts

你好 现在一个页面如何使用多个页面的问题解决了嘛，如何解决的呀 大佬   请问大佬  如何在页面怎么使用呀
