### ISSUE TITLE
ExpressionSetter  在第二次输入值后对schema修改错误

### ISSUE THREAD

**Issue by wssgchungang** [alibaba/lowcode-engine#449]
## **详细描述 bug（必填）**

ExpressionSetter  在第二次输入值后对schema修改错误

## **如何复现 bug？（必填，非常重要）**

 详细复现步骤：

1. 假设组件其中一个属性“width”设置器是ExpressionSetter，刚开始为空，绑定 “this.state.hello”, 在schema中显示为
 "width": {
    "type": "JSExpression",
    "value": "this.state.hello",
   }
2. 再次修改，绑定“this.state.outer”，在schema中显示为
 "width": {
    "type": "JSExpression",
    "value": "this.state.hello",
    "mock": {
      "type": "JSExpression",
      "value": "this.state.outer"
    }
   }
 并没有改成期望的结构，多了个mock属性
  "width": {
    "type": "JSExpression",
    "value": "this.state.outer",
   }

**Comment by LeoYuan** [comment]
@hzd822 帮忙鉴定下？

**Comment by hzd822** [comment]
引擎版本说明下，我用play now的demo是好的，你也可以在play now的demo里面试下，是否可以复现
