### ISSUE TITLE
预览组件有几率出现组件加载失败，不渲染

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#451]
@alilc/lowcode-plugin-code-editor 用的是最新的1.0.2

这是正常情况下
![image](https://user-images.githubusercontent.com/50658231/167248952-39dd072a-d00d-4d96-ad9b-42920ac2bfe4.png)

偶尔刷新的情况下，会出现资源不存在的情况。因为输入框、选择框物料是我自己重写的包，所以没出现这个问题
![image](https://user-images.githubusercontent.com/50658231/167248994-7cd7d714-4957-4e5b-bf7a-931097abb11b.png)

**Comment by oneQiu** [comment]
![image](https://user-images.githubusercontent.com/50658231/167249350-f91e383c-4af8-4b7e-afac-8c6bb64934b4.png)
local存储的包信息

**Comment by LeoYuan** [comment]
渲染页面的资源加载不是你自己保证的么？

**Comment by blueju** [comment]
@oneQiu 
这个问题我遇过，我最近也在公司内部弄低代码，物料也都是公司内部的组件库经过物料转换的。

我们公司内部的组件库是基于 antd 二次封装的，因为都是使用 npm 的方式使用，所以重来没重视过 umd 包，umd 包中没有将 antd 打包进来，在使用时需要把 antd 先 script 引入进来。
在后续的预览过程中遇到了和你一样的问题，报的错误我记得也是类似的，说未发现某些组件的属性。

原因在于 antd  umd 包的加载速度慢于你物料 umd 包的加载速度（你可以看看 network 里的耗时），导致你物料 umd 包先执行。这里其实我也很奇怪，按理来说，script 的加载是并发的，但是执行是按顺序的呢。

所以最后问题很可能出在你组件的 umd 包（那种可以直接在浏览器中直接 script 引入加载的包），你可能没有将你的前置依赖 antd 打包进去。

我最后的解决方案是：我们的 umd 包将 antd 一并打包进来，后续物料描述文件 assets.json 那里就不再需要既引入 antd 又 引入我们的组件库了。

最后可以参考一下我自己根据内部组件库的经验，写的一套壳子，它输出 dist 的 umd 包中包含了 antd 的代码，使用时不再需要先行 script 引入 antd。
[https://github.com/blueju/blue-design](https://github.com/blueju/blue-design)

**Comment by oneQiu** [comment]
> 

感谢

**Comment by liujuping** [comment]
这个问题重复了，辛苦在这个 issue 里面继续跟踪进度，为了方便管理，这个问题我先关掉了。

Duplicate of https://github.com/alibaba/lowcode-engine/issues/329
