### ISSUE TITLE
npm install失败

### ISSUE THREAD

**Issue by qilong1997** [alibaba/lowcode-engine#452]
装包失败，提示@alilc/lowcode-demo@1.0.18 Error

**Comment by blueju** [comment]
麻烦按照模板说清楚呀，是本工程吗？

这个工程下的收集的是整个 lowcode-engine 生态的 issue，按模板说清楚是哪个好区分。

最近也在用，这样子不按模板写 issue，想为社区贡献点自己的力量都很难做呢。
