### ISSUE TITLE
修改已有物料的 group 和 category 字段值的钩子

### ISSUE THREAD

**Issue by twinkle77** [alibaba/lowcode-engine#453]
## **Describe the bug (required)** / **详细描述 bug（必填）**

下图来自物料文档 - https://lowcode-engine.cn/material

<img width="646" alt="image" src="https://user-images.githubusercontent.com/17792166/167279606-73cb50d4-bd61-4dec-a573-88b4e6ca4f2c.png">

group 和 category 决定了物料在组件面板的展示位置，现在想把 白名单内的组件( 比如 Modal、Drawer、Tooltip ... 类的组件）归类为 “常用组件”，因为 category 在打包成物料库之前，就已被写死了

1. 想在设计器初始化时，动态修改  category 字段
2. 或者有没有办法，对已有物料的 snippets 重新描述 或 覆盖

**Comment by LeoYuan** [comment]
material.registerMetadataTransducer 试试看~

**Comment by twinkle77** [comment]
https://github.com/alibaba/lowcode-engine/issues/476
