### ISSUE TITLE
不能通过单击按钮显示弹窗

### ISSUE THREAD

**Issue by lianglinux5** [alibaba/lowcode-engine#455]
## **不能通过单击按钮显示弹窗**
页面定义一个按钮和弹窗，单击按钮设置弹窗为显示状态。弹窗显示不出来

这个Dialog本身有个state属性visible不知道在哪里控制的

**Comment by lianglinux5** [comment]
<img width="1727" alt="image" src="https://user-images.githubusercontent.com/14293060/167284314-6076b6c2-83ab-4fe6-85a2-bd08bc3523fc.png">

**Comment by liujuping** [comment]
可以看看这个issue https://github.com/alibaba/lowcode-engine/issues/446

**Comment by lianglinux5** [comment]
<img width="1724" alt="image" src="https://user-images.githubusercontent.com/14293060/167328774-45f97708-e18e-4c37-bb83-007e7ded7e2d.png">

<img width="621" alt="image" src="https://user-images.githubusercontent.com/14293060/167328895-3d621bfb-0ada-48b5-bedc-084ba91b562a.png">

<img width="1720" alt="image" src="https://user-images.githubusercontent.com/14293060/167328967-3a0714a1-f235-412e-ba0a-c7f93cf5a74c.png">

**Comment by lianglinux5** [comment]
在组件state里定义 isShowDialog来控制弹窗是否显示,不起作用。看渲染出来的弹窗组件是本身有自己的state.这个父组件不知道怎么控制了

**Comment by liujuping** [comment]
refid 目前还不支持查看，不是图片中的那个。

需要从 schema 里面查看，找到组件，找到 ref 参数。

![image](https://user-images.githubusercontent.com/11935995/167329362-97497ba2-78a1-43a6-aea4-2f709f7e5b26.png)

**Comment by lianglinux5** [comment]
可以了。多谢
