### ISSUE TITLE
1.谢谢 绑定表达式这个我知道，我想问的是 接口给我反过来的数据字段 不是value lable ，我如何自定义用来显示的字段

### ISSUE THREAD

**Issue by 15163789836** [alibaba/lowcode-engine#456]
1.

![image](https://user-images.githubusercontent.com/11935995/167327114-12c8aafe-c7d5-4e28-98e7-5c3c454a4977.png)

2.

配置数据源，获取接口内容，传到上图的表达式中。

_Originally posted by @liujuping in https://github.com/alibaba/lowcode-engine/issues/441#issuecomment-1120548814_

**Comment by liujuping** [comment]
这个目前的组件不支持配置，有下面两种处理方式

1.将数据转化成符合结构的格式。
2.开发一个可以支持配置的 Select 组件。
