### ISSUE TITLE
直接预览的时候 在preview 中获取不到组件列表（packages） 和数据schema 

### ISSUE THREAD

**Issue by taolei1990** [alibaba/lowcode-engine#457]
根据官方文档
![image](https://user-images.githubusercontent.com/23173640/167329675-179aac51-c5df-4759-8d19-591fe47ba618.png)
先获取组件列表在存在浏览器中然后在获取 就能在预览的时候加载出页面了 这个是能实现预览 但是问题是必须从设计器中获取组件列表然后存起来然后在打开预览页面才能加载页面
但是我们做出来的页面应该是要直接打开的不需要在经过设计器呀 现在问题是现在直接在preview中获取不到组件列表
![image](https://user-images.githubusercontent.com/23173640/167329882-04e3b12a-6215-4a96-a090-3e94a024ae04.png)
这种情况是不是需要将组件列表数据和设计出来的Schema数据都保存到服务器 然后在preview页面中通过接口获取到这两份数据才能加载出页面 目前项目等着上线 求大佬解救

**Comment by liujuping** [comment]
实际项目中，应该存储到数据库里面，根据路径获取 schema 和 物料列表啥的。

**Comment by taolei1990** [comment]
谢谢 明白了
