### ISSUE TITLE
antd一些组件不能选中问题，除了二次封装发包解决还有其他更简单的方法吗

### ISSUE THREAD

**Issue by mDing11** [alibaba/lowcode-engine#458]
antd/pro-component内的一些组件不能选中问题，看到你们修复是进行了二次封装然后再发包，我想直接用原始组件库，不想再自己维护一个组件包，有其他解决办法嘛

**Comment by oneQiu** [comment]
我是把antd那套的资产包的json拷贝了过来，然后自己弄了一个物料库，专门解决那个别几个出问题的组件

**Comment by twinkle77** [comment]
没法....
编辑态组件 跟 原始组件 总归会有些不同
