### ISSUE TITLE
Feature: @alifd/build-plugin-lowcode library config not work

### ISSUE THREAD

**Issue by yingyuk** [alibaba/lowcode-engine#460]
## **Describe the bug (required)** / **详细描述 bug（必填）**

`@alifd/build-plugin-lowcode` `library` config not work

https://github.com/alibaba/lowcode-materials/blob/main/packages/antd-lowcode-materials/build.lowcode.js#L17

https://github.com/alibaba/lowcode-materials/blob/main/packages/fusion-lowcode-materials/build.json#L2

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

<img width="979" alt="image" src="https://user-images.githubusercontent.com/16535206/167381686-9f4fa1b1-f1ad-4ea7-9e77-3fa4e907b956.png">

<img width="1105" alt="image" src="https://user-images.githubusercontent.com/16535206/167384222-b3d6b2d4-b9c5-4375-b761-e3e47ce162b3.png">

**Comment by LeoYuan** [comment]
@mark-ck hey, tough guy, plz check this out 😄

**Comment by wulucxy** [comment]
same problem here~，为啥要关掉

**Comment by mark-ck** [comment]
没懂，怎么不 work 了
