### ISSUE TITLE
为什么编辑和预览打印的this值不相同？

### ISSUE THREAD

**Issue by lsztiwate** [alibaba/lowcode-engine#461]
<img width="964" alt="企业微信截图_ef7bd4d2-7e56-426a-b29a-4c18bd1e51b2" src="https://user-images.githubusercontent.com/100106108/167386169-004794c7-5fa8-475c-93d7-87b3c563ddde.png">

<img width="793" alt="企业微信截图_4d180df2-7fe2-4a8a-b9fd-ce414ac1b20d" src="https://user-images.githubusercontent.com/100106108/167386341-647ad24a-80ac-4e8a-a74c-d127010d04f9.png">

编辑时可以拿到appHelper值，预览时却找不到了，我该如何使用一个全局变量和公共方法呢？

**Comment by LeoYuan** [comment]
![image](https://user-images.githubusercontent.com/1195765/167537405-4deba585-1990-486c-9793-d2b682e64ea7.png)

**Comment by lsztiwate** [comment]
> ![image](https://user-images.githubusercontent.com/1195765/167537405-4deba585-1990-486c-9793-d2b682e64ea7.png)

我在编辑器中无法设置appHelper，这样就不能保证编辑器和渲染出来的页面是相同的appHelper。 请问在编辑器中如何设置appHelper来保持统一呢？

**Comment by LeoYuan** [comment]
设计态通过注入自定义 utils，其他 requestHandlersMap 暂时还未支持传入~
渲染态，如上图直接自定义 appHelper.utils 即可~

> 注：这个 demo 只是为了验证能力，要注入个性化的 utils 以及保持 设计渲染一致性，还是得上层的各个平台自己去做~

**Comment by twinkle77** [comment]
@LeoYuan 
设计态支持 appHelper 是刚需呀，如果跟  运行时的 appHelper 不一样
设计态中间画布执行代码 直接就报错了

**Comment by twinkle77** [comment]
https://github.com/alibaba/lowcode-engine/issues/419
其实是同一个问题
