### ISSUE TITLE
数据源load方法无法进行错误处理

### ISSUE THREAD

**Issue by lsztiwate** [alibaba/lowcode-engine#462]
<img width="984" alt="企业微信截图_acd0056b-dc91-4024-a9df-147080fda4ce" src="https://user-images.githubusercontent.com/100106108/167389122-10472cef-cd07-4fd3-bf55-091c0aebe34e.png">

低代码使用过程中，使用dataSourceMap。load()方法调用接口，无法获取接口失败的信息！

请问如何该使用数据源load方法呢？

**Comment by LeoYuan** [comment]
@xingmolu 有没有文档描述如何判断请求失败？4xx / 5xx / 2xx（success: false）？

**Comment by xingmolu** [comment]
数据源面板里的 `errorHandler` 配置里可以处理错误信息

**Comment by lsztiwate** [comment]
> 数据源面板里的 `errorHandler` 配置里可以处理错误信息

测试过 数据源中的错误处理函数 在执行load中无法触发。

**Comment by lsztiwate** [comment]
找到问题所在了，执行load方法时要确定是否有setState，一定要等到setState执行完成后再使用load方法。否则会拿不到数据源请求的状态 @xingmolu @LeoYuan

**Comment by xingmolu** [comment]
@lsztiwate 数据源中的错误处理函数没有执行的原因是之前的官方demo中没有启用数据源引擎导致，目前已经提交PR修复该问题：https://github.com/alibaba/lowcode-demo/pull/29
