### ISSUE TITLE
demo出码报错，预览样式丢失

### ISSUE THREAD

**Issue by Osub** [alibaba/lowcode-engine#465]
` yarn start
yarn run v1.22.17
$ icejs start
ice.js 1.18.5
info 使用 Fusion 组件主题包： @alifd/theme-design-pro
 WARNING  Compiled with 2 warnings上午10:08:51

 warning  in ./node_modules/@alifd/pro-layout/es/pro-card/index.js

"export 'CardProps' was not found in './components/card'

 warning  in ./node_modules/@alifd/pro-layout/es/pro-card/index.js

"export 'CardSectionProps' was not found in './components/card-section'

 ERROR  Failed to compile with 1 errors上午10:08:51

This dependency was not found:

* @alilc/lowcode-materials in ./src/pages/$/index.jsx

To install it, you can run: npm install --save @alilc/lowcode-materials
Error from chokidar (D:\): Error: EBUSY: resource busy or locked, lstat 'D:\pagefile.sys'`

**Comment by Osub** [comment]
安装 @alilc/lowcode-materials 后 依然不能解决问题

**Comment by LeoYuan** [comment]
运行 yarn start 之前做了什么操作，假如没有任何操作，空页面导出，也请写清楚~

**Comment by Osub** [comment]
添加了一个 选项卡 组件， 空页面导出也有问题
