### ISSUE TITLE
如何跟go后端搭配使用？没有找到最佳实践

### ISSUE THREAD

**Issue by xiaofeige** [alibaba/lowcode-engine#468]
文档实在是写的太不行了，我耍了好久没发现怎么导出我编辑的页面，然后搭配我写的golang后端使用。
我理解出码功能会编译出一个页面，然后我改改配置文件中后端的地址就可以了，但是没找到入口，编译之后的东西没法用。

太难用了，低代码的初衷本来就是降低编码难度，为何感觉这个理解成本不亚于我直接自己写前端？

**Comment by JackLian** [comment]
亲，这个是给前端开发者来做一个自己的低代码平台，来服务某些特定用户人群，并非直接提供给终端用户使用的，如果您这边需要降低写前端需求的成本，可以考虑一些其他的成熟的面向后端开发者的低代码平台
