### ISSUE TITLE
升级`lowcode-engine1.06 -> 1.0.7`之后，大纲树一直在初始化

### ISSUE THREAD

**Issue by haoziqaq** [alibaba/lowcode-engine#472]
<img width="341" alt="image" src="https://user-images.githubusercontent.com/24223652/167827480-c334e2c6-eb46-48ae-8136-1eb6e0fd3a3a.png">

升级`lowcode-engine1.06 -> 1.0.7`之后，大纲树显示不出来，一直显示初始化

**Comment by twinkle77** [comment]
同

**Comment by liujuping** [comment]
问题修复中。可以先用之前版本的引擎。

**Comment by liujuping** [comment]
fixed in lowcode-engine 1.0.8
