### ISSUE TITLE
如何替换顶层容器？

### ISSUE THREAD

**Issue by ImSwordTooth** [alibaba/lowcode-engine#473]
## **Describe the bug (required)** / **详细描述 bug（必填）**
使用的是 lowcode-engine-demo，默认给的顶层容器是 Page，点到 Page 那一层，属性面板是空的。
**如何使用自己的组件去替换顶层容器呢？**
或者退而求其次，怎么给Page添加属性值？  

我有试过修改 assets.json 的components字段，但是不知道Page组件都有什么props，而且估计也不够用。
[宜搭](https://vv0f3i.aliwork.com/home/)的项目顶层容器似乎是自定义的。

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
详细复现步骤：
1. 打开 [demo](http://lowcode-engine.cn/demo)
2. 点击大纲树的顶层容器；
3. 右侧属性面板为空

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

希望能有替换顶层容器的方案。

---

## **Screenshots (optional)** / **bug 截图（可选）**
![image](https://user-images.githubusercontent.com/43266605/167826979-23775cdc-2e4d-4ba2-92e6-306f93c1d7c2.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - 低代码引擎版本：1.0.0
 - 低代码引擎扩展包版本：1.0.0
 - 浏览器版本：chrome 101.0.4951.54
 - 其他物料 / 插件 / 工具链版本：无

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

**Comment by LeoYuan** [comment]
那你就自定义一个 Page 组件好了，属性都可以自己定义~

**Comment by ranyue** [comment]
出码的时候，如何自定义Page, nodeTypeMapping 对应的 page 对应的是字符串

**Comment by zxfwaxx** [comment]
> 那你就自定义一个 Page 组件好了，属性都可以自己定义~

自定义的page无法向里面拖拽其他物料，怎么解决一下，麻烦可以告知一下吗

**Comment by sanmao666** [comment]
> > 那你就自定义一个 Page 组件好了，属性都可以自己定义~
> 
> 自定义的page无法向里面拖拽其他物料，怎么解决一下，麻烦可以告知一下吗

2周过去了，请问你解决了嘛，我也碰到了
