### ISSUE TITLE
只想展示自定义的组件库，我该如何去做呢？

### ISSUE THREAD

**Issue by Jveen-D** [alibaba/lowcode-engine#476]
报告老板，这不是一个`bug`，这不是一个`bug`，这不是一个`bug`。
我在实现项目的过程中，遇到了一个问题不知道怎么去解决。我自己新建了一个组件库，一共实现了`17`个常用的组件，而我在组件库只想展示这`17`个组件，想把默认的`精选组件`和`原子组件`藏起来，并且想保留`精选组件`中的`行列容器`组件。我也想重新写一个`行列容器`组件，后来发现难度太大了...

我尝试过在`assets.json`直接把`@alifd/pro-layout`、`@alifd/fusion-ui`这两个资产包去掉了，确实大多数组件都消失了，但是这样也会把我想要的一些组件搞丢。

我也尝试配置过`assets.json`中的`ignoreComponents`字段，但是这个字段在语雀没有说明，不知道该怎么去修改。

求帮助！
![image](https://user-images.githubusercontent.com/46897216/167855276-6c425672-aae5-4e21-b2ad-623516adc6c2.png)

**Comment by alvarto** [comment]
https://github.com/alibaba/lowcode-plugins/tree/main/packages/plugin-components-pane

最简单的方式是，clone 这个面板并修改里面的逻辑～

**Comment by alvarto** [comment]
比如你可以修改 initComponentList 里的逻辑，筛选具体的部分：

<img width="604" alt="image" src="https://user-images.githubusercontent.com/1797855/167856185-37a18ce4-80f5-4a37-8597-a75b8856f394.png">

**Comment by Jveen-D** [comment]
性感猛虎，在线答题，thx~
