### ISSUE TITLE
无法出码“选项卡”

### ISSUE THREAD

**Issue by yuuagoo** [alibaba/lowcode-engine#478]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

当页面加入“选项卡”组件后，点击出码报错  Invalid Identifier [Tab.Item]

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

1、面板拖入“选项卡” 组件
2、点击出码

---
![image](https://user-images.githubusercontent.com/57406595/167979792-0d6a25bf-9f27-4416-82e2-1ec2c02fabd3.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
    "@alilc/lowcode-engine": "^1.0.0",
    "@alilc/lowcode-engine-ext": "^1.0.0",

**Comment by shayulei** [comment]
我也出现这个错误，不知道怎么排查。

**Comment by xusanduo08** [comment]
我是自定义的组件，也出现了类似的错误
![image](https://user-images.githubusercontent.com/17930163/168512297-c337ae91-c9a2-46a1-9692-cc5e46fc8f77.png)

**Comment by shayulei** [comment]
怎么关注这个问题

**Comment by Clarence-pan** [comment]
这个应该是因为 `Tab.Item` 这个组件名不是一个有效的 JS 标识符导致的：
![image](https://user-images.githubusercontent.com/8750132/169935712-163a3667-44d0-450b-a3e7-0c2317be1a5f.png)
相关规范：
![image](https://user-images.githubusercontent.com/8750132/169935794-0a05eb4a-46c6-44bc-85e7-c36a0dbb54c1.png)

@mark-ck 帮忙看看吧 是不是可以在资产包里定义标签页的时候将 `Tab.Item` 定义为 `TabItem` （去掉中间的点）

**Comment by maimai123** [comment]
一样，添加选项卡组件时，出码报错
