### ISSUE TITLE
请大家谈一谈对于目前引擎文档有什么不足之处

### ISSUE THREAD

**Issue by LeoYuan** [alibaba/lowcode-engine#48]
引擎整体文档：https://lowcode-engine.cn/doc
引擎 API：https://lowcode-engine.cn/doc?url=bv3und

用户文档是我们认为项目中非常重要的一部分，想听听大家的建议~
善意的批评我们会虚心接受，有好的建议我们会积极采纳，感谢大家~

**Comment by ChesterBu** [comment]
请教下addonRenderer、TempRenderer这两者与PageRenderer的区别是什么呢，以及对应使用场景是哪些呢？

**Comment by better-owlet** [comment]
对状态共享、事件操作一块介绍不够丰富。如出码看到有 i18n的实例方法，但在配置里又不是内置函数。模棱两可。
对API使用的示例不足。

**Comment by chensce** [comment]
尽快把标注为wip的部分，编写完整。
这个项目非常有价值，希望能够有很大的发展。

**Comment by LaiZhou** [comment]
官方文档和demo里的代码基本没有匹配的，建议组织下文档，先来个上手扩展的step by step ，然后给个reference做细节详细说明。

**Comment by alvarto** [comment]
@LaiZhou 收到，这个项目的 demo 和文档量是非常大的，我们尽快优化 reference 问题。

**Comment by xieshaohu** [comment]
建议针对Demo有一个快速上手的简单说明，当前功能划分非常清晰，但是具体怎么把动态数据绑定到组件上没有找到功能、也没有找到文档。

**Comment by alvarto** [comment]
> 建议针对Demo有一个快速上手的简单说明，当前功能划分非常清晰，但是具体怎么把动态数据绑定到组件上没有找到功能、也没有找到文档。

@xieshaohu 在 demo 上左下角的问号，有产品使用文档。

**Comment by jasonjcpeng** [comment]
正在研究针对setter的二次开发，目的是要在精选组件上扩展setter。
现在遇到的问题是，没有找到setter较详细的协议描述。
能有较完善的setter的二开Demo就更好了。

**Comment by lulg** [comment]
文档建议细化一下，有点云里雾里，最好有按场景的完整教程。

**Comment by alvarto** [comment]
@lulg 产品使用文档在 demo 上左下角的问号；如果是编辑器扩展，文档里有写；可以详细描述一下哪里需要完善吗？

**Comment by lulg** [comment]
> 

这个文档整体有点偏架构技术原理。是否可以通过使用场景来做一个完整的描述，比如我作为一个产品或者实施人员，如何快速搭建完一个简单的增删查改的流程。

我研究的时候关注了以下几个点，没有找到明确答案：
1.组件之间如何互动，比如一个表格，左边有一棵树，选中树节点可以对表格进行过滤。是使用事件配置吗，能否做到前端零编码。
2.页面之间如何传参，比如我一个列表页，有个自定义按钮，按钮弹出另一个页面，需要往弹出的页面上传一些参数。
3.将来该框架是否有配合后台元数据编程等方面的支持，这样就不用挨个字段配置属性了，直接通过配置元数据就可以了。

**Comment by alvarto** [comment]
@lulg 收到，我们后续文档补充一下这些场景的解决方案描述

**Comment by lulg** [comment]
![image](https://user-images.githubusercontent.com/28698352/158096503-5faabaf5-da63-496e-9304-e0ad1fdaf62f.png)
wen文档里这块内容没有吗，我看到官方示例里点击右下角弹出来是这样的：
![image](https://user-images.githubusercontent.com/28698352/158096572-5dfe1c2c-e186-4bc4-84d2-1a88505ba65c.png)

**Comment by alvarto** [comment]
@lulg 收到，我们近期因为升级 https 服务，现在跨域请求被 mixed content 规则拦截了。我这两天更新一下

此前可以通过此链接访问产品使用文档：https://www.yuque.com/lce/usage

**Comment by DiligentNezha** [comment]
我新增了一个表单容器，给表单容器里的按钮绑定事件，在事件里想获取到提交的表单数据，有没有案例呢？找了半天没找到，另外，能否再丰富一些后端相关的文档，比如为该低代码引擎开发后端应用，有没有什么规范或者最佳实践什么的

**Comment by Go7hic** [comment]
https://lowcode-engine.cn/doc?url=funcv8 组件低代码化这一块讲的不是很清楚(我觉得这个功能很重要，因为用你这个引擎的大都要结合内部自己的UI或业务组件来用的)，比如我现在有一套和 antd 类似的组件库，我是直接按照文档里说的步骤来操作吗？build-scripts 是什么东西呢，后面找了一下需要安装一个 "@alib/build-scripts"。还有如果我的组件库如果不是用 webpack 来开发的，这个还支持吗？
建议可以学一下next.js 那样弄一个 example 目录放你们写到的各种情况，这样就算文档没写清楚，起码还可以看代码。

**Comment by chenjinxinlove** [comment]
文档里面建议加一些组件之间如何配合的。比如表单筛选之后如果去执行table的请求。

**Comment by lijiaxu1996** [comment]
文档还是比较抽象，更多偏技术原理、但是如果想让这套低代码生态更好，还需要把一些通用业务场景提炼出来，另外，自定义的物料如何和setter配合、再如何和一些插件配合使用，这一块希望好好讲讲。
**最后说一句，其实新开源出来的问题真的很多，包括包的的问题，各种环境的问题，但也希望阿里低代码项目能够一直维护下去，因为我觉得这个项目挺有意义的，至少能在行业内设定标准，对于前端或者低代码讲是很有用的。**

**Comment by lpali** [comment]
我们团队都是用的vue技术栈，应该怎么使用这个引擎

**Comment by hzd822** [comment]
vue的看这个 https://github.com/alibaba/lowcode-engine/discussions/47

**Comment by LeoYuan** [comment]
> 我们团队都是用的vue技术栈，应该怎么使用这个引擎

见 https://github.com/alibaba/lowcode-engine/discussions/47，官方不会做这个，目前有其他团队正在做，有消息通知大家~

**Comment by atom-yang** [comment]
@LeoYuan 
代码仓库（数据源，扩展等仓库也是）里还存在大量的未替换的内网链接，例如存在很多这个域名https://yuque.antfin-inc.com下的文档链接
辛苦麻烦完成替换

**Comment by caoshaohua1025** [comment]
请问下  本地跑lowcode-demo之后，配置page之后，点击出码下载zip包，package.json中会出现"@alifd/fusion-ui": "1.0.24-21"配置,但是npm中根本没这个版本，改成最新bate版本也会存在引入组件报错问题

**Comment by xiemeilong** [comment]
出码的代码里RefsManager是干什么的，是可以去掉吗，给人一种会被lockin的感觉。

**Comment by LHongHui** [comment]
能否增加容器类自定义组件的开发示例

**Comment by icex** [comment]
Guys, I think a major roadblock for adoption is the language barrier. Google translate is ok for some parts, but images (flowcharts for example) can't be translated. The project has huge potential.

**Comment by alvarto** [comment]
> 能否增加容器类自定义组件的开发示例

https://www.yuque.com/lce/doc/epz1kk#RGwZ5

您好，物料配置详解里详细描述了对应功能，请查收～

**Comment by 286yym** [comment]
git下载的官方dome，没做任何修改，运行后提示：“编辑器初始化中....”，所有dome都打不开出码，和schema和源码面板等

**Comment by 286yym** [comment]
请问如何正确获取编辑器，就是，出码，schema，源码编辑中的js和css，变量绑定中的'绑定'等，涉及编辑器的，都是没办法运行，https://github.com/alibaba/lowcode-demo和https://github.com/alibaba/lowcode-code-generator-demo，这俩个都无法启动编辑器(可以正常拖拽，配置，但出码按钮无法出码，源码编辑无法编辑，schema面板无法查看，变量绑定无法编辑)，提示：“编辑器初始化中....”

**Comment by lijiaxu1996** [comment]
**强烈建议加一个重复性问题自动提醒定位回复关闭机器人，太多重复性问题以前的issues里面就有，也建议能够把一些重复性问题可以及时关闭的机器人，有时候问题都看不见了**

**Comment by LeoYuan** [comment]
> **强烈建议加一个重复性问题自动提醒定位回复关闭机器人，太多重复性问题以前的issues里面就有，也建议能够把一些重复性问题可以及时关闭的机器人，有时候问题都看不见了**

重复问题只能人工识别了。。。

另外，重复问题部分是因为大家不看文档和过往 issue，也可能文档没写清楚，前者希望各位大佬用引擎之前还是整体略读一遍文档，demo 代码，遇到问题再精读细节，后者我们识别到缺失或者写的不够清晰的地方，不断迭代打磨😃

**Comment by julytang** [comment]
文档建议分成两部分，一个是接入从0-1的。另一部分是适合已经做过低代码建设的团队如何使用低代码引擎重构先有技术架构的文档。比如说协议数据在引擎操作的流转，物料拖入时候的钩子添加自定义属性，然后是协议转换的专用层的最佳实践等等。我个人片面的认为还是有比较多的用户是希望用低代码引擎重构自己目前的低代码实现的，但是协议层的东西是跟后端绑定的，没有那么容易切换，比如奥创之类的。能不能提供一份从自有协议低搭建引擎实现迁移到低代码引擎的文档。这样对于低代码引擎的发展和收敛集团内低代码搭建技术栈都有好处。目前接入的文档对于我这样的用户很不友好，很多都是api的罗列，找api也是比较麻烦，没法很好的定位问题。

**Comment by sunnyguohua** [comment]
我理解获取数据是在数据源里定义，通过组件绑定实现的，这是数据入口；没搞懂在哪里定义数据/交互出口，简单地说就是在哪里可以提交http请求，如果要自己从头写js，太麻烦了；如果支持引入，在哪里引入？

**Comment by AtticusLv** [comment]
是否可以提供一些demo，诸如如何搭建一个需要用户登录、页面渲染数据前需要对用户登录鉴权这类的demo？

**Comment by codergray** [comment]
强烈建议完善1个典型的CRUD的example，目前的“如何制作表单页”还缺少条件搜索与表格的联动，分页与表格的联动、表单数据新增与表格联动；

**Comment by paiangit** [comment]
建议在Windows系统上跑一下项目流程，做好npm script的兼容处理。

目前发现Windows系统上跑不起来。比如 "setup": "./scripts/setup.sh"，package.json中这个命令运行报错，

> '.' 不是内部或外部命令，也不是可运行的程序

需要改成："setup": "bash ./scripts/setup.sh"

又如，

"start": "build-scripts start"

这里会报错误：

> 'build-scripts' 不是内部或外部命令

疑似@alib/build-scripts这个包在Windows下有问题，暂不清楚原因。

**Comment by LeoYuan** [comment]
建议先看下 readme～

目前我们只支持类 *nix 系统，win 上通过模拟终端，推荐 wsl 来兼容

**Comment by keminu** [comment]
请教一下，只支持react嘛？不能支持vue？

**Comment by LeoYuan** [comment]
> 请教一下，只支持react嘛？不能支持vue？

建议看下 discussion 以及其他 issue 中的描述

**Comment by GavinHome** [comment]
能不能出一个前后端的完整demo，现在demo只有客户端的设计器和渲染，期望完善后端存储和工作流结合的demo，如此可以完整体现一个表单从创建到审批到列表展示查询等具体场景，更利于新手入门，更加容易推广阿里低代码。

**Comment by LeoYuan** [comment]
鉴于目前很多建议都跟文档无关，所以此 issue 暂时关闭~

有 bug 相关的请直接提新的 issue，感谢😄
