### ISSUE TITLE
关于project下可以有多个documentModel，如何切换currentDocument的问题

### ISSUE THREAD

**Issue by meizilove258** [alibaba/lowcode-engine#485]
### project下有多个document，处于编辑状态的document为currentDocument。想问下如何切换currentDocument。我把api都查看了一下没有这样的方法。比如有fileName: 'page1'，和fileName: 'page2'的两个document，当前正在编辑page1，想切换到page2去编辑，如何切换。

**Comment by Dogtiti** [comment]
先remove page1 再open page2

**Comment by LeoYuan** [comment]
openDocument() 传入 fileName？

**Comment by mark-ck** [comment]
参考这个代码 https://github.com/mark-ck/lowcode-portal/blob/master/src/plugins/pages-plugin/index.tsx#L46

**Comment by meizilove258** [comment]
我看文档的时候，文档上是project下可有多个document。我原想是通过project来维护多个页面的，目前看所提供的api并不能达到project下维护多个页面的目的。没有一个toggleCurrentDocument的api。我看了上面的参考代码remove page1再open page2。我并不想删掉任何一个页面，我只是想toggleCurrentDocument。往project下添加了5个页面，每切换一下当前编辑页，还是先删除再open。open和create都是往project下面添加。这样删了添加，操作操作，就重复添加了。   

官方能回复下嘛，project的这个抽象，你们抽象时是想维护多个页面的嘛，从api上看不出来是。希望得到一个官方的答复。谢谢官方！！
