### ISSUE TITLE
建议出个演示Demo视频

### ISSUE THREAD

**Issue by keepal7** [alibaba/lowcode-engine#49]
rt

**Comment by alvarto** [comment]
您好，左下角的问号里面有产品使用文档，用大量动图描述了 demo 如何使用。目前受限于人力我们还没时间弄视频 host 的问题，敬请谅解～

**Comment by alvarto** [comment]
![image](https://user-images.githubusercontent.com/1797855/155949942-15badc56-e6e4-4a19-ae73-a824367cae4e.png)
