### ISSUE TITLE
关于节点的ID可变性

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#490]
我有个场景 需要创建的时候添加包裹组件，同时还要把这组件的id存在父组件的Props里面 ，但是我发现我这个写法会出现props.name和id不匹配

![image](https://user-images.githubusercontent.com/50658231/168260683-15f7183f-81ea-44e3-806e-4b9e6a739595.png)
![image](https://user-images.githubusercontent.com/50658231/168260798-d91c6671-075d-40f9-a7c9-26f998653b76.png)

**Comment by LeoYuan** [comment]
新创建的节点会在目前文档中所有节点中查询 id 是否重复，replaceWith 的实现是「先生成新节点，后删除旧节点」，所以会导致 id 变化了，两个思路：1. 更改 replaceWith 的实现；2. 调用更原子化的 API，比如先 remove，然后 insertAfter

**Comment by oneQiu** [comment]
> 新创建的节点会在当前中所有节点中查询 id 是否重复，替换为“先生成新节点，后删除旧节点”，所以会导致 id 变化，两个想法：1. 更改 replaceWith 的实现；2. 调用更原子化的API，比如先remove，然后insertAfter

但是我用了insertAfter以后发现好像只能自动添加在最后面，能否在光标处插入？
![image](https://user-images.githubusercontent.com/50658231/168507910-73f56674-83da-4e94-8f47-c7de8c0b9b29.png)

**Comment by oneQiu** [comment]
因为我节点是需要删除的，所以remove后 我不能在insertAfter插入第二个参数来保证位置

**Comment by LeoYuan** [comment]
insertAfter 带参数的呀~第一个待插入节点，第二个就是插入在谁之后，另外节点删除之前记录一下位置，可以找到 prevSibling 或者记录下 index 等

**Comment by oneQiu** [comment]
> insertAfter 带参数的呀~第一个待插入节点，第二个就是插入在谁之后，另外节点删除之前记录一下位置，可以找到 prevSibling 或者记录下 index 等

是这样操作的，inserAfter(schema, added)  。。但是前面已经remove(added)了，所以插不进去指定位置。。
后面说的index是可以作为参数的吗
