### ISSUE TITLE
有没有计划支持formily表单场景的那些特性

### ISSUE THREAD

**Issue by chenfeiwu** [alibaba/lowcode-engine#492]
要是二合一真的太完美了，我现在正在为这两个选型而发愁

**Comment by LeoYuan** [comment]
官方应该暂时不会做，之前有位小伙伴咨询过技术方案，我给出了以下建议，即：包装一个表单组件，接收来自外部的属性配置，属性配置内容为 formily 定义的表单项协议，组件内部调用 formily 的表单渲染能力完成渲染~

**Comment by icecxh** [comment]
我们已经把formily的表单接入lowcode，目前正在进行一些场景验证中，验证完毕后会进行开源。

**Comment by LeoYuan** [comment]
> 我们已经把formily的表单接入lowcode，目前正在进行一些场景验证中，验证完毕后会进行开源。

@icecxh 
相当赞，期待🎉🎉🎉

**Comment by Dogtiti** [comment]
> 我们已经把formily的表单接入lowcode，目前正在进行一些场景验证中，验证完毕后会进行开源。

赞

**Comment by luohe** [comment]
> 我们已经把formily的表单接入lowcode，目前正在进行一些场景验证中，验证完毕后会进行开源。

太期待了🎉🎉🎉

**Comment by Immanding** [comment]
https://github.com/seada-low-code/lowcode-ecology/tree/main/packages/formily-materials

**Comment by Immanding** [comment]
formily 物料[@seada/formily-materials](https://github.com/seada-low-code/lowcode-ecology/tree/main/packages/formily-materials)，目前已经支持了多个项目的表单场景，如果有问题可以提issue或mr
