### ISSUE TITLE
预览  出现 Slot component is not found in components list! component list is: 错误

### ISSUE THREAD

**Issue by 15163789836** [alibaba/lowcode-engine#494]
## **Describe the bug (required)** / **详细描述 bug（必填）**
直接预览  出现 Slot component is not found in components list! component list is:
A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
 预览 页面 Slot component is not found in components list! component list is:  出现很多条  几千条吧  页面非常卡顿
---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
预览页面

Steps to reproduce the behavior: / 详细复现步骤：
![image](https://user-images.githubusercontent.com/104408070/168708496-558d7f47-a29e-4c07-ade0-ef2cb1d2b646.png)

在页面任何操作点击 也会  导致Slot component is not found in components list! component list is:   报错

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为
正常 预览页面
---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
![image](https://user-images.githubusercontent.com/104408070/168708620-588ae835-8f80-4b14-b4bf-eb1f2c3cdf18.png)
![image](https://user-images.githubusercontent.com/104408070/168708648-526d937f-eb4c-4dab-b1f9-29ea0da66607.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by JackLian** [comment]
https://github.com/seajs/seajs/issues/545
参考这里面的建议，补充完整必要信息，如何复现，是否有复现环境或者demo等

**Comment by hmz5** [comment]
我也遇到了

**Comment by hmz5** [comment]
已找到问题：
project.exportSchema(),
project.exportSchema(TransformStage.Save)
针对slot的导出schema不一致

project.exportSchema() 导出案例 - 渲染slot异常
![image](https://user-images.githubusercontent.com/16495308/169678153-7301c570-7a19-442f-94ea-290c67226d0c.png)

project.exportSchema(TransformStage.Save) 导出案例 - 渲染正常
![image](https://user-images.githubusercontent.com/16495308/169678176-44398437-edff-448e-af45-3374dc5621c7.png)

如上为官方最新demo实验结果，修改src/universal/utils 中 setProjectSchemaToLocalStorage方法中导出exportSchema参数

具体原因还未知。

**Comment by hmz5** [comment]
补充渲染结果
![image](https://user-images.githubusercontent.com/16495308/169678371-54eb0b6b-55f6-4d9c-9a83-d69b97312538.png)

**Comment by hmz5** [comment]
@JackLian

**Comment by hmz5** [comment]
看了源码project的修改记录，应该是有修改过exportSchema的默认值吧。
