### ISSUE TITLE
Page 组件可否支持属性配置（样式 + 事件）

### ISSUE THREAD

**Issue by twinkle77** [alibaba/lowcode-engine#497]
## **Describe the bug (required)** / **详细描述 bug（必填）**
Page 组件支持属性配置（样式 + 事件）

![image](https://user-images.githubusercontent.com/17792166/168718884-cf52a75a-fa05-4f6d-b2bf-1eb1eae13d7b.png)

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1.  打开 https://lowcode-engine.cn/demo/basic-antd.html
2.  切换到 “基础 antd 组件” 模式
3.  选择大纲树，可以看到 Page 组件无法配置样式或者事件

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

当前阶段希望能配置样式，就无需再拖入一个容器了

**Comment by mark-ck** [comment]
可以通过 metadataTransducer 给 page 补充 meta 配置，参考这里：
- 文档: https://lowcode-engine.cn/docV2/mu7lml#LRXhp
- 视频: https://www.bilibili.com/video/BV1j3411P749/

**Comment by zdgzdgzdg** [comment]
> metadataTransducer
文档链接过期了能重新给个么

**Comment by jinchanz** [comment]
> > metadataTransducer
> > 文档链接过期了能重新给个么

https://lowcode-engine.cn/site/docs/api/material#%E7%89%A9%E6%96%99%E5%85%83%E6%95%B0%E6%8D%AE%E7%AE%A1%E9%81%93%E5%87%BD%E6%95%B0

应该是这个
