### ISSUE TITLE
需要提供统一变量配置的地方和获取的方法

### ISSUE THREAD

**Issue by ZhangPeiHan** [alibaba/lowcode-engine#498]
![image](https://user-images.githubusercontent.com/40198635/168722085-7c731cb5-d7ba-4a11-b9e8-dff1dac8dd60.png)

**Comment by twinkle77** [comment]
最好有个全局代码块的面板
有 global constanst 跟 global utils

**Comment by liujuping** [comment]
由于这个依赖数据库，所以在引擎层面不提供支持。

假设我们有十几个页面，在 schema 中存储全局变量，在其中一个页面中进行编辑的时候没有办法修改其他页面的 schema，会导致全局变量配置不统一的情况。

这种场景建议自己扩展一下，比如说，增加一个全局变量的插件，按照应用纬度进行存储。当页面加载的时候，挂在 window 对象或者其他地方。这样来达到效果。
