### ISSUE TITLE
切换 setter 时，setter 获得的 value 值为 undefined，如何在 setter 切换时获取物料当前的 value

### ISSUE THREAD

**Issue by haoziqaq** [alibaba/lowcode-engine#499]
切换 setter 时，setter 获得的 value 值为 undefined，如何在 setter 切换时获取物料当前的 value

**Comment by haoziqaq** [comment]
我希望在切换 setter 时，保持物料当前的值，而不是清空当前的值，我应该怎么做呢？

**Comment by JackLian** [comment]
切换setter指的是什么场景，麻烦补充下信息

**Comment by haoziqaq** [comment]
我通过对ArraySetter进行封装暂时解决了我的场景问题。
