### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by chengjunjian2020** [alibaba/lowcode-engine#5]
我通过http方式将代码拉下来后
首先 npm install成功了
然后在执行npm run setup报错了
这是以下报错
![image](https://user-images.githubusercontent.com/40468022/154263736-bd1a9c7e-c5da-4fcf-8050-c24391a10a57.png)
而后我通过排查到日志是这样的
![image](https://user-images.githubusercontent.com/40468022/154263861-6940c345-ac3e-492e-8514-d373d5c4b6c6.png)
我不太熟悉sh脚本
![image](https://user-images.githubusercontent.com/40468022/154263954-df3ec447-549e-4fdf-aba9-280c92e36642.png)
l 我仔细看了下自己还是无法解决，通过百度都尝试过了

**Comment by LeoYuan** [comment]
要不试试 windows 下其他终端，比如 [WSL](https://docs.microsoft.com/en-us/windows/wsl/install)？

ps: 跑不起来应该是 shell 运行环境问题
pps：run start:demo 暂时是跑不起来的，我们有另外一个项目做 [demo](https://github.com/alibaba/lowcode-demo)，不过还没发布。。。

**Comment by eternalsky** [comment]
WSL 中文 doc：https://docs.microsoft.com/zh-cn/windows/wsl/install
中文教程：https://blog.csdn.net/weixin_45027467/article/details/106862520

**Comment by h7ml** [comment]
能不能优化下启动命令？

**Comment by chengjunjian2020** [comment]
> 要不试试 windows 下其他终端，比如 [WSL](https://docs.microsoft.com/en-us/windows/wsl/install)？
> 
> ps: 跑不起来应该是 shell 运行环境问题 pps：run start:demo 暂时是跑不起来的，我们有另外一个项目做 [demo](https://github.com/alibaba/lowcode-demo)，不过还没发布。。。

下载太慢呢，有其他方式么，下载到最后一直不走了

**Comment by LeoYuan** [comment]
> > 要不试试 windows 下其他终端，比如 [WSL](https://docs.microsoft.com/en-us/windows/wsl/install)？
> 
> > 
> 
> > ps: 跑不起来应该是 shell 运行环境问题 pps：run start:demo 暂时是跑不起来的，我们有另外一个项目做 [demo](https://github.com/alibaba/lowcode-demo)，不过还没发布。。。
> 
> 
> 
> 下载太慢呢，有其他方式么，下载到最后一直不走了

cnpm 或者 vpn 或者用国内某个镜像源

**Comment by fengruiabc** [comment]
@LeoYuan 请问下，有正式release的预期时间吗，想体验下，3q3q

**Comment by Blizzard-liu** [comment]
解决了吗  在windows上怎么跑

**Comment by Blizzard-liu** [comment]
解决了吗  在windows上怎么跑
