### ISSUE TITLE
npm init @alilc/element your-element-name 命令失效

### ISSUE THREAD

**Issue by xxholly32** [alibaba/lowcode-engine#50]
`npm init @alilc/element your-element-name` 报错 ，npm版本 7.x

`npx @alilc/create-element your-element-name` 可以成功

**Comment by eternalsky** [comment]
请帖一下 npm init 出错的信息。另 npm init 和 npx 应该是等价的，不太可能出现一个成功，一个失败的情况

**Comment by xxholly32** [comment]
my bad
