### ISSUE TITLE
setter 不支持 hooks 写法

### ISSUE THREAD

**Issue by haloworld007** [alibaba/lowcode-engine#507]
## **Describe the bug (required)** / **详细描述 bug（必填）**
setter 使用 hooks 写法报错

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
1. clone lowcode-demo
2. `src/universal/plugin.tsx` 中将 setterMap 中的 StringSetter 替换为 CustomSetter
<img width="726" alt="image" src="https://user-images.githubusercontent.com/8730698/168951742-f629e6a4-e0d4-45f0-be8d-3d1d42422d27.png">
3. CustomSetter写法如下： 
<img width="728" alt="image" src="https://user-images.githubusercontent.com/8730698/168951837-f165f217-f695-41f7-a13b-5f1c453e3a07.png">

4. 启动项目`yarn start`

5. 拖拽一个按钮到画布，报错 
 
<img width="1238" alt="image" src="https://user-images.githubusercontent.com/8730698/168951962-14f6a52e-eeeb-4bfd-87d4-203f14b2e736.png">

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为
---
预期是能正常渲染 setter，如果上述 CustomSetter 删除 `useState` 代码是能正常渲染的。

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: 1.0.8
 - AliLowCodeEngineExt version: 1.0.3
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by haloworld007** [comment]
<img width="709" alt="image" src="https://user-images.githubusercontent.com/8730698/168987716-e077c60d-30ff-4283-afdd-f29cbf7ec1cc.png">

看样子是这句代码造成的 @LeoYuan 能帮忙看下吗

**Comment by haloworld007** [comment]
https://github.com/alibaba/lowcode-engine/pull/513 fixed

**Comment by wenccro** [comment]
报错321，是react引用重复了，你在setter里面排包react就行
