### ISSUE TITLE
启动@alilc/element工程报错

### ISSUE THREAD

**Issue by dj49846917** [alibaba/lowcode-engine#508]
node版本： v14.18.1

在使用使用npm init @alilc/element your-element-name，新建这个工程时，npm install之后，执行npm run lowcode:dev报如下错误：

ERR! (undefined) ./.tmp/meta.js
eact-complowcodecolorful-buttonmeta' in 'C:\Users\jackdu\Documents\test\react-comp\.tmp'
ERR!
ERR! (undefined) ./.tmp/meta.js
eact-complowcodecolorful-inputmeta' in 'C:\Users\jackdu\Documents\test\react-comp\.tmp'
ERR!
ERR! (undefined) ./.tmp/default.view.js
eact-compsrcindex.scss' in 'C:\Users\jackdu\Documents\test\react-comp\.tmp'
ERR!
ERR! (undefined) ./.tmp/view.js
eact-compsrcindex.scss' in 'C:\Users\jackdu\Documents\test\react-comp\.tmp'
ERR!
ERR! (undefined) ./.tmp/default.view.js
eact-compsrcindex.tsx' in 'C:\Users\jackdu\Documents\test\react-comp\.tmp'
ERR!
ERR! (undefined) ./.tmp/view.js
eact-compsrcindex.tsx' in 'C:\Users\jackdu\Documents\test\react-comp\.tmp'
Error from chokidar (C:\): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'
Error from chokidar (C:\node_modules): Error: EBUSY: resource busy or locked, lstat 'C:\DumpStack.log.tmp'

**Comment by LeoYuan** [comment]
看一下 readme 里写的如何在 windows 上运行~

**Comment by CL008** [comment]
这个问题是怎么解决的

**Comment by HermanL02** [comment]
> wsl
