### ISSUE TITLE
碰到几个问题

### ISSUE THREAD

**Issue by winterZhao** [alibaba/lowcode-engine#51]
1. readme里写的git clone地址，建议换成https的，否则git的是没权限的。
2. 把整个项目clone到本地，以开发方式安装运行，没有报错，但是成了这个样子。
` Starting the development server at:
   - Local  :  http://localhost:3333/
   - Network:  http://xxx.xxx.xxx.xx:3333/，
`
然后浏览器输入对应的url打开宛如nginx打开目录，全是一个个文件夹或者文件。  根本没有启动项目的样子。原谅我没有截图，没有找到上传图片的地方。
3. 运行了在线demo. 发现画布上的元素无法移动。 更别说复制出来的元素进行移动了。
4.  感觉需要出个使用手册。  就是你们的产品让一个新手或者非技术人员使用，他需要注意什么，当然二开文档也是需要的。
5.  在画布上编辑完以后点击保存到本地，是存到localStorage了吗？还是存成文件了呢。 感觉保存的操作感不强，不知道保存到哪里了。有点害怕自己劳动了半天的劳动成果就没有了。
6. 感觉需要像processon那样引入项目的概念。我同时进行两个编辑怎么办呢。
7. 预览很糟糕，或者可能我使用的方式不对，画布上显示的和预览的完全不一样。画布上看着像个半成品，预览出来效果就是乱码。。
8. 是否有类似批量应用样式的效果呢。两行3列的效果。我使用了6个文本。然后一个一个修改样式。这样的低代码应用样式，感觉还不如手写
9. select少了一种默认展开options的配置项，可能是setters里应该加个参数
10. 事件还不太会用。我想实现点击一个按钮让弹窗出现，还不得要领。
11. 导入导出问题，能否类似draw.io那样，不止导出js和css，还能导出一个类似原型的，然后方便后续分享给别人在同样的系统里实现导入，已达到团队协作的目的
12. 一个遮罩我配置了隐藏，我如何在画布中重新找到它呢
13. demo里导出zip解压缩后的package.json里有`"@alifd/next": "{{version}}",`  alifd/fusion-ui@0.1.6-beta.24 npm里没有这个版本

我最满意的一个点
1. 可以自定义画布宽度。

最后问一句，25个issues怎么就能搞到1k star的，有点意外。。

**Comment by winterZhao** [comment]
感觉更希望ams，tms之类的成熟产品开源

**Comment by alvarto** [comment]
感觉需要出个使用手册。 就是你们的产品让一个新手或者非技术人员使用，他需要注意什么，当然二开文档也是需要的。

Demo 左下角有：

![image](https://user-images.githubusercontent.com/1797855/155957357-4b4af161-80ef-46b6-94fb-3870a995647a.png)

**Comment by alvarto** [comment]
8. 可以使用源码面板里的 CSS 样式，然后你在样式里面设置 className 即可

**Comment by winterZhao** [comment]
你图片怎么来的呢。

**Comment by alvarto** [comment]
我从官网 demo 的界面点出来的

**Comment by winterZhao** [comment]
> 我从官网 demo 的界面点出来的

请问一下易搭这个平台的使用者定位是什么样的人呢。

**Comment by LeoYuan** [comment]
> * readme里写的git clone地址，建议换成https的，否则git的是没权限的。
> * 把整个项目clone到本地，以开发方式安装运行，没有报错，但是成了这个样子。
>   ` Starting the development server at:
>   
>   * Local  :  http://localhost:3333/
>   * Network:  [http://xxx.xxx.xxx.xx:3333/，](http://xxx.xxx.xxx.xx:3333/%EF%BC%8C)
>     `
>     然后浏览器输入对应的url打开宛如nginx打开目录，全是一个个文件夹或者文件。  根本没有启动项目的样子。原谅我没有截图，没有找到上传图片的地方。
> * 运行了在线demo. 发现画布上的元素无法移动。 更别说复制出来的元素进行移动了。
> * 感觉需要出个使用手册。  就是你们的产品让一个新手或者非技术人员使用，他需要注意什么，当然二开文档也是需要的。
> * 在画布上编辑完以后点击保存到本地，是存到localStorage了吗？还是存成文件了呢。 感觉保存的操作感不强，不知道保存到哪里了。

1. 正常 github 操作，https / git 两种都可以选择，了解下 ssh key；
2. 引擎主包定位是启动几个资源文件的编译，因为缺少物料、setter、插件等，所以就算能预览意义也不大，所以我们才弄了 demo 这个项目整合了引擎内核、物料、setter、插件等；
3. 无法复现，建议单独提个 issue；
4. 好，文档会持续优化
5. 保存到 localStorage 只是为了演示效果，真实场景你应该保存到后端服务去；
6. 引擎不提供项目等概念，同理，研发流程、打包部署、监控 等都不会包含；
7. 隐藏的组件在大纲树可以找到；
8. demo 导出的问题建议单独提个 issue；
