### ISSUE TITLE
如何获取状态，例如TransformStage，我想知道当前是否处于编辑态，还是渲染态

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#510]
如题，想知道当前是处于哪个状态，除了自己往window挂以及url参数以外，引擎有自带的方法或者属性吗？

**Comment by oneQiu** [comment]
PS：在物料库内，我想编辑态的时候不允许某些操作

**Comment by LeoYuan** [comment]
简单场景（改动量不大）可以利用 props.__designMode：
![image](https://user-images.githubusercontent.com/1195765/169192152-398495c8-fa5b-449f-8f29-e6ee80b5932b.png)

复杂场景（改动量大）在资产包里定义 editUrls：
![image](https://user-images.githubusercontent.com/1195765/169192259-3f96c84e-231a-4fcb-aa6c-f104c7fe9972.png)

**Comment by oneQiu** [comment]
> 简单场景（改动量不大）可以利用 props.__designMode： ![image](https://user-images.githubusercontent.com/1195765/169192152-398495c8-fa5b-449f-8f29-e6ee80b5932b.png)
> 
> 复杂场景（改动量大）在资产包里定义 editUrls： ![image](https://user-images.githubusercontent.com/1195765/169192259-3f96c84e-231a-4fcb-aa6c-f104c7fe9972.png)

好的，简单场景这个Props已经可以满足业务了。

另外目前物料的组件之间通信有推荐方案吗？两个组件之前的一些数据交流

**Comment by wtt24** [comment]
editUrls生成逻辑在哪，有文档介绍吗？

**Comment by liujuping** [comment]
> editUrls生成逻辑在哪，有文档介绍吗？

可以看一下这个，相当于写一个在设计态中使用的组件，写的逻辑和正常写组件一样，https://www.yuque.com/lce/doc/xgrv61#dIzCd
