### ISSUE TITLE
建了一个微信群欢迎大家进群交流 

### ISSUE THREAD

**Issue by shitoudada** [alibaba/lowcode-engine#521]
建了一个微信群欢迎大家进群交流
![157180826-b0f994c0-8a6b-4946-a521-763d81c93c4a](https://user-images.githubusercontent.com/10807769/169564032-de232b6c-a09b-4ae4-9986-3ecac62465c0.jpeg)

**Comment by LeoYuan** [comment]
https://lowcode-engine.cn/

首页已经有微信和钉钉群二维码，这是要干嘛？

**Comment by shitoudada** [comment]
> https://lowcode-engine.cn/
> 
> 首页已经有微信和钉钉群二维码，这是要干嘛？

不好意思，去官网找了半天，还是没有找到微信群

**Comment by LeoYuan** [comment]
就在最下面～

**Comment by blueju** [comment]
@shitoudada 
在右下角的“关注我们”那。
![lowcode-engine cn_ (2)](https://user-images.githubusercontent.com/49681036/169789315-63900625-51ca-482b-940a-44d7925bc97c.png)

**Comment by yutianmr** [comment]
群都失效了 倒是更新一下二维码啊
