### ISSUE TITLE
设置器如何增加一个tab页面

### ISSUE THREAD

**Issue by chaochao666** [alibaba/lowcode-engine#525]
## **Describe the bug (required)** / **详细描述 bug（必填）**
想请教两个问题，看了文档没太明白。
1.设置器如何增加一个自定义的tab页面
2.设置器如何控制默认tab页面的显示与否
![31523B3D-3B2C-4704-B8A0-69F74F727550](https://user-images.githubusercontent.com/39239903/169680461-a849806e-1342-4dfd-a406-61e160cda36c.jpeg)

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by hzd822** [comment]
1.目前设置器暂未支持新增一个tab
2.默认是第一个tab，props属性可以通过分组等方式来归类一些属性

**Comment by chaochao666** [comment]
> 1.目前设置器暂未支持新增一个tab
> 2.默认是第一个tab，props属性可以通过分组等方式来归类一些属性

那麻烦请教您下，宜搭设计器的这个数据tab是如何实现的呢？我这边需要开发一个类似的功能
![Uploading B9D36D6F-BAFF-479E-BEA5-A5F7F4647714.jpeg…]()

**Comment by chaochao666** [comment]
![Uploading E260A0FA-FF4E-4648-B42D-EC6EB1E37ED2.jpeg…]()

**Comment by chaochao666** [comment]
![Uploading E4687525-B81C-43F0-B1D9-066118273BAE.jpeg…]()

**Comment by ImSwordTooth** [comment]
我按照官网的[https://lowcode-engine.cn/docV2/mu7lml#LRXhp](https://lowcode-engine.cn/docV2/mu7lml#LRXhp)倒是实现了一下，只是这个tab是全组件通用的，如何设置显隐还没有尝试，不知道支不支持
![image](https://user-images.githubusercontent.com/43266605/169729535-f7476ffa-d938-482c-8729-71686f2839ee.png)

**Comment by LeoYuan** [comment]
支持的，因为设置面板是根据 metadata 的数据结构来渲染的，而每个组件的 metadata 都是独立的~

比如说：
```ts
registerMetadataTransducer((metadata: TransformedComponentMetadata) => {
  if (metadata.componentName === 'YourComponent') {
    // do something
    metadata.configure.combined.push({
      name: '#custom',
      title: { type: 'i18n', 'zh-CN': 'YourComponentTab', 'en-US': 'YourComponentTab' },
      items:[],
    });
  }
  // 其他的不处理
  return metadata;
});
```
