### ISSUE TITLE
开源版本可以加这些功能吗

### ISSUE THREAD

**Issue by chenfeiwu** [alibaba/lowcode-engine#526]
这个版本好用很多呢
![image](https://user-images.githubusercontent.com/14910761/169689103-85664dc9-4afb-42f9-93dd-2a141285a236.png)

**Comment by liujuping** [comment]
这个是公司内部的产品，相关的功能没有开源计划

**Comment by LeoYuan** [comment]
图中截图已经是个低代码平台了，使用了很多自定义插件来扩展能力，很多插件跟后端服务有关（比如区块、低代码组件能力等）不适合开源~

**Comment by chenfeiwu** [comment]
> 图中截图已经是个低代码平台了，使用了很多自定义插件来扩展能力，很多插件跟后端服务有关（比如区块、低代码组件能力等）不适合开源~

有没有相关体系设计思想的文档博客可以参考呀
