### ISSUE TITLE
antd 组件 穿梭框  选取了再取消到最后一个 为什么取消不掉  

### ISSUE THREAD

**Issue by 15163789836** [alibaba/lowcode-engine#529]
## 复现截图
![image](https://user-images.githubusercontent.com/104408070/169728342-544e866b-7877-4396-b5a8-c04e80944f11.png)

## 复现流程与链接
穿梭框  取消到最后一个 为什么取消不掉  

## 期望结果

可以全部选取  也可以全部取消，不会剩下一个取消不掉

## 环境信息

-引擎版本 1.0.3-beta.0
- ext 版本 1.0.3
- 物料
  - moment﹫2.24.0
  - lodash
  - iconfont-icons
  - ﹫ant-design/icons﹫4.7.0
  - antd﹫4.19.5
  - ﹫alifd/next﹫1.23.0
  - ﹫alilc/lowcode-materials﹫1.0.3

**Comment by LeoYuan** [comment]
> 引擎版本 1.0.3-beta.0

好奇，你们怎么用到这个版本的？是某次 git clone 后就不再 git pull 了么？😭
