### ISSUE TITLE
如何主动触发表单验证

### ISSUE THREAD

**Issue by haoziqaq** [alibaba/lowcode-engine#530]
我该如何获取到表单容器的实例，从而可以调用组件的方法

**Comment by haoziqaq** [comment]
似乎在 https://github.com/alibaba/lowcode-materials/commit/fe15e82029b3725a8bf0d2c7d754bca1a3f25d76 这个提交中加入了 ref 属性，但是我看 antd 的物料已经很久没有发过版本了，物料包大概是多久 release 一次呢？

**Comment by haoziqaq** [comment]
@twinkle77

**Comment by Dogtiti** [comment]
@haoziqaq  已经有插件了 自己注册到antd场景里，目前demo只注册了通用场景 https://github.com/alibaba/lowcode-demo/pull/26#issue-1232817146

**Comment by haoziqaq** [comment]
好的 感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年5月23日(周一) 晚上10:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/lowcode-engine] 如何主动触发表单验证 (Issue #530)




 
@haoziqaq  已经有插件了 自己注册到antd场景里，目前demo只注册了通用场景 alibaba/lowcode-demo#26 (comment)
