### ISSUE TITLE
Antd物料, Input无法选中，必须通过大纲树选中，并且输入无效

### ISSUE THREAD

**Issue by haoziqaq** [alibaba/lowcode-engine#531]
![image](https://user-images.githubusercontent.com/24223652/169746519-2943cddc-5263-4992-97d6-27eea9e7747a.png)

**Comment by haoziqaq** [comment]
似乎是默认max-length为0导致的，可能的话官方可以考虑修改一下默认值，包括边框，我认为应该是默认拥有边框的

**Comment by eightHundreds** [comment]
这问题没解决, 应该不要关吧

**Comment by liujuping** [comment]
无法选中的问题是因为 Antd 的 Input 物料的 ref 逻辑，需要进一步的进行适配。稍后我会看看。

**Comment by Shirley1006** [comment]
> 无法选中的问题是因为 Antd 的 Input 物料的 ref 逻辑，需要进一步的进行适配。稍后我会看看。
这个问题有修复吗？是哪个版本呢？
