### ISSUE TITLE
数据源面板加载后首次打开面板为空

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#533]
复现步骤
1. 创建数据源
![image](https://user-images.githubusercontent.com/50658231/169773971-317106fd-756c-43ce-861d-46a7ef649768.png)

2. 保存
3. 重新进入页面，拉取Schema，打开数据源面板，会发现没有数据源
![image](https://user-images.githubusercontent.com/50658231/169774248-c7e3d0f4-73fd-465e-8cd2-57ddcec82926.png)
4. 切换到其他的面板，比如组件库面板，再点回去，才会显示数据源，从保存的Schema里看是存在相关的信息

官方的Demo也能复现

**Comment by oneQiu** [comment]
Q2：导出会出现面板渲染失败
![image](https://user-images.githubusercontent.com/50658231/169934533-c370bc4d-1584-49e3-867b-50faccfc7a80.png)

**Comment by oneQiu** [comment]
这个问题能解决吗。

**Comment by twinkle77** [comment]
q1 q2 都 done 了  @oneQiu
