### ISSUE TITLE
物料扩展，A组件如何主动添加B组件？

### ISSUE THREAD

**Issue by 1377023219** [alibaba/lowcode-engine#534]
你们好，问题是这样的

目前想实现一个表单，可通过拖拽，增加表单组件，已实现如下，可自由增加表单功能：
![微信截图_20220523171919](https://user-images.githubusercontent.com/36667646/169791044-5282bea4-1c2a-4172-a609-49aaaffb4b82.png)
![image](https://user-images.githubusercontent.com/36667646/169791294-7ddfdbd7-9989-4e45-abcd-caa458e0146e.png)

但是由于<Form.Item>也有要可自由定义的功能，所以也把<Form.Item>注册为物料。

那么请问如何实现，当在< Form>拖入< Input>物料时，主动添加<Form.Item>物料，处于< Form><Form.Item>< Input>的层级关系。
有什么方法实现么？

**Comment by Dogtiti** [comment]
https://github.com/alibaba/lowcode-materials/blob/41d24a67d4671fcc7ae8088560167b998d4130d1/packages/fusion-lowcode-materials/lowcode/form/meta.ts#L395
