### ISSUE TITLE
撤销、模拟器插件支持位置修改吗？

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#535]
像撤销和模拟器的插件，都是npm包使用的，然后直接register注册，有暴露方法让我自定义位置吗？我想都放在工具栏里
![image](https://user-images.githubusercontent.com/50658231/169791767-f48541dc-44c0-4899-b7b1-5325488bb9b7.png)

**Comment by liujuping** [comment]
目前没有暴露方法，可以 fork 仓库代码改一下，发一个自己的 npm 包。

代码：https://github.com/alibaba/lowcode-plugins

**Comment by LeoYuan** [comment]
或者把 https://github.com/alibaba/lowcode-plugins/blob/d047edef955aaa0627a305c31ccdc8f84de30264/packages/plugin-undo-redo/src/index.tsx#L17 导出来，在你的应用里注册一个插件，skeleton.add 一下~
