### ISSUE TITLE
表单容器提交与重置按钮消失bug

### ISSUE THREAD

**Issue by qqcyuan** [alibaba/lowcode-engine#537]
![image](https://user-images.githubusercontent.com/58452046/169967196-b0218091-449e-438f-a793-b9e790ec0fd4.png)
点击一下这两个按钮就消失了

**Comment by Dogtiti** [comment]
![image](https://user-images.githubusercontent.com/38354472/170292010-d4b52728-a75a-40bc-9b09-542dfa9d2f5f.png)
选择到`button`时，`setter`就已经设置了`ghost`属性为`true`,这不算是bug，把`ghost`对应`setter`的默认值改一下就好了
