### ISSUE TITLE
antd ProTable 低代码物料ref配置问题

### ISSUE THREAD

**Issue by guangshene** [alibaba/lowcode-engine#539]
## **antd ProTable 低代码物料ref配置问题**

proTable组件有两个ref，actionRef和formRef，在meta文件里，应该如何配置这两个属性呢。

proTable连接 https://procomponents.ant.design/components/table/#protable

**Comment by liujuping** [comment]
1.同一个低代码组件不支持配置多个 ref
2.ref 的名字只支持 'ref'
