### ISSUE TITLE
原生input 无法输入

### ISSUE THREAD

**Issue by panda0000009** [alibaba/lowcode-engine#540]
![image](https://user-images.githubusercontent.com/49061144/169987835-18fa1967-7065-46b6-8358-689b12cb6f4f.png)
没有聚焦框，也不能输入

示例代码：
<form action="demo-form.php">
First name: <input type="text" name="FirstName" value="Mickey"><br>
Last name: <input type="text" name="LastName" value="Mouse"><br>
<input type="submit" value="提交">
</form>

**Comment by panda0000009** [comment]
实例代码：
`<form action="demo-form.php">
First name: <input type="text" name="FirstName" value="Mickey"><br>
Last name: <input type="text" name="LastName" value="Mouse"><br>
<input type="submit" value="提交">
</form>`

**Comment by panda0000009** [comment]
![image](https://user-images.githubusercontent.com/49061144/169988584-e5815f5f-3120-473f-a990-52c159aaac1d.png)

**Comment by LeoYuan** [comment]
为什么要能输入？设计态的渲染更多是看编排出来的效果，要真实测试比如联动之类的逻辑，还是去预览页吧~

**Comment by panda0000009** [comment]
预览页也输入不了，大佬。

**Comment by LeoYuan** [comment]
预览输入不了那跟引擎有啥关系。。。
