### ISSUE TITLE
Dialog组件不显示

### ISSUE THREAD

**Issue by NicholasJupiter** [alibaba/lowcode-engine#546]
## 复现截图
![Uploading image.png…]()

## 环境信息

- 引擎版本 1.0.8
- ext 版本 1.0.3
- 物料
  - moment﹫2.24.0
  - lodash
  - ﹫alifd/next﹫1.24.18
  - NextTable﹫1.0.1
  - ﹫alilc/lowcode-materials﹫1.0.2
  - ﹫alifd/pro-layout﹫1.0.1-beta.6
  - ﹫alifd/fusion-ui﹫1.0.5

**Comment by liujuping** [comment]
Duplicate of https://github.com/alibaba/lowcode-engine/issues/446

**Comment by liujuping** [comment]
其他问题的话需要补充更多的信息。
