### ISSUE TITLE
使用Ant Design Charts组件时时会出现 设计器出现错误，预览却没问题

### ISSUE THREAD

**Issue by baiheinet** [alibaba/lowcode-engine#547]
## **Describe the bug (required)** / **详细描述 bug（必填）**

使用Ant Design Charts组件时时会出现 设计器出现错误，预览却没问题

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
assets.json的components 增加一下组件

`{
      "componentId": "01hkmly0p5o60",
      "devMode": "proCode",
      "npm": {
        "package": "@ant-design/plots",
        "version": "1.0.9",
        "exportName": "Area",
        "subName": "",
        "main": "lib/index.js",
        "destructuring": true
      },
      "className": "page_l3cbyypn",
      "componentName": "Area",
      "screenshot": "https://gw.alipayobjects.com/zos/antfincdn/ld0NQtdLO0/mianjitugengxinshuju-after.gif",
      "title": "面积图",
      "category": "图表",
      "group": "精选组件",
      "configure": {
        "props": [
          {
            "type": "group",
            "title": "数据",
            "items": [                   
              {
                "important": false,
                "type": "field",
                "title": "x轴字段名",
                "name": "xField",
                "setter": "StringSetter",
                "extraProps": {
                  "display": "inline"
                }
              },
              {
                "important": false,
                "type": "field",
                "title": "y轴字段名",
                "name": "yField",
                "setter": "StringSetter",
                "extraProps": {
                  "display": "inline"
                }
              }
            ],
            "extraProps": {
              "display": "accordion",
              "defaultCollapsed": false
            }
          }
        ],
        "component": {
          "isContainer": false,
          "isModal": false
        },
        "supports": {
          "style": false
        }
      },
      "experimental": {
        "callbacks": {}
      },
      "snippets": [
        {
          "title": "面积图",
          "screenshot": "https://gw.alipayobjects.com/zos/antfincdn/ld0NQtdLO0/mianjitugengxinshuju-after.gif",
          "schema": {
            "componentName": "Area",
            "props": {
              "data": [
                {
                  "timePeriod": "2006 Q3",
                  "value": 1
                },
                {
                  "timePeriod": "2006 Q4",
                  "value": 1.08
                },
                {
                  "timePeriod": "2007 Q1",
                  "value": 1.17
                },
                {
                  "timePeriod": "2007 Q2",
                  "value": 1.26
                },
                {
                  "timePeriod": "2007 Q3",
                  "value": 1.34
                },
                {
                  "timePeriod": "2007 Q4",
                  "value": 1.41
                },
                {
                  "timePeriod": "2008 Q1",
                  "value": 1.52
                },
                {
                  "timePeriod": "2008 Q2",
                  "value": 1.67
                },
                {
                  "timePeriod": "2008 Q3",
                  "value": 1.84
                },
                {
                  "timePeriod": "2008 Q4",
                  "value": 2.07
                },
                {
                  "timePeriod": "2009 Q1",
                  "value": 2.39
                },
                {
                  "timePeriod": "2009 Q2",
                  "value": 2.71
                },
                {
                  "timePeriod": "2009 Q3",
                  "value": 3.03
                },
                {
                  "timePeriod": "2009 Q4",
                  "value": 3.33
                },
                {
                  "timePeriod": "2010 Q1",
                  "value": 3.5
                },
                {
                  "timePeriod": "2010 Q2",
                  "value": 3.37
                },
                {
                  "timePeriod": "2010 Q3",
                  "value": 3.15
                },
                {
                  "timePeriod": "2010 Q4",
                  "value": 3.01
                },
                {
                  "timePeriod": "2011 Q1",
                  "value": 2.8
                },
                {
                  "timePeriod": "2011 Q2",
                  "value": 2.8
                },
                {
                  "timePeriod": "2011 Q3",
                  "value": 2.84
                },
                {
                  "timePeriod": "2011 Q4",
                  "value": 2.75
                },
                {
                  "timePeriod": "2012 Q1",
                  "value": 2.64
                },
                {
                  "timePeriod": "2012 Q2",
                  "value": 2.55
                },
                {
                  "timePeriod": "2012 Q3",
                  "value": 2.46
                },
                {
                  "timePeriod": "2012 Q4",
                  "value": 2.45
                },
                {
                  "timePeriod": "2013 Q1",
                  "value": 2.57
                },
                {
                  "timePeriod": "2013 Q2",
                  "value": 2.68
                },
                {
                  "timePeriod": "2013 Q3",
                  "value": 2.8
                },
                {
                  "timePeriod": "2013 Q4",
                  "value": 2.89
                },
                {
                  "timePeriod": "2014 Q1",
                  "value": 2.85
                },
                {
                  "timePeriod": "2014 Q2",
                  "value": 2.73
                },
                {
                  "timePeriod": "2014 Q3",
                  "value": 2.54
                },
                {
                  "timePeriod": "2014 Q4",
                  "value": 2.32
                },
                {
                  "timePeriod": "2015 Q1",
                  "value": 2.25
                },
                {
                  "timePeriod": "2015 Q2",
                  "value": 2.33
                },
                {
                  "timePeriod": "2015 Q3",
                  "value": 2.53
                },
                {
                  "timePeriod": "2015 Q4",
                  "value": 2.74
                },
                {
                  "timePeriod": "2016 Q1",
                  "value": 2.76
                },
                {
                  "timePeriod": "2016 Q2",
                  "value": 2.61
                },
                {
                  "timePeriod": "2016 Q3",
                  "value": 2.35
                },
                {
                  "timePeriod": "2016 Q4",
                  "value": 2.11
                },
                {
                  "timePeriod": "2017 Q1",
                  "value": 2.08
                },
                {
                  "timePeriod": "2017 Q2",
                  "value": 2.2
                },
                {
                  "timePeriod": "2017 Q3",
                  "value": 2.38
                },
                {
                  "timePeriod": "2017 Q4",
                  "value": 2.59
                },
                {
                  "timePeriod": "2018 Q1",
                  "value": 2.63
                },
                {
                  "timePeriod": "2018 Q2",
                  "value": 2.67
                },
                {
                  "timePeriod": "2018 Q3",
                  "value": 2.64
                },
                {
                  "timePeriod": "2018 Q4",
                  "value": 2.5
                },
                {
                  "timePeriod": "2019 Q1",
                  "value": 2.31
                },
                {
                  "timePeriod": "2019 Q2",
                  "value": 2.04
                },
                {
                  "timePeriod": "2019 Q3",
                  "value": 1.83
                },
                {
                  "timePeriod": "2019 Q4",
                  "value": 1.71
                },
                {
                  "timePeriod": "2020 Q1",
                  "value": 1.65
                },
                {
                  "timePeriod": "2020 Q2",
                  "value": 1.59
                },
                {
                  "timePeriod": "2020 Q3",
                  "value": 1.58
                }
              ],
              "xField": "timePeriod",
              "yField": "value"
            }
          }
        }
      ]
    }`

## **Screenshots (optional)** / **bug 截图（可选）**
设计器错误
![image](https://user-images.githubusercontent.com/900786/170206471-8d8aac41-0e84-4708-b64b-a2ccedf581f1.png)

预览没问题
![image](https://user-images.githubusercontent.com/900786/170208084-cdbf5af9-3917-4a4d-b25f-cb75fae75da5.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
引擎版本与官网demo一致

**Comment by LeoYuan** [comment]
信息麻烦再给完整点，比如 library 要怎么加 antd-charts？

直接基于 demo fork，启动就能复现就更好了~

**Comment by baiheinet** [comment]
> 信息麻烦再给完整点，比如 library 要怎么加 antd-charts？
> 
> 直接基于 demo fork，启动就能复现就更好了~

`{
      "package": "@ant-design/plots",
      "version": "1.0.9",
      "urls": [
        "https://unpkg.com/@ant-design/plots@latest/dist/plots.min.js"
      ],
      "library": "Plots"
    },`

**Comment by huangapple** [comment]
@baiheinet  有解决吗？

**Comment by wangqiangstar** [comment]
> https://unpkg.com/@ant-design/plots@latest/dist/plots.min.js

请问下有生成的@ant-design/plots的meta物料文件吗
