### ISSUE TITLE
期望可以在windows上更方便调试

### ISSUE THREAD

**Issue by hjgeek** [alibaba/lowcode-engine#548]
”windows 环境必须使用 WSL“，这条对windows环境调试太不友好了
建议改用node，来实现那些 sh 命令脚本

**Comment by liujuping** [comment]
详细说明：https://www.yuque.com/lce/doc/glgn4a

**Comment by chenfeiwu** [comment]
太希望支持window了

**Comment by chenfeiwu** [comment]
lowcode的出现是为了打破物料孤岛，却成为了编译系统的孤岛 呜呜呜~~~还没开始打破物料孤岛就已经在门口堵死了 哈哈

**Comment by 350020527** [comment]
太希望支持window了，调试方便，对没有苹果电脑的人来说就是灾难

**Comment by liujuping** [comment]
> 太希望支持window了，调试方便，对没有苹果电脑的人来说就是灾难

主要是公司配置的都是 Mac，没有支持 window 的条件，只能希望大家多多共建，帮组低代码引擎支持 window。🙇‍♀️
