### ISSUE TITLE
@alilc/element 初始化新建物料步骤与官方文档描述不符

### ISSUE THREAD

**Issue by canfoo** [alibaba/lowcode-engine#549]
官方文档描述 @alilc/element 新建一个组件如下：
<img width="611" alt="image" src="https://user-images.githubusercontent.com/16999086/170227889-3e37dfc9-ddda-41ab-8cc5-560ac72513ac.png">

按照步骤执行截图如下：
<img width="788" alt="image" src="https://user-images.githubusercontent.com/16999086/170228663-10624399-f5af-4d57-8bec-de93504c79dd.png">

包模式选项和官方描述不一样，尝试选择“PC-多包模式”继续，生成的代码目录和官方描述的也不一致。另外在安装依赖的时候，安装失败：“@ali/fie4-plugin-component 这个包不存在无法下载安装”，到npm源查找下，发现这个包确实不存在。。。至此，无法进行下一步了。

<img width="485" alt="image" src="https://user-images.githubusercontent.com/16999086/170229120-49e2c091-2172-4ada-8cee-7d1dfba69abc.png">

所以是哪里出现问题了？@alilc/element升级了，但是官方文档未更新？还是？

**Comment by mark-ck** [comment]
没有复现你说的问题唉，我执行 npm init @alilc/element react-comps --registry=https://registry.npmmirror.com 是跟文档说明一致的

**Comment by eternalsky** [comment]
看起来是引用到了老的 element 版本，可以试下清楚一下 npm 的缓存再试试。或者更新到比较新的 npm 版本尝试一下
