### ISSUE TITLE
Failed to init plugin:editorInit, it maybe affect those plugins which depend on this.

### ISSUE THREAD

**Issue by blueju** [alibaba/lowcode-engine#552]
## **Describe the bug (required)** / **详细描述 bug（必填）**

报错信息：

[designer:pluginManager] Failed to init plugin:editorInit, it maybe affect those plugins which depend on this.

![image](https://user-images.githubusercontent.com/49681036/170407769-03b6a40d-68f2-4da2-ac52-61f9ce90c63c.png)

导致物料无法被拖拽入画布

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

开发环境不报错，构建后运行报错。

因为代码在公司内部，因此无法提供 😭，也提供不出来 codesandbox 示例供演示。

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

不报该错误，物料可被拖拽入画布

---

## **Screenshots (optional)** / **bug 截图（可选）**

![image](https://user-images.githubusercontent.com/49681036/170407769-03b6a40d-68f2-4da2-ac52-61f9ce90c63c.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by blueju** [comment]
如果无法通过以上信息得知问题出处，期望能得到各位大佬对该错误的一些猜测可能、当初设计该报错信息时考虑的场景情况、或或者源码位置。
谢谢各位。

**Comment by JackLian** [comment]
有没有可以复现的demo，截图里能看到的无非是先从第一个报错的查起，看看为啥第一个链接报错了

**Comment by blueju** [comment]
原因是：初始化时传入的 json schema 是错误的
