### ISSUE TITLE
画布中组件设置点击跳转后无法选中组件，如何在编辑模式下屏蔽组件的点击事件？

### ISSUE THREAD

**Issue by wtt24** [alibaba/lowcode-engine#553]
## **Describe the bug (required)** / **详细描述 bug（必填）**

画布中组件设置点击跳转后无法在画布中选中组件，试图选中组件后直接触发组件的跳转。
如何在编辑模式下屏蔽组件的点击事件？

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 画布中拖入一个按钮
3. 为按钮设置跳转链接
4. 在画布中试图选中按钮，但是直接出发了跳转

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
希望能直接选中按钮，而不是触发按钮的点击事件

---

## **Screenshots (optional)** / **bug 截图（可选）**
![image](https://user-images.githubusercontent.com/32216310/170409979-1102af53-6963-40c7-ab62-6878279bed04.png)

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.8] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.3] / 低代码引擎扩展包版本

**Comment by liujuping** [comment]
参考：https://github.com/alibaba/lowcode-engine/issues/510

**Comment by LeoYuan** [comment]
或者配置一个 onClickHook，禁止在画布中选中~

https://github.com/alibaba/lowcode-engine/blob/3d176cb5345f9c712457f2d2545e03541ffcb585/packages/types/src/metadata.ts#L439

**Comment by wtt24** [comment]
> 

直接 return false不生效呢
```js
advanced: {
    callbacks: {
      onClickHook: () => false,
    },
},
```
