### ISSUE TITLE
物料库加载CSS方式存在样式污染问题

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#559]
比如：我开发页面用的是antd的组件，我使用了fusion和antd两个物料库，因为两个css文件都对body的fontsize写了样式，导致页面的样式会出现变大变小的问题。因为这是通过加载css的方式

红色区域是我的预览，顶部是我们自己的layout
![Uploading image.png…]()

**Comment by oneQiu** [comment]
![image](https://user-images.githubusercontent.com/50658231/170653207-e217dc8e-5209-4937-b54e-7b9277e0fa69.png)

**Comment by oneQiu** [comment]
![image](https://user-images.githubusercontent.com/50658231/170655044-54063373-5678-4598-a3d4-947ab0c0bf56.png)
我的想法是能否把加载的css样式放在head的开始位，而不是结束位，或者说能给个配置。这个样式的影响还是蛮大的

**Comment by LeoYuan** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/Specificity

要不考虑下提高你的 css 的 specificity？next 是引擎的基础依赖，外部 css 只能覆盖或者提高 Specificity~
