### ISSUE TITLE
demo出码后的工程  yarn   @ali/universal-mtop 报错

### ISSUE THREAD

**Issue by ah-wq** [alibaba/lowcode-engine#56]
demo出码后，下载源码进行yarn 发现 Couldn't find package "@ali/universal-mtop@^5.1.9" required by "@alilc/lowcode-datasource-mtop-handler@*" on the "npm" registry。无法安装成功，导致出码后的代码无法使用，烦请解决一下。

**Comment by Clarence-pan** [comment]
好的，package.json 中的数据源相关的依赖应该需要根据 dataSourceMap 中用到的来按需添加  回头我修复下此问题

**Comment by Clarence-pan** [comment]
fixed in @alilc/lowcode-code-generator@1.0.1
