### ISSUE TITLE
高级表格中的分页器不带事件，希望能够像单独分页器一样可以编辑事件

### ISSUE THREAD

**Issue by yanchengqu** [alibaba/lowcode-engine#560]
## 复现截图
高级表格中的分页器不带事件
![分页器](https://user-images.githubusercontent.com/7960007/170693820-f7d0d206-3b20-4312-bae5-5b5d04c3b48c.png)
单独分页器带事件
![正常分页器](https://user-images.githubusercontent.com/7960007/170694136-f476b2ae-c25c-4b42-852f-19218b941397.png)

## 复现流程与链接
选中“高级表格”没看到分页器可以编辑操作事件，具体参考上图红框部分
## 期望结果
希望高级表格中的分页器可以像单独分页器一样，能够编辑事件
## 环境信息

- 引擎版本 1.0.8
- ext 版本 1.0.3
- 物料
  - moment﹫2.24.0
  - lodash
  - ﹫alifd/next﹫1.24.18
  - NextTable﹫1.0.1
  - ﹫alilc/lowcode-materials﹫1.0.2
  - ﹫alifd/pro-layout﹫1.0.1-beta.6
  - ﹫alifd/fusion-ui﹫1.0.5

**Comment by 1377023219** [comment]
我们是直接隐藏掉自带的分页，拉个新的分页组件做处理。
在这里顺便也希望开发者能更新下默认的assets.json文件
