### ISSUE TITLE
如何正确在window对象上，扩展全局变量。

### ISSUE THREAD

**Issue by 1377023219** [alibaba/lowcode-engine#562]
是这样的，我们想通过window对象增加变量，给"源码模板"增加一些新功能，以便使用。
![image](https://user-images.githubusercontent.com/36667646/170861051-303b3568-92d0-42cf-aaee-dc54c29509dd.png)
![image](https://user-images.githubusercontent.com/36667646/170860641-573c471c-3d96-459c-b5aa-c38624b5d820.png)
![image](https://user-images.githubusercontent.com/36667646/170860673-f16aa4db-57c6-4b85-98e0-2a7761ade155.png)

框架的"模拟器"是在iframe里的，我需要等待iframe生成后获取到window才能写入全局变量
但是因为project.onSimulatorRendererReady的事件，比"源码模板"的componentDidMount生命周期慢一些，导致获取自定义的变量时会报错。

请问如何较好的挂在变量在window上。

**Comment by LeoYuan** [comment]
尝试使用 extraEnvironment 往 renderer 里注入资源~


参考：
- https://github.com/alibaba/lowcode-engine/blob/4f4ac5115d18357a7399632860808f6cffc33fad/packages/plugin-designer/src/index.tsx#L68
- https://github.com/alibaba/lowcode-engine/blob/2871b5ba4c3dbf1ed76bf4d6359fb457190a9b22/packages/designer/src/builtin-simulator/host.ts#L95

**Comment by smlPig** [comment]
> 尝试使用 extraEnvironment 往 renderer 里注入资源~
> 
> 参考：
> 
> * https://github.com/alibaba/lowcode-engine/blob/4f4ac5115d18357a7399632860808f6cffc33fad/packages/plugin-designer/src/index.tsx#L68
> * https://github.com/alibaba/lowcode-engine/blob/2871b5ba4c3dbf1ed76bf4d6359fb457190a9b22/packages/designer/src/builtin-simulator/host.ts#L95

你好！请问具体怎么操作？
