### ISSUE TITLE
页面管理图标如何注册才能显示在第一位？

### ISSUE THREAD

**Issue by HDZnice** [alibaba/lowcode-engine#563]
我在plugin里面，也放在了最开始的地方注册，但是项目跑起来后还是【大纲树】在第一个

**Comment by LeoYuan** [comment]
```ts
AliLowCodeEngine.skeleton.add({
  area: 'leftArea',
  type: 'PanelDock',
  name: 'xxx',
  content: () => 'xxx',
  index: -1, // 使用 index 来定义位置，内置的默认都是 0
  props: { icon: () => 'x' /* ReactElement 也可以 */ },
});
```

![image](https://user-images.githubusercontent.com/1195765/171081197-0d7ac214-a603-4410-b480-9ac83db13b9c.png)

**Comment by HDZnice** [comment]
非常感谢！

**Comment by lavyun** [comment]
👍🏻

**Comment by lmm1990** [comment]
设置index不起作用，代码如下
skeleton.add({
        index: -1,
        area: 'leftArea',
        type: 'PanelDock',
        name: 'pageComponentsPane',
        content: ComponentsPane,
        props: {
          align: 'top',
          icon: 'zujianku',
          description: '页面',
        },
      });
      
      ts类型也没有index参数
export declare type IPublicTypeSkeletonConfig = IPublicTypePanelDockConfig | IPublicTypeWidgetBaseConfig;
https://github.com/alibaba/lowcode-engine/blob/779edf783bac1ef71668fb74eaba44527c99a0f5/packages/types/src/shell/type/widget-base-config.ts

@liujuping

**Comment by LeoYuan** [comment]
![image](https://user-images.githubusercontent.com/1195765/233249162-7bdd56e2-4711-4e2f-aa91-aaf9fd573251.png)

**Comment by lmm1990** [comment]
可以了，index必须要为-2，才可以加到第一位

**Comment by LeoYuan** [comment]
> 可以了，index必须要为-2，才可以加到第一位

index 正常就是用于排序的，之所以 index: -2 才行推测是当前第一个大纲树用了 -1~
