### ISSUE TITLE
物料接入工程配置 renderUrls 后，无法热更新

### ISSUE THREAD

**Issue by twinkle77** [alibaba/lowcode-engine#565]
## **Describe the bug (required)** / **详细描述 bug（必填）**
由于组件比较复杂，需要将设计态跟运行态分开

1. 执行 `npm init @alilc/element your-material-name`
2. 参考大佬的[教程](https://www.bilibili.com/video/BV1bS4y1c7Eq?share_source=copy_web) 
3. 配置  renderUrls
<img width="820" alt="image" src="https://user-images.githubusercontent.com/17792166/171016716-8d776900-28e2-4ab4-adf9-a03971091510.png">
4. 给组件新增 `view.tsx` 文件
<img width="247" alt="image" src="https://user-images.githubusercontent.com/17792166/171016344-1f7944a7-6785-447f-be97-d0cdd988937f.png">

每次改动 `src` 目录下的代码，都需要 yarn build 一次，请问有没有更好的开发方式

**Comment by twinkle77** [comment]
@mark-ck  请教下大佬

**Comment by loganjingdi** [comment]
单独建立一个物料仓库（https://github.com/alibaba/lowcode-materials），并启动，例如在3333端口运行，配置demo工程，universal/assets.json增加如下配置：
![image](https://user-images.githubusercontent.com/48111864/171075013-8f0945cd-b3a1-4315-8368-da9218f5d467.png)，
即可使用热更新。

**Comment by twinkle77** [comment]
我说的可能还不是你这种场景，
你这个场景下直接用 XSwtich 配置代理即可，不用改动代码

```
{
  "proxy": [
    [
      "https://cdn.com/xxx@(.*)/lowcode/view.js",
      "http://localhost:3333/view.js"
    ],
    [
      "https://cdn.com/xxx@(.*)/lowcode/meta.js",
      "http://localhost:3333/meta.js"
    ]
  ],
}

```

@loganjingdi

**Comment by twinkle77** [comment]
"watch": "watch 'npm run lowcode:build' ./src ./lowcode",
