### ISSUE TITLE
使用官方的demo + 官方脚手架创建的物料组件库使用@alilc/build-plugin-alt调试异常

### ISSUE THREAD

**Issue by PTLEI** [alibaba/lowcode-engine#570]
## **Describe the bug (required)** / **详细描述 bug（必填）**

使用官方的demo + 官方脚手架创建的物料组件库，demo使用start启动，物料使用lowcode:dev脚本启动；配合@alilc/build-plugin-alt做调试，demo显示inject注入成功，panel中有相应组件，而拖拽后发生组件not found。

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

1. demo使用start启动
2. 物料使用lowcode:dev脚本启动
3. 物料没用start启动的原因是现行脚手架（20220531）创建的应用使用start会启动一个9001端口的应用（一个next的应用），demo没法inject

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---
![lQLPJxZb6H8dcoDNA5zNBpCwf5LhoTe4hGACl6YPtwD4AA_1680_924](https://user-images.githubusercontent.com/40331443/171086826-1e23f6e1-1ca7-49e4-9c99-81e3546a11b6.png)
<img width="1678" alt="lQLPJxZb6H8dcmPNBmLNDRywV_UOQGUC1B8Cl6YPtUDVAA_3356_1634" src="https://user-images.githubusercontent.com/40331443/171086887-f6eec58d-debc-4896-9598-e66bff0cbe1b.png">

<img width="1680" alt="lQLPJxZb6H8dcqbNBlrNDSCwLp1MOUwkYCcCl6YPtUDhAA_3360_1626" src="https://user-images.githubusercontent.com/40331443/171086890-6656c000-9120-469b-a797-a727bf15797d.png">

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
node: 14.17.1
npm: 6.14.13

**Comment by liujuping** [comment]
1.在控制台中输入 `AliLowCodeEngine.material.componentsMap`，看看对应的物料是否存在

2.选中组件，在控制台中输入 `AliLowCodeEngine.project.currentDocument.selection.getNodes()[0].exportSchema('render')`，查看 componentName 是否匹配。

3.如果还有问题，看一下引擎是什么版本，提供相关信息。

**Comment by PTLEI** [comment]
> AliLowCodeEngine.project.currentDocument.selection.getNodes()[0].exportSchema('render')
1.
![20220531145454](https://user-images.githubusercontent.com/40331443/171111489-aaa60d8d-e30c-4416-83c6-c6d9d71b9aaa.jpg)
2. 
![20220531145521](https://user-images.githubusercontent.com/40331443/171111506-d530f13e-a28a-4d1e-b7da-ca48ce03816b.jpg)
3.
![20220531145705](https://user-images.githubusercontent.com/40331443/171111565-f98e8baf-a7b2-4062-bd61-3ae23f9d2cfa.jpg)


引擎1.0.8 

@alilc/build-plugin-alt 1.0.9
@alilc/lowcode-plugin-inject 1.0.0

**Comment by Dogtiti** [comment]
same

**Comment by eternalsky** [comment]
这块我来处理一下，查了一下是因为 library 对不齐导致的。

**Comment by eternalsky** [comment]
@PTLEI @Dogtiti 已经升级了插件，对应 library 支持配置这个变化。
@alilc/build-plugin-alt 1.1.0
@alilc/lowcode-plugin-inject 1.1.1

组件的 build.lowcode.js 也有一点变化，需要把 library 传入 inject 插件。
```js
const { library } = require('./build.json');

module.exports = {
  alias: {
    '@': './src',
  },
  plugins: [
    [
      '@alifd/build-plugin-lowcode',
      {
        library,
        engineScope: "@alilc"
      },
    ],
    [
      '@alilc/build-plugin-alt',
      {
        type: 'component',
        library,
        inject: true
      }
    ]
  ],
};

```

**Comment by Dogtiti** [comment]
> @PTLEI @Dogtiti 已经升级了插件，对应 library 支持配置这个变化。 @alilc/build-plugin-alt 1.1.0 @alilc/lowcode-plugin-inject 1.1.1
> 
> 组件的 build.lowcode.js 也有一点变化，需要把 library 传入 inject 插件。
> 
> ```js
> const { library } = require('./build.json');
> 
> module.exports = {
>   alias: {
>     '@': './src',
>   },
>   plugins: [
>     [
>       '@alifd/build-plugin-lowcode',
>       {
>         library,
>         engineScope: "@alilc"
>       },
>     ],
>     [
>       '@alilc/build-plugin-alt',
>       {
>         type: 'component',
>         library,
>         inject: true
>       }
>     ]
>   ],
> };
> ```

可以了

**Comment by CalmDownJ** [comment]
借个楼，请问 使用官方demo + 官方脚手架创建的物料组件库 预览页出现 component is not found，有人遇到了吗？有解决方案吗？
![image](https://user-images.githubusercontent.com/20920943/180386350-cbc51db2-8820-4159-9e0f-b01cd45b72ca.png)
![image](https://user-images.githubusercontent.com/20920943/180386380-3b32d857-7af8-48ef-bb11-fd78cd18adf0.png)
