### ISSUE TITLE
自定义用的antd的框架开发的组件，本地开发没问题，部署后，线上预览有时候出现不了报错Component Not Found，刷新一下又出来了，在刷一下又没了，偶现的问题。怎么解决？

### ISSUE THREAD

**Issue by chengqi77** [alibaba/lowcode-engine#573]
自定义用的antd的框架开发的组件，本地开发没问题，部署后，线上预览有时候出现不了报错Component Not Found，刷新一下又出来了，在刷一下又没了，偶现的问题。怎么解决？
**下载的官网demo预览 ，在使用antd场景下，也会有一样的问题**
尝试解决方案：改变packages的加载顺序 （未解决）

**Comment by liujuping** [comment]
按照这个试一下：https://www.yuque.com/lce/doc/bgodtf

**Comment by chengqi77** [comment]
> 按照这个试一下：https://www.yuque.com/lce/doc/bgodtf

OK 谢谢

**Comment by 15163789836** [comment]
你好 请问再使用antd组件开发的时候 有用到表单校验嘛,最近在用antd配页面  再表单校验这遇到了问题，想请问一下 如何配置校验
