### ISSUE TITLE
在组件库开发的组件为什么放到项目资产包里面使用就会渲染异常

### ISSUE THREAD

**Issue by 329697166** [alibaba/lowcode-engine#576]
操作步骤: 
1、npm init @alilc/element xxx；
2、在src/components文件夹下创建了一个form组件;
3、在src/index.tsx里面引入form组件;
4、通过npm publish --access=public发布了组件；
5、在项目的assets.json里加入发布好的组件资产包信息；

代码如下：
![微信图片_20220531173713](https://user-images.githubusercontent.com/8613493/171143512-8d2f97a5-948e-40c9-a881-c1eaa3e21047.png)
![image](https://user-images.githubusercontent.com/8613493/171144352-491f8f15-2863-41b4-96d5-dcad3f43b7cc.png)
![image](https://user-images.githubusercontent.com/8613493/171144444-c0c94e28-3ee3-40f1-bd1a-ef4f581e8d1c.png)
![image](https://user-images.githubusercontent.com/8613493/171144502-6c35c7a0-080b-4639-ab23-38b5f641b795.png)
![image](https://user-images.githubusercontent.com/8613493/171149055-d825ef17-965a-4196-b212-e67b36ceba8e.png)

结果：
![636a77c8c16acf3d231027d4a7726dd](https://user-images.githubusercontent.com/8613493/171140587-747686bf-11a6-48e9-ab99-8cc40e91f4f0.png)

**Comment by LeoYuan** [comment]
packages 中没有引入 antd 资源文件？
