### ISSUE TITLE
物料引入问题请教

### ISSUE THREAD

**Issue by w4ngzhen** [alibaba/lowcode-engine#578]
在使用官方antd物料的时候，发现assets中需要将antd的umd库CDN方式引入，但是看antd物料的配置，并没有看到有比较特殊的配置表明antd以externals的方式引用。所以请教一下官方这块有具体的配置吗？我具体的需求是：自己开发的组件库是umd形式的，但是会生成类型定义，然后在materials项目中，将这些组件库以externals的方式引入呢？

**Comment by LeoYuan** [comment]
写在 assets#packages 里，即代表会引入~
