### ISSUE TITLE
创建低代码应用方式2 显示错误

### ISSUE THREAD

**Issue by xingbaoliang** [alibaba/lowcode-engine#580]
按照官方文档中 创建低代码应用，接入编辑。展示的内容只有一个图标
<img width="991" alt="image" src="https://user-images.githubusercontent.com/27947669/171196179-5cdfd078-cb4a-4569-b99e-723b4749c28d.png">

**Comment by LeoYuan** [comment]
哪个文档？

**Comment by xingbaoliang** [comment]
<img width="1410" alt="image" src="https://user-images.githubusercontent.com/27947669/171321374-657b4ae0-55a4-479b-9519-73f727c4c492.png">
这个https://lowcode-engine.cn/docV2/start-with-lce

**Comment by xingbaoliang** [comment]
求大佬看看

**Comment by LeoYuan** [comment]
你可以来个 复现仓库，不然没法看。。。
