### ISSUE TITLE
init设置默认device，选中状态不正确

### ISSUE THREAD

**Issue by yz1311** [alibaba/lowcode-engine#587]
## **详细描述 bug（必填）**

请提供清晰且精确的 bug 描述

如果设置device: 'mobile'
```javascript
 init(document.getElementById('lce-container')!, {
    // designMode: 'live',
    locale: 'zh-CN',
    device: 'mobile',
   ...
```
虽然界面上的宽度变成375了，但是模拟器的选中状态还是desktop

---

## **如何复现 bug？（必填，非常重要）**

详细复现步骤：

---

## **预期行为（必填，非常重要）**
选中正确的图标

---

## **bug 截图（可选）**
![QQ20220601-171018](https://user-images.githubusercontent.com/9854019/171369723-8714c8e6-3952-4b79-81cc-705eb07a00a3.png)

---

## **请提供如下信息（必填）**
- 引擎版本 1.0.8
- ext 版本 1.0.3
- 物料
  - moment﹫2.24.0
  - lodash
  - iconfont-icons
  - ﹫ant-design/icons﹫4.7.0
  - antd﹫4.19.5
  - ﹫alifd/next﹫1.23.0
  - ﹫alilc/lowcode-materials﹫1.0.3

## **更多额外信息（可选）**
无

**Comment by LeoYuan** [comment]
@mark-ck 可以帮忙看下~或者把这个插件源码放出来，由社区帮忙 PR~

**Comment by mark-ck** [comment]
已开源 https://github.com/alibaba/lowcode-plugins/blob/main/packages/plugin-simulator-size/src/index.tsx

**Comment by yz1311** [comment]
源码中，是这三个类型
const devices = [
  { key: 'desktop' },
  { key: 'tablet' },
  { key: 'phone' },
];

但是init的device值是 'default' | 'mobile'两个值，不知道是否为bug?
我将device: 'mobile'改为device: 'phone'可以正常选中

![image](https://user-images.githubusercontent.com/9854019/172546840-0c5873de-ec4c-45bb-8c8e-91159bfe9db3.png)

**Comment by LeoYuan** [comment]
插件中实现自定义画布大小有点问题，不应该直接找到 dom 节点去修改样式，可以参考下 [引擎画布代码](https://github.com/alibaba/lowcode-engine/blob/4f4ac5115d18357a7399632860808f6cffc33fad/packages/designer/src/builtin-simulator/host-view.tsx#L51)

目前支持 3 种定制方式：
1. project.simulator.set('device', 'mobile' / 'iphonex' / 'iphone6' / 'default'); // 直接使用内置设备类型
2. project.simulator.set('deviceClassName', 'my-canvas-class'); // 定制 canvas 的样式类
3. project.simulator.set('deviceStyle', { canvas: { width: '300px', backgroundColor: 'red' }, viewport: { width: '280px' } }); // 最灵活的方式，直接设置 canvas / viewport 的样式（canvas 是外框，viewport 是内框，可以在 canvas 设置手机 / 平板背景图）

**Comment by LeoYuan** [comment]
@yz1311 要不要试试按照上面的方式，优化一下现有 SimulatorPane 的逻辑？😄
