### ISSUE TITLE
在antd组件中 一个页面如何可以展示 多个弹框，一个页面有多个弹窗 但设计态目前的大纲树是只能选取一个模态框，预览页也能展示出一个 弹窗

### ISSUE THREAD

**Issue by 15163789836** [alibaba/lowcode-engine#597]
## **Describe the bug (required)** / **详细描述 bug（必填）**
一个页面有多个弹窗 但是只能选取展示一个，设计态目前的大纲树是只能选取一个模态框，预览页也能展示出一个 弹窗，怎么能选取展示 多个弹窗

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
我一个页面创建了 两个弹窗，现在只能选取 展示其中一个  另一个展示不出来，在预览的时候，我用两个按钮绑定了两个点击事件去触发模态框的显示，但是只有在设计时勾选了的模态框才能被控制，设计时也只能勾选一个。怎么能两个都弹出

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
使用demo  antd组件 创建多个弹窗   在预览页面只能展示出一个

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为
配置 两个弹窗，我用两个按钮绑定了两个点击事件去触发模态框的显示，但是只有在设计时勾选了的模态框才能被控制，设计时也只能勾选一个。怎么能两个弹窗都弹出

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
antd组件 只能选取一个，到预览 页面也只能展示 选取的哪一个
![image](https://user-images.githubusercontent.com/104408070/171662597-44936418-f9fd-4eb6-bd87-ef7e862a415c.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
  Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by LeoYuan** [comment]
看是不是 schema 上有 hidden 字段隐藏了模态框~

如果是的话，参考 https://github.com/alibaba/lowcode-demo/blob/accdf87661ce5ed45b552dcf3d913e09bc849509/src/sample-plugins/delete-hidden-transducer/index.ts#L6

**Comment by 15163789836** [comment]
> 看是不是 schema 上有 hidden 字段隐藏了模态框~
> 
> 如果是的话，参考 https://github.com/alibaba/lowcode-demo/blob/accdf87661ce5ed45b552dcf3d913e09bc849509/src/sample-plugins/delete-hidden-transducer/index.ts#L6

确实是有hidden字段 为true，只要设置一个弹出框  另一个弹窗就会设置hidden字段 为true， 手动修改schema 都改成false 或者删掉 再一点保存又会重新生成出来，参考的那段代码 和我的项目里的代码现在一样

**Comment by LeoYuan** [comment]
导出 schema 是用 exportSchema(TransformStage.Save) 么？示例代码的 transducer 只在 Save 阶段生效~

**Comment by 15163789836** [comment]
> 导出 schema 是用 exportSchema(TransformStage.Save) 么？示例代码的 transducer 只在 Save 阶段生效~

可以了 谢谢 大佬
