### ISSUE TITLE
数据源面板-请求参数点击变量绑定页面渲染错误

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#604]
复现
1. 点击数据源面板，新建
![image](https://user-images.githubusercontent.com/50658231/172155671-0161f397-e392-4e55-ac2e-0e6492767ba8.png)
2. 点击请求参数右侧的变量绑定，点击选择框
现象
![image](https://user-images.githubusercontent.com/50658231/172155797-fb962efe-d075-4760-96b8-a9a68f6f07e1.png)

**Comment by LeoYuan** [comment]
感觉是个很老的问题了，用了最新版本么？

**Comment by oneQiu** [comment]
新版本解决
