### ISSUE TITLE
slot在拖拽后出现重复嵌套

### ISSUE THREAD

**Issue by luna2216** [alibaba/lowcode-engine#605]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

slot在拖拽后出现重复嵌套

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

1、进入https://lowcode-engine.cn/demo/index.html
2、拖入一个自定卡片，把自定义卡片从区块中拖出来
3、查看大纲树，卡片的slot中会多出一层嵌套的slot
4、重复上述操作，会出现很多层嵌套

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

slot不存在嵌套

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

![image](https://user-images.githubusercontent.com/19427679/172182551-c1f790e5-2ced-4ca2-a3a4-5118d98912d5.png)

**Comment by LeoYuan** [comment]
能用非自定义的卡片复现么？

**Comment by luna2216** [comment]
> 

只要用了jsslot就会出现，定位到原因是拖动的时候复制了当前的schema，会再执行一遍jsslot的初始化操作，插入了一个slot，但是这时候value里已经有slot。

**Comment by LeoYuan** [comment]
关键是咋操作的。。。
```
1. xxx
2. yyy
3. zzz
```
我确实没法复现。。。

**Comment by LeoYuan** [comment]
![image](https://user-images.githubusercontent.com/1195765/174994347-a5920194-1653-4e64-b7d9-42372557be81.png)

将卡片拖进拖出若干次后，看大纲树没有你说的情况~

**Comment by LeoYuan** [comment]
倒是来个可复现demo啊，从第一句话就在说。。。

**Comment by luna2216** [comment]
> 倒是来个可复现demo啊，从第一句话就在说。。。

自定义卡片啊，问题描述不就说了

**Comment by luna2216** [comment]
![image](https://user-images.githubusercontent.com/19427679/175500589-c7f9abfe-261a-4d30-9293-f7d59b27e600.png)
