### ISSUE TITLE
组件和JS面板之间通信问题

### ISSUE THREAD

**Issue by oYangJingLun** [alibaba/lowcode-engine#606]
组件内部能调JS面板的方法吗？
比如我有一个button组件，现在的做法是在meta.js里面配置events把事件暴露出去，然后设计时在事件绑定js面板的方法。
差不多是这样：
...
render() {
return 
<button onclick="this.props.onclick"  >
}
...
如果我想封装一些通用的方法在js面板，然后给组件调用，而不是在设计时再去绑定一次，这该如何做？
...
render() {
return 
<button onclick="buttonClick"  >
}
...

js面板
buttonClick() {
   doingsomething()
}

**Comment by LeoYuan** [comment]
不可以，不然组件岂不是耦合了 JS 面板中的函数~
