### ISSUE TITLE
添加了一个filter组件，怎么获取form的formData

### ISSUE THREAD

**Issue by leehomeok** [alibaba/lowcode-engine#61]
![image](https://user-images.githubusercontent.com/13464485/156181729-0e2ee153-0041-4721-b385-05ff1e557ef7.png)
如图，我添加了一个filter组件，怎么给查询按钮的点击事件onSearch方法 添加获取formData的数据逻辑？

**Comment by leehomeok** [comment]
请问protable的分页器要怎么绑定数据，以及绑定pageSize, onchange事件？
![image](https://user-images.githubusercontent.com/13464485/156345667-4769b246-765e-42b5-85dd-6066906d6c81.png)

**Comment by blueju** [comment]
@leehomeok 请问为什么关闭 issue，是找到解决方案了吗？这一块我也是有些疑惑怎么获取表单值，您是怎么做的？我在想我是不是 react+antd 用多了感觉了使用 form.getFieldsValue 来获取表单值

**Comment by leehomeok** [comment]
> @leehomeok 请问为什么关闭 issue，是找到解决方案了吗？这一块我也是有些疑惑怎么获取表单值，您是怎么做的？我在想我是不是 react+antd 用多了感觉了使用 form.getFieldsValue 来获取表单值

组件有默认事件onSubmit 可以拿到表单数据
