### ISSUE TITLE
物料库脚手架生成的物料库无法使用了

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#612]
我的物料库是两个多月前通过@alilc-element生成的，一直都能使用，但是今天删除依赖重新下载依赖的时候运行不起来了。报错如图
![image](https://user-images.githubusercontent.com/50658231/172349443-3ce3d92b-19a5-4543-bf78-f889ad4bae19.png)
![image](https://user-images.githubusercontent.com/50658231/172349481-ca23abff-604a-405e-82dc-04038d5b5ac0.png)

**Comment by mark-ck** [comment]
把 webpack 锁定到 4.x 再试试
