### ISSUE TITLE
npm init @alilc/element your-material-name 搭建项目build模式下预览状态报错

### ISSUE THREAD

**Issue by rodchen-king** [alibaba/lowcode-engine#619]
## **Describe the bug (required)** / **详细描述 bug（必填）**

1. npm init @alilc/element your-material-name 创建项目，不做任何修改
2. dev环境下，编辑和预览够可正常展示
3. build环境下，编辑可以正常展示，预览报错

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

1. 通过npm init @alilc/element your-material-name 创建项目，不修改任何代码。
4. 安装依赖
5. npm run lowcode:dev 项目运行正常，编辑状态和预览态都可以正常显示。
6. npm run lowcode:build。项目生成./build/lowcode文件夹。
7. 在./build/lowcode下执行http-server启动服务。
8. 编辑状态操作正常，预览状态失败报错

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
![image](https://user-images.githubusercontent.com/19780441/172583607-2f810d9a-2c16-4599-b95c-fa48e72c16a4.png)

![image](https://user-images.githubusercontent.com/19780441/172583400-af215763-b306-497f-aa78-2c2d80846b71.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - @alifd/build-plugin-lowcode: [e.g. 0.3.0]  / 低代码引擎版本

![image](https://user-images.githubusercontent.com/19780441/172583259-ea115c23-25c5-48b1-865d-9d6001f50b49.png)

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by rodchen-king** [comment]
@mark-ck

**Comment by mark-ck** [comment]
@rodchen-king 我刚刚按照你的步骤试了一遍，没有复现问题😂

**Comment by mark-ck** [comment]
![image](https://user-images.githubusercontent.com/44559440/173521596-5cf16dde-8f20-4b8c-bfda-a05d470573e2.png)

**Comment by rodchen-king** [comment]
> @rodchen-king 我刚刚按照你的步骤试了一遍，没有复现问题😂

大佬，你这个是编辑状态啊，你预览状态有问题吗，我说的是预览状态的情况

**Comment by mark-ck** [comment]
> > @rodchen-king 我刚刚按照你的步骤试了一遍，没有复现问题😂
> 
> 大佬，你这个是编辑状态啊，你预览状态有问题吗，我说的是预览状态的情况

预览态是有些问题，你更新到这个版本再试试 @alifd/build-plugin-lowcode@0.3.1-beta.0 ，如果没有问题我再发个正式版

**Comment by rodchen-king** [comment]
@mark-ck 这个包有点问题，package的main设置有点问题。
![image](https://user-images.githubusercontent.com/19780441/173876518-982bc51d-3faa-4de5-aa5d-3dc72d75d3e2.png)

我手动改了一下node_modules里面的main路径，现在可以正常跑了，build下的preview可以用了。
![image](https://user-images.githubusercontent.com/19780441/173876746-3b9bef85-0fbb-433c-be77-327daa8b3cc0.png)
