### ISSUE TITLE
数据源面板，编辑数据源，添加“请求头信息”之后页面报异常

### ISSUE THREAD

**Issue by BarronLin** [alibaba/lowcode-engine#62]
### 重现步骤
如下图所示：
![image](https://user-images.githubusercontent.com/9267731/156189278-62af6749-0e92-47cc-b1f9-a8a703721e39.png)

点击确认，报异常如下：
![image](https://user-images.githubusercontent.com/9267731/156189812-260b6654-30ef-4f59-96a1-d53b0af6e7c6.png)

**Comment by liujuping** [comment]
Duplicate of https://github.com/alibaba/lowcode-engine/issues/127
