### ISSUE TITLE
物料开发中，自定义的两个设置器setter之间无法使用event.on、event.emit进行通信

### ISSUE THREAD

**Issue by chenrunsong** [alibaba/lowcode-engine#622]
## **Describe the bug (required)** / **详细描述 bug（必填）**
实现了两个自定义的设置器setterA及setterB，并可正常运行，随后有个需求场景为在setterA中使用event.on进行注册监听事件，在setterB中使用event.emit进行触发，无效！

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
![image](https://user-images.githubusercontent.com/21167854/172758702-0acdbee0-ffd7-483e-8368-ee4014123a67.png)
![image](https://user-images.githubusercontent.com/21167854/172758778-78f51b3b-44e2-4a1c-85a1-caea58c16d08.png)

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
setterA:
componentDidMount() {
event.on('ListConfigSetterEvent', this.bindEvent)
}
componentWillUnmount() {
event.off('ListConfigSetterEvent', this.bindEvent)
}
bindEvent = (eventName) => {
// do someting
console.log(eventName, 666666)
}

setterB: 在select的change事件中通过event.emit使用先前注册的事件名“ListConfigSetterEvent”进行触发，但无效
handleChange = (value, data, extra) => {
    this.bindFunction()
    this.setState({ apiID: value })
    this.state.onChange(value)
  }
  bindFunction = () => {
    const {field, value} = this.props
    event.emit('ListConfigSetterEvent', field.name)
  }

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
![image](https://user-images.githubusercontent.com/21167854/172759015-8b18517b-f1ca-46b4-989f-56c35c9099c0.png)
![image](https://user-images.githubusercontent.com/21167854/172759051-c536c474-e6cd-458a-8873-096916012bde.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by chenrunsong** [comment]
没有大佬帮忙看下吗？

**Comment by LeoYuan** [comment]
on 前加个 common:

```
event.on('common:xxx', (data) => {});

event.emit('xxx', 1, 2, 3);
```

**Comment by chenrunsong** [comment]
> on 前加个 common:
> 
> ```
> event.on('common:xxx', (data) => {});
> 
> event.emit('xxx', 1, 2, 3);
> ```

感谢，已解决，希望更新到文档中。
