### ISSUE TITLE
Bug report: 在 schema 面板修改 schema，源码面板的代码没有变化，并且把 schema 改回来了

### ISSUE THREAD

**Issue by haoziqaq** [alibaba/lowcode-engine#624]
![image](https://user-images.githubusercontent.com/24223652/172787267-2ab6eff5-f90a-417b-ac02-e03853f2e3b7.png)

![image](https://user-images.githubusercontent.com/24223652/172787492-889e6554-b11a-41ca-9a41-947779e001df.png)

![image](https://user-images.githubusercontent.com/24223652/172787529-538efb3e-379e-442d-8d31-00a07e521642.png)

![image](https://user-images.githubusercontent.com/24223652/172787633-a78b64b2-264d-4f1f-9fb4-5638f37bd3c0.png)

**Comment by alvarto** [comment]
By design。目前源码面板会涉及到 JSX 编译，所以所有的 state、lifeCycle、methods 都是编译之后的结果，源码存在 originCode 里。

具体说明见：https://www.yuque.com/lce/usage/trgdtr#Oj88V

**Comment by haoziqaq** [comment]
importSchema 如果只带有  originCode 而没带有 state、lifeCycle、methods。理应导入的时候生成 state、lifeCycle、methods。 现在的行为貌似是，必须打开源码面板，才会触发生成。再这之前，绑定事件或者变量是找不到定义的。

**Comment by alvarto** [comment]
源码面板只是一个插件，它通过 originCode 来保存原形代码的依赖。
引擎目前不负责导入时生成 originCode，因为目前 originCode 还是一个没有进入规范的字段。而且从实际操作而言，如果 state、lifeCycle、methods经过了 babel 编译，它的数据也很难直接还原出来一个 originCode。

**Comment by haoziqaq** [comment]
了解了 感谢



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年6月9日(周四) 下午5:48
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/lowcode-engine] Bug report: 在 schema 面板修改 schema，源码面板的代码没有变化，并且把 schema 改回来了 (Issue #624)




 
源码面板只是一个插件，它通过 originCode 来保存原形代码的依赖。
 引擎目前不负责导入时生成 originCode，因为目前 originCode 还是一个没有进入规范的字段。而且从实际操作而言，如果 state、lifeCycle、methods经过了 babel 编译，它的数据也很难直接还原出来一个 originCode。
