### ISSUE TITLE
如何做block区块、Template模板

### ISSUE THREAD

**Issue by heyicheng** [alibaba/lowcode-engine#628]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by LeoYuan** [comment]
参考组件面板，组件面板拖的是单一节点的 schema，区块 / 模板拖的是多个节点的 schema，本质上没有区别~

**Comment by dzlhk** [comment]
> 参考组件面板，组件面板拖的是单一节点的 schema，区块 / 模板拖的是多个节点的 schema，本质上没有区别~

区块或者模版有具体的demo 或者文档参考么，拖拽后，区块和模版中自定义的方法，和变量，是如何解析的呢？

**Comment by LeoYuan** [comment]
区块实现上跟 组件面板 非常类似的，注意：区块没有方法，变量也是遵循页面搭建协议，设置一个 { type: 'JSExpression', value: 'xxx' } 结构就好~

假如你是想做低代码组件，包含生命周期、内部数据对象、动作绑定，一时半会说不清，可以关注下 @eternalsky 的 GMTC 演讲~

**Comment by dzlhk** [comment]
好的谢谢，

> 区块实现上跟 组件面板 非常类似的，注意：区块没有方法，变量也是遵循页面搭建协议，设置一个 { type: 'JSExpression', value: 'xxx' } 结构就好~
> 
> 假如你是想做低代码组件，包含生命周期、内部数据对象、动作绑定，一时半会说不清，可以关注下 @eternalsky 的 GMTC 演讲~

好的谢谢，演讲时还没有开始么？还是已经结束，可以看回放？

**Comment by LeoYuan** [comment]
还没开始，请关注 8 月中旬的 GMTC~

**Comment by guohejun** [comment]
> 区块实现上跟 组件面板 非常类似的，注意：区块没有方法，变量也是遵循页面搭建协议，设置一个 { type: 'JSExpression', value: 'xxx' } 结构就好~
> 
> 假如你是想做低代码组件，包含生命周期、内部数据对象、动作绑定，一时半会说不清，可以关注下 @eternalsky 的 GMTC 演讲~

怎么做低代码组件啊，有没有demo可以参考下，我想实现把自定义组件拖拽到编辑器里，然后上面有一个“拖拽组件或模板到这里”的功能

**Comment by JackLian** [comment]
> > 区块实现上跟 组件面板 非常类似的，注意：区块没有方法，变量也是遵循页面搭建协议，设置一个 { type: 'JSExpression', value: 'xxx' } 结构就好~
> > 假如你是想做低代码组件，包含生命周期、内部数据对象、动作绑定，一时半会说不清，可以关注下 @eternalsky 的 GMTC 演讲~
> 
> 怎么做低代码组件啊，有没有demo可以参考下，我想实现把自定义组件拖拽到编辑器里，然后上面有一个“拖拽组件或模板到这里”的功能

https://parts.lowcode-engine.cn/home

**Comment by guohejun** [comment]
> > > 区块实现上跟 组件面板 非常类似的，注意：区块没有方法，变量也是遵循页面搭建协议，设置一个 { type: 'JSExpression', value: 'xxx' } 结构就好~
> > > 假如你是想做低代码组件，包含生命周期、内部数据对象、动作绑定，一时半会说不清，可以关注下 @eternalsky 的 GMTC 演讲~
> > 
> > 
> > 怎么做低代码组件啊，有没有demo可以参考下，我想实现把自定义组件拖拽到编辑器里，然后上面有一个“拖拽组件或模板到这里”的功能
> 
> https://parts.lowcode-engine.cn/home

造物平台啊，我开始用过，后来因为公司网络安全原因，就开始学习其他方式的自定义物料了，在这过程中，有接触到https://github.com/alibaba/lowcode-materials，但是插槽功能一直没有找到怎么实现的
