### ISSUE TITLE
ant物料布局组件，col列宽度拖动的问题。

### ISSUE THREAD

**Issue by elaineKuo** [alibaba/lowcode-engine#632]
## **Describe the bug (required)** / **详细描述 bug（必填）**

加载antd的物料，拖拽一个“两栏的布局组件”；选中组件后，拖拽右侧蓝色的框，改变col的宽度。setter里面占位格数会NAN；

请问如果实现【alifd_pro-layout布局组件中】，拖拽col后，可以改变col的固定宽度。

是否是应该在定义组件meta信息时，拦截画布中的拖拽事件？怎么拦截？

![image](https://user-images.githubusercontent.com/13790374/173072395-dbbcbca9-28a6-48af-af72-0853bc080943.png)

![image](https://user-images.githubusercontent.com/13790374/173072290-ea6483f8-3d93-428b-ba82-3106a43d3788.png)

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by hujiulong** [comment]
我这周内修复

**Comment by hujiulong** [comment]
我试了下，没复现出来，你在这个地址看看是不是还有你说的问题：https://alifd.alicdn.com/npm/@alilc/antd-lowcode-materials@1.0.7/build/lowcode/index.html

> 请问如果实现【alifd_pro-layout布局组件中】，拖拽col后，可以改变col的固定宽度。
是否是应该在定义组件meta信息时，拦截画布中的拖拽事件？怎么拦截？

需要在 meta 中定义 resize 相关的配置，可以看看这里：https://github.com/alibaba/lowcode-materials/blob/4a80e3d76e1306c2bdbbb82eb0cc191ebbd5c695/packages/antd-lowcode-materials/lowcode/grid.col/meta.ts#L58
