### ISSUE TITLE
antd组件  求助  穿梭框分页功能的使用  数据的分页数量如何绑定，还是没有这个选项

### ISSUE THREAD

**Issue by 15163789836** [alibaba/lowcode-engine#633]
## **Describe the bug (required)** / **详细描述 bug（必填）**
创建穿梭框 选择分页样式设置 穿梭框底部就会出现分页 如何像给表格的分页一样绑定 可不可以绑定每一页展示的数据条数和数据总量

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
穿梭框底部就会出现分页 如何像给表格的分页一样绑定 可不可以绑定每一页展示的数据条数和数据总量
---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
创建穿梭框 选择分页样式设置 穿梭框底部就会出现分页 如何像给表格的分页一样绑定 可不可以绑定每一页展示的数据条数和数据总量

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为
使用穿梭框 分页，每页展示10条 点击页数切换数据

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

选择分页样式设置
![image](https://user-images.githubusercontent.com/104408070/173174973-e751256c-a169-4a3a-a8e3-87dd2e344efe.png)
分页器 就会展示出来
![image](https://user-images.githubusercontent.com/104408070/173174978-43f8bfe9-bdcd-401e-8fc3-e0cadf2468f6.png)
如何绑定展示数据条数和数据总量
---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by hujiulong** [comment]
升级 @alilc/antd-lowcode-materials 到 1.0.7 ，加上了分页的详细配置

**Comment by 15163789836** [comment]
> 升级 @alilc/antd-lowcode-materials 到 1.0.7 ，加上了分页的详细配置
现在是我 把数据绑定 设置每页条数 然后穿梭框自动根据数据的总量和我设置的每页展示条数  做出分页对吧，我可不可以通过像表格分页那种方法 拿到我选择的页数去请求接口拿数据 做分页 ,现在这样 后端做的带分页的接口  就在穿梭框离不能用了
