### ISSUE TITLE
antd 组件 穿梭框选项  取消到最后一个  会取消不掉了  

### ISSUE THREAD

**Issue by 15163789836** [alibaba/lowcode-engine#634]
## **Describe the bug (required)** / **详细描述 bug（必填）**
穿梭框选项  数据  取消到最后项  选项会取消不掉了  
A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
使用穿梭框 添加数据  先选取数据  再取消选取  会剩下最后一项取消不掉

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

选取数据  然后取消选取  都能取消掉
---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
选取多条数据
![image](https://user-images.githubusercontent.com/104408070/173175140-bdf1982d-0470-41dd-97df-89945b30eedb.png)
取消数据的选取
![image](https://user-images.githubusercontent.com/104408070/173175176-8e5a11e1-845f-41d3-b58f-8a07a2ae7d0f.png)
最后一项是取消不掉的

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.6] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by hujiulong** [comment]
升级 @alilc/antd-lowcode-materials 到 1.0.7 试试
