### ISSUE TITLE
Mac测试可以跑起来，win不行，npm run setup有问题？

### ISSUE THREAD

**Issue by lijiaxu1996** [alibaba/lowcode-engine#64]
Lerna各种环境可以正常安装，但是一运行npm run setup就报错，我看了脚本命令都是mac/linux下的命令，需要怎么改那个scripts/setup.sh的命令呀
文档说的**WSL**怎么用呀，低版本的win就一定不能跑了嘛

**Comment by LeoYuan** [comment]
readme 里有 WSL 链接~

使用引擎 cdn 文件不需要 mac，开发目前只能支持 mac 了（关键我们这也没人有 win，没法调试问题😄）

**Comment by LeoYuan** [comment]
可能没那么简单，sh / bat 据我有限的了解，差别比较大，比如路径分隔符等~

两个建议：
1. 用 win 下的高级终端；
2. 探索一下，提 PR 支持 win 的普通终端；

**Comment by lijiaxu1996** [comment]
> 可能没那么简单，sh / bat 据我有限的了解，差别比较大，比如路径分隔符等~
> 
> 两个建议：
> 
> 1. 用 win 下的高级终端；
> 2. 探索一下，提 PR 支持 win 的普通终端；

好滴 好滴

**Comment by lijiaxu1996** [comment]
**对于win的几点办法：**

1. 使用wsl，前提是外网，可以下载配置wsl，我目前用的内网，不行。
2. 在测试服务器上安装node，把开发环境迁移到测试环境，使用vscode远程连接服务器开发（目前可以使用）
3. 自己编写脚本，还在学习研究中.......

**Comment by enjoyWeb** [comment]
遇到这个错误是为啥呀，依赖我都装好了的呀，我是window系统
`setup.sh: line 7: lerna: command not found`
