### ISSUE TITLE
onAddNode 触发事件，回调的Node参数不正确

### ISSUE THREAD

**Issue by leehomeok** [alibaba/lowcode-engine#643]
Describe the bug (required) / 详细描述 bug（必填）
A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
拖入了一个Filter组件， 触发的回调函数 的参数是Filter组件的children最后一个 child, FormInput

To Reproduce (required) / 如何复现 bug？（必填，非常重要）
Steps to reproduce the behavior: / 详细复现步骤：
鼠标hover到输入框，点击高级表单

Expected behavior (required) / 预期行为（必填，非常重要）
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为
触发回调的参数返回正确的Node

Screenshots (optional) / bug 截图（可选）
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
![image](https://user-images.githubusercontent.com/13464485/173506259-c657d083-f16e-4361-b2c2-602c5313276b.png)

Environments (please complete the following information) (required): / 请提供如下信息（必填）
AliLowCodeEngine version: [e.g. 1.0.5] / 低代码引擎版本
AliLowCodeEngineExt version: [e.g. 1.0.3] / 低代码引擎扩展包版本
Browser [e.g. chrome, safari] / 浏览器版本 chrome 100
materials / plugins / tools / 其他物料 / 插件 / 工具链版本

另外 还有onAddNode 事件的触发时机也有问题，麻烦帮忙解决一下，谢谢
https://github.com/alibaba/lowcode-engine/issues/438

**Comment by LeoYuan** [comment]
具体啥问题？

**Comment by leehomeok** [comment]
> 具体啥问题？

就是onAddNode的回调函数 应该回调的node 是Filter,但是 我打了断点查看，实际回调的是Filter =>children的 last child , FormInput

**Comment by LeoYuan** [comment]
应该是整颗Filter，包括子节点都新增了吧
