### ISSUE TITLE
数据源开启排序后直接完成被清空

### ISSUE THREAD

**Issue by sundi78634** [alibaba/lowcode-engine#650]
## 复现截图
<img width="347" alt="image" src="https://user-images.githubusercontent.com/13900729/173758226-9e8f6a91-4452-4dcc-8cdf-3ee7bd592704.png">

<img width="344" alt="image" src="https://user-images.githubusercontent.com/13900729/173758273-d038289e-70d1-4c20-aa61-3f0ab8865e67.png">

<img width="340" alt="image" src="https://user-images.githubusercontent.com/13900729/173758298-00d0afa1-cac1-411f-a3d6-e7d9e0024214.png">

## 复现流程与链接

1. 数据源面板点击“排序”。
2. 点击“完成”。
3. 数据源被清空；排序后结果正常。

## 期望结果

数据源无变化。

## 环境信息

- 引擎版本 1.0.8
- ext 版本 1.0.3
- 物料
  - moment﹫2.24.0
  - lodash
  - iconfont-icons
  - ﹫ant-design/icons﹫4.7.0
  - antd﹫4.19.5
  - ﹫alifd/next﹫1.23.0
  - ﹫alilc/lowcode-materials﹫1.0.3

**Comment by LeoYuan** [comment]
@xingmolu 鉴定一下哈~

**Comment by twinkle77** [comment]
这个问题无法复现了，应该是被修复了
