### ISSUE TITLE
自定义的物料组件不发布到npm上怎么集成到lowcode-demo里

### ISSUE THREAD

**Issue by Ronchan0805** [alibaba/lowcode-engine#653]
如题

**Comment by liujuping** [comment]
lowcode-demo 实际上需要的是一个 cdn 地址，这个 cdn 地址获取的方式可以自己进行处理即可。

**Comment by Ronchan0805** [comment]
![image](https://user-images.githubusercontent.com/74052977/173981303-62c9fa6a-1751-4a11-9215-74e3b49d931a.png)
![image](https://user-images.githubusercontent.com/74052977/173981408-49a79fea-41f2-439b-be53-e95e26b9a332.png)
额，我还是不太明白您的意思。我用@alilc/element 脚手架构建出来的assets-prod.json是这个,您的意思是指在我把他 merge 到项目的 assets.json 之前先替换这些[http](https://unpkg.com)开头的地址是吗

**Comment by LeoYuan** [comment]
https://lowcode-engine.cn/docV2/ulvlkz#Ioc87
这个不香么？

**Comment by Ronchan0805** [comment]
我目前的解决办法是把自定义物料组件的产物（脚手架运行npm run lowcode:build的产物）放到官方的lowcode-demo工程里，在assets.json中修改https开头的网络路径为本地资源的相对路径，路径地址就是自定义物料组件构建的产物。相当于把自定义组件物料放在本地工程静态资源项目里。
