### ISSUE TITLE
选项卡出码错误

### ISSUE THREAD

**Issue by panxiao1** [alibaba/lowcode-engine#661]
# 项目中拖入选项卡
![image](https://user-images.githubusercontent.com/22336563/174038850-9f45e1bf-e7aa-4c8c-8169-251e57135804.png)
![image](https://user-images.githubusercontent.com/22336563/174038897-ddd6b829-8301-428e-986a-9e4235dc3bf4.png)
# 点击出码按钮
![image](https://user-images.githubusercontent.com/22336563/174038987-f7219e13-66cb-4092-85c1-9ed38c6aa463.png)

**Comment by LeoYuan** [comment]
@Clarence-pan 有空可以帮忙看看~

**Comment by Clarence-pan** [comment]
这个是 assets 的定义有问题   对于 `Tab.Item` 这种子组件应该将 componentName 定义成`TabItem` 这样子 -- componentName 需要是一个有效的 JS 标识符

![image](https://user-images.githubusercontent.com/8750132/174516868-d6fe3e73-6924-484d-a45c-124005d00dc6.png)

https://lowcode-engine.cn/lowcode#22-%E7%BB%84%E4%BB%B6%E6%98%A0%E5%B0%84%E5%85%B3%E7%B3%BBa

**Comment by LeoYuan** [comment]
https://github.com/alibaba/lowcode-materials/pull/51

**Comment by LeoYuan** [comment]
后面跟进 #961 吧，本 issue 将关闭~
