### ISSUE TITLE
使用antd组件如何使用Form.create创建表单

### ISSUE THREAD

**Issue by zhoulisuper** [alibaba/lowcode-engine#670]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by hujiulong** [comment]
你是指 antd 的低代码物料吗，低代码物料基于 antd 4，没有 Form.create 这个 API 了

**Comment by zhoulisuper** [comment]
如何在js代码中获取到antd中的form实例？

**Comment by hujiulong** [comment]
> 如何在js代码中获取到antd中的form实例？

可以设置 ref，Form 组件有这个配置，然后在代码面板中就可以通过 `this.$('ref')` 来获取 form 实例

**Comment by zhoulisuper** [comment]
<img width="1848" alt="image" src="https://user-images.githubusercontent.com/15810063/174700103-bfa646bc-96aa-40cd-841d-3be034682a31.png">
使用antd基础场景 似乎没有设置ref的入口

**Comment by hujiulong** [comment]
> 使用antd基础场景 似乎没有设置ref的入口

这个例子用的不是最新的物料库，你可以看看这个：https://alifd.alicdn.com/npm/@alilc/antd-lowcode-materials@1.0.8/build/lowcode/index.html

![image](https://user-images.githubusercontent.com/13267437/174740964-a3e901ed-0a14-4c8f-8dcd-7ec67f09033f.png)
