### ISSUE TITLE
首次加载正常，切换路由重进后，拖拽组件到画布后松开后没有反应。

### ISSUE THREAD

**Issue by xiyuanwang** [alibaba/lowcode-engine#673]
首次初始化引擎，能正常使用，但当切换路由（我用的hashrouter）后，退回上一页，然后再次打开页面（设置了flag不重复加载插件），设计器可以渲染出来（大概率，非必现），但是，当拖拽组件，到画布时，右侧的设置器感应不到组件，此时，鼠标在画布上松开后，组件无法添加到Node树上，视觉上看不到任何改变。

AliLowCodeEngine  v1.0.8 
AliLowCodeExt  v1.0.3 

看到已经有一些issue和本问题类似，都是希望提供一键（一个api）清除方法（目前已尝试在页面返回时进行各种清理尝试，包括删除current document、插件等）。

看官方 demo 切换组件库时都是会relaod页面的，所以，也准备试试 reload，但是做法比较恶心，希望能有更好的解决方案。

**Comment by LeoYuan** [comment]
可以给个可以复现的 demo，我尝试定位 & 优化一下~
