### ISSUE TITLE
NextTable和ProTable出错

### ISSUE THREAD

**Issue by woodrow-wang** [alibaba/lowcode-engine#677]
## **Describe the bug (required)** / **详细描述 bug（必填）**

使用 NextTable 和 ProTable 出码报错

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1. 从官方的demo(https://lowcode-engine.cn/demo/index.html)(clone到本地的demo一样);
2. 如果使用了NextTable或者ProTable;
3. 出码后解开zip文件，进入目录;
4. yarn(或者npm install);
5. npm start报错，报错信息参见截图:

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

用官方demo出一个基本的页面，以进行评估；

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

![lc1](https://user-images.githubusercontent.com/1477560/174519850-d7e5aa5c-f376-489c-9278-6231e9c17e5b.png)

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本      官方Demo使用版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本     官方Demo使用版本
 - Browser [e.g. chrome, safari] / 浏览器版本      chrome（97.0.4692.99）
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本 官方Demo使用版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by 699Felix** [comment]
同样遇到该问题

**Comment by markdashi** [comment]
+1

**Comment by aleadag** [comment]
+1, the same problem

**Comment by markdashi** [comment]
这是来自QQ邮箱的假期自动回复邮件。
 
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
