### ISSUE TITLE
出码后 zip文件package.json有bug 随手提一下

### ISSUE THREAD

**Issue by baiheinet** [alibaba/lowcode-engine#68]
**Screenshots** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

![4RqTkW4z8O](https://user-images.githubusercontent.com/900786/156491634-d1e3ff8a-1fb0-4940-813d-bf102e6d658e.png)

**Comment by Clarence-pan** [comment]
麻烦提供下您的 schema JSON 和复现方法

**Comment by baiheinet** [comment]
![image](https://user-images.githubusercontent.com/900786/156569997-1b2f61d2-cf90-414e-9a47-a351664c317e.png)

**Comment by Clarence-pan** [comment]
@baiheinet 麻烦您提供下相关的 Schema 吧（JSON 文件）或者直接将出码生成的源代码 zip 包附在此 issue 中吧

我这边基于 [lowcode-demo](https://github.com/alibaba/lowcode-demo) 这个项目尝试复现了下，发现没有出现 "{{version}}" 的问题

至于 `@ali/build-plugin-ice-def` 这个依赖已经在 @alilc/lowcode-code-generator@1.0.2-beta.1 中去掉了
