### ISSUE TITLE
物料编辑态开发在画布侧无法正常显示

### ISSUE THREAD

**Issue by Ewall1106** [alibaba/lowcode-engine#680]
## **Describe the bug (required)** / **详细描述 bug（必填）**

物料编辑态开发的代码在画布侧无法正常显示，显示的还是`src/index.tsx`中的内容。

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1. 官方脚手架init一个物料
2. 新建一个`view.tsx`文件用于编辑态开发

<img width="274" alt="image" src="https://user-images.githubusercontent.com/11911766/174538360-a2e5dc0b-16cb-40cc-a77e-5ced8719d7c8.png">

3. 重新执行 `npm run lowcode:dev`
4. 画布侧展示的还是`src/index.tsx`中的内容，而非`view.tsx`中的内容。
---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

希望画布侧展示`view.tsx`编辑态的内容。

---

## **Screenshots (optional)** / **bug 截图（可选）**

![image](https://user-images.githubusercontent.com/11911766/174539033-e5a3ab80-654b-4184-996b-0db0577fb237.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**

<img width="412" alt="image" src="https://user-images.githubusercontent.com/11911766/174539171-5e37bc74-0778-4635-a902-f6784a02a2fb.png">

**Comment by LeoYuan** [comment]
@mark-ck 是不是物料调试不支持这个能力？没有直接设置 editUrls？

**Comment by mark-ck** [comment]
@JackLian 这是支持的
