### ISSUE TITLE
如何在源码js部分引用antd的组件

### ISSUE THREAD

**Issue by zhoulisuper** [alibaba/lowcode-engine#683]
<img width="617" alt="image" src="https://user-images.githubusercontent.com/15810063/174550991-c2129386-598d-4fd5-a45d-140142a881b1.png">

**Comment by zhoulisuper** [comment]
目前报未定义Tag 异常

**Comment by hujiulong** [comment]
这里的代码不会有 bundler 处理，所以 import 是没用的，如果你确定页面中引入了 antd，可以改成这样
```js
getTable() {
  const { Space, Table, Tag } = window.antd;
  // 你的代码
}
```
