### ISSUE TITLE
如何创建低代码业务组件

### ISSUE THREAD

**Issue by dzlhk** [alibaba/lowcode-engine#684]
想尝试创建。低代码业务组件（Low-Code Business Component），
以及想实现拖拽区块（Block）到编辑器中（有完整的事件、生命周期管理、状态管理、数据流转机制等）可以与本来页面已经存在的schema 进行合并，比如 函数和状态管理，可以直接加入到本来的页面容器中

查看了大部分，文档，暂未发现这块实现的参考方式。
这里可以请教下，有哪些有意义的参考文档或者项目么？谢谢🙏

**Comment by JackLian** [comment]
目前还没有相关的资料，预计8月份GMTC上会有专门的讲解，会后也会有ppt资料可以下载，自行实现的话建议参考官网协议中的定义，配合阅读render部分源码

**Comment by jiamengnan** [comment]
> 想尝试创建。低代码业务组件（Low-Code Business Component）， 以及想实现拖拽区块（Block）到编辑器中（有完整的事件、生命周期管理、状态管理、数据流转机制等）可以与本来页面已经存在的schema 进行合并，比如 函数和状态管理，可以直接加入到本来的页面容器中
> 
> 查看了大部分，文档，暂未发现这块实现的参考方式。 这里可以请教下，有哪些有意义的参考文档或者项目么？谢谢🙏

请问大佬实现了吗？我也遇到了这个问题，想参考下思路~~

**Comment by eternalsky** [comment]
可以参考 GMTC 北京站 LowCodeEngine 相关的分享，体验低代码组件，可以访问 parts 造物来体验。

**Comment by Osub** [comment]
parts 造物 开源了吗？想参考一下整个流程

**Comment by JackLian** [comment]
> parts 造物 开源了吗？想参考一下整个流程

造物不开源的
