### ISSUE TITLE
类似宜搭的表单设计器请问有开源出来吗

### ISSUE THREAD

**Issue by alvin0216** [alibaba/lowcode-engine#687]
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/34113677/174704155-cec557da-077a-41df-892d-157ee7558b4e.png">

地址 https://www.aliwork.com/workPlatform

**Comment by JackLian** [comment]
已开源的能力在demo中可见，宜搭是商业产品，在引擎之上叠加了相当多的东西
