### ISSUE TITLE
assets中components和componentList的使用问题

### ISSUE THREAD

**Issue by SteveCGC** [alibaba/lowcode-engine#688]
## **Describe the bug (required)** / **详细描述 bug（必填）**

目前看到官方的demo中的assets.json中component有两种声明方式
1. components配合sort, 但components都是RemoteComponentDescription
2. componentList，但也有components，但components不生效，删除后不影响

想用components配合sort, 但components是ComponentDescription类型的，就无法正确入料，请问现在无法使用这种方式吗？

**Comment by mark-ck** [comment]
components + sort 应该是可以用的，不过只能对组件面板的 tab 和 category 进行排序，没办法精确到组件的排序
