### ISSUE TITLE
目前看到的schema示例和物料都是基于class组件，有考虑过使用函数组件作为物料的场景吗

### ISSUE THREAD

**Issue by Vision-Tang** [alibaba/lowcode-engine#69]

**Comment by JackLian** [comment]
函数组件也是支持的哈

**Comment by Vision-Tang** [comment]
有对应的文档链接吗

**Comment by liujuping** [comment]
可以根据文档创建一个物料，默认的物料示例就是函数组件。

**Comment by Vision-Tang** [comment]
看到物料是可以基于函数组件，但schema还是用类组件的规范，这会不会导致一些问题
比如子组件（函数组件）使用useImperativeHandle暴露出来的内部方法，在父组件（类组件）当中无法获取到

**Comment by liujuping** [comment]
低代码平台的物料都是由自己控制的，这时候可以选择都使用函数组件或者都使用类组件。函数组件和类组件混用的情况下，的确无法使用一些特定的 hook 方法，但是这个是低代码引擎无法控制的。

schema 的规范主要是基于类的规范，函数组件其实也是类组件的一种语法糖，所以在使用上是没有区别的。一些新特性的 hook 很可能不支持，这种可以针对性提供一下 issue，内部会对 schema 的规范进行提案、修改等。
