### ISSUE TITLE
全局表单容器如何设计呢？

### ISSUE THREAD

**Issue by alvin0216** [alibaba/lowcode-engine#690]
如图（宜搭）：无论拖入什么物料，都是在表单容器里面

![image](https://user-images.githubusercontent.com/34113677/174739579-c013ba17-f295-47ad-a606-0c4d4a58fb0e.png)

而就算我拖了容器进来

<img width="1090" alt="image" src="https://user-images.githubusercontent.com/34113677/174739904-c1351019-5b8a-40e4-89d2-b98b20df326b.png">

这是怎么配置的呢？顶级不是 Page 而是 XForm，我这里的需求是做一个表单设计器，类似宜搭

<img width="1439" alt="image" src="https://user-images.githubusercontent.com/34113677/174740203-6b5c1f82-c0b8-410c-b81e-714cd5d8beed.png">

**Comment by JackLian** [comment]
方案1: 自定义Page组件，方案二，改造大纲树面板，将表单容器作为根节点展示

**Comment by wulucxy** [comment]
@JackLian 如何自定义 Page 组件？
