### ISSUE TITLE
服务端出码，直接报solutions 未定义

### ISSUE THREAD

**Issue by azzg** [alibaba/lowcode-engine#693]
## **Describe the bug (required)** / **详细描述 bug（必填）**
使用官网示例代码进行服务器端出码，运行时，直接报solutions 未定义，官方代码如下：
![image](https://user-images.githubusercontent.com/15156146/174745229-31f32897-797f-46e5-adb5-ae18e7a20156.png)

本地代码如下：
![image](https://user-images.githubusercontent.com/15156146/174745558-9167c4d4-d9a8-4761-a178-848fb5366dd7.png)

![image](https://user-images.githubusercontent.com/15156146/174745660-b9ded735-8660-4fb0-8903-f152b6218fc6.png)

**Comment by Clarence-pan** [comment]
![image](https://user-images.githubusercontent.com/8750132/174748029-35c7d183-9940-4f2b-abe3-704494b9284f.png)

node v16.x 对于 default 导出的处理有点奇怪，如上图  
也可能是 esbuild 对于 default 导出处理得有些bug

**Comment by azzg** [comment]
哪个版本的node可以正常调用服务器端出码的代码呢

**Comment by Clarence-pan** [comment]
@azzg 可以尝试别用 "type": "module" 这种模式，使用传统的 require 的方式应该是好的（可以考虑使用 babel 来将 import 转换为 require）

**Comment by sundi78634** [comment]
@alilc/lowcode-code-generator@1.0.6 遇到了同样的问题，有解决办法吗

**Comment by Clarence-pan** [comment]
使用require方式引入应该不会报错的

**Comment by sundi78634** [comment]
@Clarence-pan 能否提供一份环境信息？Node版本14.19.0，使用require引入一样的报错。

**Comment by sundi78634** [comment]
看了下源码，solutions是默认导出，引入后从default下取值就可以了。
使用ESM和CommonJS都可以

**Comment by tony574273719** [comment]
const CodeGenerator = require('@alilc/lowcode-code-generator');

const lowcodeGenerate = async (schema) => {
    const projectBuilder = CodeGenerator.default.solutions.icejs();
    const project = await projectBuilder.generateProject(
        schema, // 编排搭建出来的 schema
    );
    // 写入磁盘
    await CodeGenerator.default.publishers.disk().publish({
        project, // 上一步生成的 project
        outputPath: '/path/to/your/output/dir', // 输出目录
        projectSlug: 'your-project-slug', // 项目标识
    });
}

**Comment by LeoYuan** [comment]
这个问题本质上是在 CommonJS/CJS 和 ESM 混用时，如何处理 export default 的问题~

在常见的转译器，比如 typescript compiler / webpack，都有相应的机制去抹平处理 CJS / ESM 的差异，比如 ts 是 [esModuleInterop](https://www.typescriptlang.org/tsconfig#esModuleInterop)，webpack 是[默认支持](https://webpack.js.org/concepts/modules/#supported-module-types)。

假如没有用到以上，那就只能自己 require('@alilc/lowcode-code-generator').default 了~
