### ISSUE TITLE
开发物料组件时，如何指定属性对应的设置器

### ISSUE THREAD

**Issue by zhoulisuper** [alibaba/lowcode-engine#695]
<img width="483" alt="image" src="https://user-images.githubusercontent.com/15810063/174761835-7209ca9a-ee48-42cb-b664-b15492ab29cc.png">
 如图所示 如何指定 value 为一个StringSetter
 color 为一个StringSetter

**Comment by sundi78634** [comment]
物料有对应的meta配置文件，指定setter componentName即可。可参考[lowcode-materials](https://github.com/alibaba/lowcode-materials)。

**Comment by Ronchan0805** [comment]
> 问题一：如果修改meta配置文件 重新编译后会将meta文件覆盖 问题二：如何设置对某个组件meta文件进行编译 目前设置build.lowcode.js 中noParse: false属性，针对的是整个物料库

我发现meta文件仅会在第一次编译自动生成 ，后续的增删改都不会更新meta文件（我用的是官方提供的那个脚手架）。可以将meta.ts拆分成几个部分，将属性那部分配置项通过导入导出放到组件里面来维护

**Comment by zhoulisuper** [comment]
👍
