### ISSUE TITLE
 <ReatRender>可以接受appHelper      当我是用init()方法，这个时候怎么把apphelper传到编辑态的ReactRender组件

### ISSUE THREAD

**Issue by heyicheng** [alibaba/lowcode-engine#696]

**Comment by twinkle77** [comment]
```
import { config, plugins, common, skeleton } from '@alilc/lowcode-engine'
import appHelper from './appHelper'

await registerPlugins()

config.setConfig({
  requestHandlersMap: appHelper.requestHandlersMap,
  appHelper: { // 传给编辑态的 appHelper
    constants: {
      ...appHelper.constants,
    },
    utils: {
      ...appHelper.utils,
    },
  },
  enableCondition: true,
  enableCanvasLock: true,
  supportVariableGlobally: true,
  simulatorUrl: simulatorAssets,
})

await plugins.init(preference)
```

**Comment by heyicheng** [comment]
<img width="580" alt="image" src="https://user-images.githubusercontent.com/30236583/174930450-a7f7b415-724e-487e-84a3-7527f953da3e.png">
<img width="773" alt="image" src="https://user-images.githubusercontent.com/30236583/174932555-a6b7a7ef-866f-453c-b6d9-6f3a4c8dd717.png">
已经有appHelper但是在ReactRender中还是没有啊
<img width="1698" alt="image" src="https://user-images.githubusercontent.com/30236583/174932673-020494d7-d7c6-42cf-8cda-58231846bc30.png">

**Comment by LeoYuan** [comment]
试一下 1.0.11 版本~
