### ISSUE TITLE
物料(element-material)环境问题

### ISSUE THREAD

**Issue by toviLau** [alibaba/lowcode-engine#70]
---------- 物料(element-material)环境问题 ----------
出现的 version 0.1.0

1. npm install 没有安装 fie 
package.json 的 devDependencies 下没有 fie 的列表信息  是需要手动全局安装么?

2 npm start启动项目
提示:
/bin/sh: tnpm: command not found
手动安装 tnpm后 再次运行
提示
[core-error] 运行插件或套件时出现了错误, 未找到 @ali/fie4-plugin-component 模块! 正在尝试自动修复...
 npm库里我也没有搜到相关包的信息

**Comment by toviLau** [comment]
os: macos 12.2.1
node: v14.17.0
npm: 6.14.13

**Comment by LeoYuan** [comment]
如何复现呢？麻烦把复现步骤写一下

**Comment by toviLau** [comment]
稍后 我再重新clone初始化一下 再试下

**Comment by toviLau** [comment]
环境描述
os: macos 12.2.1
node: v14.17.0
npm: 6.14.13 (--registry=https://registry.npm.taobao.org)

重现步骤
1 npm init @alilc/element element-material
 请选择引擎生态元素类型 > 组件/物料 > 跨端-多包模式

2 cd element-material

3 npm install
(以上步骤正常)

4 npm start --> 报错如下
sh: fie: command not found

于是我查看了package.json文件
在 devDependencies 与 dependencies 都没有找到 fie 的列表的相关信息
请问这个是需要手动全局安装么?
----------------------------------------- 优雅分隔线 ----

尝试: 
我手动全局安装 fie
npm i -g fie
npm start

报错:
/bin/sh: tnpm: command not found

再次尝试: 
手动全局安装 tnpm
npm i -g tnpm
npm start

报错
[core-error] 运行插件或套件时出现了错误, 未找到 @ali/fie4-plugin-component 模块! 正在尝试自动修复...
----------------------------------------- 优雅分隔线 ----

去 npmjs.org --> search package..
我也没有搜到相关包的信息

**Comment by toviLau** [comment]
@LeoYuan @mark-ck

**Comment by mark-ck** [comment]
fixed
