### ISSUE TITLE
节点操作项

### ISSUE THREAD

**Issue by xiaoqian-GUO** [alibaba/lowcode-engine#706]
如何根据不同的组件类型配置不同的节点操作项吗

**Comment by JackLian** [comment]
具体是什么场景，麻烦描述的更具体些，或者给出截图

**Comment by xiaoqian-GUO** [comment]
> 具体是什么场景，麻烦描述的更具体些，或者给出截图

具体的场景是：有一个场景是我们想默认在页面最顶层添加一个组件，但是这个组件是不可删除的，目前看的话，删除是默认配置的，并且不能单独根据某个组件的名称动态配置节点操作项
