### ISSUE TITLE
<ReatRender>可以接受appHelper , 当我是用init()方法，这个时候怎么把apphelper传到编辑态的ReactRender组件

### ISSUE THREAD

**Issue by heyicheng** [alibaba/lowcode-engine#707]
<img width="1152" alt="image" src="https://user-images.githubusercontent.com/30236583/175184735-fe91c39c-b49f-4786-83cd-fde258aee529.png">
<img width="1542" alt="image" src="https://user-images.githubusercontent.com/30236583/175184763-4cb34a9f-9f6e-4f32-85bb-57bfc9e8e3cd.png">
已经有appHelper但是在ReactRender中appHelper没有
<img width="1716" alt="image" src="https://user-images.githubusercontent.com/30236583/175184784-14abc703-1239-4998-897f-eef8b041e261.png">

**Comment by alvarto** [comment]
```
import { engineConfig } from '@ali/lowcode-engine'
engineConfig.setConfig({
  appHelper: {},
})
```
