### ISSUE TITLE
Transfer相关问题

### ISSUE THREAD

**Issue by mengyuhang4879** [alibaba/lowcode-engine#714]
问题1：底部渲染不能使用
  - 1 插槽插入
   - 点击前
   
![image](https://user-images.githubusercontent.com/39154179/175247109-930cef59-51a0-415d-bacf-c6c9a8a76700.png)

   - 点击后
![image](https://user-images.githubusercontent.com/39154179/175247257-f86c1c4e-0aa4-4b9c-9e0e-d33ec89f3c62.png)

  - 2 多选框标题合集（目前有问题）
![image](https://user-images.githubusercontent.com/39154179/175248070-4448d3f3-8a40-45ab-90fe-d534e597a1a1.png)

**Comment by hujiulong** [comment]
这看起来是个 bug ，我这周修复一下

**Comment by hujiulong** [comment]
@alilc/antd-lowcode-materials 1.0.9 版本已经修复
