### ISSUE TITLE
pro-layout能开源吗

### ISSUE THREAD

**Issue by SteveCGC** [alibaba/lowcode-engine#717]
pro-layout里面的行列容器很有用，非常灵活，目前要实现一个vue版本，所以想参考下源码，现在一点头绪都没有

**Comment by JackLian** [comment]
目前无明确开源计划

**Comment by ljmCoder** [comment]
行列容器的这种灵活的交互方式可以大概给些思路吗？ 我们也觉得很棒。 想实现一个类似的灵活的行列容器。非常感谢！
