### ISSUE TITLE
组件绑定自带事件中调用setState会报渲染异常

### ISSUE THREAD

**Issue by zhoulisuper** [alibaba/lowcode-engine#719]
form组件onfinish事件
table组件onTableChange/rowSelectionChange事件
以上方法中调用setState都会报循环渲染异常

代码
 //搜索列表
   onSearch(){
    this.setState({
      lastTimeSearchParams: { ...this.state.formData},
    })
    this.fetchList()
}

<img width="674" alt="image" src="https://user-images.githubusercontent.com/15810063/175452643-8c0706e8-87fc-4656-ab9a-bd514b3a0a72.png">

**Comment by JackLian** [comment]
请提供复现步骤或复现demo

**Comment by zhoulisuper** [comment]
demo文件可参考问题 734

**Comment by zhoulisuper** [comment]
[归档.zip](https://github.com/alibaba/lowcode-engine/files/8996805/default.zip)

**Comment by liujuping** [comment]
尝试了一下，没有复现。

可以点开 React 的链接，看一下具体错误的原因。也可以使用开发版本的 React 看一下详细的错误，辛苦先自查一下。

如果自查无法解决请提供更详细的复现步骤。比如 demo 的哪个场景，如何导入 schema 等。参考 https://www.yuque.com/lce/doc/yvlxhs
