### ISSUE TITLE
ArraySetter数据过多导致页面卡死

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#720]
场景：我的下拉选择器配置了ArraySetter和JsonSetter，我切换到JsonSetter然后塞入了800条数据，然后保存页面，重新进来的时候他自己切换到了ArraySetter导致页面卡死。

建议：优化此处为虚拟滚动？ or 记录当前用的是Setter是什么

**Comment by JackLian** [comment]
虽然不是我负责这块吧，但我比较好奇为啥setter里会塞800条数据这么多....能介绍下场景吗

**Comment by oneQiu** [comment]
> 虽然不是我负责这块吧，但我比较好奇为啥setter里会塞800条数据这么多....能介绍下场景吗

正常来说这种应该使用数据源功能的，但是用户没有后端服务什么的，我们现在也没做json文件托管，所以用户就塞了800选项。
数据源对于刚上手用户来说还是有成本的。

**Comment by JackLian** [comment]
那强烈不建议这么做，另外引擎并不是一个完整的低代码平台产品形态，需要你们自行建设成一个平台的，并不是直接给到想使用低代码平台的用户的，作品平台开发方就缺啥补啥就好了

**Comment by hzd822** [comment]
800多项建议使用插件来单独处理吧，arraysetter不适合做上百条的数据设置

**Comment by oneQiu** [comment]
Q2: 我把json文件上传到了阿里云上面，然后打算通过数据源的方式请求下来，但是发现居然跨域了，我阿里云配置了可跨域。同时如果我自己在源码面板里面通过js代码去fetch就没问题，想问下有什么区别吗？
![image](https://user-images.githubusercontent.com/50658231/175457586-9b642d03-e176-49cb-9491-5d4117421581.png)
![image](https://user-images.githubusercontent.com/50658231/175457659-12d3ad36-f0b7-4c2b-bd6f-655b82352537.png)

结果：
![image](https://user-images.githubusercontent.com/50658231/175457783-b8777285-50fd-48bd-9438-a4c85eeac8be.png)

![image](https://user-images.githubusercontent.com/50658231/175457721-eb1512da-a272-413e-bba8-1116911dd3eb.png)
