### ISSUE TITLE
antd Form默认值不生效

### ISSUE THREAD

**Issue by 329697166** [alibaba/lowcode-engine#727]
![5961d20e6a960114ade534615f8895c](https://user-images.githubusercontent.com/8613493/175550479-b750b94e-f00c-4874-beb6-b5a8a09a4b63.png)
![15ae335491492b4e1bfac05f7725436](https://user-images.githubusercontent.com/8613493/175550505-3586e0eb-223a-422d-897d-60807f9fd379.png)
通过schema发现antd Form组件的默认值字段是values但是antd Form的默认值字段应该是initialValues

**Comment by 329697166** [comment]
![image](https://user-images.githubusercontent.com/8613493/175551013-b32fe21a-d8dd-48da-8640-6ae84dff1c72.png)

**Comment by hujiulong** [comment]
我试了下，绑定数据源是生效的，从你的截图里看，你给的数据格式应该有问题，checkbox组件接收的是字符串数组。

`initialValues` 是我特意去掉的，因为它在搭建中使用会让使用者很疑惑，initialValues 只在初始化时生效，所以在搭建中设置了这个值，页面也不会有变化。
