### ISSUE TITLE
官方的fusion物料库项目，组件的功能不能正常使用

### ISSUE THREAD

**Issue by bingfenglengyan** [alibaba/lowcode-engine#730]
## **Describe the bug (required)** / **详细描述 bug（必填）**
官方提供的fusion物料库中的NextTabel组件，编辑功能和官网demo提供的不一致

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
1、下载官方提供的 fusion-lowcode-materials项目，安装依赖并运行
2、找到NextTable组件，并拖拽到画布中，会出现一堆warning
![image](https://user-images.githubusercontent.com/35730201/175844297-497bf0ac-0844-4cc7-a947-cb35c8904cb8.png)
3、点击组件中编辑按钮，并没有出现官网demo中的效果
![image](https://user-images.githubusercontent.com/35730201/175844419-3dfb0351-69fd-4036-acfc-78fdd9c32723.png)

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
点击编辑按钮，表格出现可编辑项，期望和官网demo一样的效果
![image](https://user-images.githubusercontent.com/35730201/175844487-b7df9175-4f68-4113-a38c-ddca8e724800.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
![image](https://user-images.githubusercontent.com/35730201/175844549-a444e016-084e-4563-925a-b3305ab9ed52.png)
![image](https://user-images.githubusercontent.com/35730201/175844568-6708c155-c8df-401b-8bb6-d6c48280c5ca.png)

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by mark-ck** [comment]
这个需要自己实现
