### ISSUE TITLE
openDocument中间画布无法oepn当前新创建的document

### ISSUE THREAD

**Issue by wangqin5436** [alibaba/lowcode-engine#732]
## **Describe the bug (required)** / **详细描述 bug（必填）**
多页应用需新增一个document ，project.openDocument 创建成功 ，中间画布无法oepn当前新创建的document。

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
1、自定义新增按钮点击时project.openDocument(newSchema)
2、当前project.exportSchema(TransformStage.Save) 可见已经有两个document
![image](https://user-images.githubusercontent.com/22440598/175887481-1dcd4785-5251-4c01-8876-7c4be35eb565.png)
3、zhong中间画布显示的还是第一个页面
![image](https://user-images.githubusercontent.com/22440598/175887673-9a2f6427-be77-4f47-a6c1-56a8621791f0.png)

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
点击新增页面，能创建并切换到新的页面
编辑完某个页面切换到页面时，project schema对应的document的schema为编辑后的schema

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
![image](https://user-images.githubusercontent.com/22440598/175888547-a61ef82e-1f32-4771-ae5b-34be12e9d9a9.png)

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
![image](https://user-images.githubusercontent.com/22440598/175888706-54e85c11-816e-44d8-a9b1-1d9f0afeda26.png)

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by LeoYuan** [comment]
明确一下问题：是不是从 doc A 切换到 doc B 成功，再从 doc B 切换不回来 doc A？

```
const curDoc = AliLowCodeEngine.project.currentDocument;
const lastDocId = curDoc.id;

// A -> B
AliLowCodeEngine.project.openDocument({ componentName: 'Page' });

// B -> A
AliLowCodeEngine.project.openDocument(lastDocId);
```

是这意思么？

**Comment by wangqin5436** [comment]
从 doc A 新增doc B并切换到 doc B 界面--->失败
// A -> B
AliLowCodeEngine.project.openDocument({ componentName: 'Page' });  还是显示curDoc的界面

**Comment by LeoYuan** [comment]
到底是第一步失败，还是第二步失败啊？

![image](https://user-images.githubusercontent.com/1195765/176084870-b6621d77-246f-4474-ba82-ea0dc7f670d4.png)
我这边 A -> B 是成功的，从 B 通过 openDocument(docIdOfA) 切回 A 才有问题~

**Comment by wangqin5436** [comment]
刚试了一下 ， A -> B 是成功的，是我之前的page schema是有问题的
从 B 切回 A 有问题

**Comment by LeoYuan** [comment]
试试 1.0.11 版本引擎~

**Comment by wangqin5436** [comment]
1.0.11 版本也不行呢

**Comment by LeoYuan** [comment]
给个demo项目，然后写出你的复现步骤，或者用我的代码试下？

**Comment by wangqin5436** [comment]
是按你提供的代码写的 ，没有成功切回去
