### ISSUE TITLE
react-renderer package schema 无法运行

### ISSUE THREAD

**Issue by wulucxy** [alibaba/lowcode-engine#733]
## **Describe the bug (required)** / **详细描述 bug（必填）**

目前场景想基于  react-renderer 支持 scheme 渲染。执行完`npm run setup` 之后，进入到 `react-renderer` 执行 `npm run start`，渲染结果异常。

![image](https://user-images.githubusercontent.com/5326403/176145099-845b48b6-969a-4e04-aa18-22639324d097.png)

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

English version example：
1. 执行 `npm setup`
2. `cd packages/react-renderer`
3. `npm start`

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

能够正常演示 ` react-renderer` demo

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by wulucxy** [comment]
补充：单独安装 `@alilc/lowcode-react-renderer` 无法跑通 官方提供的`https://github.com/alibaba/lowcode-engine/blob/main/packages/react-renderer/demo/schemas/dataSource.js` schema。

源码仓库地址：https://github.com/wulucxy/lowcode-engine-test/blob/main/src/config/schemas/dataSource.js

**Comment by wulucxy** [comment]
问题3：
https://github.com/alibaba/lowcode-engine/blob/main/packages/react-renderer/demo/schemas/list.js

list schema 不符合 [容器结构描述](https://lowcode-engine.cn/lowcode#233-%E5%AE%B9%E5%99%A8%E7%BB%93%E6%9E%84%E6%8F%8F%E8%BF%B0-a)，希望尽快修改

**Comment by wulucxy** [comment]
问题4：
https://github.com/alibaba/lowcode-engine/blob/main/packages/react-renderer/demo/schemas/list.js

和 [[lowcode-datasource](https://github.com/alibaba/lowcode-datasource)] 约定的 DataSourceConfig type 不符

**Comment by LeoYuan** [comment]
在根目录多执行一步 npm run build，否则找不到相关依赖包~

整个项目整体运行依赖没问题是因为 tsconfig paths 有相关重定向的配置，参考：https://github.com/alibaba/lowcode-engine/blob/develop/tsconfig.json

**Comment by LeoYuan** [comment]
> 问题3： https://github.com/alibaba/lowcode-engine/blob/main/packages/react-renderer/demo/schemas/list.js
> 
> list schema 不符合 [容器结构描述](https://lowcode-engine.cn/lowcode#233-%E5%AE%B9%E5%99%A8%E7%BB%93%E6%9E%84%E6%8F%8F%E8%BF%B0-a)，希望尽快修改

具体是哪？

**Comment by wulucxy** [comment]
@LeoYuan dataSource 缺少 list 结构，其理论上 dataHandler 应该包裹在 list 里面

**Comment by LeoYuan** [comment]
这个 issue 先关了吧，还未解决的问题麻烦重新提一下，尽量一个 issue 反馈一个问题哈~
