### ISSUE TITLE
预览/出码schema后，页面渲染异常；出码react组件页面正常渲染

### ISSUE THREAD

**Issue by zhoulisuper** [alibaba/lowcode-engine#734]
schema和packages文件 见附件
使用demo项目搭建页面，源码区域中如果调用setState，预览下控制台报渲染无限循环异常，页面交互不正确。componentDidMount中赋值也不生效。
出码成schema 然后使用schema运行页面，和预览情况一致；
出码成react组件，将组件运行，页面交互正常，数据加载正常
[归档.zip](https://github.com/alibaba/lowcode-engine/files/8990306/default.zip)

**Comment by zhoulisuper** [comment]
[归档.zip](https://github.com/alibaba/lowcode-engine/files/8990301/default.zip)

**Comment by liujuping** [comment]
1.无限循环异常

问题原因是在一些表达式中执行了 setState，目前 setState 会导致页面重新执行所有的表达式，执行表达式过程中调用 setState，进而导致无限循环。这个问题目前只能先在代码逻辑上避免一下，后面有了优化方案之后进行修复。

2.componentDidMount 中赋值不生效的问题已修复，https://github.com/alibaba/lowcode-engine/pull/898
