### ISSUE TITLE
关于 project - 模型 API 的疑惑与 bug

### ISSUE THREAD

**Issue by moling1234** [alibaba/lowcode-engine#738]
## **Describe the bug (required)** / **详细描述 bug（必填）**
1: 利用 createDocument（不带参数，不传 schema） 创建完一个 document 后发现它和正在打开的 document 配置一样
2: 利用 createDocument（参数，传 schema） 创建完一个 document 后无法利用 openDocument 切换到 刚才的document
3: 疑惑 documentmodel内的id 与 schema 的id是什么关系

---

Steps to reproduce the behavior: / 详细复现步骤：
1: 利用 createDocument（不带参数，不传 schema） 创建完一个 document 后发现它和正在打开的 document 配置一样
2: 利用 createDocument（参数，传 schema） 创建完一个 document 后无法利用 openDocument 切换到 刚才的document
3: 疑惑 documentmodel内的id 与 schema 的id是什么关系

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by LeoYuan** [comment]
@moling1234 

类似 #732 ，应该已经修复，你可以拉 develop 分支测试下，正式版本预计今天发布~

**Comment by moling1234** [comment]
> @moling1234
> 
> 类似 #732 ，应该已经修复，你可以拉 develop 分支测试下，正式版本预计今天发布~

明确一下问题，1: 首先创建有问题，不传参数创建的 document 会和正打开的 document 配置一样

**Comment by moling1234** [comment]
> > @moling1234
> > 类似 #732 ，应该已经修复，你可以拉 develop 分支测试下，正式版本预计今天发布~
> 
> 明确一下问题，1: 首先创建有问题，不传参数创建的 document 会和正打开的 document 配置一样
2: 无法切换到新创建的 document

**Comment by LeoYuan** [comment]
不如按照你预期的和实际的来写？
不传参你想要什么效果？
切换，你是如何切换的？把代码贴上来，这才是精确的复现步骤

**Comment by moling1234** [comment]
好的，下次按照要求提bug

**Comment by moling1234** [comment]
> 不如按照你预期的和实际的来写？ 不传参你想要什么效果？ 切换，你是如何切换的？把代码贴上来，这才是精确的复现步骤

好的，下次按要求提bug

**Comment by LeoYuan** [comment]
试试 1.0.11 版本引擎~

**Comment by LeoYuan** [comment]
请问 1.0.11 解决你的问题了吗？

**Comment by moling1234** [comment]
> 请问 1.0.11 解决你的问题了吗？
最近几天比较忙，还没有尝试，周末我尝试一下，下周一给到反馈结果

**Comment by moling1234** [comment]
> 请问 1.0.11 解决你的问题了吗？
最近几天比较忙，还没有尝试，周末我尝试一下，下周一给到反馈结果
