### ISSUE TITLE
请问如何给StyleSetter设置默认值?

### ISSUE THREAD

**Issue by yz1311** [alibaba/lowcode-engine#739]
## 复现截图
想给StyleSetter直接设置默认值，目前碰到一些问题，用snippets的方式，直接给style赋值是可以的，但是界面里面的占位视图会消失，
查询源码得到，这里对style有做判断，如果不为空，就直接不显示占位视图，请问这样做是为什么？那我如何能给StyleSetter设置默认值，并且保留占位视图?

## 复现流程与链接

![WX20220628-120308](https://user-images.githubusercontent.com/9854019/176089462-a3cf70d6-bacd-4dec-8ac8-cc250aa40270.png)

```
 {
          "componentName": "Column",
          "library": "LYMaterials",
          "title": "Column",
          "icon": "",
          "snippets": [
            {
              "title": "Column",
              "schema": {
                "componentName": "Column",
                "title": "Column",
                "props": {
                  "style": {
                    "display": "flex",
                    "flexDirection": "column"
                  }
                }
              }
            }
          ]
        },
```
![WX20220628-120211](https://user-images.githubusercontent.com/9854019/176089500-645bcae3-33fa-488b-8f64-971f60873e46.png)

这里有做判断
https://github.com/alibaba/lowcode-engine/blob/main/packages/react-simulator-renderer/src/renderer-view.tsx#L205

![image](https://user-images.githubusercontent.com/9854019/176089615-86a756cd-4f81-46f2-87c8-609516c75d8f.png)

## 期望结果

StyleSetter设置默认值，并且保留占位视图

## 环境信息

- 引擎版本 1.0.10
- ext 版本 1.0.4-beta.4
- 物料
  - moment﹫2.24.0
  - lodash
  - ﹫alifd/next﹫1.23.0
  - ly-materials﹫0.0.2-beta2
  - ﹫alifd/ali-lowcode-components﹫latest
  - bizcharts﹫4.1.11
  - ﹫alife/container﹫0.3.7

**Comment by LeoYuan** [comment]
可以通过在设计视图里，自定义占位符实现~

```
class YourComponent {
  render() {
    if (this.props.leaf.isEmpty) {
      return <div>空</div>;
    }
    return 其他视图;
  }
}
```
