### ISSUE TITLE
高级表单组件渲染异常

### ISSUE THREAD

**Issue by alexpdh** [alibaba/lowcode-engine#742]
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 新增页面；
3. 拖入高级表单组件，设置其中一个表单项的布局，将一列更改为四列；
![1](https://user-images.githubusercontent.com/16286355/176137500-dc661580-7a35-4e58-a8b7-c8ae6f3dc81c.png)
4. 选择高级表单，调整高级表单布局，从四列变为三列，浏览器crash，电脑CPU，内存被打满。
![3](https://user-images.githubusercontent.com/16286355/176137121-63c33b57-5b8e-4ec4-b980-ff04df542131.png)
![4](https://user-images.githubusercontent.com/16286355/176137356-fa527ac7-29ca-41dc-a676-894fb24ae8ef.png)

**Comment by mark-ck** [comment]
fixed
