### ISSUE TITLE
物料库def云构建失败

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#747]
本地构建能成功，但是在集团的def平台上面构建是有问题的。路径问题吗
![image](https://user-images.githubusercontent.com/50658231/176336179-28be7579-d848-4649-96e8-8ad130665398.png)

**Comment by JackLian** [comment]
可以找云构建的同学鉴定下

**Comment by oneQiu** [comment]
找过了，没发现问题，像是插件@alifd/build-plugin-lowcode的配置问题

**Comment by mark-ck** [comment]
看日志像是 @alifd/theme-1 没有加到 dependency 里？

**Comment by oneQiu** [comment]
但是我好像没用这个 @alifd/theme-1，关键是本地能构建成功。
