### ISSUE TITLE
内网环境自己新增一个物料，必须npm publish?

### ISSUE THREAD

**Issue by lijiaxu1996** [alibaba/lowcode-engine#75]
我内网想新增一个组件，必须npm publish嘛？还是必须我们内网也得同步一套淘宝最新的npm源呢？

**Comment by alvarto** [comment]
不必，通过资产包协议，您可以自由的声明任意当前网络环境可达的 URL 来引入资产包。资产包的要求只有一个，通过 UMD 方式打包，让低代码引擎可以读取到 `window[对应包名]`。

参考：https://github.com/alibaba/lowcode-demo/blob/main/public/assets.json

此部分物料文档我们将继续优化，感谢您的反馈。

**Comment by lijiaxu1996** [comment]
<img width="132" alt="image" src="https://user-images.githubusercontent.com/59685169/156911719-4154aa72-bf16-4e02-bba0-d5eec5c8fcd0.png">
我自定义的组件包如果想让引擎识别不是必须发布在fusion上吧

**Comment by alvarto** [comment]
不是。

**Comment by alvarto** [comment]
参考“低代码的生产和消费”章节：http://lowcode-engine.cn/doc?url=oduwl5

经过或者不经过物料中心，都是可以完成流程的。
