### ISSUE TITLE
布局容器拖拽改变宽度无效, 控制台报错

### ISSUE THREAD

**Issue by Tomatoro** [alibaba/lowcode-engine#754]
## **Describe the bug (required)** / **详细描述 bug（必填）**

designDemo之前的容器拖拽改变宽度的时候, 没有效果, 之前是可以的,是升级过版本??

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 顶部选择基础antd组件
3. 左侧布局里选择三栏, 四栏等
4. 拖拽中间组件的宽度
5. 控制台报错

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
可以正常拖拽, 改变宽度

---

## **Screenshots (optional)** / **bug 截图（可选）**
![image](https://user-images.githubusercontent.com/33597040/176586873-3523cfad-6327-44db-a47d-e59852c4ee44.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本
都是线上demo库的最新版

**Comment by JackLian** [comment]
线上最新demo没能复现，可以提供下可复现的操作步骤

**Comment by Tomatoro** [comment]
今天又试了下, 可以了又, 先关闭了
