### ISSUE TITLE
Tab 出码错误

### ISSUE THREAD

**Issue by sunjunqing2008** [alibaba/lowcode-engine#755]
failed to run code generator:  Error: Invalid Identifier [Tab.Item]

Tab 出码错误

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

![1656568990315](https://user-images.githubusercontent.com/20146948/176604078-e2b2a872-f7ec-46aa-b2c0-cf7b4e210ca5.png)

**Comment by JackLian** [comment]
https://lowcode-engine.cn/docV2/yvlxhs
