### ISSUE TITLE
如何限制Shema的children只能拖入一个组件

### ISSUE THREAD

**Issue by sbiweeq** [alibaba/lowcode-engine#756]
## **Describe the bug (required)** / **详细描述 bug（必填）**

如何限制Shema的children只能拖入一个组件

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
![image](https://user-images.githubusercontent.com/10651998/176620307-eb924528-e68b-4860-b924-691fdd6c7107.png)
如果已经有拖入子组件了,怎么限制只能不能再拖入其他

**Comment by otakuXv** [comment]
@sbiweeq 目前不支持限制子组件数量，可以选择自己写一个插件来实现
