### ISSUE TITLE
npm run lowcode:dev 运行正常，但是demo预览访问超时,多图如下

### ISSUE THREAD

**Issue by lijiaxu1996** [alibaba/lowcode-engine#76]
[**新增组件参考：**](https://www.yuque.com/lce/doc/funcv8#ehg7Q)
环境：
Mac：15.4
node & npm：
<img width="384" alt="image" src="https://user-images.githubusercontent.com/59685169/156913608-741b5801-13f7-4c3c-81e8-6d9c615b8dc6.png">
<img width="359" alt="image" src="https://user-images.githubusercontent.com/59685169/156913620-8b80b76a-dce5-4b90-878b-450055ea1ce5.png">

我的初始化目录如图：
<img width="1088" alt="image" src="https://user-images.githubusercontent.com/59685169/156913410-e77e2e59-1b41-47c7-b25f-44757aaa66e2.png">
<img width="1183" alt="image" src="https://user-images.githubusercontent.com/59685169/156913510-862a1672-3813-4ba6-9827-adbbdee19bd9.png">
<img width="1277" alt="image" src="https://user-images.githubusercontent.com/59685169/156913576-74bbb4d9-481e-4b1c-8c04-20881309a109.png">

**Comment by lijiaxu1996** [comment]
已解决~

**Comment by LeoYuan** [comment]
报错第二条是 engine-core.js 没有找到，url 是什么？

建议直接给一个可以复现的仓库~

**Comment by lijiaxu1996** [comment]
> 报错第二条是 engine-core.js 没有找到，url 是什么？
> 
> 建议直接给一个可以复现的仓库~

老哥，你的意思是直接在官方demo上面进行修改么，我是想自己编写源码组件，然后把它转化成低代码组件，但是不知道怎么操作，这个问题卡了两天了

**Comment by LeoYuan** [comment]
检查一下你的 engine-core.js 到底是哪个 url，理论上直接访问 cdn 肯定是没问题的，是不是你本地代理了？

再次声明，明确的写出你的复现步骤是最快解决问题的方式~

**Comment by lijiaxu1996** [comment]
好，我试试

**Comment by lijiaxu1996** [comment]
## **新增组件问题详细描述**

1. https://www.yuque.com/lce/doc/funcv8 我是参考这里的步骤进行新增组件的
2. 使用npm start的时候页面可以打开 
<img width="1267" alt="image" src="https://user-images.githubusercontent.com/59685169/157154506-cdc00280-5cec-4872-87b9-31702f40ae3d.png">
3. npm run lowcode:dev 的时候预览不了，确实是URL问题
<img width="789" alt="image" src="https://user-images.githubusercontent.com/59685169/157154680-8fd8c298-b161-434b-adf8-e18cc6a54d5f.png">
4. 我看页面里面使用的是cdn加载的方式，但是engine-core.js打不开,urldev开头的打不开
<img width="1205" alt="image" src="https://user-images.githubusercontent.com/59685169/157154819-972713b4-2710-4674-95ca-f4af39d5c2a1.png">
<img width="1160" alt="image" src="https://user-images.githubusercontent.com/59685169/157154881-11884984-5951-40db-83fa-29107afa0db1.png">
---

## **复现bug**
1. npm init @alilc/element my-table 
2. 选择pc-单包
3. cd my-table && npm i
4. npm start 可以正常访问
5. 运行 npm run lowcode:dev 出现问题了
6. 运行npm run lowcode:build 生成的designer.html里面查看engine-core.js的cdnURL访问不了
---


## 预期行为**
希望能够成功预览自己新增的组件，并能进行低代码拖拽操作

---


---

## **环境**
 - 1.0.1 / 低代码引擎版本
 - 98.0.4758.109（正式版本） (x86_64)
 -  node v14.18.1
