### ISSUE TITLE
lowcode-engine-1.0.11安装报错error An unexpected error occurred: "ENOENT: no such file or directory, copyfile '/usr/local/share/.cache/yarn/v6/npm-ansi-styles-3.2.1-41fbb20243e50b12be0f04b8dedbf07520ce841d-integrity/node_modules/ansi-styles/index.js' -> '/home/cmcc/lowcode/lowcode-engine-1.0.11/node_modules/@babel/highlight/node_modules/ansi-styles/index.js'"

### ISSUE THREAD

**Issue by cooper190113** [alibaba/lowcode-engine#763]
**安装环境：**
1、操作系统：centos7
2、node、npm、cnpm版本
![image](https://user-images.githubusercontent.com/851243/176981901-1ada7259-58e0-4229-b616-fc95d408a922.png)

**安装版本：**
lowcode-engine-1.0.11（尝试使用最新的版本也出现同样错误）

**安装步骤：**
1、cnmp i -dd   --成功
2、cnpm run setup 或者npm run setup  --失败。报错信息如下：
![image](https://user-images.githubusercontent.com/851243/176981984-3a2382b4-003d-407e-946f-404a611360bd.png)

**Comment by LeoYuan** [comment]
抱歉，centos 我么没法兼容，你用 centos 当开发机器？

**Comment by CasbaL** [comment]
同样遇到这个文件复制的问题
>error
``` bash
warning "workspace-aggregator-e4d654fc-5f88-4184-933d-e6687b70d259 > @alilc/lowcode-rax-renderer > build-plugin-rax-component > rax-compile-config > @babel/preset-flow > @babel/plugin-transform-flow-strip-types@7.19.0" has unmet peer dependency "@babel/core@^7.0.0-0".
warning "workspace-aggregator-e4d654fc-5f88-4184-933d-e6687b70d259 > @alilc/lowcode-rax-renderer > build-plugin-rax-component > rax-compile-config > @babel/preset-flow > @babel/plugin-transform-flow-strip-types > @babel/plugin-syntax-flow@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
error An unexpected error occurred: "ENOENT: no such file or directory, copyfile '/home/zhushuaibo/.cache/yarn/v6/npm-globals-13.18.0-fb224daeeb2bb7d254cd2c640f003528b8d0c1dc-integrity/node_modules/globals/globals.json' -> '/home/zhushuaibo/Demo/lowcode-engine/node_modules/@eslint/eslintrc/node_modules/globals/globals.json'".
info If you think this is a bug, please open a bug report with the information provided in "/home/zhushuaibo/Demo/lowcode-engine/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
Process stalled
Active handles:
  - WriteStream
  - WriteStream
  - ReadStream
lerna ERR! yarn install --mutex network:42424 --non-interactive --no-package-lock exited 1 in 'lowcode-engine'
lerna ERR! yarn install --mutex network:42424 --non-interactive --no-package-lock exited 1 in 'lowcode-engine'
```
看了下在项目根目录的 `node_modules` 里的eslinrc 的 `node_modules` 中没有  `globals` 这个文件夹
```bash
➜  globals l /home/zhushuaibo/.cache/yarn/v6/npm-globals-13.18.0-fb224daeeb2bb7d254cd2c640f003528b8d0c1dc-integrity/node_modules/globals
total 92K
drwxr-xr-x 2 zhushuaibo zhushuaibo 4.0K Nov 30 13:36 .
drwxr-xr-x 3 zhushuaibo zhushuaibo 4.0K Nov 30 13:36 ..
-rw-r--r-- 1 zhushuaibo zhushuaibo 5.4K Nov 30 13:36 .yarn-metadata.json
-rw-r--r-- 1 zhushuaibo zhushuaibo 9.3K Nov 30 13:36 .yarn-tarball.tgz
-rw-r--r-- 1 zhushuaibo zhushuaibo  41K Nov 30 13:36 globals.json
-rw-r--r-- 1 zhushuaibo zhushuaibo  165 Nov 30 13:36 index.d.ts
-rw-r--r-- 1 zhushuaibo zhushuaibo   58 Nov 30 13:36 index.js
-rw-r--r-- 1 zhushuaibo zhushuaibo 1.1K Nov 30 13:36 license
-rw-r--r-- 1 zhushuaibo zhushuaibo  948 Nov 30 13:36 package.json
-rw-r--r-- 1 zhushuaibo zhushuaibo 2.1K Nov 30 13:36 readme.md
➜  globals l /home/zhushuaibo/Demo/lowcode-engine/node_modules/@eslint/eslintrc/node_modules/
total 16K
drwxr-xr-x 4 zhushuaibo zhushuaibo 4.0K Nov 30 13:47 .
drwxr-xr-x 5 zhushuaibo zhushuaibo 4.0K Nov 30 13:47 ..
drwxr-xr-x 3 zhushuaibo zhushuaibo 4.0K Nov 30 13:47 espree
drwxr-xr-x 4 zhushuaibo zhushuaibo 4.0K Nov 30 13:47 type-fest
```

> 开发环境
```bash
OS: Ubuntu 22.04 jammy(on the Windows Subsystem for Linux)
Kernel: x86_64 Linux 5.15.74.2-microsoft-standard-WSL2
Shell: zsh 5.8.1
CPU: Intel Core i5-10500 @ 12x 3.096GHz

```

**Comment by CasbaL** [comment]
> 同样遇到这个文件复制的问题
> 
> > error
> 
> ```shell
> warning "workspace-aggregator-e4d654fc-5f88-4184-933d-e6687b70d259 > @alilc/lowcode-rax-renderer > build-plugin-rax-component > rax-compile-config > @babel/preset-flow > @babel/plugin-transform-flow-strip-types@7.19.0" has unmet peer dependency "@babel/core@^7.0.0-0".
> warning "workspace-aggregator-e4d654fc-5f88-4184-933d-e6687b70d259 > @alilc/lowcode-rax-renderer > build-plugin-rax-component > rax-compile-config > @babel/preset-flow > @babel/plugin-transform-flow-strip-types > @babel/plugin-syntax-flow@7.18.6" has unmet peer dependency "@babel/core@^7.0.0-0".
> error An unexpected error occurred: "ENOENT: no such file or directory, copyfile '/home/zhushuaibo/.cache/yarn/v6/npm-globals-13.18.0-fb224daeeb2bb7d254cd2c640f003528b8d0c1dc-integrity/node_modules/globals/globals.json' -> '/home/zhushuaibo/Demo/lowcode-engine/node_modules/@eslint/eslintrc/node_modules/globals/globals.json'".
> info If you think this is a bug, please open a bug report with the information provided in "/home/zhushuaibo/Demo/lowcode-engine/yarn-error.log".
> info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
> Process stalled
> Active handles:
>   - WriteStream
>   - WriteStream
>   - ReadStream
> lerna ERR! yarn install --mutex network:42424 --non-interactive --no-package-lock exited 1 in 'lowcode-engine'
> lerna ERR! yarn install --mutex network:42424 --non-interactive --no-package-lock exited 1 in 'lowcode-engine'
> ```
> 
> 看了下在项目根目录的 `node_modules` 里的eslinrc 的 `node_modules` 中没有 `globals` 这个文件夹
> 
> ```shell
> ➜  globals l /home/zhushuaibo/.cache/yarn/v6/npm-globals-13.18.0-fb224daeeb2bb7d254cd2c640f003528b8d0c1dc-integrity/node_modules/globals
> total 92K
> drwxr-xr-x 2 zhushuaibo zhushuaibo 4.0K Nov 30 13:36 .
> drwxr-xr-x 3 zhushuaibo zhushuaibo 4.0K Nov 30 13:36 ..
> -rw-r--r-- 1 zhushuaibo zhushuaibo 5.4K Nov 30 13:36 .yarn-metadata.json
> -rw-r--r-- 1 zhushuaibo zhushuaibo 9.3K Nov 30 13:36 .yarn-tarball.tgz
> -rw-r--r-- 1 zhushuaibo zhushuaibo  41K Nov 30 13:36 globals.json
> -rw-r--r-- 1 zhushuaibo zhushuaibo  165 Nov 30 13:36 index.d.ts
> -rw-r--r-- 1 zhushuaibo zhushuaibo   58 Nov 30 13:36 index.js
> -rw-r--r-- 1 zhushuaibo zhushuaibo 1.1K Nov 30 13:36 license
> -rw-r--r-- 1 zhushuaibo zhushuaibo  948 Nov 30 13:36 package.json
> -rw-r--r-- 1 zhushuaibo zhushuaibo 2.1K Nov 30 13:36 readme.md
> ➜  globals l /home/zhushuaibo/Demo/lowcode-engine/node_modules/@eslint/eslintrc/node_modules/
> total 16K
> drwxr-xr-x 4 zhushuaibo zhushuaibo 4.0K Nov 30 13:47 .
> drwxr-xr-x 5 zhushuaibo zhushuaibo 4.0K Nov 30 13:47 ..
> drwxr-xr-x 3 zhushuaibo zhushuaibo 4.0K Nov 30 13:47 espree
> drwxr-xr-x 4 zhushuaibo zhushuaibo 4.0K Nov 30 13:47 type-fest
> ```
> 
> > 开发环境
> 
> ```shell
> OS: Ubuntu 22.04 jammy(on the Windows Subsystem for Linux)
> Kernel: x86_64 Linux 5.15.74.2-microsoft-standard-WSL2
> Shell: zsh 5.8.1
> CPU: Intel Core i5-10500 @ 12x 3.096GHz
> ```

```bash
➜  globals npm -v
9.1.1
➜  globals node -v
v16.18.1
➜  globals npm -v
9.1.1
➜  globals yarn -v
1.22.19
➜  globals pnpm -v
7.14.2
```
