### ISSUE TITLE
出码模块有BUG

### ISSUE THREAD

**Issue by chenld1113** [alibaba/lowcode-engine#767]
## **Describe the bug (required)** / **详细描述 bug（必填）**
import { Image } from "@alilc/lowcode-materials";
无法找到组件,上面引入其他组件为正确路径
![image](https://user-images.githubusercontent.com/32389179/177076541-bbc865b1-957a-4b9f-9371-50760fb596e8.png)

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
[低代码demo平台
](https://lowcode-engine.cn/demo/index.html)
Schema:
`{
  "componentName": "Page",
  "id": "node_dockcviv8fo1",
  "props": {
    "ref": "outerView",
    "style": {
      "height": "100%"
    }
  },
  "fileName": "/",
  "dataSource": {
    "list": [
      {
        "type": "fetch",
        "isInit": true,
        "options": {
          "params": {},
          "method": "GET",
          "isCors": true,
          "timeout": 5000,
          "headers": {},
          "uri": "mock/info.json"
        },
        "id": "info",
        "shouldFetch": {
          "type": "JSFunction",
          "value": "function() { \n  console.log('should fetch.....');\n  return true; \n}"
        }
      }
    ]
  },
  "state": {
    "text": {
      "type": "JSExpression",
      "value": "\"outer\""
    },
    "isShowDialog": {
      "type": "JSExpression",
      "value": "false"
    }
  },
  "css": "body {\n  font-size: 12px;\n}\n\n.button {\n  width: 100px;\n  color: #ff00ff\n}",
  "lifeCycles": {
    "componentDidMount": {
      "type": "JSFunction",
      "value": "function componentDidMount() {\n  console.log('did mount');\n}"
    },
    "componentWillUnmount": {
      "type": "JSFunction",
      "value": "function componentWillUnmount() {\n  console.log('will unmount');\n}"
    }
  },
  "methods": {
    "testFunc": {
      "type": "JSFunction",
      "value": "function testFunc() {\n  console.log('test func');\n}"
    },
    "onClick": {
      "type": "JSFunction",
      "value": "function onClick(props) {\n  console.log('props', this);\n  console.log(this.getNodeInstanceFromElement);\n  console.log(1, utils.appHelper); // this.setState({\n  //   isShowDialog: true\n  // })\n}"
    },
    "closeDialog": {
      "type": "JSFunction",
      "value": "function closeDialog() {\n  this.setState({\n    isShowDialog: false\n  });\n}"
    }
  },
  "originCode": "\n\nclass LowcodeComponent extends Component {\n  state = {\n    \"text\": \"outer\",\n    \"isShowDialog\": false\n  }\n  componentDidMount() {\n    console.log('did mount');\n  }\n  componentWillUnmount() {\n    console.log('will unmount');\n  }\n  testFunc() {\n    console.log('test func');\n  }\n  onClick(props) {\n    console.log('props', this)\n    console.log(this.getNodeInstanceFromElement);\n    console.log(1, utils.appHelper)\n    // this.setState({\n    //   isShowDialog: true\n    // })\n  }\n  closeDialog() {\n    this.setState({\n      isShowDialog: false\n    })\n  }\n}",
  "title": "",
  "isLocked": false,
  "condition": true,
  "conditionGroup": "",
  "children": [
    {
      "componentName": "NextPage",
      "id": "node_ockzs2vw431",
      "props": {
        "headerDivider": true,
        "minHeight": "100vh",
        "presetNav": true,
        "presetAside": true,
        "footer": false,
        "nav": false,
        "aside": false,
        "placeholderStyle": {
          "gridRowEnd": "span 1",
          "gridColumnEnd": "span 12"
        },
        "headerProps": {
          "background": "surface"
        },
        "header": {
          "type": "JSSlot",
          "value": [
            {
              "componentName": "NextPageHeader",
              "id": "node_ockzs2vw433",
              "props": {},
              "title": "页面头部",
              "isLocked": false,
              "condition": true,
              "conditionGroup": "",
              "children": [
                {
                  "componentName": "NextRowColContainer",
                  "id": "node_ockzs2vw434",
                  "props": {
                    "rowGap": 20,
                    "colGap": 20
                  },
                  "title": "行列容器",
                  "isLocked": false,
                  "condition": true,
                  "conditionGroup": "",
                  "children": [
                    {
                      "componentName": "NextRow",
                      "id": "node_ockzs2vw435",
                      "props": {},
                      "title": "行",
                      "isLocked": false,
                      "condition": true,
                      "conditionGroup": "",
                      "children": [
                        {
                          "componentName": "NextCol",
                          "id": "node_ockzs2vw436",
                          "props": {
                            "colSpan": 1
                          },
                          "title": "列",
                          "isLocked": false,
                          "condition": true,
                          "conditionGroup": "",
                          "children": [
                            {
                              "componentName": "NextP",
                              "id": "node_ockzvfoetv17",
                              "props": {
                                "wrap": false,
                                "type": "body2",
                                "verAlign": "middle",
                                "textSpacing": true,
                                "align": "left"
                              },
                              "docId": "dockzvfoetv",
                              "title": "段落",
                              "isLocked": false,
                              "condition": true,
                              "conditionGroup": "",
                              "children": [
                                {
                                  "componentName": "NextText",
                                  "id": "node_ockzvfoetv18",
                                  "props": {
                                    "type": "h5",
                                    "children": {
                                      "type": "JSExpression",
                                      "value": "this.state.info?.info",
                                      "mock": "标题标题"
                                    },
                                    "mark": false,
                                    "code": false,
                                    "delete": false,
                                    "underline": false,
                                    "strong": false
                                  },
                                  "docId": "dockzvfoetv",
                                  "title": "",
                                  "isLocked": false,
                                  "condition": true,
                                  "conditionGroup": ""
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ],
          "title": "header"
        },
        "isTab": false,
        "contentAlignCenter": false,
        "contentProps": {
          "style": {
            "background": "rgba(255,255,255,0)"
          }
        }
      },
      "title": "页面",
      "isLocked": false,
      "condition": true,
      "conditionGroup": "",
      "children": [
        {
          "componentName": "NextBlock",
          "id": "node_ockzs2vw437",
          "props": {
            "placeholderStyle": {
              "height": "100%"
            },
            "noPadding": false,
            "noBorder": false,
            "title": "区域标题",
            "rowGap": 20,
            "colGap": 20,
            "background": "surface",
            "layoutmode": "O",
            "strict": true,
            "colSpan": 12,
            "rowSpan": 1,
            "mode": "transparent",
            "childTotalColumns": 12
          },
          "title": "区域",
          "isLocked": false,
          "condition": true,
          "conditionGroup": "",
          "children": [
            {
              "componentName": "NextBlockCell",
              "id": "node_ockzs2vw438",
              "props": {
                "colSpan": 12,
                "rowSpan": 1,
                "mode": "procard",
                "isAutoContainer": true,
                "title": "区块标题",
                "hasDivider": true,
                "loading": false,
                "bodyPadding": "",
                "hasCollapse": false,
                "text": true,
                "visibleButtonCount": 3,
                "operationConfig": {
                  "align": "center"
                },
                "operations": []
              },
              "title": "",
              "isLocked": false,
              "condition": true,
              "conditionGroup": "",
              "children": [
                {
                  "componentName": "NextRowColContainer",
                  "id": "node_ockzs2vw439",
                  "props": {
                    "rowGap": 20,
                    "colGap": 20
                  },
                  "title": "行列容器",
                  "isLocked": false,
                  "condition": true,
                  "conditionGroup": "",
                  "children": [
                    {
                      "componentName": "NextRow",
                      "id": "node_ockzs2vw43a",
                      "props": {},
                      "title": "行",
                      "isLocked": false,
                      "condition": true,
                      "conditionGroup": "",
                      "children": [
                        {
                          "componentName": "NextCol",
                          "id": "node_ockzs2vw43b",
                          "props": {
                            "colSpan": 1
                          },
                          "title": "列",
                          "isLocked": false,
                          "condition": true,
                          "conditionGroup": "",
                          "children": [
                            {
                              "componentName": "NextP",
                              "id": "node_ocl55h2xz2bf",
                              "props": {
                                "wrap": false,
                                "type": "body2",
                                "verAlign": "middle",
                                "textSpacing": true,
                                "align": "left"
                              },
                              "docId": "docl55h2xz2",
                              "title": "段落",
                              "isLocked": false,
                              "condition": true,
                              "conditionGroup": "",
                              "children": [
                                {
                                  "componentName": "NextRowColContainer",
                                  "id": "node_ocl55h2xz2bg",
                                  "props": {
                                    "rowGap": 20,
                                    "colGap": 20
                                  },
                                  "docId": "docl55h2xz2",
                                  "title": "行列容器",
                                  "isLocked": false,
                                  "condition": true,
                                  "conditionGroup": "",
                                  "children": [
                                    {
                                      "componentName": "NextRow",
                                      "id": "node_ocl55h2xz2bh",
                                      "props": {},
                                      "docId": "docl55h2xz2",
                                      "title": "行",
                                      "isLocked": false,
                                      "condition": true,
                                      "conditionGroup": "",
                                      "children": [
                                        {
                                          "componentName": "NextCol",
                                          "id": "node_ocl55h2xz2bi",
                                          "props": {
                                            "colSpan": 1
                                          },
                                          "docId": "docl55h2xz2",
                                          "title": "列",
                                          "isLocked": false,
                                          "condition": true,
                                          "conditionGroup": "",
                                          "children": [
                                            {
                                              "componentName": "NextP",
                                              "id": "node_ocl55h2xz2du",
                                              "props": {
                                                "wrap": false,
                                                "type": "body2",
                                                "verAlign": "middle",
                                                "textSpacing": true,
                                                "align": "left",
                                                "ref": "nextp-096a3e8c"
                                              },
                                              "docId": "docl55h2xz2",
                                              "title": "段落",
                                              "isLocked": false,
                                              "condition": true,
                                              "conditionGroup": "",
                                              "loop": [
                                                {
                                                  "text": "1",
                                                  "img": "img1"
                                                },
                                                {
                                                  "text": "2",
                                                  "img": "img2"
                                                }
                                              ],
                                              "children": [
                                                {
                                                  "componentName": "NextText",
                                                  "id": "node_ocl55h2xz2dw",
                                                  "props": {
                                                    "type": {
                                                      "type": "JSExpression",
                                                      "value": "onClick()",
                                                      "mock": "h5"
                                                    },
                                                    "children": "标题标题",
                                                    "mark": false,
                                                    "code": false,
                                                    "delete": false,
                                                    "underline": false,
                                                    "strong": false,
                                                    "ref": "nexttext-0e155aba",
                                                    "__events": {
                                                      "eventDataList": [
                                                        {
                                                          "type": "componentEvent",
                                                          "name": "onClick",
                                                          "relatedEventName": "onClick"
                                                        }
                                                      ],
                                                      "eventList": [
                                                        {
                                                          "name": "onClick",
                                                          "description": "鼠标点击",
                                                          "disabled": true
                                                        }
                                                      ]
                                                    },
                                                    "onClick": {
                                                      "type": "JSFunction",
                                                      "value": "function(){this.onClick.apply(this,Array.prototype.slice.call(arguments).concat([])) }"
                                                    }
                                                  },
                                                  "title": "",
                                                  "isLocked": false,
                                                  "condition": true,
                                                  "conditionGroup": ""
                                                },
                                                {
                                                  "componentName": "Image",
                                                  "id": "node_ocl55h2xz2dv",
                                                  "props": {
                                                    "src": "https://img.alicdn.com/tps/TB16TQvOXXXXXbiaFXXXXXXXXXX-120-120.svg",
                                                    "title": "",
                                                    "alt": ""
                                                  },
                                                  "docId": "docl55h2xz2",
                                                  "title": "图片",
                                                  "isLocked": false,
                                                  "condition": true,
                                                  "conditionGroup": ""
                                                }
                                              ]
                                            }
                                          ]
                                        }
                                      ]
                                    }
                                  ]
                                }
                              ]
                            }
                          ]
                        }
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }
      ]
    }
  ]
}`
点击出码

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
可以引入正确的组件路径,import {NextText, Image } from "@alilc/lowcode-materials/lib/index.js";
---

## **Screenshots (optional)** / **bug 截图（可选）**
![image](https://user-images.githubusercontent.com/32389179/177076541-bbc865b1-957a-4b9f-9371-50760fb596e8.png)

**Comment by hanrea** [comment]
+1
