### ISSUE TITLE
插槽保存后删除插槽内的组件重新添加,查看或导出schema会出现操作一次就多一层Slot

### ISSUE THREAD

**Issue by sbiweeq** [alibaba/lowcode-engine#768]
## **Describe the bug (required)** / **详细描述 bug（必填）**

插槽保存后删除插槽内的组件重新添加,查看或导出schema会出现操作一次就多一层Slot

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1.开启一个插槽
2.添加一个组件
3.保存
4.刷新页面
5.删除这个插槽内的组件,重新添加
6.保存页面
7.查看schema,就会出现多一层slot

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
仅一层

---

## **Screenshots (optional)** / **bug 截图（可选）**
错误情况
![e3a5a11cb898dbf4efcada1b5e8df29](https://user-images.githubusercontent.com/10651998/177083252-5bb70012-4ebf-4e61-a83a-8bb7a858b6a8.png)
正常情况
![image](https://user-images.githubusercontent.com/10651998/177083291-06412a69-6f73-498f-8238-deb7cbbbf088.png)

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.11] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.11] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

**Comment by JackLian** [comment]
用官网demo，按步骤操作未能重现，具体是开启哪里的插槽，拖了那个组件进去，也麻烦补充下

**Comment by sbiweeq** [comment]
> 用官网demo，按步骤操作未能重现，具体是开启哪里的插槽，拖了那个组件进去，也麻烦补充下

官网demo上没有类似的组件,使用这个的Result可复现
https://alifd.alicdn.com/npm/@alilc/antd-lowcode-materials@1.0.9/build/lowcode/index.html


**操作步骤**

1.删除icon插槽内的组件
2.重新从组件库中拖一个icon组件到插槽
3.保存
4,刷新页面
5.反复1-4步骤操作几次,最后查看schema  Result组件的props的 icon属性就会出现无限叠加

`
{
  "componentName": "Page",
  "id": "node_ocl5683giz1",
  "props": {},
  "docId": "docl5683giz",
  "hidden": false,
  "title": "",
  "isLocked": false,
  "condition": true,
  "conditionGroup": "",
  "children": [
    {
      "componentName": "Result",
      "id": "node_ocl56d1wra1",
      "props": {
        "status": "success",
        "title": "Success!",
        "subTitle": "Order number: 123",
        "icon": {
          "type": "JSSlot",
          "value": [
            {
              "componentName": "Slot",
              "id": "node_ocl56d2tcq1",
              "props": {},
              "docId": "docl56d2tcq",
              "hidden": false,
              "title": "",
              "isLocked": false,
              "condition": true,
              "conditionGroup": "",
              "children": [
                {
                  "componentName": "Slot",
                  "id": "node_ocl56d1wra2",
                  "props": {},
                  "docId": "docl56d1wra",
                  "hidden": false,
                  "isLocked": false,
                  "condition": true,
                  "conditionGroup": "",
                  "title": "",
                  "children": [
                    {
                      "componentName": "Icon",
                      "id": "node_ocl56d2tcq2",
                      "props": {
                        "type": "SmileOutlined",
                        "size": 20,
                        "rotate": 0,
                        "spin": false
                      },
                      "docId": "docl56d2tcq",
                      "hidden": false,
                      "title": "",
                      "isLocked": false,
                      "condition": true,
                      "conditionGroup": ""
                    }
                  ]
                }
              ]
            }
          ]
        }
      },
      "docId": "docl56d1wra",
      "hidden": false,
      "title": "",
      "isLocked": false,
      "condition": true,
      "conditionGroup": ""
    },
    {
      "componentName": "Carousel",
      "id": "node_ocl5683gizd",
      "props": {
        "autoplay": false,
        "dotPosition": "top",
        "easing": "",
        "effect": "scrollx",
        "items": [
          {
            "key": "panel-1"
          },
          {
            "key": "panel-2"
          }
        ]
      },
      "docId": "docl5683giz",
      "hidden": false,
      "title": "",
      "isLocked": false,
      "condition": true,
      "conditionGroup": ""
    }
  ]
}
`

**Comment by sbiweeq** [comment]
最新版本测试没有问题了

**Comment by sbiweeq** [comment]
![image](https://user-images.githubusercontent.com/10651998/177113564-adb39ee6-170b-4dc5-b6cb-b315619b2b68.png)

**Comment by liujuping** [comment]
这个和引擎版本没有关系，辛苦将插件都更新到最新版本。

**Comment by sbiweeq** [comment]
> 这个和引擎版本没有关系，辛苦将插件都更新到最新版本。

![image](https://user-images.githubusercontent.com/10651998/177240930-1aa597d8-fc47-44a3-a3a1-4bcaa3282f0f.png)
都是最新版本

**Comment by liujuping** [comment]
@alilc/lowcode-plugin-schema 看看这个 npm 版本。

**Comment by liujuping** [comment]
https://lowcode-engine.cn/demo/basic-antd.html

可以用这个地址，有 Result 组件，但是也没有办法复现问题。

![image](https://user-images.githubusercontent.com/11935995/178885191-c054bb47-f088-47a2-bb87-bd6d8c3357de.png)

这个地址有的资源没有更新。比如插件版本都是之前的。

**Comment by lucy091** [comment]
官网antd table组件加行展开不会报错
![image](https://user-images.githubusercontent.com/33422728/181451329-9df5ab2a-c4a8-4627-b30f-426c180ef048.png)

用antd物料库启动本地启动，lowcode-enginee升级到11会报错，不知道是哪里不一样
![image](https://user-images.githubusercontent.com/33422728/181451614-41ae3ce8-28b9-4c1e-ac86-19c2ad781a06.png)

**Comment by LeoYuan** [comment]
> 官网antd table组件加行展开不会报错
> 
> ![image](https://user-images.githubusercontent.com/33422728/181451329-9df5ab2a-c4a8-4627-b30f-426c180ef048.png)
> 
> 
> 
> 用antd物料库启动本地启动，lowcode-enginee升级到11会报错，不知道是哪里不一样
> 
> ![image](https://user-images.githubusercontent.com/33422728/181451614-41ae3ce8-28b9-4c1e-ac86-19c2ad781a06.png)
> 
> 

麻烦新开一个issue，不要搭车～

**Comment by LeoYuan** [comment]
由于无法复现，此issue先关闭了～

按照过往经验，此问题是插件中exportSchema没有使用save模式导出而造成的，也可以按照此思路自查本地代码～

**Comment by lucy091** [comment]
确实，project.exportSchema(TransformStage.Save) 这么到处不会多一层solt
然后还有就是，之前我版本lowcode-enginee版本是9再次编辑又会多一层slot，本地npm install lowcode-enginee的包要升级到最新就好了
