### ISSUE TITLE
lowcode-material 编译失败

### ISSUE THREAD

**Issue by wulucxy** [alibaba/lowcode-engine#770]
## **Describe the bug (required)** / **详细描述 bug（必填）**

1. `noParse` 改为 false
2. `npm run build:dev`
3. 编译失败
 
![image](https://user-images.githubusercontent.com/5326403/177161646-3f6b2b3f-39cd-4269-961c-8115dfc5b8da.png)

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---
函数声明参数和调用参数不一致，参考：

https://github.com/alibaba/lowcode-tools/blob/main/packages/build-plugin-lowcode/src/index.js#L273

https://github.com/alibaba/lowcode-tools/blob/main/packages/build-plugin-lowcode/src/index.js#L487

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

组件 `meta` 文件正常生成

---

**Comment by mark-ck** [comment]
@wulucxy 试试这个版本 @alifd/build-plugin-lowcode@0.3.2-beta.0
