### ISSUE TITLE
数据源里面配置接口，勾选了是否支持跨域，但是在使用时还是报跨域问题

### ISSUE THREAD

**Issue by HDZnice** [alibaba/lowcode-engine#771]
数据源里面配置接口，勾选了是否跨域，但是在使用时还是报跨域问题，貌似那个是否支持跨域选项没作用

**Comment by JackLian** [comment]
可能对跨域的理解有些问题，可以看下网上资料，例如这个
https://juejin.cn/post/7094162429310926855
