### ISSUE TITLE
升级引擎到最新版本 1.0.11 后，array setter 的 drawer 打不开

### ISSUE THREAD

**Issue by twinkle77** [alibaba/lowcode-engine#774]
## **Describe the bug (required)** / **详细描述 bug（必填）**

<img width="336" alt="image" src="https://user-images.githubusercontent.com/17792166/177308646-b9ec78c0-6c44-4e6f-a564-4ea9e15813c5.png">

红框按钮，点击后，drawer 不会弹出来

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1. 升级 lowcode-engine 到 1.0.11 版本
2. 点击 Array Setter 的编辑按钮

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
popup 正常弹出来

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: 1.0.11

## **Additional context (optional)** / **更多额外信息（可选）**

查看代码，是该 pr  https://github.com/alibaba/lowcode-engine/pull/660  导致的

**Comment by twinkle77** [comment]
@zyy7259 麻烦老哥也看下

**Comment by yz1311** [comment]
@zyy7259   canCloseByOutSideClick这个属性能不能做成可配置的，现在默认是true后，如果我想在整个页面显示另外一个弹窗，点击弹窗后，下面的Drawer也会自动隐藏    @twinkle77  我倒是依旧可以显示

**Comment by twinkle77** [comment]
更 react 版本相关，奇怪

弹窗出不来
  'https://g.alicdn.com/code/lib/react/17.0.2/umd/react.development.js',
  'https://g.alicdn.com/code/lib/react-dom/17.0.2/umd/react-dom.development.js',

弹窗能出阿里
  'https://g.alicdn.com/code/lib/react/16.13.1/umd/react.development.js',
  'https://g.alicdn.com/code/lib/react-dom/16.13.1/umd/react-dom.development.js',

**Comment by twinkle77** [comment]
react 17 版本，需要把 Drawer 的  canCloseByOutSideClick  去掉，弹窗才能正常弹

看了下 canCloseByOutSideClick 的实现：
https://github.com/alibaba-fusion/next/blob/master/src/overlay/overlay.jsx#L621

<img width="1084" alt="image" src="https://user-images.githubusercontent.com/17792166/177461833-94bef50c-ef84-4e47-b13e-ae0fcd9bc4b6.png">

应该是 react 17 的事件委托的变动导致的：

<img width="997" alt="image" src="https://user-images.githubusercontent.com/17792166/177461992-b92af397-43a2-4e3c-8743-03011ff698b5.png">

**Comment by twinkle77** [comment]
@zyy7259 @hzd822 @yz1311  @LeoYuan 
啊哈，问题已经找到，大佬讨论下怎么改，我提个 pr，哈哈

**Comment by cnlon** [comment]
@hzd822 这个问题有计划解决么？

**Comment by zhangyangupup** [comment]
哎，我也遇到这个问题，都这久了，react 版本的这个 bug 还在
