### ISSUE TITLE
页面编辑器( designer ) 里面的保存Schema后点返回上一步 报错, Cannot read properties of null (reading 'componentMeta')

### ISSUE THREAD

**Issue by flgame** [alibaba/lowcode-engine#776]
## **Describe the bug (required)** / **详细描述 bug（必填）**

页面编辑器( designer ) 里面的保存Schema后点返回上一步 报错, Cannot read properties of null (reading 'componentMeta')

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
https://lowcode-engine.cn/demo/index.html  
1. 在线上Demo里 随便拖几个组件进来
2. 打开Schema，点击保存Schema
3. 点击 编辑器顶部的 返回上一步
4. 并没有按照操作意愿返回了上一步操作，而是报错了  

**报错信息如下**
```
TypeError: Cannot read properties of null (reading 'componentMeta')
    at N (modal-nodes-manager.ts:7:12)
    at e (modal-nodes-manager.ts:125:19)
    at new e (modal-nodes-manager.ts:34:10)
    at document-model.ts:372:32
    at L (control.ts:21:3)
    at e (document-model.ts:365:5)
    at Yt (mobx.esm.js:1255:15)
    at e.import (mobx.esm.js:1239:12)
    at e.redoer (document-model.ts:143:14)
    at e (history.ts:99:12)
```

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by LeoYuan** [comment]
![image](https://user-images.githubusercontent.com/1195765/177517343-175f5d3e-5658-42e3-9176-c67c7de181de.png)

测试了下，没有报错。。。虽然 undo / redo 不符合预期，把你的具体步骤再写一下？

**Comment by flgame** [comment]
**第2步 保存Schema 很关键**

1. 在线上Demo里 拖入一个组件，比如标题
2. 左下角...打开Schema，点击保存Schema
3. 点击 编辑器顶部的 返回上一步，报错了

**Comment by flgame** [comment]
@LeoYuan 显示不仅仅是保存Schema会报错，保存源码、修改数据源之后都会报错或者失效，这两个应该是操作比较频繁的。
是否可以在Schema修改之后 回退到上一个Schema

**Comment by LeoYuan** [comment]
没看懂。。。
尝试修改数据源，没遇到什么问题

**Comment by flgame** [comment]
就是把第二步换成 修改数据源或者保存源码，然后回退 会遇到相同的问题，导致redo、undo 报错及失效。

![image](https://user-images.githubusercontent.com/19725668/177921027-eebf6695-e41a-48fe-a565-6a94f12c13c5.png)
![image](https://user-images.githubusercontent.com/19725668/177921415-6f7cfc27-d2c6-4323-a6db-d63845c7ed70.png)

**Comment by flgame** [comment]
还是有问题，希望能解决，要不然redo、undo功能就失去了作用。

**Comment by LeoYuan** [comment]
通过 project.importSchema 是直接将 schema 全部重置，相当于初始化项目，丢失了操作记录。

解决方案：可以通过 project.currentDocument.importSchema，相当于往操作记录栈里推入一次操作，此时需要调用 project.simulatorHost.rerender() 刷新画布~

几个插件要作相应修改，提个 PR？
