### ISSUE TITLE
project.openDocument后的componentsMap问题

### ISSUE THREAD

**Issue by wangqin5436** [alibaba/lowcode-engine#779]
## **Describe the bug (required)** / **详细描述 bug（必填）**

project.openDocument()后，切换不同页面，project.exportSchema(TransformStage.Save)导出的schema中的componentsMap为当前document的，而不是project的全部document的，此时预览时会Component Not Found

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1、搭建当前页面
2、project.openDocument(newSchema);
3、预览

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

openDocument后project.exportSchema(TransformStage.Save)中的componentsMap为整个project的全集，而非当前Document的componentsMap

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

![image](https://user-images.githubusercontent.com/22440598/177488701-0fa997b6-9f07-4355-a3a0-d44a5c1195de.png)
![image](https://user-images.githubusercontent.com/22440598/177488800-2a210776-4d9b-4a3a-95c4-da2c7556922d.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
![image](https://user-images.githubusercontent.com/22440598/177488884-fd277d3c-cc56-4be2-a7b2-91f05c22523b.png)

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by wangqin5436** [comment]
@LeoYuan 这个问题是否会跟进

**Comment by LeoYuan** [comment]
问题已经确认，会跟进修复的~

在此之前，你可以通过如下代码当临时解决办法：

![image](https://user-images.githubusercontent.com/1195765/178175270-1ba91478-acc3-4a44-8cb2-9fe1f06b7f41.png)

**Comment by wangqin5436** [comment]
好的 感谢
