### ISSUE TITLE
修改的回调参数信息不全

### ISSUE THREAD

**Issue by wukangjun** [alibaba/lowcode-engine#780]
## **Describe the bug (required)** / **详细描述 bug（必填）**
比如说对table组件进行属性修改:
![image](https://user-images.githubusercontent.com/20104154/177491259-78c504e3-7ae4-458d-ab5b-8670cb288470.png)
schema的格式如下：
![image](https://user-images.githubusercontent.com/20104154/177491418-cecec4b3-aca8-4887-9f9b-a1958a68aff8.png)
修改了其中一个值，onChangeNodeProp的回调参数返回如下：
![image](https://user-images.githubusercontent.com/20104154/177491565-4dd9d788-3c1f-439b-8406-1dfbb997f9b2.png)
key是title，而不是columns[1].title, 这样会导致最终调用api（setPropValue的path参数不正确导致渲染错误）,错误如下：
<img width="862" alt="image" src="https://user-images.githubusercontent.com/20104154/177491922-7ba91c77-ffd9-4dd4-b6d7-22c5e86acafe.png">

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.11] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.3] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by LeoYuan** [comment]
从 prop.path 里去解析出你要的全路径 key？

**Comment by wukangjun** [comment]
是有path.但是当prop的值是数组的话，path就有问题了，无法返回index序列号



---原始邮件---
发件人: "LeoYuan ***@***.***&gt;
发送时间: 2022年7月6日(周三) 下午5:25
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [alibaba/lowcode-engine] 修改的回调参数信息不全 (Issue #780)




 
从 prop.path 里去解析出你要的全路径 key？

**Comment by wukangjun** [comment]
![image](https://user-images.githubusercontent.com/20104154/177520832-14df762a-2fe7-4d5c-82cb-66534b3bff35.png)
当前prop的columns的值是数组，我修改了第1个或者第2个序列的内容，path返回如上图，会发现path的第2值为undefined的
