### ISSUE TITLE
lowcode-engine-ext升级导致报错

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#785]
如图 引擎版本和ext版本，只要点击高级就会报错
![image](https://user-images.githubusercontent.com/50658231/177703719-45957ced-81ab-42c6-85e5-26275efaf42d.png)
![image](https://user-images.githubusercontent.com/50658231/177704066-f69a4fdf-f654-45e5-b37d-d2c66cb6688c.png)

除了最新版11以外都是报错

PS：我自己项目是直接页面白屏了，如果catch住不崩溃？

**Comment by LeoYuan** [comment]
![image](https://user-images.githubusercontent.com/1195765/177763141-0e62d35e-ad2b-46f6-aa85-5697dce1a057.png)

要不还是把复现步骤写清晰，并且自己先按照步骤验证一下？
