### ISSUE TITLE
通过注入模式调试插件时，样式文件修改不生效

### ISSUE THREAD

**Issue by LeoYuan** [alibaba/lowcode-engine#788]
复现步骤：
1. 拉取 lowcode-plugins 代码，cd packages/plugin-simulator-size；
2. tnpm i；
3. 修改 build.json，增加 inject 配置，如下：
```json
[
  "@alilc/build-plugin-alt",
  {
    "type": "plugin",
    "inject": true
  }
]
```
4. tnpm start 启动应用；
5. 在 [官方demo](https://lowcode-engine.cn/demo/index.html) 上追加 debug 标识，修改后：https://lowcode-engine.cn/demo/index.html?debug

即可开始调试，此时修改 index.scss 文件无法实时生效~

**Comment by eternalsky** [comment]
今天处理一下

**Comment by eternalsky** [comment]
https://github.com/alibaba/lowcode-tools/pull/5 修复此问题，已经发布。
