### ISSUE TITLE
lowcode-engine-demo 出码，下载的代码运行不起来（react-sortablejs异常）

### ISSUE THREAD

**Issue by oneal32** [alibaba/lowcode-engine#794]
## 复现截图
![image](https://user-images.githubusercontent.com/16522676/177955971-c6e00d27-14c9-4d4c-bf9a-f50e89c6f0f0.png)

###  链接
https://lowcode-engine.cn/demo/index.html

### 复现流程
- 1、拖动加入 `高级表格` `查询筛选`
- 2、出码，下载代码，解压
- 3、进入代码目录，执行 `npm install`  `npm start`，报错如下：
```
 error  in ./node_modules/react-sortablejs/dist/index.js

Module parse failed: Unexpected token (160:55)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| };
| class $7fe8e3ea572bda7a$export$11bbed9ee0012c13 extends (0, $8zHUo$react.Component) {
>     /* eslint-disable-next-line */ static defaultProps = {
|         clone: (item)=>item
|     };

```

## 期望结果
出码后下载的代码，可以运行起来，并在浏览器看到页面。

## 环境信息
- node v10.15.3
- npm: '6.4.1'
- 引擎版本 1.0.11
- ext 版本 1.0.3
- 物料
  - moment﹫2.24.0
  - lodash
  - ﹫alifd/next﹫1.24.18
  - NextTable﹫1.0.1
  - ﹫alilc/lowcode-materials﹫1.0.2
  - ﹫alifd/pro-layout﹫1.0.1-beta.6
  - ﹫alifd/fusion-ui﹫1.0.5

**Comment by LeoYuan** [comment]
@Clarence-pan 帮忙看一下哈~

**Comment by bequite1991** [comment]
我也是 遇到这个问题了 网上百度一圈说要改babel 配置  然而还是没有解决

**Comment by iqinning** [comment]
这个问题临时方案可以在 package.json 中固定 react-sortablejs 版本为 6.1.1 

[https://github.com/SortableJS/react-sortablejs/issues/240](url)

**Comment by oneal32** [comment]
> 这个问题临时方案可以在 package.json 中固定 react-sortablejs 版本为 6.1.1
> 
> [https://github.com/SortableJS/react-sortablejs/issues/240](url)

谢谢！用你的方法暂时解决了。 出码后，安装指定版本react-sortablejs:  `npm install react-sortablejs@6.1.1`

**Comment by lzek** [comment]
同样的问题

**Comment by Sstriving** [comment]
这个问题还存在。。并且上面的解决办法按照后，还不行
