### ISSUE TITLE
组件事件的绑定是否支持函数表达式

### ISSUE THREAD

**Issue by haoziqaq** [alibaba/lowcode-engine#800]
目前我希望给一个组件绑定事件回调，只能绑定一个事件名，请问是否可以绑定一个函数表达式。

**Comment by alvarto** [comment]
目前设计应该是不支持的，当前这个面板控制的是绑定函数名 + 传参，而 JS 面板控制的是实际函数实现。

JS 面板实现了复杂的功能，如JSX编译等，但事件绑定浮层没有。

如果要一步到位，可能需要自己实现一个 Plugin 了，主动实现函数绑定事件
