### ISSUE TITLE
如何接入私有库的npm包

### ISSUE THREAD

**Issue by SamWeichangyue** [alibaba/lowcode-engine#802]
## 如何接入私有库的npm包？

- 因为部分包是基于antd 二次封装的业务组件库，发布于公司npm私服，那这部分业务组件库想加入物料包改如何操作？
- 这部分也牵扯这私有化部署。所以想请教下大佬

**Comment by JackLian** [comment]
用引擎开发自己的低代码平台，同样部署在内网就好了

**Comment by SamWeichangyue** [comment]
> 使用开发引擎的低代码平台，同样部署自己的网络方便了

这目前是这样的思路。但是遇到了问题，就是自己私服的npm包，如何接入到物料中心，文档中物料扩展，要么是cdn地址，要么是公网npm包

**Comment by liujuping** [comment]
主要用的就是 cdn 地址，你们自己私服的npm包需要你们自己处理，

1.类似正常的 npm，发布之后就可以通过 cdn 地址访问到 npm 包里面的文件

2.自己通过打包、构建等方式将资源上传到 cdn。

**Comment by SamWeichangyue** [comment]
> 主要用的就是 cdn 地址，你们自己私服的npm包需要你们自己处理，
> 
> 1.类似正常的 npm，发布之后就可以通过 cdn 地址访问到 npm 包里面的文件
> 
> 2.自己通过打包、构建等方式将资源上传到 cdn。

1、那clone unpkg 部署一个私有的cdn，并开放公网可访问该cdn
2、私服的npm物料包 同时发布至上述cdn中，这个思路是否可行 ？@liujuping
