### ISSUE TITLE
关于JS源码面板插件的一个样式（关于ve-code-control和lc-code-control）

### ISSUE THREAD

**Issue by meizilove258** [alibaba/lowcode-engine#803]
关于JS源码面板插件的一个样式（关于样式类名ve-code-control和lc-code-control），想要原来最新版中的lc-code-control这个样式类能把高撑起来嘛。现在这样的展示有高有点太小了。展示如下图：

<img width="1664" alt="image" src="https://user-images.githubusercontent.com/29622627/178231757-18cbe6e5-fbb6-4bfb-8e19-659ad53a2963.png">

<img width="1232" alt="image" src="https://user-images.githubusercontent.com/29622627/178232352-a8ea4d6e-8260-4475-8188-9aca1477a6e8.png">

**Comment by alvarto** [comment]
Fixed as of @alilc/lowcode-plugin-code-editor@1.0.3
官网 Demo 稍后修复，你本地可以重装一下 @alilc/lowcode-plugin-code-editor 这个包
