### ISSUE TITLE
@alilc/lowcode-rax-renderer 不能渲染schema

### ISSUE THREAD

**Issue by mengyuhang4879** [alibaba/lowcode-engine#804]
1.代码
```
import { createElement ,Component} from 'rax';
import RaxRenderer from '@alilc/lowcode-rax-renderer'
import {Button}  from 'antd'
class Lowcode extends Component{
  constructor(props) {
    super(props)
  }

  render() {
    const schema = {
      componentName: 'Page',
      props: {},
      children: [
        {
          componentName: 'Button',
          props: {
            type: 'primary',
            style: {
              color: '#2077ff'
            },
          },
          children: '确定',
        },
      ],
    };
    const components = {
      Button
    };
    return (
      <div className="lowcode-plugin-sample-preview">
        <div>yyyyyyyy</div>
        <RaxRenderer
          className="lowcode-plugin-sample-preview-content"
          schema={schema}
          components={components}
        />
      </div>
    )
  }
}
export default Lowcode

```

2.页面效果
![image](https://user-images.githubusercontent.com/39154179/178236166-1e21090f-636a-45f8-b7e4-698547beac5d.png)

**Comment by liujuping** [comment]
import {Button}  from 'antd'

这里的 Button 得是 antd 的组件。

**Comment by mengyuhang4879** [comment]
我想低代码集成rax，现有的组件都不能使用吗，是得自己封装吗？



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年07月11日 17:46 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [alibaba/lowcode-engine] @alilc/lowcode-rax-renderer 不能渲染schema (Issue #804) |

import {Button} from 'antd'

这里的 Button 得是 rax 的组件。

**Comment by liujuping** [comment]
低代码集成 rax，画布和组件都需要是 rax。目前引擎的官方物料中没有 rax 的，需要自己封装。

**Comment by mengyuhang4879** [comment]
好的，谢谢



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2022年07月11日 17:53 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [alibaba/lowcode-engine] @alilc/lowcode-rax-renderer 不能渲染schema (Issue #804) |

低代码集成 rax，画布和组件都需要是 rax。目前引擎的官方物料中没有 rax 的，需要自己封装。
