### ISSUE TITLE
是否有Rax 应用的demo

### ISSUE THREAD

**Issue by sundi78634** [alibaba/lowcode-engine#806]
## 复现流程与链接
[lowcode-demo](https://github.com/alibaba/lowcode-demo)中几种编辑态预览态的demo都是React的，lowcode-engine中rax的render和simulator-render的包，并未找到相应的demo，能否支持一下？

## 期望结果
rax 低代码demo

## 环境信息

- 引擎版本 1.0.11
- ext 版本 1.0.3
- 物料
  - moment﹫2.24.0
  - lodash
  - ﹫alifd/next﹫1.24.18
  - NextTable﹫1.0.1
  - ﹫alilc/lowcode-materials﹫1.0.2
  - ﹫alifd/pro-layout﹫1.0.1-beta.6
  - ﹫alifd/fusion-ui﹫1.0.5

**Comment by liujuping** [comment]
https://github.com/Sarali2022/lowcode-engine-rax
