### ISSUE TITLE
物料多个schema节点的情况下，第二次拖入设计器时报错

### ISSUE THREAD

**Issue by haoziqaq** [alibaba/lowcode-engine#807]
我有如下结构的物料定义

```js
{
  snippets: {
    title: '一个组件',
    schema: [
      {
         componentName: 'Card',
         ...
      },
      {
         componentName: 'Modal',
         ...
      }
    ]
  } 
  ...
}
```

当我第一次拖入设计器时是正常渲染了Card , Modal两个节点，第二次拖入时就报错了。报错信息如下。

![image](https://user-images.githubusercontent.com/24223652/178415863-1427296a-dfd5-420b-bfcc-cd3362a0b984.png)

![image](https://user-images.githubusercontent.com/24223652/178415894-086d0091-60dc-4415-bc69-95c620cbc281.png)

单个节点的情况下就不会出错，但是我不知道如何携带一个Modal，因为模态组件不在最外层似乎不会渲染大纲树里面？希望能得到指导，谢谢～

**Comment by JackLian** [comment]
这里bydesign，schema就不是接受一个数组，modal的你参考下materials里面dialog的实现吧

**Comment by winixt** [comment]
![image](https://user-images.githubusercontent.com/20717402/201818335-ea430e49-6d44-4c8c-aef2-a7c10c69d485.png)
@JackLian 这里 pop 不修改原数组就可以支持了吧？

**Comment by winixt** [comment]
如果设计不打算支持，是不是给用户一个警告提示友好一些？
