### ISSUE TITLE
advanced.initialChildren 为函数时不被触发

### ISSUE THREAD

**Issue by haoziqaq** [alibaba/lowcode-engine#808]
![image](https://user-images.githubusercontent.com/24223652/178420270-c7b1ac10-b085-470b-9c01-26fd9c5efb64.png)

![image](https://user-images.githubusercontent.com/24223652/178420102-bb074c80-c70f-4a0c-80ef-62ac3c96a2d8.png)

**Comment by LeoYuan** [comment]
可以看一下这两段代码：

https://github.com/alibaba/lowcode-engine/blob/3d176cb5345f9c712457f2d2545e03541ffcb585/packages/designer/src/document/node/node.ts#L177

https://github.com/alibaba/lowcode-engine/blob/3d176cb5345f9c712457f2d2545e03541ffcb585/packages/designer/src/document/node/node.ts#L237-L249

看起来是会调用的~
