### ISSUE TITLE
如何在物料拖入设计器时执行一些逻辑

### ISSUE THREAD

**Issue by haoziqaq** [alibaba/lowcode-engine#809]
![image](https://user-images.githubusercontent.com/24223652/178442204-809f9b87-74c8-4eef-a61a-28506c589e2d.png)

我查看了物料相关的文档，这里的钩子似乎没有特别合适的。

**Comment by haoziqaq** [comment]
我也不知道我算不算解决了这个问题，我是通过在全局使用这样的方式暂时实现了效果。。。总感觉如果在advanced选项里能支持拖入的钩子会合适许多。

```js
project.onChangeDocument(() => {
  project.currentDocument.onAddNode((node) => {
 
  })
})
```

**Comment by mrliyaya** [comment]
> ![image](https://user-images.githubusercontent.com/24223652/178442204-809f9b87-74c8-4eef-a61a-28506c589e2d.png)
> 
> 我查看了物料相关的文档，这里的钩子似乎没有特别合适的。

方便的话可以发下 这个 文档链接吗， 想看一下
