### ISSUE TITLE
@alifd/build-plugin-lowcode包功能问题

### ISSUE THREAD

**Issue by shifengdiy** [alibaba/lowcode-engine#81]
lowcode-plugins下的base-monaco-editor项目有一个依赖@alifd/build-plugin-lowcode，请问这个包的功能是什么呢，也没有看到这个依赖的源码，如果没有用到是否可以删掉

**Comment by alvarto** [comment]
本地 build 需要用到它。具体功能请 @eternalsky 解释一下～

**Comment by shifengdiy** [comment]
感谢及时回复，那我也在依赖包中删除

**Comment by alvarto** [comment]
base-monaco-editor 并不是一个标准的插件，只是一个大部分低代码引擎的插件都需要用的 monaco-editor 的封装。

标准插件的书写方式，可以参考 plugin-schema 之类的包哈，也在同一个仓库下面。
