### ISSUE TITLE
关于静态资源加载的实现

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#810]
这是我们项目的页面，左侧每个菜单点击，都切换右侧低代码页面。但是发现一个问题，如果说上一个页面和当前页面是不同的版本，那么就会导致静态资源可能有污染。

![image](https://user-images.githubusercontent.com/50658231/178462903-6ea1b8b5-e9f6-42b0-bf40-d1e29c69ea47.png)

因为我看head标签里面发现，每次执行<ReactRenderer />组件里面的逻辑加载一次，就会添加一次静态资源上去，来回切换页面，就会出现好多个资源
![image](https://user-images.githubusercontent.com/50658231/178463925-eb1ac3a9-52fc-4777-ae02-85c50fa2a924.png)

**想问下有没有什么方法能在reactrenderer里面去执行，清除这次加进来的静态资源，或者说这些资源加载后能不能在标签上打个标，我自己删除**

**Comment by oneQiu** [comment]
有没有成本小一点的，现在项目已经在使用中了

**Comment by LeoYuan** [comment]
这些资源是谁加载的？

**Comment by oneQiu** [comment]
> 这些资源是谁加载的？

预览的时候通过`injectComponents` 创建的，能否给这些资源的html标签上打个标识，这样我自己useEffect销毁的时候自己去处理删除掉。
![image](https://user-images.githubusercontent.com/50658231/188781484-83a11542-84e2-4352-880b-b362de7992f0.png)

**Comment by mixtan** [comment]
> 这是我们项目的页面，左侧每个菜单点击，都切换右侧低代码页面。但是发现一个问题，如果说上一个页面和当前页面是不同的版本，那么就会导致静态资源可能有污染。
> 
> ![image](https://user-images.githubusercontent.com/50658231/178462903-6ea1b8b5-e9f6-42b0-bf40-d1e29c69ea47.png)
> 
> 因为我看head标签里面发现，每次执行组件里面的逻辑加载一次，就会添加一次静态资源上去，来回切换页面，就会出现好多个资源 ![image](https://user-images.githubusercontent.com/50658231/178463925-eb1ac3a9-52fc-4777-ae02-85c50fa2a924.png)
> 
> **想问下有没有什么方法能在reactrenderer里面去执行，清除这次加进来的静态资源，或者说这些资源加载后能不能在标签上打个标，我自己删除**

你好，请你们项目也是基于lowcode-engine低代码引擎开发的低代码平台吗？生成的schema里所有资源都是私有化吗？
