### ISSUE TITLE
lowcode-tools,package.json配置有问题.

### ISSUE THREAD

**Issue by chenld1113** [alibaba/lowcode-engine#813]
## **Describe the bug (required)** / **详细描述 bug（必填）**
https://github.com/alibaba/lowcode-tools/blob/main/packages/build-plugin-lowcode/demo/component/package.json#L35
![image](https://user-images.githubusercontent.com/32389179/178630029-54ec5464-9f2f-4421-96cf-8e08ebd6fa57.png)

@ali/fusion-icon-setter 依赖包未发布.
![image](https://user-images.githubusercontent.com/32389179/178630059-37ba152b-0ef5-496b-9291-0d2647b35475.png)
![image](https://user-images.githubusercontent.com/32389179/178630360-3cc89b71-8859-4c78-a470-2901b2038239.png)

**Comment by chenld1113** [comment]
@mark-ck

**Comment by liujuping** [comment]
这个问题已经修复了。

**Comment by kapeter** [comment]
Not Found - GET https://registry.npmjs.org/@ali/fusion-icon-setter - Not found，这个仓库还未发布

**Comment by littlepoolshark** [comment]
2024年8月15号了，怎么我这里还报这个问题啊？
