### ISSUE TITLE
如何动态扩展搭建协议、物料协议以及编辑器状态？

### ISSUE THREAD

**Issue by chnliquan** [alibaba/lowcode-engine#817]
标准的搭建协议和物料协议都是会在运行时供插件消费的，请问如下的问题应该怎么处理呢？

1. 搭建协议可以在运行时扩展吗，比如我的业务或者插件需要扩展一个如下的类型
![image](https://user-images.githubusercontent.com/34906299/178703608-f11d83a8-dfe0-4113-8414-6c432905a0fa.png)
是必须提前修改好引擎中的搭建协议部分还是说可以在运行时动态的扩展并解析，类型定义是否可以在消费的时候获取到？

2. 资产协议可以在运行时扩展吗，比如我的业务或者插件需要扩展一个如下的类型
![image](https://user-images.githubusercontent.com/34906299/178698181-f417b0cb-a7c8-4be0-8315-4ed8b6e82671.png)
这个我理解只需要对 setter 扩展就可以了对吧？但是同样的类型定义如果没预置怎么在消费的时候获取到呢？

3. 对于设计器的操作，比如选中一个组件触发属性面板的变化我看代码的实现是通过 eventbus 监听 `designer.selection.change` 事件来控制变化
![image](https://user-images.githubusercontent.com/34906299/178702651-aa175d56-37b2-4e47-8520-7cc25ed9088a.png)
如果我需要定义一个 mySelection.change 这样的事件供整个设计器里面的插件来用，是不是就定一个自定义的事件名就可以了？如果是这样如何保证事件名不冲突呢？还是说有其他的方案

**Comment by chnliquan** [comment]
@LeoYuan 大佬帮忙看看？

**Comment by LeoYuan** [comment]
1/2 不知道场景，没法回答~
3 是通过 namespace 自己控制，比如 event.emit('yourNS.xxx', data)~

**Comment by chnliquan** [comment]
@LeoYuan  感谢回复，1/2 的场景就是目前这些字段如果不能满足业务的诉求，想增加新的字段才能满足，方案一种是在引擎侧修改 Schema 然后发包，方案二是提供一种动态的扩展方式，这样引擎侧不需要修改发包，不知道现在引擎侧采用的那种方式。3 这个问题比如「属性面板」这个插件目前满足不了我的业务诉求，我想在每一个设置器field前面增加一个按钮来做业务的逻辑，我需要 fork 这个官方插件然后修改 UI 么？然后点击这个 + 按钮触发事件 propertyAdd 会影响大纲树的话是否也需要 fork 个大纲树插件然后绑定 propertyAdd 这个事件联动是么？
![image](https://user-images.githubusercontent.com/34906299/180764511-20ea660b-e443-4467-9530-bdb4dfad1097.png)

**Comment by LeoYuan** [comment]
1/2 说的是 registerMetadataTransducer 的事？
3 理论上是可以的，属性面板可以实现成自己的，不过前提需要熟悉现在的属性面板写法，会比较复杂~

**Comment by chnliquan** [comment]
registerMetadataTransducer 我看是处理物料的，1 是指搭建 schema 最终会被渲染器消费，渲染器会根据定义这一份标准 schema 渲染出视图，如果业务方需要的搭建协议里面的某些字段标准的 schema 里面没有要如何处理，是不断迭代这个标准这个 schema 发版，还是说可以保持这个是 schema 不变，业务方通过某种方式去动态扩展？
3 这个如果要加个按钮，官方推荐的方式是什么呢 @LeoYuan

**Comment by LeoYuan** [comment]
1 自己加，自己消费就行，假如觉得是通用的，可以往协议提PR
3 可以自己定制一个设置面板，不过需要先把目前的设置面板源码读一读
