### ISSUE TITLE
表单组件联动展示实现方案

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#820]
例如yida是有个"formula"配置项，但是不知道怎么去实现。
场景：页面上有个选择器和输入框，我希望选择器选中某个选项的时候输入框显示出来。但是如果通过JS代码去实现，对用户不太友好了。想知道yida是通过哪些API去实现的。ref吗？

**Comment by Dogtiti** [comment]
通过`condition`去判断
```js
{
  name:'A',
  condition: (target) => {
     return target.parent.getPropValue('B') === 'xxx';
  }
}
```

**Comment by oneQiu** [comment]
Q2: 我按照demo同样添加了Ref的配置项，通过this.$('xxx')的方式，但是并没有生效，打印出来的值没有我挂到ref的属性。 是需要用class到写法吗？
![image](https://user-images.githubusercontent.com/50658231/178949609-6d74fa56-3082-4431-8ab9-6d052901cc99.png)
![image](https://user-images.githubusercontent.com/50658231/178949677-82353a5d-efe7-4b54-8dbe-3e30fc22ddf3.png)
