### ISSUE TITLE
组件拖拽时候光标位置

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#823]
想知道这个光标位置是怎么去决定在上下还是在左右的，能否控制？

我现在有个容器组件是Flex，然后内部的组件光标都是在左右，能否改成上下？
![image](https://user-images.githubusercontent.com/50658231/179145244-4d79ccdd-2fc9-46db-866a-710b947a1c0c.png)

**Comment by LeoYuan** [comment]
可以去看下这段代码：

https://github.com/alibaba/lowcode-engine/blob/4f4ac5115d18357a7399632860808f6cffc33fad/packages/designer/src/designer/location.ts#L69-L85

理论上 flex-direction: column 就会是「横着的线」~
