### ISSUE TITLE
seada/formily-materials  未同步npm

### ISSUE THREAD

**Issue by hanrea** [alibaba/lowcode-engine#825]
@seada/antd-materials
@seada/formily-materials
这个包是不是忘记更新npm了？ npm 上还是0.0.1-rc.3
index.jsx 引入 "@seada/formily-materials/src/index.tsx"; 提示文件不存在。
antd+formily 的 dmeo 出码也跑不起来。

## 期望结果

antd+formily 的 dmeo  出码本地跑起来。

## 环境信息

- 引擎版本 1.0.11
- ext 版本 1.0.3
- 物料
  - moment﹫2.24.0
  - lodash
  - iconfont-icons
  - ﹫ant-design/icons﹫4.7.0
  - antd﹫4.19.5
  - ﹫alifd/next﹫1.24.18
  - ﹫alilc/antd-lowcode-materials﹫1.0.6
  - ﹫seada/antd-materials﹫0.1.1
  - ﹫seada/formily-materials﹫0.1.1

**Comment by liujuping** [comment]
如果是使用的 formily 物料，可以到这边提问哈。

https://github.com/seada-low-code/lowcode-ecology/tree/main/packages/formily-materials
