### ISSUE TITLE
build.lowcode.js 配置的setterMap无法使用的 antd 组件的原因

### ISSUE THREAD

**Issue by twinkle77** [alibaba/lowcode-engine#826]
## **Describe the bug (required)** / **详细描述 bug（必填）**

刚好要用到 setterMap，继续跟踪上一个 issue 的原因， https://github.com/alibaba/lowcode-engine/issues/824

<img width="1771" alt="image" src="https://user-images.githubusercontent.com/17792166/179198413-dbf057ac-d568-4178-9ba0-faa475f4d350.png">

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1.  clone https://github.com/seada-low-code/lowcode-ecology/tree/setter-map  仓库的 setter-map 分支
2. yarn bootrap
3. cd packages && cd formily-markup-materials 
4. yarn lowcode:dev
5. 拖入 Formily Form 组件
6. 切换 setter
![image](https://user-images.githubusercontent.com/17792166/179199133-080a56f1-579d-4877-ab60-eef1ea8fbcb1.png)
7. 可以看到正常渲染
8. 让自定义 setter 使用 antd 的 Input
<img width="685" alt="image" src="https://user-images.githubusercontent.com/17792166/179199316-ae4cb996-bb05-4c9c-b8f4-aabbcae91a15.png">
9. 渲染直接挂了

原因：window 上不存在 antd 变量

**Comment by twinkle77** [comment]
需要改 @alifd/build-plugin-lowcode 的代码，但这个 plugin 好像不开源

**Comment by LeoYuan** [comment]
@twinkle77 已经开源了，要不要提个 PR？😄

https://github.com/alibaba/lowcode-tools/tree/main/packages/build-plugin-lowcode

**Comment by twinkle77** [comment]
@LeoYuan  issue 已提
