### ISSUE TITLE
新建物料发布成功后 assets-prod.json文件里面的链接无法访问

### ISSUE THREAD

**Issue by sjxswh** [alibaba/lowcode-engine#828]
这个是运行发布后的提示
<img width="1792" alt="WechatIMG6049" src="https://user-images.githubusercontent.com/32295872/179448235-2cdab037-5821-4ab9-a8d8-a9bc45f170fb.png">
<img width="705" alt="WechatIMG6050" src="https://user-images.githubusercontent.com/32295872/179448314-0063d146-ab04-46fc-9962-517fc9a571bf.png">
链接前缀改成https://cdn.jsdelivr.net/npm还是无法访问
<img width="668" alt="WechatIMG6051" src="https://user-images.githubusercontent.com/32295872/179448324-0bbe6819-2736-437e-be20-110b6d28a397.png">
这个是package.json数据
<img width="932" alt="WechatIMG6052" src="https://user-images.githubusercontent.com/32295872/179448328-13be8ddb-1062-4057-8fa6-455085377461.png">

**Comment by sjxswh** [comment]
已解决无需回复了

**Comment by zxy1115769** [comment]
怎么解决的？遇到了同样的问题
