### ISSUE TITLE
Safari浏览器报错- window.requestIdleCallback is not a function

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#829]
如题 在Safari浏览器下面会报未定义错误。
![image](https://user-images.githubusercontent.com/50658231/179468945-859fa10b-ecb7-480a-b675-1d746e2b6014.png)

![image](https://user-images.githubusercontent.com/50658231/179469060-4a07ba30-16e4-43eb-8892-cfa6762ae8ce.png)

相关的API在在mdn上不兼容
![image](https://user-images.githubusercontent.com/50658231/179469904-815d480f-7dba-4ed0-9283-94df01c424e8.png)

**Comment by JackLian** [comment]
应该是未做safari兼容，欢迎PR~
