### ISSUE TITLE
自定义物料 如何绑定设计器的样式和事件

### ISSUE THREAD

**Issue by sjxswh** [alibaba/lowcode-engine#834]
<img width="1792" alt="WechatIMG6053" src="https://user-images.githubusercontent.com/32295872/179510521-a7091945-f76e-424b-a59d-e2513ff2045a.png">

**Comment by yz1311** [comment]
可以拷贝StyleSetter的源码然后覆盖
```
setters.registerSetter('StyleSetter', StyleSetter);
```
