### ISSUE TITLE
物料扩展组件项目初始化报错

### ISSUE THREAD

**Issue by beautiful-boyyy** [alibaba/lowcode-engine#837]
## 物料扩展组件项目初始化报错

执行 `npm init @alilc/element react-comps` 报错

## 复现bug
![image](https://user-images.githubusercontent.com/66351806/179919947-20b9dced-d738-4bb1-9cd8-317018578f45.png)

## 环境
-npm: `8.5.0`
-node: `16.14.2`
-OS: `Ubuntu 20.04.4 LTS on Windows 10 x86_64`

**Comment by eternalsky** [comment]
本地试了一下 npm 8 + node 16 的组合没有问题，无论加不加 sudo。目前没有复现出来这个问题，等后面在 windows 机器上再试一下。

**Comment by beautiful-boyyy** [comment]
试了，还是8行

**Comment by beautiful-boyyy** [comment]
@eternalsky 
试了，还是8行
