### ISSUE TITLE
@alifd/build-plugin-lowcode

### ISSUE THREAD

**Issue by posuihushui** [alibaba/lowcode-engine#84]
https://github.com/alibaba/lowcode-materials 仓库里面包引用的@alifd/build-plugin-lowcode，具体链接是：https://www.npmjs.com/package/@alifd/build-plugin-lowcode
请问此包的git地址是啥？

**Comment by LeoYuan** [comment]
@mark-ck 有计划开源么？

@posuihushui 现在先从 node_modules 里边看吧~
