### ISSUE TITLE
单个组件无法支持数据双向绑定

### ISSUE THREAD

**Issue by ssjjdd** [alibaba/lowcode-engine#842]
## **Describe the bug (required)** / **详细描述 bug（必填）**

对当前值进行变量绑定，只能回显当前变量的值，无法对值进行修改
当然也可能是我的使用姿势不对

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
![image](https://user-images.githubusercontent.com/23442317/180166712-06a0bf21-14d5-4d9d-a1d9-3187994f9191.png)

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

能支持变量的双向绑定

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**

用官方提供的demo就可以复现
https://lowcode-engine.cn/demo/basic-antd.html

**Comment by JackLian** [comment]
by design 没有双向绑定的能力
