### ISSUE TITLE
请问可以支持页面锚点跳转吗？

### ISSUE THREAD

**Issue by AndyTiTi** [alibaba/lowcode-engine#847]
# 1、现有业务需求 官网头栏需要锚点跳转相应区块，请问怎么操作呢？
# 2、this.$(refId)没有current属性吗？如何获取ref节点的offsetTop属性值？

**Comment by JackLian** [comment]
1. 链接组件呗
2. 你要干啥，描述清楚点，不要只说“没有什么吗？”，描述下你的场景，想干什么，现在怎么做的，期望什么结果，现在什么结果

btw，issue有模板，有如何高效提问的指南，建议看一下哈

**Comment by AndyTiTi** [comment]
1. 链接组件可以配置href的锚点属性 #pointPosition，但是要跳转到的区块如何配置id属性呢？
2. 我想获取某个元素的offsetTop，当offsetTop大于1000的时候右下角弹出客服按钮，但这种方式行不通 this.$(refId).current.offsetTop【常规的ref都有current属性，低代码平台我控制台打印输出this.$(refId).current为undefined】




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/lowcode-engine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月22日(星期五) 下午3:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/lowcode-engine] 请问可以支持页面锚点跳转吗？ (Issue #847)





  
链接组件呗
 
你要干啥，描述清楚点，不要只说“没有什么吗？”，描述下你的场景，想干什么，现在怎么做的，期望什么结果，现在什么结果
  
btw，issue有模板，有如何高效提问的指南，建议看一下哈
