### ISSUE TITLE
请问 editTable组件怎么绑定 state数据源？

### ISSUE THREAD

**Issue by leehomeok** [alibaba/lowcode-engine#85]
## **Describe the bug (required)** / **详细描述 bug（必填）**

请问 editTable组件怎么绑定 state数据源？
右侧属性面板没有发现可以绑定数据源，文档也没有体现在哪里绑定数据源变量

**Comment by hzd822** [comment]
你好，可以用beta版本的ext.js,变量面板可以绑定数据源
https://alifd.alicdn.com/npm/@alilc/lowcode-engine-ext@1.0.2-beta.2/dist/js/engine-ext.js

**Comment by leehomeok** [comment]
> 你好，可以用beta版本的ext.js,变量面板可以绑定数据源 https://alifd.alicdn.com/npm/@alilc/lowcode-engine-ext@1.0.2-beta.2/dist/js/engine-ext.js

 你好，大佬， 已经换成了这个beta版本，但是选中editTable， 依然没有发现 表格数据源设置
![image](https://user-images.githubusercontent.com/13464485/157173876-8156678a-946b-455b-8802-6b8c15624c55.png)

**Comment by LeoYuan** [comment]
> ⚠️⚠️⚠️ 所以引擎以及相关生态包放出的带有 beta.z 版本号的版本，均为测试版，只为临时验证一些问题，切勿用于生产环境，如有使用，导致的任何问题，概不负责。

**Comment by LeoYuan** [comment]
> editTable 现在不支持配置数据源，proTable 可以😂

引用自 @mark-ck

**Comment by leehomeok** [comment]
![image](https://user-images.githubusercontent.com/13464485/160794128-067500f1-0dc6-43dc-ad59-73dbb268d02b.png)
请问 这2个 变量名要怎么填？
比如this.state.items  = 
[{
    "id": "f52844a6d6c94816a00715cb13269e45",
    "assertId": "f771f6dd1a904cdebb2ace8ebedae1b3",
    "oaid": "1234567s8",
    "store": "番禺门店",
    "assert_classfication_name": "IT资产",
    "equipment_classification_name": "显卡",
    "depreciation_code": "1231",
    "assert_name": "七彩虹显卡",
    "sap_card_no": "SAP123",
    "it_asset_no": "xp20220330",
    "authorizer_name": "lihao"
}]

**Comment by mark-ck** [comment]
EditTable 组件不支持数据源
