### ISSUE TITLE
当前页面如何实现a标签 锚点跳转至指定元素位置？

### ISSUE THREAD

**Issue by AndyTiTi** [alibaba/lowcode-engine#850]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

### 需求：当前页面如何实现a标签 锚点跳转至指定元素位置？
---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
点击顶部导航标签，如何跳转至相应的区块？
<img width="703" alt="image" src="https://user-images.githubusercontent.com/30618750/180394534-196d6ad1-68e1-4a06-8825-a69cc75f7008.png">
【例：点击上图的鸣谢按钮（其他按钮点击同样跳转至与title相对应的区块），页面滚动至下图中的位置】
<img width="699" alt="image" src="https://user-images.githubusercontent.com/30618750/180395000-74e24d0a-ffa5-42c2-8c9d-ff099eb64aa5.png">

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

点击a标签跳转至相应的锚点位置

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
- 引擎版本 1.0.11
- ext 版本 1.0.3
- 物料
  - moment﹫2.24.0
  - lodash
  - ﹫alifd/next﹫1.24.18
  - NextTable﹫1.0.1
  - ﹫alilc/lowcode-materials﹫1.0.2
  - ﹫alifd/pro-layout﹫1.0.1-beta.6
  - ﹫alifd/fusion-ui﹫1.0.5

**Comment by LeoYuan** [comment]
听起来就是正常的锚点功能？目标元素加个 id，触发元素加个 #id~

不过在低代码组件里，要看组件是否支持 id 这个配置项~

**Comment by AndyTiTi** [comment]
是的，老师，就是正常的锚点功能。

已有组件支持扩展属性吗？比如给textarea组件增加id属性。





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/lowcode-engine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月25日(星期一) 下午4:43
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/lowcode-engine] 当前页面如何实现a标签 锚点跳转至指定元素位置？ (Issue #850)





 
听起来就是正常的锚点功能？目标元素加个 id，触发元素加个 #id~
 
不过在低代码组件里，要看组件是否支持 id 这个配置项~

**Comment by LeoYuan** [comment]
看下 registerMetadataTransducer 如何给已有物料增加低代码描述配置，另外也要看下层组件是否接收 id 这个属性~

简单测试，直接在源码面板里 props 增加 id，看看能不能被渲染

**Comment by AndyTiTi** [comment]
好，感谢老师提点。


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/lowcode-engine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月25日(星期一) 下午5:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/lowcode-engine] 当前页面如何实现a标签 锚点跳转至指定元素位置？ (Issue #850)





 
看下 registerMetadataTransducer 如何给已有物料增加低代码描述配置，另外也要看下层组件是否接收 id 这个属性~
 
简单测试，直接在源码面板里 props 增加 id，看看能不能被渲染
