### ISSUE TITLE
project.currentDocument?.root?.importSchema无效问题

### ISSUE THREAD

**Issue by wukangjun** [alibaba/lowcode-engine#853]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

---
画布渲染完成后，调用project.currentDocument?.root?.importSchema(JSONSchema) 没有效果
## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
1. 初始化schema，画布中展示了一个按钮
![image](https://user-images.githubusercontent.com/20104154/180422312-2b380e42-ca47-4e33-986d-7eb01b2dccf5.png)
schema如下：
{
  "componentName": "Page",
  "id": "node_dockcviv8fo1",
  "props": {
    "ref": "outerView",
    "style": {
      "height": "100%"
    }
  },
  "docId": "docl5w71y5k",
  "fileName": "/",
  "dataSource": {
    "list": []
  },
  "state": {
    "text": {
      "type": "JSExpression",
      "value": "\"outer\""
    },
    "isShowDialog": {
      "type": "JSExpression",
      "value": "false"
    }
  },
  "css": "body {\n  font-size: 12px;\n}\n\n.button {\n  width: 100px;\n  color: #ff00ff\n}",
  "lifeCycles": {
    "componentDidMount": {
      "type": "JSFunction",
      "value": "function componentDidMount() {\n  console.log('did mount');\n}"
    },
    "componentWillUnmount": {
      "type": "JSFunction",
      "value": "function componentWillUnmount() {\n  console.log('will unmount');\n}"
    }
  },
  "methods": {
    "testFunc": {
      "type": "JSFunction",
      "value": "function testFunc() {\n  console.log('test func');\n}"
    },
    "onClick": {
      "type": "JSFunction",
      "value": "function onClick() {\n  this.setState({\n    isShowDialog: true\n  });\n}"
    },
    "closeDialog": {
      "type": "JSFunction",
      "value": "function closeDialog() {\n  this.setState({\n    isShowDialog: false\n  });\n}"
    }
  },
  "originCode": "class LowcodeComponent extends Component {\n  state = {\n    \"text\": \"outer\",\n    \"isShowDialog\": false\n  }\n  componentDidMount() {\n    console.log('did mount');\n  }\n  componentWillUnmount() {\n    console.log('will unmount');\n  }\n  testFunc() {\n    console.log('test func');\n  }\n  onClick() {\n    this.setState({\n      isShowDialog: true\n    })\n  }\n  closeDialog() {\n    this.setState({\n      isShowDialog: false\n    })\n  }\n}",
  "hidden": false,
  "title": "",
  "isLocked": false,
  "condition": true,
  "conditionGroup": "",
  "uid": "8339b903-712d-460e-b1ac-ae3634267d70",
  "children": [
    {
      "componentName": "Button",
      "id": "node_ocl5wazxtb3",
      "props": {
        "type": "primary",
        "icon": false,
        "children": "按钮123",
        "danger": false,
        "block": false,
        "size": "middle"
      },
      "docId": "docl5wazxtb",
      "hidden": false,
      "title": "",
      "isLocked": false,
      "condition": true,
      "conditionGroup": "",
      "uid": "8339b903-712d-460e-b1ac-ae3634267d70"
    }
  ]
}
2. 传入了新的schema，如下：
{"componentName":"Page","id":"node_dockcviv8fo1","props":{"ref":"outerView","style":{"height":"100%"}},"docId":"docl5w71y5k","fileName":"/","dataSource":{"list":[]},"state":{"text":{"type":"JSExpression","value":"\"outer\""},"isShowDialog":{"type":"JSExpression","value":"false"}},"css":"body {\n  font-size: 12px;\n}\n\n.button {\n  width: 100px;\n  color: #ff00ff\n}","lifeCycles":{"componentDidMount":{"type":"JSFunction","value":"function componentDidMount() {\n  console.log('did mount');\n}"},"componentWillUnmount":{"type":"JSFunction","value":"function componentWillUnmount() {\n  console.log('will unmount');\n}"}},"methods":{"testFunc":{"type":"JSFunction","value":"function testFunc() {\n  console.log('test func');\n}"},"onClick":{"type":"JSFunction","value":"function onClick() {\n  this.setState({\n    isShowDialog: true\n  });\n}"},"closeDialog":{"type":"JSFunction","value":"function closeDialog() {\n  this.setState({\n    isShowDialog: false\n  });\n}"}},"originCode":"class LowcodeComponent extends Component {\n  state = {\n    \"text\": \"outer\",\n    \"isShowDialog\": false\n  }\n  componentDidMount() {\n    console.log('did mount');\n  }\n  componentWillUnmount() {\n    console.log('will unmount');\n  }\n  testFunc() {\n    console.log('test func');\n  }\n  onClick() {\n    this.setState({\n      isShowDialog: true\n    })\n  }\n  closeDialog() {\n    this.setState({\n      isShowDialog: false\n    })\n  }\n}","hidden":false,"title":"","isLocked":false,"condition":true,"conditionGroup":"","uid":"a6b530d5-d0d6-4723-b400-a790be228e37","children":[{"componentName":"Button","id":"node_ocl5wazxtb3","props":{"type":"primary","icon":false,"children":"按钮123","danger":false,"block":false,"size":"middle"},"docId":"docl5wazxtb","hidden":false,"title":"","isLocked":false,"condition":true,"conditionGroup":"","uid":"a6b530d5-d0d6-4723-b400-a790be228e37"}]}
此时画布内容为空了。但是schme面板内容是最新的。
![image](https://user-images.githubusercontent.com/20104154/180422703-68e347c1-ea98-4b33-8dc4-833c4f69ad49.png)

---

English version example：
4. Click on '....'
5. Scroll down to '....'
6. See error

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
4. 在右侧修改标题内容为「修改后的标题」；
5. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by LeoYuan** [comment]
有没有一种可能 Button 需要传递参数？比如 children？😄
