### ISSUE TITLE
npm init @alilc/element your-material-name error

### ISSUE THREAD

**Issue by bianyuanfei** [alibaba/lowcode-engine#854]
## **Describe the bug (required)** / **详细描述 bug（必填）**

A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
---
Some errors occurred on the console
---
## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：
1. npm init @alilc/element 
2. choose component library
3. colorful-button and colorful-input are automatically generated
4. npm install
5. npm run lowcode:dev
6. See error
7. drag clolorful-button/colorful-input
8. See more error 

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---
Colorful buttons and colorful input boxes can be used normally after dragging and dropping

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

<img width="1089" alt="image" src="https://user-images.githubusercontent.com/38514473/180653847-3f0a9f0c-9a4a-439d-a9ba-107586de5536.png">
{
  "name": "chart-byf",
  "version": "0.1.0",
  "description": "chart-byf",
  "main": "lib/index.js",
  "module": "es/index.js",
  "typings": "types/index.d.ts",
  "files": [
    "build",
    "dist",
    "lib",
    "es",
    "types"
  ],
  "scripts": {
    "start": "build-scripts start",
    "build": "build-scripts build",
    "lowcode:dev": "build-scripts start --config ./build.lowcode.js",
    "lowcode:build": "build-scripts build --config ./build.lowcode.js",
    "f2elint-scan": "f2elint scan",
    "f2elint-fix": "f2elint fix",
    "prepublishOnly": "npm run build && npm run lowcode:build"
  },
  "directories": {
    "test": "test"
  },
  "keywords": [
    "Fusion"
  ],
  "author": "fusion-team",
  "license": "MIT",
  "husky": {
    "hooks": {
      "pre-commit": "f2elint commit-file-scan",
      "commit-msg": "f2elint commit-msg-scan"
    }
  },
  "lint-staged": {
    "**/*.{js,jsx,ts,tsx,vue}": "f2elint exec eslint",
    "**/*.{css,scss,less,acss}": "f2elint exec stylelint"
  },
  "peerDependencies": {
    "react": "^16.x",
    "react-dom": "^16.x",
    "moment": "latest"
  },
  "devDependencies": {
    "@alib/build-scripts": "^0.1.3",
    "@alifd/build-plugin-lowcode": "^0.3.0",
    "@alifd/theme-2": "^0.4.0",
    "@storybook/addon-actions": "^6.3.1",
    "@storybook/addon-docs": "^6.3.4",
    "@storybook/addon-essentials": "^6.3.0",
    "@storybook/addon-storysource": "^6.3.1",
    "@storybook/react": "^6.3.5",
    "@storybook/source-loader": "^6.3.1",
    "@types/react": "^16.14.24",
    "@types/react-dom": "^16.9.4",
    "build-plugin-component-multiple": "^1.0.0-beta.5",
    "build-plugin-fusion": "^0.1.0",
    "f2elint": "^3.0.0"
  },
  "dependencies": {
    "@alifd/next": "^1.25.27",
    "prop-types": "^15.5.8",
    "react": "^16.x",
    "react-dom": "^16.x"
  },
  "acceptDependencies": {
    "webpack": "^4.46.x"
  },
  "resolutions": {
    "webpack": "^4.46.x"
  },
  "componentConfig": {
    "isComponentLibrary": true
  }
}

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser chrome / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by Dogtiti** [comment]
warning不影响 是因为有一些`props`透传到DOM上了
