### ISSUE TITLE
页面之间如何跳转传递数据

### ISSUE THREAD

**Issue by MrShenPH** [alibaba/lowcode-engine#857]
请问通过引擎搭建出来的两个页面如何实现点击A页面中的某个按钮传参跳转到B页面呢

**Comment by LeoYuan** [comment]
url params?

**Comment by MrShenPH** [comment]
我的表述有点问题，需求是这样的：
1:通过引擎渲染模块渲染A页面schema
2:点击A页面schema中的按钮引擎渲染模块重新渲染B页面的schema

这个可以通过url拼接params实现吗？demo中有没有这样的示例呢？react新手，不太熟练

**Comment by LeoYuan** [comment]
没看懂
