### ISSUE TITLE
怎么添加新页面？

### ISSUE THREAD

**Issue by Go7hic** [alibaba/lowcode-engine#86]
设置了一个页面，怎么添加新的页面？没找到操作按钮呢
<img width="1587" alt="image" src="https://user-images.githubusercontent.com/3821390/157153837-53e6e3d3-5714-4f5e-922f-b8e90224dad7.png">

**Comment by LeoYuan** [comment]
引擎提供的是底层 API，有创建/ 加载 / 删除等 [文档管理 API](https://www.yuque.com/lce/doc/dcrbff)，UI 层的定制化由上层平台负责，可以做成下拉列表、多 tab等形式~

**Comment by Go7hic** [comment]
> 

懂了。还没看文档 先体验的 DEMO
