### ISSUE TITLE
ant-design-pro 6.0.0-beta.1 整合@alilc/lowcode-engine 1.0.12启动后访问此功能报错

### ISSUE THREAD

**Issue by chenfeiwu** [alibaba/lowcode-engine#860]
ant-design-pro 6.0.0-beta.1 整合@alilc/lowcode-engine 1.0.12启动后访问设计页面报错，官方文档没有这相关例子等，感觉好难啊

## **Describe the bug (required)** / **详细描述 bug（必填）**

![image](https://user-images.githubusercontent.com/14910761/180790851-a992ef18-c527-4d7b-a97f-b035e6f21539.png)
```
TypeError: Cannot set properties of undefined (setting 'PropTypes')
Module../node_modules/_@alilc_lowcode-designer@1.0.12@@alilc/lowcode-designer/es/builtin-simulator/utils/parse-metadata.js
http://localhost:8000/mf-dep____vendor.62d01dee.js:83663:24
__webpack_require__
http://localhost:8000/mf-va_remoteEntry.js:23:42
Module../node_modules/_@alilc_lowcode-designer@1.0.12@@alilc/lowcode-designer/es/builtin-simulator/host.js
http://localhost:8000/mf-dep____vendor.62d01dee.js:81173:80
__webpack_require__
http://localhost:8000/mf-va_remoteEntry.js:23:42
Module../node_modules/_@alilc_lowcode-designer@1.0.12@@alilc/lowcode-designer/es/builtin-simulator/index.js
http://localhost:8000/mf-dep____vendor.62d01dee.js:82882:63
__webpack_require__
http://localhost:8000/mf-va_remoteEntry.js:23:42
Module../node_modules/_@alilc_lowcode-designer@1.0.12@@alilc/lowcode-designer/es/project/project-view.js
http://localhost:8000/mf-dep____vendor.62d01dee.js:96457:76
__webpack_require__
http://localhost:8000/mf-va_remoteEntry.js:23:42
Module../node_modules/_@alilc_lowcode-designer@1.0.12@@alilc/lowcode-designer/es/project/index.js
http://localhost:8000/mf-dep____vendor.62d01dee.js:96437:71
__webpack_require__
http://localhost:8000/mf-va_remoteEntry.js:23:42
Module../node_modules/_@alilc_lowcode-designer@1.0.12@@alilc/lowcode-designer/es/designer/designer.js
http://localhost:8000/mf-dep____vendor.62d01dee.js:85482:67
__webpack_require__
http://localhost:8000/mf-va_remoteEntry.js:23:42
Module../node_modules/_@alilc_lowcode-designer@1.0.12@@alilc/lowcode-designer/es/designer/index.js
http://localhost:8000/mf-dep____vendor.62d01dee.js:87323:67
__webpack_require__
http://localhost:8000/mf-va_remoteEntry.js:23:42
Module../node_modules/_@alilc_lowcode-designer@1.0.12@@alilc/lowcode-designer/es/document/document-model.js
http://localhost:8000/mf-dep____vendor.62d01dee.js:89255:67
__webpack_require__
http://localhost:8000/mf-va_remoteEntry.js:23:42
Module../node_modules/_@alilc_lowcode-designer@1.0.12@@alilc/lowcode-designer/es/document/index.js
http://localhost:8000/mf-dep____vendor.62d01dee.js:90578:73
__webpack_require__
http://localhost:8000/mf-va_remoteEntry.js:23:42
Module../node_modules/_@alilc_lowcode-designer@1.0.12@@alilc/lowcode-designer/es/component-meta.js
http://localhost:8000/mf-dep____vendor.62d01dee.js:84152:67
__webpack_require__
http://localhost:8000/mf-va_remoteEntry.js:23:42
Module../node_modules/_@alilc_lowcode-designer@1.0.12@@alilc/lowcode-designer/es/index.js
http://localhost:8000/mf-dep____vendor.62d01dee.js:95491:73
__webpack_require__
http://localhost:8000/mf-va_remoteEntry.js:23:42
Module../node_modules/_@alilc_lowcode-engine@1.0.12@@alilc/lowcode-engine/es/engine-core.js
http://localhost:8000/mf-dep____vendor.62d01dee.js:115972:81
__webpack_require__
http://localhost:8000/mf-va_remoteEntry.js:23:42
Module../node_modules/.cache/mfsu/mf-va_@alilc_lowcode-engine.js
http://localhost:8000/mf-dep____vendor.62d01dee.js:38:79
__webpack_require__
http://localhost:8000/mf-va_remoteEntry.js:23:42
(anonymous function)
http://localhost:8000/mf-va_remoteEntry.js:1499:105
__webpack_require__.m.<computed>
webpack:/ant-design-pro/webpack/runtime/remotes loading:2481
  2478 | var onFactory = function(factory) {
  2479 | 	data.p = 1;
  2480 | 	__webpack_require__.m[id] = function(module) {
> 2481 | 		module.exports = factory();
       | ^  2482 | 	}
  2483 | };
  2484 | handleFunction(__webpack_require__, data[2], 0, 0, onExternal, 1);
View compiled
options.factory
webpack:/ant-design-pro/webpack/runtime/react refresh:6
  3 | options.factory = function (moduleObject, moduleExports, webpackRequire) {
  4 | 	__webpack_require__.$Refresh$.setup(options.id);
  5 | 	try {
> 6 | 		originalFactory.call(this, moduleObject, moduleExports, webpackRequire);
    | ^  7 | 	} finally {
  8 | 		if (typeof Promise !== 'undefined' && moduleObject.exports instanceof Promise) {
  9 | 			options.module.exports = options.module.exports.then(
View compiled
__webpack_require__
.ant-design-pro/webpack/bootstrap:24
  21 | 	var execOptions = { id: moduleId, module: module, factory: __webpack_modules__[moduleId], require: __webpack_require__ };
  22 | 	__webpack_require__.i.forEach(function(handler) { handler(execOptions); });
  23 | 	module = execOptions.module;
> 24 | 	execOptions.factory.call(module.exports, module, module.exports, execOptions.require);
     | ^  25 | } catch(e) {
  26 | 	module.error = e;
  27 | 	throw e;
View compiled
▶ 3 stack frames were collapsed.
__webpack_require__
.ant-design-pro/webpack/bootstrap:24
  21 | 	var execOptions = { id: moduleId, module: module, factory: __webpack_modules__[moduleId], require: __webpack_require__ };
  22 | 	__webpack_require__.i.forEach(function(handler) { handler(execOptions); });
  23 | 	module = execOptions.module;
> 24 | 	execOptions.factory.call(module.exports, module, module.exports, execOptions.require);
     | ^  25 | } catch(e) {
  26 | 	module.error = e;
  27 | 	throw e;
View compiled
Function.fn
webpack:/ant-design-pro/webpack/runtime/hot module replacement:62
```

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
```
# 使用 npm
npm i @ant-design/pro-cli -g
pro create myapp
umi@4
simple
```
![image](https://user-images.githubusercontent.com/14910761/180791032-414d3154-7339-4fcb-968a-8b66cea73783.png)
![image](https://user-images.githubusercontent.com/14910761/180791081-2c66e39a-759a-4645-a602-244c8f4bf085.png)
![image](https://user-images.githubusercontent.com/14910761/180791298-ba0e91e5-4608-4047-94f2-e35e27a21dca.png)
```javascript
import React, { useState, useEffect } from 'react'
import { project, plugins, common, skeleton } from '@alilc/lowcode-engine'

// 此 schema 参考 demo 中的默认 schema 书写
import userSchema from './schema.json'

export default function EditorView() {
  /** 插件是否已初始化成功，因为必须要等插件初始化后才能渲染 Workbench */
  const [hasPluginInited, setHasPluginInited] = useState(false);

  useEffect(() => {
    plugins.init().then(() => {
      setHasPluginInited(true)
    }).catch(err => console.error(err))
  }, []);

  useEffect(() => {
    project.importSchema(userSchema)
  }, [userSchema]);

  if (!hasPluginInited) {
    return null;
  }

  return (
    <common.skeletonCabin.Workbench
      skeleton={skeleton}
    />
  );
}
```
---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
和Ant Design Pro整合

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [1.0.12] / 低代码引擎版本
 - AliLowCodeEngineExt version: [1.0.4] / 低代码引擎扩展包版本
 - Browser [chrome 97.0.4692.99] / 浏览器版本

**Comment by LeoYuan** [comment]
```<script src="https://g.alicdn.com/code/lib/prop-types/15.7.2/prop-types.js"></script>```

少引入了这一句？

**Comment by chenfeiwu** [comment]
> `<script src="https://g.alicdn.com/code/lib/prop-types/15.7.2/prop-types.js"></script>`
> 
> 少引了这句话？

不对呀 我这个是typescript工程呀

**Comment by LeoYuan** [comment]
看看官网demo的代码，有一个场景是使用antd组件

**Comment by chentiewei** [comment]
@chenfeiwu 你搞定了吗？求帮助！

**Comment by Yaya-20** [comment]
> 

您好， 请问下 这个问题怎么解决的

**Comment by chenfeiwu** [comment]
> 

{
  "name": "ant-design-pro",
  "version": "5.2.0",
  "private": true,
  "description": "An out-of-box UI solution for enterprise applications",
  "scripts": {
    "analyze": "cross-env ANALYZE=1 umi build",
    "build": "umi build",
    "deploy": "npm run build && npm run gh-pages",
    "dev": "npm run start:dev",
    "gh-pages": "gh-pages -d dist",
    "i18n-remove": "pro i18n-remove --locale=zh-CN --write",
    "postinstall": "umi g tmp",
    "lint": "umi g tmp && npm run lint:js && npm run lint:style && npm run lint:prettier && npm run tsc",
    "lint-staged": "lint-staged",
    "lint-staged:js": "eslint --ext .js,.jsx,.ts,.tsx ",
    "lint:fix": "eslint --fix --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src && npm run lint:style",
    "lint:js": "eslint --cache --ext .js,.jsx,.ts,.tsx --format=pretty ./src",
    "lint:prettier": "prettier -c --write \"src/**/*\" --end-of-line auto",
    "lint:style": "stylelint --fix \"src/**/*.less\" --syntax less",
    "openapi": "umi openapi",
    "playwright": "playwright install && playwright test",
    "prepare": "husky install",
    "prettier": "prettier -c --write \"src/**/*\"",
    "serve": "umi-serve",
    "start": "cross-env UMI_ENV=dev umi dev",
    "start:dev": "cross-env REACT_APP_ENV=dev MOCK=none UMI_ENV=dev umi dev",
    "start:no-mock": "cross-env MOCK=none UMI_ENV=dev umi dev",
    "start:no-ui": "cross-env UMI_UI=none UMI_ENV=dev umi dev",
    "start:pre": "cross-env REACT_APP_ENV=pre UMI_ENV=dev umi dev",
    "start:test": "cross-env REACT_APP_ENV=test MOCK=none UMI_ENV=dev umi dev",
    "test": "umi test",
    "test:component": "umi test ./src/components",
    "test:e2e": "node ./tests/run-tests.js",
    "tsc": "tsc --noEmit"
  },
  "lint-staged": {
    "**/*.less": "stylelint --syntax less",
    "**/*.{js,jsx,ts,tsx}": "npm run lint-staged:js",
    "**/*.{js,jsx,tsx,ts,less,md,json}": [
      "prettier --write"
    ]
  },
  "browserslist": [
    "> 1%",
    "last 2 versions",
    "not ie <= 10"
  ],
  "dependencies": {
    "@alilc/lowcode-engine": "^1.0.13",
    "@alilc/lowcode-engine-ext": "^1.0.4",
    "@ant-design/icons": "^4.7.0",
    "@ant-design/pro-components": "1.1.1",
    "@umijs/plugin-sass": "^1.1.1",
    "@umijs/route-utils": "^2.0.0",
    "antd": "^4.20.0",
    "classnames": "^2.3.0",
    "lodash": "^4.17.0",
    "moment": "^2.29.0",
    "node-sass": "^7.0.1",
    "omit.js": "^2.0.2",
    "rc-menu": "^9.1.0",
    "rc-util": "^5.16.0",
    "react": "^17.0.0",
    "react-dev-inspector": "^1.7.0",
    "react-dom": "^17.0.0",
    "react-helmet-async": "^1.2.0",
    "umi": "^3.5.0"
  },
  "devDependencies": {
    "@ant-design/pro-cli": "^2.1.0",
    "@playwright/test": "^1.17.0",
    "@types/classnames": "^2.3.1",
    "@types/express": "^4.17.0",
    "@types/history": "^4.7.0",
    "@types/jest": "^26.0.0",
    "@types/lodash": "^4.14.0",
    "@types/react": "^17.0.0",
    "@types/react-dom": "^17.0.0",
    "@types/react-helmet": "^6.1.0",
    "@umijs/fabric": "^2.11.1",
    "@umijs/openapi": "^1.6.0",
    "@umijs/plugin-blocks": "^2.2.0",
    "@umijs/plugin-esbuild": "^1.4.0",
    "@umijs/plugin-openapi": "^1.3.3",
    "@umijs/preset-ant-design-pro": "^1.3.0",
    "@umijs/preset-dumi": "^1.1.0",
    "@umijs/preset-react": "^2.1.0",
    "cross-env": "^7.0.0",
    "cross-port-killer": "^1.3.0",
    "detect-installer": "^1.0.0",
    "eslint": "^7.32.0",
    "gh-pages": "^3.2.0",
    "husky": "^7.0.4",
    "jsdom-global": "^3.0.0",
    "lint-staged": "^10.0.0",
    "mockjs": "^1.1.0",
    "prettier": "^2.5.0",
    "stylelint": "^13.0.0",
    "swagger-ui-dist": "^4.12.0",
    "typescript": "^4.5.0",
    "umi-serve": "^1.9.10",
    "@alilc/lowcode-react-renderer": "^1.0.13",
    "@alilc/lowcode-plugin-code-editor": "^1.0.3",
    "@alilc/lowcode-plugin-code-generator": "^1.0.4",
    "@alilc/lowcode-plugin-components-pane": "^1.0.3",
    "@alilc/lowcode-plugin-datasource-pane": "^1.0.5",
    "@alilc/lowcode-plugin-inject": "^1.1.3",
    "@alilc/lowcode-plugin-manual": "^1.0.3",
    "@alilc/lowcode-plugin-schema": "^1.0.1",
    "@alilc/lowcode-plugin-simulator-select": "^1.0.0",
    "@alilc/lowcode-plugin-zh-en": "^1.0.0",
    "@alilc/lowcode-setter-behavior": "^1.0.0",
    "@alilc/lowcode-setter-title": "^1.0.2",
    "@alilc/lowcode-utils": "^1.0.13"
  },
  "engines": {
    "node": ">=12.0.0"
  }
}

**Comment by b-yp** [comment]
同样遇到这个问题

**Comment by Osub** [comment]
我也是集成报错
```
TypeError: window.React is undefined
./node_modules/@alilc/lowcode-designer/es/builtin-simulator/utils/parse-metadata.js
```

**Comment by Osub** [comment]
> 同样遇到这个问题
> 
> 见这条回答：[#860 (comment)](https://github.com/alibaba/lowcode-engine/issues/860#issuecomment-1196457610) 在 `index.html` 中引入
> 
> 如果还有问题， 参考这个 demo 项目 https://github.com/alibaba/lowcode-demo/blob/main/demo-general/public/preview.html

ts 中如何导入？没有npm包吗？必须要用url的方式引入吗？
