### ISSUE TITLE
「咨询」引擎内的TransformStage不同阶段枚举值的区别是什么

### ISSUE THREAD

**Issue by xiaoqian-GUO** [alibaba/lowcode-engine#861]
## **Describe the bug (required)** / **详细描述 bug（必填）**

Render = 'render'
Serilize = 'serilize'
Save = 'save'
Clone = 'clone'
Init = 'init'
Upgrade = 'upgrade'

不同阶段的枚举值的含义有什么区别，什么场景触发什么阶段？

---

**Comment by liujuping** [comment]
不同的 TransformStage 获取到的 schema 会有一些轻微的差异，具体的差异可以看看代码，这里列出来一些我了解的
'render'：在设计器画布中渲染时，比如 JSSlot 在设计器中会有 value，也就是展示 Slot 的插槽占位
'init'：初始化阶段
'save'：最终保存的 schema，比如 JSSlot 如果没有拖拽组件进去，就不会展示组件了

**Comment by LeoYuan** [comment]
```
Render = 'render'
Serilize = 'serilize'
Save = 'save'
Clone = 'clone'
```
前四个是在 导出Schema（exportSchema） 时用到，用于导出不同用途的 schema，比如在设计器渲染时有插槽节点（此时使用 render），而在真正预览的时候没有（此时使用 save）~
*ps: 其中 clone / serilize 不常用到*

```
Init = 'init'
Upgrade = 'upgrade'
```
后两个主要是在初始化节点模型时用到，用于初始化期间对原始 props 做一些钩子函数处理~

所有 6 个都能通过 [addPropsTransducer](https://www.yuque.com/lce/doc/dcrbff#SO4No) 来注册钩子函数，分别在 初始化 和 导出 Schema 阶段被调用~
