### ISSUE TITLE
表单容器可以作为根节点如何实现？

### ISSUE THREAD

**Issue by haoziqaq** [alibaba/lowcode-engine#864]
看到宜搭的表单设计器可以直接将一个表单容器作为根节点，而不使用page，引擎可以实现这个功能么

**Comment by LeoYuan** [comment]
https://github.com/alibaba/lowcode-engine/blob/690aaa1ce4af5c45f14b205cd8f54168e2be7b54/packages/designer/src/document/document-model.ts#L90

试试在引擎 init 之前设置 focusNodeSelector~

```ts
config.set('focusNodeSelector', (root) => { return 你的 Node });
```
