### ISSUE TITLE
设置器高级面板的循环条件编辑时对应界面渲染不正确

### ISSUE THREAD

**Issue by Lanzz1994** [alibaba/lowcode-engine#867]
## 复现截图
正常：
![image](https://user-images.githubusercontent.com/29368329/181190869-97e14a64-3c9a-463b-8788-93e8620fead0.png)
编辑后渲染数据展示异常
![image](https://user-images.githubusercontent.com/29368329/181190038-8f5af8f3-9956-4850-883b-5d2a91efabb6.png)
每次编辑循环条件的输入框onChange时，循环渲染出来的数据都会增加
## 期望结果
编辑循环条件界面数据渲染正常展示
## 环境信息

- 引擎版本 1.0.11
- ext 版本 1.0.3
- 物料
  - moment﹫2.24.0
  - lodash
  - iconfont-icons
  - ﹫ant-design/icons﹫4.7.0
  - antd﹫4.19.5
  - ﹫alifd/next﹫1.23.0
  - ﹫alilc/antd-lowcode-materials﹫1.0.6

**Comment by JackLian** [comment]
麻烦提供复现步骤或demo，相关说明参考 https://www.yuque.com/lce/doc/yvlxhs

**Comment by 946629031** [comment]
> 麻烦提供复现步骤或demo，相关说明参考 https://www.yuque.com/lce/doc/yvlxhs

reply test
