### ISSUE TITLE
可以提供整合ant-design/fusion -design的资料或demo吗

### ISSUE THREAD

**Issue by chenfeiwu** [alibaba/lowcode-engine#872]
官网没有整合这两个design的资料

**Comment by LeoYuan** [comment]
具体指的是什么？引擎对物料没有限制，手写普通 React 组件都行~

**Comment by chenfeiwu** [comment]
> 具体指的是什么？引擎对物料没有限制，手写普通 React 组件都行~

就是我需要把引擎整合到ant-design/fusion -design工程里面，通过引模块的方式加载进来

**Comment by LeoYuan** [comment]
是引擎依赖物料，不是物料依赖引擎，所以应该站在引擎的视角去看如何使用物料~

要不你先看看这个 [demo](http://lowcode-engine.cn/demo) 以及相应的[代码](https://github.com/alibaba/lowcode-demo) ，相关的官方文档 / issue 都可以浏览一遍~

**Comment by chenfeiwu** [comment]
> 是引擎依赖物料，不是物料依赖引擎，所以应该站在引擎的视角去看如何使用物料~
> 
> 要不你先看看这个 [demo](http://lowcode-engine.cn/demo) 以及相应的[代码](https://github.com/alibaba/lowcode-demo) ，相关的官方文档 / issue 都可以浏览一遍~

明白了，引擎应该独立于所有物料的，所以我要在上层做类似表单服务这样的低代码平台，只需要在这个引擎工程去构建是吧，而这些design工程去调用渲染就行了
