### ISSUE TITLE
服务端出码Cannot read properties of undefined (reading 'icejs')

### ISSUE THREAD

**Issue by versole** [alibaba/lowcode-engine#873]
![image](https://user-images.githubusercontent.com/36833118/181444205-cfec70d0-d78d-42d9-9fa1-04c4407cc0fb.png)
按照文档走的步骤，报错Cannot read properties of undefined (reading 'icejs')就这几行代码

**Comment by LeoYuan** [comment]
可能文档写漏了，可以参考code-generator-demo的代码（仓库在置顶issue有写）
