### ISSUE TITLE
数据源新建报错

### ISSUE THREAD

**Issue by zandko** [alibaba/lowcode-engine#874]
![IMG-2022-07-28-15 21 08@2x](https://user-images.githubusercontent.com/37948383/181445361-0425c9cc-c365-4ae8-8db3-312cef917772.png)
<img width="339" alt="IMG-2022-07-28-15 22 32@2x" src="https://user-images.githubusercontent.com/37948383/181445530-db32d6bc-0770-4b11-b34b-6645e4232fa8.png">
<img width="360" alt="IMG-2022-07-28-15 22 47@2x" src="https://user-images.githubusercontent.com/37948383/181445562-fa80e461-3157-4791-815c-06d6457b8422.png">
<img width="525" alt="IMG-2022-07-28-15 22 56@2x" src="https://user-images.githubusercontent.com/37948383/181445590-6f5b3697-84a2-4be9-b3de-ab76797217bc.png">

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.13] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.4] / 低代码引擎扩展包版本)

**Comment by LeoYuan** [comment]
![image](https://user-images.githubusercontent.com/1195765/182061108-45f16bfa-0e90-4688-b842-613e71d9a05c.png)

怎么复现的？现象很重要，精确的复现步骤更重要~

**Comment by twinkle77** [comment]
无法复现  @zandko
