### ISSUE TITLE
物料项目---折叠面板accordion不支持默认折叠？

### ISSUE THREAD

**Issue by chenrunsong** [alibaba/lowcode-engine#875]
## **Describe the bug (required)** / **详细描述 bug（必填）**
物料项目 meta.ts中物料描述，"display": 'accordion'渲染为折叠面板时不支持默认折叠
A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**
![image](https://user-images.githubusercontent.com/21167854/181472484-7e0384b4-8ef7-4ea0-a6ef-7b8f611766e2.png)

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为
可以设置默认折叠，否则在面板太多的情况下，非常麻烦
---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
![image](https://user-images.githubusercontent.com/21167854/181472698-46250c0d-82a4-4ca2-b9e2-f83b8b3d5c71.png)
![image](https://user-images.githubusercontent.com/21167854/181472855-cd660a19-f371-485e-835d-3a171f019b27.png)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - 
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 chrome  98.0.4758.102
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by LeoYuan** [comment]
看看demo中存在的assets.json，我记得有默认折叠的示例

**Comment by LeoYuan** [comment]
```
{
  "name": "advanced",
  "title": "高级",
  "type": "group",
  "extraProps": {
    "display": "accordion", // 写外面也行
    "defaultCollapsed": true // 控制默认折叠
  }
}
```

@chenrunsong

**Comment by chenrunsong** [comment]
test ok！
