### ISSUE TITLE
lowcode-tools/packages/lowcode-plugin-inject/package.json  配了module入口，实际上没生成es文件夹

### ISSUE THREAD

**Issue by meizilove258** [alibaba/lowcode-engine#876]
lowcode-tools/packages/lowcode-plugin-inject/package.json  配了module入口，实际上打包输出没生成es文件夹，vite用的esbuild时会报错，webpack不会报错，能生成个es文件夹嘛

<img width="1059" alt="image" src="https://user-images.githubusercontent.com/29622627/181472334-614662b3-8f27-44c3-9255-210bd0577b1a.png">

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/29622627/181473283-5eaea69e-7291-478a-b817-31a5759ca80b.png">

**Comment by eternalsky** [comment]
感谢反馈，最新版已修复
