### ISSUE TITLE
设置器面板中图标不显示

### ISSUE THREAD

**Issue by MrShenPH** [alibaba/lowcode-engine#877]
## **Describe the bug (required)** / **详细描述 bug（必填）**
A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述

设置器面板中有些属性的图标没有显示，是哪个cdn资源没有引入进来吗？
---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题
![1659009203391](https://user-images.githubusercontent.com/22426016/181499041-a6eb394d-65a5-451b-a988-26553e9fe4f8.jpg)
![1659009175135](https://user-images.githubusercontent.com/22426016/181499065-2eb4e243-0e34-4f76-be3f-4b78d2004a12.jpg)

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [1.0.8] / 低代码引擎版本
 - AliLowCodeEngineExt version: [1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by LeoYuan** [comment]
看看是不是什么资源被屏蔽了？

**Comment by Lin9672** [comment]
请问这个问题是如何解决的呀？

**Comment by haledeng** [comment]
@MrShenPH check 一下 //at.alicdn.com/t/font_2761185_gdpwg9vnz7.js 资源是否加在了。这里是自定义的 Icon，是需要额外加在 JS 资源的，如果没有加载，可以查一下自定义 ICON 部分的代码。目前是在 window.onload 或者 docoment 的事件中触发的，是否事件没有触发。
