### ISSUE TITLE
lowcode-plugin-simulator-select插件引用错误

### ISSUE THREAD

**Issue by baieceo** [alibaba/lowcode-engine#88]
lowcode-plugin-simulator-select/lib/index.js第14行var _lowcodeEngine = require("@ali/lowcode-engine");运行时会报错，应为var _lowcodeEngine = require("@alilc/lowcode-engine");

**Comment by LeoYuan** [comment]
感谢提醒，该插件代码仍未开源，在应用层面可以通过配置兼容一下：https://github.com/alibaba/lowcode-demo/blob/6a26531007e79ed83ec074ec515f38db2a676756/build.json#L20

**Comment by baieceo** [comment]
> 感谢提醒，该插件代码仍未开源，在应用层面可以通过配置兼容一下：https://github.com/alibaba/lowcode-demo/blob/6a26531007e79ed83ec074ec515f38db2a676756/build.json#L20

烦请更新下http://lowcode-engine.cn/doc?url=start-with-lce配置打包部分吧

**Comment by alvarto** [comment]
嗯嗯，已修正，感谢指出
