### ISSUE TITLE
demo中默认的注册setter去掉之后依然有设置面板

### ISSUE THREAD

**Issue by versole** [alibaba/lowcode-engine#880]
![image](https://user-images.githubusercontent.com/36833118/181693320-f10a8c08-27ee-4129-b58e-2037a428705c.png)
我已经把注册设置器注释了，并且在demo项目删除了lowcode-engine-ext依赖，但是demo项目依然完好无损的跑起来了。。。所以这个注册setter的作用是？

**Comment by LeoYuan** [comment]
看了下引擎内部默认的插件也会注册这些 setters，可以通过 disableDefaultSetters: true 去禁用掉~

https://github.com/alibaba/lowcode-engine/blob/9459ac543eadd5f6d9023c4fa3f168ff03ecc64a/packages/engine/src/engine-core.ts#L111-L123
