### ISSUE TITLE
@alilc/lowcode-react-renderer在钉钉小程序中运行失败

### ISSUE THREAD

**Issue by sprufu** [alibaba/lowcode-engine#882]
希望在钉钉小程序中使用react渲染模块，在引入这模块后运行失败，报TypeError: Function(...) is not a function错误，请问目前是没有考虑小程序的兼容还是使用存在错误？

**Comment by LeoYuan** [comment]
小程序得用 rax-renderer~

你这个报错似乎是 Function 在小程序的 JS 运行环境不存在

**Comment by sprufu** [comment]
谢谢您的帮助，请问只是替换为@alilc/lowcode-rax-renderer吗，是要不要需要其它的配置，现在有没有相关的demo.

**Comment by JackLian** [comment]
应该不止，得看看你现在是咋用的，麻烦提供下具体复现的的步骤吧，如果设计的部分是react，用raxrender也没用
参考 https://lowcode-engine.cn/docV2/yvlxhs

另外目前确实没有提供rax相关的demo

**Comment by sprufu** [comment]
谢谢大家的帮助，之前没有接触rax，先学习学习rax再来尝试，谢谢
