### ISSUE TITLE
[QUESTION] 何时支持ice.js 2.x

### ISSUE THREAD

**Issue by xmsz** [alibaba/lowcode-engine#883]
## **Describe the bug (required)** / **详细描述 bug（必填）**

- 使用ice.js 2.x
- 根据文档安装@alilc/lowcode-engine、项目启动依赖失败
- 

而且我使用cdn引入，直接报错未找到react，感觉搭配不起来啊

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---
DEMO:https://github.com/xmsz/demo-20220804

中文版示例：
1. 创建icejs项目
2. 安装@alilc/lowcode-engine
3. 启动项目
4. 启动失败，报错说依赖打包问题

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

可以集成在icejs里

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version:  最新
 - AliLowCodeEngineExt version: 最新
 - Browser: chorme
 - icejs: 2.x

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

就是在icejs里构建起来，就怎么简单

```
pnpm create icejs
pnpm i --shamefully-hoist
pnpm i  @alilc/lowcode-engine
npm run start

```

**Comment by xmsz** [comment]
> 你好 @xmsz，由于缺乏必要的信息（如 bug 重现步骤、引擎版本信息 等），无法定位问题，请按照 [issue bug 模板](https://github.com/alibaba/lowcode-engine/blob/main/.github/ISSUE_TEMPLATE/bug-report.md) 补全信息，也可以通过阅读[引擎的 issue 说明](https://www.yuque.com/lce/doc/yvlxhs) 了解什么类型的 issue 可以获得更好、更快的支持。

已补充

**Comment by liujuping** [comment]
需要提供更加完整的复现步骤。参考：https://www.yuque.com/lce/doc/yvlxhs

![image](https://user-images.githubusercontent.com/11935995/182780345-31a125c3-66d6-41fd-b608-94d6935e8882.png)

**Comment by xmsz** [comment]
> 需要提供更加完整的复现步骤。参考：https://www.yuque.com/lce/doc/yvlxhs
> 
> ![image](https://user-images.githubusercontent.com/11935995/182780345-31a125c3-66d6-41fd-b608-94d6935e8882.png)

DEMO: https://github.com/xmsz/demo-20220804

**Comment by LeoYuan** [comment]
![image](https://user-images.githubusercontent.com/1195765/183411208-372bf7f4-9b8f-4b7c-830d-367312191166.png)

**Comment by xmsz** [comment]
> ![image](https://user-images.githubusercontent.com/1195765/183411208-372bf7f4-9b8f-4b7c-830d-367312191166.png)

我知道 我想用代码提示能力

**Comment by liujuping** [comment]
你的这个项目去掉 @alilc/lowcode-engine 相关的逻辑，跑起来都是有问题的。

先想办法正常启动项目，再通过 cdn 的方式引入 lowcode-engine。（需要配置 extends 等，保障 lowcode-engine 不会打包进去）

这个问题就先关掉了，如果有其他问题可以提新的 issue。
