### ISSUE TITLE
@alife/container 这个包好像没有发布到外网？

### ISSUE THREAD

**Issue by versole** [alibaba/lowcode-engine#884]
fusion ui出码之后依赖这个包，但是这个包好像没发到npmjs

**Comment by LeoYuan** [comment]
@mark-ck 帮忙看看？😄

**Comment by liujuping** [comment]
@versole 这个复现路径辛苦描述一下。

**Comment by versole** [comment]
> @versole 这个复现路径辛苦描述一下。

使用base  fusion ui 中的组件搭建完之后，出码构建。构建失败。因为构建出来的项目中依赖@alife/container这个包，但是这个包没有发布到npmjs源上。 导出的schema中包含了类似{
            "package": "@alife/container",
            "version": "0.3.7",
            "exportName": "P",
            "main": "lib/index.js",
            "destructuring": true,
            "subName": "Cell",
            "componentName": "NextPCell"
        }, 依赖的包是这个

**Comment by liujuping** [comment]
@versole 经过讨论，由于这个 @alife/container 包还没具备发布外网的条件，目前的方案是把 @alife/container 包相关的组件在对应的场景中删掉。
