### ISSUE TITLE
[QUESTION]按照官网的使用umd方法跑不起来

### ISSUE THREAD

**Issue by xmsz** [alibaba/lowcode-engine#885]
## **Describe the bug (required)** / **详细描述 bug（必填）**

我参考官网，写了
```
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Document</title>
    <!-- 低代码引擎的页面框架样式 -->
    <link
      rel="stylesheet"
      href="https://alifd.alicdn.com/npm/@alilc/lowcode-engine@latest/dist/css/engine-core.css"
    />
    <!-- Fusion Next 控件样式 -->
    <link
      rel="stylesheet"
      href="https://g.alicdn.com/code/lib/alifd__next/1.23.24/next.min.css"
    />
    <!-- 低代码引擎的页面主题样式，可以替换为 theme-lowcode-dark -->
    <link
      rel="stylesheet"
      href="https://alifd.alicdn.com/npm/@alifd/theme-lowcode-light/0.2.0/next.min.css"
    />
    <!-- 低代码引擎官方扩展的样式 -->
    <link
      rel="stylesheet"
      href="https://alifd.alicdn.com/npm/@alilc/lowcode-engine-ext@latest/dist/css/engine-ext.css"
    />

    <!-- React，可替换为 production 包 -->
    <script src="https://g.alicdn.com/code/lib/react/16.14.0/umd/react.development.js"></script>
    <!-- React DOM，可替换为 production 包 -->
    <script src="https://g.alicdn.com/code/lib/react-dom/16.14.0/umd/react-dom.development.js"></script>
    <!-- React 向下兼容，预防物料层的依赖 -->
    <script src="https://g.alicdn.com/code/lib/prop-types/15.7.2/prop-types.js"></script>
    <script src="https://g.alicdn.com/platform/c/react15-polyfill/0.0.1/dist/index.js"></script>
    <!-- lodash，低代码编辑器的依赖 -->
    <script src="https://g.alicdn.com/platform/c/lodash/4.6.1/lodash.min.js"></script>
    <!-- 日期处理包，Fusion Next 的依赖 -->
    <script src="https://g.alicdn.com/code/lib/moment.js/2.29.1/moment-with-locales.min.js"></script>
    <!-- Fusion Next 的主包，低代码编辑器的依赖 -->
    <script src="https://g.alicdn.com/code/lib/alifd__next/1.23.24/next.min.js"></script>
    <!-- 低代码引擎的主包 -->
    <script
      crossorigin="anonymous"
      src="https://alifd.alicdn.com/npm/@alilc/lowcode-engine@latest/dist/js/engine-core.js"
    ></script>
    <!-- 低代码引擎官方扩展的主包 -->
    <script
      crossorigin="anonymous"
      src="https://alifd.alicdn.com/npm/@alilc/lowcode-engine-ext@latest/dist/js/engine-ext.js"
    ></script>
  </head>
  <body>
    <div id="lce-container"></div>
    <script>
      window.AliLowCodeEngine.init(document.getElementById("lce-container"), {
        enableCondition: true,
        enableCanvasLock: true,
      });
    </script>
  </body>
</html>
```

结果运行起来，没有报错，但是界面长这样
![127 0 0 1_5500_index html](https://user-images.githubusercontent.com/5879146/182020934-5419452e-19eb-4821-9a95-57ba0db2a655.png)

这是正常的吗？

还有我想直接在现有项目icejs中使用，有没有更方便的方法？

脑袋疼，搞了半天出了demo项目能跑起来 其他都不行 难道编辑器只有在demo项目扩展吗？

有没有成功使用icejs2或者vite项目的？

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

---

English version example：

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by LeoYuan** [comment]
建议你给个完整示例项目，这样才能更好排查问题~

**Comment by xmsz** [comment]
> 建议你给个完整示例项目，这样才能更好排查问题~

我有贴代码，直接index.html跑就行

**Comment by LeoYuan** [comment]
可以看下 DOM，容器没有设置高度，所以只展示了部分，另外这是个裸的引擎，没有其他插件，对于刚开始使用引擎，建议还是从 Demo 项目开始了解，引擎、插件、物料、设置器以及工程化配置~
