### ISSUE TITLE
如何禁止一个节点的拖拽

### ISSUE THREAD

**Issue by haoziqaq** [alibaba/lowcode-engine#886]
<img width="1091" alt="image" src="https://user-images.githubusercontent.com/24223652/182108449-060957ce-6de2-4a20-80bb-e2983711f1f3.png">

我尝试使用这个配置项解决问题，copy 和 remove 是有效果的，但是 move 禁用不了

**Comment by LeoYuan** [comment]
看下物料描述的 onMoveHook 部分~

**Comment by haoziqaq** [comment]
解决了 感谢
