### ISSUE TITLE
如何引入其他npm包

### ISSUE THREAD

**Issue by StepByBo** [alibaba/lowcode-engine#887]
想要将页面中的表格导出为excel，如何引入excel相关的包，在低代码平台中使用？

**Comment by LeoYuan** [comment]
你就看低代码的产物 - 符合搭建协议的 JSON 结构能否生成 excel~

**Comment by StepByBo** [comment]
但是希望在低代码页面中实现导出功能，例如点击按钮触发导出，所以如何在低代码平台中导入能够生成excel的相关插件？

**Comment by StepByBo** [comment]
> 你就看低代码的产物 - 符合搭建协议的 JSON 结构能否生成 excel~
但是希望在低代码页面中实现导出功能，例如点击按钮触发导出，所以如何在低代码平台中导入能够生成excel的相关插件？

**Comment by StepByBo** [comment]
> 你就看低代码的产物 - 符合搭建协议的 JSON 结构能否生成 excel~

但是希望在低代码页面中实现导出功能，例如点击按钮触发导出，所以如何在低代码平台中导入能够生成excel的相关插件？

**Comment by LeoYuan** [comment]
感觉不是插件，就是点击按钮的回调调用某个excel库？excel库直接在html里（假如是渲染画布，在assets.json里）引入就好了~
