### ISSUE TITLE
@alilc/lowcode-utils/es/aeeset.js中 export {xxx, xxx, xxx} from '@alilc/lowcode-types' 向外导出不存在的变量

### ISSUE THREAD

**Issue by meizilove258** [alibaba/lowcode-engine#890]
@alilc/lowcode-utils/es/aeeset.js中 export {AssetItem, AssetType, AssetLevels, Asset, AssetList, AssetBundle, AssetLevel, AssetsJson} from '@alilc/lowcode-types' 向外导出不存在的变量（@alilc/lowcode-types下没有这样的变量），vite使用的esbuild，esbuild的transform环节，会报错，具体文件地址和报错信息如下图。webpack可能会对这种有处理，不会报错。不存在的变量的导出能出掉下嘛

<img width="1359" alt="image" src="https://user-images.githubusercontent.com/29622627/182549581-f7a5f820-b379-44a9-9c43-09b632f44734.png">

<img width="1486" alt="image" src="https://user-images.githubusercontent.com/29622627/182549054-3d7e9830-c7a0-457d-ab05-6321cec11d03.png">

<img width="1588" alt="image" src="https://user-images.githubusercontent.com/29622627/182549522-bf983912-0605-4ab4-af97-866d1bc5ee97.png">

**Comment by meizilove258** [comment]
有人嘛

**Comment by ZhelinCheng** [comment]
兄die解决了吗？

**Comment by meizilove258** [comment]
> 兄die解决了吗？

解决了
<img width="927" alt="image" src="https://user-images.githubusercontent.com/29622627/184330154-da0b0486-b7e6-4efd-96d8-343e28fd2e35.png">

**Comment by forcs** [comment]
> > 兄die解决了吗？
> 
> 解决了 <img alt="image" width="927" src="https://user-images.githubusercontent.com/29622627/184330154-da0b0486-b7e6-4efd-96d8-343e28fd2e35.png">

确定解决了？貌似，内部依赖的@alilc/lowcode-engine-ext还是会报错，怎么解？
<img width="708" alt="截屏2022-08-14 17 58 38" src="https://user-images.githubusercontent.com/1214543/184531930-e158fe6e-2ea4-43e2-a5fb-304599dfaf78.png">

**Comment by meizilove258** [comment]
> 我是上周五是用vite去构建的，发现还是报错。

主包更新到1.0.14时，测试这儿的功能请看上面的截图，现在主包还没更新，等着更新就好啦。

**Comment by sunhannie** [comment]
9月份2号还是报错

**Comment by meizilove258** [comment]
https://alifd.alicdn.com/npm/@alilc/lowcode-engine@1.0.14-beta.2/dist/js/engine-core.js    用这个来试试

**Comment by meizilove258** [comment]
> 9月份2号还是报错

<img width="466" alt="image" src="https://user-images.githubusercontent.com/29622627/188078647-556028fa-f151-414b-aa19-ca616a525b7d.png">


https://alifd.alicdn.com/npm/@alilc/lowcode-engine@1.0.14-beta.2/dist/js/engine-core.js 主包用这个，其它依赖升级如下
"@alilc/lowcode-react-renderer": "1.0.14-beta.2",
 "@alilc/lowcode-utils": "1.0.14-beta.2", 

其中"@alilc/lowcode-plugin-inject": "^1.1.3"这个包的node_modules下面有@alilc/lowcode-utils这个时，把它删了。这样用最外层node_modules下面的@alilc/lowcode-utils，就可以了。

总之，就是依赖包版本的问题，要是报错，你就看看对应包的版本是否是 1.0.14.beta.2
