### ISSUE TITLE
@alilc/element脚手架生成的meta.ts无法使用props.title属性

### ISSUE THREAD

**Issue by jingjingzhao** [alibaba/lowcode-engine#891]
## **Describe the bug (required)** / **详细描述 bug（必填）**

使用@alilc/element脚手架创建的物料项目，执行`lowcode:dev`后，自动生成的`/lowcode/xx/meta.ts`文件中，类型`ComponentMetadata`的`props`，没有`title`属性。我使用 props.title，页面上也没生效。
但开源的`lowcode-materials`库，`/lowcode/xx/meta.ts`文件中，props属性都使用了title，且页面上能生效。
为什么？

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
1. 执行 `npm init @alilc/element your-element-name` 
2. 自定义component
3. 执行`npm run lowcode:dev`
![image](https://user-images.githubusercontent.com/5880014/182605016-6adb3250-60fe-4d94-b5f8-8ac6ee3dc67e.png)

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

希望可以像官方开源的物料一样使用meta里的各个属性

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [1.0.6] / 低代码引擎版本
 - AliLowCodeEngineExt version: [1.0.3] / 低代码引擎扩展包版本
 - "@alib/build-scripts": "^0.1.3",
 - "@alifd/build-plugin-lowcode": "^0.3.0",

**Comment by LeoYuan** [comment]
> 但开源的lowcode-materials库，/lowcode/xx/meta.ts文件中，props属性都使用了title，且页面上能生效。

页面上能生效是指属性配置中有 title 这个属性？

**Comment by jingjingzhao** [comment]
![image](https://user-images.githubusercontent.com/5880014/184809072-8919816f-b1fc-4a32-a873-7897c45eeab6.png)
![image](https://user-images.githubusercontent.com/5880014/184809170-1b1393bc-19d5-495d-ba11-f099a1ca9d87.png)

**Comment by LeoYuan** [comment]
是 isExtends 导致的，外层的 props 是入料模块自动生成的，内层的 configure.props 是人工设置的，但会覆盖外层，需要加上 isExtends，具体参考：

https://github.com/alibaba/lowcode-demo/blob/a28106d451a869404933f5f1e84bae096df4abb6/src/scenarios/basic-fusion/assets.json#L485

**Comment by jingjingzhao** [comment]
「外层的 props 是入料模块自动生成的，内层的 configure.props 是人工设置的」，是不是写反了？
我执行 `lowcode:dev` 自动生成的meta.ts中，有内层的 configure.props，无外层的 props。
我另一个疑问是，我手动去写外层的props，ts定义中并没有外层的 props.title 属性，如上图会飘红，且配置了页面上也不生效。为啥 lowcode-materials项目可以这么用，且生效呢？ @LeoYuan

**Comment by LeoYuan** [comment]
从物料描述协议来看，configure字段下都属于体验增强，所以应该这部分是个性化配置的。

props.title为啥不生效，你测试过isExtends了么，可以看下代码parse-props.ts怎么处理props 和 configure.props的关系。

**Comment by jingjingzhao** [comment]
看了源码，懂了。
看来是ts有些属性没加上或类型定义有问题。
1. prop-config.ts中 `PropConfig`，缺少`title`定义；
2. metadata.ts中`TransformedComponentMetadata`中`Configure`的`props`，类型是 FieldConfig[] | FieldConfig 吧？`FieldConfig`里缺少 `override`定义 等

大佬啥时候补一下 ts 呀 @LeoYuan 
![image](https://user-images.githubusercontent.com/5880014/186111973-0c558394-562d-4c88-bfbf-ebe8c53bd23f.png)

**Comment by LeoYuan** [comment]
求PR 😃
