### ISSUE TITLE
启动后界面异常

### ISSUE THREAD

**Issue by zhouxinyong** [alibaba/lowcode-engine#9]
按照Readme步骤
1. npm install
2. npm run setup
3. npm run start

启动成功：
![image](https://user-images.githubusercontent.com/15569753/154438609-3d1601d2-4a2c-410a-9d4b-eafed3fa324e.png)

打开链接后显示如下：
![image](https://user-images.githubusercontent.com/15569753/154438689-f6eae5ec-4599-4048-9658-6f5b352e0c7e.png)

**Comment by m-yangyu** [comment]
他这个目前只是单纯的打出几个模块包，但是需要一个页面去进行承载，但是我发现。。他的一个cdn包是AliLowCodeEngineExt，这个不知道怎么用。。

**Comment by LeoYuan** [comment]
demo 稍后就会放出哈，demo 整合了引擎内核，物料，setter和插件，需要一些时间打磨一下😃

**Comment by m-yangyu** [comment]
哦~， 对不起是我搞错了，原来这个引入之后是一个去空白的模板，需要自己一个个配置上去的
