### ISSUE TITLE
超级严重的bug

### ISSUE THREAD

**Issue by Blizzard-liu** [alibaba/lowcode-engine#90]
## **Describe the bug (required)** / **详细描述 bug（必填）**

原子组件 下的 树形选择控件 拖拽到页面就崩溃了

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

![image](https://user-images.githubusercontent.com/20244432/157197521-42eed7bd-f3c3-4500-9c95-a6d8203be4ef.png)
![image](https://user-images.githubusercontent.com/20244432/157197568-7c3f8eb3-46ff-40ec-bb36-bc07919f0de4.png)

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
应该正常显示

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
- 引擎版本 1.0.0-beta.22
- ext 版本 1.0.0
- 物料
  - moment﹫2.24.0
  - lodash
  - ﹫alifd/next﹫1.24.18
  - NextTable﹫1.0.1
  - ﹫alilc/lowcode-materials﹫1.0.1
  - ﹫alifd/pro-layout﹫1.0.1-beta.5
  - ﹫alifd/fusion-ui﹫1.0.5-beta.1

**Comment by alvarto** [comment]
@mark-ck 看起来 assets.json 的版本号需要更新

**Comment by mark-ck** [comment]
> @mark-ck 看起来 assets.json 的版本号需要更新

@Blizzard-liu 这个问题应该已经解决掉了，demo 最新版本没有这个问题，可以参考 demo 里的 engine 和 engine-ext 的版本更新下 https://github.com/alibaba/lowcode-demo/blob/main/public/index.html

**Comment by Blizzard-liu** [comment]
我查看的就是你们官网的demo    http://lowcode-engine.cn/demo

**Comment by mark-ck** [comment]
@alvarto @LeoYuan 
这个 demo 里的版本好像有点老了，更新一下吧

> 我查看的就是你们官网的demo http://lowcode-engine.cn/demo

**Comment by alvarto** [comment]
@liujuping 看看官网的 demo 是不是没有更新到最新版？

**Comment by mark-ck** [comment]
> 大佬 采访下 为什么选择开源 准备把我们这些初级程序员都干失业吗

初级 只是一个阶段，你很快就会到中级、高级这些阶段，不用担心；
说下我的理解，不一定对，你可以参考下，开源是为了减少低水平的重复建设，同样的东西不要你搞一套我搞一套，大家一起研究更深入的东西是不是更好

**Comment by LeoYuan** [comment]
@Blizzard-liu 先用这个 https://alifd.alicdn.com/npm/@alilc/lowcode-demo@1.0.0/build/index.html

@liujuping 考虑下，官网 demo 直接 302 到上面的地址？

**Comment by Blizzard-liu** [comment]
@mark-ck 开源好的很啊 造福我们小兵   我们公司正准备做一个低代码平台  调研了几天 毫无头绪 你们真是及时雨啊  本来准备对drawio进行二次开发的  但是事件绑定 数据绑定这块没有头绪    目前市面上的开源低代码引擎你们是第一个吧  有没有竞品 我去吐槽下

**Comment by Blizzard-liu** [comment]
我下班了  明天见哈

**Comment by liujuping** [comment]
> @Blizzard-liu 先用这个 https://alifd.alicdn.com/npm/@alilc/lowcode-demo@1.0.0/build/index.html
> 
> @liujuping 考虑下，官网 demo 直接 302 到上面的地址？

已重定向到上面的地址。
