### ISSUE TITLE
@alilc/element 生成多物料库，npm i 安装依赖报错

### ISSUE THREAD

**Issue by SamWeichangyue** [alibaba/lowcode-engine#904]
## **@alilc/element 生成多物料库，npm i 安装依赖报错**

跟着官网的步骤走生成react多组件库，npm i时 报错

---

中文版示例：
1. npm init @alilc/element test-demo
2. choose 组件/物料，后续都选默认；
3. 模式 选择 react-组件库；
4. npm i 报错；
5. **platform: mac,
node: 16.13.0
npm: 8.1.0**
---
![WX20220804-195110](https://user-images.githubusercontent.com/30724369/182840868-d6dae72f-cae6-4aaa-acbe-8337b312f93b.png)

## **定位**
目前定位是colors 撤销包导致，影响到build-plugin-component-multiple这个包

**Comment by eternalsky** [comment]
本地实测使用官方 npm 源没有收到 colors 撤包影响，请看一下是不是设置的特殊npm 源导致的。
<img width="483" alt="截屏2022-08-05 上午10 43 39" src="https://user-images.githubusercontent.com/8038928/182990525-75e71214-14ae-4c8f-ba68-1632087d58bd.png">

**Comment by SamWeichangyue** [comment]
> 本地实测使用官方 npm 源没有收到 colors 撤包影响，请看一下是不是设置的特殊npm 源导致的。 <img alt="截屏2022-08-05 上午10 43 39" width="483" src="https://user-images.githubusercontent.com/8038928/182990525-75e71214-14ae-4c8f-ba68-1632087d58bd.png">

排查了下，可能是私有npm源缓存了公有源的包，然后公有撤包，私有源还有缓存

**Comment by SamWeichangyue** [comment]
> 本地实测使用官方 npm 源没有收到 colors 撤包影响，请看一下是不是设置的特殊npm 源导致的。 <img alt="截屏2022-08-05 上午10 43 39" width="483" src="https://user-images.githubusercontent.com/8038928/182990525-75e71214-14ae-4c8f-ba68-1632087d58bd.png">

排查了下，可能是私有npm源缓存了公有源的包，然后公有撤包，私有源还有缓存
