### ISSUE TITLE
lowcode-demo项目升级后，旧版数据无法在preview页面中加载

### ISSUE THREAD

**Issue by minibill11** [alibaba/lowcode-engine#906]
## **Describe the bug (required)** / **详细描述 bug（必填）**

我在历史版本中存储了数据，
![image](https://user-images.githubusercontent.com/25745175/182844032-917c4fb7-091f-4582-a3af-0631adddbdc1.png)

其中componentsMap里面带了版本信息，

更新最新版本的lowcode-demo后，数据的version发生了改变
![image](https://user-images.githubusercontent.com/25745175/182844307-82721a55-9608-4acc-9d18-263c1eba3588.png)

前后版本不一致导致页面无法加载，
![image](https://user-images.githubusercontent.com/25745175/182844617-dc473646-9819-4c39-b11a-c26b23ad4c66.png)

在项目的预览功能中，保存的数据通过 project.exportSchema(TransformStage.Save) 获取，

但在preview页面中project不存在，无法获取  最新的componentsMap信息

类似这个问题：[https://github.com/alibaba/lowcode-engine/issues/457](https://github.com/alibaba/lowcode-engine/issues/457)

也就是升级后旧数据的页面都不能通过preview打开了，必须先用设计器去更新一下componentsMap信息，
请问有什么方式可以解决这个版本升级的问题

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：

## **Expected behavior (required)** / **预期行为（必填，非常重要）**
A clear and concise description of what did you expect to happen. / 请清晰和精确的描述你预期的行为

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by liujuping** [comment]
有可以复现的路径嘛。可以在线上 demo，或者 demo 项目上复现的最好啦。
