### ISSUE TITLE
如何配置左侧扩展区的隐藏以及主内容区在特定场景下禁用删除和拖拽功能

### ISSUE THREAD

**Issue by flingyu** [alibaba/lowcode-engine#908]
![image](https://user-images.githubusercontent.com/30229467/183037399-aae6d1bc-2f94-43ad-9870-fc804fd50924.png)

**Comment by JackLian** [comment]
控制左侧区域隐藏看这个api
https://lowcode-engine.cn/docV2/bv3und#HKUcT

**Comment by JackLian** [comment]
拖拽的禁用控制，需要调整物料描述meta中advanced.onMoveHook，返回false时就是不许移动。动态调整meta可以结合这个API来搞 https://lowcode-engine.cn/docV2/mu7lml#LRXhp

**Comment by JackLian** [comment]
删除的控制，参考https://lowcode-engine.cn/docV2/mu7lml#va9mb

**Comment by flingyu** [comment]
> 删除的控制，参考https://lowcode-engine.cn/docV2/mu7lml#va9mb

谢谢解答～

**Comment by flingyu** [comment]
> 控制左侧区域隐藏看这个api https://lowcode-engine.cn/docV2/bv3und#HKUcT

试了一下用hidePanel并没有生效
![image](https://user-images.githubusercontent.com/30229467/183057554-5aa085bf-7eb5-46a9-9639-ad213206ffbb.png)
