### ISSUE TITLE
win10系统下新建扩展物料后运行项目页面报错

### ISSUE THREAD

**Issue by Carloslst** [alibaba/lowcode-engine#909]
请问下这个问题是什么引起的：在win10系统下根据文档创建扩展物料install后运行完npm run lowcode:dev后控制台没有报错，但是打开页面后报错。
![pic](https://user-images.githubusercontent.com/44060788/183048427-ff8cedc6-1374-4cf5-9af4-2c5076aab817.png)

**Comment by zxy1115769** [comment]
mac下也遇到了同样的报错

**Comment by LeoYuan** [comment]
麻烦将出问题的物料仓库上传 / zip 形式给出~

**Comment by eternalsky** [comment]
看起来接口没有通，node 控制台有什么报错？如果没有的话，考虑网络环境问题。

**Comment by zxy1115769** [comment]
没有用到接口，是写的假数据，就是运行npm run lowcode:dev 打开浏览器控制台就有这个报错，物料都是可以正常展示在面板的 就是一直报下面的错





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "alibaba/lowcode-engine"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年8月19日(星期五) 下午4:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [alibaba/lowcode-engine] win10系统下新建扩展物料后运行项目页面报错 (Issue #909)





 
看起来接口没有通，node 控制台有什么报错？如果没有的话，考虑网络环境问题。

**Comment by Carloslst** [comment]
> 看起来接口没有通，node 控制台有什么报错？如果没有的话，考虑网络环境问题。

我是正常操作按照文档，是mock数据

**Comment by eternalsky** [comment]
@zxy1115769 我说的接口是指的本地起的 node server 提供的接口

**Comment by eternalsky** [comment]
@zxy1115769 @Carloslst 请提供一下 node 控制台的日志，是否有出错。没有的话考虑防火墙屏蔽了 3333 端口
