### ISSUE TITLE
官方文档跳转错误

### ISSUE THREAD

**Issue by twinkle77** [alibaba/lowcode-engine#911]
## **Describe the bug (required)** / **详细描述 bug（必填）**

官方文档跳转错误

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1. 访问 https://lowcode-engine.cn/
<img width="1039" alt="image" src="https://user-images.githubusercontent.com/17792166/183333034-ace6a780-2019-4790-998a-8fb08fed45c3.png">
2. 点击 “快速开始”
3. 跳转错误， 如下图
<img width="1128" alt="image" src="https://user-images.githubusercontent.com/17792166/183333073-ec0bcd22-1038-45ec-8ee6-c8b9ca43b11b.png">

**Comment by JackLian** [comment]
现已恢复，原因是内嵌式的语雀文档被语雀官方限流，后续会切换到其他的文档解决方案上
