### ISSUE TITLE
antd组件库的一些bug/优化建议

### ISSUE THREAD

**Issue by 501981732** [alibaba/lowcode-engine#920]
## **Describe the bug (required)** / **详细描述 bug（必填）**
最近在基于antd组件搭自己的lowcode，发现了几点开源antd-lowcode-materials的几个bug/优化项
A clear and concise description of what the bug is. / 请提供清晰且精确的 bug 描述
1. typography.link/text/paragraph/title 等内容不支持变量绑定
![image](https://user-images.githubusercontent.com/20636097/183548711-18747c34-552e-42c8-934e-d61f8a704d54.png)
![image](https://user-images.githubusercontent.com/20636097/183548763-fe08c763-0317-48f7-bd7a-40542b98b5d5.png)
![image](https://user-images.githubusercontent.com/20636097/183548779-22f4d908-3868-43db-b41b-4ea7b1b528f8.png)

2. typography.title 重要程度setter建议调整为SelectSetter 
3. typography.paragraph setter建议调整为 TextAreaSetter
4. model隐藏底部组件 没有隐藏底部
![image](https://user-images.githubusercontent.com/20636097/183548911-4e987fdc-9780-455a-8c90-42ef65fdefd6.png)

5. skeleton组件默认不展示，并且不支持插槽
![image](https://user-images.githubusercontent.com/20636097/183549026-fea79107-ba8c-490e-b203-2e05151cbaec.png)

刚开始调试，后续调试遇到问题再继续提哈

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - antd-lowcode-materials@1.0.9

**Comment by 501981732** [comment]
如果可以的话，晚点我提个pr改下遇到的几个问题

**Comment by LeoYuan** [comment]
> 如果可以的话，晚点我提个pr改下遇到的几个问题

放手干吧，少年~❤️
