### ISSUE TITLE
数据源面板中的接口列表和接口数据如何获取

### ISSUE THREAD

**Issue by MrShenPH** [alibaba/lowcode-engine#922]
请问数据源面板中配置的的接口列表及接口数据（ID，地址，请求参数，请求方法等）如何获取到呢
<img width="958" alt="image" src="https://user-images.githubusercontent.com/22426016/183616072-5a5a8ec9-21b2-4d52-80a2-59dee712e532.png">

**Comment by liujuping** [comment]
可以看看这个文档，https://www.yuque.com/lce/usage/trgdtr

**Comment by MrShenPH** [comment]
没有太明白需要怎么获取，能劳烦提供一下思路吗
