### ISSUE TITLE
如何在@alilc/element工程中修改webpack配置

### ISSUE THREAD

**Issue by dj49846917** [alibaba/lowcode-engine#926]
我需要在@alilc/element脚手架中设置webpack的externals请问该如何配置呢

**Comment by liujuping** [comment]
可以在 build.json 里面这样配置

![image](https://user-images.githubusercontent.com/11935995/185074152-bf18ec7a-fe4d-424b-b7d4-a23dc96a045c.png)

在 build.plugin.js 就可以修改 webpack 配置。配置参考：https://github.com/neutrinojs/webpack-chain
![image](https://user-images.githubusercontent.com/11935995/185074289-78f8333a-5f9e-4db8-8e7d-2480c231fbc1.png)
