### ISSUE TITLE
如何在已经完成的Demo中添加一个按钮（功能：可以对当前选中的页面进行二次编辑），类似于钉钉宜搭？

### ISSUE THREAD

**Issue by muyinjun** [alibaba/lowcode-engine#928]
老师请教一个问题。如何在已经完成的Demo中添加一个按钮（功能：可以对当前选中的页面进行二次编辑），类似于钉钉宜搭？
<img width="1698" alt="image" src="https://user-images.githubusercontent.com/110951827/183836646-dc57cadf-1fda-4f39-955c-e47629c81f7d.png">

**Comment by wangkangzhen** [comment]
目的是想实现对已完成的页面做二次编辑吗？
可以在editorInit()中通过openDocument()把已保存的数据加载进去，

**Comment by liujuping** [comment]
这个按钮就是在渲染的低代码内容之外自己添加的，和引擎无关，自己项目实现就好。
