### ISSUE TITLE
低代码平台保存函数，会存在问题吗？

### ISSUE THREAD

**Issue by Fuyun791** [alibaba/lowcode-engine#93]
这是一个疑问。就是低代码平台提供了编辑函数的能力，我看了json里面也保存了可执行的函数字符串内容。

我不是特别的了解浏览器安全这块。如果恶意输入一些脚本或者是一些特别的格式。有可能会让服务器执行或者打击到数据库吗？

希望能有人解答

**Comment by alvarto** [comment]
常规意义上的低代码的后端是对 JSON 进行存储和返回，不会去分析执行，因此后端安全相对而言不是很大的问题。

低代码的前端运行时（ http://lowcode-engine.cn/doc?url=oduwl5 ）会尝试展现存储的 JSON，搭配后端请求，因此 XSS 的可能是存在的。

**Comment by LeoYuan** [comment]
我觉得安不安全跟是否是低代码无关，人员 A 做了一个网页，B 将网页发给 C 后，B 借用 C 的身份窃取 C 的数据则是安全问题，比如网页对文本框输入直接存入数据库，或者将 url query 不转义直接放到网页显示等~

低代码提供的函数编辑能力都是为了 A 制作网页，A 自己写 alert 并不能称之为注入攻击，假如 A 的网页将写脚本的能力给了用户 B 并且不安全保存，B 继而转发给 C，这才是安全问题~

**Comment by LeoYuan** [comment]
也不能完全这样理解官方模板 / 私人模板~
模板好比 npm 包，npm 包一样可以埋有问题的脚本，但是你是否从来没有怀疑过 npm 包。。。
不过用之前看一看 JS 内容，或者根据使用量来背书，也不失为一种策略
