### ISSUE TITLE
国际化问题

### ISSUE THREAD

**Issue by zxy1115769** [alibaba/lowcode-engine#932]
![image](https://user-images.githubusercontent.com/39354224/183885484-c79236b9-a20b-439c-bff3-aa6525bb9e1e.png)
demo中切换中英文 只有设置器面板中的属性切换，其他模块内文字没变化，平台国际化问题有什么好的解决方案么？或者相关配置文档提供一下

**Comment by LeoYuan** [comment]
参考文档：https://www.yuque.com/lce/doc/ikdcvk
