### ISSUE TITLE
数据源请求跨域问题

### ISSUE THREAD

**Issue by yangyangdg** [alibaba/lowcode-engine#935]
![1](https://user-images.githubusercontent.com/49295228/184060377-b63f1b37-9086-41e7-b805-0bd56df4ea0b.png)
![2](https://user-images.githubusercontent.com/49295228/184060394-59c4d99c-93f3-495f-8ca4-5db0ed2f3991.png)
已经在数据源请求配置里配置了跨域，但是还是存在跨域问题，服务器端已经做了跨域处理

**Comment by yangyangdg** [comment]
已经解决

**Comment by wang7hang** [comment]
> 已经解决
同样问题怎么解

**Comment by LiCain** [comment]
请问你是怎么解决
