### ISSUE TITLE
如何在获取资产包之后，对物料进行过滤？

### ISSUE THREAD

**Issue by flingyu** [alibaba/lowcode-engine#936]
假设资产包里有button，message、space等组件，
在某种场景下只想渲染button
该如何对物料进行一个条件渲染呢？

**Comment by LeoYuan** [comment]
不太明白问题是啥~

**Comment by oneQiu** [comment]
> 假设资产包里有button，message、space等组件， 在某种场景下只想渲染button 该如何对物料进行一个条件渲染呢？

可以在condition里面做逻辑
