### ISSUE TITLE
数据源无法保存"添加数据处理函数"字段

### ISSUE THREAD

**Issue by pumpkin123** [alibaba/lowcode-engine#937]
## 复现截图
<img width="984" alt="image" src="https://user-images.githubusercontent.com/18691796/184089278-6b8793f0-f608-4ecc-909d-3864ae04b162.png">

## 复现流程与链接
根据1,2,3步骤保存后
<img width="921" alt="image" src="https://user-images.githubusercontent.com/18691796/184089146-59b5c518-7c02-4511-b797-b249bb9b9c48.png">
点击4,5查看，"添加数据处理函数"字段为空，不见了
<img width="984" alt="image" src="https://user-images.githubusercontent.com/18691796/184089278-6b8793f0-f608-4ecc-909d-3864ae04b162.png">

## 期望结果
可以成功保存"添加数据处理函数"字段

## 环境信息

- 引擎版本 1.0.11
- ext 版本 1.0.3
- 物料
  - moment﹫2.24.0
  - lodash
  - iconfont-icons
  - ﹫ant-design/icons﹫4.7.0
  - ﹫alifd/next﹫1.23.0

**Comment by liujuping** [comment]
看看最新版本是否还有问题 @alilc/lowcode-plugin-datasource-pane@1.0.6

**Comment by pumpkin123** [comment]
升级到1.0.6 已解决
