### ISSUE TITLE
npm init @alilc/element demo-material  多包或者单包模式，运行npm run lowcode:dev,页面白屏报错

### ISSUE THREAD

**Issue by wssgchungang** [alibaba/lowcode-engine#94]
### **问题描述：**
npm init @alilc/element demo-material  多包或者单包模式，运行npm run lowcode:dev,页面白屏报错

### **复现流程：**
1. npm init @alilc/element demo-material；
2. 选择多包模式或者单包；
3. yarn install；
4. yarn lowcode:dev；

页面一直在加载中白屏，过段时间控制台报错
### **问题截图：**
![image](https://user-images.githubusercontent.com/29122164/157365177-2724fa96-1b92-4c83-af02-73f339b0ed94.png)

**Comment by duoduoObama** [comment]
同样的问题,使用 npm run lowcode:dev
![image](https://user-images.githubusercontent.com/30836806/157399078-58c4b01d-18ef-4ede-b80b-a6997401c905.png)
找不到文件

**Comment by eternalsky** [comment]
参考 https://www.yuque.com/lce/doc/ulvlkz，windows 开发者请在 WSL 环境中使用。

**Comment by wssgchungang** [comment]
> 
我是在mac上开发的，启动都是正常的，就是在启动完成后页面一直在加载然后报错

**Comment by wssgchungang** [comment]
> 

https://github.com/alibaba/lowcode-engine/issues/94#issuecomment-1062672972

**Comment by wssgchungang** [comment]
> 参考 https://www.yuque.com/lce/doc/ulvlkz ，windows 开发者请在 WSL 环境中使用。

我是在mac上开发的，启动都是正常的，就是启动完成后页面一直在加载中白屏，过段时间控制台报错

**Comment by lijiaxu1996** [comment]
> 

兄弟，你看看我的问题，和你一样的问题
<img width="304" alt="image" src="https://user-images.githubusercontent.com/59685169/157407132-5895ed9a-5485-4588-9d09-0dbcaec9ca10.png">

**Comment by duoduoObama** [comment]
我使用centos7环境启动.
![image](https://user-images.githubusercontent.com/30836806/157408952-6bbbe021-4e74-4f2c-83db-46c1ce2d4598.png)
info ========== start dev all ==========
**WARN CONFIG No webpack config found.**
info @storybook/react v6.4.19
info
info => Loading presets
ERR! Addon value should end in /register OR it should be a valid preset https://storybook.js.org/docs/react/addons/writing-presets/
ERR! [object Object]
info => Loading custom manager config
info => Using implicit CSS loaders
info => Loading custom manager config
info => Using default Webpack4 setup

这个webpack配置会提示找不到的情况.前端也会报错.

**Comment by lijiaxu1996** [comment]
> 我使用centos7环境启动. ![image](https://user-images.githubusercontent.com/30836806/157408952-6bbbe021-4e74-4f2c-83db-46c1ce2d4598.png) info ========== start dev all ========== **WARN CONFIG No webpack config found.** info @storybook/react v6.4.19 info info => Loading presets ERR! Addon value should end in /register OR it should be a valid preset https://storybook.js.org/docs/react/addons/writing-presets/ ERR! [object Object] info => Loading custom manager config info => Using implicit CSS loaders info => Loading custom manager config info => Using default Webpack4 setup
> 
> 这个webpack配置会提示找不到的情况.前端也会报错.

兄弟，cdn那个连接访问不了，我们自己写的前端组件低代码引擎访问不了

**Comment by duoduoObama** [comment]
> > 我使用centos7环境启动.![图像](https://user-images.githubusercontent.com/30836806/157408952-6bbbe021-4e74-4f2c-83db-46c1ce2d4598.png) info ========== 开始开发所有 =========== **警告配置 未找到 webpack 配置。** 信息 @storybook/react v6.4.19 信息信息 => 加载预设 ERR！附加值应以 /寄存器结尾，或者它应该是 ERR https://storybook.js.org/docs/react/addons/writing-presets/ 的有效预设！[对象 对象] 信息 => 加载自定义管理器配置信息 => 使用隐式 CSS 加载程序信息 => 加载自定义管理器配置信息 => 使用默认 Webpack4 设置
> > 这个webpack配置会提示找不到的情况.前端也会报错.
> 
> 兄弟，cdn那个连接访问不了，我们自己写的前端组件低代码引擎访问不了

嗯嗯,这个截图的内容的启动项目我是直接拉的官方:https://github.com/alibaba/lowcode-materials
这个的源码.
刚刚我使用:npm init @alilc/element 创建了个pc-多包组件,也出现你说的cdn资源访问不了的情况了.
![image](https://user-images.githubusercontent.com/30836806/157412564-faf65a9d-0d53-4877-bdaa-328727b5f248.png)

有一说一,确实只有在linux环境中,按语雀的脚手架来启动项目问题会少一点.但是目前依然没有解决根本问题.

**Comment by eternalsky** [comment]
@mark-ck 这个问题也是因为引用了 dev.g 的cdn导致的

**Comment by wssgchungang** [comment]
@mark-ck 
更新完后  现在运行lowcode:dev命令后，脚本执行时间成倍变长了，最后报错了
![image](https://user-images.githubusercontent.com/29122164/157575599-b1d9636d-8455-4fe0-991b-de3a1e670ff0.png)

**Comment by mark-ck** [comment]
> @mark-ck 更新完后 现在运行lowcode:dev命令后，脚本执行时间成倍变长了，最后报错了 ![image](https://user-images.githubusercontent.com/29122164/157575599-b1d9636d-8455-4fe0-991b-de3a1e670ff0.png)

1. 启动时间变长是因为启动时需要安装一些依赖去解析组件代码生成低代码描述，之前 engineScope 是 @ali 会通过内网 npm 安装应该是直接失败了，现在会通过外网 npm 安装可能会比较慢，你最好给 npm 设置默认的 registry （参考这里 https://npmmirror.com/）；
2. 看报错是 @alifd/next/variables.scss 不存在，你检查下 node_modules 里有没有这个包，没有的话重新安装下依赖吧；

**Comment by wssgchungang** [comment]
> > @mark-ck 更新完后 现在运行lowcode:dev命令后，脚本执行时间成倍变长了，最后报错了 ![image](https://user-images.githubusercontent.com/29122164/157575599-b1d9636d-8455-4fe0-991b-de3a1e670ff0.png)
> 
> 1. 启动时间变长是因为启动时需要安装一些依赖去解析组件代码生成低代码描述，之前 engineScope 是 @ali 会通过内网 npm 安装应该是直接失败了，现在会通过外网 npm 安装可能会比较慢，你最好给 npm 设置默认的 registry （参考这里 [https://npmmirror.com/）；](https://npmmirror.com/%EF%BC%89%EF%BC%9B)
> 2. 看报错是 @alifd/next/variables.scss 不存在，你检查下 node_modules 里有没有这个包，没有的话重新安装下依赖吧；

应该是package.json中@alifd/next版本设置有问题,改了版本之后就正常了就安装正常了

**Comment by wssgchungang** [comment]
@mark-ck 
yarn install 之后@alifd/next是正常安装的
![image](https://user-images.githubusercontent.com/29122164/157586244-533ea353-5a0e-49c4-b989-9495859e526a.png)


运行lowcode:dev后就没了
![image](https://user-images.githubusercontent.com/29122164/157586199-07a8b1b9-c120-4119-9c83-54831b3a9ccb.png)

**Comment by wssgchungang** [comment]
@mark-ck 
yarn install 后@alifd/next 安装正常；lowcode:dev后 @alifd/next这个依赖就没了
![image](https://user-images.githubusercontent.com/29122164/157586426-aee019c2-34b3-4b7d-b79c-9277e6fed7a9.png)

**Comment by mark-ck** [comment]
> @mark-ck yarn install 后@alifd/next 安装正常；lowcode:dev后 @alifd/next这个依赖就没了 ![image](https://user-images.githubusercontent.com/29122164/157586426-aee019c2-34b3-4b7d-b79c-9277e6fed7a9.png)

我本地没办法复现这个问题，对一下 node 和 npm 的版本吧

$ node -v
v14.18.1

$ npm -v
8.5.3

**Comment by mark-ck** [comment]
$ yarn -v
1.22.17

**Comment by wssgchungang** [comment]
> $ yarn -v 1.22.17

发现原因了 因为初始化的package里的“devDependencies”和“dependencies”中的@alifd/next、prop-types冲突了，导致安装完依赖后 执行lowcode:dev 直接显示冲突，然后依赖就没了
![image](https://user-images.githubusercontent.com/29122164/157626242-a235e092-158e-4952-b001-51cacc87512e.png)


![image](https://user-images.githubusercontent.com/29122164/157626177-c548d37c-a490-4ec6-98ff-e06487893353.png)

**Comment by mark-ck** [comment]
> > $ yarn -v 1.22.17
> 
> 发现原因了 因为初始化的package里的“devDependencies”和“dependencies”中的@alifd/next、prop-types冲突了，导致安装完依赖后 执行lowcode:dev 直接显示冲突，然后依赖就没了 ![image](https://user-images.githubusercontent.com/29122164/157626242-a235e092-158e-4952-b001-51cacc87512e.png)
> 
> ![image](https://user-images.githubusercontent.com/29122164/157626177-c548d37c-a490-4ec6-98ff-e06487893353.png)

好的，这里的依赖是有问题，而且有好多冗余，我更新下项目模板
