### ISSUE TITLE
官网-「快速开始」重定向异常

### ISSUE THREAD

**Issue by gmqiyue** [alibaba/lowcode-engine#945]
## **Describe the bug (required)** / **详细描述 bug（必填）**

在[官网首页](https://lowcode-engine.cn/)点击「快速开始」按钮，页面重定向到了https://error.taobao.com/app/tbhome/common/error.html

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

Steps to reproduce the behavior: / 详细复现步骤：
1. 打开[官网首页](https://lowcode-engine.cn/)
2. 点击「快速开始」按钮
---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

正常跳转到「快速开始」教程文档页面

---

## **Screenshots (optional)** / **bug 截图（可选）**

<img width="1304" alt="image" src="https://user-images.githubusercontent.com/87467755/184574412-b221adef-9441-42cd-898e-682aa65fa9e6.png">

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**

-
## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by liujuping** [comment]
现在已经恢复。
