### ISSUE TITLE
@alilc/antd-lowcode-materials Form组件渲染异常

### ISSUE THREAD

**Issue by zhoulisuper** [alibaba/lowcode-engine#946]
1、demo项目中使用antd组件情景
2、使用form容器组件 ，保存
3、本地使用渲染render组件进行渲染 报错 
4、报错代码定位图2位置

![image](https://user-images.githubusercontent.com/15810063/184587736-fe765f52-7eba-4ff4-9663-7d1bcefa3258.png)
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/15810063/184587940-8010be2c-ac92-4cc2-8188-e9b8f26ba287.png">

**Comment by b-yp** [comment]
请问这个问题解决了吗，  issue  怎么就关掉了

**Comment by b-yp** [comment]
小弟这里排查下来是 react 版本不一致，官网用的 react 16 而我用的 react 18
