### ISSUE TITLE
【咨询】如何支持PC/移动 双端展示

### ISSUE THREAD

**Issue by bcguan2008** [alibaba/lowcode-engine#947]
问题：

当下多数组件库都会分 PC 和 移动，比如 Antd ，如何编写一个分 PC 和 移动的物料库呢 ？ 

看到 fusion-lowcode-materials 库的 card 组件，是有一个 mobile 文件夹，但貌似没有作用啊
![image](https://user-images.githubusercontent.com/6290186/184601184-98c56113-247d-4be6-85e6-e0ae63b8cc0f.png)

**Comment by LeoYuan** [comment]
建议：
1. 在一套组件库兼容 pc / mobile，对于比较轻量级适配还行；
2. 分开写两套，需要对齐两套的 API；

**Comment by bcguan2008** [comment]
> 建议：
> 
> 1. 在一套组件库兼容 pc / mobile，对于比较轻量级适配还行；
> 2. 分开写两套，需要对齐两套的 API；

这块有推荐文档吗，不清楚 ALEC 的其他搭建平台是否有什么最佳实践。  现在看起来设计器里的区分设备，仍然是一套组件
（可以让组件层感知到 device， 然后根据组件去适配，这个不知道是否合理）

**Comment by LeoYuan** [comment]
https://github.com/alibaba/lowcode-engine/blob/da7f77ee91b3bf441a4a57614872df32d6a1d041/packages/react-simulator-renderer/src/renderer-view.tsx#L245

目前是在组件实现上挂载 Mobile ~

**Comment by bcguan2008** [comment]
> https://github.com/alibaba/lowcode-engine/blob/da7f77ee91b3bf441a4a57614872df32d6a1d041/packages/react-simulator-renderer/src/renderer-view.tsx#L245
> 
> 目前是在组件实现上挂载 Mobile ~

get 多谢
