### ISSUE TITLE
初始化页面，子组件如何自动绑定数据源中的变量

### ISSUE THREAD

**Issue by AndyTiTi** [alibaba/lowcode-engine#949]
## **Describe the bug (required)** / **详细描述 bug（必填）**

项目页面初始化后，子组件如何自动绑定info数据源中的字段 this.state.info.isNewUser，而不用手动进行变量绑定。
### 业务场景：
初始化页面，页面中的所有组件都要根据页面绑定的数据源返回字段进行渲染

例：新用户要渲染三个表单输入项
![image](https://user-images.githubusercontent.com/30618750/184800699-c9dea063-d3e2-4bd4-ad37-651bd9827cf6.png)

老用户只需要输入姓名即可：
<img width="562" alt="image" src="https://user-images.githubusercontent.com/30618750/184800986-fc1cb8f4-fcc4-43ab-a306-fedf357eaa55.png">

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

不用手动进行下面的变量绑定操作，改成自动获取Page当中的state变量
<img width="781" alt="image" src="https://user-images.githubusercontent.com/30618750/184801362-d0a6941b-f5a4-49a0-aa90-a9eb6c697af0.png">

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
引擎版本 1.0.11
ext 版本 1.0.3
物料
moment﹫2.24.0
lodash
﹫alifd/next﹫1.24.18
NextTable﹫1.0.1
﹫alilc/lowcode-materials﹫1.0.2
﹫alifd/pro-layout﹫1.0.1-beta.6
﹫alifd/fusion-ui﹫1.0.5
> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by JackLian** [comment]
绑定动作是发生在设计态，你这里说的是运行态，如果要这个效果，思路要从组件上想办法，将这个获取当前页面上下文数据的能力内置进相关组件里
