### ISSUE TITLE
怎么肥事  "TypeError: Cannot read properties of undefined (reading 'skeleton')"

### ISSUE THREAD

**Issue by Blizzard-liu** [alibaba/lowcode-engine#95]
## **Describe the bug (required)** / **详细描述 bug（必填）**

vue工程  按照步骤通过cdn引入  

"TypeError: Cannot read properties of undefined (reading 'skeleton')"

咋找不到嘞

---

---

## **Screenshots (optional)** / **bug 截图（可选）**
![image](https://user-images.githubusercontent.com/20244432/157365114-7322b4ab-389a-42f7-a8db-d59ef24d6922.png)
![image](https://user-images.githubusercontent.com/20244432/157365233-e666da5c-3208-4166-bd1d-a8eb4a584d2c.png)
![image](https://user-images.githubusercontent.com/20244432/157365307-1d909552-cb2f-41ea-b224-f765c66e94a5.png)

---

**Comment by alvarto** [comment]
目前低代码引擎的执行环境还是 React，Vue 不支持哈，见：https://github.com/alibaba/lowcode-engine/discussions/47

**Comment by Blizzard-liu** [comment]
太让我失望了
