### ISSUE TITLE
[咨询] 想问一下 .tmp 目录下的文件是干嘛的

### ISSUE THREAD

**Issue by iDestin** [alibaba/lowcode-engine#950]
各位大佬问一个小白问题，因为模板生成的文件夹比较多，所以想问一下 .tmp 是干嘛的，dist文件夹又是干嘛的，我们最终使用的是build/render/default/ 文件夹下的文件吗？🙏

![image](https://user-images.githubusercontent.com/36811055/184806598-f020eb75-4c2d-4a58-ba34-d5943b6ff937.png)

**Comment by liujuping** [comment]
最终 npm 用的是 
![image](https://user-images.githubusercontent.com/11935995/185053563-e1245119-f785-450b-9ede-44ce612e59bd.png)

引擎会使用到的文件在 assets-prod.json 中可以看到。
![image](https://user-images.githubusercontent.com/11935995/185053666-002a927a-e991-4184-87be-d9a96c90e93b.png)

其他的文件更多是为了开发需要。
