### ISSUE TITLE
@alifd/build-plugin-lowcode构建产物能否配置目录

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#951]
因为用的是集团的def，但是cdn同步是默认的dist的目录，build下的并不会被同步，有什么配置的方式吗

**Comment by LeoYuan** [comment]
abc.json 里配置一下将 dist 拷贝到 $BUILD_DEST 就好了~

```
{
  "name": "xxx",
  "assets": {
    "type": "command",
    "command": {
      "cmd": [
        "mv dist/* $BUILD_DEST/"
      ]
    }
  }
}

```

**Comment by oneQiu** [comment]
abc.json立马已经用了插件了
{
  "assets": {
    "type": "builder",
    "builder": {
      "name": "@ali/builder-fie4-component"
    }
  }
}

问过def的人，这里只能用一个，这样感觉我必须得自己写构建方法了

**Comment by eternalsky** [comment]
> 

意思是以后不允许写 type: "command" 了，必须使用 builder 构建？

**Comment by eternalsky** [comment]
感觉这不太可能吧，老项目 type: "command" 太多了，难道全迁移，我好像还没看到公告。

**Comment by eternalsky** [comment]
构建目录应该是可以改的，而且这个模板本来也是 fie 组件的初始化模板

**Comment by eternalsky** [comment]
看代码里的话有一个 buildTarget 参数，可以修改构建目录。

**Comment by LeoYuan** [comment]
> 感觉这不太可能吧，老项目 type: "command" 太多了，难道全迁移，我好像还没看到公告。

他意思可能是 command | builder 只能取一个。。。

**Comment by mark-ck** [comment]
@oneQiu 可以这样配置

在 build.lowcode.js 里

![image](https://user-images.githubusercontent.com/44559440/195319146-e9ddebec-42dc-474d-aa8d-d42fd211329b.png)
