### ISSUE TITLE
在demo中扩展插件随便定义一个函数   不支持  async  和await 

### ISSUE THREAD

**Issue by sunhannie** [alibaba/lowcode-engine#953]
## **Describe the bug (required)** / **详细描述 bug（必填）**

在demo中执行npm  run start

```
export default () => {
 const onSelect = async (keys : string[]) => {
    const key: string = keys[0];
    const schema = await getPageSchema(key);
    console.log('schema: ', key);
    // // 加载 schema
    // project.removeDocument(project.currentDocument as any);
    // project.openDocument(schema);
    // config.set('currentPage', key);
  };
  return <>
    <Nav type='line' defaultSelectedKeys={[defaultCurrentPage]} onSelect={onSelect}>
        <Item key="home">首页</Item>
        <Item key="login">登录页</Item>
    </Nav> 
    <Button onClick={openFileCreator}> 新建文件 </Button>
  </>
}
```

```
 const onSelect = (keys : string[]) => {
    const key: string = keys[0];
    const schema = getPageSchema(key);
    console.log('schema: ', key);
    // // 加载 schema
    // project.removeDocument(project.currentDocument as any);
    // project.openDocument(schema);
    // config.set('currentPage', key);
  };
```
不加await   async  不报错，加上报以下错误：

<img width="975" alt="image" src="https://user-images.githubusercontent.com/12994083/185022799-1b8e8d99-e3c8-4af3-a202-11ba3194d56f.png">

后来发现只要改动已经有的代码，比如lowcode-demo/src/universal/utils.ts，这个文件的await都报错

中文版示例：
1. 打开 [demo](http://lowcode-engine.cn/demo)；
2. 点击标题；
3. 在右侧修改标题内容为「修改后的标题」；
4. 渲染画布标题组件没有更新显示为「修改后的标题」；

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

期望能支持await
---

## **Screenshots (optional)** / **bug 截图（可选）**
Sceenshots for further information. (If applicable.) / 一些有用的截图将会帮助我们更好的明确以及定位问题

---

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

## **Additional context (optional)** / **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by liujuping** [comment]
据反馈：把包删除，重新安装就可以了
