### ISSUE TITLE
使用内置设置器，所有icon 无法显示

### ISSUE THREAD

**Issue by dzlhk** [alibaba/lowcode-engine#954]
排查了一下问题，
发现是 lowcode-engine-ext项目中，自定义icon ,window.onload 方法没有执行

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/14235113/185047611-28da1cd4-45d5-4404-b0dc-1863a16c24b1.png">

项目的背景是，在icejs 中使用common.skeletonCabin.Workbench  方式引入的编辑器

**Comment by dzlhk** [comment]
这是出现问题的界面截图
<img width="271" alt="image" src="https://user-images.githubusercontent.com/14235113/185047963-d066cebd-b0cd-4e61-b4c5-fc4ed60e8e54.png">

**Comment by liujuping** [comment]
这个问题可以提个 PR。
