### ISSUE TITLE
lowcode-engine-demo 综合场景 表单容器组件里的Submit和Reset按钮 点击后就出现隐藏bug

### ISSUE THREAD

**Issue by yangyangdg** [alibaba/lowcode-engine#956]
bug复现：
1、拖表单容器组件到画布
<img width="1190" alt="截屏2022-08-17 14 38 53" src="https://user-images.githubusercontent.com/49295228/185053291-bd534547-5f4f-4637-b44d-f2e3670988f0.png">
2、目前Submit和Reset按钮是显示的
<img width="1178" alt="截屏2022-08-17 14 47 39" src="https://user-images.githubusercontent.com/49295228/185053293-b756aaec-125f-471f-9035-27344c8e5a33.png">
3、点击Submit或者Reset按钮，点击的按钮就会看不到了
<img width="1189" alt="截屏2022-08-17 14 50 14" src="https://user-images.githubusercontent.com/49295228/185053711-72ad93eb-adbd-4ded-915b-d33e63a784ce.png">

**Comment by Dogtiti** [comment]
@liujuping 是点击按钮触发了 `ghost`的setter，我记得之前谁提过这个问题，不算是bug，是setter的默认值问题
<img width="1390" alt="image" src="https://user-images.githubusercontent.com/38354472/185083162-26925739-7f0e-4585-ab22-81b191295851.png">

**Comment by liujuping** [comment]
是的，所以我想尝试在这两个物料里面添加 initialValue 看看能不能解决问题。

![image](https://user-images.githubusercontent.com/11935995/185084521-12d8594e-4750-4e63-864f-6fd5f755ea0e.png)
