### ISSUE TITLE
在设计状态时，能否禁用绑定的点击事件

### ISSUE THREAD

**Issue by k55k32** [alibaba/lowcode-engine#957]
目前在设计状态时，类似于按钮组件，点击时会触发onClick绑定的事件。  有些按钮可能会调用远程的接口，文件下载之类的，在设计模式的时候，点击会触发，体验不太好。  有没有办法在设计模式下，不触发组件绑定的事件

**Comment by liujuping** [comment]
可以参考：https://www.yuque.com/lce/doc/xgrv61

**Comment by k55k32** [comment]
这个侵入式太强了呀，需要改很多组件。 现在点击事件应该都是编辑器进行处理然后传递下去的，能不能出一个接口或者拦截器，让我们能够有个地方去统一处理，来修改在编辑模式下的点击表现形式

**Comment by liujuping** [comment]
如果是设计器绑定的 onClick 事件，也可以基于 addPropsTransducer 来处理，设计态用的 TransformStage.Render，可以在这里删除掉 props.onClick。

参考：https://www.yuque.com/lce/doc/dcrbff#SO4No

**Comment by k55k32** [comment]
> 如果是设计器绑定的 onClick 事件，也可以基于 addPropsTransducer 来处理，设计态用的 TransformStage.Render，可以在这里删除掉 props.onClick。
> 
> 参考：https://www.yuque.com/lce/doc/dcrbff#SO4No

可以，这个方案可以，能够解决这个问题！

以下是我写的一个简单的插件，在编辑态态移除组件部分属性。当你不想在编辑状态下，某些属性或者事件被触发时，可以使用此组件。



#### 注册组件
```
await plugins.register(DeletePropsPlugin('onClick', 'onConfirm'))
```

#### DeletePropsPlugin 组件代码
```
import { ILowCodePluginContext } from '@alilc/lowcode-engine'
import { CompositeObject, TransformStage } from '@alilc/lowcode-types'

const DeletePropsPlugin = (...deleteProps: string[]) => {
  const plugin = ({ project }: ILowCodePluginContext) => {
    return {
      name: 'DeletePropsPlugin',
      async init() {
        project.addPropsTransducer((props: CompositeObject): CompositeObject => {
          deleteProps.forEach((key) => {
            delete props[key]
          })
          return props
        }, TransformStage.Render)
      },
    }
  }
  plugin.pluginName = 'DeletePropsPlugin'

  return plugin
}

export default DeletePropsPlugin
```

**Comment by m2maomao** [comment]
DeletePropsPlugin这个只能处理props中绑定的事件吧？如果是第三方组件本身的事件如何在编辑态屏蔽呢？

**Comment by liujuping** [comment]
> DeletePropsPlugin这个只能处理props中绑定的事件吧？如果是第三方组件本身的事件如何在编辑态屏蔽呢？

看一下这个文档：https://lowcode-engine.cn/site/docs/api/configOptions#customizeignoreselectors---%E7%82%B9%E5%87%BB%E5%BF%BD%E7%95%A5
