### ISSUE TITLE
按照官网教程“开发一个自定义物料”,执行npm run lowcode:dev之后控制台如下报错

### ISSUE THREAD

**Issue by DittoShang** [alibaba/lowcode-engine#960]
一、在node版本是18.7.0情况下，出现如下报错

PS E:\lowcode-engine\lowcode-demo\my-material> npm run lowcode:dev

> my-material@0.1.0 lowcode:dev
> build-scripts start --config ./build.lowcode.js

@alib/build-scripts 0.1.32
0: D:\DesignProgramFiles\nodejs\node.exe
1: E:\lowcode-engine\lowcode-demo\my-material\node_modules\@alib\build-scripts\bin\child-process-start.js
2: start
3: --config
4: ./build.lowcode.js
_componentViews:  []
in render view:  false
                                         11% buildingi ｢wds｣: Project is running at http://0.0.0.0:3333/    
i ｢wds｣: webpack output is served from undefined
i ｢wds｣: Content not from webpack is served from E:\lowcode-engine\lowcode-demo\my-material
node:internal/crypto/hash:71
  this[kHandle] = new _Hash(algorithm, xofLen);
                  ^

Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:133:10)
    at module.exports (E:\lowcode-engine\lowcode-demo\my-material\node_modules\webpack\lib\util\createHash.js:135:53)

    at NormalModule._initBuildHash (E:\lowcode-engine\lowcode-demo\my-material\node_modules\webpack\lib\NormalModule.js:417:16)
    at handleParseError (E:\lowcode-engine\lowcode-demo\my-material\node_modules\webpack\lib\NormalModule.js:471:10) 
    at E:\lowcode-engine\lowcode-demo\my-material\node_modules\webpack\lib\NormalModule.js:503:5
    at E:\lowcode-engine\lowcode-demo\my-material\node_modules\webpack\lib\NormalModule.js:358:12
    at E:\lowcode-engine\lowcode-demo\my-material\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (E:\lowcode-engine\lowcode-demo\my-material\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (E:\lowcode-engine\lowcode-demo\my-material\node_modules\loader-runner\lib\LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}

Node.js v18.7.0

二、在node版本是14.5.0情况下，出现如下报错
PS E:\lowcode-engine\lowcode-demo\my-material> npm run lowcode:dev

> my-material@0.1.0 lowcode:dev E:\lowcode-engine\lowcode-demo\my-material
> build-scripts start --config ./build.lowcode.js

@alib/build-scripts 0.1.32
0: D:\DesignProgramFiles\nodejs\node.exe
1: E:\lowcode-engine\lowcode-demo\my-material\node_modules\@alib\build-scripts\bin\child-process-start.js
2: start
3: --config
4: ./build.lowcode.js
_componentViews:  []
in render view:  false
                                         11% buildingi ｢wds｣: Project is running at http://0.0.0.0:3333/
i ｢wds｣: webpack output is served from undefined
i ｢wds｣: Content not from webpack is served from E:\lowcode-engine\lowcode-demo\my-material
                                         34% building_componentViews:  []
in render view:  false
                                         100%
info WEBPACK Hash: ce76eee51bc11bf79c70
info WEBPACK Version: webpack 4.46.0
info WEBPACK Child
info WEBPACK     Hash: ce76eee51bc11bf79c70
info WEBPACK     Time: 4632ms
info WEBPACK     Built at: 2022/08/22 上午10:21:08
info WEBPACK                                                                   Asset      Size
                                 Chunks                   Chunk Names
info WEBPACK         E:\lowcode-engine\lowcode-demo\my-material\.tmp\default.view.js   355 KiB  E:\lowcode-engine\lowcode-demo\my-material\.tmp\default.view  [emitted]        E:\lowcode-engine\lowcode-demo\my-material\.tmp\default.view
info WEBPACK     E:\lowcode-engine\lowcode-demo\my-material\.tmp\default.view.js.map   399 KiB  E:\lowcode-engine\lowcode-demo\my-material\.tmp\default.view  [emitted] [dev]  E:\lowcode-engine\lowcode-demo\my-material\.tmp\default.view
info WEBPACK                 E:\lowcode-engine\lowcode-demo\my-material\.tmp\meta.js   362 KiB          E:\lowcode-engine\lowcode-demo\my-material\.tmp\meta  [emitted]        E:\lowcode-engine\lowcode-demo\my-material\.tmp\meta       
info WEBPACK             E:\lowcode-engine\lowcode-demo\my-material\.tmp\meta.js.map   404 KiB          E:\lowcode-engine\lowcode-demo\my-material\.tmp\meta  [emitted] [dev]  E:\lowcode-engine\lowcode-demo\my-material\.tmp\meta       
info WEBPACK                                                           designer.html    10 KiB
                                         [emitted]
info WEBPACK                                                              index.html  10.1 KiB
                                         [emitted]
info WEBPACK                                                                index.js   478 KiB
                                  index  [emitted]        index
info WEBPACK                                                            index.js.map   491 KiB
                                  index  [emitted] [dev]  index
info WEBPACK                                                            preview.html  1.45 KiB
                                         [emitted]
info WEBPACK                                                              preview.js  2.55 MiB
                                preview  [emitted]        preview
info WEBPACK                                                          preview.js.map  2.65 MiB
                                preview  [emitted] [dev]  preview
info WEBPACK                                                                 view.js   355 KiB
                                   view  [emitted]        view
info WEBPACK                                                             view.js.map   399 KiB
                                   view  [emitted] [dev]  view
info WEBPACK     Child html-webpack-plugin for "designer.html":
info WEBPACK                 Asset     Size  Chunks  Chunk Names
info WEBPACK         designer.html  548 KiB       0
info WEBPACK     Child html-webpack-plugin for "index.html":
info WEBPACK              Asset     Size  Chunks  Chunk Names
info WEBPACK         index.html  548 KiB       0
info WEBPACK     Child html-webpack-plugin for "preview.html":
info WEBPACK                Asset     Size  Chunks  Chunk Names
info WEBPACK         preview.html  539 KiB       0
ERR! (undefined) ./.tmp/meta.js
ERR! Module not found: Can't resolve 'E:lowcode-enginelowcode-demomy-materiallowcodemy-materialmeta' in 'E:\lowcode-engine\lowcode-demo\my-material\.tmp'
ERR!
ERR! (undefined) ./.tmp/view.js
ERR! Module not found: Can't resolve 'E:lowcode-enginelowcode-demomy-materialsrcindex.scss' in 'E:\lowcode-engine\lowcode-demo\my-material\.tmp'
ERR!
ERR! (undefined) ./.tmp/default.view.js
ERR! Module not found: Can't resolve 'E:lowcode-enginelowcode-demomy-materialsrcindex.scss' in 'E:\lowcode-engine\lowcode-demo\my-material\.tmp'
ERR!
ERR! (undefined) ./.tmp/view.js
ERR! Module not found: Can't resolve 'E:lowcode-enginelowcode-demomy-materialsrcindex.tsx' in 'E:\lowcode-engine\lowcode-demo\my-material\.tmp'
ERR!
ERR! (undefined) ./.tmp/default.view.js
ERR! Module not found: Can't resolve 'E:lowcode-enginelowcode-demomy-materialsrcindex.tsx' in 'E:\lowcode-engine\lowcode-demo\my-material\.tmp'

**Comment by liujuping** [comment]
如果是 window 环境可以看看这个：https://www.yuque.com/lce/doc/glgn4a

**Comment by DittoShang** [comment]
> 如果是 window 环境可以看看这个：https://www.yuque.com/lce/doc/glgn4a

感谢，已用wsl解决
