### ISSUE TITLE
添加Tab组件，出码报错

### ISSUE THREAD

**Issue by yangyangdg** [alibaba/lowcode-engine#961]
bug重现：
1、拖Tab组件到画布
![1661154344363](https://user-images.githubusercontent.com/49295228/185867461-5b658a06-e1f9-4da7-9b05-8603106e9c94.jpg)
2、出码报错
![image](https://user-images.githubusercontent.com/49295228/185867623-3d3621c7-9f3f-4b87-aa79-82cb8c7ad2a5.png)

**Comment by LeoYuan** [comment]
后面跟进 #1565 吧，本 issue 将关闭~
