### ISSUE TITLE
【文档】文档点击锚点跳转后滚动条失效

### ISSUE THREAD

**Issue by dabuside** [alibaba/lowcode-engine#965]
## **Describe the bug (required)** / **详细描述 bug（必填）**

文档点击锚点跳转后滚动条失效

---

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

1. 打开 https://lowcode-engine.cn/docV2/dcrbff
2. 点击右侧目录区面板如`index`锚点
3. 右侧目录区面板无法滚动

---

## **Expected behavior (required)** / **预期行为（必填，非常重要）**

可以正常滚动

## **Screenshots (optional)** / **bug 截图（可选）**

![51j0dKzWsf](https://user-images.githubusercontent.com/7280952/186058748-bb81a243-68d9-49bd-a05e-c488e341ff5b.gif)

## **Environments (please complete the following information) (required):** / **请提供如下信息（必填）**
win 10
chrome Version 104.0.5112.102 (Official Build) (64-bit)

**Comment by liujuping** [comment]
这个已经替换成新的文档系统了。

https://lowcode-engine.cn/site/docs/specs/lowcode-spec
