### ISSUE TITLE
出码之后引入的依赖不正确

### ISSUE THREAD

**Issue by versole** [alibaba/lowcode-engine#967]
![image](https://user-images.githubusercontent.com/36833118/186130914-e88c12b4-c09f-4877-a967-fc059af442cf.png)
Can't resolve '@seada/antd-materials/src/index.tsx' 我看@seada/antd-materials/src/index.tsx不存在。打包过后没有这个目录。

**Comment by zackxizi** [comment]
@versole 将  lowcode/ProTable/meta.ts 中npm.main 改为空字符 即可
