### ISSUE TITLE
数据源使用webscoket怎么实现呢 大佬们

### ISSUE THREAD

**Issue by Blizzard-liu** [alibaba/lowcode-engine#97]

**Comment by Blizzard-liu** [comment]
有没有大佬回复下

**Comment by Blizzard-liu** [comment]
在线等大佬回复

**Comment by JackLian** [comment]
数据源部分主要是定义请求地址和响应的生命周期回调，这个目前还主要是http类的协议，ws的形式从协议层面还没做过支持，也没见过类似实现，想要实现的话可以基于引擎做扩展，将ws的请求信息通过数据源定义出来（现有协议做扩展），然后渲染态做响应的处理。

**Comment by Blizzard-liu** [comment]
那想要实现定时刷新数据怎么实现呢

**Comment by JackLian** [comment]
这场景说真的是真没见过....所以也不好揣测，但大概是需要render中实现一个相应插件，用于数据的收发，并触发界面的数据刷新

**Comment by Blizzard-liu** [comment]
场景就是 图表类的数据需要定时刷新

**Comment by Blizzard-liu** [comment]
场景就是 图表类的数据需要定时刷新

**Comment by JackLian** [comment]
如果这个平台专门是做实时数据大屏或者大盘的话，确实可以从平台级提供ws数据源的支持，当然建设成本也稍高一点，如果只是有这个场景，但也不是很多，也可以考虑将ws的支持做在组件级，这样成本会小很多

**Comment by Blizzard-liu** [comment]
好的 谢谢 组件级实现思路是什么呢

**Comment by JackLian** [comment]
比如组件定义一个数据源的prop，里面是ws请求相关的配置，搭建时候可以手动配上。更进一步可以把这部分能力抽象一个util，所有需要ws能力的图表组件可以集成这个util。
