### ISSUE TITLE
antd formily场景下出现表格无法横向滚动问题

### ISSUE THREAD

**Issue by dingyanhe** [alibaba/lowcode-engine#970]
## 复现截图
- 如下图：第一栏设置了 200px
- 第二栏设置了 5000px
- 第三栏 设置了 200px + 固定右侧
- 未出现滚动
![image](https://user-images.githubusercontent.com/26290798/186135447-f1c3c5c7-caa2-49d1-b67e-fe83a83d54e3.png)

## 复现流程与链接
- [demo](https://lowcode-engine.cn/demo/antd-pro-with-formily.html)
- 物料搜索“表格”
- 新增加一列“操作”
- 设置宽度“200”，固定在右侧
- 将其他两个列分别设置为200px及5000px
- 表格右侧未固定“操作”列

## 期望结果
“操作”列固定在右侧

## 环境信息

- 引擎版本 1.0.11
- ext 版本 1.0.3
- 物料
  - moment﹫2.24.0
  - lodash
  - iconfont-icons
  - ﹫ant-design/icons﹫4.7.0
  - antd﹫4.19.5
  - ﹫alifd/next﹫1.24.18
  - ﹫alilc/antd-lowcode-materials﹫1.0.6
  - ﹫seada/antd-materials﹫0.1.1
  - ﹫seada/formily-materials﹫0.1.1

**Comment by liujuping** [comment]
这个问题可以到这边提问哈

https://github.com/seada-low-code/lowcode-ecology/tree/main/packages/formily-materials
