### ISSUE TITLE
modifyBuiltinComponentAction方法有问题

### ISSUE THREAD

**Issue by yz1311** [alibaba/lowcode-engine#973]
## **详细描述 bug（必填）**

官方文档
https://lowcode-engine.cn/docV2/mu7lml#va9mb

```
import { material } from '@alilc/lowcode-engine';

material.modifyBuiltinComponentAction('remove', (action) => {
  const originAction = action.content.action;
  action.content.action = () => {
  	console.log('before reomve!');
    originAction();
    console.log('after remove!');
  }
});
```

可以对remove行为进行拦截，但是实际因为无法获取到node，会直接报错
```
{
    name: 'remove',
    content: {
      icon: IconRemove,
      title: intlNode('remove'),
      /* istanbul ignore next */
      action(node: Node) {
        node.remove();
      },
    },
    important: true,
  },
```

## ***预期行为（必填，非常重要）**
运行正常

**Comment by liujuping** [comment]
material.modifyBuiltinComponentAction('remove', (action) => {
  const originAction = action.content.action;
  action.content.action = (node) => {
  	console.log('before reomve!');
    originAction(node);
    console.log('after remove!');
  }
});

即可，文档已更新。
