### ISSUE TITLE
如何删除Component Not Found的组件

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#974]
因为迭代更新，删除了某个组件，但是有些页面依然有，所以出现了组件不存在的内容，我期望是希望能够点击然后支持我删除。但是发现并不能点击这个组件。
![image](https://user-images.githubusercontent.com/50658231/186590866-2a3d1376-85e9-4a94-836c-c753b5ffcee9.png)

**Comment by dingyanhe** [comment]
左侧有个大纲列表，可一试试里面能不能找到对应的节点

**Comment by oneQiu** [comment]
> 左侧有个大纲列表，可一试试里面能不能找到对应的节点

能找到，但是点击了依旧不能出现删除操作，或者说能否在大纲的组件旁加上删除按钮？

**Comment by chvin** [comment]
同样的问题，对于没有找到组件，也应该支持选中删除，类似这样
![image](https://user-images.githubusercontent.com/5383506/188460378-5546a10f-f5f6-4c28-bd80-4053878ec7ed.png)
