### ISSUE TITLE
如何通过assets.json文件获取componentsMap对象

### ISSUE THREAD

**Issue by yz1311** [alibaba/lowcode-engine#977]
## **详细描述 bug（必填）**

在demo中，componentsMap是通过前面保存在localStorage中的，但是现在只有assets.json文件的话，如何获取到componentsMap对象?

## **预期行为（必填，非常重要）**

---

## **请提供如下信息（必填）**
 - AliLowCodeEngine version: [e.g. 1.0.0] / 低代码引擎版本
 - AliLowCodeEngineExt version: [e.g. 1.0.0] / 低代码引擎扩展包版本
 - Browser [e.g. chrome, safari] / 浏览器版本
 - materials / plugins / tools / 其他物料 / 插件 / 工具链版本

> (this information can be collected via [the manual plugin](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png) / 版本信息可[通过低代码用户手册插件收集](https://img.alicdn.com/imgextra/i1/O1CN0115zonY1IsgbkZ2ir7_!!6000000000949-2-tps-3066-1650.png))

##  **更多额外信息（可选）**
Any other context of the problem here. / 可以追加更多的额外信息，帮助定位问题

**Comment by liujuping** [comment]
根据 assets.json 的 components 获取。可以参考资产包协议： https://lowcode-engine.cn/assets
