### ISSUE TITLE
有没有一种模式 可以让布局任意拖拽 

### ISSUE THREAD

**Issue by Blizzard-liu** [alibaba/lowcode-engine#98]
有没有一种模式 可以让布局任意拖拽  类似这样  https://woai3c.github.io/visual-drag-demo/#/

**Comment by Blizzard-liu** [comment]
在线等大佬回复

**Comment by JackLian** [comment]
自由布局，目前官方并没有提供，也暂无提供的计划，欢迎大家来贡献~

**Comment by LeoYuan** [comment]
假如想做个简单的绝对布局，对每个节点设置 position: absolute 以及跟随拖拽属性设置相应的 top / left，不失为一种简单解法~
