### ISSUE TITLE
数据源没有回显

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#982]
以前就存在的bug，之前看已经修复了，但是刚才在demo上试了下，还存在这个问题。

1. 创建数据源以后，保存页面，然后重新进入页面，打开数据源面板没有出现，关闭面板重新打开就会出现

[之前的iss](https://github.com/alibaba/lowcode-engine/issues/533)

**Comment by liujuping** [comment]
这个问题我尝试重新构建了，还是不生效，我猜测和请求时机有问题。这个我找人再帮忙看看。
