### ISSUE TITLE
编辑页面右侧的属性编辑框是否可以用户自行调节大小。

### ISSUE THREAD

**Issue by Sarali2022** [alibaba/lowcode-engine#983]
当属性是数组类型，展示核心列比较多时，好多信息都隐藏了，是否可以用户调整右侧边的大小进行编辑
<img width="1475" alt="image" src="https://user-images.githubusercontent.com/104294827/187165604-6aacab97-6696-4486-91a3-afb60549679a.png">

**Comment by liujuping** [comment]
可以尝试自定义 Setter，或者给已有的 Setter 增加参数并提 PR，比如支持数组类型折叠展开，默认展示多少个等等。

如果只是字体大小，还是会隐藏，调整的意义不大。
