### ISSUE TITLE
@alilc/lowcode-renderer-core 包依赖的 moment.js 的用途是？

### ISSUE THREAD

**Issue by twinkle77** [alibaba/lowcode-engine#984]
## **Describe the bug (required)** / **详细描述 bug（必填）**

@alilc/lowcode-renderer-core 包依赖的 moment.js 似乎没用？ 全局搜索，没有搜索到使用场景

源码：

<img width="1426" alt="image" src="https://user-images.githubusercontent.com/17792166/187203865-3d27d6c3-7ca9-4ab8-863c-fee0da5c356a.png">

打包体积：

<img width="1104" alt="image" src="https://user-images.githubusercontent.com/17792166/187204129-7a7e7904-bc4c-4e86-820f-ac1c8243127c.png">

可以看到 moment.js 占用的 @alilc/lowcode-renderer-core 包的 99% 的体积

@alilc/lowcode-renderer-core 总包 670，moment 独占 669

## **To Reproduce (required)** / **如何复现 bug？（必填，非常重要）**

源码位置： https://github.com/alibaba/lowcode-engine/blob/main/packages/renderer-core/src/utils/common.ts#L12

**Comment by alvarto** [comment]
我理解如果没有遇到问题，可以拿掉。对 moment 的使用集中于UI 部分（skeleton / setter），主要是经由 fusion next 间接依赖

**Comment by twinkle77** [comment]
@alvarto 我去试试把他拿掉跑跑看

**Comment by alvarto** [comment]
好奇一下，为何要单独打 @alilc/lowcode-renderer-core？低代码编辑器的使用就 4 个包够了

- 用于引擎的 @alilc/lowcode-engine
- 用于扩展的 @alilc/lowcode-engine-ext
- 用于编辑器中画布的 @alilc/react-simulator-renderer
- 用于直接渲染的 @alilc/react-renderer

在这四个包里做好 external 也还好

**Comment by alvarto** [comment]
了解了，你可以可以拿掉试试。

我一直是维护者之一，不存在换人哈
