### ISSUE TITLE
dumi下使用低代码包

### ISSUE THREAD

**Issue by oneQiu** [alibaba/lowcode-engine#986]
因为需要把页面渲染封装成组件，所以在dumi里面封装了组件渲染，但是报未定义错
![image](https://user-images.githubusercontent.com/50658231/187339333-d0a8767a-b802-407c-a550-05246a0a25c7.png)

**Comment by liujuping** [comment]
看一下这个：https://www.yuque.com/lce/doc/reh10c

**Comment by oneQiu** [comment]
> 看一下这个：https://www.yuque.com/lce/doc/reh10c

![image](https://user-images.githubusercontent.com/50658231/187397552-3d824de9-f33f-463b-9b65-a7fec5412071.png)
尝试过了，不知是不是因为在dumi的情况下会这样

**Comment by liujuping** [comment]
![image](https://user-images.githubusercontent.com/11935995/189320091-a0a08cee-47b6-4544-b35c-872d7842b3bb.png)

不知道这个能不能解决问题。

**Comment by LeoYuan** [comment]
externals 配置没有成功吧。。。
