### ISSUE TITLE
「咨询」区块开发 & 区块源码

### ISSUE THREAD

**Issue by xiaoqian-GUO** [alibaba/lowcode-engine#987]
## **Describe the bug (required)** / **详细描述 bug（必填）**

想咨询下区块如何开发，以及现在的区块源码是开源的吗，所在仓库是哪个呢

---

**Comment by twinkle77** [comment]
b 站有视频可以参考下

**Comment by xiaoqian-GUO** [comment]
> b 站有视频可以参考下

能发下相关链接吗

**Comment by xiaoqian-GUO** [comment]
> 



> b 站有视频可以参考下

@alifd/pro-layout 这个能开源吗

**Comment by twinkle77** [comment]
@xiaoqian-GUO  https://live.bilibili.com/6848714

**Comment by twinkle77** [comment]
> > 
> 
> > b 站有视频可以参考下
> 
> @alifd/pro-layout 这个能开源吗

这个我不清楚哦 建议去钉钉群问问

**Comment by LeoYuan** [comment]
暂时不开源，假如需要参考部分逻辑的实现，可以看该 npm 里的 es 部分代码~

**Comment by xiaoqian-GUO** [comment]
> 暂时不开源，假如需要参考部分逻辑的实现，可以看该 npm 里的 es 部分代码~

好的 谢谢
