### ISSUE TITLE
rax启动不起来

### ISSUE THREAD

**Issue by Sarali2022** [alibaba/lowcode-engine#992]
背景描述：
希望低代码平台生成小程序和app应用，目前尝试用低代码平台生成H5,在小程序或者app中嵌套，测试过之后，加载和交互相关的和原生的差距有点大，下载rax的组件尝试，没有启动成功，尝试改lowcode-demo环境，仍然失败。

说下lowcode-demo修改步骤如下：
环境：
lowcode-demo：  "version": "1.0.25",
修改内容：
1、修改index.ts
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/104294827/187584394-f9cb897b-6af4-42b6-9d6c-b9094c461d04.png">
2、去掉无用的物料
<img width="1300" alt="image" src="https://user-images.githubusercontent.com/104294827/187584518-99f1fd7f-08ea-4816-9b39-fffb1400a4df.png">
启动时报错信息
<img width="1297" alt="image" src="https://user-images.githubusercontent.com/104294827/187584605-7507cf0d-d1e4-4843-8de7-30fe4beb47db.png">
尝试的事项
解压rax-simulator-renderer.js,解压包不可用。

能否提供一个rax的demo？

**Comment by liujuping** [comment]
资产包上加上 lodash 试一下呢。

**Comment by Sarali2022** [comment]
加了
<img width="707" alt="image" src="https://user-images.githubusercontent.com/104294827/187585777-6d472f3c-8fd4-42f2-a1e1-d402d97dbc1c.png">
依赖里面也加了

报找不到
index.js:13 Uncaught TypeError: Cannot read properties of undefined (reading 'Component')
错误信息：
<img width="1190" alt="image" src="https://user-images.githubusercontent.com/104294827/187585727-a477200d-f369-423f-9335-8a713b51bdcd.png">

**Comment by liujuping** [comment]
加一下 rax 的 cdn 资源。

**Comment by Sarali2022** [comment]
是这个地方加吗？
<img width="1004" alt="image" src="https://user-images.githubusercontent.com/104294827/187591020-39722feb-e4d9-42b1-962c-8330225eb6ff.png">
报了这个错误
<img width="824" alt="image" src="https://user-images.githubusercontent.com/104294827/187591131-87e62446-7299-43ba-b67f-b9d1b3426ed9.png">

**Comment by Sarali2022** [comment]
加到这个地方也是报错
<img width="1174" alt="image" src="https://user-images.githubusercontent.com/104294827/188055755-3acc66b3-499f-4e35-987e-dfc1e5c84256.png">
报错信息
<img width="990" alt="image" src="https://user-images.githubusercontent.com/104294827/188055804-c530f8a2-897b-4c67-8f8b-dde81f67ad1b.png">

**Comment by Sarali2022** [comment]
@liujuping  这是我修改的代码，麻烦帮忙看看了，谢谢啦。
[Uploading lowcode-demo.zip…]()

**Comment by liujuping** [comment]
![image](https://user-images.githubusercontent.com/11935995/188348203-21807370-5147-474b-8f06-a1300fdf12f7.png)

这里顶部加上

{
      "package": "rax",
      "version": "1.2.2",
      "urls": "https://cdnjs.cloudflare.com/ajax/libs/rax/1.2.2/rax.umd.js",
      "library": "Rax"
},
