### ISSUE TITLE
JSSlot 会渲染一个额外的容器 lc-container，影响设计时的布局

### ISSUE THREAD

**Issue by haoziqaq** [alibaba/lowcode-engine#993]
我把官方最新的的ant-design物料(v1.0.10)fork到我本地进行维护和构建，导入构建出来的物料协议之后发现 JSSlot 会渲染一个影响布局的 lc-container 容器

![image](https://user-images.githubusercontent.com/24223652/187594090-b52cb304-af1e-41e6-a11c-fb6d95ba81f1.png)

这是怎么回事呢，希望能得到解答。

**Comment by haoziqaq** [comment]
引擎版本1.0.12

**Comment by haoziqaq** [comment]
目前我是从 lowcode-materials，fork过来的仓库，进入antd物料包里装好依赖，然后把package.json的name改成了别的名字（其他什么都没动），然后跑lowcode:dev命令，渲染结果就成这样了，目前不知道是什么原因。希望解惑。

**Comment by liujuping** [comment]
这是设计态下的 JSSlot 组件，在没有子元素的时候，起到让用户知道这里可以拖拽进去元素的提示作用。

**Comment by haoziqaq** [comment]
可是组件已经拖进来了，他就不该继续存在了呀，而且渲染态的时候，他依然存在不知道怎么回事。

而且您看看这个问题，也挺奇怪

> 目前我是从 lowcode-materials，fork过来的仓库，进入antd物料包里装好依赖，然后把package.json的name改成了别的名字（其他什么都没动），然后跑lowcode:dev命令，渲染结果就成这样了，目前不知道是什么原因。希望解惑。

**Comment by haoziqaq** [comment]
在我没改包名之前，他的渲染是符合期望的。改了包名就出问题了

**Comment by haoziqaq** [comment]
复现仓库: https://github.com/haoziqaq/lowcode-materials

复现步骤
1. cd packages/antd-lowcode-materials
2. yarn
3. yarn lowcode:dev

**Comment by LeoYuan** [comment]
已经确认问题了，目前有两种方案：
1. antd-lowcode-materials 已经定制了 Slot 组件，[参考代码](https://github.com/alibaba/lowcode-materials/blob/main/packages/antd-lowcode-materials/lowcode/slot/view.tsx)，注入这个组件，将会覆盖内置的 Slot 组件；
2. 将内置的 Slot 组件移除 .lc-container 这一层结构；

建议你先用方案1，方案2我们同步修改~

**Comment by haoziqaq** [comment]
非常感谢

---原始邮件---
发件人: "LeoYuan ***@***.***&gt;
发送时间: 2022年9月8日(周四) 中午11:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;非常
主题: Re: [alibaba/lowcode-engine] JSSlot 会渲染一个额外的容器 lc-container，影响设计时的布局 (Issue #993)




 
已经确认问题了，目前有两种方案：
  
antd-lowcode-materials 已经定制了 Slot 组件，参考代码，注入这个组件，将会覆盖内置的 Slot 组件；
 
将内置的 Slot 组件移除 .lc-container 这一层结构；
  
建议你先用方案1，方案2我们同步修改~
