### ISSUE TITLE
npm run lowcode:dev 不会自动生成lowcode文件

### ISSUE THREAD

**Issue by zhouxiny1** [alibaba/lowcode-engine#994]
![image](https://user-images.githubusercontent.com/111745349/187649087-7c2c7f26-6842-47d7-8c4e-b5d30e603cd7.png)
使用组件转为低代码的方式，之前会自动生成lowcode文件，把lowcode文件删除后再执行就不会自动生成文件

**Comment by eternalsky** [comment]
本地测试没有这个问题，lowcode:dev 可以在没有 lowcode 文件夹的情况下重新生成，请检查一下 build-plugin-lowcode 版本是否为最新

**Comment by LeoYuan** [comment]
没有问题的话先关了哈~
